### ISSUE TITLE
Signal-Android fails to sanitize unicode in URLs domains

### ISSUE THREAD

**Issue by ortegaalfredo** [signalapp/Signal-Android#10069]
- [* ] I have searched open and closed issues for duplicates
- [ *] I am submitting a bug report for existing functionality that does not work as intended
- [ *] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ *] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal-Android fails to sanitize unicode in URLs, specifically in the domain.

### Steps to reproduce
- Copy the following URL and paste it into a message for a group or a private message using Signal-Desktop (Note: the URL contains a u+FFF0 unicode. Github will also convert it to an hyperlink, this is in itself unsafe behavior and likely another bug):

www.innofensiveLinknot￰Malicious.com

- Send the message containing the malicious URL to the victim using the Signal-Desktop client (victim must be using the Signal-Android client). This is important, as the Signal-Android client will sanitize the link before sending it, but Signal-Desktop will not. All Signal clients for Android will detect the unicode u+FFF0 and wont convert the URL to hyperlink, but the string after the unicode character "malicious.com" will still be recognized as a hyperlink. Signal will then show a notification for the whole "www.innofensiveLinknotMalicious.com" and a button to open the link.

-  When you press the notification button, the user will open the link "malicious.com" in the browser, instead of "www.innofensiveLinknot￰Malicious.com"

**Actual result:** Sending a specially crafted URL the user will be asked to open "www.innofensiveLinknot￰Malicious.com" but instead the link "Malicious.com" will be opened.

**Expected result:** The user opens the link "www.innofensiveLinknot￰Malicious.com"

### Screenshots

![index](https://user-images.githubusercontent.com/1576696/95527651-4d400c00-09ac-11eb-9fb5-048a072ef1d2.jpeg)
![index2](https://user-images.githubusercontent.com/1576696/95527662-58933780-09ac-11eb-83f4-a2f297ee2005.jpeg)

### Device info

**Device:** Samsung S10
**Android version:** 10.0.0
**Signal version:** 4.71.5

### Additional info

Using this technique you can cut links in several parts, for example:

www.g￰oogle.co￰m

This malicious link will open "oogle.co" in the Signal-Android message notification dialog.

**Comment by ortegaalfredo** [comment]
Related to https://github.com/signalapp/Signal-Desktop/issues/4568

**Comment by richardddd98** [comment]
This is a huge security issue. This should have maximum priority.

**Comment by richardddd98** [comment]
I tried these links with Huawei Browser and it redirects to "about:blank#blocked" instead of the actual link, I guess due to the Unicode character

**Comment by greyson-signal** [comment]
It seems like this issue is stating that Signal-Android is handling these links properly in-app, but that the smart reply the OS constructs for our notification (i.e. the 'Open link' button) is deceptive?

If that's an accurate statement, I suggest you open a bug against Android. We don't create that 'open link' button -- the OS does.

**Comment by ortegaalfredo** [comment]
It makes sense, but I couldn't reproduce this particular notification bug using Whatsapp, Telegram o other messengers. Also, it only works using Singal-Desktop as the source. Perhaps Signal-Android is sanitizing the URL before sending it to the network?

**Comment by HacKanCuBa** [comment]
> It makes sense, but I couldn't reproduce this particular notification bug using Whatsapp, Telegram o other messengers. Also, it only works using Signal-Desktop as the source. Perhaps Signal-Android is sanitizing the URL before sending it to the network?
> Edit: Could reproduce in Slack, so I think you are correct. Still, perhaps Signal could implement a workaround.

If Signal-Android is sanitizing the message before sending then the workaround would be to do the same in Signal-Desktop and every other Signal apps. The Android bug would still be there but at least somewhat controlled.

**Comment by greyson-signal** [comment]
Android does not change any message contents on inbound or outbound messages. All we do is change how things are rendered -- inside the app. 

I also don't know what your testing methodology is -- sending the aforementioned link from Android -> Android can still produce the 'open link' smart notification button, whereas you said you couldn't reproduce it that way.

There's a lot of black box stuff happening here with the notification system, and the behavior even sounds OEM-specific, with Huawei doing different things than stock Android. I'm guessing one reason your test results may be inconsistent is because of your pre-existing notification state (sometimes different notification actions are visible based on how many notifications you have) as well as differences between OEMs. 

I still believe the targets of your bug report are the OEM's themselves.
