### ISSUE TITLE
[Solved] Emoji picker missing search button

### ISSUE THREAD

**Issue by cobordism** [signalapp/Signal-Android#10073]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the android app, the emoji picker is lacking the (magnifying-glass) search tab that make it easy to find emoji

### Steps to reproduce
I use a google free android like e.foundation.
I installed Signal App 4.71.5 (7082)
I start typing a message, I select emoji, I have to scroll through all emoji searching for the one I want.
The little search tab that I have on the signal desktop app is missing in the android app.
No typing on the keyboard brings up any emoji selection. The only way to select an emoji is to scroll through all of them and search visually.

**Actual result:** The search tab is missing on the android app and there  is no way to search for emoji by text. 
**Expected result:** I either expect there to be a search tab (like in the desktop app) or for emoji to be suggested as I type. However neither is the case.

### Screenshots

![1024-2048-max](https://user-images.githubusercontent.com/12838530/95659486-b8f7b580-0b21-11eb-8603-947b06e45d4a.png)
![Screenshot_Signal](https://user-images.githubusercontent.com/12838530/95659570-3d4a3880-0b22-11eb-8254-f3e3b5e673f4.png)

### Device info

**Device:** Fairphone FP3
**Android version:** 9 (/e/ version 0.11-p.2020083170821-stable-FP3 )
**Signal version:** 4.71.5 (7082)

**Comment by cobordism** [comment]
The desktop app by comparison:
![Screenshot from 2020-10-10 17-59-51](https://user-images.githubusercontent.com/12838530/95659639-a3cf5680-0b22-11eb-956b-9a38d6c274c5.png)
![Screenshot from 2020-10-10 17-59-58](https://user-images.githubusercontent.com/12838530/95659640-a467ed00-0b22-11eb-8a3d-e9cff8a62570.png)

Note the search tab (top left). This is what is missing on the android app.

**Comment by Nisc3d** [comment]
There is no emoji search on Signal for Android, so that is not a bug, but a feature request and should be discussed on the forum here: https://community.signalusers.org/t/emoji-search-in-emoji-picker/1700

**Comment by cobordism** [comment]
How is it not a bug? the button (that I know is there because I can see it on the desktop)  is not showing and not clickable on the phone. 
Unless you are saying that it is deliberately so and they want all phone users to have to manually scroll through all emoji.. but that would make no sense whatsoever.

**Comment by Nisc3d** [comment]
Yes there is this button on the desktop, but it is not there on the phone, because it doesn't exist for everyone. I think not, that they deliberately want that all phone users scroll through all emoji, but they just prioritize some new features over others. As a workaround you can use a keyboard with emoji search.

**Comment by cobordism** [comment]
Ok.I suppose I could do that.
Which keyboard should I install?
Note: I have no google account so please don’t suggest an app that is only in the google store.

Further question:
Will your keyboard work with all the languages I have set up? The spelling checkers? Because ideally I do not want to have to set everything up again if I can avoid it.

**Comment by condemnedmeat** [comment]
> Ok.I suppose I could do that.
Which keyboard should I install?
Note: I have no google account so please don’t suggest an app that is only in the google store.
>
> Further question:
Will your keyboard work with all the languages I have set up? The spelling checkers? Because ideally I do not want to have to set everything up again if I can avoid it.

I have searched on your behalf cobordism.

I believe this :arrow_down:, is compatible with your wish list.

![emoji+keyboard+pro+top](https://user-images.githubusercontent.com/42522540/95687556-c9786080-0bf3-11eb-9bc9-81217c7601ed.jpg)

As you can see, it is very practical. I guarantee you will stand out, using this keyboard.

![_86493540_emoji4](https://user-images.githubusercontent.com/42522540/95687267-093e4880-0bf2-11eb-8a44-62b80d635588.jpg)

My friend, whose first language is emoji, uses this keyboard. He is not allowed out unsupervised.

I should note that my research has led me to believe my phone cannot install this keyboard :disappointed:, so I cannot be sure it will work on your phone. Try `adb install physical_emoji_keyboard.apk` before opening an issue would be my advice. I look forward to an update on your efforts.

I won't be upset though if you decide to instead look around for yourself. Good-luck! :+1:

**Comment by rossmacarthur** [comment]
Just downloaded Signal (on Android) and immediately encountered that searching emojis does not exist :+1:

**Comment by cobordism** [comment]
It is no longer relevant and can be marked as solved and closed.
