### ISSUE TITLE
Sending media files in Signal reboots phone (sic!)

### ISSUE THREAD

**Issue by filipzarzynski** [signalapp/Signal-Android#10167]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

**It's not a joke**

### Bug description
My phone reboots while or shortly after sending media messages in Signal

### Steps to reproduce
- Send Photo(s) or Video(s) in Signal conversation
- about 1 in 3-5 cases the phone reboots while sending message or shortly after

**Actual result:** Phone reboots, 
**Expected result:** Phone keeps working (?)

### Device info
**Device:** Samsung SM-A605FN
**Android version:** 10 (A605FNXXU6CTH1, QP1A.190711.020.A605FNXXU6CTH1) (stock and up to date)
**Signal version:** 4.75.4 (7281) (up to date with google pay store)

### Link to debug log
https://debuglogs.org/96612d8d6cd658c6af86d0b169e9f03657fe973aca6a035b779b5fb09041e8eb (created after reboot but containing some Signal crash logs)

### Additional info
- sometimes while sending media messages Signal freezes and can only be reopened after making it force close 
- phone does 'soft-reboot' (it goes blank, then straight to system decryption animation - It does not ask for encryption key)

It does not reproduce on 4 different phones I have on hand (including pixel 4 with userdebug OS) (same media files used).
About 50% ot the time after reboot the message is not sent, but in other cases it is, seemingly at random

I'm android OS security engineer, and have never seen anything like that on prod os builds, except for proof of vulnerability apps that triggered watchdog bite or kernel panic (but even then it was not skipping encryption key boot phase). It's unlikely but possible that it's SMPL (Sudden Momentary Power Loss) issue as it's 2yo phone but that would mean that Signal is overly exhausting system resources while sending media. 
Unfortunately I'm not fluent in userland apps so I was unable to debug it myself. 
I'm posting issue here instead to manufacturers support page as it's only occurring while or shortly after (up to 30s) using Signal, making me assume it's not generic OS issue but somehow Signal bug or bug triggered explicitly by Signal app.
Issue started appearing last week, phone was charged to at least 40% every time, it occurs both while using Wi-Fi and on mobile data.
Feel free to close if debug logs do not show any clear signs of issue source or if you think it's OS bug.

**Comment by richardddd98** [comment]
May I ask you what the source of these media files is? Locally taken photos and videos or retrieved from the Internet/another device?
Also, if it was SMPL wouldn't the probability of occurrence depend on the battery level? If you have your phone at 40% on battery does it occur with the same probability as with your phone at 100% and running from AC adapter?

Anyway, I saw a similar behavior on a Samsung Galaxy Tab S3 while using ffmpeg. If I try to convert a long video to AV1 codec, after some minutes the tablet would reboot. The wrapper application for ffmpeg has only storage permission, and Android version is 9 with March 2020 level security patches. Something similar happened also on my older Samsung Galaxy S4 while running some tasks of a distributed computing project on BOINC (Rosetta@home if I recall correctly), after some time the phone would just reboot. Never went deep into these issues, but my first guess was one of the following:
1) Some faulty CPU instruction sequence (in particular maybe something related to CPU acceleration instructions for media files; these applications try to exploit them to speed up computation). Some CPUs historically had bugs which allowed for the system to hang if some instructions were triggered in a particular sequence. See for example: https://www.techpowerup.com/268479/intel-ice-lake-cpus-have-a-system-crashing-bug: "It seems like the IntelliJ IDE has a specific sequence of instructions that trigger Ice Lake CPUs to crash OS."
2) Some kind of bug on CPU scheduler which caused the system to hang and a watchdog timer which would reboot the system, due to the high CPU usage and multithread occupancy by ffmpeg

Hope this might provide some possible clues and help further investigating this issue

**Comment by filipzarzynski** [comment]
@richardddd98 

**Media files additional info:** Issue occurred both with local photos and/or videos (most of cases) as well as external photos (memes :)).
In all but one case after reboot (or two) I was able to successfully send those messages (if they where not successfully send in the firs try, the one resulting in reboot).
One and only case when I was not able to send media in second/third try (it hung for more than 5 min and I had to force close the app) it was about 20 freshly taken photos so I dismissed it as probably related to size of message and successfully send them in batches.

**SMPL:** Theoretically yes, but I've seen cursed things in past few years including SMPL on device powered from high-end lab DC power supply (although I was working on late pre-production hardware)

**Other remarks:** 
/0. Tab S3 (assuming stock OS) might have older versions of native media codecs that tended to do that in some cases...
/1. From quick search Signal seams to not use asm optimisations in code. As far as I know Java code should not be able to create faulty CPU instructions causing OS reboot, it could cause at max Android Runtime crash, that would look something like reboot, but then (to the best of my knowledge) decryption animation would not show. Also there seams be no conversion going on while sending media files so media codes as faulty as they are should not be triggered differently in Signal than for ex. Gallery/Photos app that does not cause issues.
/2. Watchdog is my best bet at this point (unfortunately on prod device with user OS I cannot access dmesg to check for it, and I cannot tamper with this device on that level)

**Comment by DrMcCoy** [comment]
I too had that happen just now on my Nokia 7.2 with Android 10

Sending images, even just viewing the gallery, has been really buggy the past...two weeks? I click the + to send a photo, and sometimes the image preview don't load, they just stay black. Opening up the gallery, the preview stay black. Sometimes, they do load after a whole minute, often they don't.

When I then just try to send a photo, it stays there, black screen with a spinner, for minutes at a time. Even so long that the screen locks again. I can sometimes force Signal to stop, but sometimes even that doesn't work and just now my phone outright rebooted when it couldn't be stopped.

**Comment by DrMcCoy** [comment]
Here's how it looks (the grey is where I redacted a few things, that's not a bug). As you can see, the preview does load for three of the images eventually, just when sending them, but not for the last one. It's a bit random.

![Screenshot_20201118-183011](https://user-images.githubusercontent.com/156130/99566194-dfd0c380-29cc-11eb-80b7-9669ad30719f.png)
![Screenshot_20201118-183023](https://user-images.githubusercontent.com/156130/99566207-e2331d80-29cc-11eb-93eb-b4405d383c0e.png)
![Screenshot_20201118-183031](https://user-images.githubusercontent.com/156130/99566217-e4957780-29cc-11eb-8e5d-633289570953.png)
![Screenshot_20201118-183055](https://user-images.githubusercontent.com/156130/99566225-e6f7d180-29cc-11eb-873e-a2e7272dc91c.png)

**Comment by filipzarzynski** [comment]
@DrMcCoy Exactly the same thing happens in my case.
If I recall correctly reboots seams to be negatively corelated with that 'blank preview' issue. If I get preview instantly then it sometimes reboots but if I see blank squares instead of pictures it takes some time to load but does not reboot (as far as I remember). 

As it happens I have Nokia 7.2 on hand, but when I was testing it before submitting issue I was not able to recreate issue.
What got my attention is number of photos you have on your device (3k in 'all media'), on my Samsung SM-A605FN I have something in 1-2k range.
It might be a lead.

My previous failed reproduction tests on different phones included max 30 images on device (always on freshly wiped device) , so I will redo them later with few thousands images loaded to device.
I can also flash Nokia 7.2 and Pixels with userdebug aosp-gsi OS, maybe hack stock system images to catch dmesg just before reboot.
I will try to spare few hour during this weekend to do so.
