### ISSUE TITLE
Photo picker should use more standard Android interface

### ISSUE THREAD

**Issue by luser** [signalapp/Signal-Android#10170]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The Signal photo picker, accessed by tapping the blue + button, then the "gallery" icon, only shows photos on the local device. The Android system photo picker UI allows choosing photos from other apps such as Google Photos and Google Drive. I have photos organized into albums in Google Photos and it's difficult or impossible to find them using the existing Signal photo picker.

### Steps to reproduce
- Tap + button next to text input
- Tap "Gallery" icon

**Actual result:** Signal shows a list of albums on the local device.
**Expected result:** Signal opens system photo picker, or offers an option to do so.

### Screenshots
For comparison, the Twitter Android app shows a similar UI to Signal, but has a dropdown menu with a "More..." item:
![Screenshot_20201106-092523](https://user-images.githubusercontent.com/286001/98377233-8e125b80-2012-11eb-8ec0-d2b8ac6747d4.png)

Clicking that item opens the system photo picker:
![Screenshot_20201106-092602](https://user-images.githubusercontent.com/286001/98377277-9bc7e100-2012-11eb-940e-c760b9a2cd9a.png)

I assume this is using the ["Use the system picker"](https://developer.android.com/training/data-storage/use-cases#media-import-system) functionality described on the Android developer site.

### Device info

**Device:** Google Pixel 4a
**Android version:** 11
**Signal version:** 4.75.4

**Comment by EmberHeartshine** [comment]
+1. It's frankly absurd how little integration Signal has on Android. Only a few updates ago did it change over to using the standard Android biometric auth instead of its own internal solution.

On top of this, Android's media cache doesn't update as frequently as it should, so picking recent items can be a challenge unless you use a different gallery app and send a share intent.

**Comment by EmberHeartshine** [comment]
This issue is still present.

**Comment by rohieb** [comment]
This would be great to have. I wonder if it could also help with issues like #10394

**Comment by EmberHeartshine** [comment]
This is a bug, unless not being able to pick images between MediaStore refreshes is the intended behavior.

**Comment by luser** [comment]
I consider this a bug, since Signal works differently than almost every other Android app I use.

**Comment by firefoxlover** [comment]
Instead of reworking the internal Gallery, Signal should not use it at all. Please just use the AOSP photo picker portal, it works great and means Signal doesnt need any filesystem access.

This is crucial for security, least privilege.

Please. It even saves you maintenance work.

![gif](https://developer.android.com/static/images/training/data-storage/photo-picker-multiselect.gif)
