### ISSUE TITLE
Add support for sending multiple files (like PDFs) [Feature Request]

### ISSUE THREAD

**Issue by mandarpatkar** [signalapp/Signal-Android#10231]
It is very tedious to send each file one-by-one, it would be great to have this feature.
Thanks !

**Comment by SomeGuru** [comment]
Totally agree with @mandarpatkar here... If even maybe a way to cue up the uploads that could be sent one by one, but chosen as a grouping of files to send to someone, be it Files, Images, Videos. Doing 1 by 1 is time consuming and sometimes repeated items sent because of failure to see a view of the previously sent files.

Thanks,
SomeGuru

**Comment by Genis-Sage** [comment]
hey @mandarpatkar and @SomeGuru 
Signal devs reserved the Github issue tracker for bug

feature requests should be placed on https://community.signalusers.org/

there's already a feature request for it:
https://community.signalusers.org/t/sending-multiple-attachments-at-once/2459/146
