### ISSUE TITLE
Can Signal Android/Apple relay messages back to desktop application?

### ISSUE THREAD

**Issue by SomeGuru** [signalapp/Signal-Android#10232]
I have Android, my co-worker has Apple, and we can both use the desktop application between our home networks. What we don't seem to be able to do is get all the messages coming into Signal Phone applications to relay into the Desktop application for those not using Signal... We have asked them to use it, however some just will not... So is there a way to relay the phone app messages back through the signal Desktop application and respond accordingly? Also I cannot seem to find a Proxy location for the application, is there one that we can apply so the corporate networks can use the desktop application over proxy servers?

Thanks,
SomeGuru

**Comment by hiqua** [comment]
Regarding synchronization of SMS/MMS on Signal-Desktop there's already an issue open there: https://github.com/signalapp/Signal-Desktop/issues/3225 (honestly I don't expect it to ever happen but who knows, in any case it's not happening soon).

Regarding proxy issues try to check the forum, I see that there's some information there for instance: https://community.signalusers.org/t/desktop-client-proxy-problems/2164/7

For features requests or support you'll have better luck using https://community.signalusers.org/ instead of the Github issues (which are meant for bug reports).
