### ISSUE TITLE
[5.0.1] - Back ups got turned off, SMS texts not sending

### ISSUE THREAD

**Issue by jaredsburrows** [signalapp/Signal-Android#10270]
App Version:
 - 5.0.1

Issues:
 - Back ups got turned off?
 - SMS texts not sending - stuck in "pending"

I have read the following:
 - https://support.signal.org/hc/en-us/articles/360009303072-Troubleshooting-sending-messages

**Comment by jaredsburrows** [comment]
This happened after upgrading the app. 

I had to manually turn on back ups again and I had to set the default "Messages" app to texting default and then set it to Signal back again to get it to work.

**Comment by mentalisttraceur** [comment]
Same "SMS stuck in pending" issue, except changing the default SMS app back and forth didn't fix it, and I don't know when/if Signal auto-updated and if an update directly caused it.

What I do know is that it started last night, seemingly spontaneously, and it happened literally in between a couple of messages - I had sent three messages within a few seconds of each other and then looked away (switched to another app). When I next checked, the first went through, but the next two got stuck in pending. Every message since then is also stuck in pending.

Receiving messages in the meantime still works fine. But every SMS I've tried sending since this started has gotten stuck in pending.

It's not just a visual bug - the messages are actually never making it to the other person.

(I haven't checked what's going on with backups.)

**Comment by Tursko** [comment]
Possibly the issue? 
https://9to5google.com/2020/12/09/carrier-services-sms-android-issue/amp/

**Comment by therriault** [comment]
Had the same issue with SMS not sending, started yesterday and none of the usual fixes (deleting pending messages, clearing cache, force quitting, restarting phone) made any difference. Solved it by enabling the default Android messaging app (which I'd previously disabled) and the texts immediately caught up. No idea of the mechanism but easy thing to try.

**Comment by mentalisttraceur** [comment]
Okay so I can also now confirm that it specifically has to be the included-with-Android messaging app. In my previous message on this issue, I had tried toggling it to another app that could also work as the default SMS app, and that didn't help at all. But re-enabling the stock Android messaging app and making that one the default fixed the issue immediately.

**Comment by jaredsburrows** [comment]
@mentalisttraceur I was just about to comment and say the same thing. Enabling the default messaging app on the Pixel 4 seems to remedy the issue. I wonder if this a "system default"s kind of issue? I am not sure why I get some texts and some not.
