### ISSUE TITLE
GV1 Migratuon capability not refreshing

### ISSUE THREAD

**Issue by Leptopoda** [signalapp/Signal-Android#10286]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As said in the [forum](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-0-release/18811/140?u=leptopoda)  all my devices are on a gv1 migration capable Version (i've updated my iPad to 5.0.2 since then) but still my `gv1 migration` capability is on not supported. Although my gv1 migration feature flag is true.
```
====== CAPABILITIES =======
-- Local
GV2          : true
GV1 Migration: true

-- Global
GV2          : SUPPORTED
GV1 Migration: NOT_SUPPORTED
```

I guess this is a Server problem and reminds me of a [bug on some non play services devices where this behaviour happened on gv2 rollout](https://community.signalusers.org/t/beta-testing-the-new-gv2-groups-big-signal-group-with-as-many-volunteering-forum-members-as-possible/17030/37?u=leptopoda).
(2 other accounts without play services and no linked devices worked with the migration though)

### Device info

**Device:** Xiaomi mi a3 
**Android version:** 10 (linrage os 17.0)
**Signal version Android:** 5.0.4
**Signal version iOS:** 5.0.2
**Signal version Desktop:** 1.39.2

### Link to debug log

**Android:** https://debuglogs.org/1415a09698464e74d6a464c4aa532aeefbcdd65f7f43d18828d5d2aeb36b7336
**IOS:** https://debuglogs.org/11a9631451c42c14abd1a124e803201353cf4d3f2a476c80ea45f22ae7419f8f.zip
**Desktop:** https://debuglogs.org/64edd0b26e7d6248c463807bef3c912148d0ca8bb6bbe658cb1ab5e93d666f41

**Comment by andhmak** [comment]
I have a similar problem. My desktop client has been update to 1.39.2 for some time, and I just updated the android app to the 5.0.5 production version. The android's debug log reads as such:

```
====== CAPABILITIES =======
-- Local
GV2          : true
GV1 Migration: false

-- Global
GV2          : SUPPORTED
GV1 Migration: NOT_SUPPORTED
```

**Comment by Leptopoda** [comment]
There seems to be a fix on the forum 
https://community.signalusers.org/t/upgrade-legacy-group-to-groups-v2-or-move-chat-history-to-new-group/16201/59?u=leptopoda

**Comment by greyson-signal** [comment]
@andhmak 
> and I just updated the android app to the 5.0.5 production version

We only refresh feature flags every 2 hours. Can try restarting the app and see if it updates?

**Comment by bme13** [comment]
For one device in my family the global GV1 Migration remains not supported. The update was received yesterday and I restarted the phone multiple times. There is no linked device. Here's the logfile. https://debuglogs.org/8dcb89f21e578a7be1697cc18984e782abd6e6dc133febf06a1e35d7fd69655a
Just a question, is it possible that some groups are migrated and others not if that flag says migration is not supported. There is one group on that device that now is gv2. It was created back in November and I'm pretty sure it was a gv1 back then but now I'm starting to doubt about that.

**Comment by Leptopoda** [comment]
@bme13 

>  I'm pretty sure it was a gv1 back then but now I'm starting to doubt about that.

![Uploading Screenshot_20201215-212419_Signal.png…]()

You should se something like there when migration happened.

**Comment by Leptopoda** [comment]
Update to 5.0.7 fixed my capabilities

@greyson-signal shall we close this?

**Comment by bme13** [comment]
@Leptopoda. Thanks, didn't see that migration message so I assume it was a v2 group after all.

**Comment by bme13** [comment]
I'm not sure if it's worth to look into this any further but it still doesn't work for this one account in my family. Here are a few additional logs. 
https://debuglogs.org/40925ef56fb86fac98034ce79c8589fc44227ada8f42956c62c9407b866bf7a7
https://debuglogs.org/861ca329683ba15cb40f198509934a2070fc371c1114362b4d681e8e6736f5ef
Some additional information. I've installed Signal on this phone a few weeks ago (approx 04-12) and during that installation I've restored an backup file. 
In one of the debuglogs of yesterday (https://debuglogs.org/78dec52514cb1a4a58e191240443c29013d343ba3a20276baa6e7f8a241104f9) I've found this line:
5.0.7 2020-12-16 12:26:02.626 CET W GroupsV1MigrationUtil: Profile sharing is disabled! Can't migrate.
Based on that I've looked a bit closer and found one archived group that showed a group request message. (Not sure why since that was an very old test group.) So I assumed the migration failed due to that. Yesterday I've accepted that group request but until now still no luck in getting that global GV1 Migration flag.
As said I'm not sure if more information is needed otherwise I will remove this installation and reinstall Signal (or just wait for the manual upgrade)

**Comment by greyson-signal** [comment]
@bme13 Can you try blocking someone (anyone), and then checking to see if you have the capability? You can unblock them immediately afterwards. Blocking is just a trigger to refresh your account attributes, which I'm worried didn't happen when you got the feature flag.

**Comment by bme13** [comment]
Yes, that did the trick indeed. Thanks.
