### ISSUE TITLE
Signal hangs and freezes at certain times

### ISSUE THREAD

**Issue by sivaraam** [signalapp/Signal-Android#10284]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In some cases when I try to leave a chat immediately after sending a message, Signal hangs with a blank page link the one seen below:

![Screenshot_2020-12-12-23-14-26](https://user-images.githubusercontent.com/12448084/101992717-42229880-3cdb-11eb-8a0e-79c2bf8d5065.png)

Removing Signal from recent apps and trying to open it doesn't fix it. I only see a blank white screen at that point like the one below (note: I have Screen Lock turned on).

![Screenshot_2020-12-12-23-14-41](https://user-images.githubusercontent.com/12448084/101992728-51a1e180-3cdb-11eb-97ff-3cd896b783fb.png)

I have to "Force stop" Signal to be able to open the app again.

I've been observing this since 4.79.

### Steps to reproduce
Not sure about the specific steps to reproduce this but it always happen when I leave a conversation.

**Actual result:** I see blank conversation list screen and the profile photo that appears in the top-left is also missing.

**Expected result:** I'm able to see the conversation list properly and the app works as usual.

### Device info

**Device:** Samsung SM-J111F
**Android version:** 5.1.1
**Signal version:** 5.0.4

### Link to debug log
https://debuglogs.org/e2bdb810840dcf55193c7054ba21fa78d8216330df21cd34992e31bdde9e9b81

**Comment by gab81** [comment]
hi, i can feel you, again, this was happening today - today i had low signal in a shop, and "signal" couldn't get a phone or audio call no matter what!

**Comment by richardddd98** [comment]
It happens to me too if I send and receive simultaneously messages in a couple of long conversations, which are affected by the slowness issue #9930. But it is very rare. I think it might be some kind of race condition and then deadlock. You can fix it by killing the application and running again. Anyway, since the last 2 months with the latest updates it seems this issue is gone, or maybe I've been lucky and it didn't happen to me just for case.

@sivaraam @gab81 Do you have any chat affected by this issue of the slowness? Do you think my hypothesis can also apply to your case?

**Comment by gab81** [comment]
hi, to be honest i dont use for signal that much for messaging right now, mostly for audio and video call that i want to be encrypted so i cannot tell, so far they are OK, few times they do not get delivered.

Actually today, i mentioned earlier, that i was in really low reception, well Signal would not really even deliver messages, audio calls would not connect (with ringing on my side) and video calls not working at all.

On the other hand, whatsapp connected (very choppy but worked) and so was audio call.. so it seems that if you don't have high enough bandwidth Signal does not even connect, not even messages.

I guess it's using more bandwidth due to the higher encryption and have to say that video calls look very sharp in Signal. on the other hand, seems bad if you either have low reception or if your network is not fast enough.

**Comment by zyklon-b** [comment]
I believe I'm suffering from the same bug.

There's anywhere from 10-120 second delay when sending texts. It freezes when going in and out of conversations. I'm trying to avoid signal on the Android app as much as possible and utilizing Signal Desktop because of it...I just don't know what else to do :(

**Comment by richardddd98** [comment]
@zyklon-b The issue you're describing seems more similar to #9930. Here we're talking about an issue that forces you to kill Signal and start it again, otherwise it won't work. The other issue (#9930) is about slowness, there it is described an issue where Signal is slow and you have to wait in order to receive and send messages in some conversations. You don't have to kill Signal, you only have to wait. Am I misunderstanding?

**Comment by gab81** [comment]
in my opinion the fact that it doesn't connect is pretty serious, after all it's such a basic thing. and also to connect you if connection is a bit slow would also be better,...it sems as thought it only connects if you have super uber bandwidth, for example Whatsapp connected me on an occasion where signal wouldn't. it was choppy video but it worked.

**Comment by ph00lt0** [comment]
@richardddd98 I doubt this is the case. I have this issue in https://github.com/mollyim/mollyim-android/issues/20 returning after a day of usage in a clean database since last update. Conversations are not so long that this should cause any issues. I think this is a very critical bug in terms of user experience.
