### ISSUE TITLE
After disabling Signal's "Other" type of notifications in Android, outgoing call notifications are missing

### ISSUE THREAD

**Issue by marcel263** [signalapp/Signal-Android#10327]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using Signal 5.0.8 without Play Services. When making a call while "Other" is disabled as a notification category in Android, there does not appear an in-call notification to hang up, check call status, etc. Notifications for outgoing calls should be grouped under "Calls" and not "Other"

### Steps to reproduce
- In Android settings, find notification settings for Signal
- Disable "Other"
- Call someone, then immediately go to home screen. 

**Actual result:** Instead of having the expected notification item, nothing appears
**Expected result:** Have all calling notifications be managed by the "Calls" group of notifications, so that disabling "Other" does not mistakenly disable in-call notifications

### Device info

**Device:** Samsung A series
**Android version:** Android 10, OneUI 2.5 November 2020 Update
**Signal version:** 5.0.8.

**Comment by w1bsb** [comment]
I can confirm the same behavior is exhibited on my device. I'm using a Pixel 4 with CalyxOS but chose to use Websockets for notifications instead of GCM/FCM.  I have the "Other" category disabled to suppress the background connection persistent notification. When I make a call on Signal, I cannot see the "in progress" notification so that I can easily toggle back to the call if I move to the home screen or perform another action.

@cody-signal do you think it would be possible to either move the "call in progress" notification into its own notification category or possibly even move the websocket persistent notification "Background connection enabled." into its own category so users can easily choose to suppress this message if using websockets?  I'm not sure how complex the android notification category system is but it seems like this should be fairly trivial to do and would eliminate this problem for the few having it now, and future users as well.

**Comment by w1bsb** [comment]
Just saw commit notes that the background connection has been moved to its own category from version 5.32.10 on. The Play Store version has this change. Confirmed working on a backup phone -- with Background connection notification channel turned off, In progress call notification works. Thanks @cody-signal

**Comment by marcel263** [comment]
Dear commenter yes it has been fixed

with thanks to developers and contributors
