### ISSUE TITLE
Chat keeps jumping to new/latest messages while I am still reading old messages

### ISSUE THREAD

**Issue by cjk28** [signalapp/Signal-Android#10332]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Chat keeps jumping to new/latest messages while I am still reading old messages

### Steps to reproduce
- receive several (e.g. 50)  messages from a group chat while you don't have the app open (e.g. device locked)
- click on the notification for the chat from android notification shade
- start reading messages
- someone in group sends new message

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- signal jumps to the bottom/new/latest message

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- scroll position should not change
### Device info

**Device:** Nokia 5.3
**Android version:** 10
**Signal version:** 5.0.8

### Link to debug log

https://debuglogs.org/2d0b55995068e5c8e91ece4efc4230fcaf2cc13e59e1b2fb41aa9f90e8b08edc

I believe the issue only happens after opening signal from a notification, rather than opening the app from the app drawer. Similarly, if I have induced the bug, when I switch to the app via the recent apps switcher, the issue also persists.

**Comment by RandolphNimmer** [comment]
I believe this is the same bug: https://github.com/signalapp/Signal-Android/issues/10114

**Comment by cjk28** [comment]
Looks different, mine jumps straight to the latest message whereas that one just seems juddery

**Comment by RandolphNimmer** [comment]
Gotcha. I can say, I have been having both issues on my device. I guess I assumed they are two symptoms of the same bug, but maybe not.

**Comment by kanylbullen** [comment]
I have this constantly. I'm on beta version. 5.0.8. App is completely unusable in active groups.

**Comment by makchamp** [comment]
Hello,
So I have found a 'fix' to this problem however I do not think it is the most optimal solution. I will explain why.
For context, this bug is actually very easily reproducible for me. All I need to do to trigger it on my device (S10) is:

1. Scroll up in a decently(~100+) long conversation (doesn't matter if its groups or not)
2. Exit the conversation (using the back button works)
3. Go back into the conversation and begin scrolling down

At some point the chat will jump to the very bottom (the top of the RecyclerView). This happens very consistently (almost every time I try to reproduce following these steps).

While debugging I noticed that this behaviour only happens when messages are being loaded back in. If all the messages have already been loaded, the chat will never 'jump'. 

Looking in the file `ConversationFragment.java`,
The adapter's data observer  is  `ConversationSnapToTopDataObserver` 

The area of interest is specifically the overridden method `onItemRangeInserted()` on line 1461.
```    
    @Override
    public void onItemRangeInserted(int positionStart, int itemCount) {
      if (positionStart == 0 && itemCount == 1 && isTypingIndicatorShowing()) {
        return;
      }

      super.onItemRangeInserted(positionStart, itemCount);
      getListAdapter().notifyDataSetChanged(); // Change HERE
    }
```
This is the callback is for inserted messages. Calling `notifyDataSetChanged();` on the adapter in here will stop the jumping behaviour. While this appears to work it has some drawbacks. 
It will cause some minor blinking or flickering as you scroll down when new messages are inserted. This is because "LayoutManagers will be forced to fully rebind and relayout all visible views".  This is why google only recommends to use [notifyDataSetChanged](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#notifyDataSetChanged()) as a last resort. The more logical alternative would be to use `notifyItemInserted(positionStart, itemCount)`. It does seem more natural to do so in here given that the callback pertains to only a certain range of items and not the entire list. However doing this does did not work for me. I did not go much deeper than that with the time I had. 

As to why this works, it's clear that the scroll's position is not being properly maintained when new items are inserted. Calling `notifyDataSetChanged` will refresh it properly, however I do not believe it to be the most optimal solution. Maybe the devs can comment further on this. 

For now I will use this temporary fix as the trade-off is well worth it for me.

**Comment by mrd** [comment]
I am experiencing the same issue most of the time. Except one time today something slightly different happened. I was trying to read through 'today's messages and instead of unexpectedly jumping to the latest one, it actually jumped to 'yesterday's messages that I had already read. That was even odder, but also rather unusual. I'll see if it happens again.

**Comment by yolanv** [comment]
Also happening in my group conversations. Can reproduce.

**Comment by inthewaves** [comment]
https://user-images.githubusercontent.com/26474149/104377874-f894bb80-54db-11eb-8b1d-f742a6556ce2.mp4

**Comment by bme13** [comment]
Happens to me too. I'm not sure if more debug logs are needed but here's one. Initially it jump up to some already read messages and after some more scrolling it jump all the way down to the latest received.
https://debuglogs.org/c197a2c311ec0ebe952623e50386c8d389e96e7bfe74613f9181e076ad0a3edc

**Comment by tlsa** [comment]
I have this problem too.  I've only noticed it in a quite-active group chat.

**Comment by error401de** [comment]
Can reproduce on multiple devices. Are there any news on a fix? For people in frequented groups this is a daily occurring issue.

**Comment by stil** [comment]
Super super annoying, reading active group chats is giving me a headache with constant jumping. Please make it a high priority issue

**Comment by SSYSS000** [comment]
I am also facing this issue on my Samsung A51 using version 5.2.3 of Signal.

**Comment by kylejw1** [comment]
Experiencing this on a Samsung Galaxy S8.  Originally thought my thumb may be accidentally brushing the 'jump to bottom' button, but today I kept my eye on it and confirmed that is not the case.

**Comment by greyson-signal** [comment]
Hi there, can you all see if you still have the issue in 5.3.8? Currently in beta. A potential fix was put in.

**Comment by bme13** [comment]
Hi. For me this seems to be fixed in 5.3.8. I had ~180 unread messages and for the first time was able to read them without jumping back and forth. Thanks!

**Comment by makchamp** [comment]
> Hi there, can you all see if you still have the issue in 5.3.8? Currently in beta. A potential fix was put in.

Fixed for me on 5.3.8 ! Thank you.

**Comment by kylejw1** [comment]
I switched to the beta 5.3.8 yesterday morning and have not seen the issue since.

Thanks very much!

**Comment by cjk28** [comment]
> Hi there, can you all see if you still have the issue in 5.3.8? Currently in beta. A potential fix was put in.

Yep seems fixed, thanks!
