### ISSUE TITLE
Feature Request: Toggle encryption per contact.  Use case...

### ISSUE THREAD

**Issue by jonfen** [signalapp/Signal-Android#10345]
When a former signal user (ex: new phone, didn't set up signal) sends me a unencrypted message and I respond via my default SMS app (signal) -- they never get the message.  If I was able to turn off (even temporarily) the encryption and just send a regular unencrypted SMS to that user -- they would get it.  Even something like "Hey did you get a new phone?  Did you setup signal yet?"

**Comment by Genis-Sage** [comment]
Hey @jonfen

Signal devs reserved the Github issue tracker for bugs

For feature request, please visit the forum https://community.signalusers.org

Also, this is already implemented since the start:
Simply press the send button for a longer time and choose unsecured sms
See https://support.signal.org/hc/en-us/articles/360007060212-Send-a-message#android_send_message

**Comment by merkste** [comment]
@jonfen You can already do that on Android: Long-press the send button and select whether to send the message via SMS or via Signal protocol.

**Comment by jonfen** [comment]
> @jonfen You can already do that on Android: Long-press the send button and select whether to send the message via SMS or via Signal protocol.

That was the fastest feature request turn around ever!
