### ISSUE TITLE
Android app takes a long time to catch up

### ISSUE THREAD

**Issue by LordNacho** [signalapp/Signal-Android#10364]
Bug Description

When I've had a conversation on desktop and open the app, the app takes a long time to catch up.
Steps to Reproduce

    Have a conversation with someone on desktop
    Open the app
    Watch notifications come in for each message, a second or so between each, until you are caught up.

Actual Result:

The app notifies for each message, one at a time

Expected Result:

The app catches up all the messages quickly
Screenshots

N/A
Platform Info

Signal Version:

1.39.4

Operating System:

MacOs

Linked Device Version:

Android 10
Link to Debug Log

N/A

**Comment by Genis-Sage** [comment]
hey @LordNacho 
could you provide more information, which are requested in the bug template:

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log



the only information you gave until now is you Android version, the rest are Desktop information



also, you could try out the 5.1.x beta of Signal (after making a backup), which has lot's of performance improvements

**Comment by LordNacho** [comment]
How do I access the debug log on Android?

**Comment by UserX404** [comment]
Settings - more settings - debug log

**Comment by LordNacho** [comment]
https://debuglogs.org/4f4bebf92e0cb1d3d166771c318fa50c25ac6f42db3f0a6436d03f1503af0530

It happened when I went back into the app just now. There weren't many messages though.

**Comment by rishi255** [comment]
Same issue. Not just "notifications" but I have to re-read the whole conversation in the app because messages come one at a time on mobile (when you start the app on mobile after having a whole conversation on desktop). The messages come one by one with a gap of around 1 second or more. So if I had say even 50 messages in the conversation I had on desktop, I need to wait for around a minute just for the android app to catch up. This gets much worse with very active group conversations as number of messages can go much higher, say 500.

Does anyone have an idea of where in the code this issue could be occuring?
