### ISSUE TITLE
Contact list takes too much time to refresh. And new contact joined Signal event is not working. The contact doesn't appear in the list until I refresh. 

### ISSUE THREAD

**Issue by C4P4E7** [signalapp/Signal-Android#10398]

**Comment by C4P4E7** [comment]
> 

The contact doesn't appear in the list till I refresh.

**Comment by bkqtnte10** [comment]
Probably related to #9498. 

I saw this behavior twice already that contacts are only shown after refresh (and waiting). However it is not easy to replicate.

**Comment by Krrishdhaneja** [comment]
Same here

**Comment by C4P4E7** [comment]
> Probably related to #9498. 
> 
> I saw this behavior twice already that contacts are only shown after refresh (and waiting). However it is not easy to replicate.

Replicate?

**Comment by thecoducer** [comment]
I'm facing this same issue too. It takes quite a lot of time to refresh the contact list.

**Comment by ponder2000** [comment]
### The refresh is not proper(circular progress indicator loads for too long)!
Sometimes my friend get to see when one of my new friend joined signal via contacts but I am having the same contact it takes too much time to reflect! Why so?? I am sure both of us has significant internet speed.

**Comment by bme13** [comment]
Hi, There can be a difference in contact updating for you and you're friends due to the nature of how contact discovery works. Please note that once a contact joins Signal it's not that contacts client that informs you that he/she joined Signal. You're own client checks on a regular basis (think it's once every 6 hours) if someone of your contact list joined Signal. Hence there can be a difference between you and you're friend see a common contact in your list. For additional information please see: https://signal.org/blog/private-contact-discovery/
As for the new contact event I think that is indeed not working at the moment. Since this ticket is mostly about refreshing I will create a new ticket for that specific issue.
