### ISSUE TITLE
Disable notifications when more than 5 messages are missed in a particular chat

### ISSUE THREAD

**Issue by gexgik** [signalapp/Signal-Android#10602]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There's no need to be notified after each message in a specific chat. If I miss more than 5(for example) messages on the same chat, disable the notification.
### Steps to reproduce
- ask another user to write more than 5 messages to you
- 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- you will get notified for each and every message

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- Get notified only for first 5 messages, then mute notifications.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Sgn-32** [comment]
Hi gexgik,

please use the community forum for feature requests.

https://community.signalusers.org/search?q=notification%20%23feature-requests

**Comment by Frivolous2** [comment]
Hello! 

You can upvote this feature request, if you haven't done already:

https://community.signalusers.org/t/rate-limiting-notifications-aka-delayed-batch-receive-periodically-muted/1761

You can use your existing GitHub account to Log In to this forum.

I hope this helps. 😇

**Comment by wolf99** [comment]
Feature request is from some years ago. I have voted on it nevertheless.

 I'd happily investigate getting started with android to implement a commit for this myself. Except that it seems there have been several PRs for this already that were closed without explanation.

Can anyone please clarify what would be required for a PR on this to succeed?
Or indeed, if there is any reason that a PR on this would never succeed?

**Comment by cosmo321** [comment]
Please! I can't state how annoying it is when a group chat suddenly gets **very** active.

**Comment by wolf99** [comment]
Yes this is still relevant.
And yes, I think everyone here would like very much to know what is blocking it, but no-one seems to have any information to share to date.

**Comment by Frivolous2** [comment]
I'm not a dev, but feature requests are ignored on GitHub as far as I know, only bug reports are expected here. Most GitHub issues like this one I've seen just get closed and redirected to the corresponding feature request in the forum. I suppose might as well save them the work and close it ourselves. @gexgik

For anyone who wishes for the feature to be implemented, please join us in upvoting the FR here:

https://community.signalusers.org/t/rate-limiting-notifications-aka-delayed-batch-receive-periodically-muted/

**Comment by wolf99** [comment]
@Frivolous2  there have been several PRs for community contributions for this. Meaning that no request to develop it should be needed.

**Comment by Frivolous2** [comment]
Well, I'm sure the devs are aware of the PR. Doesn't mean that every PR will get turned into a feature - the UX designers need to make a decision whether it's a good idea or not, and I'm assuming they have other things higher on the todo list. 

Sure, it's been a while, but that doesn't change the fact that they probably have other priorities; they're not just going to merge things that are low-prio just because they are small changes. 

Maybe they have an idea for a notification system overhaul, and don't want to merge anything because then how will it interact with the new system? Or maybe they don't. Fact is, other than upvote the feature request, and that way hopefully bump it up in their todo list, there's **nothing** you can do about it as a user.

We get a good, free app, and we are not paying customers - whatever the Signal devs' internal process is, we can't do anything about it, other than upvote an FR in the forum. This issue on GitHub will most probably achieve nothing other than @stalebot pestering us once a year until a dev closes the issue and points us to the FR anyway.

**Comment by greyson-signal** [comment]
Hi there, thanks for the discussion, but we use Github for bugs. I don't consider notifying users of every message they get as a bug. We may make changes in the future to add more controls around notifications, but I don't know when. Thanks!
