### ISSUE TITLE
SMS Messages not imported after enabling from Signal app

### ISSUE THREAD

**Issue by nertim** [signalapp/Signal-Android#10618]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
SMS messages are not imported after enabling from Signal app. This has worked just fine with version 5.0.8 yesterday, but it seems to not work with version 5.1.8

### Steps to reproduce
- Install Signal app (version 5.1.8)
- Enable SMS/MMS integration

**Actual result:** None of the SMS/MMS messages show up in the Signal app
**Expected result:** Once the SMS/MMS integration is enabled, there should be notification asking to import all the messages and than all the messages should get imported.

### Device info

**Device:** Pixel 3
**Android version:** 11
**Signal version:** 5.1.8

### Link to debug log
https://debuglogs.org/0184dbc99d078ab209569a50d65e21ae407e7e2228e05853b23bacd16b9188f7

**Comment by nertim** [comment]
Looks like this is a recent update issue.. noticed this on reddit as well - https://www.reddit.com/r/signal/comments/kwx57k/importing_existing_messages_from_android_messages/

**Comment by ShintoPlasm** [comment]
I can confirm this is happening on my Google Pixel 3a.

Device: Pixel 3
Android version: 11
Signal version: 5.1.8

Link to debug log:
https://debuglogs.org/8e8307fd236503ab7b748d9a1814ddc42e79913849acc633746fb23d7405b9d0

**Comment by UnicodeApocalypse** [comment]
Also confirmed on OnePlus Nord.

Device: OnePlus Nord
Android version: 10
Signal version: 5.1.8

**Comment by frossigneux** [comment]
It seems that this feature has been removed in this [commit](https://github.com/signalapp/Signal-Android/commit/3134837d56bf5d20b7475a78d43f6f3ac4757b40). Having encrypted backup support doesn't justify to remove plain text backup, used for restoring messages from SMS Backup and Restore...

**Comment by ShintoPlasm** [comment]
> It seems that this feature has been removed in this [commit](https://github.com/signalapp/Signal-Android/commit/3134837d56bf5d20b7475a78d43f6f3ac4757b40). Having encrypted backup support doesn't justify to remove plain text backup, used for restoring messages from SMS Backup and Restore...

Not the same thing. The removed feature was about importing plaintext backups created originally by (old) versions of Signal. The issue described here is about importing SMS messages from the phone's main database.

**Comment by nertim** [comment]
@ShintoPlasm I think @frossigneux might be on to something.. I remember seeing this particular toast and the commit seems to indicate that it is deleted 
![image](https://user-images.githubusercontent.com/493476/104663752-83171f80-5682-11eb-96d9-f253b4e9e156.png)

**Comment by ShintoPlasm** [comment]
@nertim Interesting, and worrying. So what's the point of SMS support within Signal if you can neither export it (removed a while ago) nor import it? It seems to me like the app is offering functionality that is fundamentally crippled, if your suggestion is correct.

**Comment by nertim** [comment]
I'm assuming the inability to import might just be a bug. I am hoping some from the Signal dev group could provide a little more clarification. But I did notice on reddit that others have ran in to this issue recently as well.

**Comment by P3pito** [comment]
Same issue here.

You really should fix that ASAP as you are getting the biggest boost ever thanks to whatsapp change of privacy settings. Don't make new comers go to Telegram because of a small bug like this !

**Comment by Edenglish92** [comment]
Same issue on Samsung S20 FE with OneUI 3 (Android 11)

**Comment by KyleGoetke** [comment]
Same issue on my Pixel 4a with Android 11

**Comment by Edenglish92** [comment]
> Same issue on Samsung S20 FE with OneUI 3 (Android 11)

Any workaround? I would like to twitch to Signal for both SMS and Encrypted chat but without history it's not going to happen...

**Comment by nertim** [comment]
@Sgn-32 ... Apologies for referencing you directly on this issue. Would you be able to identify what might be going on?

**Comment by axeloz** [comment]
Hello, same here on a Pixel 3 XL. I did set Signal to be my default SMS client but I don't get any prompt for importing existing SMS. It used to work on my former phone. Thanks

**Comment by ShintoPlasm** [comment]
This issue still persists in v5.1.9

**Comment by CorruptComputer** [comment]
This is such an important feature to have when people are trying to migrate to the app. How can this be overlooked and removed??

Please Signal, add this feature back.

**Comment by ShintoPlasm** [comment]
> This is such an important feature to have when people are trying to migrate to the app. How can this be overlooked and removed??
> 
> Please Signal, add this feature back.

The timing for this is just so astonishingly bad, I can't get my head round it.

**Comment by Edenglish92** [comment]
While discussing with teammates, I discovered that with the same device (Samsung S20 FE) and same OS (OneUI 3.0), they got the SMS import and it worked 😳 I dit not get any import proposition on mine... So strange!

**Comment by axeloz** [comment]
@ShintoPlasm I'm sure we all understand about the timing. I just don't understand why this migration feature was removed at the first place. Now my Signal app is empty and I don't want to use two separate apps. And I agree with everything said earlier: you have a huge opportunity with the flow of new users, the transition should be as smooth as possible
Good luck to the Signal teal and thanks for the hard work. I will make a recurring  donation today, hopes it help.

**Comment by Sgn-32** [comment]
The linked commit was from 3 Jul 2018. Removed was the plaintext backup import.

The strings for SMS database migration is still available in Signal master:
https://github.com/signalapp/Signal-Android/blob/ff11609a823fc95bee9d438183a4ee95fe011ab2/app/src/main/res/values/strings.xml#L2125
```
<string name="database_migration_activity__would_you_like_to_import_your_existing_text_messages">Would you like to import your existing text messages into Signal\'s encrypted database?</string>
<string name="database_migration_activity__the_default_system_database_will_not_be_modified">The default system database will not be modified or altered in any way.</string>
<string name="database_migration_activity__skip">Skip</string>
<string name="database_migration_activity__import">Import</string>
<string name="database_migration_activity__this_could_take_a_moment_please_be_patient">This could take a moment. Please be patient, we\'ll notify you when the import is complete.</string>
<string name="database_migration_activity__importing">IMPORTING</string>
```
And source code is also in master:

https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/database/SmsMigrator.java

Some actually discussion is also on the community website:
https://community.signalusers.org/t/import-standard-sms-database-into-signal/6362

**Comment by axeloz** [comment]
The solution described on the community forum worked like a charm for me.

**Comment by Edenglish92** [comment]
> The solution described on the community forum worked like a charm for me.

Installing an old version of Signal, importing SMS and then updating Signal?

**Comment by ShintoPlasm** [comment]
> > The solution described on the community forum worked like a charm for me.
> 
> Installing an old version of Signal, importing SMS and then updating Signal?

Much as this is "a" solution, this is going to push some newcomers away from the app and isn't really sustainable in the long run. I can also confirm that this problem is still there in version 5.2.3 (via the Uptodown app store).

**Comment by axeloz** [comment]
No this is not THE solution, that's for sure, just a quick fix. This issue has to be addressed soon for the new comers.

**Comment by 0xedward** [comment]
The solution, shared by @Sgn-32 , of downgrading your Signal app version to import SMS worked for me, but in my case, I wanted to merge my existing Signal messages sent on Signal 5.2.3 with my unimported SMS messages.

The workaround solution doesn't work for this use case. The older 4.78.5 version doesn't support importing a backup created with a newer Signal version (5.2.3). I was able to import SMS messages on 4.78.5 and create new backup, but now I had a separate problem of having two Signal backups and being able to restore only one of the backups on reregistration. 

So I can either have Signal with my SMS imported, but missing all my Signal messages or Signal with my Signal messages, but none of my SMS messages imported. 

I imagine the feature to migrate SMS into Signal would not only be useful for newcomers, but also for existing users.

**Comment by frontrunnersoftware** [comment]
This SMS import mechanism worked fine on my own Oneplus 7T Pro.  However, my friends Honor View 10 phone wouldn't import SMS messages on initial install.   After clicking on the import banner, the app just moved on, but does not show any historical SMS messages.  I can send and receive them no problem.  I tried uninstall-reinstall, making Signal the default SMS app before import and allowing all permissions manually, but still no luck.

**Comment by go2null** [comment]
Still here on v5.2.3, Pixel 2 XL

**Comment by go2null** [comment]
And LG G8X ThinQ

**Comment by UserX404** [comment]
Just found that Git issue and already had a discussion at the [community forum](https://community.signalusers.org/t/import-standard-sms-database-into-signal/6362?u=userx404).

The onboarding [megaphone - commit](https://github.com/signalapp/Signal-Android/commit/b9d8868aab3e4ce81448fffa7b848b4757e4d9ca) removes the `SystemSmsImportReminder` which seems to trigger SMS import into database.

**Comment by greyson-signal** [comment]
1) The SMS import was only partially functional. It did not import MMS messages (so no pictures or group conversations).
2) If you somehow managed to import twice, you'd get duplicates of all of your messages.
3) The importer looks like was written 7 years ago... because it was. 
4) We were funneling a ton of people to this screen with a big banner right after they installed the app. Not a great first impression.

I understand people want this functionality, but the way it was working in the app just isn't acceptable in my opinion. I'd like to update and fix it, I just need to find the time. In the meantime, please feel free to use Signal as your SMS app moving forward, and if you want to reference your previous messages, just check your old SMS app. Goodness knows you'd have to do that anyway for pictures and group chats.

**Comment by ShintoPlasm** [comment]
Suddenly removing a key functionality without warning, especially with so many new people joining, is probably not the way I'd have chosen to do it. In the age of smartphones and unlimited data, I'm also wondering how many of us are even using MMS (instead of WhatsApp etc.) and how many would have been affected by the lack of MMS import. Surely a big warning would have let people make their own choice?

**Comment by Edenglish92** [comment]
> Suddenly removing a key functionality without warning, especially with so many new people joining, is probably not the way I'd have chosen to do it. In the age of smartphones and unlimited data, I'm also wondering how many of us are even using MMS (instead of WhatsApp etc.) and how many would have been affected by the lack of MMS import. Surely a big warning would have let people make their own choice?
> 
> Having said all that, thank you for taking this on. I wish you luck with trying to update the SMS bit.

+1, this removal makes no sense... MMS is crap whereas SMS import is fundamental.

**Comment by nkm8** [comment]
For people seeking a workaround, see my comment here: https://github.com/signalapp/Signal-Android/issues/8887#issuecomment-766389939

I think this issue boils down to: is importing SMS without MMS a useful feature? I vote yes, but I'm sure opinions differ. 

In a perfect world, this feature would be added back and updated to support MMS. This would ease the transition for new users. For example, the default Messages app on Android constantly spams the share sheet in Android 11. You have to uninstall/disable the app to stop this, which makes it difficult to reference old messages. 

It may seem trivial, but pain points like this make it much harder to transition non-technical users to Signal.

**Comment by asmallbeast** [comment]
> ...if you want to reference your previous messages, just check your old SMS app. Goodness knows you'd have to do that anyway for pictures and group chats.

At least on a Pixel, this isn't possible. Google Messages will only show messages if the app is set as the default SMS app. I'd really like to use Signal as my SMS app going forward, but to do so I'd have to switch the default back to Messages anytime I wanted to reference old texts.

I understand the desire to replace the importer with a better version, but it really seems to me that deprecating this feature rather than simply removing it would have been a much better user experience. Even if you can still access your old texts in your previous SMS app, nobody wants to have to do that. Having to save your MMS pictures to your device isn't that big of an issue, but removing the feature entirely creates way too much friction in the switching process.

**Comment by johnwblue** [comment]
I run a self-complied, bare AOSP on pixel.  I downloaded the signal apk when it was v5.0.8 and it imported my SMS without issue.

That said, I am sysadmin by trade and so I will not fully understand the complexities of why QKSMS and now Signal have such a hard time reading the stock SMS database in.  It’s a database ..

/data/data/com.android.providers.telephony/databases/mmssms.db

.. I have opened it myself and in poking around I can see how things are linked together.  It seems like it would be such a low bar to get over.  Can anyone explain the software engineering challenges of performing an SMS/MMS import?  Either this feature is being punted by most everyone or it is really hard to do.

Finally, I replied to this particular email because of ShintoPlasm whatsapp comment.  You can start counting with me!  I have never used whatsapp.  I do not ever want to use whatsapp .. or any other social media app.  I do respect others freedom/right to choose and self-determination but the echo chamber I live in with my tinfoil hat is actually fairly quiet.

PS .. kudos to the Signal team on detecting Google Play is missing from the phone but installing anyway.

**Comment by ndbudd** [comment]
> 1. The SMS import was only partially functional. It did not import MMS messages (so no pictures or group conversations).
> 2. If you somehow managed to import twice, you'd get duplicates of all of your messages.
> 3. The importer looks like was written 7 years ago... because it was.
> 4. We were funneling a ton of people to this screen with a big banner right after they installed the app. Not a great first impression.
> 
> I understand people want this functionality, but the way it was working in the app just isn't acceptable in my opinion. I'd like to update and fix it, I just need to find the time. In the meantime, please feel free to use Signal as your SMS app moving forward, and if you want to reference your previous messages, just check your old SMS app. Goodness knows you'd have to do that anyway for pictures and group chats.

I understand this, but I am one such new user. The inability to import my old SMS DB (Oppo R9S), basically renders Signal as a non-starter for me, and, I expect a lot of other users that don't take the time to post. Signal looks great, as is it's intent, but it's practically useless without my messaging history.

I'll be ready to try again once the functionality is repaired :)

**Comment by breversa** [comment]
@greyson-signal 
I believe the SMS import should be brought back into Signal in order to improve acceptance and broaden the audience : more than 50% of the time, when I invite someone to use Signal, one of their first reaction is "What ? Yet Another Messaging App ?©"

I usually manage to get around by explaining that Signal can do both SMS *and* secure messaging, but even when they set Signal as their default app, their first complain is "I need to check the SMS app to remember where I was in each conversation. That's not good, I won't use Signal, sorry not sorry."

Allowing new users to import their existing SMS conversation (and even better : to *advertise* such feature) would go a long way into improving the app's acceptance. :-)

**Comment by hamishmb** [comment]
Still seems to be an issue.

Moto G8 power.
Android 10.

**Comment by PabloDons** [comment]
Y'all should make time for this. This is the single reason why i haven't switched to signal yet. I consider it unusable without my sms database. I refuse to resort to checking my old app for past conversations. It's too inconvenient

**Comment by aniphreak** [comment]
Please have time make this functional or at least revert back to the old code This is a very essential feature for new users. 

The workaround on the community doesnt work anymore because old versions of Signal does not verify phone numbers when instaig the app.

There are no alternatives for this. Please developers.

**Comment by greyson-signal** [comment]
I'll reiterate that we cannot just 'turn the old thing back on'. It was very bad for multiple reasons, and we'd probably just have to re-do it from the ground-up and do a bunch of testing on it. That takes a lot of time, and it's hard to justify putting a lot of time into features to support non-encrypted messaging. Not saying we won't ever come back to it, but we need to schedule time for it, and there's no time in the near future.
