### ISSUE TITLE
[Blocking BUG] 25 seconds or more to send a message in large group

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#10644]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is taking 25 or more seconds to send a small text message to a group with >500 members.

Edit:

This bug is especially bad when you are migrating your communities to Signal and then they run into that lack of fluency causing them to lose interest in chatting.

### Steps to reproduce
- Join to a group with >200 members.
- Send a message.
- Wait the message to be sent.

**Actual result:** Signal is taking 25 or more seconds to send a message.
**Expected result:** Signal send the message instantly as in 1:1 chats.

### Screenshots

https://user-images.githubusercontent.com/32582878/104671558-0bf68100-56ac-11eb-92f6-f478560feaa6.mp4

### Device info

**Device:** Samsung Galaxy A70.
**Android version:** 10
**Signal version:** 5.2.0

### Link to debug log

https://debuglogs.org/b6185f75ae96d0f1031eecc3e04688bbac587afcd0d4830f39850400f903ad5c

Edit 2: the desktop app works fine, messages are sent instantly. Don't know if iOS users are affected.

**Comment by swarupbhanjachowdhury** [comment]
@Edu4rdSHL  yes i checked the group by joining myself,

But it's already taking very long time to even joining the group.

And sending messages is taking over 3 minutes for me. And also draining pretty much extra internet to just send a message in a large group

**Comment by Frivolous2** [comment]
This is a limitation of the Signal protocol, I think? The app is designed so that the server doesn't even know there is a group chat, nevermind what members there are in that group. The downside is Signal has to do some extra jumping through hoops, which goes exponentially bad the more devices there are in said group. I believe the Signal team recently said they're working really hard on making big groups work better.

This is all based on my limited understanding of [this article](https://signal.org/blog/private-groups/).

**Comment by Edu4rdSHL** [comment]
@Frivolous2 if that's a Signal protocol limitation then groups in Whatsapp should have the same problem but they doesn't. Also, as I said the desktop app works as expected, so it's an Android app specific issue.

**Comment by Frivolous2** [comment]
> 
> 
> @Frivolous2 if that's a Signal protocol limitation then groups in Whatsapp should have the same problem but they doesn't. Also, as I said the desktop app works as expected, so it's an Android app specific issue.

From what I understand, Signal groups work by encrypting and sending the message individually to each participant, with each participant's public key. So, in a group of 500 participants, my phone is encrypting and then sending 500 messages. This works better on desktop because of the more CPU power I would assume. The rationale is that since you're just sending individual messages, the server doesn't even know there is a group, doesn't know what members are in there, doesn't know anything other than "[anonymous sender](https://signal.org/blog/sealed-sender/) has sent message to user X"; the app upon receipt sorts which messages go in which chat, whether in a direct message with the sender or in a group with the sender.

If I understand correctly, WhatsApp doesn't care if it knows about a group's existence, so it just creates a group key for each group, and all participants use it to send group messages. So, instead of encrypting and sending 500 messages, you encrypt one message with the group key, send it to the server, and then the server sends it to the 500 participants. The upside is greatly improved speed; the downside is the server knows there's a group chat, and it knows who is in it, and it's only one key protecting the security of all the messages in the group.

Signal treats its server as if its compromised, which is why it goes to such extreme lengths: so that you don't have to trust the server for anything. It does make implementing some features harder though; for example, group permissions/admins had to be [reimagined from the ground up](https://www.signal.org/blog/signal-private-group-system/) from how other apps do them, so that Signal does not rely on the server to store data on who is an admin and who isn't.

Again, I might be totally wrong in my understandings of things. 😅

**Comment by Edu4rdSHL** [comment]
Closing because devs doesn't seems to be interested on it.

**Comment by swarupbhanjachowdhury** [comment]
@Edu4rdSHL it doesn't matter they are interested ot not, it's a valid bug, it should be open until someone fix it.

**Comment by greyson-signal** [comment]
As some others have helpfully described, Signal currently has to send a message to each group member individually, which is why this can take a while when sending to very large groups. We have work planned to improve performance here. Thanks!
