### ISSUE TITLE
Possible private info exposed to android system

### ISSUE THREAD

**Issue by tanujkucp** [signalapp/Signal-Android#10650]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
See screenshots below.

See the above image, first one is android share sheet and second one is home screen with app shortcuts on long press.
Now as the app claims to expose as much less of data as possible to android system to protect user privacy, but here the android operating system is getting access to your contact names , group names and also knows that these are the people you frequently talk to. This is a privacy loophole disguised inside a feature. I understand that those share targets in share sheet and long press shortcuts to chats on homescreen  are good features, but they cost privacy. Also think of the fact that people use all kinds of home launchers on android and they get to see this contact data.

I would like to ask for views of maintainers on this.

### Steps to reproduce
- Go to browser and share any link , that will open android share sheet
- Go to homescreen and long press on the signal app icon

**Actual result:**  frequently contacted contact names and group names get exposed to android system
**Expected result:** Both features should not be there to protect user privacy

### Screenshots

![Screenshot_20210115-132658_Android_System~2](https://user-images.githubusercontent.com/32611332/104697590-fe85d900-5735-11eb-8be9-e6ff83cff728.png)

![Screenshot_20210115-132708_Pixel_Launcher~2](https://user-images.githubusercontent.com/32611332/104697609-0776aa80-5736-11eb-85ed-35a82199f3b9.png)

### Device info

**Device:** Xiaomi Redmi 5 plus Derpfest Custom ROM
**Android version:** 11
**Signal version:** 5.1.8

### Link to debug log
Not relevant

**Comment by nrizzio** [comment]
This is intended functionality and not a bug. "Exposing groups to the Android System" is only a problem if your device is compromised, at which point there's nothing any individual app can do about it.

**Comment by Rhahkeem** [comment]
> This is intended functionality and not a bug. "Exposing groups to the Android System" is only a problem if your device is compromised, at which point there's nothing any individual app can do about it.

Makes sense

**Comment by tanujkucp** [comment]
> This is intended functionality and not a bug. "Exposing groups to the Android System" is only a problem if your device is compromised, at which point there's nothing any individual app can do about it.

If we consider what signal promises then, noone except the sender and receiver should be able to know anything about the conversation and any private info. If we use these 2 features than we are exposing private info to various launcher apps available for Android, many of which maybe logging this info.

**Comment by Frivolous2** [comment]
I'm in no way able to comment on the devs' opinion, so here is mine: a lot of people download custom keyboards, which, if malicious, can siphon a lot more than just your favourite contacts. Signal cannot protect people from themselves outside of the app all the time, because it's also meant to be the "for mortals" secure messaging app, which means it has to add convenient features present in other competitors, so that it doesn't repel casual users away. 

In addition, the vast majority of users use the preinstalled launcher from the OEM. If the OEM launcher is sniffing info about contacts, then probably so is the contact app, and the keyboard, and the camera, etc. People with custom launchers are Google Play's problem, to screen apps for malicious behaviour. If you don't trust your OEM or Play, there is F-Droid.

I'm not saying your worries are invalid - those are valid concerns - I just think Signal can't provide perfect privacy and perfect usability - it's a middle ground. Perfect privacy has been probably available since PGP emails, but what's the point of it if you can't convince your contacts to use it?
Hence, compromises. Hence, Signal.

**Comment by Frivolous2** [comment]
And just to add to that, Signal simply promises that they can't read your messages, and no one else can, _in transit_. It cannot protect you if your device has a virus, or a malicious OEM, or lacks the security updates. No app can. I'm also not sure it's Signal's job to tell people to not buy cheap phones with no updates, or flashy launchers from dodgy sources. Sure, it can make, say, a blog article "Steps to protect your privacy on your device" and offer a fun popup in-app for those that are interested, but it's ultimately not Signal's job to do _everything_ to protect privacy. In my opinion, expecting that is an unnecessary sacrifice, and is kind of hard to actually implement, I believe. Even if they remove direct share, how will Signal know your keyboard is not from Dodgy Company, Inc.?

**Comment by Frivolous2** [comment]
I think Signal can't protect against everything, but a "Privacy Checkup" style wizard might help detailing the times your info might leak to the OS.

You might also be interested in this debate:
https://community.signalusers.org/t/signal-should-warn-users-who-are-likely-using-insecure-ime-apps/10272/77
