### ISSUE TITLE
Calling Via WiFi Not Working Well.

### ISSUE THREAD

**Issue by sharibtanweer** [signalapp/Signal-Android#10654]
This app not working calling video or voice call not working well it always keeping call drop.
Not working on wifi on android and windows. testing not performed before making in live.
When calling it keep triggering to on mobile data when i already using wifi.

**Comment by KushagraKarira** [comment]
The problem is likely with your wifi ISP
I've tested it on my device and no problems

**Comment by Frivolous2** [comment]
> 
> 
> When calling it keep triggering to on mobile data when i already using wifi.

The mobile data indicator is switched on, but if you are connected to wifi, it will keep on using that wifi connection. I'm assuming the data is put on a "standby" mode in case your wifi drops/gets out of range, so that you can continue your call on mobile data immediately.

**Comment by sharibtanweer** [comment]
No Its Only Happening In Signal App Not Happening In Other App Like Whatsapp Or VOIP App Made By Me. You Have To Do R & D Again.

**Comment by Frivolous2** [comment]
I'm not 100% sure why Signal does it like this, but the mobile data indicator switching on is normal for Signal, and it doesn't use any extra data when you're connected to WiFi, as far as I can tell.

As to the call drops, it might be after effects from the outage. 

In any case, please use the [template](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports) and provide debug logs, so that the devs can diagnose what's wrong.

I hope this helps. 😇

**Comment by sharibtanweer** [comment]
Hello sir.

I am a Android app developer can i be a part of signal app?

Please call me in this number 919999503127 or revert me in my emal if you
want me part of signal app.

Thanks & Regard
