### ISSUE TITLE
Signal failed to delete your account

### ISSUE THREAD

**Issue by kintonc** [signalapp/Signal-Android#10685]
Hi all. I'm experiencing the same bug as as [Issue 10666](https://github.com/signalapp/Signal-Android/issues/10666), I am trying to delete my account but I get 'Failed to delete account. Do you have a network connection?'. Can confirm that it is not a network connection issue. 

Repro:
1. Unregister my phone number from Signal, by going to Advanced -> uncheck "Signal messages and calls"
2. Try deleting account
3. Get error message

I'm using Signal Android 5.1.9. 

AFAIK Signal servers are back up now so not sure why I am seeing this error message.

**Comment by Sgn-32** [comment]
Try without unchecking "Signal messages and calls".
https://support.signal.org/hc/en-us/articles/360007061192-Unregister-or-Delete-Account

If it isn't working, please post debug log.

**Comment by kintonc** [comment]
Deleting account works if I do not uncheck "Signal messages and calls".

From a UX perspective, this is very confusing for a user, as (a) there's no indication the "Signal message and call" and "Delete account" options are linked, and (b) the difference between "Signal message and call" and "Delete account" is not clear. Would recommend a UX change here.

**Comment by arnowelzel** [comment]
I also have this problem with Signal 5.30.6.

The story:

1. I had to factory reset my phone - it did not boot any longer
2. I reinstalled signal
3. The PIN I used before did NOT work anylonger
4. I could NOT create a new pin
5. All my contacts are GONE

So I decided to try it with deleting the account and creating a new one.

There is no "Signal message and call" - only a form to enter the phone number for the account to be deleted.

I entered the correct number - then there is a dialog with "Deleting account... Deleting user data and resetting the app" and a progress indicator.

After another dialog pops up: "Account Not Deleted" explaining that there was a problem with deleting the account.

**Comment by cody-signal** [comment]
We are currently experiencing a server outage with the service that is responsible for handling PINs and creating/verifying them. This is likely the issue you are currently running into. I'm sorry this has happened, but know our server team is hard at work trying to fix the issue.

**Comment by arnowelzel** [comment]
Thanks for the feedback and good luck with the server issues. Keep up the good work which I experienced in the past!

**Comment by ymatt888** [comment]
I have two signal accounts in two android devices and both are connected and working fine. Unfortunately, I cannot delete the account in both devices.
Explanation:
* This is an intentional tactic by the Signal team to discourage people from closing accounts. They want people to abandon their accounts and uninstall the app without closing their accounts.
* The reasoning behind the tactic is to accumulate a large user database to convince potential buyers ‘for Signal’ in the future - for big $~
* This is a dishonest dirty tactic used by American companies initially and then copied by many other companies around the world. The practice is not only online but also in physical form: most companies never delete clients’ data, even when requested to do so.

**Comment by greyson-signal** [comment]
@ymatt888 I assure you, if account deletion is failing, it is not intentional. If you send us a log (Settings > Help > Debug log) we can look into what is failing and address it. Worth noting that I think a week ago there was a server issue preventing deletions, but that should be resolved by now.
