### ISSUE TITLE
Text selection controls don't work in message composition box

### ISSUE THREAD

**Issue by sivaraam** [signalapp/Signal-Android#10725]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since v5.1 text selection controls don’t seem to be working anymore in the message composition box. When I try to select text the control bar appears briefly in the top and disappears. I’m also unable to paste any text. This used to work fine before this update. This is killing me as I'm pretty much stuck with no cut/copy/paste in the composition box right now. I can't even paste text after editing it somewhere else 😢 

### Steps to reproduce
- Open a conversation
- Enter some text and try to select portions to cut/copy/paste
- Try pasting some text

**Actual result:** Observe that it is not possible to select/cut/copy/paste text in composition box
**Expected result:** It should be possible to select/cut/copy/paste text in composition box

### Device info

**Device:** Samsung SM-J111F
**Android version:** 5.1.1
**Signal version:** 5.2.3

### Link to debug log
https://debuglogs.org/afeefd831bbcd989d08bb06b05a60b766d3f20b91cf1c71c909f21c0c770c423

**Comment by Caerbannog** [comment]
I remember having observed this behaviour on one of my phones this week.
But I didn't note the config/version and did not take the time to troubleshoot it.

**Comment by prof33** [comment]
I also started experiencing the same issue yesterday after updating to the latest version.
I am using a Samsung Galaxy Tab A SM-T285.
Android version: 5.1.1
Signal version: 5.2.3

**Comment by ascendingSun** [comment]
I cannot reproduce this issue on the latest version 5.3.1

**Comment by Trombonista** [comment]
On S4mini V5.3.1 (and some previous versions) I can copy, but not paste. Does not matter if to-be-pasted text is plain or a link.

**Comment by Caerbannog** [comment]
I managed to reproduce it.
I suspect that the problem comes from the (old) Android version.
The problem happens on the conversation screen but not on everywhere.

Signal: 5.2.3
Device: Samsung Galaxy Grand Prime
OS: Android 5.1.1

Here is a screen where I managed to select text. Note that the controls appear in a "control toolbar" at the top of the screen.

<img src="https://user-images.githubusercontent.com/242172/105642836-72d62000-5e8c-11eb-9f98-0cd190d0b6d4.png" width="270" height="480" />

Here is another screen where I failed to select text. After a long click, the "control toolbar" flashed then disappeared. Note that the expected toolbar position suspicioulsy matches the app toolbar.

<img src="https://user-images.githubusercontent.com/242172/105642831-6e116c00-5e8c-11eb-81ea-fe6a2a361594.png" width="270" height="480" />

Here is yet another where the design doesn't work great with the "control toolbar". Text has been selected, but is now hidden. It's not an important issue though ; that screen needs a lot less polish than the conversation screen.

<img src="https://user-images.githubusercontent.com/242172/105643358-a9fa0080-5e8f-11eb-80d6-84b4cb1026bc.png" width="270" height="480" />

On the same phone I triggered a related problem in the Google Maps app (search for something, then edit the search). The "control toolbar" was shown but messed up Google Map's UI.

So the problem might be caused by Signal's layout interacting with the "control toolbar" on Android 5.1.1.
