### ISSUE TITLE
Cannot receive MMS on Verizon

### ISSUE THREAD

**Issue by judemille** [signalapp/Signal-Android#10730]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
MMS messages fail to receive sometimes.

### Steps to reproduce
- Using Verizon
- Receive MMS messages

**Actual result:** MMS messages will occasionally fail to receive for a period of time before returning to normal. This occurs with good network connectivity, wifi calling compatibility on or off, wifi calling on or off.
**Expected result:** MMS messages always receive properly with good network connection.

### Screenshots

![signal-2021-01-18-183007](https://user-images.githubusercontent.com/8127111/104973986-140c3480-59bc-11eb-98fb-269b6ae9e023.jpeg)

### Device info

**Device:** OnePlus 8 5G UW (IN2019)
**Android version:** Oxygen OS 10.5.5.IN67CD
**Signal version:** 5.2.2

### Link to debug log
N/A as the most recent occurrence just ended, will upload when it happens next.

**Comment by gchartier** [comment]
I'm having this issue about 60% of the time while messaging an unsecured group MMS chat. Strangely enough, I am only having the issue with one of the contacts in my 3 person group chat. They are an iPhone user, and they do not use signal. 

I am having either one of two issues:
1. I get a push notification saying I received a text from them, but the text went to our 1-on-1 conversation instead of the group conversation and I have to tap to retry downloading the MMS.
2. I get 2 push notifications back to back (1 saying I got a text from the individual, followed by 1 saying I got a text in the group) and the MMS loads fine in the group without me having to tap to retry downloading it.

Device: LG V40 ThinQ
Android version: 10
Software version: V405UA30c
Signal verison: 5.2.3

**Comment by binaryatlas** [comment]
I can confirm this. I have a lot of people who do not have Signal. If I can not receive MMS I will not be able to use this app.

**Comment by doriantaylor** [comment]
I have had this problem on Fido (CA) for years; [followed the troubleshooting instructions to no avail](https://support.signal.org/hc/en-us/articles/360007320211-MMS-Troubleshooting#mms). MMS messages fail to send or receive _only sometimes_ and _only if_ the phone is connected to wifi. There appears to be a correlation with the size of the message, but it isn't clear what it is. Troubleshooting guide says Signal is limited to 300k but I have sent and received much larger images over mobile data.

This comment is mainly to corroborate OP; afraid I don't have much better information than this.

**Comment by neutross** [comment]
I get this a lot when in group text; i think one user in my group text is iOS and the other is android; not sure if that has anything to do with this, but this is VERY annoying.

**Comment by neutross** [comment]
just tried turning off wifi; restarting my phone; it seems like whenever im sending aa flurry of text messages is when one errors out and the whole string of messages times out/errors.
