### ISSUE TITLE
Camera bug when device turned

### ISSUE THREAD

**Issue by biel-correa** [signalapp/Signal-Android#10735]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If you open the camera and turn your device things get strange

### Steps to reproduce
- Open a chat or the notes
- Click on the camera button on the bottom
- Turn to landscape mode

This also happens on the camera button on the main screen

**Actual result:** My camera gets stretched out but the UI keeps normal
**Expected result:** My camera should fit on screen 

### Screenshots
I can't take screenshots

### Device info
**Device:** Moto G5
**Android version:** 8.1.0
**Signal version:** 5.1.9

### Link to debug log
https://debuglogs.org/50fd81b4c3d58524eef9049bb91c3564c299c6a9bff00b01b84b95fe87616133

**Comment by Genis-Sage** [comment]
Hey @bielzim0

You can take Screenshots, after you allowed it in the signal settings

Without screenshots, at least I can not imagine what you see

I guess at minimum, it is related to  #10274

**Comment by bielzim0** [comment]
# Vertical
![Screenshot_20210120-075745](https://user-images.githubusercontent.com/56176344/105252243-da722f80-5b5b-11eb-8612-abbf3925ed43.jpg)

# Horizontal
![Screenshot_20210120-075840](https://user-images.githubusercontent.com/56176344/105252304-ecec6900-5b5b-11eb-87d5-e2fb209f9f95.jpg)

### The quality of the image in the horizontal gets lost because it is stretching the image in order to fit the vertical x axis in the horizontal x axis

**Comment by Caerbannog** [comment]
Another duplicate: https://github.com/signalapp/Signal-Android/issues/10235
