### ISSUE TITLE
Publish for default app catalog for all Android devices (distribution on Amazon App Store, Huawei AppGallery, etc.)

### ISSUE THREAD

**Issue by pangyuehung** [signalapp/Signal-Android#10770]
- [✅] I have searched open and closed issues for duplicates
- [✅] I am submitting a bug report for existing functionality that does not work as intended
- [✅] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [✅] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Maybe soon people will switch to a decentralized solution like [Element](https://element.io/)/Matrix, but for now Signal is the most popular option. Unfortunately, it is not available for all Android users, and as the US is known to use [sanctions to wage silent wars](https://citationsneeded.libsyn.com/episode-106-the-sanitization-of-sanctions) and [starve civilians](https://thegrayzone.com/?s=sanctions) in order to bully the governments of sovereign nations (often based on unchecked far-right-wing ~"intel"~ propaganda), this can restrict access to the Play Store. While there is a self-updating APK using websockets from #1000, a proper listing in alternative app stores is needed to actually facilitate this properly. 

P.S. Unless F-Droid starts appearing preinstalled on devices—which would be cool—this is not a rehash of the duplicates of https://github.com/signalapp/Signal-Android/issues/127#issuecomment-13335689 (#281 #282 #3954 #4429 #4430 #5853 #5995 #6292 #7505 #7988 #8469 #9044 #9966 #3995 #8584), but perhaps the original should remain unlocked  for comment so people don't keep opening new ones? 

### Steps to reproduce
- Get some Android device that doesn't use the Google Play Store
- Search the phone's default AppGallery or App Store for Signal
- ????
- Use WhatsApp

**Actual result:** No luck
**Expected result:** Luck!

### Device info

**Device:** NOH-NX9
**Android version:** 10
**Signal version:** :cry:

**Comment by richardddd98** [comment]
I agree. It would be nice for me to have Signal in Huawei AppGallery instead of having to download the APK. Telegram is there and an official developer confirmed it's Telegram itself which is publishing their apk on AppGallery

**Comment by YamiYukiSenpai** [comment]
It'd be nice to have it on F-Droid.

**Comment by Energiereaktor** [comment]
> It'd be nice to have it on F-Droid.

Yeah, that would really be amazing!

**Comment by pangyuehung** [comment]
Please do not coopt this ticket for something it is explicitly _not_ for, and for which there are already over a dozen linked tickets for in the original description, or else maintainers may mistakenly close this. Unless/until F-Droid comes pre-installed on devices, it is not relevant to this discussion, so please use one of the existing tickets which are actually about F-Droid in particular.

**Comment by Energiereaktor** [comment]
@pangyuehung The problem is, that all issues, which requested signal to be in the F-droid store, have been closed.

**Comment by Cerberus0** [comment]
Hi @pangyuehung,

Please note that this issue tracker is [only meant for tracking bugs in the Signal Android app](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues). This is not the right place for questions, comments, general discussion, or feature requests. Signal does not currently support additional app stores, and therefore adding support for additional app stores is considered to be a feature request. All such requests have explicitly belonged on the [Signal Community forum](https://community.signalusers.org/) since [April 2018](https://github.com/signalapp/Signal-Android/issues/7598). Signal's developers are already aware of this request and the community has been tracking its progress on the forum since March 2020:

* https://community.signalusers.org/t/availability-in-other-android-app-stores/12792

Please close this issue and continue the discussion over on the community forum. For everyone who wants to see Signal available through F-Droid, please jump over to the forum's status page and existing feature request threads:

* https://community.signalusers.org/t/wiki-signal-android-app-on-f-droid-store-f-droid-status/28581
* https://community.signalusers.org/t/signal-f-droid-repository/2808

Thanks!

**Comment by pangyuehung** [comment]
Thank you for the reply and explanation
