### ISSUE TITLE
Can't download/view video in android app group chat

### ISSUE THREAD

**Issue by sanjithks** [signalapp/Signal-Android#10794]
Device: Pixel 4a
Country: UAE, ISP: Du
Signal Android App - 
In group chat, a video that was sent by another android user (from India) is:
 - viewable/downloadable on the windows 10 app
 - NOT viewable/downloadable on the android app 
 The preview in the android app shows a download button, which keeps resetting to the original position after a few loops of the "download circle" animation.

![signal-2021-01-24-192551](https://user-images.githubusercontent.com/1007999/105634963-0b16d980-5e7a-11eb-9f50-cbd402f8c9f8.jpeg)

![signal-2021-01-24-193715](https://user-images.githubusercontent.com/1007999/105635340-b2484080-5e7b-11eb-8c8f-2199222c37f0.jpeg)

![signal-2021-01-24-193106](https://user-images.githubusercontent.com/1007999/105635123-c93a6300-5e7a-11eb-8bc0-95a563a13e33.jpeg)

**Comment by kapalko** [comment]
I have the same issue with images. Strangely, I can replicate the issue on MacOS although my Mac just shows a constantly spinning circle.

Other users are on iOS.

Screenshots:
Android:
<img width="409" alt="Screen Shot 2021-01-24 at 5 09 13 PM" src="https://user-images.githubusercontent.com/11836366/105645052-393eee00-5e67-11eb-9131-055d4a4b0c89.png">

MacOS:
<img width="531" alt="Screen Shot 2021-01-24 at 5 09 40 PM" src="https://user-images.githubusercontent.com/11836366/105645062-4cea5480-5e67-11eb-88dd-538434e8abdc.png">

### Device info
**Device:** Google Pixel 4a 5G
**Android version:** Android 11
**Signal version:** 5.3.3

Debug Log:
https://debuglogs.org/0b2a29bc31460f5397dea83eca727ea6187b6871f25e882da1e194040f6e6a96

**Comment by bme13** [comment]
Yesterday received a video in a groupchat that showed similar behaviour. Unfortunately I cannot confirm if it's viewable on a different device since I don't have a linked device. In our situation it appears the video is not viewable by any member of the group which all have Android devices. This makes me think something might went wrong during the upload, also on an Android device. Hence I've asked for the debug log of the sender device as well. Here are both logs.
Receiver device:
https://debuglogs.org/a405ffcb4c345ea1d1b7e5f5cb347f68a61d087a2edb0c58048e72839dbd3bd2
Sender device:
https://debuglogs.org/0dd1ffde4bbc65c57864588e4915a0ad6b7803db319aaa9ca76db8ab3cf98f0d
The message details about the video are (from my sending device):
Sent: Aug7, 2021, 9:48:13 AM
Received : Aug 7, 2021 9:04:21 PM

**Comment by cody-signal** [comment]
Interesting. Thank you @bme13 for providing sender and receiver logs, that's very helpful in situations like these.

It appears the sender had a really rough time sending the video as it took 12 hours of failed attempts. Appeared to be a combination of potentially poor networking or a very restrictive OS not letting us run to completion. However, once it was successful they sent the message.

On the receiver side, the message was received and attachment downloaded fine but it couldn't be decrypted due to a bad MAC. We'll track this internally and look at what we can do to prevent the bad state from occurring.

**Comment by fahei** [comment]
I also have this since some weeks. For me its on a private chat, when i want to download a video the loading animation starts and when it reaches 100%, the video download badge comes again and i can click on it again.
