### ISSUE TITLE
Signal app crashes on scanning invalid QR code

### ISSUE THREAD

**Issue by yasht01** [signalapp/Signal-Android#10805]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes after scanning invalid QR code to verify identity.

### Steps to reproduce
- Open Signal app
- Go to a person's profile
- Click on 'View safety number'
- Click on 'Tap to scan' or on the QR code to open the QR code scanner.
- Scan any invalid QR code. (Example QR code: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/QR_code_for_mobile_English_Wikipedia.svg/1200px-QR_code_for_mobile_English_Wikipedia.svg.png)
- (Scanning the invalid QR code for the first time does not crash the app. But, on the second try, the app crashes)

**Actual result:**
Signal app crashes.

**Expected result:**
Signal should return to the profile page of the person.

### Screenshots
![App Crash](https://user-images.githubusercontent.com/55907631/105687440-74e8bf00-5f1e-11eb-846c-b668adfb7be4.jpeg)

### Device info
**Device:** Nokia 6.1 Plus
**Android version:** 10 (December Security Patch)
**Signal version:** 5.2.3

### Link to debug log
https://debuglogs.org/9ca21fc80bc0c57a0fbafe6f1f731f316bb34b7e5f54740c0d7d0e9d5eede22a

**Comment by Xrasure** [comment]
I could reproduce the issue on Signal beta 5.3.4

I'll drop my debug log in if it helps somehow:

https://debuglogs.org/ab1ad09ae525d9c21a01b5475b9b3acb5ae78e41d1e6677fd8467e0990974e1a

**Comment by Caerbannog** [comment]
I digged deeper to find the source of the RuntimeException, as required by @alan-signal in PR #10805.

The exception is thrown in this `compareTo` call when the provided `scanned` string is not a valid Protobuf encoding.
https://github.com/signalapp/Signal-Android/blob/e95bb9cb0fe8c463db723e5fa21ea9b164a87a24/app/src/main/java/org/thoughtcrime/securesms/VerifyIdentityActivity.java#L414

The `compareTo` function is implemented in `libsignal-client`. The `decode` call can fail when `combined` is not a valid Protobuf message:
```rust
// https://github.com/signalapp/libsignal-client/blob/java-0.2.2/rust/protocol/src/fingerprint.rs#L118
pub fn compare(&self, combined: &[u8]) -> Result<bool> {
  let combined = proto::fingerprint::CombinedFingerprints::decode(combined)?;
  ...
}
```

This was fixed two days ago by @jack-signal in this commit:
> https://github.com/signalapp/libsignal-client/commit/d77fa218a295864fc15c6a7a08752578151f6e0a:
> **Map errors through the bridge more carefully**
> Remove several errors that were very once-off.
>
> In Java avoid throwing RuntimeException unless it's an internal error
that we really should crash on.

Here is the exact fix:
```rust
// https://github.com/signalapp/libsignal-client/commit/d77fa218a295864fc15c6a7a08752578151f6e0a#diff-cb9375261d08a971b0c5c82ff769639f8c911cc9ca543a2f18850e5c8a1f7427R121
-  let combined = proto::fingerprint::CombinedFingerprints::decode(combined)?;
+  let combined = proto::fingerprint::CombinedFingerprints::decode(combined)
+    .map_err(|_| SignalProtocolError::FingerprintParsingError)?;
```

What is now needed is to release a new version of `libsignal-client`. The last [published release](https://github.com/signalapp/libsignal-client/tags) is `java-0.2.2`, which does not contain the fix. Any further release should contain it.

Then we will be able to update the dependency [here](https://github.com/signalapp/Signal-Android/blob/v5.3.10/app/build.gradle#L337). Though it's probably not that easy, because the last upgrade of `libsignal-client` was reverted for some reason: https://github.com/signalapp/Signal-Android/commit/afbe27c55f8217036c175ac39575ae826af75c74

**Comment by Caerbannog** [comment]
I digged deeper to find the source of the RuntimeException, as required by @alan-signal in PR #10805.

The exception is thrown in this `compareTo` call when the provided `scanned` string is not a valid Protobuf encoding.
https://github.com/signalapp/Signal-Android/blob/e95bb9cb0fe8c463db723e5fa21ea9b164a87a24/app/src/main/java/org/thoughtcrime/securesms/VerifyIdentityActivity.java#L414

The `compareTo` function is implemented in `libsignal-client`. The `decode` call can fail when `combined` is not a valid Protobuf message:
```rust
// https://github.com/signalapp/libsignal-client/blob/java-0.2.2/rust/protocol/src/fingerprint.rs#L118
pub fn compare(&self, combined: &[u8]) -> Result<bool> {
  let combined = proto::fingerprint::CombinedFingerprints::decode(combined)?;
  ...
}
```

This was fixed two days ago by @jack-signal in this commit:
> https://github.com/signalapp/libsignal-client/commit/d77fa218a295864fc15c6a7a08752578151f6e0a:
> **Map errors through the bridge more carefully**
> Remove several errors that were very once-off.
>
> In Java avoid throwing RuntimeException unless it's an internal error
that we really should crash on.

Here is the exact fix:
```rust
// https://github.com/signalapp/libsignal-client/commit/d77fa218a295864fc15c6a7a08752578151f6e0a#diff-cb9375261d08a971b0c5c82ff769639f8c911cc9ca543a2f18850e5c8a1f7427R121
-  let combined = proto::fingerprint::CombinedFingerprints::decode(combined)?;
+  let combined = proto::fingerprint::CombinedFingerprints::decode(combined)
+    .map_err(|_| SignalProtocolError::FingerprintParsingError)?;
```

What is now needed is to release a new version of `libsignal-client`. The last [published release](https://github.com/signalapp/libsignal-client/tags) is `java-0.2.2`, which does not contain the fix. Any further release should contain it.

Then we will be able to update the dependency [here](https://github.com/signalapp/Signal-Android/blob/v5.3.10/app/build.gradle#L337). Though it's probably not that easy, because the last upgrade of `libsignal-client` was reverted for some reason: https://github.com/signalapp/Signal-Android/commit/afbe27c55f8217036c175ac39575ae826af75c74
