### ISSUE TITLE
Opted out of contact sharing for privacy, but contacts got notified all the same!

### ISSUE THREAD

**Issue by gatopeich** [signalapp/Signal-Android#10824]
Notifying contacts that you joined should be strictly opt-in feature and driven from the one joining.

Instead it looks like anybody with my number got a "XXX joined Signal!" message. Where is the privacy? 🙄

Notably, people I had blocked on Whatsapp just contacted me "Hello, Signal notified that you are around..."

**Comment by Caerbannog** [comment]
Hi @gatopeich !
Thanks for thinking about improvements and caring about privacy.

You can read and discuss about the situation here:
https://community.signalusers.org/t/why-are-users-who-have-my-phone-number-in-their-contacts-notified-that-ive-joined-signal/1320

Note: as the current behaviour is intentional, and until this changes, this issue will probably be closed.
