### ISSUE TITLE
Crash when sharing image 

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [signalapp/Signal-Android#10835]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashed when sharing a picture with "share" option in opera browser. 

### Steps to reproduce
- clicked on the picture in browser,
- selected share picture,
- selected the contact
- on the regular sharing screen the picture and the thumbnail was all black, 
- I clicked the arrow screen blinked
- I clicked another time

**Actual result:** the app crashed
**Expected result:** it should have send the message

### Screenshots
Couldn't make it

### Device info

**Device:** xiaomi redmi note 9
**Android version:** 10 QP1A.190711.020
**Signal version:** 5.3.6

### Link to debug log
https://debuglogs.org/f9773454387bbcbda44aa8e703c70a09a232ea7bb4a579a6097583303e58d8a1

**Comment by Xrasure** [comment]
I could not reproduce this on Signal beta using a oneplus 6t

**Comment by cmkrafft** [comment]
I was able to reproduce the reported behavior using a Samsung Galaxy J5 (2016), running on Android 7.1.1 and Signal v5.3.7.

My debug log: [https://debuglogs.org/f3b5a7984cbcc8a1629536ec0799ee00f3e7aa286ebb8e7663e5e663b596d870](https://debuglogs.org/f3b5a7984cbcc8a1629536ec0799ee00f3e7aa286ebb8e7663e5e663b596d870)

**Comment by rainerm77** [comment]
I can confirm this issue. What I've observed:
a) Only happens on specific phones/Android-OS configurations. E.g. this crash happens on my wife's phone, but not on my phone (on my phone it still works with v5.3.7.1)
b) Only happened after very recent Signal *updates* (v5.3.7) - I'm sure it worked on my wife's phone a few weeks ago at v5.0.10
c) On the phone it happens, it does not matter from which app I select "share" image to Signal (from WhAp but also from a Gallery or Explorer App), Signal then crashes

Full-log version:
https://debuglogs.org/df3ad2a85cd527acfd71c90bdd0db5c1178433d4970adbeccebee96758c7fda1

Short-log version, Exceptions filtered. The error happened at 2021-02-03 14:48:
https://debuglogs.org/c679409cd30e058fe91cd5629778b499c6688f4ebcbcc050e09c81a014ce3211

I hope these logs help (otherwise contact me, then I could use adb debug-log if necessary)

**Comment by rainerm77** [comment]
Hello all!

Whatever this very strange bug was, I think it happened due to the graduate updates the past few weeks maybe just on this specific device (or a combination of the state of its database and the graduate updates).

I’ve now tested exactly on the phone where it occurred the following trivial workaround/solution worked:

- I’ve created a chat backup
- Then in Android deleted the app-cache + app-data
- Deleted and re-installed the app
- Restored the chat backup

At exactly the Android phone, on which the bug previously has occurred, this simple solution solved the issue. Now when using “Share” some picture from other apps to Signal works again without a crash.

--> Maybe the others who reported this bug maybe can also try and confirm if this simple solution solves their problem as well?

**Comment by KarolTrzeszczkowski** [comment]
@rainerm77 I'd rather not reinstall the app if it's not absolutely necessary. It will change my security numbers and I will have to verify them in person with those whom I already have. I'll wait for the devs to look at it.

**Comment by infonotarydev** [comment]
I observe this issue now and following samsung forum tips I can confirm it's a Signal issue: When I trigger the system's share menu from any app, that app crashes. If I repeat that, from the second time onwards it works.
Samsung S21FE
Signal v6.32.5
Android 13 (with September security patch)

**Comment by alex-signal** [comment]
Hello! We just rolled out 6.33 100% to production, so please check and see if this fixes the issue for you.

**Comment by alex-signal** [comment]
@infonotarydev We've discovered a bug on Samsung devices where the database isn't initialized before the sheet tries to get the avatar. I'm working on getting it out in 6.33.3 now, but I can't promise an exact timeline because Google Play 🤷🏻

**Comment by infonotarydev** [comment]
Hi Alex, sorry for replying late. Now I have 6.33.3 and the problem is fixed. Thanks
