### ISSUE TITLE
Signal copies urls in chats as http instead of https

### ISSUE THREAD

**Issue by LaKH-exe** [signalapp/Signal-Android#10846]
When copying a url in a signal chat by long pressing it. It will be copied as http instead of https.
This only happens when https is not specified in the url. Check the attached screenshots.
I noticed this happens in the desktop version as well.

**Signal version:** 5.3.7

![sig1](https://user-images.githubusercontent.com/31774612/106199021-7a176980-61bd-11eb-9a44-b742ccd87314.jpeg)
![sig2](https://user-images.githubusercontent.com/31774612/106199029-7daaf080-61bd-11eb-8599-1c86bfaf022e.jpeg)

**Comment by dreaddr** [comment]
noticed this as well, HTTPS everywhere blocks sites when I try to use websites copied from signal, a minor inconvenience that can be stopped by defaulting to https?

**Comment by LaKH-exe** [comment]
> noticed this as well, HTTPS everywhere blocks sites when I try to use websites copied from signal, a minor inconvenience that can be stopped by defaulting to https?

Correct. Using https as default will stop future issues like this from happening.

**Comment by Xrasure** [comment]
This is still a thing in the beta of signal

**Comment by treviang** [comment]
I think this is a bug of the Android component used (https://developer.android.com/reference/android/text/style/URLSpan). The method getURL() returns the text with http (and no https) protocol by default. I don't konw if it's an accettable solution to replace every time http with https. I had the same issue with Whatsapp and Telegram as well.

**Comment by rgherta** [comment]
Hi @treviang the original android urlspan class is here https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/style/URLSpan.java. 

Its constructor reads a string and getUrl() just returns the string back. I see nothing wrong here.

The app uses this derived class
https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/util/LongClickCopySpan.java

You can see the toast with notification, you can see some handling in prepareUrl that probably needs to also handle a default schema for urls.

Now to summarize:

- A url with value "https://www.signal.org" is copied correctly to clipboard (just a string right?)
- A url with value "www.signal.org" is copied as "http://www.signal.org"  (some default http somewhere?)

Not sure where this extra http is coming from. I hope it is not happening on first saving the message because I cannot find the block where this is happening.

**Another** aspect here is that when we click the span, it will open an intent like you see in the onClick of URLSpan.java however this intent will open a browser window with http://www.signal.org that will respond with 307 and will redirect to the https://... so I think this is the second aspect of the problem. I think you can add an intent filter in the manifest file to make sure implicit intents with https only.

**Comment by hiqua** [comment]
The same seems to happen from Signal-Desktop.

**Comment by bertwesarg** [comment]
I must question the usefulness of this _copy URL_ feature in general. Point in case, I just sent the SMTP (`smtp.example.com`) and IMAP (`imap.example.com`) host names via Signal, and the receiver needed to remove the `http://` again to make them usable in the input form. `https://` would not solve this at all. Additionally, its the same behavior for Signal-Android as in Signal-iOS. Could be a separate issue though. In Signal-Desktop (v1.39.6), the host names are not recognized as URLs at all.

**Comment by rgherta** [comment]
If I remember right this means your secure signal app will initiate insecure requests from your device. There may be some info in those http headers to identify this user agent.
