### ISSUE TITLE
File attachment option is not working as expected. 

### ISSUE THREAD

**Issue by AsyncRes** [signalapp/Signal-Android#10842]

**Comment by NeutralBit** [comment]
@greyson-signal Hi, Instead of introducing new toggle for Uncompressed image (or video), isn't it better to ignore compression when sending image as FILE option? This way it will save headache of new option, also most of the users comfortable with FILE option being uncompressed (as lots of app use this method.) 

A possible solution (dumb maybe), 
calling super() in [DocumentSlide.java:23](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/mms/DocumentSlide.java#L23) with an extra argument `AttachmentDatabase.TransformProperties.forSkipTransform()` will call the overloaded version of Slide() constructor, which will ignore compression when file selected as Document (aka FILE option). There should be a cleaner way I think.

Optional: When send an image (or video) using FILE option, this should be displayed as Document (in documentStub). or at least an icon or something to indicate that the image is sent as file. Marking the attachment as file in database might be the way?
