### ISSUE TITLE
Unable to add /Delete people to a Group

### ISSUE THREAD

**Issue by gayatrianandh** [signalapp/Signal-Android#10851]
### Bug description
I have a Group with 225 people. Currently I am on version 5.3.8 ( through beta release).
I am Group Admin
I am unable to add pending requests ( through group link), unable to delete exisitng user or add new user manually.
I get error, Failed to update Group

### Steps to reproduce
- Access Group
- approve pending requests 
- Attempt to add or delete user to or from the gropu

**Actual result:** Error Failed to update Group
**Expected result:** Should add or delete user

### Device info

**Device:** One Plus A5000 ( Build No. Oneplus A5000_23_201029 )
**Android version:** 10
**Signal version:** 5.3.8

### Link to debug log

https://debuglogs.org/b80aca1c0828aa03194faa7ae7abb8220058829b5bf854961407dc998a5adc36
![Screenshot_20210129-172002](https://user-images.githubusercontent.com/78210784/106272274-cb276c00-6256-11eb-9d99-859f2f5263fc.jpg)

**Comment by volomike** [comment]
We are getting this issue too. Also Android. Also latest version of the app. Multiple group admins all report -- cannot edit the name of the group, cannot remove a group member, cannot add a new member to the group.

**Comment by gayatrianandh** [comment]
I am on 5.3.10 through FAD release..issue persists

**Comment by volomike** [comment]
I don't know what the programming team did on the server end, but the bug is now resolved in my test case with a group created in December of 2020 (I think, to the best of my recollection, on that date). Today, on that same group, we were able to add a group member as well as remove another one. Not to say that this was a fluke and the bug could come back, but my test today showed at least in this instance that the bug is resolved.
