### ISSUE TITLE
Backup not possible, only error message “No file picker available.”

### ISSUE THREAD

**Issue by roberts01** [signalapp/Signal-Android#10862]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I want to turn on the backup function, I only get the notification "No file picker available.”

### Steps to reproduce
- Open Signal
- Go to the backup setting
- press "Turn On"

**Actual result:** see description. Nothing else happens.
**Expected result:** I want a backup.

### Screenshots
![Screenshot_20210130-125356](https://user-images.githubusercontent.com/31773450/106355784-7fc69980-62fa-11eb-84dc-630a20621a2b.png)

### Device info
**Device:** Nokia 7.2
**Android version:** 10, unrooted
**Signal version:**  5.2.3 from the Google Play store

### Link to debug log
https://debuglogs.org/85dce9b70e021467c10eeae9f61c3846bbc1e2157326f8ed4b12e81132f86754

Also posted the bug here: https://community.signalusers.org/t/backup-not-possible-only-error-message-no-file-picker-available/26247

**Comment by Garfield69117** [comment]
Hi!
Same issue here, whatever the file picker used.

Signal v5.3.12
OnePlus6 on OOS 10.3.6

Debug : https://debuglogs.org/b010150ab5cf4a18612b2e56de8ce584c51937eab639d34aa98d136cc7dd847d

**Comment by roberts01** [comment]
So I tried to find a workaround and found an interesting effect: I turned off the Storage access for the Signal app, and it changes nothing whatsoever. 
Thats a problem I think, as the app should check whether it has storage access if it wants to write to storage to create a backup.

**Comment by Garfield69117** [comment]
Yes, same behavior for me. It's weird indeed...

**Comment by majo-z** [comment]
Same behaviour for me too on Pixel 3, can't create backup, tried to clear the cache, clear the storage (lost all my messages of course), reinstall, still not working.

**Comment by cbbn01** [comment]
Is this issue solved yet? I face this same issue and it's annoying.

**Comment by gitwah** [comment]
Same issue on a OnePlus 7 Pro running Android 10, Signal 5.5.5

**Comment by roberts01** [comment]
As of the 10th April 2021, this issue still persists.
I expect by no means a fast reaction, but after 3 months I think at least an acknowledgement would be appropriate.

**Comment by greyson-signal** [comment]
Very strange, since we're doing a pretty standard thing to pick a folder. Error implies there's no capable file picker.

https://github.com/signalapp/Signal-Android/blob/68aa97a676f313131a9c64763acfbe3813b9076f/app/src/main/java/org/thoughtcrime/securesms/backup/BackupDialog.java#L120

**Comment by roberts01** [comment]
Hey @greyson-signal , thanks a lot for your response!
Now that we acknowledged the problem, is would be wonderful to have it solved, especially before May when people have to accept WhatsApps new TOS.
IF we can help, feel free to ask!

**Comment by alex-signal** [comment]
From my sleuthing, AOSP should have a system app with 'documentsui' in the package name.

If you have ADB installed, could you hook up your device and try the following:

```
adb shell pm list packages | grep documentsui
```

That should print off any documentsui apps there are. For example, on my Pixel 4 there are two present:

```
package:com.google.android.documentsui.theme.pixel
package:com.google.android.documentsui
```

One of these is the AOSP documents UI and the other is likely just a themed version specific for Pixel 4.

If you don't have ADB available, you could go into your phone settings to your applications list, and press the overflow menu in the top right and hit "system apps" and then search for "documentsui" and see if anything pops up. My device shows the `com.google.android.documentsui.theme.pixel` one.

**Comment by roberts01** [comment]
Hey Alex, that just lists Googles' documents app. 
I for example have com.simplemobiletools.filemanager.pro installed, but none of the Google DocumentUIs.

**Comment by roberts01** [comment]
SOLVED IT

**Comment by alex-signal** [comment]
@roberts01 Signal fires off an Intent that the system is then responsible for handling. If there are multiple apps installed that are able to handle the intent, the user gets a system-created dialog allowing them to choose which app to handle the intent with. If none is installed, you get the crash you were experiencing.

DocumentsUI is part of AOSP and has been for a while. It should be present on the device unless explicitly replaced by the manufacturer. In your case, manual intervention (using ADB) was performed to remove a system-level app that then broke behaviour elsewhere.

If there's no app on your device that lets you choose a file, there isn't really anything we can do. Besides perhaps give the user a little more information about whats happening other than the toast.

**Comment by roberts01** [comment]
@alex-signal True enough. Maybe make a FAQ entry for this case here tho, as there appearantly are some people with the same problem.

**Comment by majo-z** [comment]
"adb shell cmd package install-existing com.android.documentsui" didn't work for me - documentsui doesn't exists error

... but finally found a solution:
1. Install Solid Explorer File Manager from Google Play
2. Open it, click on hamburger menu(top left corner), then settings icon and check "Show root storage"
3. Go back and navigate to: Root-> system-> priv-app-> DocumentsUIGoogle-> click on DocumentsUIGoogle.apk-> Install-> Done
4. Reboot the phone

Note: My phone(Pixel 3) is not rooted

**Comment by kiloDE** [comment]
Hello Community,

I've experienced that bug too, after accidentally removing the Google DocumentsUI..  

**Context:**
I tried this night a bit around, due to the Signal Bug (you cant export/backup your messages without DocumentsUI.apk by Google - which is a poor Design... but maybe a deep design decision is behind it)
I'm tried it with a S10 device. 

**Fixing the shit**
First of all... you need root (otherwise a cache clear is mostly enough, since the app itself isn't fully removed from the system)

**Plugin your Phone via USB and Debugging Enabled** (Software Informations -> Build Version press x times on it, then you're developer, back to menu, enable USB Debugging, authorize your phone - this might be different for different android versions and devices!)
I assume you already have ADB installed and likely a **rooted phone**, under linux just write apt-get install adb -y and you're fine (surely with sudo / root)

**Quick and Dirty Solution in 10 mid to easy steps:** 
1. **adb devices** (check if the device is listed, if not... you might have other problems :) )
2. **adb shell**  (open a linux shell on your golden eye == a ROOT SHELL on your PHONE)
3. Type in **"su"** (to get root); verify with "**whoami**" (should return "root")
4. **cd /system && echo "test" > /system/ && rm /system/test**   (to **test if it returns read only ;)** - checks if the /system dir is writable )
5. **mount -o rw,remount /** (NOT /SYSTEM; DO THIS ONLY IF READONLY, it remounts the partition and enables writing)
6. **cd /system/priv-app/**  (enter the priv-app directory, which may differ depending on your manufacturer and Android Version) 
7. **./find | grep -i DocumentsUI** Then enter that directory (Lists the Directories which contain DocumentsUI, it's case-INSENSITIVE, enter it...) In my case it was locate under: /system/priv-app/DocumentsUIGoogle/DocumentsUIGoogle.apk 
8. **pm install --user 0 DocumentsUIGoogle.apk** (in the root shell, ofc; Does the installation for SYSTEMWIDE)
9. **pm install  DocumentsUIGoogle.apk** (in the root shell, ofc; Does the installation for USERSPECIFIC)
10. **It should return "success**". Otherwise do some throubleshooting **WINNER-WINNER-CHICKEN-DINNER ;)** 

**In case of any head->wall banging events.. (For your own safety ;) ):**
If this why ever not appearing (some "INTERNAL_ERROR" or "SIGNATURE_VERIFICATION_FAILED") you might consult some online Forum for it... in my case it was possible to set a Environment Variable to disable VERIFICATION and I had to purge multiple times the DocumentsUIGoogle (com.google.android.documentsui)

**Very Very Additional Context:**
In my case this APK File on the phone was corrupt after my accidental removal action :o
1. Download some Stock Image for your device...
2. Extract it (tar -xvz AP.tar system.img.lz4 && lz4 -d system.img.lz4 && simg2img system.img out.img)
3. Mount the shit: mkdir tmpfs; mount -o loop out.img tmpfs; (now you see a mointpoint in that directory - therefore it should be empty)
4. Now grab the APK cd tmpfs && cp system/priv-app/DocumentsUIGoogle/DocumentsUIGoogle.apk <WHERE YOU WANT IT>
5. Download it to your phone (how you do that is your choice... I've used ncat on the phone, which seems to be preinstalled)
6. pm install --user 0 DocumentsUIGoogle.apk
Don't forget to replace the APK in /system/priv-app/DocumentsUIGoogle/DocumentsUIGoogle.apk 

FOR YOUR OWN SAFETY ::: YOU NEED SOME EXPERIENCE TO DO IT. BUT IT'S POSSIBLE! :) 
I read some Posts in Blogs / Forums where some users recommend a reset of the device, which is NOT needed.

**Comment by kiloDE** [comment]
> Very strange, since we're doing a pretty standard thing to pick a folder. Error implies there's no capable file picker.
> 
> https://github.com/signalapp/Signal-Android/blob/68aa97a676f313131a9c64763acfbe3813b9076f/app/src/main/java/org/thoughtcrime/securesms/backup/BackupDialog.java#L120

Yup but the bug is... that everything depends on that call and the android internal structure.
Isn't it possible to implement a safe alternative inside Signal? Just a question... 
BTW: It's also a bit downgrading, because everything depends on a Google (Or if you have Samsung - Samsung) app since it's not exchangeable :O

**Comment by kiloDE** [comment]
> @roberts01 Signal fires off an Intent that the system is then responsible for handling. If there are multiple apps installed that are able to handle the intent, the user gets a system-created dialog allowing them to choose which app to handle the intent with. If none is installed, you get the crash you were experiencing.
> 
> DocumentsUI is part of AOSP and has been for a while. It should be present on the device unless explicitly replaced by the manufacturer. In your case, manual intervention (using ADB) was performed to remove a system-level app that then broke behaviour elsewhere.
> 
> If there's no app on your device that lets you choose a file, there isn't really anything we can do. Besides perhaps give the user a little more information about whats happening other than the toast.

That's not that correct. The intent also fails if the app just isn't "com.google.android.documentsui" or "com.google.documentsui".
So if you have some custom FileManager out of the F-Droid Store (for example) and you would have removed the "Files" App, it would also crash.

**Comment by greyson-signal** [comment]
> Yup but the bug is... that everything depends on that call and the android internal structure.

Everything depends on that call because that's the standard way to request permissions to write in a folder on Android. It's not Google-specific. That's just how it works across all of Android. I think that intent has been available since KitKat, and it was made the standard way to request file permissions in Android 10. If whatever you've replaced it with does not have this capability, then you will have problems. You can read more about it [here](https://developer.android.com/training/data-storage/shared/documents-files). Thanks!

**Comment by illuminor** [comment]
I have the same bug, and yes, I have DocumentsUI uninstalled from my Android device. I have alternative file managers though.

You say this is intended and normal behavior in such case, but the thing is, while it's true that I have no DocumentsUI, no other app (and I mean none) has a problem bringing up a prompt that asks which file manager I want to use to pick files. Signal is the only one that shows the 'No file picker available' message and leaves me with no options to backup my data, which is very unfortunate.

**Comment by heatl0rd** [comment]
Im just echoing this bug for devd. It shouldnt behave in this way. @illuminor explained it best. Although we dont have documentsUI, i have never encountered an issue with any other app that bugs out instead of giving the user the choice of picking a file picker. Devs please reconsider how you implement this function.

**Comment by gitstuffedm8** [comment]
I am echoing as well, without root I don't even have an option to fix this myself.

Pretty poor design I must say, but maybe reason why?

**Comment by acmor** [comment]
I get the same error on a Motorola G10 (XT2127-2), not-rooted Android 11 device.
I have Solid Explorer and Goofle File installed.

`acmor@T0009aead8 ~ % adb shell
capri:/ $ su
/system/bin/sh: su: inaccessible or not found
127|capri:/ $ pm install-existing com.google.android.documentsui
Package com.google.android.documentsui installed for user: 0
capri:/ $ pm list packages | grep documentsui
package:com.google.android.overlay.modules.documentsui
capri:/ $`

**Comment by chrisbaber** [comment]
I also removed com.android.documentsui then discovered this issue.

I have since reinstalled this file, and verified it is installed and exists in my phone.

I rebooted the phone, and still have the "no file picker" error.

I uninstalled Signal, then rebooted the phone, hoping Signal looked for it upon startup, but still have this issue.

At this point, the necessary package is properly installed, but I still have the problem.

How do i get Signal to see this package again, so I can work with backups?

I need to restore an existing backup, so I can move forward with like, and this has taken far too much of my life so far, and I really just want to get this resolved.

Happy to help, or provide any logs or do any testing

**Comment by H3rcu1es** [comment]
Ok so I just googled for documentsUi apk  and downloaded  the file.  It's mainly the 'Files' app.  
After installing it, I went into luckypatcher and converted the 'Files' app to system/private.  And ya Alhamdulillah now the problem is solved!

**Comment by Jiemiin** [comment]
> "adb shell cmd package install-existing com.android.documentsui" didn't work for me - documentsui doesn't exists error
> 
> ... but finally found a solution:
> 1. Install Solid Explorer File Manager from Google Play
> 2. Open it, click on hamburger menu(top left corner), then settings icon and check "Show root storage"
> 3. Go back and navigate to: Root-> system-> priv-app-> DocumentsUIGoogle-> click on DocumentsUIGoogle.apk-> Install-> Done
> 4. Reboot the phone
> 
> Note: My phone(Pixel 3) is not rooted

Best Solution. It worked for me
