### ISSUE TITLE
Email spam messages

### ISSUE THREAD

**Issue by thetoastedghost** [signalapp/Signal-Android#10882]
Hello! I keep getting spam messages sent from emails. I was told to open a bug report and post here. I am running the beta version. 

https://debuglogs.org/f9d9d0bb5b6e42e1d15ba5829de21d029d20cb279633ced34e9ebb0b7c2463e2

**Comment by Caerbannog** [comment]
Hi @thetoastedghost!

If you followed the bug report template, there would be a higher chance of fixing the problem. 

Please read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports 
Please add links to other places where you might have described your problem.
Please explain the situation with a lot of details so that we can understand precisely what happens.
Please explain the steps to reproduce, etc.
