### ISSUE TITLE
[RTL] Mirroring issues

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#10914]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Some Items in ActionBar and elsewhere don't get mirrored as intended.

### Steps to reproduce
- Use RTL

### Screenshots
1. Multiple forward button:

![image](https://user-images.githubusercontent.com/34171942/107117197-cfbed680-688d-11eb-9f74-6787aae85db2.png)

2. Media editor multiple forward button:

![image](https://user-images.githubusercontent.com/34171942/107837983-da5efb80-6db8-11eb-97cf-c44f35e30a6d.png)

 

### Device info

**Device:** HTC M9
**Android version:** 7.0 or higher
**Signal version:** 5.3.12

**Comment by fumiakiy** [comment]
Hi @Xashyar , do you mind if I ask you to split the issue to two, so that the new one is solely about the "Forward/Reply" button on the toolbar? I have a fix to the `1.` and `2.` which is very simple one-liner, while the fix to `3.` is going to be a workaround to [an Android bug](https://issuetracker.google.com/issues/37138973) that require moving resource files here and there.

**Comment by Xashyar** [comment]
> Hi @Xashyar , do you mind if I ask you to split the issue to two, so that the new one is solely about the "Forward/Reply" button on the toolbar? I have a fix to the `1.` and `2.` which is very simple one-liner, while the fix to `3.`
With pleasure, I moved it to https://github.com/signalapp/Signal-Android/issues/11006

**Comment by Xashyar** [comment]
@fumiakiy 
With pleasure! I moved it to #11006
