### ISSUE TITLE
Some short codes aren't working

### ISSUE THREAD

**Issue by soleera** [signalapp/Signal-Android#10935]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
All short codes have a country code (in my case +64) added to them. This seems to be fine for 4 or 5 digit short codes, but 6 digit short codes like 771005 can't handle having a country code attached to them and messages sent to these numbers fail.

### Steps to reproduce

 - Attempt to send a message to a 6 digit short code like 771005 

**Actual result:** 
An error occurs: "Message could not be sent. Check your connection and try again."

**Expected result:** 
The message should be sent to the correct short code.

### Screenshots

![Screenshot_20210208-121236](https://user-images.githubusercontent.com/25336289/107162325-269beb80-6a07-11eb-893a-2b190cef6086.jpg)

### Device info

**Device:** OnePlus 8 Pro IN2023
**Android version:** Oxygen OS 11.0.2.2.IN11AA
**Signal version:** 5.3.7.1

### Link to debug log

https://debuglogs.org/a68861d1911dc8413d0caac9196e31d25a8f474f4e3568d4f45e945a60c64713

**Comment by samueltardieu** [comment]
I can confirm. Signal is also set as my text messages application. When I tried to send "STOP" to "36180" as directed in a spam text message to be removed from their lists (as is classical in France), I couldn't use Signal because it expanded the number to "+3336180" which does not work. The network must receive "36180" as the whole number, and this holds for other short numbers.

Signal could either not add a country code to short numbers (up to 6 digits ? harcode the few countries with less digits in their phone numbers ?), or not add the country code to numbers not in a canonical format (in France and most countries, phone numbers not starting with "0" should not be expanded as they denote special numbers).
