### ISSUE TITLE
android crash on startup

### ISSUE THREAD

**Issue by ErikDohmen** [signalapp/Signal-Android#10951]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I start the app, it is instantly crashing again. The moment I've put my phone in flight mode, the problem stops. I tried to send the report, but before that is finished the app crashes again. So there's not enough time to send the report. And as there isn't a way to copy paste the report, I can't see a way to put it here sadly enough.

### Steps to reproduce
* start the app
* that's it, it crashes

### Device info
**Device:** Pixel 5
**Android version:** 11
**Signal version:** 5.4.1
phone is just a couple of days old, fresh installation.

### Link to debug log
No option to add the debug log, but for what I can see it crashes with no notification on the method getContactStorageSyncIdsMap (RecipientDatabase.java line 1233).
As I've checked what was on that line, I removed all my memberships for the groups I'm in and removed all the groups afterwards as well. Therefor I thought there wouldn't be an option anymore to crash on this matter. But still, the app crashes. Also after clearing cash, remove the app, reinstall the app. Then it works.
But the moment I try and install with a backup (even the one after clearing all the groups) it still crashes

**Comment by C-Fergus** [comment]
Same issue here, I was recently added to a group chat where I think one of the members did not have Signal and so I had to set Signal as my default messaging app. This made the typing prompt at the bottom of the screen to disappear from that chat specifically which was fixed by closing and re-opening the app. I messaged to the chat and received some messages and everything seemed to be working as normal.

I then sent a message as a reply to another message and the app instantly crashed and now I am having the same issue as Erik.

### Device info

**Device:** Huawei P Smart 2019
**Android version:** 10.0.0.296
**Signal version:** 5.5.5
