### ISSUE TITLE
People get kicked out on group update

### ISSUE THREAD

**Issue by scroom** [signalapp/Signal-Android#10953]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
For several years we have been using a signal group with the family. A few days ago, this old type group was automatically converted to a new type group. Unfortunately, this removed two group members whose Signal versions are apparently too old. These people can also no longer be added to the group. Unfortunately, old type groups can also no longer be created, so these people are now excluded from family chat.

I think the new features for new type groups are great. However, groups should not be automatically converted if people are excluded in the process.

**Comment by Dhanurjan** [comment]
Tell them to update their applications on their devices. And try to add them again.

**Comment by Sgn-32** [comment]
This migration is a manually migration. Someone in this group has pushed the "Upgrade"-button.

https://community.signalusers.org/t/request-to-upgrade-to-new-group-is-too-pushy/27953

https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-4-release/27904/68

**Comment by FlyThePlanet** [comment]
> Tell them to update their applications on their devices. And try to add them again.

Providing they can.
When you have the grand mother using an iPhone 5 running perfectly well but now stuck on iOS 10.3.3 and Signal 3.9.1.1 what do you do?

> This migration is a manually migration. Someone in this group has pushed the "Upgrade"-button.

Well, things have changed.
Since this morning group admins are not given the choice anymore.
They are now BANNED from writing until they upgrade the groups, so until they exclude all their group members who can't follow!

As you can see on the screenshot below, since this morning the request for upgrade is now covering the writing area and there's now no way to remove it!!!

![image](https://user-images.githubusercontent.com/39710808/114029054-6ea98400-9879-11eb-8068-a7923a38cd52.png)

It's really becoming unacceptable!
You can't ask user who can run Signal perfectly fine to change their phone just for 1 app.
Leave them connect to the group they are already members of, even with limited functionalities.
