### ISSUE TITLE
Shared picture sent to wrong contacts

### ISSUE THREAD

**Issue by bepaald** [signalapp/Signal-Android#10963]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
When sharing a photo from gallery, the photo is sent to a different contact than was selected.

My brother recently sent me a picture that was intended for another contact, he said he was quite sure he selected the right contact and that it had happened before, but we sort of shrugged it of. Since then, he has been extra careful and observant when sharing pictures. Just now, it happened again, and this time he is 100% sure he chose the correct contact. I told him to immediately create a debug log, so now I'm filing this bug for him. I would say this is a big deal. It is hardly a problem for my brother and his contacts, but it's not difficult to imagine this causing major problems.

### Steps to reproduce
- Find a picture in your gallery app, choose share -> signal
- Contacts appear, pick ContactA
- the Picture appears in preview mode, full screen, so the rest of the chat is not visible, however my brother states (as he is being extra careful) he consciously noted the text "*Message to ContactA*" in the (empty) message text box.
- Hit send
- After hitting send, the fullscreen preview with the "*Message to ContactA*" text box is presented again, and can not be easily left. Apparently the back-button needs to be rapidly tapped to leave this screen. A single 'back' will just re-show it.

At this point my brother gets a thank you for the picture from ContactB, not the intended recipient of he message. And indeed, the picture now shows in the conversation with ContactB, and ContactA has not received anything.

### Device info
**Device:** Samsung S9
**Android version:** 10
**Signal version:** 5.3.12

### Link to debug log
The message that was unintentionally sent to ContactB has timestamp 15:23:46
https://debuglogs.org/3a2a606e1dd0710fe6b95ee6f93500103aaa37c35abe7e3248aefa8debc76318

**Comment by antonok-edm** [comment]
The same thing just happened to me as well on Signal 6.33.3*.

This is a **serious** issue to have in a "secure", "private" messaging app. Luckily for me, the image I shared was not particularly sensitive, but having images sent to contacts selected at random is unacceptable for users with _any_ expectation of privacy.

@greyson-signal @nicholas-signal @cody-signal @alex-signal @jrose-signal 

<sub>* I know, it's not 100% up to date but I looked through the commit logs and didn't see anything addressing this recently, either.</sub>

**Comment by greyson-signal** [comment]
The specific variation of this bug was fixed years ago (it ended up being tracked in a different issue). Did you experience the _exact_ same thing? Including checking the contact name? I ask because by far the most common thing that happens is that people accidentally tap a different/extra name during contact selection and don't realize it. However, we can't really diagnose it unless you send us a debuglog and the sentTimestamp of the message in question.

You can get a debuglog link via Settings > Help > Debug log, and you can get the sentTimestamp by long pressing a  message, selecting "Info", and then long press the sent time in order to copy the timestamp. Thanks!

**Comment by antonok-edm** [comment]
@greyson-signal thank you for the prompt, detailed response :pray: 

> **by far the most common thing that happens** is that people accidentally tap a different/extra name during contact selection and don't realize it.

Based on my investigation below, I'm going to assume this was my own fault, but it sounds like this issue is common enough that the UX could benefit from some modifications to make this less likely to occur in the future.

## Problematic UX

Currently, it's possible to select an additional recipient of a forwarded message while their name and selection indicator are _completely hidden_ behind the `Add a message` popup.

If that happens, the only feedback is that their name is added to the list of pending recipients. That list is small, could be easily obscured behind a thumb while it's changing, and isn't visually apparent when it's incorrect.

## UX recommendations

1. Ignore touch interactions for recipients close to the extreme top and bottom of the list, such that it's impossible to select one while their name and selection indicator aren't visible.
2. Add recipient thumbnails to the list of pending recipients, making them more visually distinct and recognizable at a glance.

## Investigation details

I believe what I've done was this:
1. Find a previously sent photo in a conversation
2. long-press the image and press `Forward`
3. select my intended group chat to send to
4. add a message
5. send

I'm noticing now that step 3 does indeed have potential to add more than one recipient, which, admittedly, I hadn't seen earlier. So it's **hard to rule out an accidental tap**. Judging by the timestamps on the previous messages, it looks like these two recipients would have been adjacent on the list. The intended recipient would have been first, with the unintended recipient directly below. I had to scroll down to reach that point in the list.

In case it's useful, the timestamps are
```
1698801236441   intended image
1698801236768   intended message

1698801236695   unintended image
1698801236890   unintended message
```
although I'm unable to access my debug log; it doesn't progress past the loading spinner.

**Comment by antonok-edm** [comment]
Ah, I see https://github.com/signalapp/Signal-Android/issues/13239 now. I didn't even realize you could literally click _through_ the popup - that is a good catch :sweat_smile: 

I was honestly referring to parts of the visible list, just where the relevant entry is _mostly_ offscreen.

Abusing that convenient screenshot even further...

![more-hidden](https://github.com/signalapp/Signal-Android/assets/22821309/de180b6d-0bde-4192-a557-6dd409604650)

The area I've highlighted technically _doesn't_ have anything drawn over it, but it's part of an entry in the list that can't be read because the entry's text and indicator are obscured.

Some UI designs change the background color of the entire rectangle for list entries, which would have made it possible to tell if it was selected, but the only indicator that an entry has been selected here is the checkmark getting filled. If the checkmark can't be seen, accidental selection can't be noticed, and I doubt users ever intend to select list items in that position either.

This can happen at the top of the list viewport as well - I hope that makes sense based on what I described, but I can make a new screenshot if it's not clear.

**Comment by greyson-signal** [comment]
Ah I see, I'll forward this info to our designers and see if they have any suggestions. Thanks!
