### ISSUE TITLE
BiometricAuthentication - unlock with pin fails

### ISSUE THREAD

**Issue by Kwasow** [signalapp/Signal-Android#11029]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Selecting the "Use PIN" option does not unlock the app.

### Steps to reproduce
- Lock Signal
- Open Signal and choose "Use PIN"
- Enter the correct pin
- Confirm
- Unlock with PIN again

**Actual result:** The app unlocks after second try
**Expected result:** The app unlocks after first try

### Device info
**Device:** Redmi Note 9 Pro
**Android version:** 10.0
**Signal version:** 5.4.9

### Link to debug log
https://debuglogs.org/3e961dc8459bcce79bce155718bec3ee04118836ab5a862b4f8373b74400c153

Added after editing: https://debuglogs.org/e8c2116ee126f0e0892e48047d4d094efa76f9d16c81fa5e2e76911851e5e14d

**Comment by Kwasow** [comment]
Introduced in 3c4252a933a800f5f6dd8ec61bda4ec113350903

**Comment by Kwasow** [comment]
If it may have anything to do with it: when I select the "Use PIN" option a system app opens for PIN input (I mean - not a pop-up). I don't know if this is standard Android behavior or if it's a MIUI implementation.

**Comment by Kwasow** [comment]
Updated issue description and added a new debug log

**Comment by cody-signal** [comment]
Hopefully this will be fixed in 5.4.10, please try again when that drops soon. Apparently API 10 and androidx.biometric is a hot mess so we're skipping it for Android 10 but thankfully the simple biometric integration works well for API 10 on the devices we've tested with so far. 

If don't want to wait and you build your own app, you can try applying this patch: https://gist.github.com/cody-signal/f296508c190b102cd8b81be551acf7c3#file-bio-patch

**Comment by Kwasow** [comment]
It is indeed fixed in 5.4.10, thanks!
