### ISSUE TITLE
Signal won't ring when receiving incoming calls, instead only notifies of missed calls

### ISSUE THREAD

**Issue by CyberBismarck** [signalapp/Signal-Android#11023]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal will irregularly not ring when my phone receives a Signal voice call. Instead, it will simply notify me that I have missed a call once the caller hangs up.

This issue doesn't happen always. Sometimes the calls will come through as normal when attempting to replicate the problem, and I cannot identify any pattern that could be causing the bug to happen.

The last instance of this happened less than an hour ago. I missed a call from a user on an iPhone 11 (running iOS 14.4 and using Signal version 5.4.0.17).

I have submitted below the debug logs for both my Android 11 and their iOS 14.4 devices, taken immediately after the bug happened.

### Steps to reproduce
- Receive a voice call.
- Signal will give no indication that there is an incoming call.
- Once the caller hangs up, Signal will announce that there has been a missed call.

**Actual result:** The user will not be notified of the call until the caller hangs up.

**Expected result:** Signal will ring as normal, and allow the user to answer the call.

### Device info
**Device:** Samsung Galaxy S20
**Android version:** 11
**Signal version:** 5.4.7

### Link to debug log

Samsung Galaxy S20 (failed to receive the call):
https://debuglogs.org/da0649264affb38dbb596e40f98f8a16b5f58daeea16708e2a09712a5b0225de

iPhone 12 (initiated the call):
https://debuglogs.org/87451f2ae4325503bc921641c529d5d43857f8f831c209295644dc83eedf4653.zip

**Comment by Rhahkeem** [comment]
Seen this happen from time to time too. I ended up just changing the ring tones (basically unset and reset). See if that helps any

**Comment by CyberBismarck** [comment]
> 
> 
> Seen this happen from time to time too. I ended up just changing the ring tones (basically unset and reset). See if that helps any

Yeah, I've tried that in the past, but it hasn't had much of an effect; the bug still happens occasionally.

**Comment by dotlineX** [comment]
Yeah happens to me too sometimes.

**Comment by samishk87** [comment]
This happens with me and my family every day, app doesn't ring but shows missed call notification.

Android: Android Pie 11
Device: Samsung Galaxy M30s

I am a beta tester of the app and I up to date keep latest version of app.

**Comment by sailbird** [comment]
Major breakthrough! This has been occurring on and off for years. It also manifests as a failure to make a ping sound when a text message is received. I finally believe I know how to work around it. Furthermore, my workarounds should enable someone with the source code to find the bug:

1. Reinstall Signal. This is a terrible option because (a) you will lose all your history and (b) you'll need the SIM that you used to register your Signal number, which should be different from your actual number for obivous security and flexibility reasons. As soon as the registration SMS arrives (assuming you even still have the registration SIM in working order), it's like flashing a giant neon sign over your head that says "Dear World: the person with this Signal number is standing right here at this GPS."

2. Update Signal manually (if it's not automatically updated) via Google Play (or the App Store if this also occurs with the iOS version). This will fix the problem for a while as well, completely independent of what the update actually changes. Already using the latest version? You're screwed until the next one comes out.

...and then, in a matter of weeks to months, it will randomly go into no-notification mode again.

The implications are quite clear: Signal's datastore gets either corrupted or desynchronized with the OS such that only an upgrade or reinstall fixes the problem. I would imagine that it's quite easy for the Signal team to figure out what sort of reinitialization occurs upon an upgrade, which would then reveal the particular part of the state that's getting wonky.

Meanwhile, if this can't be root caused, then it would be greatly helpful to have a menu option that says "fix broken notifications". Either that, or every time you open the app, it tells the OS "for the millionth time, I want my damn notifications enabled!"

This is probably the worst and longest lived Signal bug. It literally destroys its utility as a messaging app. I realize there are 1200 open issues (many of which being duplicates, but still). Nevertheless, the significance of fixing this one particular issue can hardly be understated.

Friends have shouted at me, colleagues have been pissed off, and family members have assumed that I've been neglecting them, all because of this fucking bug. Enough is enough. Maybe it's not even a Signal issue, but it deserves to be a high priority for the team.

**Comment by greyson-signal** [comment]
@sailbird Would love to get a debuglog from you. The most common cause of this problem is not within Signal itself, but rather that the device itself limits the push notifications it forwards to our apps, usually in the name of 'battery optimization'. So knowing some more information about your device would be helpful. 

Of course sometimes there's other issues too, so I've forwarded this bug to our calling team. A debuglog taken after you've experienced the issue would help them too. Thanks!

**Comment by jinnko** [comment]
Have seen this too and contacts report the same regularly, both on Android and iOS.  I disabled battery optimization long ago hoping it would help, and it did help a bit, but this still occurs occasionally.  In my case what I've noticed is there's no notification until the caller gives up, at which point there's a visual notification but no sound or vibration.  Will submit, or have contact submit, a debug log on the next occurrence.

**Comment by sailbird** [comment]
@greyson-signal Thank you for looking at this. Unfortunately it's back in a notifying mood at the moment, so there's no log to submit. While I can certainly believe that battery optimization might cause the same symptoms, it's hard to see how that would be the case here, as it's temporarily cured by upgrading to the latest Signal release at any given time (regardless of what actually changed in the app). Would that somehow reset the battery optimization policy? Maybe, that would be a huge Android design flaw.

All I can say is that I'm trying to be really attentive to what I do with my phone, so the next time this occurs, I will hopefully be able to tell you what I was doing when it started happening. The problem, of course, is that I won't realize anything is wrong until someone tries to call me. Even then, I might just think I didn't notice the alert. All this means that the trigger event might be hours or even days before the manifestation, which is why I think the most promising line of attack is to look at how Signal's storage state changes across upgrades (or the state of the data structures that it shares with the OS).

**Comment by CyberBismarck** [comment]
I've got another debug log.

Call just came in from an iPhone user, but Signal only notified me that I had missed it once the caller hung up. I called the caller back and, once the conversation was over, I submitted the debug log:

https://debuglogs.org/636c9e94bb0dcb918f293965a8d5d2644b588c2d5f8d5115de3dc7c9bbe58825

**Comment by jonahbeckford** [comment]
FYI: I don't think this issue has the same root cause as the one I opened (#11095). The debug log https://debuglogs.org/636c9e94bb0dcb918f293965a8d5d2644b588c2d5f8d5115de3dc7c9bbe58825 shows:

```
03-08 13:12:17.656  7355  7446 D IncomingMessageObserver: Network: true, Foreground: true, FCM: true, Censored: false, Registered: true, Websocket Registered: true, Proxy: false
03-08 13:12:17.656  7355  7446 D IncomingMessageObserver: Reading message...
...
03-08 13:12:33.477  7355  7355 I WebRtcCallActivity: Hangup pressed, handling termination now...
```

The "Reading message" means it got past the missing notification problem from my issue.

**Comment by sailbird** [comment]
@jonahbeckford Thanks. So at least now we know there are similar manifestations for different reasons.

**Comment by szotsaki** [comment]
This is most probably a duplicate of https://github.com/signalapp/Signal-Android/issues/7733. May I ask to close this issue (to avoid having duplicates) and continue the conversation in the linked ticket?

**Comment by CyberBismarck** [comment]
> This is most probably a duplicate of #7733. May I ask to close this issue (to avoid having duplicates) and continue the conversation in the linked ticket?

Yes, that would seem to be the case. I'll close it.

**Comment by CyberBismarck** [comment]
Thanks, @szotsaki
