### ISSUE TITLE
App converted a link with a dot at the end to an actual dot

### ISSUE THREAD

**Issue by bigfatbird** [signalapp/Signal-Android#11061]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When posting a link with a dot at the end (https://en.wikipedia.org/wiki/Fontaines_D.C.) the dot at the end will be converted to an actual dot. So the link wont work anymore

### Steps to reproduce
- Post link with a dot and send to a chat partner
- click the link
- link does not work

**Actual result: broken link
**Expected result: A fully working link

### Device info

**Device:** Google Pixel 3a
**Android version:** 11.0.0
**Signal version:** 5.4.7

**Comment by Nisc3d** [comment]
Ironic that Github does the same.

**Comment by greyson-signal** [comment]
It's tricky, but I'd wager that most of the time you *do* want periods at the end of a link to be an 'actual dot', likely because the link is at the end of a sentence. Our linkifier is just the stock Android linkifier, so I imagine that we behave the way most apps on the platform behave, so I'm gonna close this. I recognize there are situations that it will break links, but I think the current behavior will be correct more often than not.
