### ISSUE TITLE
Landscape Video Calls on 5.4.12 orientation problem, counter intuitive

### ISSUE THREAD

**Issue by gab81** [signalapp/Signal-Android#11072]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

**Bug description**
The landscape video call mode does not work in a logic fashion, this is counter intuitive.

**Steps to reproduce**
During a call in landscape mode you would normally rotate the phone to the left hand side for going on "landscape mode", i am right handed, that's standard, so your earpiece speaker goes on the left and the usb port on the right - to be clear.

Videos look upside down on main screens when both phones rotate to the same side.

- Start a video call (phone 1 calling phone 2, NO group call)
- Rotate phone 1 on the left side (so earpiece speaker is on the left and usb port is on the right)
- Rotate phone 2 that receives the call also on the left side (so earpiece speaker is on the left and usb port is on the right)

**Actual result:** Phone 1 looks upside down, Phone 2 looks upside down
**Expected result:** Phone 1 looks OK and Phone 2 looks OK as well **without the need of rotating further phone 2**. or phone 1.

THIS is possible if you rotate phone 2 on the opposite side, so if the phones are "kissing" each other on the usb port if you have both in front of you.

please see screenshots below:

### Screenshots

**Photo 1**

User 1 calls user 2, they both rotate to the LEFT and it’s WRONG, Signal doesn’t rotate on both receiving screens, even though the selfie camera shows correct angle (little screen)

![image](https://user-images.githubusercontent.com/54513687/110236061-127ad980-7f34-11eb-84bc-3d87b9121653.png)

**Photo 2**

User 1 calls user 2 and when user 2 realises that something is wrong then something counter intuitive happens, **ONLY user 2 rotates the phone on the other side**, so usb connectors are effectively “kissing” each other, that’s what i meant, and now indeed it looks CORRECT.

![image](https://user-images.githubusercontent.com/54513687/110236074-21fa2280-7f34-11eb-90c3-d16bd5b3f4c4.png)

### Device info
**Device:** Samsung S8 SM-G950F
**Android version:** 9
**Signal version:** 5.4.12

### Link to debug log
https://debuglogs.org/7a3da03e2a06caaaf27498a6081883e5963ee7262183515a780860259cee065d

**Comment by gab81** [comment]
additionally, observed today **that the first time your own video will show ok**, whether you orient left or right, BUT the next time it looks upside down on either side the phone is rotated to in landscape mode. 

so, this is your own video using back camera (not selfie). if you start video in landscape first is ok.

if you start in landscape then back to portrait then back landscape NOT ok.

**Comment by gab81** [comment]
I just observed this in 5.5.5

during a video call, if you use the back camera (not selfie one), your own preview video feed in landscape mode is always upside down. the receiving end will see it OK if phones are like mirrored so facing each other on the usb side like kissing, if you had both in front of you. if both phones are oriented in the same way is always upside down.

**Comment by TeraHz** [comment]
This has been a problem for a while on Android. As described in the OP, it only works in a very specific orientation and it easily breaks if you switch front/main cameras.

**Comment by gab81** [comment]
hmhm on other apps your own video always looks properly oriented though, your video preview i mean.

it's true that the back camera also is wrong on whatsapp i think.

your own video preview should be straight though, i was doing a video call from my android to signal desktop to my parents showing our house, so using the back camera and for the whole call i had the video preview upside down, so difficult to frame the camera understanding what i was showing.

can't we find a solution instead? thanks

**Comment by rawlife56** [comment]
Google's duo implements the rotation perfectly out of all messengers. Element handles it decently as well. May be we can fork them @greyson-signal 

Also referencing few other rotation issues 
#10975 
#11018

**Comment by unpack5** [comment]
on the forum we have a similar problem ([link](https://community.signalusers.org/t/rotate-video-call-picture-manually/17495/11?u=cargo)), the root of which I believe is the same as of this issue. in short, with certain platform (desktop vs. mobile) and orientation (portrait vs. landscape) combinations, it' impossible to see each other in the correct rotation.

no one answered our concerns, so I'll post here as well. we'd be very glad to hear some feedback from the developers, as this is a really nasty UX bug that makes it hard to use Signal for video calls.
 
---


I have a similar issue in video calls.

my device is an **Android 9 phone** . at the time of our last call I had Signal ~~5.4.12 APK~~ 5.7.6, APK version downloaded from the Signal website.

my contact’s devices are an **iPhone 8** and a **Macbook** (I don’t know the model). I don’t know what version his Signals are.

there are three settings in which we can do video calls:

1. when I need to hold my Android in **portrait** mode and he needs to use his iPhone in **landscape** mode.
2. when I need to hold my Android in **landcape** mode and he needs to use his iPhone in **landscape** mode.
3. when I need to hold my Android in **landcape** mode and he needs to use his **Macbook** (non-rotatable.).

in **none** of the above settings can we get to a point where **both of us sees the other in the right orientation** .

* it’s regardless of who initiates the call.
* it’s regardless of which of his two devices my contact uses.
* when he appears 90 degrees rotated, my gut reaction is to simply rotate my phone, but as you guessed, Signal has the orientations locked, so if I see him correctly, then he sees me rotated 90 degrees.
* I played around with my phone’s manual/auto orientation switch, to no avail.
* he did the same on his phone, to no avail.
* I experimented with rotating my phone before *or* after pressing the video call button in the chat, to no avail.
* Android–portrait+iPhone–portrait and Android–portrait+Macbook are not desirable combinations in our use case, but we tried both for curiosity’s sake (we won’t be using these combos even if they’re fixed). the former combo causes cropping where at least one of our self-views shows a different view that what the other sees (usually the lower half of my self-view is not visible to him). in the latter combo, I see him extremely cropped (basically unusable), but he sees me properly and his own self-view is also okay. I have no idea what’s going on there.

is there anything I can do to make the video work for us, or are these issues already fixed in a newer release? if neither, would you please look into it? we’d like to use Signal but can’t really until the video works.

**Comment by rawlife56** [comment]
@unpack5 I don't think it's solved. Android to android calls also act in weird ways wrt rotation. They should at least pass an intent to rotate the entire screen, just rotating the the in-call UI is confusing AF for everybody.  
(Just the icons rotate and everything else is in the portrait direction, how can somebody expect a regular user to understand this really odd design ?)

**Comment by SilverMight** [comment]
Any fix for this? This makes landscape calling unusable...

**Comment by street-grease-coder** [comment]
Yep, that was it... After all donations to signal the rotation issues aren't fixed after almost a year? 

I'd rather have less privacy than the other person rotating in confusing manners because they're exactly laying sideways on the edge between vertical and horizontal position. 

I find myself using Whatsapp in the end, since Signal doesn't even have an option for turning landscape/portrait mode on/off manually. This is ridiculous. Bye signal...

**Comment by GoldenDragonfly** [comment]
This bug has reported on signal form with fix. Havn't fix till. https://community.signalusers.org/t/give-option-to-disable-video-rotation-on-video-call/42264
