### ISSUE TITLE
Lots of "checking for messages" notifications, but still failing to give me new message notifications.

### ISSUE THREAD

**Issue by ElBiggus** [signalapp/Signal-Android#11071]
- [ X] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I get regular "checking for messages" notifications which seems to be an attempted workaround to earlier issues around not getting new messages if Signal has been idle for a while, but the original faulty behaviour seems to persist and I have to regularly open Signal to ensure new messages are dealt with.

### Steps to reproduce
- Don't open Signal for a while.

**Actual result:** New messages are not received (or notifications are not displayed; it's hard to tell what the actual culprit is).
**Expected result:** Notifications are displayed when a message is received.

### Device info

**Device:** Xiaomi Mi A2 Lite
**Android version:** 10.something
**Signal version:** Whatever the latest Play Store version is (checking means I will have to restart this issue).

**Comment by greyson-signal** [comment]
Hi there! Can you please post a log after you get a 'checking for messages' notification but don't receive any messages? Thanks!

**Comment by steelowheel** [comment]
I have a Oneplus phone and Xiaomi Miband 4 wearable. No problem with my phone, but I get notifications to my Miband saying "Checking for messages".

**Comment by lebbe** [comment]
I am bothered with this message all the time as well, Samsung Galaxy S10. Several times a day, a notification "Checking for messages" pops up, and it is really disruptive, since it uses the sms/messge icon. I no longer know if I actually got a new message, or if it is just checking for messages.... Where can I check the logs?

**Comment by MEESTER-SUPERMAN** [comment]
I've experienced this too. The Android app notifications are pretty unreliable for me in general. I know inbound messages are coming in from my fitness tracker and from Signal Desktop, but the Android app has an annoying delay, and notifications won't present themselves until you open the app.

This has happened to friends and family as well, and it's putting them off from using Signal, which is a shame since I've been bringing a lot of people over from WhatsApp.

I'm wondering if this is down to Android memory management for the application. In all of the affected cases, we've made sure to set the battery optimisations to 'Ignored' where applicable.

**Comment by greyson-signal** [comment]
I believe the original issue here was the result of a bug that caused this notification to show up more often than desired, which was fixed a while back. You still make see it from time to time, but there should be at least 6 hours in between each instance.

@MEESTER-SUPERMAN You should look at #8692
