### ISSUE TITLE
Animated stickers slows down the app

### ISSUE THREAD

**Issue by Dhanurjan** [signalapp/Signal-Android#11087]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm using several animated sticker packs and if I open up the keyboard and stickers pack all the animated stickers animating in low fps and signal app getting too slow to respond.

### Steps to reproduce
- go to a chat
- select  sticker icon near keyboard signal message bar
- keyboard opens up with animated stickers packs

**Actual result:** all the animated stickers starting to animate in low fps and the app is getting so slow to respond until I close the keyboard
**Expected result:** all the animated stickers animate smoothly and the app runs smooth

### Screenshots
![signal-2021-03-11-084319](https://user-images.githubusercontent.com/64047298/110731024-8d4f3780-8247-11eb-802b-54905d5aa510.jpeg)

### Device info

**Device:** Nokia 2.2
**Android version:** 10
**Signal version:** 5.4.12

### Link to debug log
https://debuglogs.org/c5adcf36758e6ee8920f10070021674157477eb6f55cfc14bec8d05715dd1b43

**Comment by Johndeep** [comment]
I want to add to this problem and extend it.

Since Stickers or animated "whatever they are" are features of Signal, I would **really** appreciate
- [ ] the option to turn off all **unnecessary** Sticker/gif/"whatever is posted" animations

Yes, of course it is possible just to not use these things at all, but if you're at the receiving end to chat with someone, who cannot stop using it, it would be really nice to be able to just disable all the animations. This is by the way an issue on all platforms (Android/Desktop). On Desktop it eats up a significant amount of CPU power, just because Electron..

Discord is a good example how it is better done: If you really need to see the animation, click on (or hover over) it, else just leave it static.

**Signal version:** 5.17.3
