### ISSUE TITLE
Suggestion: dialog to warn users of Android battery optimization

### ISSUE THREAD

**Issue by ttshaw1** [signalapp/Signal-Android#11108]
I only recently figured out that Android had been crippling Signal for battery optimization. It seems to be a commonly acknowledged issue in the dev community, but as someone who knows essentially nothing about Android or mobile development, it took me a few months to figure out why some incoming SMS messages seemed to vanish from the face of the earth. Can we add a dialog box to warn users of this issue when they set Signal as their default SMS app? Signal recognizes when it's the default app, so it should be possible to throw up a dialog box when it detects the transition. Or possibly some other, cleaner, condition.

Example text: "Users have reported issues receiving text messages caused by Android's battery optimization. Ensure that Signal has the same battery optimization settings as your phone's default messaging app."

**Comment by greyson-signal** [comment]
Yeah, this is a problem we're dealing with and attacking on several fronts. The problem is that every manufacturer is different, so showing that type of prompt across the board wouldn't be ideal. We are making advancements though :) Also in the future, please post suggestions/discussion topics on the [forum](https://community.signalusers.org/). Thanks!
