### ISSUE TITLE
Chat backups are not being created - without errors or any other feedback

### ISSUE THREAD

**Issue by frans-fuerst** [signalapp/Signal-Android#11131]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Chat backups are not being created _at all_, tapping on "Create backup" has no effect - no errors or messages pop up. I can de-activate backups and re-activate them - I'm provided with a new passphrase, check the confirmation and press "enable backups", but I'm now where I started, "Last backup" only shows "Never".

I tried to wait a couple of days hoping the backup starts automatically, but no.

There are other bug reports describing a similar problem caused by the inability to write on the external SD card. I tried to eject the external SD card, but with no effect.

Looking into the debug log shows _no_ entries regarding backups.

Background-Info: 

I had Signal 4.49 installed on an older Galaxy Note 4, switched to a new phone (same Signal identity) and I now wanted to make a backup from that old installation. Backups worked before I stopped using that phone but I don't have the key any more. So I tried to make a backup by re-activating backups but faced the above problems. I then updated to version 5.4.12 and even re-registered on that old phone. The App works fine but no backups will be made at all.

Backups on my current phone - same account - work fine.

### Steps to reproduce

- start Signal, go to "Chats"/"Backups", 
- "Turn on" Backups
- Confirm "I have written down...", press "Enable Backups"
- Try to tab on "Create Backup"

**Actual result:** Nothing happens (no error, no message)
**Expected result:** Backup starts or error message describing a problem pops up

### Device info

**Device:** Samsung Galaxy Note 4 / SM-N910F / trltexx
**Android version:** 6.0.1 (N910FXXS1DQG5, N4S-Rom v13.3 - DQG5)
**Signal version:** 5.4.12 and 4.49 (taken from https://signal.org/android/apk/)

### Link to debug log

https://debuglogs.org/0d81b4b1f44d7647953ee333e9cf19428d56ae8c36f8fdb9fc91dd053ad97902

**Comment by sebthom** [comment]
Same issue for me on Galaxy S10 with Android 11. I tried using internal and external storage. I also enabled USB debugging but no errors are shown in the debug log when clicking on "Create Backup".

**Comment by hiqua** [comment]
Can you try with the last version, and submit a debug log if it still doesn't work? Signal 5.5.5 also has an account transfer feature, you could try it in your case. Can you also confirm that the backup folder is empty? If not, what does it contain? The log mentions the deletion of 2019 backups, are they indeed deleted? How much space do you have free on the device?

@sebthom please submit the debug log anyway, maybe there's some information anyway.

**Comment by sebthom** [comment]
@hiqua I rebooted my phone in the meantime, now the backup button works for me.

**Comment by frans-fuerst** [comment]
I now updated, retried, rebooted and again retried, but unfortunately with no effect.

Here is the new report: https://debuglogs.org/bc54d8062ee79030c85517ccf88ff97b15b43e6a0dc6d4801260edcae7930bcb

**Comment by hiqua** [comment]
There are a lot of warnings (lines with ` W `) that relate to a migration job, and the first sections indicates that a lot of jobs were happening or have to happen. I think these are DB migrations that happen when there are version updates. If these do not work correctly, I don't expect the backup to work, but it's not completely clear to me.

From your debug log, the last job happened at `1616755914755` epoch time (in ms), so that's Fri 26 Mar 2021 11:51:54 AM CET, right before you submitted the debug log.

What happens if you reboot and try again? Can you submit another debug log, just to be sure that these jobs are still there, with new timestamps?

Just to be clear, these are shots in the dark, I don't know have extensive knowledge about the code base (I don't want to give you too much hope).

**Comment by hiqua** [comment]
You haven't mentioned the new feature "Transfer account" that I referred to previously. Did you try it out? It's an option just under "Chat backups". I don't think it will work in your case, since it relies on the same mechanism as the backups, but it's worth trying. Maybe we'll get more interesting info in the debug logs as well.

**Comment by RequestPrivacey** [comment]
First post for me on Github, so I hope it fits/is relevant in this context: For me after hitting "Create Backup" it started and counted up, but after a certain count exited without error message (and still: "Last Backup: Never"). The storage of my phone was pretty full, so I deleted some other stuff and tried again. This time it finished without problems. So a info message stating that there isn't enough storage would be beneficial I think. Thanks for the work!
