### ISSUE TITLE
Play Services Error

### ISSUE THREAD

**Issue by shouyou10** [signalapp/Signal-Android#11139]
I have uninstalled Google Play Services on my device using adb. Before that I had no issue with Signal. But now I can not log in at all. Every time I try to to this prompts: "Play Services Error". Although it is self-explanatory, my question then would me if I want to improve my security by removing Play Services, will I not be able to have Signal?
![Imagepipe_0](https://user-images.githubusercontent.com/76897897/112714161-fe8e1c00-8ed0-11eb-84a2-572e11ff9c2c.jpg)

**Comment by hiqua** [comment]
You probably left your device in a bad state. Removing the Play Services using adb is kind of hackish, if you really want a device without these you should probably install another rom instead.

Signal works perfectly fine without Play Services. In your case, it's likely confused because it relied on it, and suddenly it's not available anymore. You could try to reinstall Signal, but again, you probably left your device in a bad state.

**Comment by shouyou10** [comment]
Honestly, by Almigthty's blessing, my device is in a proper state. There are reasons why I am not opting for a custom rom.
I tried reinstalling several times. But same result everytime. I really like Signal for being one of the best, if not the best, messaging app on the market. But then again, it is on the market (Play Store), not on F-Droid. And almost all of my apps are from F-Droid. So, I never had any issue for not having Play Services. I really would have loved to use Signal. But that may not be possible for the time being.
Thank for replying. Please continue you great work with Signal. My best wishes will always be for Signal.

**Comment by shouyou10** [comment]
Honestly, by Almigthty's blessing, my device is in a proper state. There are reasons why I am not opting for a custom rom.
I tried reinstalling several times. But same result everytime. I really like Signal for being one of the best, if not the best, messaging app on the market. But then again, it is on the market (Play Store), not on F-Droid. And almost all of my apps are from F-Droid. So, I never had any issue for not having Play Services. I really would have loved to use Signal. But that may not be possible for the time being.
Thank for replying. Please continue you great work with Signal. My best wishes will always be for Signal.

**Comment by hiqua** [comment]
APK available here: https://signal.org/android/apk/

Again, Signal is perfectly usable on a phone without Google Play Services, but if you modify your phone using adb after Signal has been installed it will be hard to avoid such bugs.

I believe Signal distinguishes between devices with or without Google Play Services when it's first launched. That's why it will rely on it even if you uninstall the Service, at least until you reinstall Signal.

**Comment by shouyou10** [comment]
I tried reinstalling the app. But with the same result. Also used your link to download the app for expert. But noting changed. Anyhow, thanks for your reply.

**Comment by bme13** [comment]
Don't have experience with removing play services myself but it's been mentioned in the community that it might be hard to do it right. Perhaps https://community.signalusers.org/t/signal-just-wont-work-without-google-play-services/14420/7 is of any help.

**Comment by z3r0r4** [comment]
I find it to be quite disappointing that the sentiment that's shown toward removing gapps via adb makes it seem like it's something that one should not be doing. Removing gapps via adb is a very easy way to restrict the grip of googles spy software on your device. Most apps continue to work, even if they might complain that g services are updating, in many cases the dialog can just be closed.

The actual issue is that **signal** doesnt attempt to try the non gapps route but instead just **refuses to work**.

**Comment by z3r0r4** [comment]
@shouyou10 there is a fix that worked for me which the above comment points to.
Instead of using:
`adb shell pm uninstall -k --user 0 com.google.android.gms`
use
`adb shell pm disable-user --user 0 com.google.android.gms`
> Package com.google.android.gms new state: disabled-user

to disable the google spyware.
This can be done after having already executed the first command.
After this Signal seems to work as intended without gapps
