### ISSUE TITLE
Signal doesn't work without GMS (no fixes?)

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#11154]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't register Signal on my device that has no Google Play Services.  
I know that, you've provided APK on your website, Burt it still shows the same result.  
Why don't you search for alternatives to GCM(Google Cloud Messaging) for push notifications rather than depending on Google.?  
I'm currently running it on my other that that GMS on it.  
If I don't have GMS installed, I'm supposed to use WebSockets?

### Steps to reproduce
- Install Signal on a phone that has no GMS
- Register

**Actual result:** The app does nothing but keeps loading, and becomes unresponsive.
**Expected result:** I should be allowed to register to use the app without GMS.!

### Device info
**Device:** Lenovo TB3-710F
**Android version:** 5.0.1
**Signal version:** 5.5.5

**Comment by miku86** [comment]
Hey,

why do you think it's because of no Google Play Services?
Maybe it's your very old Android version or something else.

On my end, it's working without Google Play Services.

**Comment by pixincreate** [comment]
@miku86, initially I thought it was because of Android version, which made no sense to me as the tab has no GMS running Android on Lollipop that doesn't even support sim-card.  
I received SMS verification on my other mobile after about **2 - 3** hours and finally I was able to access Signal on my tab.  
And yes, notifications on Signal apk are way too slow.
AFAIK, Signal is not supported on Tabs as it doesn't show up neither on **AuroraStore** nor PlayStore(Assumed as Aurora uses same API).  
_Suggestion_: **Why not use CDN instead of GCM for push notifications.? It's fast and responsive.**

**Comment by Kwasow** [comment]
It makes sense to deliver notifications through a 3rd party service to save time on development. Developing a service, that's constantly running on your Android device and making sure that it is not stopped by any background optimizations while working reliably and being easy on your battery is no easy task and takes a lot of effort to maintain.

Using a solution like firebase takes all that burden off of the developers and they can then focus on the product itself - building a stable app, developing secure protocols and encryption methods and protecting your privacy.

**Comment by manfromdownunder** [comment]
> It makes sense to deliver notifications through a 3rd party service to save time on development. Developing a service, that's constantly running on your Android device and making sure that it is not stopped by any background optimizations while working reliably and being easy on your battery is no easy task and takes a lot of effort to maintain.
> 
> Using a solution like firebase takes all that burden off of the developers and they can then focus on the product itself - building a stable app, developing secure protocols and encryption methods and protecting your privacy.

Using firebase is not protecting your privacy.  Firebase allows google to fingerprint you.  You are confusing security with privacy.

**Comment by EmberHeartshine** [comment]
> I know that, you've provided APK on your website, Burt it still shows the same result.

The Signal website version only includes a secondary update feature, and is otherwise identical to the Play Store release. You'll have to run a fork like [Twin Helix's Signal-foss](https://www.twinhelix.com/apps/signal-foss/) in order to truly disconnect from ~~surveillance~~ Google services.

**Comment by strugee** [comment]
@pixincreate I think you are confused as to what a CDN is. You can't build a push notification service out of a CDN (at least, not without some horrifically ugly hacks but probably not at all). I think you're also missing the fact that Signal can't "just" add a different push service. GMS works effectively because it is built into the Android operating system and has a special status that means it is not subject to Android's normal battery optimization. The other important thing about having GMS include a centralized system component is that it can maintain one connection for the entire device, which avoids waking up the radio more than necessary, etc., all of which saves battery life. Signal cannot add components into the Android operating system.

Note that GCM is only used to "wake up" the app. Actual messages, even in encrypted form, do not go through GCM (at least, last time I checked).

> If I don't have GMS installed, I'm supposed to use WebSockets?

Yes. When you say "why don't you search for alternatives"... WebSockets is the alternative.

In general you've been mentioning a lot of problems in this issue, but nobody can help you if you don't post a debug log. Please do so. (I believe there are instructions in the "submitting useful bug reports" page that you read.)

**Comment by KonstantMan** [comment]
I have the same problem with signal on Android 8, I have heavily degoogled my phone and I use netguard to disable any internet access. So I have noticed that signal notifications work only when I enable Google services, is there any way to install signal from a different source other than Aurora in order to receive notifications without the Google services?

**Comment by Krzmbrzl** [comment]
May I ask whether FOSS alternatives to FCM have been considered yet? There seem to be some available, one of which appears to be [UnifiedPush](https://unifiedpush.org/). This is also what the Element Matrix client will be going to use (see https://github.com/vector-im/element-android/pull/3448). Their approach seems very solid to me: If available, use FCM. Otherwise check for the availability of UnifiedPush and if available, use that. Only if that is not available either, use manual polling.

I guess the prio between FCM and UnifiedPush may be switched (implicating that someone who has UnifiedPush installed might rather use that instead of FCM) but either way this (or something like this) should solve the problem, shouldn't it?

**Comment by genofire** [comment]
UnifiedPush would solve the most problems ...

**Comment by genofire** [comment]
Still no reaction from the Team, so use UnifiedPush;(

**Comment by pixincreate** [comment]
I wanted to use Signal on a DeGoogled phone.

But the thing is, no custom ROM exist for my tab. I sideloaded Signal which worked. However, I'd debloated all Google stuffs. But still Signal checked for GMS package and started requesting it which I don't wanna give.

If it cannot work without Google, I'm ready to give up Signal. That's it.

**Comment by hiqua** [comment]
Signal's stance in that regard is simple and is now well documented across issues:
* regular phones with FCM are supported
* phones without FCM are somewhat well supported
* everything in-between is not, especially regular phones where the user tried to remove some system packages and ends up with a half-broken OS

Signal works fine on LineageOS without FCM.

**Comment by genofire** [comment]
Signal own implementation (beside FCM) drains unnessacary the battery (and has sometimes a delay).

UnifiedPush adds another option and the library has an [good fallback to FCM](https://unifiedpush.org/developers/embedded_fcm/) (if no other Push Distributor is installed).

This options is a generical way of pushnotification, which let the user handle the way of notification. Severaly ways are [implemented](https://unifiedpush.org/users/distributors/) already:
- FCM
- [Gotify](https://gotify.net/)
- [Ntfy](https://ntfy.sh/)
- [Nextcloud](https://github.com/UP-NextPush)
- Or [direct](https://unifiedpush.org/users/distributors/np2p/), if you have an Public-IP (or other proxy) to your android device.

**Comment by tiptoptom** [comment]
@genofire how can I tell the app to use Ntfy?

**Comment by genofire** [comment]
@tiptoptom Signal does not support UnifiedPush. So current you could not use Ntfy or any other UnifiedPush Distribution.

There are some Matrix Client, which supports UnifiedPush like:
- FluffyChat
- SchildiChat
- This PR on Element: https://github.com/vector-im/element-android/pull/3448
if you want to try UnifiedPush in the real world.

**Comment by xundeenergie** [comment]
I have Schildichat in heavy use on my android. And ntfy with up-provider (common-proxies). And it works like a charm.
Schildichat is "optimized for akku usage", it gets killed by my huawai p30 on every sleep AND wakeup (crazy thing).

But the notifications via ntfy are working. the only app is ntfy, which is not allowed to be killed, when the phone gets sleeping.

This is realy great stuff, and i would love it, if signal implements this.

**Comment by pixincreate** [comment]
Assuming that this issue will not be fixed, I'm closing this issue.

**Comment by genofire** [comment]
Thats really sad - and a lack against the matrix world, that signal does not use a secure way of push notification.

**Comment by pixincreate** [comment]
It never will.

Its really annoying for me to give sms permission to Play services in order for signal to register me in to use the app and they don't seem to care about it in any way.

I'll just let go it for now, and will eventually stop using Signal in the mean time in the near future. None of my contacts use it either..;-;

**Comment by Peltoche** [comment]
I guess the best solution is to move on Matrix with a signal bridge and the Element app. You can also try to move your the friends on it, that's what I have done. I have bring maybe 20 people to Signal and I have move them all on Matrix.
