### ISSUE TITLE
Voice messages sent from any computer stutter and glitch

### ISSUE THREAD

**Issue by chriskalos** [signalapp/Signal-Android#11161]
I don't really know what other information to give...

How to reproduce:
Send voice message from any PC app of Signal (macOS and Windows tested)
Often times the resulting voice message will include stutters, repetition of small sections, and other glitches.

Also there is another bug when playing back some voice messages that also makes them sound glitchy even though they aren't.

**Comment by hiqua** [comment]
If you play these messages on the desktop app, does the audio stutter?

If that's the case, then it wouldn't be a playback bug in the Android app, but some problem with the input on the desktop apps, so that would be a bug for Signal-Desktop.

Can you add debug logs of all the apps after having reproduced it?

**Comment by chriskalos** [comment]
If I record a message on PC, it will often stutter when playing on either PC or Android or iOS, because the actual sound file is created like that.

If I send something via Android that is not meant to be a voice message (e.g. a voice recording from my voice recordings app) it may or may not stutter when playing back within Signal on Android but apparently it does not stutter for the recipient.

During my testing right now, I actually cannot reproduce the bug, which is super annoying because it happens literally every day usually. I will get back to this when I manage to reproduce it, and I will attach debug logs.

**Comment by hiqua** [comment]
> If I send something via Android that is not meant to be a voice message (e.g. a voice recording from my voice recordings app) it may or may not stutter when playing back within Signal on Android but apparently it does not stutter for the recipient.

In this case, does it stutter on your desktop client as well?

Yes debug logs would help, hard to guess where these bugs come from otherwise. Also make sure you're using the latest versions. Just follow the bug report template next time, without the corresponding information it's hard to do anything.

**Comment by chriskalos** [comment]
> In this case, does it stutter on your desktop client as well?

No, which is why I assume it is a client-side Android issue. But again, I'll try my best to reproduce this and attach debug logs. I'm closing this for now and I'll make a new bug report when I have the appropriate information.

Apologies, I'm new to Github! Student developer and all...
