### ISSUE TITLE
Link preview disapears after manually adding text

### ISSUE THREAD

**Issue by bme13** [signalapp/Signal-Android#11198]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While sharing a link from e.g. the browser to Signal the link preview is shown as expected. However after adding a space or return and then some additional text in the message composition box or adding an emoji the link preview is gone. This does not happen for every link though. I can reproduce it with this kind of links: https://www.motorsport.com/motogp/news/marc-marquez-honda-return-portimao/6182143/
As a side note I've also noticed the hostname of the visited page is in the logfile. Not sure if that should have been redacted.

### Steps to reproduce
- Share link, e.g. https://www.motorsport.com/motogp/news/marc-marquez-honda-return-portimao/6182143/ to contact in Signal
- Add space/return to keep the proper link and then add text or emoji
- Link preview is gone

**Actual result:** Link preview is gone after adding additional text to link
**Expected result:** Link preview remains as long as the link is valid

### Device info

**Device:** Samsung S9
**Android version:** 10
**Signal version:** 5.7.5 (but also reproducible with 5.6)

### Link to debug log

https://debuglogs.org/01a5d405992d4540af0065f744668e82201a32169c5d3acf8af9e96c2907f181

**Comment by Herohtar** [comment]
I can confirm this issue in Signal 5.25.7 on Pixel 5 running Android 12.

It seems that it only happens with URLs that end with `/`. If you enter a URL such as `https://google.com/`, you can type as many spaces and newline characters as you want after the URL, but as soon as you type a non-whitespace character it will remove the link preview and "refresh" it. Typing additional characters after that will not affect the link preview.

This does not happen if the URL is of the form `https://google.com`, `https://google.com/#stuff`, `https://google.com/?q=test`, etc.

**Comment by fumiakiy** [comment]
What OP was seeing turned out not to be a Signal bug. The owner of the `www.motorsport.com` website should fix the issue on their website by returning `https` URL in their 301 Redirect response when the trailing slash was omitted in the request. Because Android doesn't by default (thus neither does Signal) allow insecure http request any more, the redirection failed and the link preview would not be generated for the URL whose trailing slash was omitted (for this website).

The interesting part is that the trailing slash gets removed by Android's LinkifyCompat when there is any character after word boundaries (read: whitespaces). So, giving `https://google.com/` or `https://google.com/   ` (has three trailing whitespaces) to [LinkifyCompat.addLinks](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-core-release/core/core/src/main/java/androidx/core/text/util/LinkifyCompat.java#:~:text=addLinks) generates a URLSpan that points to `https://google.com/` with the trailing slash, while giving `https://google.com/   a` to the same method generates `https://google.com` without the trailing slash. It's just how the underlying regular expression was written in [android.util.Patterns.AUTOLINK_WEB_URL](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/util/Patterns.java#:~:text=Pattern%20AUTOLINK_WEB_URL), which is not even publicly accessible.

We could say this is a bug in Android but in reality, behaving differently for a URL with and without a trailing slash is something the website should avoid in my humble opinion.

To summarize,

1. Writing or pasting `https://www.motorsport.com/motogp/news/marc-marquez-honda-return-portimao/6182143/` works fine in Signal because the URL has the trailing slash and the website returns what Signal expects.
2. Entering a whitespace or two after the URL still works just fine.
3. But once you add a non-whitespace characters (such as new lines) after those whitespaces, Android's LinkifyCompat class generates the same URL __but without the trailing slash__.
4. The website `motorsport.com` returns 301 Redirect response with an insecure `http` URL to the request that does not have the trailing slash.
5. Signal (in all fairness Android) stops the attempt to access the URL and throws an error.
6. That results in what we saw; `No link preview available`.

Google.com doesn't change how it behaves with or without a trailing slash at the step 4 above so that the link preview does not change. The link preview does get refreshed as Herohtar noted, because the previous URL (with a slash) and the _new_ URL (without a slash) is indeed different. This part could be worked around in Signal's code but honestly I don't know if it is what the app should do because technically those are two different identifiers according to the URI spec.

**Comment by Herohtar** [comment]
So all that to say, it's a bug in Android.
