### ISSUE TITLE
Show when the recipient is currently typing

### ISSUE THREAD

**Issue by eikowagenknecht** [signalapp/Signal-Android#1121]
Since I couldn't find any information regarding ths topic:

Would it be possible to add an indicator "... is typing" when the recipient is typing? This is a standard feature of modern (insecure) messengers (i.e. iMessage, XMPP, WhatsApp, Threema, ...) and currently not available in TextSecure. Should be optional of course.

**Comment by Beanow** [comment]
Definitely +1 for this. It's one of the major features that I'm missing switching from XMPP. Especially with people I chat for longer periods of time with there's a big **void of social cues** here.

Typing, online, auto-away, busy, etc. They answer questions like, do I have this person's attention? Is now a good time to bring up this subject? In my opinion vital components for a rich IM experience.

In their book the XMPP people devoted a chapter to this alone to explain why they made this a core feature and how they implemented it. http://shop.oreilly.com/product/9780596521271.do and I'm sure there's more material pointing out the importance.

That being said, I'm aware that XMPP has a different design completely security wise and in message propagation. So I'm wondering **what the status is of this issue**. Are we looking at security and protocol issues that need solving? Or is it a matter of backlog and this being lower priority, but reasonably straightforward to implement?

**Comment by jm3** [comment]
@michaelkirk, thanks for re-opening WhisperSystems/Signal-iOS/issues/730 and for pointing me here. I use the Chrome app & iOS so I wouldn't have thought to look for related Android issues.

IMO "…is typing" feedback is a deceptively important feature. As @Beanow explained nicely above, modern messaging apps all employ some kind of "is replying" feature (Slack, Twitter, Apple's Messages, etc.) because it provides huge communication benefits. Now that users increasingly expect this feature means that every day Signal's clients lack it, new users trying the app will experience that it's more primitive, less polished, and perhaps even less stable or secure than other messaging applications they're used to. It's a mistaken perception, but it hurts present and future Signal users if they miss out on the security of the app due to the absence of an expected UX convention. Typing feedback indicators help messaging feel real-time and responsive. Feedback or back-pressure that the counterparty is typing signals that more is coming, keeps us engaged, and helps us better connect with whoever we're chatting with.

To echo what @Beanow volunteered above, I would love to help support evangelizing, implementing, reviewing, and releasing this!

**Comment by moxie0** [comment]
Thanks @jm3 I think we agree that doing something here is important. We'll be working on how to do it best.

**Comment by p4nci** [comment]
I really DISLIKE this "feature" (just as "read" mark).
@moxie0 please consider some concerns discussed already at community forum:
[Why no optional typing notifier or “read” mark?](https://whispersystems.discoursehosting.net/t/why-no-optional-typing-notifier-or-read-mark/)
There is a broad consensus that this must be "optional"

**Comment by moxie0** [comment]
I fully understand that not everyone wants read receipts or typing indicators or whatever.  Thanks for the feedback, but let's not have the discussion here.

**Comment by yebaital** [comment]
Yes please do this

**Comment by GSPP** [comment]
It would be useful to be able to disable this feature per contact/chat. In social chats I want it on and at work I might want it off.

**Comment by AlekseyLobanov** [comment]
+1 Very useful if I need to write long messages
