### ISSUE TITLE
Disabling signal-pin-reminders by default for better accessibility.

### ISSUE THREAD

**Issue by Glasses8448** [signalapp/Signal-Android#11235]
The usabillity for humans with mental handicap is complicated by this feature. Please consider disabling signal-pin-reminders by default for better accessibility.

**Comment by hiqua** [comment]
Maybe your post would get more visibility there: https://community.signalusers.org/c/Accessibility/32

If you have more information about how the reminders harm the experience, that could be helpful. I think they only appear at the bottom, leaving at least 3 or 4 conversations visible. Do you mean that they distract the user?

I assume you already know that it's an option in "privacy". Do you consider the initial setup phase (number registration) accessible, or is it assumed that this phase is done with external help? In that case, it would make sense to prompt at the end whether these reminders should be disabled (so that the external help can easily do it at this point).
