### ISSUE TITLE
Port Textsecure to Jolla/SailfishOS

### ISSUE THREAD

**Issue by cintema** [signalapp/Signal-Android#1127]
Is there a port to SailfishOS/Jolla already in the works and if not, would a port be feasible?
Afaik, Jolla uses the Telepathy messaging framework which should make the seamless integration of TextSecure well possible...
Any thoughts?
Thanks, 
Chris

**Comment by elimisteve** [comment]
@cintema 

> I think it might be easier to convert ObjectiveC to C++ than java code, therefore it's probably clever to start from the iOS version of TextSecure once it becomes available...

Good point.  I may be interested in porting TextSecure to Ubuntu Touch.  I want to write the app in Go, from which I can link to C, C++, and/or Obj-C code, which is exciting because Signal is written in these languages.

Anyone have any tips for doing this?  I'll try to contact DiosDelRayo and see if s/he has figured any of this out.  Thanks!

**Comment by elimisteve** [comment]
Aaand here's two posts from DiosDelRayo saying he's not interested in writing software for SailfishOS anymore:

Long rant: https://together.jolla.com/question/75103/rant-good-bye-jolla-good-bye-sfos-and-good-bye-native-textsecure/

Post about unregistering to stop showing his support: https://together.jolla.com/question/78068/how-can-i-unregister-my-tjc-account/

**Comment by DanScharon** [comment]
@elimisteve actually @CODeRUS has started to port libaxolotl and libaxolotl-curve to SailfishOS: https://github.com/CODeRUS/libaxolotl https://github.com/CODeRUS/libaxolotl-curve
