### ISSUE TITLE
Contacts Synchronization

### ISSUE THREAD

**Issue by emirhanbilge** [signalapp/Signal-Android#11299]
Firstly Im sorry for my English ,

- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There are differences between the Signal contacts in my phone and the windows computer.

### Steps to reproduce
1- I installed the signal application on my computer.
2- From my phone; Connected Devices> '+' button> scan QR Code in my Pc
3- There are differance contacts my  pc

**Actual result:**People who are not registered on my phone appear in the application on the computer. When I cleared my signal data and tried this, they did not give different results.
**Expected result:** Having contacts appearing in the Signal app in my phonebook.

### Screenshots
[X](url)
https://drive.google.com/file/d/1wTvmejrSO1DOIz1hclT7q8od9BIflSDu/view?usp=sharing
https://drive.google.com/file/d/1-7SDky6q7B8ArbsbXWdFf4eqrpr3HT3G/view?usp=sharing

### Device info

**Device:** Samsung M30S 
**Android version:** Android 11
**Signal version:** 5.11.1
Pc Windows : 10 PRO
Windows Version : 20H2

**Comment by petvoigt** [comment]
I can confirm this issue (Signal version 5.9.7 from F-Droid, Android 11/LineageOS 18.1, Signal Desktop version 5.1.0).

Since Signal Desktop 5.1.0 "File->Preferences->Contacts->Import Now" at least does not throw errors anymore. But at the same time new contacts are not imported anymore to Signal desktop. Chat import, however, seems to work.

**Comment by emirhanbilge** [comment]
Thank you for your attention. Actually, I noticed that the problem is caused by the lack of automatic synchronization on the Android side. Contacts synchronization is not done automatically on the signal, we have to update manually to see the newly added contacts on Android. I could not see a detailed part of this in the settings. We encounter this kind of thing because contacts updates the desktop when logging in for the first time.

**Comment by petvoigt** [comment]
My observation is different (now with Signal Desktop 5.4.1): While new Signal contacts are always found automatically on the Android side (regardless of the Android Signal version) these new contacts never appear on the Desktop side - until there is a first message to/from them them. In fact, contacts synchronization from Android to Signal Desktop newer worked as long as I can remember. This is annoying because a first message to a new contact can only be initiated from the mobile (Anroid) Signal client.
