### ISSUE TITLE
Texts to non-Signal users that are long in character length fail to send

### ISSUE THREAD

**Issue by johnwblue** [signalapp/Signal-Android#11315]
This is a minor annoyance for me, but I am tried of hearing my wife complain about it so could you please fix it?

Texts to non-Signal users that are long in character length fail to send.

**Comment by johnwblue** [comment]
![Screenshot_20210517-215247](https://user-images.githubusercontent.com/17463087/118583619-f927b200-b75a-11eb-8929-ffda2638cde7.png)

**Comment by elitejake** [comment]
If I recall correctly, there is a limit of 160 characters while sending SMS. ISPs usually get around that with concatenation. It might be that your ISP doesn't support such long messages.

**Comment by hiqua** [comment]
Please always attach a debug log when reporting such things.

As hinted at by the previous comment, can you check that you're able to send long SMS with another app, to rule out your provider as the cause of this?

If that does work with another app, that would be a workaround for now, until the bug is found.

To be clear, I'm able to send long SMS (well I think I've at least 2*160, maybe 3*160 once) using Signal, so it's not an easily reproducible bug (if it's a Signal bug).

**Comment by tsikmartin** [comment]
i am able to send novels, the other non signal user would just get them with a 1/2 2/2 message if i recall correctly
