### ISSUE TITLE
Can't Copy From Debug Log

### ISSUE THREAD

**Issue by seniorm0ment** [signalapp/Signal-Android#11365]
There is no way to copy output from the debug log.
If a user wishes to copy a specific portion, double tapping, holding on text, both seem to not work.
Deleting a bunch of lines one by one manually is time consuming and tedious.

**Comment by greyson-signal** [comment]
Because that text area has to render (possibly) megabytes of text, we have to actually render it with a RecyclerView instead of a single TextView. Even if we enabled text selection, you'd only be able to select a single line at a time, which was why it was easier to just leave it disabled.

I don't anticipate we'll be fixing this anytime soon, just because to do so would involve writing an entirely custom TextView.

**Comment by seniorm0ment** [comment]
why could the user not output the page into a text file or something? I would assume it could simply parse one line after another to a text file, it'd at least allow the user to then copy and modify with ease in their text editor if they wish.
