### ISSUE TITLE
Messages never arrive to the recipient if it's not installed  even after re-install

### ISSUE THREAD

**Issue by pixincreate** [signalapp/Signal-Android#11373]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
You might think it as a feature request, but it's **not**.  
I'd flashed my phone, and I'm a regular Signal user. Signal, now is not on my phone. My brother sent me a message, I didn't know. After setting up my phone, I opened Signal to see any messages if exist, none of them were there even though I haven't deleted my account. Where did the message that brother sent go?  
I'm unaware if it's a server error or anything else. But this thing really pisses me out. I lost a precious one-time opportunity because of that.  
  If the recipient's device is unavailable, then it should wait for atleast 24 hours to have that device active so that the recipient can read the message.

### Steps to reproduce
- Uninstall Signal
- Ask someone to send you a message.(now, you're unaware that a message has arrived)
- Install signal, you'll not see the message that the guy on the other side sent you.

**Actual result:** I cannot see any hints or messages that someone had sent me a message as Signal was not installed.
**Expected result:** Even if Signal is not installed on the device, the user is registered, means, if a person/sender sends a message to receiver/me, the moment I install Signal, I should know atleast know that the specific sender had sent me a message so that I can acknowledge.   
If nothing is notified how could a person know? 

### Screenshots

This doesn't require screenshots in my opinion.

### Device info

This bug can be seen on every device, not only mine.  
**Device:** Nokia 6.1 Plus(LineageOS)
**Android version:** 11.0(18.1)
**Signal version:** 5.14.0

### Link to debug log

This has nothing to do with logs.

**Comment by bme13** [comment]
Hi, It's indeed not user friendly however I think this is currently by design. By uninstalling and re-installing you're safety number most likely changed and this resulted in the messages being dropped. See https://support.signal.org/hc/en-us/articles/360007060632-What-is-a-safety-number-and-why-do-I-see-that-it-changed-

**Comment by pixincreate** [comment]
Yes, I read that. It's really annoying to have important messages get deleted even before knowing.  
In my opinion, the moment **security keys** change, the part of code handling the security key, **should** remember the previous key until the device is re-registered/reconnected, so that it can deliver the message to the receiver if any exist. Then, the previous security key can be deleted, right? I don't se any sort of privacy issues right here, BTW.

**Comment by bme13** [comment]
I don't have enough insight to make a statement about the decision to handle it the way it currently does. Here's a discussion on the forum about it that might be helpful: https://community.signalusers.org/t/what-happen-to-those-undelivered-messages-when-a-recepient-reinstalls-signal/6758.
I think that if you restore a backup or transfer your data there is no safety number change and the messages are not lost in that case. 
Furthermore to me this does seem like a feature request and not a bug since it behaves as designed and I guess if you want to discuss this more the community forum would be the appropriate place.

**Comment by pixincreate** [comment]
> I think that if you restore a backup or transfer your data there is no safety number change and the messages are not lost in that case.

Yes. But what about the messages that had to arrive in between uninstalling and re-installing?   

> Furthermore to me this does seem like a feature request and not a bug since it behaves as designed

I do agree with your point of view. But it should not be feature request as Signal, being a private Messenger, keeps the messages private and secure, and it should not lose the messages in between which will cause inconvenience to a rate of 100%(in my case as of now).  
Atleast what I'd recommend is that the user should be **notified** that "A message had arrived from the [contact name] which is unrecoverable and ask the person to re-send."  
Wouldn't this solve the present issue?  
P.S: I really feel like it's a bug. User must be notified at least btw.
