### ISSUE TITLE
Chat colors no longer work as expected

### ISSUE THREAD

**Issue by Sad-Flycatcher** [signalapp/Signal-Android#11380]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Previously, setting the chat color for a contact would change the color of messages from that contact. Now, setting the chat color for a contact has no effect on messages from that contact. Messages from all contacts appear in light grey. The chat color set for a contact instead changes the color of my own messages when I am viewing a conversation with the contact in question.

### Steps to reproduce
- Open a conversation
- Top right menu > Conversation settings > Chat color & wallpaper > Chat color
- Set a color
- Return to the conversation

**Actual result:** My own messages change color to the color I have set for a contact. Messages from the contact do not change color.
**Expected result:** Messages from the contact appear in the color set. My own messages do not inherit the color I set for a contact.

### Screenshots
![Screenshot_before](https://user-images.githubusercontent.com/85723001/121630146-bdb9a280-cad0-11eb-9a9e-695fe0100b8b.png)
![Screenshot_after](https://user-images.githubusercontent.com/85723001/121630179-c9a56480-cad0-11eb-9393-73f3f1b96cf7.png)

### Device info
**Device:** Unihertz Titan
**Android version:** 10
**Signal version:** 5.13.8

**Comment by derNarr** [comment]
For me this is the same :-( -- I hope there is a fix soon. This is really distracting. Now all my bubbles are highlighted and have the colour that used to be the colour of my contact.

**Comment by derNarr** [comment]
Searching the closed issues, this seems to be intended see #11358 there is an open issue for the desktop version as well https://github.com/signalapp/Signal-Desktop/issues/5316 and there is a long feedback chat of a lot of frustrated people here https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048 with some reasoning of the devs here https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/100 .

Hopefully, this gets reverted soon or at least customizable. But it seems that the majority of messaging apps do it in the "new" way as well and signal wants to adopt this UI consensus. IMHO this design choice makes sense for messaging apps with large and diverse group, like Telegram, Discord or Matrix.org, but not for a text message / SMS replacement app. But if you have time you can read through all the linked threads and add more links here, if you find them useful on the topic.

**Comment by klikevil** [comment]
> adopt this UI consensus. IMHO this design choice makes sense for messaging apps with large and diverse group, like Telegram, Discord or Matrix.org, but not for a text message / SMS replacement app. But if you have time you can read through all the linked threads and add more links here, if you find them useful on the topic.

I hate it so much that i went nuclear and reverted to 5.3.0, I may fork 5.4.x and maintain one with the original message color if i ever have a few weeks to go through all their spaghetti nodejs stuff and will not accept pull requests to whomever changed my message colors.

**Comment by derNarr** [comment]
There seems to be a poll now (which will have very limited meaning) in the feedback channel:

https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/786

As stated there as well, this poll will be not representative at all, but for me it was still good (and interesting to see) that 15 to 20 people seem to like the new UI.

**Comment by pascoda** [comment]
I did not consider this a bug per se, so I commented/reported this here:
https://github.com/signalapp/Signal-Android/commit/6342a45b4eb141cc02e45bc0163fada6e2769211#commitcomment-51972596

another thing I just realised today: the one "thing" that stays the same throughout all my messages (me) has no consistent color now. that's seriously bad design.

**Comment by derNarr** [comment]
In here I also want to emphasize that (at least for me) it is  really **only about the colouring** and that I do want to have colour identities for my contacts and that it only clashes twice in the last years for me.

I do think the other UI changes go in a good direction. Especially having the **contact pictures next to bubbles in group chats is really good**. Placement can be improved and the default picture should have some generative / procedural / distinctive feature to it, because I have a decent amount of contacts with the same initial letters.

Colouring the names in an distinctive way is an interesting feature as well, where I really have to see how much I like or dislike it and how it can be improved in terms of contrast etc.

So at least for me, it is only about the colours and having vivid colours attached to contacts (and myself in a boring grey).

My responses are not about freezing the status quo and having everything like the “old style” UI forever. Not at all.

**Comment by UserX404** [comment]
Github is used as bug tracker only and this change is intended.
This issue is still discussed in the forum heavily.
https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/828

**Comment by Sad-Flycatcher** [comment]
> Github is used as bug tracker only and this change is intended.

Ideally most changes to software are intentional; unfortunately, this change breaks existing functionality.

**Comment by parbash** [comment]
In group chats the contact name changes colour per chat... Same contact is orange in one and blue in another. Having the same color on the dm and group chat made everything so easy to read. This just makes everything confusing.

**Comment by Kixunil** [comment]
@UserX404 This **is** a bug because the setting has no effect. Not even after restarting Signal. I wanted to set my messages to gray to workaround it - didn't work.

>  change is intended.

What kind of a person decides to just **invert** the semantics of UI from version to version without giving an option to flip it back? It's incredibly confusing. It may sound harsh but I perceive the intention as a bug too.

**Comment by scoder** [comment]
For me, this change makes it difficult to visually distinguish chat partners.

With an AMOLED screen and black background, the main place of distinction is the colour of the chat bubbles. I find it confusing to have different colours for my own writings in different chats, so my colour is the same for all chats. And I cannot change the colour of the chat partner. That means that all chats now look the same to me.

It's probably only a matter of time until I send a compromising message to the wrong person, because I simply was in the wrong chat when typing or pasting it (which visually appeared exactly like the right chat but wasn't it).

**Comment by cody-signal** [comment]
> Github is used as bug tracker only and this change is intended.
> This issue is still discussed in the forum heavily.
> https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/828

**Comment by Iron-E** [comment]
Replies to a user don't use their chat color either. It always uses the main color

**Comment by morleym** [comment]
If a user feels it is such a breaking change that they opened on issue on github to genuinely report it as a bug, that *might* be a sign for the product manager to take to heart.

**Comment by Kixunil** [comment]
@cody-signal please re-read the issue. Changing color in the settings has no effect - that is the main point and it **is** a bug.

**Comment by derNarr** [comment]
> > Github is used as bug tracker only and this change is intended.
> > This issue is still discussed in the forum heavily.
> > https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/828

I still feel it would be wise to keep this issue open for another week to make it easier for people to find the right links on discussion and to prevent people from reopening new issues on the same topic.

**Comment by pcharest** [comment]
It's clearly a bug. So it must be on github!

**Comment by Sad-Flycatcher** [comment]
Acknowledging that a change you have made to your software program has broken functionality in a way that affects people other than yourself is something that can be hard to admit. However, I think it's fair to say that Signal has passed the stage of being a hobby project where developers are responsible only to themselves. As a software project grows, its userbase gets bigger and each user puts an increased amount of trust in the software to maintain certain standards and certain functionality. At the same time, though, many of these users become more willing to support the project as it grows. Bug reports are an important way in which users can support a software project without needing to be programmers themselves.

It's simply the nature of software development that changes to a program can break existing functionality despite a developer's best intentions. A famous quote attributed to Edsger Dijkstra says, "If debugging is defined as the art of taking bugs out of a program, programming must be the art of putting them in."

I'm willing to give developers here the benefit of the doubt and assume that whichever change caused this issue represents an honest mistake. When a piece of software is sufficiently complex and has a large number of users, it's statistically likely that a fault may be picked up by a user rather than a developer.

I understand that software authors can't realistically fix every single issue that is reported, especially in cases when these people are volunteers. Many users would understand if the developers admit that they don't have the resources to solve a particular bug. If this happens in the context of an open source project, someone else may be able to contribute a code fix.

However, when a bug report is closed at short notice without a resolution and without any more sincere engagement from the closing developer than quoting another user's message, this violates users' trust and begins to cast doubts on the integrity of the developers involved -- it's less certain that developers' actions aren't malicious and the bug was really just an honest mistake.

**Comment by pentargency** [comment]
>less certain that [...] the bug was really just an honest mistake.

I agree with your general sentiment as I also despise this change and think it fundamentally regresses the group chat functionality of the app, however, what nobody seems to be expressly clarifying for you is this is definitely (and sadly) not a bug or accident. This is an intentional (if baffling) change.

The developers have intentionally chosen to remove all existing coloring functionality for inbound messages and now only permit you to color your own outbound messages. The option in the per-chat settings now only refers to your outbound message coloring within that chat, and options to allow for inbound message coloring have been intentionally removed.

Closing this issue is very warranted given the intended function of GitHub's issue tracker. As this is an open-source project, a more appropriate place on GitHub to lodge ideological disagreements with this certainly ridiculous decision would be the fork button, or a corrected codebase and subsequent pull request. Otherwise, the forum on which they solicit and centralize feedback is most appropriate.

**Comment by derNarr** [comment]
New issues are opened on the topic as people do perceive the change as a bug:

https://github.com/signalapp/Signal-Android/issues/11389

https://github.com/signalapp/Signal-Android/issues/11387

Would it be able to reopen the issue and keep it open for some time to make it easier to find?

**Comment by jason88k** [comment]
> I hate it so much that i went nuclear and reverted to 5.3.0, I may fork 5.4.x and maintain one with the original message color if i ever have a few weeks to go through all their spaghetti nodejs stuff and will not accept pull requests to whomever changed my message colors.

Do you have a link to this that you're working on? I'd gladly support the old-color fork and cherry-pick to get the other future updates without the new color bullshit.

**Comment by klikevil** [comment]
> > I hate it so much that i went nuclear and reverted to 5.3.0, I may fork 5.4.x and maintain one with the original message color if i ever have a few weeks to go through all their spaghetti nodejs stuff and will not accept pull requests to whomever changed my message colors.
> 
> @klikevil Do you have a link to this that you're working on? I'd gladly support the old-color fork and cherry-pick to get the other future updates without the new color bullshit.

@jason88k 
Not yet, and i haven't even started on android yet as I mainly use signal as a desktop client, I do have instructions for rolling back to 5.3 successfully on desktop and preventing it from being updated (my build is 5 days past expire date and is functioning properly).

https://github.com/signalapp/Signal-Desktop/issues/5316

C:\windows\system32\drivers\etc\hosts

```
127.0.0.1	updates.signal.org
127.0.0.1	updates2.signal.org
```

Search the above bug issue for a post that i did with virustotal link for a 5.3 installer, move %APPDATA%\signal\ out of the way, reinstall old signal.  You will need to create daily backups because your phone will occasionally force everyone else blue.  This is a completely nuclear option that blows away all previous chat/conversation histrory.
