### ISSUE TITLE
Other person's video rotating 

### ISSUE THREAD

**Issue by samsunga50** [signalapp/Signal-Android#11393]
### Bug description
When the other person rotates their phone by 90°, you see them rotated by 180° on your phone.

### Steps to reproduce
- Video call someone on signal.
- Have them rotate their phone by 90° for e.g lying down
- Keep your phone straight.

**Actual result:** Their video is rotated by 180°
**Expected ** Nothing should happen

### Device info
**Device:** Samsung A50
**Android version:** 11.0
**Signal version:** latest

**Comment by slimfish08** [comment]
This issue also happens to me. I have to hang up and call again in order to not see the other person's video upside down.
The video rotation also affects when both persons are laying to the side. 

### Steps to Reproduce:
- Call someone
- Lay down looking to your left side
- Have the other person laying down to their left side too

**Actual Result:** Both persons see the other upside down
**Expected Result:** Both should see straight, like it happens when one person lays to the left, and the other to the right

**Phone Model:** LG V60 ThinQ
**Android Version:** 11.0
**Signal Version:** 5.15.6
