### ISSUE TITLE
Readability suffered greatly after recent color change

### ISSUE THREAD

**Issue by csando** [signalapp/Signal-Android#11390]
Switched to signal because of this feature, to have different colours for incoming messages. Now it's gone. Despite claims of "increased readability" that is certainly not the case.

**Comment by Nostrocean** [comment]
They expect people cease complain, when the solution are three lines of code, which would leave both systems active, at the user's choice in the color panel.

https://community.signalusers.org/t/beta-feedback-for-the-new-color-changes/33048/1241

Do not stop complaining. and do not donate. do not recommend donate, explain the reasons... once captured, you don't matter. Business are business.

**Comment by greyson-signal** [comment]
Hi there, this was an intentional change. You can discuss it more in the previously-linked forum post, and you can read all of my posts on the matter [here](https://community.signalusers.org/t/discussion-about-the-new-color-changes/33048?u=greyson-signal). I took a considerable amount of time to address all of the core complaints I observed. Thanks!

> when the solution are three lines of code

So, so, terribly inaccurate. I explain in my posts why this isn't true, the large amount of work that would be involved, and the other logical inconsistencies you run into.

> once captured, you don't matter. Business are business.

Signal is a non-profit. The fact that we rely on donations means that we actually have a very large incentive to give existing users the features they want. These changes were very intentional and well-planned, and I believe that if you read my previously-linked posts you'll see that we absolutely considered and responded to the issues people had with the new color system.

**Comment by kototama** [comment]
>      Signal is a non-profit. The fact that we rely on donations means that we actually have a very large incentive to give existing users the features they want.

Like the shitty mobilecoins payment that nobody wanted?

**Comment by kototama** [comment]
Anyway the color update is disturbing. Very bad. You broke something that was not broken.

Continue like this and people will stay with Signal just because it's the least bad of messengers, not the best.
