### ISSUE TITLE
Save media to internal storage broken with Android 11

### ISSUE THREAD

**Issue by char32** [signalapp/Signal-Android#11400]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I want to save an attachment to InternalStorage/Pictures - which does not work anymore after and Upgrade on Android 11.
Maybe it is related to Androids framework changes regarding scoped storage, etc.

### Steps to reproduce
- Go to chat thread with a contact
- Got to all media
- Select a image attachment and click on save
- Confirm with "yes"

**Actual result:** A toast notification pops up with the content "Error while saving attachments to storage!"
**Expected result:** Attachment should be saved to Internal Storages' /Pictures folder

### Device info

**Device:** HMD Nokia 8.1
**Android version:** 11 Build 00WW_6_210
**Signal version:** 5.13.8

**Comment by cody-signal** [comment]
Please provide a link to the debug log.

**Comment by Sushantrahane** [comment]
@cody-signal @scw @offby1 @jcs i am also facing this issue but this is not an Android issue my device is running nougat .It is happening with audio & video attachments
Device info Samsung galaxy A510F
signal version -5.14.5

**Comment by HappyCampero76** [comment]
Hi guys i am facing similar issue but with pictures since each time i try too save a picture on my storage it says:
Error while saving attachment to storage.
Never tried to save anything else..
Asus Zenfone2 Laser Android 6.0.1.
Ive sent 2 emails from the site to the admins but so far no answer...
Attaching screenshot of the message i receive.
Can anybody tell me how can i fix that error please?
Or if they are working of fixing the error....
Cos kinda boring download the pics from signal on my laptop save em and move em on the phone..
Thanks to anybody that can answer or provide any sort of help..
Before i forget Signal has every permissions i want it to have turned on and storage specifically is on..

![Screenshot_20210630-180841](https://user-images.githubusercontent.com/68563269/123995122-4a6bc800-d9ce-11eb-9e7a-81ecd2c127cd.jpg)

![Screenshot_20210630-180015](https://user-images.githubusercontent.com/68563269/123994609-d3ceca80-d9cd-11eb-8602-c052124fa4ca.jpg)

**Comment by Sushantrahane** [comment]
@greyson-signal i am also facing this issue but this is not an Android issue my device is running nougat .It is happening with audio & video attachments
Device info Samsung galaxy A510F
signal version -5.16.3

**Comment by Sgn-32** [comment]
@Sushantrahane have you checked that the folders "Pictures" and "Movies" exist on your device?
see https://github.com/signalapp/Signal-Android/issues/10792

And please post a debug log.

**Comment by matkoniecz** [comment]
> Hi to all. I see nobody has pasted a link to a full debug log. For those of you who run into this issue please append the link to the uploaded log!

I run into it. Is there some way to export text preview, review it externally and post it? I see mentions of unpreviewed "binary data" and log lines to long to preview on my phone.

I am not willing to blindly press submit as I reproduced it while sending keepass password database.

**Comment by matkoniecz** [comment]
As bonus: I have now a phantom file that is not shown in Amaze, is shown in FileZilla and cannot be deleted.

No idea is it caused by Signal or is it a reason for my problems.
