### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by SyCoREAPER** [signalapp/Signal-Android#11419]
What is needed to get tablet support concurrent with phone on Android? I'm happy to donate time, money, etc to get this started. 

I've had to stop using Signal because it cannot sync text and signal messages with my tablet.

**Comment by greyson-signal** [comment]
A massive UI refactor, to start ;) Supporting larger screens is something we've always had on the backburner, just because there isn't a very large userbase. Not to say we're not interested, but we've gotta rank it among other features that will affect more users.

That said, we use Github as an issue tracker. For discussions, please check out [the forum](https://community.signalusers.org/). Thanks!

**Comment by granthgh** [comment]
With due respect, I believe that you are wrong and that Android tablet support and linking is required by a large number of users worldwide.
Its the one issue that's causing me a problem right now.
