### ISSUE TITLE
App shortcut icons aren't adaptive

### ISSUE THREAD

**Issue by lokesh-krishna** [signalapp/Signal-Android#11412]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Icons used for app shortcuts are circular irrespective of the icon style chosen in system settings. 

### Steps to reproduce
- Long press on the app icon to bring up app shortcuts

**Actual result:** Icons used for the app shortcuts are circular, embedded within the icon shape selected in system settings leading to empty space at the edges
**Expected result:** Icons adapt to the shape picked in system settings

### Screenshots
With the squircle shape selected, this is what things look like presently in Signal:
![signal-2021-06-27-184934](https://user-images.githubusercontent.com/20235646/123546290-9eca3a00-d779-11eb-831b-9bad4df8e8d8.jpg)

This is how Discord handles it:
![signal-2021-06-27-185914](https://user-images.githubusercontent.com/20235646/123546395-f8326900-d779-11eb-97e1-31563203b321.jpg)

### Device info

**Phone**: Redmi Note 7 Pro
**Android version:** 11
**Signal version:** 5.15.3

**Comment by alex-signal** [comment]
Hi! Thanks for the bug report. This should be fixed as of `5.16` which'll be rolling out soon to a beta near you!

Due to how shortcuts work, this may not fix itself instantaneously. As a workaround once you are on 5.16, I'd follow these steps:

1. Enable screen lock in App Settings -> Privacy -> Screen Lock (this will delete all system shortcuts)
1. Close the signal app
1. In System app settings, clear cache for signal app (WARNING: Do not clear data. Only cache.) This will make sure Glide (the image manager library Signal uses) doesn't have any out-of-date shortcut bitmaps in it's file cache.
1. Open the signal app
1. Disable screen lock in App Settings -> Privacy -> Screen Lock (this will re-add all system shortcuts)

Clear cache might not be necessary, as I've also added a version number to the key that the cache system uses to locate the proper file, but it doesn't hurt.
