### ISSUE TITLE
Unable to Transfer from Adroid device

### ISSUE THREAD

**Issue by ioogithub** [signalapp/Signal-Android#11440]
### Bug description
Transfer from Android device does not work.

### Steps to reproduce
1. Open transfer wizard on old phone- "Searching for new Android device"
2. Open transfer wizard on new phone- "Searching for Android device"
3. Invitation to connect... accept
3. Nothing happens after waiting up to 20 minutes.

"Unable to discover old device"

An unexpected error occurred while attempting to connect to your new Android device.

Repeated twice.

This feature simple does not work ...honestly I didn't expect it would.

**Comment by alex-signal** [comment]
Hi! could you please send us debug logs from each device?

https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by clauz9** [comment]
hi, @alex-signal I've followed the steps above and managed to replicate it, 

here's a debuglog of the sending device. 
log: https://debuglogs.org/d479cf965c57f94290b872abfcf22dc2fd0611e278a36fe36c0c1b4c7440a0e3

and a debug log of the receiving device, that I took after I registered a phone number, because It crashes when you try to get debug logs by tapping multiple times on the large texts at the beginning, I've posted about it in the most recent beta thread on the forum. 
log: https://debuglogs.org/a7a7f075ae82571da297715bb574832247510a873f9f29dd249a9e0b049416ad

I hope the log captured what you need. 
I've tested this on a couple of devices and it seems to only happen when I try to transfer TO android 5.1 and 6.01 devices. 

here's the 6.0.1 log: https://debuglogs.org/3523cc58792d6e77ff2cc93cf552c192cfd19d1271c28df277e02f7fca354381

I don't get this message "An unexpected error occurred while attempting to connect to your new Android device." that is mentioned in the original post. but I think it's the same issue. 

this is what I get, after the receiving device, showed the invite prompt and I accepted it. 
![image](https://user-images.githubusercontent.com/77681918/126927212-6807280c-a079-4efb-b967-82d3f482fea3.png)


hopefully @ioogithub can confirm the same is happening on his device as well.

**Comment by n00bhax** [comment]
I got this error as well. Tried using older versions, clearing app data, giving more permissions. Nothing worked

**Comment by clark-signal** [comment]
> I got this error as well. Tried using older versions, clearing app data, giving more permissions. Nothing worked

Sorry to hear that, could you send logs? https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by lilwhitemouse** [comment]
This is still happening. Is there a reason it's tagged "won't fix"?

**Comment by cody-signal** [comment]
There was a recent regression in 6.33, and should be fixed on the latest 6.34.5, please try updating and trying again.
