### ISSUE TITLE
Delayed messages cause incorrect time sorting of chats

### ISSUE THREAD

**Issue by peter1rhodes** [signalapp/Signal-Android#11494]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Old messages (presumably delayed by network etc) appear at end of chat (might be OK), but this incorrectly orders the chats in the main/home view (where multiple chats are shown).

For example (as per logs etc):
In (Group) Chat A, a discussion is going on until 12:00
In Chat B, the last correspondence was at 11:00
In Chat A, an old message from 09:00 suddenly comes through from one member and appears at the bottom, but with an accurate 09:00 timestamp
Now, in the chats overview, the "last message time" for Chat A says 09:00 and it does not appear at the top, despite having more recent messages than Chat B.

### Steps to reproduce
- Have chat (seen in group, not sure if it applies to any)
- Have a message delayed by someone on the group (bad network?)
- Note that the chat is now sorted as if the most recent message was at the time the delayed message was sent, rather than by the most recent activity

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![Screenshot_20210728-140128__01](https://user-images.githubusercontent.com/51478811/127326656-a768857a-5237-4697-8eaa-a5bd2959bf6e.jpg)

Note: screenshot does not show sorting error in main view, which is the bug, because I was too slow. It does show the delayed message appearing underneath the more recent ones. Issue is that the chat was sorted in the main view as if the most recent message was 09:08, until a genuine new message was sent

### Device info

**Device:** OnePlus Three
**Android version:** 9
**Signal version:** 5.17.3

### Link to debug log

https://debuglogs.org/fecbc9ee87bcdd529d0ff02b1a95bb7859cc6f8d3334a2882d956640ff296c54

Note that in this debug log, one newer message came through that unset the error state before I grabbed the log.

**Comment by cody-signal** [comment]
Thanks for the report, want to confirm my understanding and share some context.

In the conversation view, we always show messages in RECEIVED order not sent. This makes sure any message that was delayed will be shown to the user as a new message at the bottom instead of potentially being "lost" in the history.

However, the bug you are describing, is that in the Conversation List view, for a conversation that received an out of date message, it is being sorted by that out of date SENT timestamp instead of the the RECEIVED timestamp. Meaning, the conversation could show up much lower on the list than it should,, as determined by when the last message was received.

That sound right?
