### ISSUE TITLE
deleting a SMS conversation also deletes 2 Signal conversations (?)

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#11521]
- [ ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
This is a situation on a device from an older family member. Not sure whether it is an issue or a misuse by user.
Today it was found that two Signal conversations only have a history from Monday noon.
The family member has (only) deleted yesterday a SMS conversation,
(but) from the logs there are three threads, which are individual deleted none together.

Either there was an error or the user confirmed three times the deletion of a conversation. 

```
[5.18.5] [12030] 2021-08-02 11:44:12.990 GMT+02:00 D SmsDatabase: deleteThreads(count: 1)
[5.18.5] [12030] 2021-08-02 11:44:12.996 GMT+02:00 D MmsDatabase: deleteThreads(count: 1)

[5.18.5] [12033] 2021-08-02 11:44:22.617 GMT+02:00 D SmsDatabase: deleteThreads(count: 1)
[5.18.5] [12033] 2021-08-02 11:44:22.651 GMT+02:00 D MmsDatabase: deleteThreads(count: 1)
[5.18.5] [12033] 2021-08-02 11:44:25.751 GMT+02:00 D SmsDatabase: deleteThread(42)
[5.18.5] [12033] 2021-08-02 11:44:25.754 GMT+02:00 D MmsDatabase: deleteThread(42)

[5.18.5] [12034] 2021-08-02 11:44:44.086 GMT+02:00 D SmsDatabase: deleteThreads(count: 1)
[5.18.5] [12034] 2021-08-02 11:44:44.097 GMT+02:00 D MmsDatabase: deleteThreads(count: 1)
[5.18.5] [12034] 2021-08-02 11:44:44.713 GMT+02:00 D SmsDatabase: deleteThread(14)
[5.18.5] [12034] 2021-08-02 11:44:44.714 GMT+02:00 D MmsDatabase: deleteThread(14)
```

**Expected result:** When this is an issue it should be fixed. When it's a misuse, then maybe extend logging with logs for "delete confirmation"

### Device info

**Device:** Motorola Moto G5
**Android version:** 8.1.0
**Signal version:** 5.18.5

### Link to debug log
https://debuglogs.org/0b014fb40287e292b0ae9af3b2bc59581a1f7c1087b42b2378b36b3c0e2241b5

**Comment by cody-signal** [comment]
It's hard to tell if this was user or app error, based on the logs I'm leaning more user error. I think additional logging will be needed in case this happens again to know for sure.

There are actually 5 delete operations in the logs. 

Anywhere there is a pairing of "deleteThreads" by both the Sms and Mms database, the code path behind them is only through the batch delete selection from conversation list, which is protected by a user confirmation dialog.

The deletes at these times would've been through the confirmation flow:
`2021-08-02 11:44:12.990 GMT+02:00`
`2021-08-02 11:44:22.617 GMT+02:00`
`2021-08-02 11:44:44.086 GMT+02:00`

Where there's a pairing of "deleteThread" from Sms followed by "deleteThread/deleteThreads" by Mms could be one of many flows. Mostly through a message request or through a thread update where that thread no longer has any messages and so it's deleted.

The deletes at these times would be most likely automatic ones:
`2021-08-02 11:44:25.751 GMT+02:00`
`2021-08-02 11:44:44.713 GMT+02:00`

Given the timing of the manual being reasonably spread out (10s and 22s), and the likely automatic ones being milliseconds after completing the manual, make me believe that the automatic ones were trying to delete the threads already deleted by the manual ones since neither automatic has any delete message logs after them.

**Comment by Sgn-32** [comment]
I was able to follow the process
from `handleDeleteAllSelected()` in ConversationListFragment.java
to `deleteThreads(@NonNull Set<Long> threadIds)` in SmsDatabase.java and MmsDatabase.java.
Then the automatic deletion could be called
from `deleteMessage(long messageId)` in MmsDatabase.java
with `boolean threadDeleted = DatabaseFactory.getThreadDatabase(context).update(threadId, false);`

in this `update(threadId, false)` there is
```
boolean        meaningfulMessages = mmsSmsDatabase.hasMeaningfulMessage(threadId);

  if (!meaningfulMessages) {
    if (allowDeletion) {
      deleteConversation(threadId);
    }
    return true;
  }
```
calling `deleteConversation(threadId)`

and so forth. 

> "Double erasure is better."

I could restore from a backup of (27.07.). So some newer message are lost, but the older ones were more important.


https://github.com/signalapp/Signal-Android/pull/11522
