### ISSUE TITLE
Search names with accentuated characters

### ISSUE THREAD

**Issue by Dimitri-UNHCR** [signalapp/Signal-Android#11534]
Hi @Karalix 
refering to this: Fixes #9341, better version of #9692. Adds unicode wildcards for equivalent latin characters #10202

It still does not work with Greek characters:
Typing: χρη
Does not find: Χρήστος

This may help identify similar characters: https://en.wikipedia.org/wiki/Greek_alphabet#Greek_in_Unicode
I saw the code, and maybe I can provide you with the Greek search patterns

**Comment by Karalix** [comment]
Hi @Dimitri-UNHCR ! I'd love to help make it happen. And your help would be absolutely necessary as the only year studying ancient greek won't help me much if there are ambiguities in the process. Don't hesitate to reach me on my email on my GH profile.

**Comment by Dimitri-UNHCR** [comment]
Great, thanks 👍
PS: Ancient Greek helps :)

**Comment by Caerbannog** [comment]
This problem was also mentionned here:
https://community.signalusers.org/t/contact-search-could-be-fuzzier-about-unicode-diacritics/9252/8?u=caerbannog

**Comment by Leptopoda** [comment]
Hi @Dimitri-UNHCR and @Karalix,
There still are some problems🙃

String of the message ”Τι θα γίνει με τα χρώματα?"

I tested the search with 
[x] "τι Θα Γι”
[ ] "τι Θα Γιν"
[x]"τι Θα Γίν"

The apostrophe on the 'i' seems to cause some probelms...

I don't have any time the next week to fix it myself but maybe you could step in again so it'll be fixed in a future dot release.

**Comment by Karalix** [comment]
Just to be sure, you mention "string of the message". The code for fuzzy search is only for contact and group  names for now. Maybe it can be replicated to message search but then it will need a close monitoring of the performance hit.

**Comment by Leptopoda** [comment]
Yeah I misinterpreted the commit :)
... and realized it too late sorry
