### ISSUE TITLE
Signal messages to a group causes direct SMS messages to switch back to Signal

### ISSUE THREAD

**Issue by gondoi** [signalapp/Signal-Android#11607]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a similar fashion to https://github.com/signalapp/Signal-Android/issues/10307, I have a contact that prefers to use SMS directly (iPhone Messages user), but we have a group going on Signal. When I long press and send an SMS, SMS continues until the contact messages the group, flipping the direct conversation over to Signal protocol. This has unintended consequences when the contact sends an SMS and the reply is sent over Signal.

### Steps to reproduce
- Start an SMS conversation with a Signal user
- Start a group with that user
- Have the user send a message to the group

**Actual result:** Direct SMS messaging with the signal user in a group causes the conversation to switch to Signal (SMS is not sticky)
**Expected result:** A user sending an SMS while being a Signal user should be able to stick to SMS even when a message is sent over a shared Signal group.

### Device info

**Device:** OnePlus 8
**Android version:** Oxygen OS 11.0.8.8.IN21AA
**Signal version:** 5.23.1

### Link to debug log
https://debuglogs.org/9b2dad32da9b12f8ee4b41c59db2a06a6fb72c6c7cb0a2b3b8e91155bc87fc33

**Comment by gondoi** [comment]
Has anyone had a chance to review this yet?

**Comment by gondoi** [comment]
This is not fixed yet. I can still reproduce it.

**Comment by greyson-signal** [comment]
We switch back to Signal messages pretty aggressively. In particular, we will switch back to Signal messages whenever you receive a Signal message from a user. This includes delivery receipts. I'm guessing you sent a message to the group, and their device sent back a receipt. This is important, because as a secure messaging app, we want to be using SMS as little as possible.

I don't anticipate we'll change this behavior. Adding the ability to toggle a thread back to SMS was only intended to alleviate situations where the recipient stopped using Signal or uninstalled, but the service hasn't detected them as unregistered yet. It was never intended for someone who only uses Signal for one group. Apologies!

**Comment by gondoi** [comment]
This is unfortunate. I understand the motivation, but as a user experience it's pretty poor. Unfortunately, this is in practice with a user that does not use Signal for both SMS and Signal. The poor experience in this case looks like a conversation starting in SMS but switching mid conversation to Signal causing a jarring experience or missed conversation.

i.e.:

| SMS app | Signal |
| ------------ | --------- |
| user1: "HEY! Let's go get some drinks" | |
| user2: "YEAH! What time and where?" | |
| | user1: "Moe's at 6"|
| user2: ".....?" | |
| user1: "Dang sorry, it switched to Signal. Moe's at 6." | |
