### ISSUE TITLE
Desktop connected to Android is working Android client is now non-functional

### ISSUE THREAD

**Issue by badrobit** [signalapp/Signal-Android#11651]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
An Android 11 device (Samsung S10+)(signal v5.23.8) is connected to my desktop client (signal v5.17.2). I can send and receive messages from the desktop but I cannot from within the app on the Android phone. 

### Steps to reproduce
- Open Signal on Android 
- Send a message to the note to self wait to see if it shows up with the dual checkmarks (it won't)
- Open Signal on Desktop 
- Send a message to the "note to self" wait for the message to have dual check marks 
- Open Signal on Android 
- Open the "Note to self" chat and see that the message from the desktop hasn't shown up (You can wait multiple days it never shows up)

**Actual result:** Messages sent/received when using the desktop never show up on the phone and without the desktop no messages at all shownup
**Expected result:** Signal is able to send/receive messages without needing the desktop app

### Device info

**Device:** Samsung Galaxy S10+ (SM-G975U1)
**Android version:** 11
**Signal version:** 5.23.8

### Link to debug log
[debug log](https://debuglogs.org/a4f161742a8191542484cb41a87b733b70fe3670f88422b6a932baacabf0e4cf)

**Comment by Sgn-32** [comment]
Is the Android app linked with the desktop app?
Found `Linked Devices: false` in your debug log.

You can also check in the Signal app under "Settings > Linked devices" whether is linked with the desktop.

**Comment by badrobit** [comment]
It was but something changed last night as this issue is no longer occurring on my phone or my wife's phone. They both stopped showing this behaviour at around the same time.

**Comment by timonoj** [comment]
I think I am having an even more extreme case of the same description: My Signal app has completely stopped showing any contents. The chats list has the most recent chats, and I can see the last sentence. But when I click on any chat, the chat shows blank. The settings section is blank. The desktop app seems to continue working as usual though. 
Since I have no Settings menu now, I can't backup to then reinstall. Any suggestions?

**Comment by freiheitsnetz** [comment]
I have the same issue as @timonoj . Signal on Android does not work. Empty chats, but still getting notifications. Sending is the same like described before with disappearing messages. I am on Android 12 Beta and on Signal Beta as well (5.24.14).

**Comment by Flupkees** [comment]
Exactly the same issue as @timonoj and @freiheitsnetz as well. I'm on Signal Android Beta 5.24.14 on Android 11 since yesterday and think these problems started after this update, but not sure it happened immediately after updating, because didn't use the phone client much since updating. Definitely wasn't the case before updating. The desktop client works the way it should. Is there a way to access the logs if you're not able to get into the settings?
One thing I noticed that's different from previous reports, is that the phone client is not in sync while the desktop client is. It seems as if messages come in about one hour after I receive them on the desktop client.

I'm not sure this is the same bug as @badrobit. Could you share with us whether you're experiencing the other issues the 3 of us are describing? Otherwise we should create a new issue.

**Comment by Flupkees** [comment]
Hmm, that is very strange. My phone client is still completely unusable. If I quit the app and then restart the app, it receives a few more messages. I can do that several times until the phone is in sync with the desktop client. Maybe I shouldn't do that as see if the problem magically resolves itself just as with you guys.

**Comment by pilatomic** [comment]
This problem solved itself for me too, about 24h after it first appeared. I killed the app once again, opened it once again, and this time conversation content and settings menu showed up properly, and everything was back to normal. App version did not change (still 5.24.12).
