### ISSUE TITLE
Signal uses a lot of CPU, leading to battery drain (Samsung Galaxy S7, Android 8, Signal 5.25.6)

### ISSUE THREAD

**Issue by pieqq** [signalapp/Signal-Android#11717]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal is using a lot of CPU (14.78% as I file this issue), leading to battery drain, to the point where my phone is telling me about  it and suggests that I force stop the app.

### Steps to reproduce
- Install and use Signal on my phone; sorry, no real path to reproduction, as this has happened quite frequently (once a day at least) over the last few months (not sure when it started, maybe early July)

**Actual result:** High CPU usage, battery drain
**Expected result:** Signal does not consume a lot of CPU, and my phone does not suggest that I force stop it as a result.

### Screenshots

![image](https://user-images.githubusercontent.com/512471/139410360-9baf0832-8f77-4c75-bff6-0f4a55f0273b.png)

### Device info

**Device:** Samsung Galaxy S7 edge (SM-G935FD)
**Android version:** 8.0.0
**Signal version:** 5.25.6

### Link to debug log

https://debuglogs.org/fe0b6cb27a0dbef3591ec4ed8593aed88337179591a9d4dc3e9fc79843864c03

**Comment by helpthemfix** [comment]
I agree with you. I have OnePlus 5 and Android 18.1 and Signal is the only app that drain the battery and heat the phone.
I hope the amazing dev team look at these performance issues.

**Comment by ourichermath** [comment]
I'm using GrapheneOS (latest version based on Android 12) on a Pixel 3 XL and Signal (5.25.7) is causing a large amount of battery drain on that.  Prior to GrapheneOS going to Android 12, all was fine.  Since then, battery life has been cut in half and when Signal shows up in the list of highest battery users, it's even worse.

**Comment by greyson-signal** [comment]
Hi there, let's merge this discussion with  #11031. Thanks!

**Comment by blastrock** [comment]
Hi,

I wanted to point out that I don't think those two issues are the same. Signal started draining my battery and my wife's (Pixel 4a 5g rooted stock rom, and OnePlus 6T stock rom) a few weeks ago, and #11031 dates back to February. I suspect a recent update broke it for us.

**Comment by greyson-signal** [comment]
There's basically no point in keeping discussions separate, because "my battery is draining faster" is such a difficult thing to root-cause that the best you can hope for is to get everyone having the issue in one place, encourage submitting system bug reports, and cross your fingers that one of those bug reports have actionable information in them.

**Comment by Lawatini** [comment]
I also have a battery drain problem on GrapheneOS (no FCM) but only with cellular data enabled... With Wi-Fi no battery drain.
Here are my debug logs : https://debuglogs.org/a61ab1f76e4d0c3350d5f43a9fd2219dfa871b658b34ad0d1a6a38314e32b9d4
