### ISSUE TITLE
Messages sent to a contact temporarily appeared in another discussion

### ISSUE THREAD

**Issue by hiqua** [signalapp/Signal-Android#11725]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was in "Note to Self" on Android. In the meantime, I was using Signal-Desktop. I switched back to my phone, to see some messages I sent to a real contact from Desktop appear at the bottom of my "Note to Self" conversation. I went back to the main Signal screen on Android, it was not visible from the preview. Entered "Note to Self", and these messages had also disappeared.

### Steps to reproduce

Unknown

### Device info

**Android version:** 11
**Signal version:** 5.24.7

### Link to debug log
https://debuglogs.org/38fae53963465255b583337cf2f0ae0cebf2de209f5ab36a0a1d286097cca08a

**Comment by clauz9** [comment]
This happened to me too, once but I didn't pay much attention to it, because it looked like just a UI glitch, 

It happened while my android synced messages that I sent and received using the desktop client while the Android client was offline, there were a lot of messages from the beta testing group, and a couple of 1 on 1 messages as well, that were syncing, and while it was loading the messages for the beta testing group, I exited the group conversation and opened a 1 on 1 conversation and saw 4 or 5 messages from the beta testing group, showing up in that 1 on 1 conversation that I just opened. 

I hope this helps you find some steps to reproduce... I can't seem to replicate it on my end.

**Comment by hiqua** [comment]
Hey thanks for the input! This kind of issues really looks like a race condition, and given how infrequently they happen and how much attention a user has to pay to notice them, I have little hope of reproducing them reliably manually, but I just hope this'll make the devs aware that some of the shared state if not completely bug-free.
