### ISSUE TITLE
When saving media files to disk (video/photo).  Wrong message pops up: "saved in media"

### ISSUE THREAD

**Issue by snooppr** [signalapp/Signal-Android#11759]
When saving media files to disk (video/photo).  Wrong message pops up: "`saved in media`"

The problem is that Android has a directory `/data/media` and `/storage/emulated/0/media`, and when checking these directories, the downloaded video files are not found.  
The documentation also lacks information where the media files are downloaded and you have to manually search for the directory with the saved data (exactly the path).  

Solution to the problem: when saving files to disk, instead of "`saved in media`" specify the explicit directory :: "`saved in /storage/emulated/0/Movies`".
It is the same for other file types.

**Comment by MouadhKh** [comment]
I would like to fix it. I m on it

**Comment by Aeonitis** [comment]
I had a look at this on Friday night (My first day running the code :) ), but since @MouadhKh actually was the first to jump in, I would like to share my analysis:

@snooppr The exact message is "_Saved to media_" extracted from the String resources and appended [at this line](https://github.com/signalapp/Signal-Android/blob/dce8fde19513a4fe7cc9a0d52e7dfaf26ca5a577/app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java#L316) on post-execution.

@MouadhKh The actual directory was encapsulated in other objects i.e. from [dir](https://github.com/signalapp/Signal-Android/blob/dce8fde19513a4fe7cc9a0d52e7dfaf26ca5a577/app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java#L257) to [contentValues](https://github.com/signalapp/Signal-Android/blob/dce8fde19513a4fe7cc9a0d52e7dfaf26ca5a577/app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java#L270) map shown below, datapath as '_data':
![Capture](https://user-images.githubusercontent.com/1273824/141691123-e4ae3b78-226f-417b-a78a-019f71d2f9cc.PNG)

I guess the plan was to insert into Context [at this line](https://github.com/signalapp/Signal-Android/blob/dce8fde19513a4fe7cc9a0d52e7dfaf26ca5a577/app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java#L273) for future retrieval?

The data seems retrievable with the use of a call to retrieve the Cursor from the Uri the path is encapsulated in, as follows:
`getContext().getContentResolver().query(mediaUri, new String[]{"_data"}, null, null, null)`

I suspect the UX decision on how long that path can be allowed to be on the printed Toast message to the user may be intentional. It seems that the appended suffix text 'media' in "_Saved to media_" is actually a shortened output [of the mediaUri](https://github.com/signalapp/Signal-Android/blob/dce8fde19513a4fe7cc9a0d52e7dfaf26ca5a577/app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java#L104).

I was unsure of what the best way to deliver it so I am glad I'll get to watch the agreed resolution here by you guys!

**Comment by MouadhKh** [comment]
I appreciate your help. I like the suggested approach. I will implement it and would appreciate it if you give me feedback.

**Comment by Aeonitis** [comment]
Hey @MouadhKh,

Unfortunately it might not be a PR worth our time...

1. It's a UI/UX question to raise in the forum in terms of varying length.

2. It kinda breaks the contributing rules of ["Rule 2: The user doesn't know what a key is."](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) for the Signal user.

@snooppr If you feel I'm a bit unfair, could you maybe raise it in the UI/UX forum?


@MouadhKh I really want to contribute but I'm finding it hard to go through 1400 issues, and finding a true issue, as there's also 200+ PRs awaiting approval for up to 3 years... It saddens me that this is the reality of this great app which can do a lot better. Hope you find one.

**Comment by snooppr** [comment]
@Aeonitis Hi!
If you cannot or are not ready (for any reason) to fix the problem, then the way out is simple: update at least the help documentation on the site (add information for users where they can find the downloaded files).  
It's cheap and doesn't require an impossible effort.  
I'm not ready to register on the forum.

**Comment by Aeonitis** [comment]
@snooppr I don't understand the hostility.

I don't think you read what I wrote. It shows, with the fact that you order me for the files needed while I already did.

Hope you have a better day.

**Comment by snooppr** [comment]
> @snooppr I don't understand the hostility.
> 
> I don't think you read what I wrote. It shows, with the fact that you order me for the files needed while I already did.
> 
> Hope you have a better day.

There is no animosity.  (my language is not English, possibly google translate added AI rage).  

I wanted to convey simple thoughts: add information to the documentation 'where to find downloaded files' (in case of impossibility to fix it). I am not registered on the Signal forum (registration is not required). 

Wonderful continuation of the day.

**Comment by alpy91** [comment]
Hello :)

Maybe it would help if there is a button or any form of interaction to open the just saved image in that directory
or an option under save: save and open

Not every user understands, where the image is saved and i think not beeing able to open the image is restricting the user

i will also open a ticket in the UI forum

Have a good day :)

**Comment by Aeonitis** [comment]
@alpy91 that's the right thing to do. The reason is that depending on which Android device and storage configuration is used, the storage directory will not always be the same.

For example, my phone saves it in the /"storage/emulated/0" folder... To the normal non-technical Signal user, they wouldn't know what 'emulated' means, what '0' means or if you saved it in their SD card or even what 'Internal Storage' means.

To be honest, just because I prefer what @snooppr wants for myself, I don't think that Rule 2 in the contributing guidelines will respect that choice.

Let's see what the UI/UX forum decides, it's the best next step for now. 

In a perfect world, Android OS would cut that technical lingo and explicitly state simple drive names in their Operating System API, in terms like 'Main Storage' and 'SD Card'.

**Comment by MouadhKh** [comment]
I would like to get your feedbacks

**Comment by MouadhKh** [comment]
I have just noticed that my IDE  automatically changed the code formatting. I will fix this ASAP

**Comment by MouadhKh** [comment]
I created a new PR without changing Signal initial code formatting. Please review the solution.

Thanks

**Comment by MouadhKh** [comment]
@snooppr can you give it a look please ? thanks

**Comment by snooppr** [comment]
> 

You need to ask the Signal developers a question (I myself am surprised by this attitude from the Signal developers).  I can only see the patched version in a compiled, finished form.

**Comment by MouadhKh** [comment]
It would be nice if a signal developer give it a look. I think the  feature is quite helpful and i m excited to bring it to production( i m ready to make changes if needed obviously)

**Comment by n0valis** [comment]
I came across this issue because I had to google where Signal would store my saved images.
The only thing I can say is: If in 2023 anyone responsible for this App accepts the fact that it is OK that Signal is not only not saying where a saved file goes, but misleads you to a non existing place (media): This is just embarrassing and it shows the amount ignorance for users they must have. They obviously just don't know how many of their  users don't know anything about computers, Android or filesystems. And then to confuse them even more is a nightmare. Whatever is on your bucket list, fix it.
