### ISSUE TITLE
Deleting media deletes the whole message

### ISSUE THREAD

**Issue by p0wl90** [signalapp/Signal-Android#11752]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since my Signal app used a lot of storage, I recently decided to delete all the media files but keep the text messages. Then, all text messages that were sent with attached media files or even text messages with a link preview were also removed. This is not what a users expect when they delete the media files. They expect the messages to still exist, only with some "missing media file" icon. Mabe it would even make sense to replace "media only" messages with that same icon. This is especially important because my workflow is the only possibility to keep a long archive of old messages without using 5+GB of storage.

### Steps to reproduce
- Receive an Image file with an attached text message
- Receive a text message that includes a link as well as a link preview
- Delete all media files in the storage management

**Actual result:** Both messages are fully deleted
**Expected result:** The messages still exist, only the media files are gone and replaced by some "missing image icon"

### Device info
**Device:** Google Pixel 4a
**Android version:** 12 (SP1A.211105.002)
**Signal version:** 5.25.7

### Screenshots // Debug Log
Screenshot or debug log do not make any sense here :)

**Comment by matkoniecz** [comment]
> This is not what a users expect when they delete the media files. 

Well, this is what I would expect. Note that other messengers also work in this way.

**Comment by p0wl90** [comment]
Thinking about it again, I agree that fully deleting media messages with a text could be what users expect when deleting all media files. Maybe a switch to decide whether you only want to delete the media files or also the respective message would be the best here. I think both ways are very valid use cases.

But I still think it is absolutely not expected behavior that text-only messages with an auto-generated link-preview are also fully deleted.

**Comment by Tursko** [comment]
This isn't a bug. Signal intentionally designed it this way. There are feature requests out there related to this, and even @johanw666 has a PR for this exact feature.

**Comment by Herohtar** [comment]
I think this should actually be considered a bug, as it is possible to delete individual images from a message from the full-screen view. The other images and message text will remain. However, when you delete the last image, the message text will be deleted as well. That is inconsistent behavior, and feels buggy.

**Comment by Zwyx** [comment]
Any chance we could revive this now that deletions are synced across all devices? A way to delete media files while keeping the associated messages would be very appreciated.

Also (I'm a frontend dev, so I'm familiar with UX) going to the media view on my phone to delete one _image_ and then find out that the _entire message_ has been deleted was **definitely not expected**. Yes, I know, I haven't fully read the confirmation message (because it simply looks like a regular confirmation message), I realised afterward that it did say that the associated messages would be deleted. So I know it is my fault, but it still not-great UX, in my opinion.

**Comment by veenstrajelmer** [comment]
@alex-signal this seems to me like a useful feature request, even including a PR. Could this be reconsidered?

**Comment by fakob** [comment]
That deleting media files also delete the associated text message is definitely not expected. 

If this is the way it should be handled due to product/security/whatever reasons, please update the design for it. "Hiding" the very important **Any message text associated with this item will also be deleted** in the body text of a standard confirmation message is bad product design.

Please fix this!

![Image](https://github.com/user-attachments/assets/30b8fa69-5cf1-40a1-a0dc-479e450af62f)

**Comment by androidunderground** [comment]
Not being able to delete media files without also deleting the text part of the message is definitely a design flaw. 
It doesn't contribute anything to security or message integrity, since anyone with a rooted Android device can still delete media from /data/data/org.thoughtcrime.securesms/app_parts manually or with a script. 
Of course, this results in invalid references in Signal's message database, so its about time to implement the feature in Signal itself to keep things clean.
