### ISSUE TITLE
Identifiers other than phone numbers

### ISSUE THREAD

**Issue by doherty** [signalapp/Signal-Android#1181]
It'd be nice to be able to identify people by something other than a phone number. Not all my contexts have a phone number, or at least not one I know, but do have an email address, for example. Phone numbers are generally considered more sensitive than email addresses, and have the nice property that it is easy to have many of them, among others.

This might also be an opportunity to think about fallbacks other than SMS, such as email.

**Comment by lukejmorrison** [comment]
Hey @Meredith-Signal any status on when or if this will ever get implemented? 

Has the team considered any of these?

1. The Cardano Global ID solutions: https://www.cardanocube.io/collections/identity
2. The NOSTR NIP-05 Identifier https://github.com/nostr-protocol/nips/blob/master/05.md
3. Or just a basic email address with codes like you do for SMS or a phone call.

I have so many friends who have no smart phone or land line phone because they don't want one or can't afford one and still would love to use Signal Messenger on a basic Linux PC, Windows PC or Mac etc...

Thoughts?
Best Regards,
LukeJMorrison

**Comment by lukejmorrison** [comment]
dID on Ethereum might also be an option. https://ethereum.org/en/decentralized-identity/
