### ISSUE TITLE
Improve feature : notifications

### ISSUE THREAD

**Issue by beatnickgr** [signalapp/Signal-Android#11849]
In Settings > Notification
please separate switches for 

1. group messages
2. private messages
3. message requests

(i'd like to have notifications from people i have already accepted, but not from new people nor from groups).

**Comment by alex-signal** [comment]
Hi! We recently added Notification Profiles which I think will alleviate this issue. It's not a catch-all as you mention, but you'd be able to add anyone you want notifications from, set schedules, etc.

**Comment by cosmo321** [comment]
Profiles are not a good solution to group chats! I'd very much want better notifications. Being in a group chat can be super annoying as I'd get a notification for _every_ new message. Why can't I get a notification for the first new message, then a user defined cooldown until the next notification will appear. I don't need a notification for every single unread reply. The notification is already there. I already know I have unread messages!

For example:
Person1: <some question> -> *Ding*
Person2: <asks for more information> -> *Ding*
Person1: <gives more information> -> *Ding*
Person2: <gives proper answer> -> *Ding*
Person3: <sends a gif> -> *Ding*
Person4: <lol> -> *Ding*
Person1: <thank you person 2> *Ding*

If this happened in the span of 1 minute only the first one out of these isn't annoying noise. Please add a cooldown option before Signal generates a new notification for new messages in the same group. The only thing I hate about Signal as a messaging app is when my familiy groups start a long discussion, and I have to manually mute it for 1 hour every time it happens.

**Comment by beatnickgr** [comment]
cool new feature but it's not really convenient : white-listing someone requires 7 taps.
Furthermore, people not in the whitelist (and therefore muted) don't appear as muted in the chat list, as expected.

**Comment by unhammer** [comment]
I don't use the profile feature, though it looks very fancy. An allow-list is useless since I want notifications no matter who it's from (what if someone I've never met sends "hey it seems your dog has run off I found him eating my petunias"). I just want them to be at a lower volume (or have a less annoying sound) when I'm at work, and I don't t want my phone to beep every single time when someone sends ten messages a minute. 

A cooldown profile I would use. It could simply be lower volume (or alternate sound, like a very inconspicuous bip) if there's already been a notification in the last x minutes. Importantly it shouldn't matter who it's from (the people I care most about send me the most messages in a row ¯\_(ツ)_/¯ )

**Comment by greyson-signal** [comment]
We only use github for bug reports. For feature requests, please use [the forum](https://community.signalusers.org/). Thanks!
