### ISSUE TITLE
In some cases the caption on an image is send as a seperate message bubble

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#11957]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- I have a .webp image with a partial transparent background in my notes to self
- l forward this image to a large group
- I get the option to add a caption and so I write some caption and press send

**Actual result:** The image and the caption appear as separate bubbles. Looking at them on desktop also shows them as separate bubbles, and the caption is displayed above the image even.
**Expected result:** The image and caption are send as one message bubble.

If I forward from the group back to note to self I do see caption and image as a single bubble, as expected.

### Device info

**Android version:** 10.0.0
**Signal version:** 5.31.1

**Comment by cody-signal** [comment]
Thanks for the report. Technically this is working as _designed_. There's an argument to be made for it to behave as you expect, but since the redesign forwarding work was done, what you are adding is not a caption, but adding a message, as the hint text implies.

Feel free to kick up a feature request on the forum. This isn't the first time this has come up.
