### ISSUE TITLE
Signal does not play a ringtone when receiving voice calls

### ISSUE THREAD

**Issue by Ejurety** [signalapp/Signal-Android#11972]
### Bug description
When a voice call is received, the notification pops up, the phone vibrates (even if vibrate is disabled in settings) but NO RINGTONE IS PLAYED. Making it impossible to receive voice calls if you're not staring directly at your phone 24/7. I have allowed all permission for the Signal app, and I have prevented Signal from being restricted by battery saving features. I had this issue but ignored it since I was due to swap phones, I have now setup my new phone to receive the exact same issue on a completely new & different device. Support appears to be an automated bot that doesn't function as it's only reply was that Signal is not up to date, despite it being the current version on google play store making it factually verifyable as definitively up to date.

### Steps to reproduce
- receive a voice call
- hear the lack of ringtone

### Device info

**Device: Oppo A9 2020 &/OR Moto G50 5G
**Android version:** 11 / 11
**Signal version:** 5.30.6

### Link to debug log
Oppo A9 2020 debug log
https://debuglogs.org/aa9de076493e84e8905f604d1ef0adeb85ad469494aa7228036ace793436f433
Moto G50 5G debug log
https://debuglogs.org/665924ab7c560a0b02774d41c3590adec58934f44b1a575c880027665dad36dc

**Comment by openpaul** [comment]
Might be related to the issue https://github.com/signalapp/Signal-Android/issues/10993
There it claims low ringtone volume.

**Comment by cody-signal** [comment]
Hey there, it looks like your logs for the Oppo were lost, so if you could report that would be great.

Your Moto G50 logs show an issue with being able to create the incoming ringer, which we don't usually see so that's interesting. Sadly, we aren't logging the exact issue so I'm going to add it to the next beta so we can see why we can't create the player.

Do you have anything special setup around your ringtone or audio playing?

**Comment by clauz9** [comment]
I got a device with such an issue, I've added a log on the forum.....
