### ISSUE TITLE
Update 5.32.7 - Profile image changed to "+1" automatically

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#12005]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Latest update got the profile image changed to "+1" on some devices.

### Steps to reproduce
- Install version 5.32.7
- After the update check the profile image getting changed on its own to "+1" somehow.

**Actual result:** Profile image getting changed on its own without user selection.
**Expected result:** Profile image should not get changed without user selection.

### Screenshots

![IMG_029310](https://user-images.githubusercontent.com/55331939/154628411-3d97c153-613f-4868-bc5a-7430303c01b8.PNG)

### Device info

**Device:** Multiple
**Android version:** 4-11
**Signal version:** 5.32.7

### Link to debug log

NA

**Comment by greyson-signal** [comment]
Hi there, a debuglog would be super helpful, including from your linked devices. Profiles are things multiple devices can change, and we sort of need to figure out which one did it.

**Comment by desmonk** [comment]
I will try for the log surely.

**Comment by cascheberg** [comment]
I just ran into the same bug. I checked my profile and noticed that my profiles first name and last name were cleared automatically. I did not have an avatar configured for my profile before, so apparently the default avatar that was then generated from my now empty profile name simply was "+1". I checked my own profile on a friends Signal for iOS and it was only showing some default "person icon" avatar (not the "+1") and no name.

I had updated to Signal 5.32.7 from the previous stable release some days ago and had been using it quite often since then. I am even quite sure that I noticed the issue immediately after it occurred. I quickly generated a debug log. I am quite sure that I did not have my only linked Signal Desktop instance running for at least some hours before that, but I started it after I noticed the issue to capture a debug log there as well.

https://debuglogs.org/android/5.32.7/40cba250230f8024aa2395092891bdd0aff702ff815f7c4702380a37f6508930
https://debuglogs.org/desktop/5.32.0/a7d669ecbe997bd9855987a57b73ecdb2e95a8fdae05bf510febcf815d60aef8.gz

Adding my profile name back also fixed my (automatically generated) avatar.
