### ISSUE TITLE
Voice messages do not use bluetooth microphone

### ISSUE THREAD

**Issue by Tursko** [signalapp/Signal-Android#12016]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've noticed recently that when connected to a bluetooth headset or car my voice messages still seem to record using my phones microphone. I would expect my bluetooth devices microphone to be the source.

### Steps to reproduce
- Connect bluetooth earbuds to your phone
- Record a voice message with your phone far away from you.
- Play back the message

**Actual result:** Signal doesn't use the bluetooth microphone.
**Expected result:** Signal should use the bluetooth microphone.

### Device info

**Device:** Pixel 5
**Android version:** 12
**Signal version:** 5.32.7

### Link to debug log

I can get a debug log later.

**Comment by rawlife56** [comment]
You need to give the nearby devices permission to signal

**Comment by Tursko** [comment]
That permission was already allowed.

**Comment by Tursko** [comment]
Still an issue

**Comment by BeyerMart** [comment]
Yeah i noticed it as well.
A friend is always sending my voice messages and is assuming it works via Bluetooth. I don't want to send them away but I can barely understand them.
I think this is a reason for me to try to fix it myself, even though I have crappy Bluetooth headphones and I don't know a lot about Android app development.

**Comment by dj-si** [comment]
This remains a very annoying bug (using version 5.40.4) The Signal Android app has the Nearby Devices permission enabled on my phone, and when making calls via Signal it uses both the earpiece and mic of my Bluetooth device. But when I record a Voice Message the app always uses the phone's built-in mic, which is inconsistent and definitely not as would be expected.

Please fix this so that the mic of a connected Bluetooth device is used for recording Voice Messages. (Or at the very least, as a "non-fix", display a message when recording begins to confirm that the built-in mic is being used, so that people don't record inaudible and useless Voice Messages.)

Thanks.

**Comment by cody-signal** [comment]
We are tracking this internally, and working towards it. There's a library we want to use but is complicated by later android versions. We appreciate your patience.

**Comment by sorryusernameisalreadytaken** [comment]
Since I use Signal as my daily driver, I was honestly quite surprised when I noticed this bug here.

Wouldn't it be possible to have a small toast message that informs users of the corresponding Android version or higher about voice messages with an active Bluetooth headset?

I would never have thought that this does not work until recipients told me again and again that my voice messages are very quiet.

@cody-signal 
Is there any progress to solve this problem?

**Comment by fpellanda** [comment]
And yes, also on my phone with signal version 6.1.4. Still annoying. How can i help?

**Comment by cody-signal** [comment]
No progress has been made yet. I'll bump this again internally.

**Comment by robin13** [comment]
Related to this is the issue of playing mp4 audio on the Signal iOS app:
https://github.com/signalapp/Signal-iOS/issues/3590
As it is not possible to record a message natively in the Signal App on Android, a viable workaround is to use the Android Recorder app to first record the audio (using bluetooth headset), then share it via Signal Android app. This works fine for Android -> Android, but if the recipient is using iOS, they cannot listen to the audio. Just another reason why it would be great to have native support for recording audio messages from bluetooth headset native in the Android Signal App.

**Comment by Tursko** [comment]
Hey Greyson. Has the new commit been tested with Smartwatches (like the Galaxy Watch 4)?

One huge annoyance I have right now with the Bluetooth implementation for calls is that sometimes it automatically chooses my Watch instead of my headphones (whatever the most recent connected device is). It should never choose my watch IMO.

**Comment by Tursko** [comment]
> Hey Greyson. Has the new commit been tested with Smartwatches (like the Galaxy Watch 4)?
> 
> One huge annoyance I have right now with the Bluetooth implementation for calls is that sometimes it automatically chooses my Watch instead of my headphones (whatever the most recent connected device is). It should never choose my watch IMO. I want to make sure that voice memos don't start using my watch as a microphone, that would be even worse haha.
> 
> https://community.signalusers.org/t/stop-auto-switching-to-my-smartwatch-as-a-bluetooth-source/50240

Commit was reverted for now 
https://github.com/signalapp/Signal-Android/commit/0e5031ab451bd069cb5b59f4e57ce166438acf36

**Comment by greyson-signal** [comment]
Yeah, we're investigating how we can distinguish smart watches from other things, so for now we reverted it, but hopefully we can bring it back with some fixes (and use that knowledge to fix issues during calling and stuff)

**Comment by Tursko** [comment]
> Yeah, we're investigating how we can distinguish smart watches from other things, so for now we reverted it, but hopefully we can bring it back with some fixes (and use that knowledge to fix issues during calling and stuff)

Looks like yall figured out a way! https://github.com/signalapp/Signal-Android/commit/ed67e7ac04e76f0a9c07ef65a65d31ddd9fc5faa

Looking forward to when yall re-add BT microphone support for voice memos :)

**Comment by Tursko** [comment]
Now in beta: https://github.com/signalapp/Signal-Android/commit/f1fd29a4777c0dcfd7f9711d71443ecd94e31aaf

**Comment by corrupt** [comment]
This seems to have gone live without warning.
I'm here to ask whether this could be reverted until there is a UI option to choose which device should be used when Bluetooth headsets are connected. 

Since a few weeks ago, Signal will default to using Bluetooth mics for voice messages which is a terrible inconvenience. When driving a lot and switching between calls and voice messages for communication, this means I have to remember to go into Android's bluetooth settings to disable "use for calls" for my earbuds whenever I want to record a voice message, then have to remember to turn it back on afterwards, all while driving. This used to be a total non-issue.
 
At the same time, I keep receiving voice messages from people with terrible, if not inaudible sound quality. Sometimes Signal randomly uses a person's bluetooth-connected watch, sometimes it will use a headset that people have on their desk while walking around, and even when people are aware of this, their bluetooth headsets will usually completely mangle the audio when they are in crowded, noisy places where speaking directly into the phone would still produce perfectly audible sound. 

Please, please, please revert this change asap and create a UI option for this and also some visual indication like there is in Threema for example. There is no way to know which device is used right now, without checking the system's bluetooth settings, and automatically using bluetooth devices is counter-intuitive to what people have come to expect from voice messages.

**Comment by Max-Stirner-Signal** [comment]
@corrupt, Could you please write-in via the app? Go to Signal Settings (profile) > Help > Contact us, making sure to include the debug log. 

What would also be helpful is a screenshot specifically of the microphone selector for voice notes when you have a bluetooth device connected. If you have further questions, including them in the email you send in would be appreciated.

Thanks.

**Comment by panomitrius** [comment]
For me it started to work some months ago and now since a few weeks it has stopped working again. Anyone else experiencing this?

**Comment by Tursko** [comment]
> For me it started to work some months ago and now since a few weeks it has stopped working again. Anyone else experiencing this? 

The change was reverted.

**Comment by panomitrius** [comment]
For me it started to work some months ago and now since a few weeks it has stopped working again. Anyone else experiencing this?

**Comment by Starky** [comment]
> Hi folks, just to be clear, a decision was made to remove the usage of bluetooth for voice recordings. We still use it for playback. Turns out most bluetooth mics are bad (i.e. audio quality is worse than people expect), Android thinks watches are bluetooth mics, and the flows to get users to pick the right one just aren't worth the hassle.

Is there any chance getting this feature back via an optional setting which is disabled by default? I record a lot of messages in my car and it's way more comfortable and safer when I can use my car's mic.

**Comment by sorryusernameisalreadytaken** [comment]
Hi lovely Singal users and maintainer, dear @cody-signal @greyson-signal , just to clarify: This decision was made without the users of signal, those who use it daily.

Bluetooth devices have unique IDs, don't they? Why I cannot create a whitelist with microphones that are good enough and why is it being decided over my head that my microphone is a bad one?
Using a Bluetooth audio device only for playback is not smart.

I am a Signal messenger enthusiast. I have convinced many of my fellow men of Signal and I am also of the opinion that it is a very good messenger with a lot of potential. I have also been donating monthly to the project for over 3 years because I believe in signal. I don't care that an edit function takes several years to become active or that there is no cross-device backup function that works well. But if I have to explain to new users that they can't use their headset for voice messages, it's hard for me to continue to actively support signal messenger. Signal doesn't necessarily have to have all the features that the others have, but some unique features compared to whatsapp and telegram would be nice.

A dynamic and smart selection of which headset microphones to whitelist or blacklist is not witchcraft and could become a key feature of signal.

I am firmly convinced that Signal Messenger should definitely make an effort in this direction.
I am also firmly convinced that this must be included in the signal-update-news. We should not accidentally notice that bluetooth microphones are usable for voice messages again, then suddenly they are not, then they are, and then they are purposely not.

**Comment by greyson-signal** [comment]
@sorryusernameisalreadytaken First off, thanks for all of the support! But this was a decision that was, in fact, made in response to a lot of user feedback. We built it because we thought it was a good idea, but pretty immediately received a lot of complaints. 

Many of those were that the quality was unexpectedly bad (turns out, phone mics are _way_ better than pretty much any bluetooth headset). Also, and this was the real kicker, there's no reliable way (without getting additional permissions) to detect if a bluetooth microphone is actually a microphone... or if it's a watch. Turns out, watches advertise themselves as microphones. This sort of ruined the feature.

To be clear, I could _imagine_ flows that could address this. They would likely, as you suggest, involve the user managing device allowlists/blocklists, requesting additional permissions around bluetooth when you first try to create a voice note, etc. And it just doesn't feel great. It's my understanding that all of this is also the reason why other messaging apps don't use bluetooth for voice note recording (although if you do use one that allows it, please let us know! Maybe something has changed since we last looked).

**Comment by Starky** [comment]
@greyson-signal
> It's my understanding that all of this is also the reason why other messaging apps don't use bluetooth for voice note recording (although if you do use one that allows it, please let us know! Maybe something has changed since we last looked).

Threema allows it and I think it's the best way to implement it via the button.
![signal-2023-11-01-150651_002](https://github.com/signalapp/Signal-Android/assets/383474/66cc5c60-abfd-4f00-a6e6-e5de1058d0e6)

**Comment by greyson-signal** [comment]
Thanks! I'll forward this to our design team.

**Comment by enajx** [comment]
@cody-signal @greyson-signal Since the feature is already implemented, could you push it to the beta version as an deep setting that power users could use? That way it prevents standard users to get bad quality audio by accident but allows advance user to select the input source.

**Comment by dzenifr** [comment]
I find this whole conversation odd because I've been unable to use my BT headset microphones with Signal for months now (Android), which I find really obnoxious. The oddest part is that I have a friend (iOS) who can user their BT headset to send messages. Is it an ios vs Android thing?

As a multiple years-long user of signal, I would gladly do whatever beta/power user shenanigans necessary to have this capability. I want hands free audio messaging back. I use it all day long most days. 

Please. 🙏🏼

**Comment by SayeedAmitabTimo** [comment]
Isn't it likely that many of the complaints about poor audio quality, were due to people not even realizing, that audio recording was switched to the Bluetooth device. Meaning they suddenly spoke toward the wrong mic, rather than using a bad bluetooth mic?

But anyway, I think the Threema solution, as pointed out above, is perfect, and I am here to leave my vote:
<img width="645" alt="chrome_4VPFVCUPoZ" src="https://github.com/signalapp/Signal-Android/assets/38976578/e97d6224-203a-4fa4-8e46-92b2657ee3cf">

**Comment by panomitrius** [comment]
One more vote to this option available again!

**Comment by cody-signal** [comment]
We appreciate the request and desire. And we tried real hard to do this a couple quarters ago, but it was full of issues and not just user confusion.

We use GH for error tracking not feature requests. If you want to continue championing for this as a feature, please take it to our community forum. Appreciate your enthusiasm.
