### ISSUE TITLE
Signal working only on WiFi, not with cellular data

### ISSUE THREAD

**Issue by GiamBoscaro** [signalapp/Signal-Android#12026]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
This is a follow up from #11839. The issue was closed and, as requested, I am opening a new one to solve this problem, that seems like is not caused by mobile providers, even if the bug seems the same.

Signal is only working on WiFi for my girlfriend, that is using ho.mobile on an Android phone. I am using Vodafone IT on an iPhone and everything works perfectly.
She cannot send or receive any message or media, Signal is completely unusable while connected to the mobile network. This has been going on for months and it is really hard to justify keeping using Signal. I really do not want to go back to Telegram or WA, please help me solve this.

### Steps to reproduce
- Send a message over cellular, does not work
- Connect to Wifi, message is received
- Send messages over WiFi, everything keeps working

**Actual result:** Nothing is sent or received over cellular data
**Expected result:** Everything should work over cellular like over WiFi

### Device info
**Device:** Google Pixel 4a
**Android version:** Latest
**Signal version:** Latest

### Link to debug log
https://debuglogs.org/android/5.32.7/1c40e951fd80cb3b378859bd6f23ae1a1154af835fdf0f70a6afb06d8bc72c8a

**Comment by woheller69** [comment]
I have a similar problem. Signal seems to lose push connetion when changing network: Wifi<->cellular and vice versa.
If I never use Wifi it works fine. But if I switch on Wifi when screen is on and Wifi off when screen is off it fails.
WhatsApp does not have this problem.
If I keep wifi on when screen is off it also loses connection after a while. Removing battery optimization does not help either.
I also allowed unrestricted network access without success.

**Comment by twity1337** [comment]
Same problem on my friends phone:
- Android 10 / EMUI 10, Huawei P30
- Message gets delivered with delay of 1 minute after switching from Wifi to cellular data
- As soon as Signal is opened on the phone, messages are delivered instantly.
- There are no "received" messages sent from the phone. So messages still have only one tick on the sender-side after reading them on the recipient-side.
- Sending text messages is also heavily delayed (or not possible?) - I only can see the spinning circle.
- Full access is given for the Signal-app (data access, run in background)
- For some reason, vibration is sometimes faulty (instead of "brrr-brrr" it's only a "brr........br" 😅), not sure if this is related.

Attached, you can find the log from my friends phone (I tried sending messages from 19:23 to 19:38; since 19:29 I did not get any received/read receipt message any more):
[178c7c5112f2ca8820546850e84267b5cfd480768c8586ef0f3c2ed2bbed08f1.gz](https://github.com/signalapp/Signal-Android/files/8188155/178c7c5112f2ca8820546850e84267b5cfd480768c8586ef0f3c2ed2bbed08f1.gz)

**Comment by greyson-signal** [comment]
We have some changes going out in 5.33 (going to beta today or tomorrow) that will hopefully either improve things or at least provide more debugging info.

**Comment by woheller69** [comment]
any news regarding a  fix?

**Comment by GiamBoscaro** [comment]
> any news regarding a fix?

I don't know. my girlfriend said that Signal is working now. Not perfectly, but seems like it is again working normally on cellular. So I guess it was fixed?

**Comment by woheller69** [comment]
for me it does not work v5.36.3

**Comment by greyson-signal** [comment]
If something isn't working for you, please share a link to a [debuglog](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug).

**Comment by woheller69** [comment]
https://debuglogs.org/android/5.36.3/f0eb2728686514eb40310142734315d5587eac74a61661cca6d2ff856a317c81
Again the latest message only arrived after opening the app

**Comment by woheller69** [comment]
What about adding an option "Use Websocket instead of Google Play Services"?
This would give the user a choice to work with or without Google and we could find out if the problem is caused by the Google stuff.

**Comment by woheller69** [comment]
I installed Signal-FOSS https://www.twinhelix.com/apps/signal-foss/ and there everything works fine.
All messages are received immediately. Unfortunately at the price of a lot higher power consumption.
So that is not a good solution either. 
But I wonder why that websocket implementation consumes so much energy. My IMAP email also receives notifications immediately without Google services and does not need so much energy.

**Comment by woheller69** [comment]
Still missing messages. WhatsApp does not have that problem. Why do Google Play Services work for them?

**Comment by cody-signal** [comment]
For some more context around notifications: https://github.com/signalapp/Signal-Android/issues/8692#issuecomment-
1175258671

We've added some more logging in recent updates, can you provide a new debuglog please?

**Comment by woheller69** [comment]
https://debuglogs.org/android/5.42.8/0b89934c10c93e1020fe0a93160ac96de9d0e01a87d753afc6a0f1e5e6f2fbd4

**Comment by woheller69** [comment]
I now tried 

    dumpsys deviceidle whitelist +org.thoughtcrime.securesms

Hope that helps

**Comment by cody-signal** [comment]
Holy mother your FCM messages for Signal are insanely delayed, averaging ~5-6 hours. I'd recommend checking battery/background configuration on your device. This is super odd but sadly not something we can control.

![image](https://user-images.githubusercontent.com/66265416/179264816-26e82049-f7f5-4587-80a3-163d929e0564.png)

**Comment by woheller69** [comment]
No problem with WhatsApp. How do they control it?

**Comment by woheller69** [comment]
I found that com.google.android.gms was not listed in

    dumpsys deviceidle

now added it 

    dumpsys deviceidle whitelist +com.google.android.gms

Hope that helps

**Comment by woheller69** [comment]
so far 

    dumpsys deviceidle whitelist +com.google.android.gms

seems to fix the problem for me.

**Comment by greyson-signal** [comment]
Probably best to absorb this into #8692
