### ISSUE TITLE
Can't enter passwort to restore backup

### ISSUE THREAD

**Issue by NBirkenstock** [signalapp/Signal-Android#12088]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug Description:

I created a backup file before removing signal. For the password I used letters and symbols. After reinstalling I wanted to restore the backup but signal only accepts numbers for the password.

### Steps to Reproduce:

    Create backup with password containing letters
    Remove and reinstall signal
    Try to restore backup

### Actual Result:

No messages restored

### Expected Result:

All messages restored

### Device info

**Device:** Poco X3 NFC
**Android version:** 11 (MIUI 12.5)
**Signal version:** 5.32.15 and latest beta (5.34)

### Link to Debug Log

I didn't got so far to create a log. Error occurs before I the normal HMI is accessible.

**Comment by clauz9** [comment]
ok .. let's get some terminology straight 🤔 

when you create a back-up.. Signal gives you a 30 digit password to write down. 
and you create a back-up by going to Settings -> chats -> chat backups

when you register your phone number, or from Settings -> Account -> Enable PIN, you  get the option to set a PIN, which can be an alphanumeric PIN or just Digits. 

since you're talking about creating a password with letters and symbols, I think you're talking a PIN, not a back-up. 

the PIN is requested after you register your phone number with signal, and the UI does start with only digits available, but you do have the option of selecting "Alphanumeric" as PIN type 

![image](https://user-images.githubusercontent.com/77681918/159473022-119e6ddd-d9c8-479d-a222-cbcf3f9a86c1.png)

if you tap that "alphanumeric" option, you will be able to enter your password with letters and symbols.

**Comment by NBirkenstock** [comment]
I thank you very much. Terminology was exactly the problem, not something technical. I just tried to enter the wrong passwort at the wrong place. I believe there was a misunderstanding when reading english support articles while using a non english Signal version. I have to repeat the procedure next week, so I will have a very close look to what words are used exactly in which case. If I find something to improve, I will try to improve the documentation, but for now this bug is totally closed... because there was no bug in the first place.
