### ISSUE TITLE
Freemobile SMS API no longer works since the last update

### ISSUE THREAD

**Issue by plegrand1** [signalapp/Signal-Android#12157]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello,
I have been using the Freemobile API for a long time to send SMS via it:
https://smsapi.free-mobile.fr/sendmsg 
https://smsapi.free-mobile.fr/sendmsg?user=login&pass=passwrdd&msg=message

Since the last update of Signal, I don't receive these SMS anymore, even though I receive them with the SMS application installed by default on my smartphone.
Any idea where the problem could come from?
Thanks for your help.

### Steps to reproduce
- Send SMS from API : SMS not received from signal
- Send SMS from API : SMS received from default sms application

### Device info
**Device:** Xiaomi MI9
**Android version:** 11
**Signal version:** 5.34.10

**Comment by UserX404** [comment]
If your application sends sms with your own number (same as signal is registered with) it get filtered.
Discussed here:
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-34-release/42820/179
Commit:
https://github.com/signalapp/Signal-Android/commit/c7a345eb0bb56026ad07fa7d66e872650b1521e6

**Comment by plegrand1** [comment]
I'm not sure I understand.
Indeed the application sends a sms with my own number as recipient from my own number.
But it worked before.
The problem would come from a recent update?
Does this mean that it will be fixed in a future update?
Thanks for your answer.

**Comment by greyson-signal** [comment]
Hi there, there was a relatively massive [SMS spam campaign](https://www.theverge.com/2022/3/28/22999719/spam-texts-own-phone-number-verizon-att-tmobile) that resulted in people getting SMS messages from their own number. We knew that some people may be using some web services like this, but we still thought the best course of action was to drop SMS's that are sent from your own number. Apologies, but I hope you can understand.

**Comment by aaribaud** [comment]
Could this not be made at least a user option?

**Comment by schklom** [comment]
> Hi there, there was a relatively massive [SMS spam campaign](https://www.theverge.com/2022/3/28/22999719/spam-texts-own-phone-number-verizon-att-tmobile) that resulted in people getting SMS messages from their own number. We knew that some people may be using some web services like this, but we still thought the best course of action was to drop SMS's that are sent from your own number. Apologies, but I hope you can understand.

You could at least make it into an option instead of deciding for everybody that they don't want or need it.
Sending myself SMS is the best way to get personal notifications because I don't have reliable Internet 24/7 everywhere I go, but there usually is enough service to receive texts.

Making it available as an opt-in function would solve the spam campaign problem while not screwing people who have relied on it until now. Please don't make people downgrade the Signal app just because of this. I will if I have to, but I really don't want to.

**Comment by plegrand1** [comment]
To go in the direction of the previous posts, it seems to me that it would be good that this option exists, even if it means preventing the risks of spam when it is activated.

**Comment by JohnStrunk** [comment]
This appears to also be blocking Google Fi's voicemail transcription SMS messages. I can see that Fi sends the SMS (via their logs in my account), but it doesn't appear in Signal.

Since Fi shows it as being sent from my own mobile number, I assume it's being filtered by c7a345eb0bb56026ad07fa7d66e872650b1521e6

@greyson-signal Please consider re-opening this since it's breaking one of the carrier's services, not just a niche use-case.
