### ISSUE TITLE
Target Newest Android Version

### ISSUE THREAD

**Issue by singhalrishi27** [signalapp/Signal-Android#12161]
You should Target latest Android version coz at some point you must. It will ensure a greater compatibility with newest phones also that splash screen Android 12 adds by default is really bad signal should use or migrate to the new splash screen API.
On Android 12 Signal takes Nearby Devices permission by default i don't have idea why a chatting apps needs Nearby Bluetooth Devices permission, And it happens without user consent.
Atleast update your CompileSDKVersion to API level 32 for now.

**Comment by greyson-signal** [comment]
Hi there, we're very aware of all the targetSdk stuff. Targeting 31 will take some actual work from us due to some of the changes in it. 

Concerning the nearby devices permission, I think that's a new Android 12 thing, and it's probably because we request bluetooth permissions for calling. We don't, like, explicitly request Nearby Devices. I think it's just a label that gets slapped on us until we do the new Android 12 bluetooth permission stuff.

But we don't use github for random discussion, just bug reports. For more general chatter, please use the [forum](https://community.signalusers.org/). Thanks!
