### ISSUE TITLE
Reply to SMS should send a SMS by default

### ISSUE THREAD

**Issue by ultrasuperpingu** [signalapp/Signal-Android#12200]
Couple a friends use Signal as SMS application. It won't be a problem if their reply would be a SMS but it's a signal message by default. I almost deleted my signal account to be able to get SMS back when they reply to a SMS from me before one of my friend found the option to do this. I think this option is a little "hidden" but it's not the problem. The problem is (for me), by default, if a message is received from some channel, the response should be sent on the same channel. It is almost like if you send me an email and I reply with a post mail. It doesn't make any sense. And it's a problem for the receiver. He gets no way to fix the problem on its side...

**Comment by alex-signal** [comment]
I'm very confused, do your friends not use Signal for normal Signal messages? Or is there a reason you'd rather communicate with Signal users via SMS?

**Comment by Tursko** [comment]
Falling back to SMS automatically is a security risk. What Signal needs to do is make SMS message you receive more obvious overall. The frustration probably comes from replying to the message and not realizing you sent a Signal message instead of an SMS or vise versa. 

I'm not sure why your friends would be forcing you to use Signal as your SMS client though. If you don't like the integration you should just use a standalone client like Google Messages along side Signal.

**Comment by Tursko** [comment]
If you switch to another client then the SMS messages will be managed through there. It would certainly remove the confusion.

You're right, its not actual fallback, but Signal isn't going to automatically switch to SMS since its a security risk. It's actually designed to automatically switch to Signal once a Signal message is sent. 

I'm a user that uses Signals SMS integration because I want my messages to be combined. But I've been critical of the integration the past couple of years because although it works well it can be really confusing at times. I don't think the Signal team would even consider automatically switching to SMS when receiving an SMS. It's the exact opposite of what they want you to do. But I think it would be useful if those SMS messages were more obvious so the recipient could make the choice to switch to SMS sending. 

The easiest solution is to manage your SMS messages through a dedicated SMS client, and use Signal only for Signal.

**Comment by clauz9** [comment]
It's a point of common decency, that one should not force one's friends, to resort to less secure communication methods like SMS, just for one's self 😆 

now, all joking aside 🤔 how would this work ? 

> But they thought, like me, that replying to signal message would send a signal message and that replying to SMS would send a SMS.

you want the transport method to change between Signal message and SMS according to the last received message in a conversation ? 

what if you've typed a relatively long message, and right when you want to tap send, you receive an SMS and you send your message as SMS because the transport method has changed to SMS 

your friends could change the transport method to SMS by tapping and holding on the send/plus button, and selecting "insecure SMS" and that option will be remembered, until they change it back to Signal message manually.... and since you don't use Signal messages that often they wouldn't have to do the change to often. 

but feel free to present the way you see it working 🤔

**Comment by ultrasuperpingu** [comment]
@clauz9 
You're pointing very interesting things :)

> you want the transport method to change between Signal message and SMS according to the last received message in a conversation ?

Yes, I think a SMS client should behave as a SMS client. There is no "conversation" in SMS protocol, so if you reply to a SMS, I really think the answer should be sent via SMS.

> what if you've typed a relatively long message, and right when you want to tap send, you receive an SMS and you send your message as SMS because the transport method has changed to SMS

In that case, Ok, why not sending a Signal message because it's too long for a SMS (My SMS client switch to MMS and I know some other just doesn't allow it, so, it's ok to me). But if you receive back a SMS, that mean that your contact specifically wanted to send a SMS (because he received a Signal message, so, if you are receiving a SMS back, that means he did it on purpose), so the reply should be a SMS I think.

> your friends could change the transport method to SMS by tapping and holding on the send/plus button, and selecting "insecure SMS" and that option will be remembered, until they change it back to Signal message manually.... and since you don't use Signal messages that often they wouldn't have to do the change to often.

I know (since one of my friends figure this out) and it's great. And I'm not against the feature to send a signal message as reply to less secured message. I just think it should not be the default behaviour. The problem is: each time one of my contact switch to signal as SMS client, I have to tell him how to send me SMS back to my SMS.

As a general thought (in the context of a message app), I think that a reply to a message should always be sent with the same medium. If somewhen, Signal implements others protocols (let's say something stupid as an example: Facebook or Twitter), a message received by that channel should be replied in my opinion with that channel.

Here, for me, the main issue is that the receiver of message sent by the app has no other way to fix his pb but delete its Signal account...

That being said, I just deliver my opinion here. That a very good property of open source projects. But I know people can disagree and I'm ok with that. Last call belongs to the developers :)

**Comment by Tursko** [comment]
Btw this is very obviously a feature request and we should probably bring this discussion to the forums instead of GitHub.

**Comment by ultrasuperpingu** [comment]
The feature exists so it's more a problem on what should be the default behaviour. For me, it's even a specification issue but I understand you could disagree.

**Comment by Tursko** [comment]
It doesn't exist by design. It's not a bug, this is a bug tracker.

**Comment by cody-signal** [comment]
As recommended by @Tursko , please take this to the community forums. Thanks for keeping the conversation here civil as well.

**Comment by ultrasuperpingu** [comment]
> Thanks for keeping the conversation here civil as well.

I'm really sorry if my message looked uncivil. I really didn't mean to. English is not my native language, I may have used words or expresssion interpreted as a little harsh but I swear it was not on purpose. Sorry again.

**Comment by ultrasuperpingu** [comment]
I'm just adding the conversation on the forum on this subject :
https://community.signalusers.org/t/respond-to-sms-messages-with-sms-messages-or-alternatively-persist-sms-settings-for-contacts/28172/10
