### ISSUE TITLE
Transferring to new device resulted in split profiles, split chat history, removal from group chats

### ISSUE THREAD

**Issue by ChimeraCoder** [signalapp/Signal-Android#12268]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I got a new device, and while transferring Signal to the new phone, two things went wrong, and it resulted in my profile being "split". This results in a lot of inconsistent state

1. I was removed from every group chat I was previously in, with no way to rejoin (short of getting someone to re-add me)
2. All of my old chats with others transfered correctly and appear unified to me; however:
3. For all my contacts, my messages now come from a new contact *with the same old phone number*, but with an empty chat history. All previous messages are associated with a different contact that has no phone number attached.
4. All my old "Note to Self" messages are now listed as a chat with user "Aditya Mukerjee", and new notes to myself are listed as a separate chat.

### Steps to reproduce

Here are the steps I took, and I believe they should reliably reproduce the bug.

- Initiate transfer to new phone
- After a while, the old device says that the transfer has completed, but the new device still says "Transferring Signal to a new phone" and spins indefinitely. I believe the issue here is because the screen turned off during the transfer.
- Set the screen display timeout to 30 minutes
- Initiate transfer to new phone (this time, "Transferring Signal to a new phone" terminates on the new device)
- Begin the registration flow. I have two phone numbers (one which I only use while traveling, and my main one, which is registered to Signal). Signal automatically detects my traveling number, *not* the one which was registered on the old device, so I end up using that to proceed with the transfer
- The new device *is* now registered correctly; however, the old device is stuck on the modal which has two options - I forget the exact wording, but something like "Cancel and keep this device registered" vs. "Okay". Clicking the second one causes the modal to flash, disappear for a split second, and reappear. In other words, the old device is stuck in this state with no way to proceed, while the new device appears to be working correctly. Presumably this is because the phone number differs.
- I realize that the devices are registered to different phone numbers, so I attempt to fix this by going to Account >> Change phone number, which appears to be the only way forward (the old device is stuck on the modal, so there's no way to do anything else with it.
- This "works", except now I have been removed from all my old groups, and also all of my contacts are having issues contacting me.

Weirdly, Signal **does** correctly ask for the PIN associated with the account when reregistering the phone number, so it does know that the old account exists somehow, but it doesn't actually recognize the account that the phone number was attached to.

I tried reregistering the phone number to the old phone to see if that would fix it, but it does not - the old phone, even after reregistering the old phone number, still appears to be using a separate profile from what it used before. I can't figure out any way to transfer that profile, let alone merge the two.

This is problematic because it incorrectly shows me as "not a Signal user" in my old chats when other people try to message me, and when I message them, it shows up as a "message request", even though I'm already in their contacts.

**Actual result:** Transfer works successfully
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

#### After registering the number to the old phone:

![Screenshot_20220527-114231~2](https://user-images.githubusercontent.com/376414/170734160-46d8d60b-8947-491c-9c4f-2127db41ee6c.png)

#### What it looks like for an established contact to send me a message when the number is registered to the old phone:

![Screenshot_20220527-115000~3](https://user-images.githubusercontent.com/376414/170735160-0b4913f2-d510-408d-889a-ed5eb0ce93ad.png)
![Screenshot_20220527-114948](https://user-images.githubusercontent.com/376414/170735170-f6ee0add-79d0-4989-b950-b3d8649dd877.png)
![Screenshot_20220527-115523](https://user-images.githubusercontent.com/376414/170735382-b0308568-2f50-4074-819e-a5f65fa8e020.png)

### Device info

**Device:** Pixel 6 Pro
**Android version:** 12
**Signal version:** 5.36.3

**Comment by cody-signal** [comment]
When you register with a different number than the backup, this creates a new account with new identifiers. This is why all of the restored chats/groups aren't valid anymore.

If you still have the original number. I would recommend re-registering with that number and then using the change number feature to change to the new number.

**Comment by ChimeraCoder** [comment]
> If you still have the original number. I would recommend re-registering with that number and then using the change number feature to change to the new number.

I'm not sure I follow - I'm not trying to change my number. Right now, I've got my new phone registered using the original number (which is the number I want to use), and I got that by using the change number feature. The issue is that, by doing so, I've now got two accounts - the old one, which now has no number attached to it, and which I can't seem to access in any way even though it's the one all my contacts have in their phones, and the new one, which is not a part of any groups, and which appears to my contacts as a new message request even though it has the same phone number that I've always used with them.

**Comment by greyson-signal** [comment]
Underneath all the phone number stuff, you have a unique identifier called a UUID. This is what determines if you are a member of a group and stuff.

You started out with UUID A. Then, after you did a device transfer to a _new_ number, you were assigned UUID B, since registering with a new number creates a new account. 

The "Change Number" flow is what you use to change your phone number while keeping the same UUID. However, you changed your number _after_ you were assigned UUID B, meaning that you now have your original number again, but with UUID B instead of UUID A. This is why you're no longer in groups and why people are seeing message requests from you.

If you had changed your number _before_ doing the device transfer, or if you had did the device transfer using your existing number, everything would work as expected. Unfortunately there isn't much you can do now besides getting re-added to all of your groups.

Registration and device transfer are both complex flows that can result in a lot of weirdness in certain niche situations. Unfortunately this is all working as expected. From the service's perspective, some random person has now registered using your travel number, and then changed numbers to your original signal number. The service doesn't know that underneath, you're the same physical person.

One thing I think we can do better on is the pre-population of the number after a device transfer, and warning the user if they use a different number than we find in the backup.

Overall, I'm sorry we can't fix your device, but I hope this explanation helps you understand why it happened.

**Comment by Bakan0** [comment]
> Underneath all the phone number stuff, you have a unique identifier called a UUID. This is what determines if you are a member of a group and stuff.
> 
> You started out with UUID A. Then, after you did a device transfer to a _new_ number, you were assigned UUID B, since registering with a new number creates a new account.
> 
> The "Change Number" flow is what you use to change your phone number while keeping the same UUID. However, you changed your number _after_ you were assigned UUID B, meaning that you now have your original number again, but with UUID B instead of UUID A. This is why you're no longer in groups and why people are seeing message requests from you.
> 
> If you had changed your number _before_ doing the device transfer, or if you had did the device transfer using your existing number, everything would work as expected. Unfortunately there isn't much you can do now besides getting re-added to all of your groups.
> 
> Registration and device transfer are both complex flows that can result in a lot of weirdness in certain niche situations. Unfortunately this is all working as expected. From the service's perspective, some random person has now registered using your travel number, and then changed numbers to your original signal number. The service doesn't know that underneath, you're the same physical person.
> 
> One thing I think we can do better on is the pre-population of the number after a device transfer, and warning the user if they use a different number than we find in the backup.
> 
> Overall, I'm sorry we can't fix your device, but I hope this explanation helps you understand why it happened.

Hopefully I'm allowed to comment on this closed issue (and not reopen), as I wanted to add some post-mistake information that may help people in the future. 

THANKS TO THIS POST BY @greyson-signal, I was able to think through my mistake and actually resolve it, and only lose ~2 weeks of messages on my computer (which was wiping all data each time I tried to restore).

I had a Signal backup pre-number-change-mistake. <--- THIS IS KEY. If you do not have a pre-mistake backup, I would imagine you are at a 100% loss. I also had an lvm backup of my machine that was getting wiped... Since I had made the change of phone number AFTER the transfer to the new device, I was experiencing the same exact issue as @ChimeraCoder.

Here was how I recovered:
1. Wipe Signal data on new phone
2. Transfer old (functional/working) backup file to new phone
3. Restore backup on new phone, but use the undesired phone number/account, having the correct UUID with the wrong phone number
4. Use "Change phone number" function to update to desired phone number
5. Profit

**Comment by Glean-Koto** [comment]
I was in the exact same position and I found a way to reverse this without a prior back-up.

For ease of reference, let's say I start with device A with number A. I transferred to device B with number B and changed to number A. Here is what I did:

1. Change to number B in device B.
2. Transfer from device B to device A with number A.
3. Change to number B in device A.
4. Transfer back to device B with number B.
5. Change to number A in device B.

I imagine what's happening is that the UUID is uniquely determined by the initial phone number and any new registration of a number overwrites any account with that number. (So some of these number changes may actually be unnecessary and we may be able to just, say, condense the last three steps into a single transfer, but sometimes it gives me error connecting to service, so I don't know) I found this out by re-registering a new account with number A after step 1 and somehow managing to regain control of the "unknown" account with no number (without the chat history, but is still able to message in the groups I was in after someone else sends a message out). I don't know if this is how it was in May 2022, but at least this works now.

**Comment by kate-harrison** [comment]
> One thing I think we can do better on is the pre-population of the number after a device transfer, and warning the user if they use a different number than we find in the backup.

@greyson-signal, is there an issue tracking this? I just hit the same bug last week and it was very distressing. As an outsider, this seems like a relatively easy fix to what probably feels like a major problem for any user who hits this issue.

This warning would ideally also inform the user that their desktop app will lose all of its history as well, since I was very surprised to see data loss on my laptop after touching only my phones.

---------

For anyone else finding this bug, I tried the steps in the [comment above](https://github.com/signalapp/Signal-Android/issues/12268#issuecomment-1666428254) and they **WORKED**! Some notes for anyone else in this unfortunate situation:
*  I'm using two Android phones.
 * At step 2 I had access again to my groups, though of course this was on Device A so it was of limited utility. I decided to make a local backup at this point so that I would have more recovery options if I needed them.
 * At step 2, I updated my alias from Alias B to Alias A. (When I did the original transfer that caused all of this trouble, it told me that Alias A was taken -- this was my only clue something was wrong in this entire process -- so I created Alias B.) I have no idea if this was necessary or not.
 * For each of the "Transfer" steps, I just used the "Relink" option presented in the UI. I did not wipe any local data, explicitly sign out, etc. -- I just did the easiest thing that was suggested to me by the UI.
 * Before starting any of the steps, I translated the instructions from "A" and "B" language to actual phone numbers and device names. I highly recommend this because it's otherwise very easy to get confused about which number goes where and when :)
 * The evening after I performed these steps, I was unexpectedly signed out of Signal on Device B while away from home. I tried to sign in again, but it showed scary messages suggesting I'd lose all of my message history so I just left myself logged out. Once I got home, I signed into Device A and then moved to Device B again, which worked without a problem (using my original phone number). I lost "only" the messages that had been sent between my afternoon transfer and my evening re-transfer. Moral of the story (for me): don't trust Signal to be reliable for a while :/

Once I got my phones sorted out, I still had a lot of trouble linking my laptop again. In the end, I had to re-install the app on my laptop and give up on keeping any of my conversation history -- which again was a pretty unexpected outcome since theoretically I was just changing phones, and not intending to do anything with my laptop. (IMO the UX doesn't make it clear that the laptop app's existence is entirely dependent on the phone.)

**Comment by BhaveshDiwan** [comment]
I'd like to add my two cents here: this issue is still observable as of 2026.06.

I was eventually able to resolve it after multiple rounds of trying the suggestions from the two comments above. However, the process was not straightforward, and unfortunately I can't say exactly which combination of steps ultimately fixed it.

I can confirm that I had to completely wipe the Signal app and restore from backups (which I created at every step along the way). Simply re-registering from the UI did not work in my case. It doesn't matter which SIM is in which phone, you can manually type the OTP from the SMS if working with 2 devices.

---

I was also able to preserve my Signal Desktop data without much trouble. The key was not launching the desktop app while performing this procedure, so it couldn't connect to the internet and potentially sync any unwanted state.

Once I was able to confirm with friends that I was communicating through the existing conversation history (rather than appearing as a new profile/contact), and had access back to all my groups, then only I relinked the desktop app. When prompted, I selected the option to link the existing desktop installation rather than transfer data from the phone (I unfortunately don't recall the exact wording used in the UI).

Also, please back up your Signal Desktop data directory (~/Library/Application Support/Signal on macOS or ~/.config/Signal on Linux) and your database encryption key (for example, from GNOME Keyring or macOS Keychain) before attempting any of this. It can save you a lot of pain if something goes wrong, and give you unlimited attempts to restore.

---

Finally, I would strongly recommend first restoring everything using your previous phone number on the new device and ensuring both the mobile and desktop apps are functioning correctly. Only after confirming that everything is in order should you initiate the phone number change via Settings → Account → Change Phone Number. This sequencing may be important.

**Comment by allmynamesweretakenomoreideas** [comment]
I have the Signal wrong pre-filled number issue as well.

My old phone died, but luckily the Signal Backup was on SD Card - so I put in the Card into the new phone and restored Signal but accidentally with a new phone number.

First promt in Signal was the question if I want to change to the new (better, faster) backup format - I clicked yes.
Then I realized the split account.

- Old backup has been overwritten by Signal in the new format
- Old phone is dead 

If I get the information in this thread correctly - under these circumstances I have no chances of recovering my old account right?

I guess I lost everything ¯\_(ツ)_/¯
