### ISSUE TITLE
A trailing dash/hyphen of an URL is not "hyperlinked"

### ISSUE THREAD

**Issue by gediminasel** [signalapp/Signal-Android#12288]
#11310 was closed by StaleBot but is still relevant.
Many websites don't load correctly when a trailing slash is missing.
![image](https://user-images.githubusercontent.com/21194519/173418096-020d2d46-a3eb-46a7-8aad-0116590ae13a.png)

**Comment by gediminasel** [comment]
Why not planned? 😢

**Comment by greyson-signal** [comment]
Sorry, should have explained, but we use the built-in android linkifier. There's a lot of funny situations you can get into around link parsing, and rather than try to write our own, we rely on the systems. But that means we get the system's bugs, too. But I still think this is the best path forward for us.
