### ISSUE TITLE
Signal fails to grab audio focus when playing audio messages

### ISSUE THREAD

**Issue by jcollum** [signalapp/Signal-Android#12328]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I play an audio message on Signal while a podcast or Spotify song is playing I get both audio streams at once. Same thing happens with Telegram audio messages. 

### Steps to reproduce
- play audio in Spotify / Beyond Pod / Telegram
- go to Signal 
- start playing an audio message in Signal 

**Actual result:** both audio streams play at once 

**Expected result:** Signal asks for audio focus and the other stream stops playing 

### Screenshots

N/A

### Device info

**Device:** Google Pixel 3A XL
**Android version:** 12 May SP2A.220505.006
**Signal version:** 5.41.11

### Link to debug log

https://debuglogs.org/android/5.41.11/7bf810dcf299e8777b6d493674853f0b2d3a57fca55f89f6f70fb104aa2149c8

**Comment by major-mayer** [comment]
Yeah, this is a long-standing issue and unfortunately the Signal devs/ community think this is the right, intended behavior:
I already reported this in their forums, because it's not really a bug, but more of a feature request.
- https://community.signalusers.org/t/pause-playback-lower-volume-when-playing-voice-messages/38464
- https://community.signalusers.org/t/turn-down-the-volume-while-recording-a-voice-note/34938 (the same for recording voice messages)


I find the current behaviour extremely and completely unnecessary, but I don't know what else I could do to get more attention from the devs/ UX designers at Signal. It would be really easy to fix this.

**Comment by major-mayer** [comment]
At least for playing voice messages this seems to be fixed.
Yet when recording voice messages, the music continues to play.

**Comment by jcollum** [comment]
Yeah I don't think this should be closed. I just checked it again. It is still a bug. I have the audio recording here: https://drive.google.com/file/d/1PqCaP01JGSBZqZnvNfclTUrxZIBGd-eO/view?usp=sharing. That's me saying "check check check" in a Signal message while a podcast is playing on my phone. 

5.49.4

**Comment by muessjoeh** [comment]
This behaviour annoyes me a lot. 
Since there is a lot of disagreement, it should be configurable whether there is generally audio focus when running the app or not. So everyone should be happy.

**Comment by major-mayer** [comment]
I am on 5.50.2, maybe you just have to wait a bit

**Comment by muessjoeh** [comment]
What really annoys me is when you get a phone call while you listen to a podcast. Signal does not request the audio focus, so there are two sounds at the same time,which is really, really bad.
Since there are reasons for both behaviours here, the easiest and most satisfying solution would be to make this configurable.

**Comment by jcollum** [comment]
What's the desired behavior of having podcast audio play at the same time
that you are in a signal phone call?

**Comment by jcollum** [comment]
I'm asking in what scenario is that actually desirable?

**Comment by major-mayer** [comment]
It's not about phone calls, but in one forum post, a user mentioned that he often uses voice messages to quickly send a (bad quality) recording of a song to another person.
But apart from this rather niche use case, I can't think of another one.

**Comment by muessjoeh** [comment]
The desired behaviour with podcasts and phone calls would be the following:
I listen to the podcast. When I get the call, the playing is paused, and the phone call is the only audio that is hearable. In other words, the phone app has the audio focus. When the call has ended, the podcast continues.

**Comment by cody-signal** [comment]
This was added to v5.50

**Comment by muessjoeh** [comment]
I am using 6.5.6. I cannot find the solution. Or is 5.50 a typo?

**Comment by greyson-signal** [comment]
@muessjoeh It was actually version 6.1.3. f1fafa6516

**Comment by greyson-signal** [comment]
@muessjoeh If you're referring to some other bug/behavior that isn't in the initial bug report, please open a new issue. Thanks!
