### ISSUE TITLE
Kicked out of group immediately after receiving an invite link

### ISSUE THREAD

**Issue by PanosChtz** [signalapp/Signal-Android#12343]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Receive group link
- Click on link
- "You have joined the group via group link"
- Immediately receive message "You are no longer in the group"

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

<img width="408" alt="signal" src="https://user-images.githubusercontent.com/5301283/178172177-4a6239cd-3100-40a3-acad-67db22be9440.png">

### Device info

**Device:** Samsung Galaxy S22 Ultra
**Android version:** 12
**Signal version:** 5.42.7

### Link to debug log

https://debuglogs.org/android/5.42.7/f9c6083e06140c98f0f4a85645d3b1f25df15ae490ed6253cd7a7a1c0b8ceeb3

**Comment by cody-signal** [comment]
Hi @PanosChtz , it looks like you restored from a backup. Did you happen to register with a new number? Your logs have a bunch of group membership issues so any more details on the state of the group from backups and the one you are trying to join via link would be helpful.

**Comment by PanosChtz** [comment]
Yes I transferred my account to a new phone recently, and also changed my number. I received a new link from the group administrator but this issue persists.
What additional details do you need exactly to investigate this behavior? (I'd rather not post the group invite link publicly)

**Comment by cody-signal** [comment]
No need to post it.

The extra info you posted is exactly what I needed. When you restored the backup it restored the group state as well, but did so with the previous account information. When you then registered with a different phone number it made a different account but didn't clear any group state. What's happening is the old state is being referenced instead of fetching new state and it's getting confused. Currently there's no clean way to recover from it and we need to add some sort of fix for the scenario you are encountering.

If you want to try and self solve but lose data, and you still have access to the old phone number. I'd recommend restoring the backup again, registering with the same number from the backup, and then using the change number flow in Settings to change to your new number. This will maintain your group memberships/contacts, but will lose any messages received since you made the backup.
