### ISSUE TITLE
Signal allows to take a screenshot of a view-once photo

### ISSUE THREAD

**Issue by solzard** [signalapp/Signal-Android#12350]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal allows to take a screenshot of a view-once photo.

### Steps to reproduce
- Disable `Settings > Privacy > Screen security`
- Receive a view-once photo
- Open the photo
- Try to take a screenshot

**Actual result:** Signal allows to take a screenshot of the view-once photo. I confirmed that not only Android but also iOS app allows to take screenshots. 
**Expected result:** Even if `Screen security` flag is off, in consideration of "view-once" idea, taking screenshots should be refused. 

### Device info

**Device:** OnePlus 7 (GM1900)
**Android version:** 11 (Oxygen OS 11.0.8.1)
**Signal version:** 5.42.8

**Comment by UserX404** [comment]
Afaik this is the intended behavior and is handled as a feature request on the [forum](https://community.signalusers.org/t/feature-to-disable-screenshots/5365).

**Comment by cody-signal** [comment]
This has come up a few times, and pretty much we don't see the value in it. If someone really wants to capture view-once media, there are so many ways to do it even if we did block screenshots. Like someone using a camera to take a picture of the screen. Or using a linked desktop and taking screenshots there that cannot be stopped.

Adding this protection leads to a false sense of security that is more harmful than trying to stop one of many ways of capturing view once media.

**Comment by ZacheryGlass** [comment]
What about notifying a user that a screenshot of their chat was taken, as is done in Snapchat? Yes, it can be circumvented via an external camera or by using the desktop app, but that doesn’t make it useless. The feature can be circumvented in the same way on Snapchat, but it is still a very popular and loved feature, because although people know that it can be circumvented, it is cumbersome to do so, therefore making it much more unlikely for people to bypass the screenshot notification unless they are very motivated to do so. 

In my opinion, having additional information about your conversations can only be beneficial, even if you do not receive that information 100% consistently, it’s still valuable when you do, and I do not believe this would result in a false sense of security, as everybody using this feature on Snapchat is aware of the ways that it can be circumvented. 

Additionally, to draw a parallel, it is quite easy to circumvent the read-receipts feature (read

**Comment by jzbor** [comment]
Hi, I also agree with @ZacheryGlass and @olfek . Although this is no guarantee for the image being captured it is a nice feature to have for a lot of people (who are not "high value targets"). I think it is clear to most users that you can simply use another phone to take a picture of the content, still they like this feature on WhatsApp and other messengers (Snapchat even built a whole platform around it). If you don't feel comfortable with this being default behavior I think it would be sensible as an opt-in with a little warning about possible circumvention.

I know Signal officially regards this feature as resource saving feature, but sadly documentation is a little bit lacking in this respect. Given that this is considered a privacy feature in a lot of other messengers it is very easy for users not to notice is, which gives them an even worse false sense of security. I think at the very least a warning should be added  to the [support page](https://support.signal.org/hc/en-us/articles/360038443071-View-Once-Media) educating users of what the feature can and can't do. Also a warning on first usage would be nice.

**Comment by TheScreechingBagel** [comment]
> What's the point of the screen protection toggle if it only blocks ME from taking a screenshot of MY phone?

https://support.signal.org/hc/en-us/articles/360043469312-Screen-Security

**Comment by realrandolph** [comment]
Chiming in to say I also very much would prefer this be added. Instagram and other commonly used messaging apps provide this feature. In the case of IG, even vanishing messages cannot be screenshotted. At a bare minimum, a screenshot notification should be sent. This has become an industry standard feature that is expected by users. Security doesn't need to be 'win or lose'--it exists in shades of gray. A higher barrier is better than no barrier.

**Comment by olfek** [comment]
Reply to - https://github.com/signalapp/Signal-Android/issues/12350#issuecomment-1191628102

_"Why lock our doors, if someone really wants to enter our home, there are so many ways to do it, even if we did lock our doors"_

(I'm being sarcastic)

**Comment by olfek** [comment]
And the code to do it already exists

https://github.com/signalapp/Signal-Android/blob/4339187ab6ac5ef30d30b1d40ceea3a2fe4b7bdf/app/src/main/java/org/thoughtcrime/securesms/util/TextSecurePreferences.java#L557-L559

**Comment by NicoHood** [comment]
I know there are technical ways to work around this, but the average user does not know this, so I'd prefer to not have the option to screenshot it. It is not 100% secure, but if you can screenshot it, why even bother to have a onetime photo? makes no sense to me

**Comment by TheScreechingBagel** [comment]
I think it's the other way around, if you can't guarantee it won't be screenshot-ed (you can't), why even bother having the annoyance? it isn't "not 100% secure" it's 0% secure; it's important to have clear security expectations for the user

the use of view-once media isn't for when you don't trust your chat partner to not save it, it's for when you both want the media deleted
in fact, by default, if you take a one-time-view photo in the app, it won't save it on your device

i'd view it more like disappearing chats - of course your chat partner can always save or literally just write down your messages, but if you both don't want logs after a certain time, it automates their deletion from your devices

it should not be added, it's anti-user

edit: to hijack olfek's analogy:

Locks are not (directly) security devices. ~All locks are trivial to bypass for someone committed, by lockpicking or brute force. A lock is more of a social signal, and most jurisdictions have a separate criminal charge for bypassing mechanisms like this
you should not rely on a lock to stop someone, neither should you rely on a 'self-deleting' message (duh? lmao)

**Comment by realrandolph** [comment]
Screenshot notifications aren't simply a security feature, they play a dynamic role in social interaction. People today expect them, and receive them on just about every other major platform. The notification isn't about preventing the person from taking the screenshot, it's about notifying the sender that a screenshot has been taken; anyone who has engaged with this feature on other platforms with someone they know and trust will tell you this isn't always a bad thing. Sometimes it tells the other person, "Hey, that was a really good photo, and I saved it." Other times it is ratting you out, which isn't bad either. The fact that view-once photos do NOT send a screenshot notification is at this point really, really bad UX, because users expect it. Every time it comes up with people I message, they are shocked and slightly disgusted that there are no SS notifs for view-once. They abstain from using the feature altogether. 

I've onboarded dozens of people to Signal over the years, and this feature has been a long-running point of contention. Do you want people to use Snapchat instead? Because that is what happens. It's a user retention issue.

I suppose a reasonable alternative, if you really have an obsession with not adding notification, would be to altogether remove view-once media. Without notifications, it is an incomplete feature and does not belong.

**Comment by wertzuz** [comment]
As said multible times its quite easy to circumvent screenshot detection so it won't give you a full picture, what should not be saved should not be sent.

**Comment by Kladki** [comment]
I'm pretty surprised this hasn't been implemented  too. The point of disabling screenshots is to raise the bar needed to save that photo significantly.

Sure, you can just take a photo of the device, but not only would it obviously be a massive downgrade in quality (extremely relevant if the reason you're sending a one-time photo is because, let's say, you don't want the image to be usable to train generative AI), but also many people just don't have another device to be able to take the picture with. And obviously even if they do, it's extremely less practical compared to taking a screenshot, dissuading people from doing it.

The higher barrier also has a bit of a psychological impact, where the person going out of their way to do this evasion will probably feel much more guilty doing so, given how much more effort they're putting into this than just pressing the screenshot button, again dissuading people from even trying this.

**Comment by Kladki** [comment]
Oh yeah, and when it comes to the "false sense of security", you can just have a warning when switching an image to a view-once one, similar to the one you get when downloading media to the device, saying something like "This will only allow recipients to view the image once within Signal, however this does not protect against recipients from taking a picture of Signal from another device, for example".

**Comment by mbrucher** [comment]
Ridiculous that this has not been implemented yet. Signal has so many features, but this is still why people go to Telegram instead of Signal: they care more about people not being able to copy/paste or screenshot chats than encryption. Please reconsider this, as this is a CRITICAL MISSING feature for Signal to properly replace Whatsapp/Telegram and all other. I can't state this string enough: admins in a chat should be able to set "no screenshot/no copy paste" in any proper modern chat app.
