### ISSUE TITLE
Buttons are unlabeled in group video calls

### ISSUE THREAD

**Issue by serrebi** [signalapp/Signal-Android#12361]
X [ ] I have searched open and closed issues for duplicates
X [ ] I am submitting a bug report for existing functionality that does not work as intended
X [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
X [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Buttons on the Video call screen, and the call for the conference itself are not labeled. I am a screen reader user of Talkback on Android and many buttons are not labeled here.
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
1. Go into a group conversation, and press video call button.
2. You will notice most of the buttons are not labeled on this screen, join the call.
3. Many buttons on this screen also are not labeled.
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Buttons just need to be labeled. Thanks for considering this request.
### Device info

**Device:** Manufacturer Model XVI
Samsung Galaxy s22Ultra.
**Android version:** 0.0.0
Android12
**Signal version:** 0.0.0
5.43.7

**Comment by clado** [comment]
Hi @serrebi, thank you for submitting this bug! :) I value the time you took to write it up and I'm sorry that it auto-closed on you.

Would you be able to provide more detail about the issue, such as transcribing what Talkback _does_ announce or sharing a screenshot of the impacted view?

It is true that Signal has not had content descriptions for in-call buttons for a very long time, but I had thought that this was fixed in 5.33 or later.

When I start a group video call on my phone Talkback reads "signal, multipage view, double tap to activate" and I can either double tap or scroll to start accessing the other buttons (flip, camera, mute, and start call).

here's a screenshot of the view I'm talking about:
![a screenshot of the signal group start call screen, with the name of the group censored. There are three grey buttons midway down the screen reading "speaker", "camera", and "mute". At the bottom of the screen is a big green button labelled "start call". The "camera" button has green Talkback focus.](https://user-images.githubusercontent.com/2933589/197406087-c5421e2e-887c-496b-9628-966027268f84.png)

I am noticing that once I turn the camera off and the "flip" button becomes the "speaker" button I can no longer access that button using Talkback, which is a concerning bug. However the buttons are labelled for me, so I'm curious whether you're talking about a different view, or whether the bug affecting the "speaker" button is somehow impacting all of your buttons.

I've also noticed that the "signal, multipage view" seems to capture input and prevents me from dragging my finger to find buttons, I need to flip through everything on the page using Talkback. Is the issue you're describing not that the buttons are unlabelled per se, but that they are only accessible through scroll and not through finger drag?

Thanks again for your work in submitting the bug report! :)
