### ISSUE TITLE
Crash (loop) on startup, only if data/wifi enabled

### ISSUE THREAD

**Issue by merkste** [signalapp/Signal-Android#12378]
Exception on database access, probably related to stories. Does not happen if data/wifi ist turned off. Started after last update.

Sorry for the brevity, sent from mobile.

Log:
https://debuglogs.org/android/5.44.4/4608b1e75cb712d567be602be219839a2678456fe116dc9888d72bf7b8530761

**Comment by greyson-signal** [comment]
Hi, this was fixed in 5.44.5 (prod) /5.45.4 (beta), both of which have been published in the Play Store. Unfortunately they're still under review as of this moment. They will be available for download as Google approves them.

In the meantime, you could install from out website. It's compatible with the version from the Play Store.
https://signal.org/android/apk/

**Comment by merkste** [comment]
All right. Does the app store update the apk installation then?
