### ISSUE TITLE
can’t receive messages from some users, see that others are writing, but the messages are not displayed

### ISSUE THREAD

**Issue by erik55** [signalapp/Signal-Android#12384]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug
I am using the most recent beta version. Since some minutes my daughter can’t receive my messages. She sees that I am writing, but the messages are not displayed. In a group we can still communicate.

Something similar has occured for my daughter in another chat with another person, who is not on beta!! And that other person has an iPhone.

### On her phone
The last message she sees is on her phone in our chat (it is a message she has sent) 1660131581772.

Her debug log: https://debuglogs.org/android/5.44.5/32539f407cd3381ccc05882fe0dd32e52bd8c89926b29d16276906da35b4b9db

Model: Samsung Galaxy S10e
Android: 12

### On my phone
On my phone that specific last message she sees (a message she sent to me) is 1660128451363 (there is an offset in our times but that has never been a problem before).

And this is my debuglog: https://debuglogs.org/android/5.45.6/4b6fb8d7fdacd8d3ef9f0de335e17a14e4d358013337f9874e93131a0d2a427a

Model: Samsung Galaxy S9
Android: 10

### What we tried
She already force stopped Signal and restarted it. Still not working.

**Comment by greyson-signal** [comment]
One question, just as a sanity check: if your daughter scrolls up, does she see the messages? And has she changed her clock recently? I only ask because we sort messages by received time, so if she turned her clock back several hours, new messages could be showing up _above_ already-received messages. Just something to rule out. (Also this is an issue we want to address, just difficult with our current DB schema at the moment).

**Comment by erik55** [comment]
Well, she changed timezone yesterday (moved to another place). But we talked today, and suddenly she stopped receiving my messages. But I will send some test messages for which she could search using the search function. Let’s see if she finds them.

**Comment by erik55** [comment]
Ok, @greyson-signal you seem to have been right. The messages were hidden above. She was on a train/railway when the problem suddenly occurred. Now she receives all my messages, as if nothing had happened. 

Timezone problem?? I am not sure if she used her mobile data on the train or the train's WiFi. 

Sorry for the noise. This can be closed, as you seem to be aware of the timely shifted messages.

**Comment by greyson-signal** [comment]
Thanks for checking! Yeah, it's not a great experience when this happens. Changing timezones by itself shouldn't do it (because we store unix timestamps, which don't change based on timezone), but it's possible she had a weird clock sync when moving around or something, not sure. But yeah, this is a bug we're aware of and have long-term plans to address, but nothing in the short-term :/
