### ISSUE TITLE
Unable to link device by QR code

### ISSUE THREAD

**Issue by desultory-zz** [signalapp/Signal-Android#12486]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to link device to windows 11 signal

### Steps to reproduce
- Open QR linking portion of signal app on my phone
- Open signal on my laptop
- Attempt to scan with no success

**Actual result:** 
Nothing happens
**Expected result:**
Devices link

### Device info

**Device:** Samsung Galaxy A23
**Android version:** 12
**Signal version:** 5.51.2, 5.51.5

### Link to debug log

https://debuglogs.org/android/5.51.5/8f7e724ddba0eba09bef0ca2065e0de6d37a3d32231476e61aaee6ca5ef5f691

I've also tried to downgrade to desktop version 5.27.1, have tried light and dark themes, have tried zooming in and out a lot, holding the camera close and far, can't figure out a way to get the devices to link.

**Comment by cody-signal** [comment]
Looks like the device sees the bar code but can't decode it. Would you be willing to run a same app if I sent one to you or if you're technical savvy, you can run it from our code base.

**Comment by desultory** [comment]
willing to run what?I'd be willing to test some apks and have a working knowledge of adb if needed  ---- On Mon, 03 Oct 2022 08:32:15 -0500  ***@***.***  wrote ----
Looks like the device sees the bar code but can't decode it. Would you be willing to run a same app if I sent one to you or if you're technical savvy, you can run it from our code base.

**Comment by cody-signal** [comment]
Whoops, a sample app.

Can you email me a cody at signal dot org and I can see you the apk. Would just need you to run it and post a screen shot. Thanks!

**Comment by JBBgameich** [comment]
I have a similar issue, were signal apparently tries to takes photos instead of using the viewfinder mode of the camera. This makes the QR-Code scanner extremely slow. Although it sometimes looks like it gets quite good results this way, it can't decode them.

It still used to work earlier this year, I unfortunately don't know which exact version I used then.

Other barcode scanners, for example https://github.com/wewewe718/QrAndBarcodeScanner or https://gitlab.com/Atharok/BarcodeScanner seem to use the viewfinder mode and work very quickly and reliable.

It would help if signal would not block external QR-Code scanners, at least as long as the internal one apparently works quite differently from what most external apps seem to do.

Device: Samsung Galaxy S5 Mini
Android Version: 9
Signal version 5.53.8

**Comment by desultory-zz** [comment]
> I have a similar issue, were signal apparently tries to takes photos instead of using the viewfinder mode of the camera. This makes the QR-Code scanner extremely slow. Although it sometimes looks like it gets quite good results this way, it can't decode them.
> 
> It still used to work earlier this year, I unfortunately don't know which exact version I used then.
> 
> Other barcode scanners, for example https://github.com/wewewe718/QrAndBarcodeScanner or https://gitlab.com/Atharok/BarcodeScanner seem to use the viewfinder mode and work very quickly and reliable.
> 
> It would help if signal would not block external QR-Code scanners, at least as long as the internal one apparently works quite differently from what most external apps seem to do.
> 
> Device: Samsung Galaxy S5 Mini Android Version: 9 Signal version 5.53.8

Seems separate from my issue, you should probably open a new ticket

**Comment by cody-signal** [comment]
@JBBgameich a debuglog would be helpful
