### ISSUE TITLE
calle consistently cannot hear me, the other way around it works

### ISSUE THREAD

**Issue by attila-lendvai** [signalapp/Signal-Android#12504]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
callees cannot hear me when i call them. tested with about 4-6 callees, same behavior, consistently.

when they call me back, everything works.

this happened sporadically before, but it became consistent in the past few weeks.

### Steps to reproduce
- voice call anyone on signal from my phone
- they pick it up

**Actual result:** they cannot hear me, i can hear them.
**Expected result:** we both hear each other.

### Device info
**Device:** Xiaomi POCO X3 Pro
**Android version:** 11
**LineageOS version:** lineage_vayu 20220606
**Signal version:** 5.51.7

### Link to debug log
caller side:

https://debuglogs.org/android/5.51.7/249a758b1f563b8bb50c143352381de7b05334524419ce5e236261a8cab7e06e

callee side:

https://debuglogs.org/android/5.51.7/2db639508c2a797a006b7ee7b166c0084821471ea8d9e4c46d6636d38e9eb9a7

**Comment by rashad-signal** [comment]
I took a look at the logs, and it looks like when the app is trying to get audio from your phone's earpiece in the problematic calls, the OS is just giving it silence. I'm not sure why that's happening, but I had some questions that could hopefully help narrow this down:

1. Since this bug seemed to start happening without an app update in-between, I'm wondering if it's working again for you now (or possibly back to sporadically working)?
1. If it still isn't working, can you try making a call on speakerphone (or headphones with a mic) to see if that makes a difference? All of the calls that didn't work were using the earpiece (although there are some calls in the logs which work with the earpiece).
1. There are some suggestions for microphone problems for your phone [here](https://xiaomi.eu/community/threads/poco-x3-pro-microphone-problem.66039/), but it's not clear if they will help since you're on a different ROM.
1. I tried looking for the 20220606 build of Lineage for POCO X3 Pro and wasn't able to find it online. Is it a custom / unofficial build? If not, it might just be too old to still be hosted online.

**Comment by attila-lendvai** [comment]
thank you @rashad-signal for looking into it!

it started to work again, probably after updating the Signal app (i update my apps manually every couple of weeks).

if it happens again, i'll try 2).

as for 4), this LOS version is discontinued, but i didn't have the time to upgrade to the next android version, which involves reinstalling stuff (read: wasting my life).
