### ISSUE TITLE
Removal of SMS support is a terrible idea

### ISSUE THREAD

**Issue by numericOverflow** [signalapp/Signal-Android#12517]
### Bug description
 Removing SMS support on Android will *DESTROY* your user community. Technically savvy people might remain, but the casual user demands a single app that does both secure communication and if unavailable, insecure SMS. They will not tolerate two apps and will leave the signal platform, thereby reducing your adoption exactly opposite of the logic outlined in the blog post.

https://signal.org/blog/sms-removal-android/

You can see that there is passionate, highly negative response from one major community post on [Hacker News](https://news.ycombinator.com/item?id=33179047)

### PLEASE DO NOT REMOVE SMS!!

**Comment by collinarnett** [comment]
I have successfully convinced most of my family to use signal based on the fact that they can just use one app for all their messaging. I set signal up as the default messaging app and they don't have to have the mental overhead of switching apps when they want to talk to me vs other people who don't have signal.

Now I have to explain to them that they have to use a separate app when they talk to me AND to explicitly not use their SMS app to message me in order to maintain encrypted communications. They'll probably never open signal again once this change gets implemented and I have to deal with all the incredibly annoying issues associated with SMS. At that point why am I even using signal? For the few people who have the discipline to think about who and who doesn't have signal?

This change is incredibly frustrating and I hope that it doesn't get implemented.

**Comment by AngellusMortis** [comment]
This change is definitely a bad idea. Maybe in the EU a lot of people are okay with Signal as an alternative to SMS, but in the US the **vast** majority of people are using iMessage (if they have an iPhone) or SMS/RCS (if they have an Android phone). No one (myself included) wants _yet another messaging app_. How am I going to convince my bank to stop using SMS MFA codes and switch to Signal when they cannot even be bothered to do TOTP? I already have Discord and Slack and _thankfully_ do not have Snapchat, Facebook Messenager, Whatsapp, Skype, Teams, Telegram or any of the other ones. 

The two features that _made_ Signal stand out where end to end encryption and a drop in replacement messaging app. The _only_ way I got the friends I did to switch over to Signal was by saying it is like your messaging app, but better.

**Comment by DejfCold** [comment]
> Technically savvy people might remain

Maybe, maybe not. We're people too and we also don't want unnecessarily complicated tools. I'm not and the vast majority are not dissidents, whistleblowers, journalists in hostile countries, hunted or whatever. We don't really need the privacy and security. It's just a nice thing to have. We share our lives on social media anyway. But if we, the majority who don't really need the features, stop using the platform, it becomes useless for the people who would actually do need it.

**Comment by poolpOrg** [comment]
Very bad idea indeed, most of my contacts use signal because it also is their SMS app and they can benefit from encrypted communications "for free" in the same app, not the other way around. If they can no longer use signal as their SMS app, then it means they have to reinstall an SMS app and they'll no longer use signal, which also means that the messages they used to sent to me, or one to another, goes back from encrypted to SMS. How's that improving anything ?

It's already hard to make people move away from whatsapp, messenger & stuff but there's at least this support... if removing it drives people away, what use will be signal when there's no one to chat with...

If the concern is really confusion about secure vs unsecure messages, this can be an UX change, it could litterally be a red banner with a bold font stating "insecure communications", it would still be better than your removal of what makes signal usable to non techies...

**Comment by 11-int** [comment]
Chiming in to agree, this feature change is going to kill my usage of signal, and will make convincing others to switch to it much, much more difficult

**Comment by Blu3wolf** [comment]
> we’ve heard repeatedly from people who’ve been hit with high messaging fees after assuming that the SMS messages they were sending were Signal messages, only to find out that they were using SMS

So you are just removing SMS outright? Well, here is a user for whom SMS is free, and data is expensive. Sending Signal messages costs me money, SMS does not. 

This change makes Signal pointless for my use case. You may be improving the app for some users - that's unclear to me. You'll be essentially destroying it for many.

**Comment by HonestCrypto** [comment]
Adding to the pile of users who think this is a disastrous move. I've used Signal since it was TextSecure and will be forced elsewhere if this change goes through. I've only been able to get people to use Signal due to the ability for it to serve as the default SMS app. It has been effortless for them due to automatically using secure messaging for anyone else who has Signal installed. I hope the devs consider the near unanimous disappointment on Reddit (such as /r/privacy and /r/android).

**Comment by CamdenClark** [comment]
I'm really frustrated with this decision. I've been contributing to the signal foundation for a year now, mostly because this feature exists.

Please don't do this!

**Comment by gilou** [comment]
Well, even for tech savvy people, will that be very painful. 80% of my daily contacts don't use Signal, some use Signal from time to time, but sometimes they switch back to text messages. Having all the info (text/mms) in Signal is almost a requirement for me… I do understand the concern, and I do feel like most users that already switch between many text apps won't notice, but for those that grew accustomed to having text and Signal in the same app, that is going to be a rather not welcome shock.

**Comment by leo-unglaub** [comment]
Please rethink this horrible decision. The SMS code is not that large and easily maintained. If there is space for feature bloat like stories, crypto-scam payment, ... Then you can keep functionally that people actually use!

I am going to stop my donations to Signal if this gets done.

**Comment by numericOverflow** [comment]
> > Technically savvy people might remain
> 
> Maybe, maybe not. We're people too and we also don't want unnecessarily complicated tools.
> 
True, I just meant Signal will lose all but the most dedicated users with an extremely short-sighted decision to remove the SMS feature.

**Comment by Para-lyzed** [comment]
There is absolutely nothing good about this change. I only have 1 contact that uses Signal, and we haven't talked in months. Both of us will be uninstalling if SMS is actually removed, and I've seen this same situation echoed throughout Reddit. I use Session with multiple contacts, and it's better to switch the 1 contact I have on Signal over to Session than it is to have an app installed to talk to a single person I only message once every few months anyway. In reality, I likely won't be able to convince them to switch anyway, so we'd go back to SMS.

Can you not imagine other solutions for the single actual problem that this blog post provides? Perhaps actually having a meaningful indicator that's *hard to miss* would be beneficial to people who mistakingly send SMS messages? Having a grayed out font in the text box is basically useless. Here's an idea: ***put a banner at the top of the screen that states you're using SMS instead of a Signal message***. Problem solved. As it stands, this situation essentially boils down to "nothing has been done to fix this problem an extreme minority of our userbase faces. Let's just axe a feature almost everybody uses instead of putting effort into finding a reasonable solution".

What is this trend of removing features from Signal? You just removed the ability to import SMS messages, why are features being ***actively removed***? The other issues quoted in that blog post are empty. In fact, I'll go through them in order:

1. Supporting SMS doesn't devalue the Signal protocol or the Signal app. With an improvement to the UI to actually make the difference clear, there would be no problem. The reality of the situation is that almost everyone has to use SMS at some point. My bank requires SMS for 2FA, and there is not an option to switch to another method or to turn it off. Medical providers require phone numbers and frequently send me SMS messages. The majority of people wouldn't install Signal no matter how much I asked them to, so there's a large chunk of people I regularly talk to that I can only communicate with through SMS. These are not issues specific to me, and have been echoed throughout the community. We will need an app for SMS, so why not have a combined solution from an open source app that *already features SMS integration*? It would be one thing is the rationale were "we don't want to implement SMS because it would take resources away from more important features, and since it's insecure, there's no reason for us to prioritize it". But SMS has already been implemented, so that claim holds no validity.
2. Mistakingly sending SMS is an issue that can be easily remedied by a UI fix. I've already covered this, I don't need to go into more detail.
3. The UX is *improved* by integrating with SMS, it does not detract from it. If a user willingly sets Signal as their default SMS app, they understand that they will be sending SMS messages using it. Couple that with a reasonable indication that a user is in an SMS conversation and not a Signal conversation, and there is no confusion whatsoever. The only difference that removing SMS would make would be that a user needs to install another app just to handle SMS, and it's frustrating to have to constantly switch messaging apps to talk to different people. And again, asking people to switch to Signal instead of SMS doesn't work. I - *as well as many others* - have already tried migrating everyone I talk to over to secure messaging apps.

Nothing good would come of this change, and Signal would only lose users for it.

**Comment by numericOverflow** [comment]
^^^^ Exactly this. @Para-lyzed - very well said!

**Comment by 4oo4** [comment]
The reason I started using Signal (back when it was still TextSecure) was because even though I wasn't able to use the true end-to-end encrypted messages since no one else I knew at the time used it, I at least knew that it kept my SMS messages encrypted at rest on my phone.

If I'm understanding the blog post correctly, the main reason for this seems to be so users don't have false expectations of privacy when they are using SMS/MMS messages in the Signal app? It already does a pretty good job at doing this, but if it's not sufficient that's a pretty simple UX problem to solve to make them more distinct.

That doesn't seem to justify such a radical change, so it's likely that there are other roadmap considerations that Signal isn't being transparent about. Perhaps this to make the app have feature parity with iOS and Desktop, by making it worse on purpose? Perhaps this is part of decoupling phone numbers from Signal accounts?

No matter what the real reason is, this is extremely detrimental to security and privacy by making SMS messages more vulnerable at rest. Yes, phones are fully encrypted nowadays, and SMS messages aren't encrypted in transit, but what about someone having their phone sized at a border or authorities searching the phone of a journalist or activist? 

In that case having SMS messages encrypted at rest like Signal currently allows could literally save lives. Luckily my use case isn't that extreme but I still use Signal for SMS, knowing that it keeps them safe from being readable from other apps on my phone, and requires an extra mechanism to decrypt them.

Anyone can test this out, just switch your default SMS to a different app, and if you log into any app on your phone that uses SMS for verification, guess what? The app can probably read that verification from your SMS messages without any interation. This is precisely why it's such an important feature.

Is Signal also trying to hurt adoption? The "Invite to Signal" action inside an SMS conversation probably helped onboard a lot of users to the platform, and trying to convince non-technical people to start using a separate messaging app that only lets them send special Signal messages versus something that can handle ubiquitous SMS and MMS is going to be a much harder sell.

So whatever the real reason is, be honest and don't pretend this is a privacy or security postive move. No one has false expectations about SMS encryption in transit, and if they do they are ignoring really clear UX cues the app already provides.

I'd gladly sign up for a subscription and pay for Signal if it's a question of developer resources and I'm sure other people would too. Assuming at least, that Signal would stop taking its community for granted and not try to pull such moves in the future.

**TL;DR:** This is so hostile to user-friendliness security and privacy and breaks a lot of the trust I've had using TextSecure/Signal for more than 10 years, please reconsider.

**Comment by TurboGraphxBeige** [comment]
Please, do not remove SMS support! This is the most important feature that Signal offers to me! One single messaging app on which I can reach all my contacts, whether they use Signal or not. Plus, it has the best UI. I have on-boarded people on Signal because of the unified messaging app. Without SMS support, this app is worthless to me.

Please, reconsider this decision. Make some changes in the UX or something. 

This is a huge step back for privacy.

**Comment by giltwist** [comment]
I'll keep Signal installed because the E2EE everything is important to me, but you've just lost a monthly donation from me over no longer being an all-in-one, set-it-and-forget-it solution.  Only a handful of my contacts use signal, and now I need something else for everyone else.

**Comment by cizzop** [comment]
Sorry but this decision is enough for me to cancel my monthly subscription. I've had Signal as my SMS default for years and 80%+ of my messages are through Signal. I have no desire to now use two separate messaging apps. Being able to backup and restore messages using one app has been great and now I have to manage 2.

**Comment by Blu3wolf** [comment]
How realistic is maintaining a community fork which supports SMS? I would much rather keep using Signal, but this feature is non-negotiable for me at least.

**Comment by 4oo4** [comment]
@Blu3wolf It's similar to the issue of someone wanting to run their own federated Signal servers but hopefully simpler. In this case, you technically could point the forked Signal app to Signal's existing servers for Signal messages, since SMS messages shouldn't need to touch Signal's servers at all (someone that knows more can correct me of I'm wrong)

So then the question is will Signal allow you to use their servers with a 3rd party app, assuming that someone removed all the Signal branding from it. Hopefully that's a yes but if not then someone would also have to run their own Signal Server infrastructure.

However, the real reason for this is likely not the UX one stated but likely not using phone numbers for Signal accounts anymore or something similar. In that case, the codebase would start to diverge a lot and it would take more more to maintain the feature over time.

Saying all this as someone that knows very little about Android development or Signal's internals, someone that knows more can correct me if I'm wrong.

**Comment by willbush** [comment]
A couple of months ago I called a masonry company to quote some brick repair work on my house. The owner came by and we talked for a while about various things. He mentioned he was surprised I called him on Signal. I was surprised too! I didn't even know he used signal and didn't notice when calling him. All my followup communication  with him were text via Signal and E2EE.

My decision to call vs text was whimsical and easily could have gone the other way. Since I use Signal as a default SMS app, this random small privacy win would have still happened. Without SMS support, I would never attempt to use Signal first for contacting a stranger.

Just wanted to share that anecdote since I haven't seen anyone make that point.

**Comment by TexZeTech** [comment]
The very moment I can not use the sms in signal is the day I pull my monthly donation.

**Comment by ffmurray** [comment]
Removing SMS from signal might be the single dumbest idea if signal wants to continue.  Without SMS people will not convert.  I have convinced my family, wife and many friends to use signal because they can use it for SMS as well as encrypted messaging without having to deal with the hassle of switching apps.  The fact is that is sucks that a very very small percentage of users might have a higher phone bill than expected because they cant figure out the UI, but to gut an entire app and destroy the community over this is just stupid.

**Comment by ThomasAkerlund** [comment]
I agree with all others here that this is a monumentally bad decision. I have been using the SMS feature of Signal for a long time and have convinced a lot of friends on Android to use Signal as their default SMS app precisely because it automatically switches between SMS and private messaging. What I have noticed is that almost none of my iOS friends use it, not because they don't care about privacy, but because it's cumbersome to have to switch between it and the default app.

Just look at your downloads between iOS and Android. If iOS in fact has as many downloads as Android maybe everyone commenting is in the wrong. But I suspect that is nowhere near true. Just looking at the amount of ratings, 15k in iOS compared to 2.14m in Android says quite a lot.

**Comment by Kyle-B** [comment]
Adding my voice onto the pile that the day Signal removes SMS support is the day I stop using it. I've been using Signal since it was TextSecure, and being able to get E2E encryption when one of my contacts also has Signal is great! But the **vast** majority of my contacts don't use Signal, and never will. I'm not going to use two messaging apps, I'll just stop using Signal. And there's definitely no way I'd be able to convince anyone to switch to it any more.

It's already fairly clear when you're messaging someone via SMS vs Signal, but this could be made more obvious through UX if that's actually a problem. SMS charges seem like... a non-factor for the majority of users? I feel for folks with pay-per-sms still, but how many people is that really affecting?

**Comment by DejfCold** [comment]
@TexZeTech 
> The very moment I can not use the sms in signal is the day I pull my monthly donation.

You should do it before that. Then would be too late to do anything about it. If you (and enough of other people) do it now, it sends the message clearly and they can still reverse the decision.

**Comment by ikanakova** [comment]
The Signal Foundation doesn't care about their user opinion any more than Alphabet and Meta do.  How am I supposed to trust Signal now that they aren't selling our data like those two corporations?

**Comment by TexZeTech** [comment]
The very moment I can not use the sms in signal is the day I pull my monthly donation.

> @TexZeTech
> 
> > The very moment I can not use the sms in signal is the day I pull my monthly donation.
> 
> You should do it before that. Then would be too late to do anything about it. If you (and enough of other people) do it now, it sends the message clearly and they can still reverse the decision.

Valid point. Thanks.

**Comment by KerbalNo15** [comment]
From a user of Google-free Android, Signal is the best open source SMS app. Period. It's my default SMS app and has no equal or replacement.

**Comment by willbush** [comment]
This justification shared on community forums goes into more reasons why:
 https://community.signalusers.org/t/signal-blog-removing-sms-support-from-signal-android-soon/47954/56

Found the link here: https://news.ycombinator.com/item?id=33179047

**Comment by JakeSmithQUT** [comment]
Ive stopped my reoccurring donations since this announcement and I urge others to do the same. This change is a terrible idea, this feature is the main reason why I could get so many people to sign up to Signal.

**Comment by defkev** [comment]
> Get the impression they should fight for 3rd party RCS api support

Google's RCS implementation is proprietary, but that's a Google problem, not an SMS problem, and certainly not a problem Signal should even only try to solve, especially not by removing SMS from Signal...

**Comment by ginger51011** [comment]
I want to voice my concern here as well. This is a terrible idea, and removes one of the main selling points for Signal for me: _Not just another messaging app_.

This could all be solved with more warnings (that you could turn off), not removing it.

**Comment by mjsumpter** [comment]
Please find another solution besides removing SMS support. I am a dedicated Signal user who has talked most in my life into using the app, but will most likely look for other options if this happens.

Its essentially _the_ selling point of the app besides e2e encryption. And lots of messaging apps use e2e encryption, I don't know of any that do both.

**Comment by willbush** [comment]
Guess I'm just more conflicted than before after reading the forum justification. I would think vastly more people would benefit from increased privacy on an open source chat client (Signal) if they embraced SMS and RCS. However, if Google makes it impossible for 3rd party clients to support RCS and RCS slowly makes SMS obsolete, then not polishing the brass on the Titanic makes sense.

I guess the most level headed thing I can request from Signal is a more technical blog post going into the devil in the details.

**Comment by Goldmaster** [comment]
This is the worst decision made for several reasons.

1. 1st of its 1 less app, no need to switch between sms and signal. Many people have multiple messaging apps and to download another is more difficult. Being able to say it replaces your sms app so you can get rid means its 1 less app needed.

2. Will cause confusion for people especially older people where many of us are IT tech support. What will likely happen is that they will use the default sms app to text a signal user instead of signal.

3. The ability to continue a conversation when a user joins signal. If a sms user joins signal, you have previous messaging history and the conversation continues on signal. With sms being removed, and no import feature, conversations will start from scratch so again many people wont see the point in using signal.

4. What's happened to innovate don't imitate? It seams that signal is basically trying copy WhatsApp rather than innovate and add features that make want to switch other privacy and security. The sad fact is that people are gonna stick to WhatsApp even though it is bad due to everyone else. This was Signals killer feature. Signal should focus on embrace, extend, upgrade.

Please revert this worst decision made

**Comment by QuantumRipple** [comment]
I am the kind of user that runs GrapheneOS with no gapps. I do not know a single person in real life that cares more about privacy and security than myself. Even I will drop Signal if SMS support is removed. It is going to be worse among the less savvy. I do not look forward to helping tech illiterate family members change SMS apps when their messages stop working because of the app I convinced them to install (or let _me_ install on their devices).

**Comment by yoshimo** [comment]
Instead of removing it, make sure it works again for those that have mentioned issues.
As people above said: Having different methods of communication in one place makes it easier to migrate people that rely on the it crowd to manage their devices.

**Comment by sparevermicelli** [comment]
Please listen to the community.

**Comment by ShirinGaming** [comment]
This is a horrendous idea, the message is that its for more privacy for signal users, but this is the exect opposite. Those signal users who value not having to use multiple apps just to be able to talk to a really small handful of contacts will lose the benefit of signals privacy features for what? Was this preventing usernames? Really? The line about people getting confused for having to pay for sms is just such malarkey.

Never imagined signal was only interested in providing privacy to the smallest group of people imagineable. After this what communications will be left on signal? Few politicians, a couple of activists, a bunch of lowlifes, and a handful of tech nerds?

This has to be either a publicity stunt for when they reverse it, or a clear attempt to stifle the very clear, albeit slow growth of secure private messaging in the world.

Before this by recommending signal to the tech illiterate person as a replacement for their default sms app was an opportunity to get their messaging private bit by bit. Something that both you and they have benefited from even if their were somewhat unaware of those benefits. Eventually it could have ushered in a world where privacy was the norm. Now these people would have to value the privacy aspect so much that they would have to take on another app, which by itself seems trivial, but the thing is you have to be aware of the benefits to see that trade off worth it. And most regular people are not. Which means that not only they wont benefit from the added security, but their contacts who will stay with signal wont either. Not when they are talking to the people this pushes away from the app. 

Also people are creatures of habit. Breaking that up by this decision is monumentally stupid, gives the impression to people that a privacy focused product is inherently untrustworthy, and will stop serving you over the long run.

**Comment by Zylquinal** [comment]
This would be a horrible moves made by Signal, the idea that people could use SMS is really good. For me it's a life saver, since i could use one app for both SMS and Signal-based message. And i don't like the reasoning behind it, especially when i use signal to both receive and send SMS since i trust it more instead of the one that's built-in in my android phone to save the data.

**Comment by jeloooooo** [comment]
Bad move. Don't do this to us, don't drop the SMS support!

**Comment by kevindwitama** [comment]
As with most others on this thread, I agree that SMS support should not be removed.

**Comment by he247** [comment]
I feel the same as many others, I changed because Signal supported both (I also liked the encrypted SMS option in the beginning). Especially if you are in regions where a stable network connection is not guaranteed, an SMS can safe lives. I often fall-back to SMS if the Signal message was not sent or received, in order to be sure that my contact receives the message. I don't always need encryption, but I always need a reliable way to communicate.

As @defkev suggested: 
> Either keep the legacy SMS code and bury the option to enable it somewhere deep in the experimental settings well hidden from people who cannot tell Grey from Blue or better educate your growing user base

**Comment by FadeDave77** [comment]
Please, do not remove the sms support!
ALL of the users of signal that I know, use the sms option, and I know that they would just leave the app if there weren't any sms support. Also, setting signal as a default sms app improves message delivery, because the default sms app has to always run on android. The majority of the userbase loves the feature, please DO NOT REMOVE IT!

**Comment by Tse7en** [comment]
I literally joined GitHub just to tell the signal Devs what a ridiculously stupid idea this is.

It's not just the US, but also Australia where people still use SMS a lot. Other less secure apps integrate SMS with their messaging system. Signal will now lose to these apps along with whatever the default SMS client is everytime.

If the goal of signal is to increase privacy, this will have the opposite effect. Users will leave the app and move to less secure apps for convenience. Even long term users like me.

This whole idea is incredibly short sighted and stupid.

When will companies learn that removing features of never a good idea.

**Comment by X-Ryl669** [comment]
If you wanted to shoot yourselves in your feet, you couldn't do better. 
There isn't a single valid reason to drop SMS support. 

1. It costs time and money to support that feature, but that's money you don't spend on advertisement or marketing, since without SMS support, no one will install Signal, you'll have to advertise it (and good luck for collecting donation)
2. People use SMS while they could use signal. It's people fault, not yours. At best, you can promote a UI change so that fault is known before being made.
3. RCS is now a monopolistic move from Google. Blame Google, not your users which are also your salesperson. Use the money you're collecting to lobby the government or bootstrap a trial for antitrust laws. For most people, RCS is unknown. It's barely known what a SMS is, they don't even know MMS are like emails and requires a data connection, so hiding all of this is a marketing advantage. In EU, there's a law being prepared to force messaging app to intercommunicate. Once this law is passed, you'll be able to attack Google preventing the usage of RCS on android and collect funds to develop the feature.
4. It's already incredibly difficult to have people switch from Whatsapp, if you remove features found in Whatsapp, you're dead, no matter how friendly you advertize the features your have.
5. People don't care about technology. They care about their power (to communicate) and their laziness. Using 2 apps instead of one will result in using 1 app and dropping the other one. Guess what's more important to them ?

**Comment by OcileCollection** [comment]
"From the beginning, the team behind Signal put people and their needs at the core of their commitments. They understood that iron-clad security is fairly pointless if people can’t use, access, or feel comfortable with it. In other words, if my friends won’t use a messaging app, it doesn’t work as a messaging app. It works as a thought experiment, at best."

- Signal CEO

So Signal is now a thought experiment for the US?

**Comment by Gibbo3771** [comment]
I've been using Signal since the beginning and I just don't get this decision. This will alienate a huge portion of casual users. 

Signal doesn't have the popularity of WhatsApp where 95% of contacts will have it, so people don't mind switching to SMS to message their Gran once a week.

This will kill the app.

**Comment by feltel** [comment]
I dont want to use another app just for SMS. It is (was?) a convinient way to have both secure messaging and for backwards compatibility SMS in one app. This decision will cost you a good portion of the user base.

**Comment by joshmd** [comment]
Echoing everyone's comments here.

Friends and family have been convinced to switch to signal because it REPLACES the SMS app on Android, so it is an easy swap and doesn't impact things. Now you are requiring your users to get another SMS app and therefore people will only open Signal when they remember, not by default.

This is a poor decision and will likely kill your userbase.

**Comment by afdia** [comment]
SMS support is the best way to convince people who argue that they don't need another messaging app. A task which is already difficult enough would become nearly impossible if this feature gets removed.

**Comment by bokaklav** [comment]
Bad idea... SMS was the only way I convinced my friend group to use the app.  I think we'll see a mass exodus if they go through with this.  The signal subreddit is blowing up with this.

**Comment by klbarie** [comment]
Not much to say that hasn't already been said. This is a terrible move for all reasons stated above. So many people only have this app because their friends or family convinced them to download it. This is not how you grow a user base. So many casual users WILL stop using this app. Mobile communication will get less secure as users drop this and default back to other sms apps for communication with the friends and families that sold this app to them on your behalf. 

Don't do it

**Comment by pboin** [comment]
Who removes functionality?  Does Signal think that they'll move the Android market by pulling out?  Ain't gonna happen... better to stay where you are and encrypt some messages than to pull away and stop serving folks that are just figuring out privacy.  

Bottom line, we need more crypto -- and this doesn't further that goal.

**Comment by Lucifer1903** [comment]
The only reason I use Signal is because it has SMS, the private messaging is a bonus for talking to people who also have signal and haven't bothered to move over to Session yet. 

If SMS is removed then I will find another SMS app and anyone who previously messaged me via Signal will have to Message me via Session.

**Comment by RichardPurvis** [comment]
I agree with the community. This is a bad choice. The reason most of us started using Signal was because it was everything in one place. Removing this feature is like removing search from Google.

Your reasoning for 'streamlining' makes sense, but I disagree with your design/UI/UX reasoning. Have you considered the UX of a user having to switch between two apps for messaging is far worse than some notification/reminders/icons for SMS contacts?

I will reconsider using Signal if this change goes through. Please continue being the good guys.

**Comment by martinrotter** [comment]
This is crazy. :D

**Comment by Stefan-Mada** [comment]
Please do not remove SMS support, this would actually hurt the app so much. It's a way to ease people into the ecosystrm, and without it it will be so so so much harder, if not impossible, to convince a normal person to switch.

**Comment by Blackmine57666** [comment]
That's a terrible idea.

**Comment by rjjohnson** [comment]
You're losing five monthly subscriptions from my family with this move. Please reconsider.

**Comment by aranaktu** [comment]
This was the feature with the biggest appeal to me. Installing Signal didn't mean to have an extra messaging app, but rather to replace one.  Now that this will/might be gone, I'm having another look at my contacts and realizing that Signal has the least amount of users among them (and they're using others as well), I might just get rid of it altogether.
If you're worried about SMS/Data confusion, just add a big banner/custom background/extra confirmation query before sending. Removing the main feature that would convince people to switch is just a really bad idea all around.

**Comment by aldentepasta** [comment]
My network of over 20 people have agreed to leave Signal if this goes through.

**Comment by synthgab** [comment]
Including SMS is the reason why Family is using Signal: « From now on, just use Signal instead of Messages for texting, I said a few years back. » If you move down that road, everyone will just go back to good old SMS, and they'll threw back at me that thanks to my nerdy privacy app, they have to change their habits and reconfigure everything (notifications, colors, backgrounds, etc) once again - and what can I say ? They'll be right !!

**Comment by bam2000** [comment]
Please keep this feature and don’t remove it, using it regularly

**Comment by LKJones83** [comment]
I use Signal because it replaces the terrible stock texting app and improves security with contacts who also use Signal.

When Signal stops sending SMS, I'm going to stop using Signal.

**Comment by jarednthomas** [comment]
I've used Signal for what feels like a decade, going all the way back to when you had to root and flash Cyanogenmod. I've converted countless friends and family; Really disappointed. Not just in dropping SMS, but the whole direction of the app over the past year or two. Maybe this will be the nail in the coffin. RIP to one of the greats.

**Comment by teol** [comment]
Please do not remove SMS support

**Comment by 1MachineElf** [comment]
Please listen to the community. This is a poor decision. Do not go down this road.

Similar to what others have said, I've convinced friends and family to use Signal. It's just a small number of signal users in my social circle, in the majority are using signal to communicate via SMS with people who aren't using signal. Signal's security is an extra benefit when we happen to be communicating with each other.

Now I have to explain to them that they need to stop using Signal for all their contacts except for me. I need to explain that signal decided to do this because they didn't listen to their Android users. This choice from signal devs we'll put a bad taste in my mouth. It will also damage my credibility. Why would they put any stock into my recommendations on phone security when even the best in class secure messaging app turns its back on them?

By turning back on your Android users, you aren't just hurting Signal, you are also hurting people's perception of "secure" apps.

Also, It's bizzare to me that proponents of the decision claim that SMS will be going away. There is no reason to think that Apple's iMessage will stop using SMS for Android phones. Do you really imagine the EU will force Apple to use non-existent RCS? Signal devs are jumping the gun.

**Comment by Blu3wolf** [comment]
> This justification shared on community forums goes into more reasons why: https://community.signalusers.org/t/signal-blog-removing-sms-support-from-signal-android-soon/47954/56
> 
> Found the link here: https://news.ycombinator.com/item?id=33179047

Sounds like a bug in the other messenger, if it's sending incompatible messages. It sounds like Signal only cares about the US market, if they are dead set on RCS compatibility. 

I guess I need to start advocating to my friends for yet another app - not Signal, certainly - and to install an SMS app for the numerous folks who won't. Unless there's an app that supports E2EE as well as SMS, it seems a two app solution is all I can arrange.

**Comment by nn1629** [comment]
> ### Bug description
> Removing SMS support on Android will _DESTROY_ your user community. Technically savvy people might remain, but the casual user demands a single app that does both secure communication and if unavailable, insecure SMS. They will not tolerate two apps and will leave the signal platform, thereby reducing your adoption exactly opposite of the logic outlined in the blog post.
> 
> https://signal.org/blog/sms-removal-android/
> 
> You can see that there is passionate, highly negative response from one major community post on [Hacker News](https://news.ycombinator.com/item?id=33179047)
> 
> ### PLEASE DO NOT REMOVE SMS!!

I agree, removing sms support is a really bad move

**Comment by heliophane** [comment]
Chiming in to say that the only way I was able to get my friends to move away from snapchat and SMS was to convince them they only needed one app to use SMS and signal. Removing this is going to make it impossible to continue using signal and I will be unable to use any private messenger in the future, as I already pestered them into moving 3 years ago.

**Comment by Statonwest** [comment]
Try to explain that instead of 1 messaging app with everyone. Now you need two apps and bounce back and forth trying to remember who is on what platform isn't viable. The non-security focused, and maybe even me. Will leave it to the platform so they can message all of their contacts rather than just some.
Is confusion such a big problem? If it is locked, it's safe. Non-locked, not safe.
You can not expect everyone to have all of their contacts on Signal. You also can not expect people to use multiple platforms. The easy option is the option most will pick. It is hard enough to get family members on onboard. This will kill Signal overnight. There is a reason the general public isn't onboarding to telegram.

**Comment by IllustratedMan-code** [comment]
I think we can all agree that SMS is bad. Ironically, the SMS support is what makes it easy to get people to stop using SMS. For a non-technical user, especially where I live in the US, words like SMS and MMS mean nothing. The fact that signal replaces the default SMS app is the only reason it gets used at all. I have met almost no one in the "wild" that uses signal. Converting people to signal was beneficial for me ("yay I get secure messages"); but now they will only be able to use signal to communicate with me. They will not use signal anymore. SMS compatibility is the best way to encourage adoption in an environment with few messaging apps. 

> Third, there are serious UX and design implications to inviting SMS messages to live beside Signal messages in the Signal interface. It’s important that people don’t mistake SMS messages sent or received via the Signal interface as secure and private when in fact they are not. And while we flag the difference between them in the app, we can only do so much on the design side to prevent such misunderstandings.

They seem to be ignoring the fact that iMessage solved this problem long ago. They solved it so well that people have written articles with names like "[Dear iPhone users: Please don't forget that a green bubble is a person.](https://www.androidauthority.com/green-bubble-phenomenon-1021350/)". 

To make a related point, the only way to communicate to someone using iMessage with anything other than an iPhone is through SMS. iMessage is also the only app on iPhone that can recieve SMS, making it the default messaging app. Why would an iPhone user download signal just to talk to me? Where I live, no one uses whatsapp, and I don't even know what telegram is.

 My demographic (gen Z to early millennial) has an extreme bias towards Apple products, as much as [87 percent](https://appleinsider.com/articles/22/01/06/gen-z-survey-says-87-of-us-teenagers-own-an-iphone) of us own an iPhone. In this environment, iMessage will will every time. Roughly 80-90 percent of my contacts have iPhones. Converting the remaining to signal is still beneficial, as long as SMS support exists. 

If SMS goes away, I will have no incentive to promote signal. It simply isn't popular enough where I live to be able to survive without added conveniences, like SMS. Even if it stays on my phone, who will I message?

**Comment by mudinthewater** [comment]
There is no reality in which signal removes the functionality that allows me to talk to my wife and her entire family (IOS) users without me uninstalling the application entirely. 

The 5 or so contacts I have that use actual Signal messages are not worth keeping the app installed. Convincing IOS users to install Singal is a Non-Starter. Convincing Android users to install signal only worked because it could also send texts. 

What is the goal here? To drive people to Android's default messaging app and its RCS and kill signal? 

Claiming that this is for clarity because a few idiots are paying for texts who apparently can't read the locked/unlocked icon or banner is just a joke. 

I will delete my signal the day SMS is turned off.

**Comment by eylenburg** [comment]
This is terrible. People will just go back to Whatsapp. At least with SMS support you could chat to _anyone_ from the Signal app, while adding yourself to the Signal userbase.

I don't think I'd recommend Signal to a non-technical family member or friend anymore. Might as well stick with Whatsapp because why even bother (it also has E2EE and is already used by 99.9% of people in my contact list) or recommend Matrix as the ideal solution (it also has E2EE and unlike Signal it is not centralized and has a web client so you can use it on your work computer).

**Comment by mitch-n** [comment]
### Please don't remove SMS/MMS support

I convinced my whole family to get signal because they can just replace their regular texting app. So all of our family comms are E2EE, which was awesome. That is dead if SMS/MMS support is yanked.

I have had virtually 0 issues using signal for SMS/MMS for over 5 years. It's a great client, and seamless to get E2EE with my contacts that make the switch. **The UI is already fantastic**, and it's very clear when I am sending an encrypted message or not.

Signal and the signal client are GOOD. **Please don't remove SMS/MMS support**, or I would be forced find a new solution.

**Comment by jalavosus** [comment]
This is just genuinely a bad idea. Don't remove SMS.

**Comment by LeftHandRev** [comment]
This is an absolutely awful idea. Do NOT remove SMS support. I use Signal as my one and only messaging platform so that I don't have to switch applications. Not everyone on my contact list uses Signal. 

Please retain SMS. You're going to alienate thousands of users.

**Comment by howlett** [comment]
People will simply run an older version of this software.  That will be even less secure.
Why not indicate by colour or icon that this is an SMS contact?

Please retain SMS, removing it will make most problems worse.

**Comment by greyson-signal** [comment]
Hey folks, I know this is frustrating, but it is something that's happening. I wrote some more context in a forum post, which I know some of you have read. Someone already linked it, but I'll link it again just to be safe: [link](https://community.signalusers.org/t/signal-blog-removing-sms-support-from-signal-android-soon/47954/57?u=greyson-signal).

I think that post sums up a lot of my feelings about it. I know that after reading it you may still feel frustrated and disagree with the decision. But we do have reasons, and we hear everything people are saying, but we still think removing SMS is the right path forward in the long term.

I'm going to lock the discussion on this thread not because I don't want to hear from people, but rather to direct it to a singular place that I think is better for discussion: [our forum](https://community.signalusers.org/t/signal-blog-removing-sms-support-from-signal-android-soon/47954/56). Thanks :heart:
