### ISSUE TITLE
SMS removal : losing your early adopters

### ISSUE THREAD

**Issue by hubyhuby** [signalapp/Signal-Android#12522]
https://signal.org/blog/sms-removal-android/

Signal has been using a very clever aproach very pedagogic with its users:
-it let them use SMS within signal
-it help them make people switch to it via pre-written SMS

**The value of a network is the number of persons you may reach**

WIth signal I can reach 10% of my contacts. Which are ALL persons I had convinced to switsh via the SMS function ! Otherwise thay ALL use whatsapp.

It feels like the signal community is moving to a idealistic world in theire heads, forgetting the users. Moving in a way in the same black or white world the people they are "fighting".

See desktop too : https://github.com/signalapp/Signal-Desktop/issues/3225#issuecomment-1278528307

Please delete or ban me. Anyway I am out of here if you remove SMS from android .  I ll not anymore advertise signal until its back. I will cut the update process in android waiting for the best...

**Comment by lasse-instructr** [comment]
I support this

**Comment by TudelaPierre** [comment]
I support this !

**Comment by Trapulo** [comment]
I cannot understand why it's so hard or "strange" to have signal app also a bridge to/from SMS. If the app act as as a gateway with SMS channel, messages can be shared/routed also from/to the Windows app (for example), and so on, and this can be a plus for users. It also can move more users to Signal, because it has something (else) that whatsup doesn't provide.
Signal is great, but need more power to onboard users that are not interested in privacy, etc. and powerful features are a resource.

**Comment by XxCabbyoO** [comment]
+1 
Please dont remove the sms feature
Its a key Feature for me

**Comment by svoop** [comment]
+1 What a. great day... for WhatsApp. 😢

**Comment by natrius** [comment]
This feature is a main-feature to convince people to use Signal instead of Whatsapp and SMS. Now its Whatsapp and Signal, because it was possible to simply get the SMS with Signal anyway, so it was easier for them to say "Well, why not *shrug*"

The reasoning sounds a whole like an UI-Problem and in my opinion the sms-support should stay. Otherwise there is no real advantage over Whatsapp - as bad as it sounds, but for most people "Privacy" still isn't a real issue. Its worrying, but its harsh reality. 

If that goes through, i can try to convince people to matrix because there is a real advantage over other in terms of features.

**Comment by schultzter** [comment]
At this point Google Messenger with SMS, MMS and end-to-end encrypted RCS over Google's Jibe network (not carrier) makes more sense than Signal does! Especially as people get new phones with Messenger as the default. So those SMS contacts are steadily becoming RCS contacts. 

I just wish Google had a Messenger strategy since the first Android device came out - they had an XMPP Messenger pre-installed on all Android handsets, GTalk, that was integrated with GMail and used an open XMPP server (remember Pigeon).
