### ISSUE TITLE
Lower crop handles stuck behind rotation dial in image editor

### ISSUE THREAD

**Issue by farewelltospring** [signalapp/Signal-Android#12525]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In the image editor, the lower crop handles are stuck behind the rotation dial. When you try to click and drag on the crop handles to crop the image, you rotate the image instead.

This can be averted by reducing the height of the image by dragging the upper-center crop handle (thus causing the lower crop handles to move up, no longer overlapping with the rotation dial), but this is a bad user experience.

### Steps to reproduce
- Take photo in portrait orientation
- Press crop and rotate button
- Try to crop using handles along the bottom of the image

**Actual result:** The rotation dial is turned
**Expected result:** The image should be cropped

### Screenshots

https://user-images.githubusercontent.com/108375980/195825741-e4cdb714-36be-436a-bcf3-2c3de5d0159c.mp4

### Device info

**Device:** Pixel 3
**Android version:** 11
**Signal version:** 5.52.3

### Link to debug log

https://debuglogs.org/android/5.52.3/d17dfe7b51d26f8db668d7b4eb5a3427fe80eb5057cb4f95b024466a5df251b4

**Comment by greyson-signal** [comment]
Hey there! Looks like something went wrong with your video upload on github (it's not playable for me). Could you try uploading again, or just posting a screenshot? Thanks!

**Comment by farewelltospring** [comment]
Works for me on Chrome. :shrug: Does it work if you visit the link to the video directly [here](https://user-images.githubusercontent.com/108375980/195825741-e4cdb714-36be-436a-bcf3-2c3de5d0159c.mp4) and save it to your computer and then open it in a media player? Regardless, here is a screenshot of the video:
![image](https://user-images.githubusercontent.com/108375980/195952047-cae06ff6-db4a-4170-9744-2941683264c9.png)

**Comment by farewelltospring** [comment]
If it's of any use, I have a hunch that this bug was introduced somewhere between 5.49.2 and 5.52.3.

**Comment by shaaati** [comment]
My girlfriend just described and showed the same error to me. When comparing our screens we found that on her phone (OnePlus Nord) the rotation wheel is located further away from the lower screen border than on my Pixel 6. You can see the additional whitespace on the screenshot posted by @farewelltospring.

**Comment by samschr** [comment]
This happens to me to on my Moto G7. It's an issue with any tall aspect ratio images like screenshots. Either the rotation dial needs to be hidden by default, or tall images need to be automatically scaled down more so there's no overlap with the crop handles.

**Comment by shaaati** [comment]
> This happens to me to on my Moto G7. It's an issue with any tall aspect ratio images like screenshots. Either the rotation dial needs to be hidden by default, or tall images need to be automatically scaled down more so there's no overlap with the crop handles.

That is not the required fix in my opinion. Even extreme aspect ratios are scaled down accordingly (I just cropped a picture to have almost no width and all of its height and verified that it is scaled correctly).

The problem is that the UI element with the rotation dial (as well as the cancel/accept and other buttons below it) are placed too far up the screen on some phones, but not all. If they were placed in the correct spot the current scaling would be fine.

**Comment by alex-signal** [comment]
Hello! Are you able to tell me the aspect ratio of the image? Meanwhile I have one or two things I can peek at.

**Comment by shaaati** [comment]
The aspect ratio of my test image is 397x4051.
As expected, such an image can be edited fine on my Pixel 6 but not on, e.g., a OnePlus Nord.
I guess the issue is visible with anything that matches or exceeds the aspect ratio of the native screen. For OnePlus Nord that would be 1080x2400 or a larger height.

But again, I think it doesn't matter what size the image is that you edit. It is a general UI bug on certain devices.

See this screenshot of the UI on the Nord (actual image content cropped out for privacy, superfluous spacing highlighted I red)

![signal-2022-11-04-18-48-25-773~3.jpg](https://user-images.githubusercontent.com/6776698/200042788-67bb6c53-8e44-4105-8acf-cc0ec5b675a9.jpg)`

versus the identical UI part on my Pixel (without any additional space):![Screenshot_20221104-185016~2.png](https://user-images.githubusercontent.com/6776698/200043083-f5971ee8-541e-4e21-8260-f7c949deb0c3.png)

As you can see the issue is not just with the rotation dial but starts earlier once an image has been selected. The dial part is only when users notice it because it gets in the way of something else.

Maybe this is a bug that only occurs if the Android button navigation is activated.
