### ISSUE TITLE
SMS Support Removal & Signal Alternatives

### ISSUE THREAD

**Issue by OdinVex** [signalapp/Signal-Android#12520]
No sensible person would remove SMS support, but Signal is stupidly going that route. Fine, it's all open-source, we fork it and keep it going. For now, offer a list of alternative to Signal:

1. So that we can use them *instead*.
2. Donate to *them* instead.
3. Continue not being forced to use Google's “perceived” spyware (in my opinion, it is).

For now, I'll just fork and create my own diff patches to bring support back in. I don't have the time to maintain for more than myself, and I'm not paying Google to get added to their Play Store.

Edit:

I'm currently using XMPP, self-hosted with my groups.

**Comment by jschlie** [comment]
For f**** sake, really?! So, on top of Signal already being difficult to get people to install, migrate messages and understand the workings of Signal, the new major barrier is going to be the most obvious idiotic move the devs could make? Geezuus, how did that meeting go? 

_**Dev1**: "I don't think we should support SMS any longer because I'm tired of having to make sure my sticker and payment code works if I'm sending a message to either secure or insecure recipients."_

_**Rest of Devs**: "Yeah, great idea! So what if we'd risk breaking compatibility with a huge majority of the 98% of adults that have access to SMS messaging in the US. Plus, even though the US is only 6.2% of the global SMS market with 272 million smart phone users and is projected to reach a valuation of $31.7 billion in 2022, it's worth the risk to get people off SMS. Besides, we know for certain that they'll all get in line and switch to our app when their friends and kids say they should."_

I'm looking into alternatives before the ship bursts into flames and sinks. I don't like the idea of being a ship jumping rat, but I also don't like the idea of being a loyal charcoal rat.

**Comment by whitslack** [comment]
There's no way I'm going to try to remember which friends are on Signal and which aren't. I'm just going to switch back to SMS for everyone and forget Signal. That a terrible move on their part.

**Comment by OdinVex** [comment]
Love how they locked the other thread to stop the majority saying it was a stupid idea. All users will end up doing is holding onto an old version of Signal (is Signal doing this to work with three-letter agencies to guarantee that?) or saying wtf is the point of Signal then. Had a lovely all-in-one messaging software and now I have to bring that Google crap back unless I have everyone adopt XMPP (encrypted, otr, video/audio, chat, file-send, lacks minute-audio clips support, but an extension to the protocol could be made).

**Comment by greyson-signal** [comment]
Hey folks, similar to #12517, I don't think this is the best venue for this discussion. I'll link to [my comment there](https://github.com/signalapp/Signal-Android/issues/12517#issuecomment-1277965716) for context and suggestions. Thanks!
