### ISSUE TITLE
An Opinion On The Removal Of SMS

### ISSUE THREAD

**Issue by userliluzibert** [signalapp/Signal-Android#12543]
This isn't the proper place but I want it to be known that many of the users in the community, including myself disagree with the removal of SMS support. Yes, we all know SMS is not secure and not private but it's better to have some of those conversations secure rather than push those users off the platform. I believe Signal is making a huge mistake when all they need to do is make the ui look a little better to differentiate between sms messages and Signal messages. Thank you for hearing me out and I hope this message convinces you to not remove this feature.

**Comment by RemiLelaidier** [comment]
They don't care.
I bet in a year they'll reinstate the feature (if Signal survives this understandable, but aberrant change)

**Comment by Angelinsky7** [comment]
Im coming here to also say that i think it's a bad decision to remove sms support from the app,.  It was one of the reason that i liked signal. Sad that those kind of decision are not community driven and sad that we cannot decide if we want sms or not (because it could be an option).... 
We could have done a poll to see how many people use it before removing feature
