### ISSUE TITLE
Cannot close stories onboarding screen

### ISSUE THREAD

**Issue by MartinX3** [signalapp/Signal-Android#12589]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If I want to open a story there is a tutorial showing me what to do.
But I can't dismiss it. The app freezes.

### Steps to reproduce
- open the story signal sorry from 2 hours ago

**Actual result:** freeze
**Expected result:** dismiss the dialogue 

### Device info

**Device:** Sony Xperia XZ2
**Android version:** 12
**Signal version:** 6.0.6

### Link to debug log

https://debuglogs.org/android/6.0.6/02f423d34d7e5272430f8d824165c6a3cd84625bd4189923db98d569ea35f96a

**Comment by ckolodjski** [comment]
I'm mobile rn and haven't read your debug log, but do you have animations disabled? Same thing happened to me; I had to renable animations, re-open Signal, dismiss the tutorial dialogue, and then disable animations again.

**Comment by muffl0n** [comment]
This worked for me! Pretty weird, but enabling animations temporarily really did the trick.
Thank you very much!

**Comment by MartinX3** [comment]
@ckolodjski thank you. Activating animations to dismiss the tutorial did work. <3

**Comment by herostrat** [comment]
Same for me! Thanks.

**Comment by engelhro** [comment]
Same for me… Never would've thought of that.

And again (next to the dysfunctional SMS export) a great display of the QA at Signal 👏 – such a bug should've been catched before releasing the story feature to the public.

**Comment by pSY0niK** [comment]
It doesn't happen on the on-boarding screen only, someone posted a story and opening it does the same thing (I'm assuming because there is some check to verify if on-boarding was completed beforehand, so the same menu appears again).

**Comment by alex-signal** [comment]
> Is the software documentation in android not good enough to catch this behavior with deactivated animations?

There is, and in fact there's a ViewAnimator.areAnimationsEnabled() (Albeit only available on API26+). There's also a way to check via System.Settings through a ContentResolver.

This was a bit of a weird one, and didn't use the traditional view animation apis. The animation duration scale was properly set to 0, but they play in a bit of a manual sequence:

Top, Middle, Bottom, Delay for 300ms, repeat.

So each animation properly had a 0ms duration, but because of the way it was structured (since it was using LottieAnimationView for playback), we got ourselves into a very tight loop, which ended up starving the main thread. The solution of course was to just check if animations are enabled before attempting to start playback.

> It doesn't happen on the on-boarding screen only, someone posted a story and opening it does the same thing (I'm assuming because there is some check to verify if on-boarding was completed beforehand, so the same menu appears again).

The first-time-nav dialog is displayed over any story until you hit got it, not just over the onboarding story. It's meant as a quick one-time thing but obviously SOMEONE (glares at self) forgot to test with animations disabled. Sorry about that!
