### ISSUE TITLE
Tablet version

### ISSUE THREAD

**Issue by jnigrine** [signalapp/Signal-Android#12583]
I would really appreciate having my Signal messages available on my tablet. It really gets in the way sometimes when I actually don't have my phone at hand and I don't know I got messages. (Yes, that is a real use case.)

I know there have been concerns about display size. I'd rather it be there, even if not perfect, than for the 100% perfect app to be missing. For that matter, there are issues with display size on Windows, but I use it gladly anyway!

**Comment by IAmNotAJerk** [comment]
Why is this closed may I know? The development team is shamelessly closing threads without even care to explain or refer to other threads that they rudely closed in the same manner? 

In one thread they even say no plan for a larger screen and ironly there's an ipad link device service. Yeah in a more closed plaatforrm of ipad os instead of android.

To this point it's a accessibility issue. Unlike Whatsapp or telegram, signal do not have a web interface so there is no work around. I do respect that choice for security issue, but the lack in platform openness is why I can't recommend this app anyone, which is a huge shame coz this app took all the attention as a user friendly secure messaging app that grasp most public attention (and donation)

Tight resources is not an excuse. Give us a road map and most user have the sense to wait. If you really don't care, at least have the dignity to keep these threads as a wall of shame instead of closing them violently. There IS a huge userbase, just goggle it . And by ignoring them, you just blind yourself.

**Comment by jimbudarz** [comment]
Feel free to join the people interested in this feature [in the forums](https://community.signalusers.org/t/android-tablet-support/5590). Maybe we can hit critical mass over there, even if at the moment it feels more like a support group.

**Comment by jnigrine** [comment]
Thanks, but last time I made this suggestion the ticket got closed almost 
immediately, for no reason I could understand. So I've given up on trying 
that route.
