### ISSUE TITLE
Signal number deregister on its own

### ISSUE THREAD

**Issue by Chromatros** [signalapp/Signal-Android#12595]
This is a bug that happened years ago. I already got 3 calls today that some users got confronted with this issue. The registration screen popped up. All users use the device daily and have registration lock enabled with a strong pin. I will provide the logs later. This is very annoying. Especially for people that use online free numbers to register.

**Comment by greyson-signal** [comment]
Hi there, this is intentional. If Alice registers number X and enables reglock, but Bob later proves ownership of number X (by registering and completing the SMS code), then Alice will be unregistered. However, if a reglock is present, Bob _still won't be able to register immediately_ if he does not know the reglock code. This allows reglock to still function as a way to prevent someone else from taking over your account.

However, by unregistering Alice, this starts a 7-day timer. After 7 days, if Alice doesn't re-register, then the reglock is removed and Bob will be free to register the number without needing to know the reglock. But if Alice still truly does own the number, she can simply re-prove ownership and things should go back to normal for her.

This is important because phone number can (and are) re-used among cell carriers. If someone gets a new phone number from their carrier, they should not be prevented from registering with Signal indefinitely because the previous owner has reglock.

The intention of reglock is to prevent hijacking of numbers you actually own, _not_ to guarantee the number for yourself for life.

**Comment by rt4mn** [comment]
I just had to boot an activist from our secure group chat because his account got taken over by some random person, despite him enabling registration lock. Your misleading language is putting users at risk.

> The intention of reglock is to prevent hijacking of numbers you actually own, not to guarantee the number for yourself for life.

This directly contradicts what is said in UI toggle for registration lock. It says "require your signal PIN to register your phone number with signal again". There are no qualifiers or caveots like the ones you just added. It does not say "require your signal pin to *quickly* register your number with signal again"

**Comment by greyson-signal** [comment]
Before continuing, just want to make it clear that the server change that was made where Bob proving ownership of number X would log out Alice was reverted back in mid-November because we wanted to make some adjustments to it.

So I'm actually interested in the story of how your friend lost access to their account. Do they no longer have access to the number? Are they sure they had reglock enabled? Do they have an easily-guessable PIN? Because since we reverted the change, if they truly did have reglock enabled, even if someone else answered the SMS code, your friend wouldn't be logged out unless the other person also knew their PIN.

Continuing with your other questions though, because we will be re-introducing it again in the next couple months, I'm going to respond from the perspective of us re-enabling it.

> This directly contradicts what is said in UI toggle for registration lock. It says "require your signal PIN to register your phone number with signal again".

This is still true. The other person will not be able to _register_ with your number without knowing your PIN -- they could only log you out. In the previous example, Alice still has 7 days to re-register, and during that time Bob cannot register without knowing the PIN. It's only after the 7 days that Bob could register with that number. And this 7 day period has always existed. It's always been the case that if an account is unregistered for 7 days, then the reglock is removed.

>  Yes, they should. Because otherwise people lose access to their accounts.

If people lose access to their old number, they can change their number in the account settings to their new number. Also, continuing our example, even if Alice is unregistered by Bob proving ownership of the number, she can still re-register with a different number and keep all her chats and stuff.

**Comment by rt4mn** [comment]
@greyson-signal appreciate the reply. 

I'm still talking with the activist to see if they have more details on how they originally got the number, and how they lost access to the account. From our perspective the chain of events went: activist notices their app does not work anymore ~2 days ago and yesterday we notice that their name / profile picture has changed and I have to boot them from all our group chats. Its hard to go into more specifics since now we use email to talk and both of us are very slow emailers. 

Luckily I don't think any sensitive messages where sent before they where removed, and the usurper obviously does not have chat history and so on, but I'm worried now about whether usurper impersonated the activist for 1v1 chats (unlikly given that they changed name / profile picture but still a possibility we need to account for), or about future cases where this happens, since I know for a fact a lot of the folks in our group also use burner numbers in one form or another. 

My plan right now is to either start a discussion on the forums or open a full issue on this when I hear back from the activist and have a chance to talk to other folks about how much of an impact this is going to have on us op-sec wise.

**Comment by mononobi** [comment]
> Before continuing, just want to make it clear that the server change that was made where Bob proving ownership of number X would log out Alice was reverted back in mid-November because we wanted to make some adjustments to it.
> 
> So I'm actually interested in the story of how your friend lost access to their account. Do they no longer have access to the number? Are they sure they had reglock enabled? Do they have an easily-guessable PIN? Because since we reverted the change, if they truly did have reglock enabled, even if someone else answered the SMS code, your friend wouldn't be logged out unless the other person also knew their PIN.
> 
> Continuing with your other questions though, because we will be re-introducing it again in the next couple months, I'm going to respond from the perspective of us re-enabling it.
> 
> > This directly contradicts what is said in UI toggle for registration lock. It says "require your signal PIN to register your phone number with signal again".
> 
> This is still true. The other person will not be able to _register_ with your number without knowing your PIN -- they could only log you out. In the previous example, Alice still has 7 days to re-register, and during that time Bob cannot register without knowing the PIN. It's only after the 7 days that Bob could register with that number. And this 7 day period has always existed. It's always been the case that if an account is unregistered for 7 days, then the reglock is removed.
> 
> > Yes, they should. Because otherwise people lose access to their accounts.
> 
> If people lose access to their old number, they can change their number in the account settings to their new number. Also, continuing our example, even if Alice is unregistered by Bob proving ownership of the number, she can still re-register with a different number and keep all her chats and stuff.

This is currently happenning at scale for many phone numbers in Iran. it is most likely a state sponsored attack.
the authorities can read and filter any SMS to any number they want, and this stupid half baked feature of Signal is actually letting them do exactly that. Currently I have been logged out of my account and I did have a Register Lock pin set. but when I try to register again, no SMS reaches my phone. and based on what you're saying, 7 days later, some one will have an account with my own number and can act as me. SO fucking stupid. well done Signal architectures, well done.

This also has happened to many other Iranians, one of my family members included.

**Comment by niwazukihon** [comment]
If Bob successfully proves ownership of the number for 7 days, what would happen to Alice? I assume Bob can't access past messages and contacts of Alice, but can Alice still use Signal as usual before she re-register with a different number?

Under this scheme, a government could intercept the SMS message and lock any suspicious person out of their account. Re-registering with a new number would either not work (if the government knows the person), or let the same thing happen again (if the government knows the contacts).

The "Registration Lock" option in the app setting is very misleading and plainly incorrect, because it suggests that Bob needs *both* the phone number and the PIN to claim the account. The 7 days restriction should obviously be mentioned with the "Registration Lock" option. This overall seems to jeopardize certain things Signal tried or advertised to do, such as censorship prevention.
