### ISSUE TITLE
Forwarding a message with multiple images to a story only posts the first one

### ISSUE THREAD

**Issue by nils-werner** [signalapp/Signal-Android#12632]
When you share multiple images from a conversation as a status message, it appears on my end that they get published.

However all my contacts can only see the first image. The remaining ones are not reachable for them.

**Comment by clauz9** [comment]
so, I've tested this myself, and it seems to happen only when you share multiple images that are bundled together in one message... 

otherwise if you select multiple images and share them it works ... 

Also, please add a debug log, or send it to the developers, even though in this case, it might not be necessary, it's usually good practice to stick to the issue template and not delete it, when reporting issues on github.

**Comment by nils-werner** [comment]
Oh I'm sorry I am not sure why GitHub didn't show me the issue template. I didn't delete it on purpose.

**Comment by greyson-signal** [comment]
This should be fixed
