### ISSUE TITLE
Messages sent to contact B appear in a wrong communication thread (with contact A)

### ISSUE THREAD

**Issue by MartinCupak** [signalapp/Signal-Android#12691]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was in signal messaging conversation on my Android device with one contact (A), while another person (contact B) connected with me on Signal as a completely new contact for the first time.
Since then, all outgoing messages I send to contact B appear in the conversation thread with contact A rather than with contact B. In the contact B thread, they remain as draft until I remove the draft text. My messages are sent and delivered correctly to the corresponding contacts. "Only" the communication thread with contact A is a mix of 2-way conversation with contact A and My messages sent to contact B. The communication thread with contact B contains only incoming messages from contact B.
(This was a bit of shock and panic mode that messages are delivered to wrong addressee. But apparently it is only mixed up in my Android Signal client app. I can imagine this could have serious consequences, for example in life-and-death scenarios in war zone(!!!)) 
I'm also using Signal-desktop on Linux, but there I see all the messages sorted correctly, even those which I see in Android Signal App in a wrong thread. Messages sent by me to contact B from Signal-desktop app on Linux appear in the correct conversation thread even in the Signal app on Android device. These are also the only outgoing messages I can see in Signal Android app.

### Steps to reproduce
I think this was probably triggered by new contact (B) connection request while messaging with existing contact A.
Cannot really reproduce that moment, as you can see, it looks like some unlikely race condition glitch excluding individual communication threads. It is not a group chat by mistake, as each contact (A and B) receive only their messages.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Whenever I send a message to contact B in Signal app on my Android device, it goes to the wrong communication thread with contact A. It does not appear in the thread with contact B. Signal app switches context to the communication thread with contact A.
Note: I have tried to restart the Signal App, Force stop of the Signal app and restart the phone, nothing fixed this issue.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
When I send a message to contact B in Signal app on my Android device, it shall appear in the correct communication thread with contact B. It shall not appear in a wrong communication thread with contact A. The Signal app shall not switch context to a thread with another contact (A) when tapping on send icon when sending a message to contact B.

### Screenshots
Not willing to provide screenshots in public post, sorry. Same with logs (have log.txt saved). Happy to send both via private channel.

### Device info
**Device:** Samsung Galaxy A52s 5G Dual SIM (SM-A528B/DS)
**Android version:** 12
**Signal version:** 6.5.6

### Link to debug log
Not willing to provide log in public (have log.txt saved). Happy to send it via private channel.

**Comment by greyson-signal** [comment]
Hey there, I've been actively working on this. I'm still trying to root-cause it, but in the meantime I've added additional protections at various levels in an upcoming release that should prevent things like this from actually being sent. 

Would really love the log so that I can look at this in more detail. You can send it to greyson@signal.org. When you do that, can you also get the sent timestamp of an example message that was sent with this bug? To get the timestamp, long press a message -> click info -> long press the sent time in the message details screen. That will copy the timestamp to your clipboard.

Thank you!

**Comment by MartinCupak** [comment]
Thanks, Grayson, for considering this issue important.
I've sent you the log by e-mail, incl some useful notes which hash is which user and so. I had a look into the log.txt and figured out who is Contact A and who is Contact B, and linked some of the messages times, but some seem to be off. Not sure how well the timestamps are synced WRT device system time and Signal server system time vs. eg ntp/chronny. Guessing you know all this very well ;-)
Also forgot to mention, part of the trouble could have been me having both Android Signal app and Linux Signal-desktop running at the same time.
Cheers,
Martin

> Hey there, I've been actively working on this. I'm still trying to root-cause it, but in the meantime I've added additional protections at various levels in an upcoming release that should prevent things like this from actually being sent.
> 
> Would really love the log so that I can look at this in more detail. You can send it to [greyson@signal.org](mailto:greyson@signal.org). When you do that, can you also get the sent timestamp of an example message that was sent with this bug? To get the timestamp, long press a message -> click info -> long press the sent time in the message details screen. That will copy the timestamp to your clipboard.
> 
> Thank you!

**Comment by greyson-signal** [comment]
@MartinCupak Thank you! With your log, I think I've developed a better understanding of how this happened. The logs don't go back enough to 100% confirm my theory, but I'm relatively confident I've found the bug that led to this. It is a specific combination of having some bad database state that was fixed by a database migration in 6.5, but the migration "missed a spot", which was then combined with a specific order you sent messages to a new contact, which then got the threads in this state. Hard to go into more detail without writing several long paragraphs :p

If my theory is correct, this situation should be exceedingly rare, but I'm currently preparing a fix. It'll go to beta for a day to ensure everything is fine (because it'll involve a database migration), but if it checks out I'll be shipping it to production soon after, and it should resolve your bad state. Specifically, it won't be able to "move" any messages you've already sent to the correct thread, but it will make it so all future outgoing messages should be rendered in the correct thread.

Very sorry this happened, and thank you for reporting it!

**Comment by MartinCupak** [comment]
Hi Greyson,
Just to let you know, with the recent android Signal app update my two tangled communication threads are now completely detached. The old messages sent prior the update stayed where they were, as you predicted.
So in summary, the behaviour of the app now is as expected.
Thanks again a lot for the guick fix!
All the best in 2023!
Martin
