### ISSUE TITLE
Prevent battery optimization from preventing message reception

### ISSUE THREAD

**Issue by navid-zamani** [signalapp/Signal-Android#12736]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I noticed that the majority of complaints in the Play store (at least here in Germany) revolve around not receiving messages on time. Which is caused by the battery optimizations done on certain phones.
Other apps usually tell the user to go disable those settings, by setting them to manual and always enabled. (See sceenshot.)
Signal still lacks this. So it should tell users. Both on install, for new users, and ideally on the next update, to fix it for the large base of existing users.

### Steps to reproduce
- Use a phone with this battery optimization festure.
- Install Signal, add contacts, write some messages.
- Use other apps tgat use resurces a lot and lock the phone in-between, to trigger the system to stop Signal. Do not use Signal at all, so it won’t he kept alive. (Try at leaat 24h, to make sure.)
- Arrange for some messages to be sent to you.

**Actual result:** The messages will not be received until Signal is re-opened and used again. Leading to complaints by users.
**Expected result:** Signal should always run, like on phones without ths toptimization, and hence receive pessages promptly at all times. Leading to the main souce of complaints being gone, and possibly higher adoption.

### Screenshots
Example battery optimization settings on EMUI 12 by Huawei:
![Screenshot_20230118_104147_com huawei systemmanager](https://user-images.githubusercontent.com/58148887/213137164-7885ca9b-f3e2-4e46-bc09-6b93109448ee.jpg)

### Device info

**Device:** (Many. Notably, Huawei did it first. Lists of which manufacturers do this, should be easily found online.)
**Android version:** (Many. In my case, 10.0, but stock Android does not do this AFAIK.)
**Signal version:** All

### Link to debug log

(Does not apply)

### Additional note
This should close a whole set of bugs here. I made this a new bug, as those bugs focused on the wrong things and were already too set on that path, making this meta issue off-topic there. Ideally, all those bugs should be marked as duplicates of this one.
(I have indeed searched for a bug focusing on the right thing like mine, and found none; but maybe it was worded in a way that I could not think off.)

**Comment by MakingMadness** [comment]
This is the biggest problem I've had with Signal for many years, not because I can't fix it, but because my friends can't.

How can we be expected to convince others to install Signal instead of Whatsapp if it doesn't work on most phones? This is the biggest bottleneck in getting friends to adopt Signal and actually stick with it. We need to get all Signal users to have as robust a messaging ssrvice as Whatsapp, without needing to be technical people. Not receiving messages is a critical fault for a messaging app, so if we want Signal to compete with Whatsapp then this needs to be addressed with the highest priority.

I'm aware that OEMs are the bad guys here, but that can't stop us if we want to protect our loved ones. Please implement a solution that non-technical users can easily understand and implement no matter what phone they have.

**Comment by MakingMadness** [comment]
Bump. This is important.

**Comment by cody-signal** [comment]
We are actively considering all options around improved messaging reliability, including this one, but I don't have a timeline or a clear statement on if we'll even do it. Just know it's being discussed internally.

**Comment by MakingMadness** [comment]
Thanks for the info @cody-signal, and for your hard work. I look forward to anything further on this. I've been trying to get people to adopt Signal since the beginning, and out of the friends that installed it, 80% of them bail because of the battery optimisation problem. I suspect that this issue is underrepresented on GitHub because if you're using this platform then you are almost certainly also experienced enough with tech to solve the optimisation problem yourself.

**Comment by Goldmaster** [comment]
This was what I had been wondering before!

**Comment by MakingMadness** [comment]
There's more information here: https://dontkillmyapp.com/

However, that website in itself isn't enough to combat the problem. It's out of date, and it's way too technical for non-github users. Again, this is a critical problem where the core functionality of Signal isn't working for people who aren't tech-savvy enough to post an issue here. I know it's because of OEMs, but **we have to overcome this anyway**.

**Comment by Goldmaster** [comment]
Hope this won't go stale

**Comment by greyson-signal** [comment]
We are prompting in certain situations, but only those where we detect that messages have been repeatedly delayed.

**Comment by Goldmaster** [comment]
Wave of the future Dude!

What do they look like? I guess it's only if signal gets a message and detects that the message hasn't been read that it promots the user?

**Comment by MakingMadness** [comment]
@greyson-signal thanks for the update. Would it be possible to post a screenshot or GIF of this feature?

**Comment by MakingMadness** [comment]
@greyson-signal Yes hopefully, but what is the actual solution? So far I understand that you attempt to detect that there's a problem, but what is actually done when a problem is detected? Presumably you're telling the user to do some actions in steps? Are these steps correct? Is there any QA on this? How do we know it works? Can you link to the relevant part of the code?

**Comment by MakingMadness** [comment]
@greyson-signal my friends are still having problems with this. Can it be reopened?

**Comment by MakingMadness** [comment]
Any chance this can be reopened? Thanks.
