### ISSUE TITLE
Share Contact on Signal

### ISSUE THREAD

**Issue by pedrobotelho** [signalapp/Signal-Android#12856]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When we share a contact using Signal and the contact doesn't have Country Code (+351) in my case, +44 will be added by default.

### Steps to reproduce
- Open contacts on your android contact app
- Find a contact that does not have any country code prefix attached
- Click on share and choose Signal
- Click on any contact and what will be displayed is the name and number with the country prefix of +44

**Actual result:** the country prefix of +44 will be added and +44 is not even my country code.
**Expected result:** no country code should be attached not my default and not any other.

### Screenshots
![01-signal-2023-03-24-111010_002](https://user-images.githubusercontent.com/5587196/227506655-7f248c00-8a8e-451c-b4e3-373a5958aeb3.jpeg)
![02-signal-2023-03-24-111010_003](https://user-images.githubusercontent.com/5587196/227506667-3e1433d2-9b50-4555-b86c-6b808e168efa.jpeg)
![03-signal-2023-03-24-111010_004](https://user-images.githubusercontent.com/5587196/227506685-b74c1f74-77c4-4026-a6df-b36cb53872a7.jpeg)
![04-signal-2023-03-24-111010_005](https://user-images.githubusercontent.com/5587196/227506707-9de35e91-448d-4d7c-9bc8-b45f6122e97b.jpeg)
![05-signal-2023-03-24-111010_006](https://user-images.githubusercontent.com/5587196/227506730-ffdabf5d-2ec8-4fb5-9184-e8e6a12964c2.jpeg)

### Device info

**Device:** Xiaomi Pocco X3 PRO
**Android version:** 13 TKQ1.221013.002
**Signal version:** 6.14.5

### Link to debug log
[DeBuG LOG](https://debuglogs.org/android/6.14.5/14837433dfb886168864ab3478510bde3ba6f794d9df7ad4e876229c68903320)

**Comment by d2weber** [comment]
Hi, I am encountering the same issue.
I wonder why in https://github.com/signalapp/Signal-Android/blob/55af6ca84e32683662a96f9f621728d47fabae9e/app/src/main/java/org/thoughtcrime/securesms/contactshare/ContactUtil.java#L110 the number is parsed using locale as default region, I believe it doesn't make sense here. Possible solutions might be:
* Use [getSimCountryIso](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getSimCountryIso()) instead of locale
* Use `parseAndKeepRawInput` instead of `parse` and in the case that `country_code_source` equals to `FROM_DEFAULT_COUNTRY` use `NATIONAL` instead `INTERNATIONAL` while formatting

**Comment by d2weber** [comment]
Duplciates [#9767](https://github.com/signalapp/Signal-Android/issues/9677)
