### ISSUE TITLE
Backup fails with "Bad attachment id" 

### ISSUE THREAD

**Issue by rudolfbyker** [signalapp/Signal-Android#12861]
https://debuglogs.org/android/6.14.5/e91276cb2ce3c713a4e0db1b2b7cc35406b026e3f3dbb2c12733280de23a0776

I'm more than happy to delete the offending attachment, but I have no idea how to find it.

**Comment by cody-signal** [comment]
Hrm. There indeed is a bad file here. The good news is the verifier is finding it, so you know now it's not working compared to when you may restore the backup, but also, not great you can't make a backup.

 I could make you a one-off build to help you find it. The other thing is that based on the logs, the attachment is likely from around '2023-03-03 15:50:31.464 EST' and ~7mb (though the size is likely inaccurate as that's what's causing the crash), timestamp is your best bet and use size as guidance.

**Comment by rudolfbyker** [comment]
Thanks for the info. How do I view all attachments by date or size without going through my contacts/chats one by one?

**Comment by rudolfbyker** [comment]
Thanks, I could delete the attachment, and now the backup reaches 100%. After that, it does "verifying backup". When I check back later, it still says "Last backup: 02 Mar, 08:56". No new backup file was created in my backup folder (SD card > SignalBackup).

https://debuglogs.org/android/6.15.3/4267d7a8b5f3efb535d9d9c748d3f33763d5ebe88234cdc73160842bd57bd1b4

**Comment by cody-signal** [comment]
Looks like it's hitting another bad attachment :/

This one is around 2023-03-06 11:12:52.429 UTC+2 and size is ~8.8mb

**Comment by rudolfbyker** [comment]
OK, I deleted that one, but the same thing keeps happening. Please teach me what to look for in the log. All I find is "Bad attachment ID", but I can't figure out how you see the date and time of it.

**Comment by hrehfeld** [comment]
put `id` into https://www.unixtimestamp.com/ , and `len` is the number of bytes.

[this is also happening to me]

**Comment by rudolfbyker** [comment]
Thanks!

One more thing that is bothering me, is that these attachments are perfectly fine when I view them in signal, or when I save them to my phone. They are not corrupt. So maybe the length is just being stored incorrectly?

**Comment by hrehfeld** [comment]
Is there a way to trigger backup via adb? This would at least save all the time spent scrolling...

**Comment by cody-signal** [comment]
Hi @hrehfeld @rudolfbyker looks like your updates didn't make it through our triage system to me until today.

I fully agree this is an untenable solution long term. Short term was hoping this was just a handful of attachments and not something systemic to get ya unblocked while we fit in a solution to this. Will try to get something in soon.

**Comment by cody-signal** [comment]
@hrehfeld can you provide a debuglog after a failed backup? You can post here or send it to me directly via cody at signal dot org

**Comment by cody-signal** [comment]
@rudolfbyker can you check if where you are storing the backup is fat32 formatted? I was reminded that this kind of error can occur if your backup is larger than 4gb but you are trying to save to fat32 which can't support larger than 4gb files. It would explain why it keeps happening and why the attachments seem fine.

We had a task for chunked backups that fell off the priority list that would address this problem but it's not a simple solution (more usability wise than technical).

**Comment by rudolfbyker** [comment]
Aha! Yes, my last successful backup is exactly 4G (or a few bytes under that), and I'm using my SD card, which is FAT32.

Does Android's internal storage support files larger than 4G? In this case my workaround will be to make a backup there, save it somewhere, and start over with a clean history.

Then I just need a nice backup message browser of sorts. There are a few out there, but all of them reverse-engineer the backup format. Tangent: Wouldn't it be great if the code that reads/writes backups were extracted to a separate library? Then people could link that as a Python / <insert favourite language here> library, and nobody would have to reverse engineer anything.

**Comment by alex-signal** [comment]
@rudolfbyker It should, yes. I believe internal storage is ext4

**Comment by rudolfbyker** [comment]
My backups are working on internal storage for now. Would love to move it back to external, or maybe even a trusted/encrypted cloud storage of my choice if possible (e.g. pCloud or something self-hosted).

**Comment by huttarl** [comment]
As an Android app developer, having a backup fail like this without giving any hints of why, or what to do about it, doesn't seem acceptable for users. I've been running into this same problem, when trying to back up to removable SD card. The only reason I was able to find this issue on Github was because I used logcat in the development environment and found the "Bad attachment id: null len: 608334 / org.thoughtcrime.securesms.backup.BackupRecordInputStream$BadMacException" error.

When this problem happens, could the backup functions give more help, maybe a link to some kind of FAQ that mentions the 4GB and fat32 limitations?

As it happens, I've been unable to back up to internal memory either. Maybe I'm running out of space there too -- the backup process doesn't say what caused the problem. I searched for helped on the Signal support web site (https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages) and found nothing relevant.

**Comment by gengrill** [comment]
Same.. I have a device with a 5+ year chat history across dozens of groups and tens of GBs. Now I cannot back up any of it due to `Bad attachment id: null` blocking the export at 99% - even though the backup file was clearly created, the size of the temporary backup file matches the size of the installation just before it is deleted again due to the error.

@cody-signal @greyson-signal it seems a bit odd to just bail out completely when this happens, because this hard failure means users will lose 100% of messages if even a single attachment is broken. Numerous people reported hitting this on Android over the past few years, and I think most would be more than happy to take a partial backup and recover the broken messages manually - or even delete individual messages - rather than be left with nothing at all.

**Comment by befocken** [comment]
Just encountered the same problem with the `Bad attachment id: null` error message. In my case, the backup file was about 8GB big before it got deleted  due to the failed check during verification. I solved it by using an USB stick formatted with NTFS via a USB-C-Hub, even though that took >6h because most smartphones don't prioritize a decent USB speed. For a one-off backup (e.g. for a transfer of the chats) definitely viable, but for a regular backup that's not an option, as one cannot constantly have a USB-Hub dangling off the phone.
