### ISSUE TITLE
1 unread but not listed when filtering on unread

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#12890]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I see "archived conversations (1)" but it is not being shown. It us true, I do have an archived group with unread messages. Maybe that group has been silenced before it was archived, maybe that is why this happens. I have not attempted to recreate with a new group.

Related side notes:
1. That group is a spam group to which I was added against my will
2. Signal shows "Meteor0id joined the group" but that string should say "Meteor0id was added to the group. Please ask the design team to rearote that text string. Joining is not the same as being added 
3. The translation says "earase filter" but earase is not the right word here. It should say "remove filter"  (filter verwijderen). Even better would be to not speak of interacting with filters "remove filter", but instead speak of sonething the user is actively looking for "remove filters and show all chats", that would be more intuitive to people who end up on the filtered screen by accident.

I know this UI feedback won't be seriously considered but I tried.

### Screenshots

![Screenshot_20230411-040131](https://user-images.githubusercontent.com/34976212/231036401-a2c8dcc7-c1e0-4ad3-b38d-3b3b8405cdb0.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

https://debuglogs.org/android/6.17.1/6f09b25d48592907080aa12f0fe47c82950f98286f382a4113d9c265284ddc87

**Comment by greyson-signal** [comment]
@Meteor0id 
> I see "archived conversations (1)" but it is not being shown.

This is intended. We introduced the "keep muted chats archived" feature specifically to keep stuff out of peoples main chat list. You should be able to tap the "archived conversations" button to go to the archived chats, then pull down to filter archived chats by unread as well.

> Signal shows "Meteor0id joined the group" but that string should say "Meteor0id was added to the group."
Sounds like a bug, we'll TAL.

> The translation says "earase filter" but earase is not the right word here. 
Forwarded the feedback and was told it's been updated.

@bellsebub 
> I have noticed that if somebody reacts to a message, let it now marks it as unread...

Not sure what you mean specifically. Reactions will certainly generate a notification -- but we don't mark the thread as unread with an indicator just for a reaction. Are you seeing a blue circle indicator in the chat list indicating a thread is unread purely because of reactions? If so, I can't reproduce it and would appreciate a log. You should also probably open a separate issue since it's different from the original report.

**Comment by Meteor0id** [comment]
Ah now I see how this was intended to be used, and it's not bug indeed. But that was not obvious at all, I expected that if you pull down to filter it will also list both achieved and not archived conversations. Having to swap between those is extra effort, why do that?

The reason this was not clear at all is because the "achieved conversations (1)" looks like a section header rather than a button. Because:
1. It has no background color or border
2. It has no action verb "go to" / "view"

So these are essentially 3 buttons underneath each other each with a different layout. That's not intuitive.

Maybe you want to take that up with design
