### ISSUE TITLE
Signal app update notification should not play any sound (audio) alert

### ISSUE THREAD

**Issue by jaystrictor** [signalapp/Signal-Android#12900]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My Android phone wakes me up with a loud notification sound, whenever Signal app wants to update itself.

### Steps to reproduce
- install Signal using the APK at https://signal.org/android/apk/ (and not via App Store)
- activate DND (Do Not Disturb) mode on your phone
- wait for a Signal app update notification to arrive (could take a couple of days or weeks)

**Actual result:** You will hear a loud notification sound when Signal app wants to update.
**Expected result:** I would expect to get a silent app update notification that I can turn my attention to at a later time.

Note that on my phone, usual text notifications honor the DND settings perfectly, so there is no issue with incoming Signal text messages. Those only issue a silent notification, without a sound. Only the Signal app update notification seems not to honor the DND setting.

### Device info

**Device:** Google Pixel 6a
**Android version:** 13
**Signal version:** 6.16.2

**Comment by CommonLoon102** [comment]
Signal doesn't let me sleep because of this. I get woken up once per week. Very annoying and disturbing. I will switch my phone off completely before sleep as I don't want to have this happening again. My eyes are still burning. Do not disturb was on until my wake up alarm, and Signal wakes me up regularly an hour before that.

No need to have a sound for such insignificant, ultra-low priority message at all! There is an update! Who cares?! I'll handle it when I'll look at the screen next time, no need to make any sounds! In what life scenario is it useful? Updating signal never can be such urgent that you need to wake up people or even just disturbing them in any other activity! Even if I just walk my dog, I don't want to be disturbed by a sound of "signal updates". It doesn't even worth reaching into my pocket.

Please, delete that line which makes any sound for signal updates.

I use the APK too, I'm on Lineage OS 16 without Google crap.

**Comment by cody-signal** [comment]
Sorry about that. Thanks for the clarification, we're looking into it.

**Comment by jaystrictor** [comment]
Now that I think more about this, I think @CommonLoon102 is right with their suggestion.
It is not necessary at play any sound all to notify about an update. A Signal app update can be dealt with in a quiet moment at the end of the day or even after a view day. No need to alert the phone owner immediately.
So this issue should be completely independent of the DND mode.

**Comment by greyson-signal** [comment]
Looks like we lowered the priority for this notification in 6.23. It looks like the change may have only applied to new installs though. If you'd like to change things for yourself, you can go to your system notification settings for Signal and update the "App Updates" channel to whatever settings you would like.

**Comment by CommonLoon102** [comment]
I've unchecked the "App updates" channel but then how can I update the app in the future?

**Comment by greyson-signal** [comment]
@CommonLoon102 you don't have to completely disable it -- you should be able to just update the settings. Make it a lower priority, remove the sound, that kind of thing. Different OEMs give different options.

**Comment by CommonLoon102** [comment]
@greyson-signal Oh, thank you. I have Lineage OS 9, I never knew that I can tap on the channel name and there will be a lot of other options for it. Until now. Thanks. Now it is being shown silently, let's see how it works.
