### ISSUE TITLE
APK has wrong certificate file name

### ISSUE THREAD

**Issue by scytho** [signalapp/Signal-Android#12935]
Hi,

I downloaded the APK the other day and attempted to verify the fingerprint. That failed. I then discovered that the name of the certificate file within the APK is different. Has there been a name change, or has the APK been meddled with?

**Comment by greyson-signal** [comment]
Where are you getting your APK? I just did a sanity-check of our website APK and last few Play Store APKs and they all look as expected. You should be able to run the following command:

```bash
apksigner verify --print-certs <apk file>
```

And you should expect the following output (all the way at the top, above the random warnings)

```
Signer #1 certificate DN: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Signer #1 certificate SHA-256 digest: 29f34e5f27f211b424bc5bf9d67162c0eafba2da35af35c16416fc446276ba26
Signer #1 certificate SHA-1 digest: 45989dc9ad8728c2aa9a82fa55503e34a8879374
Signer #1 certificate MD5 digest: d90db364e32fa3a7bda4c290fb65e310
```

**Comment by scytho** [comment]
I downloaded it from here: https://signal.org/android/apk/

> You should be able to run the following command:

I can’t, apksigner is too old on my system: https://github.com/signalapp/Signal-Android/issues/10316

Anyway, why did the name of the certificate file change? It looks suspicious, which is why I am here.

**Comment by greyson-signal** [comment]
The `TEXTSECU.RSA`/`CERTIFIC.RSA` files are auto-generated during app signing.

I recently re-wrote some scripts for creating builds, and the auto-generated name of this file changed – **but the signature did not change**. In order to actually check the signature (which, again, has not changed) you need to use the apksigner tool – otherwise you’re only verifying the contents of a single file in the APK/zip, instead of verifying the signature for all of the contents of the APK.

In order to prevent any confusion, I updated the scripts so that the auto-generated file will use the original `CERTIFIC.RSA` filename, so future APKs will have that filename again.

I know you said that your apksigner is out of date, but I again want to emphasize that using the apksigner tool is the only way to correctly verify the signature of the entire APK.
