### ISSUE TITLE
Tapping on text with a switch works only once

### ISSUE THREAD

**Issue by Wojtaz0w** [signalapp/Signal-Android#12934]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After tapping on text next to a switch it changes its state, but after tapping on text again doesn't do anything. 

### Steps to reproduce
- tap on any text which has a switch next to it, to change its state
- tap on it again
- it doesn't change

**Actual result:** the switch doesn't change its state
**Expected result:** switch changes its state

### Screenshots
![Screenshot_20230510-095257_Signal.png](https://github.com/signalapp/Signal-Android/assets/104674625/55f90ad2-d2ca-4d1b-9843-174492eb376c)

### Device 
**Device:** Xiaomi Redmi 9
**Android version:** 13 (crDroid) 
**Signal version:** 6.19.8

**Comment by Wojtaz0w** [comment]
Video: https://youtube.com/shorts/fIMw0a1NTlo

**Comment by g1a55er** [comment]
It looks like this is due to a stale closure capturing the `state` variable in the onClick handler for the SwitchPreference items in the DSL UI framework. We already generate new onClick handlers after every state update, because we generate a new configuration after every state update, but the one that gets called is still stale. It seems like it could be fixed by either:

- Refactoring all the onClick handlers so that it does not matter if the closure goes stale. 
- Trying to modify the behavior of the DSL UI framework so that we invoke the new onClick handlers that are generated after each state update rather than the stale ones. 
- Refactoring all the Settings panels away from the old deprecated DSL framework to the new Compose based UI framework.

**Comment by Wojtaz0w** [comment]
Fixed in 6.21.0 via commit 58e48fd 😀 Thank you developers! ❤️
