### ISSUE TITLE
Security issues not replied to

### ISSUE THREAD

**Issue by tzugen** [signalapp/Signal-Android#12981]
I have reported a security problem to security@signal.org but received no reply.

I believe there exists a way that an attacker can force log out a user out of their account without knowing the registration PIN.

**Comment by clark-signal** [comment]
Hey, @tzugen. When this type of Registration Lock question has arrived in the past, the Security team typically forwards them to Support. The response from Support may have come from a different address.

Sorry about the confusion. Here's some additional information that should help answer your inquiry.

Let's look at an example of a situation where an existing user forgets their PIN:

The user registers for Signal by entering the verification code that is sent via SMS or voice to their phone number.
The user enables Registration Lock.
If the user forgets their PIN and tries to re-register, they need to wait 7 days until they can register again -- even if they are able to successfully receive the verification code.
After 7 days have passed, the user can try again.
But all of the end-to-end encrypted information on the service that's associated with the account is deleted.
This is how Registration Lock has worked since the day it was launched.

As Signal has become more and more popular, it's increasingly common for people to register for Signal whenever they get a new phone number. If someone had previously registered for Signal using that number, and if the previous owner of that number had also enabled Registration Lock, here's what happens:

Someone attempts to register for Signal.
They can receive the verification code and enter it correctly because they now own/control that number.
But they do not know the Signal PIN, so they cannot proceed.
If the person who previously owned/controlled that number is still using Signal with that number, they will immediately receive an in-app notification in Signal asking them to verify the number again.
If the existing user has only temporarily lost control of the number (e.g. in the event of a SIM swap or mistake by their cell carrier), they can verify ownership of that number at any point during the next 7 days.
But if they no longer own the number at all, the same 7-day timer that applies to forgotten PINs from the first scenario also applies here.
After 7 days have passed, the user who now actually owns and controls that phone number can register for Signal.
But all of the end-to-end encrypted information on the service that's associated with the account is deleted.
You'll notice that the 7-day timer is the same for both scenarios (an existing user who forgets their own PIN, and a new user with a new number who doesn't know the legacy PIN that was set by the previous owner of that number).

Registration Lock was never intended to let someone hold onto a number forever, even after that number no longer belongs to them.

In the same way that it wouldn't make sense to permanently prevent an existing user who forgets their own PIN from ever registering for Signal again, it also doesn't make sense to let someone permanently hold onto a number that no longer belongs to them either.

If maintaining permanent control were possible, this could negatively affect security. For example, it might let an attacker who temporarily gained control of a phone number that didn't have Registration Lock enabled turn on the feature and then maintain permanent control of that number (taking it away from the original and actual owner, and locking them out of their account even after they regain control of their number).

We hope that this explanation makes sense. Please send any other follow-up information or inquiries to [security@signal.org](mailto:security@signal.org) so that we can keep all of the threads in the same place.
