### ISSUE TITLE
Video recording on Google Pixel devices uses the wrong camera

### ISSUE THREAD

**Issue by tedgravlin** [signalapp/Signal-Android#13017]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When recording video in Signal on a Google Pixel 7a, the wide camera is used instead of the standard camera.

### Steps to reproduce
- Using a Google Pixel device with multiple rear cameras, open the camera in Signal
- Record a video

**Actual result:** Signal uses the phone's wide camera to record video.
**Expected result:** 
Signal uses the standard camera to record video.

Note: 
* The correct camera is used when taking photos. 
* This issue has also been reported by others using Google Pixel phones: https://community.signalusers.org/t/signal-uses-the-wrong-camera-for-video-recording/29241

### Device info

**Device:** Google Pixel 7a
**Android version:** Android 13
**Signal version:** 6.24.1

### Link to debug log

https://debuglogs.org/android/6.24.1/4d302dfb5796e1ad9e9b0f9e244952b6440fcacdd95ce49522e1891670388303

**Comment by Herohtar** [comment]
Just to add some detail, it seems that the wide angle camera is treated as part of the zoom level -- that is, if you drag your finger up while recording, Signal will zoom in and eventually switch to the regular/main camera and continue zooming in. You can zoom back out and it will switch back to the wide camera at the lower zoom levels.

This results in a really bad video experience because the amount of movement required to switch between zoom levels is pretty small and the transition between wide and regular is not smooth.

Furthermore, the preview only uses the regular camera, so it is quite unexpected that you suddenly jump into wide mode when you start recording.

**Comment by Herohtar** [comment]
Still an issue. I think maybe this could be partially resolved by initializing the camera to the correct zoom level so that it doesn't go to wide angle. Assuming such a thing is possible, though it seems likely since Android treats the wide angle as something like 0.9x zoom, so maybe just need to make sure it starts at 1x?

That won't fix the issue with the zoom being really sensitive though.

**Comment by tedgravlin** [comment]
I partially addressed this issue in #13411 but I still don't have it working 100%. If anyone is familiar with CameraX take a look and see if you can figure it out. Thanks :)

**Comment by tedgravlin** [comment]
Fixed with 6a65a1c!
