### ISSUE TITLE
changing to a new number fails

### ISSUE THREAD

**Issue by lilaL** [signalapp/Signal-Android#13059]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Changing to a new number fails when not using microg google device registration on lineageOS

### Steps to reproduce
- Just follow the guide: https://support.signal.org/hc/en-us/articles/360007062012-Change-Number

**Actual result:** Validation Code is not send, and screen to enter validation code just pops up for a sec
**Expected result:** Switching to new number

### Screenshots
I've attached a video below

https://github.com/signalapp/Signal-Android/assets/12436228/7a6285b0-01ec-4414-a46d-4596582c72d3

### Device info

**Device:** SM-G900F
**Android version:** 11
**Signal version:** 6.24.4
**Lineage version:** lineage_klte-userdebug 11 RQ3A.211001.001 eng.root.20221003.153622 dev-keys from https://lineage.microg.org/#

### Link to debug log

https://debuglogs.org/android/6.24.4/b25fa1bb3c0be945dd72d6ae525f330aa41b9fd4dfe99e386f142c0b4a682ed6

**Comment by clauz9** [comment]
This is still an issue in `6.26.1` and it only happens when `Google play services` are disabled or missing...

**Comment by ic2ic2** [comment]
Not sure if this is the same kind of issue. Google Play Services is active. See the issue in https://community.signalusers.org/t/changing-my-telephone-number-messed-everything-up/54474. Basically all my contacts ended up with me as 2 users instead of just the message that my phone number was changed which should have appeared. 
One user with all messages (with the initials DE originally assigned) and one with no previous messages (initials DV were assigned). My phone shows all messages and the 'new' user + what users posted in the 'new' user and my Pc shows also all messages + what users posted in the 'old' user.
Is there a solution for this ? Or should I ask all my users to archive my 'old' user, use the new one and remove and reinstall the Pc version?

**Comment by clauz9** [comment]
This is fixed for me in version `6.26.2` :+1:

**Comment by clark-signal** [comment]
Yes I believe there was a fix for this in 6.26.2. Please let me know if you're still hitting it

**Comment by LoveIsGrief** [comment]
The current released APK is 6.25.5

https://signal.org/android/apk/

![image](https://github.com/signalapp/Signal-Android/assets/2829538/e7c7ae16-eadb-4bdc-9454-f60dcdcf5304)


Would be great if the google dependency were removed from this privacy app.
