### ISSUE TITLE
Disappeared messages from last year just reappeared out of nowhere after last update.

### ISSUE THREAD

**Issue by randomfloatingshapes** [signalapp/Signal-Android#13072]
### Bug description
Just updated the app recently on PC and Android and "disappeared" messages from last year just reappeared again.  Where there had previously been only a void, it is now filled with months of conversations, including photos and attachments, on BOTH systems.  It seemed to just show up out of nowhere.  Couldn't believe what I was seeing so I checked with conversation partner and they confirmed that disappearing messages had been enabled for them the whole time and said messages are also not showing up on their app.

### Steps to reproduce
- updated app
- ???
- profit?

### Device info
**Device:** PC Desktop(Windows 10) & Android
**Android version:** 12
**Signal version:** PC: 6.26.00,    Android: 6.25.5

### Link to debug log
[debuglogPC.txt](https://github.com/signalapp/Signal-Android/files/12114968/debuglogPC.txt)

[signal-log-ANDROID.zip](https://github.com/signalapp/Signal-Android/files/12114990/signal-log-ANDROID.zip)

**Comment by nicholas-signal** [comment]
Thank you for filing a report! This is a very serious matter and my colleagues and I are trying to better understand what happened here. I have a few questions that will help us figure this out:
- What version upgrade path did you follow? Your debug logs start at the current versions (6.26.00/6.25.5) and don't contain a record of earlier versions.
- Disappearing messages are displayed with a tiny timer icon in the conversation view. Do the reappeared messages have this icon? Do recent messages?
- Could you share some of the timestamps of the messages that reappear? You can view the timestamp [by going to message details](https://support.signal.org/hc/en-us/articles/360054649071-View-Message-Details). Long-pressing a timestamp will copy it to your clipboard.
- You mentioned the other party does not see the reappeared messages; have they had disappearing messages on since day 1, or do they have non-disappearing messages before or after the disappeared ones?
- Are the reappeared messages incoming only/outgoing only/both?
- Just to be sure: these reappearing messages were received on this same device(s)? (You haven't replaced your phone/PC since they were sent?)

**Comment by randomfloatingshapes** [comment]
> What version upgrade path did you follow? Your debug logs start at the current versions (6.26.00/6.25.5) and don't contain a record of earlier versions.

If the debug logs don't say it, then I'd have no idea where to find it.

> Disappearing messages are displayed with a tiny timer icon in the conversation view. Do the reappeared messages have this icon? Do recent messages?

Recent messages do on android but the old reappeared ones don't.  Same for PC.

> Could you share some of the timestamps of the messages that reappear? You can view the timestamp [by going to message details](https://support.signal.org/hc/en-us/articles/360054649071-View-Message-Details). Long-pressing a timestamp will copy it to your clipboard.

1656538011939
1656538049378
1656538336527
1656538336527
1656538426170

> You mentioned the other party does not see the reappeared messages; have they had disappearing messages on since day 1, or do they have non-disappearing messages before or after the disappeared ones?

There were a couple non-disappearing messages both before and after the disappearing ones for both parties.

> Are the reappeared messages incoming only/outgoing only/both?

Both.

> Just to be sure: these reappearing messages were received on this same device(s)? (You haven't replaced your phone/PC since they were sent?)

Nope, same devices.


To add, the last message after the reappeared messages states that the other party just got a new phone and had to reinstall signal, so maybe that's somehow related?  Like it's literally the same day as the last reappeared message.

**Comment by greyson-signal** [comment]
Hi there, so I've dug into things, and wanted to start off by saying that there does not exist any mechanism for devices to send old messages to each other. So the idea that the messages suddenly appeared on multiple devices at once immediately makes me thing that things may not be what they seem. Instead, I have a guess as to what may have happened:

I don't know what your chat timer is set to, but let's say it was set to 1 week. You may have had a lot of messages that were sent almost exactly 1 week ago, and maybe not a lot of messages sent this week otherwise. This would result all (or almost all) of the messages being deleted since you last viewed the chat, revealing earlier messages in the chat that you might not have realized was there the whole time. In other words: those messages didn't "reappear", they were always there -- you just usually had a bunch of other messages below them and hadn't seen them in a long time.

As to why your chat partner doesn't have the messages? As you said, the message right below that was the "safety number changed" message indicating that your chat partner got a new device. I'm guessing they didn't do a device-transfer or backup restore, and so they just don't have any messages from before they switched phones.

Do you think that's a reasonable explanation?

**Comment by randomfloatingshapes** [comment]
Seems quite reasonable.  Maybe I'm just going crazy.  In this case, I hope I am.  Thanks for taking the time to look into it.
