### ISSUE TITLE
Can no longer insert GIFs from Gboard

### ISSUE THREAD

**Issue by Herohtar** [signalapp/Signal-Android#13092]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can no longer insert GIFs from the Gboard keyboard. This was previously possible up until just today or so.

### Steps to reproduce
0. Use the Gboard keyboard
1. Open a chat
2. Tap the text entry box
3. Use Gboard's GIF search
4. Tap a GIF to add it

**Actual result:** No image is inserted and a toast appears that states, "Signal does not support image insertion here"
**Expected result:** GIF is inserted correctly

### Device info

**Device:** Pixel 7 Pro
**Android version:** 13
**Signal version:** 6.27.10

### Link to debug log

https://debuglogs.org/android/6.27.10/290c096bbcb45239c3c5a5f620587b9501ecb2723b8b7cd81b28397939bd3e9e

**Comment by nCrazed** [comment]
Experiencing same problem since the day when I last updated the Signal app to 6.27.10

Problem seems to be related to the most recent message in the conversation. So far I've been able to insert a GIF if the most recent message in the conversation was sent by my **and** from the same device that I am using to insert the GIF.

If the most recent message is from someone else, or from me, but sent from the desktop client, I see the error

**Comment by nCrazed** [comment]
I also have a friend who reports encountering the same problem with a Samsung keyboard

**Comment by rat1402** [comment]
confirming having same problem as described above (Pixel 7 Pro, latest version of Signal app, using GBoard).

**Comment by rat1402** [comment]
confirm that it is working for me now. thanks for fixing.

**Comment by Herohtar** [comment]
Can confirm it seems to be working for me as well. Thanks!
