### ISSUE TITLE
Did Donation with the App and get no badges

### ISSUE THREAD

**Issue by M-um-p-i-t-z** [signalapp/Signal-Android#13100]
and support doesn't response one of my 3  e-mails!

For over 10 years I now use the app Signal and have advertised everywhere.  
But the times are over, not only that the support no longer responds to e-mails, no, I also had to determine that now cloudflare servers were used exclusively for media shared with Signal. 
You will notice when you can no longer receive images via the home Wi-Fi network, because all IP addresses purchased from cloudflare are blocked there.

Signal has probably become too big and the NSA is just building its backdoors.
That's it and thanks for the fish...42

Decentralized is the keyword. I hope Mr. Snowden will take back his recommendation.

**Comment by M-um-p-i-t-z** [comment]
Doing Nothing! Like a boss!

**Comment by alex-signal** [comment]
There's an issue template which you did not follow, and the debug logs for what happened here would have expired by now (Donation logs last about 21 days). From the original message, it appears you only came here to air grievances and criticise Signal, which doesn't really make us want to help you. Furthermore, it sounded like you had uninstalled Signal, so we believed that the issue was moot.

If you do end up trying to donate again and the same thing happens, please feel free to open a new report and post a debug log. Try to also keep the ad hominem to a minimum, because it's hard to take your report seriously otherwise.
