### ISSUE TITLE
Signal crashes right after starting the app

### ISSUE THREAD

**Issue by simonschaufi** [signalapp/Signal-Android#13128]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Right after I start the app, it crashes and closes.

### Steps to reproduce
- use latest version
- Start the app

### Device info

**Device:** Samsung Galaxy A10
**Android version:** 11
**Signal version:** 6.29.2

**Comment by simonschaufi** [comment]
[signal-log-1692588073144.zip](https://github.com/signalapp/Signal-Android/files/12391273/signal-log-1692588073144.zip)

**Comment by cody-signal** [comment]
Thanks for the logs!! We think this is fixed in 6.30.2 which should start production rollout soon. But if you want, can join the beta and get the update sooner.

**Comment by j0057** [comment]
> 6.30.2

I have 6.30.4 on Android and Signal is crashing on startup, also after clearing the cache, also after clearing the storage and setting up my Signal account. I sent a crash report to Google infrastructure containing a stack trace.

**Comment by greyson-signal** [comment]
@simonschaufi 
> What does "Should not occur in a non-PNP world!" mean and why does this happen?

There's a certain chat event that should only be inserted if the user is using the unlaunched phone number privacy feature. We were trying to insert that event in some niche situations due to a logic error. I've corrected that error. This is a very complicated area of the codebase, so to explain more would require me to write pages of context which I don't particularly want to do, so that's the gist of it :)

@j0057
> I have 6.30.4 on Android and Signal is crashing on startup, also after clearing the cache

If you're ever able to get logs, please open a separate issue. Given we're not seeing the crash that was reported by OP in our crash console anymore, I'm guessing your hitting something else.

**Comment by j0057** [comment]
@greyson-signal I opened #13140

**Comment by BeHappy2021** [comment]
@greyson-signal I have also commented on [#13140](https://github.com/signalapp/Signal-Android/issues/13140) and added output from logcat. I've downgraded as far as 6.26.5 and upgraded as far as 6.31.2 beta and all do the same.

**Comment by simonschaufi** [comment]
Please don't mix 2 problems in one issue. This issue is solved with the latest beta. Therefore I close this.
