### ISSUE TITLE
Slow send and receive

### ISSUE THREAD

**Issue by MaximosPr** [signalapp/Signal-Android#13134]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I experience slow send and receive times in every kind of message with every signal user. It happens in every network I have available which are: cellular, home network and a café. It usually takes more than 20" to send and receive. I submit my debug log below.

### Link to debug log

https://debuglogs.org/android/6.30.4/c4db103bbfb35073f29e3d00cc0eb629ca5588f7f391b5c3404dd3a21fff48bc

**Comment by cody-signal** [comment]
Whoa, yeah, dang, wow, ouch, woof, yeesh.

Sorry about this, we'll see if anything can be done.

**Comment by mrliuws** [comment]
Hi, same issue for me too. Takes up to 10 seconds to send text messages. Compared to other messaging apps which is instantaneous.

Debug log: https://debuglogs.org/android/6.32.4/000e9f713bffa4f92d236f4f8ece228b4c6c954c6d7359adffcee367b5133de2

**Comment by 0xConstant1** [comment]
Same thing here, I have a really big database which is I guess why most people don't experience this (probably 15gb+ backup on a single conversation). Sending and receiving is extremely slow as of lately, I'm on the beta version. It was a lot better in the past after some revolutionary update but now it's extremely sluggish again to the point it's almost unusable because of how frustrating the delay is.

**Comment by mtzea** [comment]
I have the same issue and also it seems some messages are being sent faster than others which leads to disruption in message order. For example when sending four messages, the last message may be sent first and displays at the receiver's device (when it finally arrives) as first

**Comment by tati1454** [comment]
I'm having the same issue, I don't have a lot of experience in android development, but I can try to investigate a little.

**Comment by 0xConstant1** [comment]
@cody-signal Here are both debuglogs from my device and my wife's:

https://debuglogs.org/android/6.36.3/a1f6e17d0343003a4ed52d0231a3f774e980c9b660408e1bbae047d25f0da97b
https://debuglogs.org/android/6.36.3/88a93c97494cab312d5aa78336195bf6c782a7fa38e33c673c085a15f469944d

I hope they can prove useful, at its core signal is a messenger and I think it should do that flawlessly before anything else! I love signal but it's been real painful to use because of how slow messages are exchanged, however I'm not switching because i want it to succeed :) I hope they can be of help, thank you for the work you're doing.

**Comment by 0xConstant1** [comment]
@cody-signal Unfortunately it's pretty consistent throughout the whole day so I wouldn't be able to point to a specific message, thanks again

**Comment by MaximosPr** [comment]
@cody-signal  if you need more debug logs I can submit a newer one of mine and also my partner's.

**Comment by SilverMight** [comment]
Also getting this for conversations that have a large history (10gb~ full backup size)
