### ISSUE TITLE
6.30.1 & above crashes on startup

### ISSUE THREAD

**Issue by infinity0** [signalapp/Signal-Android#13144]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

### Bug description

See debug log below.

### Steps to reproduce

- start the app

**Actual result:** crashes
**Expected result:** doesn't crash

### Device info

**Device:** OnePlus 8T KB2003
**Android version:** 13 LOS 20
**Signal version:** all versions 6.30.1 - 6.31.2

### Link to debug log

~~~~
09-02 01:57:33.222 26353 26353 E AndroidRuntime: java.lang.IllegalArgumentException: Failed to resolve SessionToken for ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService}. Manifest doesn't declare one of either MediaSessionService, MediaLibraryService, MediaBrowserService or MediaBrowserServiceCompat. Use service's full name.
~~~~

### Fix

https://github.com/signalapp/Signal-Android/blob/c71456444f43a514d4d6d01dca775d374bfb332d/app/src/main/AndroidManifest.xml#L1136

"Use service's full name." like it says in the exception message.

**Comment by nicholas-signal** [comment]
We are unable to reproduce this on any of our devices, including a Pixel 2 with LineageOS 20. Is it possible you have a setting that disables the app's ability to scan its own manifest for components?

**Comment by infinity0** [comment]
Bug still exists on 6.32.4 beta.

I'm using LineageOS 20 microG edition, here https://download.lineage.microg.org/

I'm also using XPrivacyLua and denying the ability for Signal to get the list of installed applications.

Do other applications need to "scan its own manifest for components?" If not, why does Signal need to? I haven't experienced this sort of crash with other applications. Some parts of apps might stop working when "get installed applications" is blocked, but the whole app doesn't generally crash.

**Comment by infinity0** [comment]
> ### Fix
> 
> https://github.com/signalapp/Signal-Android/blob/c71456444f43a514d4d6d01dca775d374bfb332d/app/src/main/AndroidManifest.xml#L1136
> 
> "Use service's full name." like it says in the exception message.

This didn't work.

A workaround for anyone else that runs into this is to:

1. comment out all of `createMediaControllerAsync` in VoiceNoteMediaController.kt
2. `./gradlew assembleDebug`
3. Install CorePatch LSPosed module to disable signature checking & restart your phone
4. `adb install ./app/build/outputs/apk/playProd/debug/Signal-Android-play-prod-arm64-v8a-debug-6.32.4.apk`
5. Disable CorePatch LSPosed module & restart your phone, it's dangerous

Voice notes won't work but I wasn't using them anyway and at least Signal doesn't crash needlessly.

**Comment by infinity0** [comment]
> Voice notes won't work

Video playback still works even with my workaround (of patching out the offending code). Can you guys not use the same method as that, or use it as a fallback?

**Comment by infinity0** [comment]
11cfe5ee824495703b54b74a89ab2b0c76e19afb is the commit that causes this. Unless Signal wasn't "scan[ning] its own manifest for components" before this commit, I don't think that's the problem.

**Comment by nicholas-signal** [comment]
The relevant block of code is here: https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/session/src/main/java/androidx/media3/session/SessionToken.java#L108-L135

You can see it tries, using `PackageManager`, it queries for the declared components that match the [hardcoded the intent filter](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L158), an intent filter that [we match precisely](https://github.com/signalapp/Signal-Android/blob/v6.32.4/app/src/main/AndroidManifest.xml#L1147).

It would seem that in your case, it the query returns an empty list and proceeds to throw the exception you've reported.

As best I can tell, our implementation follows the [documentation](https://developer.android.com/reference/androidx/media3/session/MediaSessionService) exactly. I am happy to review any enhancements or bugfixes you can find.

> Unless Signal wasn't "scan[ning] its own manifest for components" before this commit, I don't think that's the problem.

This is indeed newly introduced code. The commit you've identified was a rewrite to adopt the new modern `androidx.media3` library, which we were not using previously (because it did not exist). As a result, we were not calling the constructor of `androidx.media3.session.SessionToken`. You can read more about media3 here: https://android-developers.googleblog.com/2023/03/media3-is-ready-to-play.html

If I were able to reproduce this, I would use a debugger to step through the `SessionToken` construction and see how the behavior differs on the affected device vs other devices.

**Comment by infinity0** [comment]
Thanks for the details. Unblocking PackageManager.queryIntentServices (API 33) in XPrivacyLua fixes the issue, it's a subset of its "get installed applications" category.
