### ISSUE TITLE
Source isn't fully open / builds aren't fully reproducible

### ISSUE THREAD

**Issue by t4moxjc7** [signalapp/Signal-Android#13154]
Its not possible to get the full source code of signal (including dependencies), and produce an APK that is [byte-for-byte](https://reproducible-builds.org/docs/embedded-signatures/) the same as the official download. This means it is not possible to read the source code and make sure new updates are not compromised, and third parties can't publish useful build hashes for each new commit. Partial source code and partially-matching builds have some use, but its limited.

**Comment by greyson-signal** [comment]
Would you mind elaborating? 

The Signal source itself is certainly available. I'm guessing you're concerned about particular dependencies? Some dependencies are out of our control, like some Play Services libraries. Unfortunately if you want to be able to receive notifications reliably on Android, that's just something you've gotta do. If there's any dependencies in particular you're concerned about, I'm happy to hear specifics.

Regarding the criticism of "byte-for-byte" matching, I do believe we meet that description. We have our own private signing key, so other people will never be able to replicate that, but we take the second approach in the link you provided for our builds: "Ignoring signatures". As noted in that section, we provide a special comparison tool, which is indeed easy to audit. It ignores the signature, as well as another file that are non-deterministic parts of the android build system that are beyond our control (all listed at the top of the file with comments). 

You can read more [here](https://github.com/signalapp/Signal-Android/tree/main/reproducible-builds), and see the apkdiff source [here](https://github.com/signalapp/Signal-Android/blob/main/reproducible-builds/apkdiff/apkdiff.py).

**Comment by greyson-signal** [comment]
You don't need to exclude the libraries to make it deterministic. It's deterministic right now -- you can follow the instructions and you'll see that the contents of the apk are the same. The point of being deterministic is to make sure that the APK we upload to the store matches the APK that you could build from source. Just because you can't see the source of the non-free dependencies doesn't mean you can't verify that it matches.

I think the apkdiff tool we provide is very readable/inspectable and satisfies our goal. I appreciate the suggestions but we won't be making any changes here. Thanks!
