### ISSUE TITLE
Cannot make calls while connected to VPN: ResponseStatus 403

### ISSUE THREAD

**Issue by ThePhoDit** [signalapp/Signal-Android#13209]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am not able to make calls when connected to a VPN service. Logs say there is a 403 response code.

### Steps to reproduce
- connect to a VPN service
- open Signal
- attempt to make a voice o video call to a contact or group

**Actual result:** Call screen "crashes" and toggles camera enabled/disabled every time to click on the start call button.
**Expected result:** Call starts.

### Device info

**Device:** Google Pixel 6a
**Android version:** GrapheneOS Android 13
**Signal version:** 6.35.3

### Link to debug log
https://debuglogs.org/android/6.35.3/224e2c6f5540ebd4aada1b279cc496e35df64bfb197140d6114c39314dc8aafd

**Comment by ThePhoDit** [comment]
It seems this only happens when the relay calls option is disabled. I think this might be the VPN blocking certain ports when trying to establish a P2P connection with call recipients?

If someone can confirm this I will close the issue as it would not be anything Signal can handle.

**Comment by churchthecat** [comment]
Same issue pixel 3a XL grapheneOS, signal-foss. Signal did not ring for me or other end until I enabled relay when on VPN .

**Comment by nicholas-signal** [comment]
Hello,

We would suggest testing with other VPN providers, as many people both inside and outside Signal successfully make and receive calls on VPNs.

Thanks!

**Comment by churchthecat** [comment]
Changing protocol works as well . seems to only happen on wireguard

**Comment by ThePhoDit** [comment]
Changing locations did the trick for me in the end, even on Wireguard

**Comment by AngelouDi** [comment]
What do you mean "Changing locations"? Facing the same issue here.

**Comment by ElSamhaa** [comment]
Signal won't ring if I'm connected to my self-hosted wireguard VPN. The interesting thing is I've only have my WG client only route a certain private IP with subnet 32. Besides, I have the split tunneling enabled only on my termux app, so it shouldn't affect Signal whatever the cause is!

**Comment by GigabyteProductions** [comment]
Please reopen this issue. I think @ElSamhaa is observing that *split tunnels* are the cause of the issue.

In my case, it is [OpenVPN for Android](https://f-droid.org/packages/de.blinkt.openvpn), that I've set up specifically only to route an RFC1918 private IPv4 subnet and an RFC4193 private IPv6 subnet. There are no default routes or DNS overrides through the VPN. This is purely a "split tunnel" by classical definition, in that the VPN adds supplemental routes to the routing table rather than hijacking all internet connectivity, not to be confused with Android's [VPN app exclusions](https://developer.android.com/reference/android/net/VpnService.Builder#addDisallowedApplication(java.lang.String)) functionality that several people call "split tunneling".

For me, Signal appears to be failing to make *new* connections after the VPN is connected. More specifically:
1. Signal failed to initiate/receive calls when connecting the VPN after WebSocket was already established, but messaging still worked
2. Signal failed to send/receive messages after killing/reopening the app

Furthermore, this same behavior regarding *split tunnels* was also identified 6 years ago; the user claims that switching to a *full VPN* configuration allowed Signal to make calls. See: https://www.reddit.com/r/signal/comments/eshchu/comment/ff9yt0u/

I was able to work around the issue and get Signal to work with my split tunnel VPN active by excluding Signal in the OpenVPN profile's "allowed apps" settings... This may also become easier to configure for other VPN apps in [Android 17](https://android-developers.googleblog.com/2026/03/the-third-beta-of-android-17.html).

Regardless, I think this is a bug in Signal as it is the only app on my phone that behaves differently when my split tunnel VPN is active.

**Comment by GigabyteProductions** [comment]
Sorry, I just realized that I forgot the original context of this issue ("Logs say there is a 403 response code"). Should a new issue be opened specifically about split tunnel VPNs?

**Comment by cody-signal** [comment]
Please open a new ticket and provide a debuglog so we can see which part of calling breaks down so we know which part to investigate.

**Comment by GigabyteProductions** [comment]
I have opened #14690 regarding the split tunnel VPN use case
