### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by csoghoian** [signalapp/Signal-Android#1321]
I tried to send a push message today to someone that I've exchanged push messages with in the past.

Rather than showing a blue text bubble, the message I sent was displayed in a green bubble, with a warning below it, "Error sending message". There was also a big red warning triangle on the left hand side of the screen.

What was missing, though, was any useful information letting me know what exactly failed.

It turns out that my contact had decided to stop using textsecure. The only way I figured this out was by asking him.

Is there a way to improve this message? It is quite possible that people will try out textsecure and then stop using it. This failure message is not very helpful.

**Comment by gordon-morehouse** [comment]
Since there are multiple dupes of this UX problem and since other error messages in the Android app are equally unhelpful ("Can't play this video," "Sorry, there was an error setting your attachment") should this be a clearinghouse bug for error messages which contain insufficient information for end users? The bug was opened by @csoghoian almost three years ago, the UI has since changed, but there are still plenty of error messages in need of improvement.
