### ISSUE TITLE
Deadname used as default name (Preferred Name not available)

### ISSUE THREAD

**Issue by gabefair** [signalapp/Signal-Android#13236]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal fails to present changed name in profile of known contact.

### Steps to reproduce
- Inside the phone's default contact app, create a new contact
- Allow signal to access your phone's contact list
- message this new contact for the first time on signal
- Make a mental note of the signal profile name on this contact
- Have the new contact change their name on their profile
- Chat history is notified of the name change 
- Go to the signal profile details page of this contact. 
- Note how the old name is still displayed

**Actual result:** The contact name does not change. Defaulting to the phone's contact name.
**Expected result:** The profile details page should show the name change.

This is a problem when the name change was a long time ago, or in large group chats where nobody is keeping close watch of the name changes.

### Screenshots
![image](https://github.com/signalapp/Signal-Android/assets/2096785/0c5d4be6-955c-479c-a870-8c3c4ddcdff9)
![image](https://github.com/signalapp/Signal-Android/assets/2096785/9de60861-9c76-4f57-bd9e-aa7657aaff6e)

**Comment by cody-signal** [comment]
Can I repeat the problem back to you to make sure I understand?

1. Have a contact (Alice) in your phone OS address book
2. Message them on Signal, shows as "Alice"
3. Alice changes their Signal profile name to "Alice 2"
4. You still seem them as "Alice" because that is what is in your address book.

If that is a correct summary of what you're seeing, then it is working as designed, address book names always take precedent over a profile name in your local view.

**Comment by gabefair** [comment]
ok, sounds like this isn't a bug but a feature request then. Sorry about that. 
It would be helpful to see both names in the profile page. Or a setting to choose which one Signal defaults to.
