### ISSUE TITLE
backup file not found on Redmi 4A with Android 6.0.1

### ISSUE THREAD

**Issue by rubo77** [signalapp/Signal-Android#13234]
Signal version:** Signal 6.36.5

I uploaded the 3GB `signal-***.backup` file on my device into the the folder "Signal" on the root of my device. It is there if i use the filemanager in the device, but when i try to restore from this backup and Signal asks me to select the file, i can navigate to the new `Signal` folder but the folder is empty.

How can I restore from this backup? 

the Backup is from 2022-09-16, maybe old files are not shown in the folder any more?

**Comment by cody-signal** [comment]
Can you provide a debuglog? Settings->Help->Debuglog and post the link here?

**Comment by rubo77** [comment]
here: 


https://debuglogs.org/android/6.36.5/125324bb9e74443cb0ea0832d86a2c347181077f60573d39c574f04aac794e0e

**Comment by rubo77** [comment]
I already had to start new now with an empty history, so the bug should be somewhere visible at the start.

But if there is a solution, I would love to start Signal again with the backup import

**Comment by cody-signal** [comment]
Thanks, given you are on Android 6 I'm wondering if something is getting messed up with the detection.

If you make a "Backups" directory inside the "Signal" directory, and then put your backup file in there, that may do the trick? On older platforms the backup can be detected automatically if it's in `Signal/Backups/<***>.backup` when you are at the welcome screen and then tap the large blue button instead of the smaller text only one.

It should also still work with the picker, but I don't know why it doesn't, so this is another option.

**Comment by rubo77** [comment]
> If you make a "Backups" directory inside the "Signal" directory, and then put your backup file in there, that may do the trick?

no luck either

**Comment by rubo77** [comment]
> On older platforms the backup can be detected automatically if it's in `Signal/Backups/<***>.backup` when you are at the welcome screen and then tap the large blue button instead of the smaller text only one

this works!

thx
