### ISSUE TITLE
Removed contact is never shown in the new conversations list again

### ISSUE THREAD

**Issue by julianfairfax** [signalapp/Signal-Android#13248]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a contact in your phone's contacts has Signal, Signal shows them in the new conversations list.

When you have a conversation with that person, the contact is added to your Signal contacts.

To remove a contact from your Signal contacts, you first have to remove it from your phone's contacts.

However, when you do this, and remove the contact from your Signal contacts, it will never be shown in the new conversations list again, if you add it back to your phone's contacts.

### Steps to reproduce
- Add a contact who has Signal to your phone's contacts
- Refresh your new conversations list in Signal
- Have a conversation with the contact
- Remove the contact from your phone's contacts
- Remove the contact from your Signal contacts
- Add the contact back to your phone's contacts
- Refresh your new conversations list in Signal

**Actual result:** The contact is not shown in Signal's new conversations list, despite being in the phone's contacts and having Signal
**Expected result:** The contact should be shown in Signal's new conversations list, because it's in the phone's contacts and has Signal

### Device info

**Device:** Google Pixel 6a
**Android version:** 14
**Signal version:** 6.39.1

### Link to debug log

https://debuglogs.org/android/6.39.1/60d1347718bc889cd7d7a05b2ba88e20977d4c8ac51217188d41c2da446c300f (immediately after refreshing the new conversations list)

**Comment by greyson-signal** [comment]
When you hide a contact, you have to manually enter their number to start a chat with them again.

**Comment by greyson-signal** [comment]
Ironically, in order to be able to effectively hide a contact, you have to keep a record internally of what that contact is. Same thing with blocking.

And with hiding you especially can't just "delete" all knowledge of a contact, because you may still have interactions with them. You could have shared groups, and they could be sending you messages. You may have a pre-existing chat and want to be able to refer to messages they sent you in the past.

The goal of this feature is to stop showing the contact in your contact list without blocking them. Sounds like you want it to be something that it's not.
