### ISSUE TITLE
Username can't be set

### ISSUE THREAD

**Issue by M3DZIK** [signalapp/Signal-Android#13266]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No matter what I type into this field, it always shows that the username is taken.

### Screenshots

![signal-2023-11-18-214152](https://github.com/signalapp/Signal-Android/assets/87065584/64d3cf97-7df4-4030-b8e3-863131da0b9b)

![signal-2023-11-18-214154](https://github.com/signalapp/Signal-Android/assets/87065584/ac616bce-d67e-4360-afbf-62b53a5bcd7c)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 13
**Signal version:** 6.41

### Link to debug log
https://debuglogs.org/unknown/0.0.0/55a842b4358fedeb911fa9cc734abf7c38cede942af3bead8beec301fdfa343b

**Comment by greyson-signal** [comment]
Looks like you tried to make a custom build to enable the username feature on a production release? (1) We don't allow usernames on production, we're still only testing this in staging. (2) I _strongly_ recommend you do not use this build on production in general. There are certain important flows that require that the person _receiving_ your message also have pnp-capable builds. Otherwise you could have a very bad time (missing messages, encryption errors, etc).

I know people are excited for usernames, but they'll come to production in due time :)
