### ISSUE TITLE
Crash & reboot to recovery (Android 11) upon receival of Pixel 7 screens & photos /w specific ICC profile

### ISSUE THREAD

**Issue by hondogitsune** [signalapp/Signal-Android#13287]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unspecific crashing over the last 14 to 21 days that could be isolated down to receiving images from a Pixel 7 user that have a Google Inc. embedded ICC profile. Stripping the colour profile with EXIF removal tools made the images not trigger their crashing behaviour.

### Steps to reproduce
- App running in background
- your friend sends you a JPEG with the below attached Google Inc. ICC v4.3.0 colour profile
- for testing if the rest of the JPEG matter it was swapped to a fox and the profile was attached
- it was observed the JPEG contents don't matter and presence or absence of the colour profile matters

[test.zip](https://github.com/signalapp/Signal-Android/files/13466563/test.zip)
[test2.zip](https://github.com/signalapp/Signal-Android/files/13466564/test2.zip)
**There is a catch: The image must be new and have never been generated into a preview thumbnail before.**

**Actual result:** Upon receival, screen flickering, complete and absolute loss of control via hardware keys, the device will flicker until death which means full shutdown to recovery mode. The device is now completely off the net and the recovery ROM runs.
**Expected result:** You receive an image and you scream in glee, if everything was working as it should be.

### Screenshots
https://archive.org/download/signalbugissue/output1.mp4 
https://archive.org/download/signalbugissue/output2.mp4

**Watch both videos please!**

![color-profile-bug](https://github.com/signalapp/Signal-Android/assets/75497157/9811b00d-2ca6-4f89-83a8-69fe5301c8ef)

### Device info
**Device:** Xiaomi Redmi Note 8 Pro 128GB mineral grey
**Android version:** Android 11
**Signal-Android version:** 6.40.5 (latest as of day of report)
**Signal-Desktop version:** 6.39.1 (latest as of day of report)
![grafik](https://github.com/signalapp/Signal-Android/assets/75497157/6d3cf6ed-918a-41f8-8898-3d67216f3024)
![grafik](https://github.com/signalapp/Signal-Android/assets/75497157/85bb3229-ec97-4046-8933-56ae3e5961b1)

### Link to debug log
Not applicable, there were no errors at the timestamps when the crash happened.

## Probably a new variant of an old bug that affected an older and different colour profile on Android 10
This is a completely different ICC colour profile. The behaviour though is exactly the same on the Android 11 OS that was supposed to fix the bug. Google's patch only handles the old colour profile but still breaks on the new one. These files are in the wild, plenty. I crashed a lot because of active group chats over the last couple of weeks. App running in background.
All of this started to happen after recent Signal updates.
In the past screens and photos with the ICC did not crash me.

Tests:
2020 (old) JPEG ICC bug -> confirmed fixed on Android 11 and 12.
This new bug (2023) report for a different JPEG ICC bug -> only crashes Android 11 on receiving.
Setting system notifications to not contain name or message content has no effect.
Disabling automatic downloading of images prevents crashes.

Theories:
Happens on generating the thumbnail only for new images.
Why is still a thumbnail generated when notifications are set to not contain name or message?
Likely regression bug in Signal since the Pixel 7, Android 13 and the colour profile far from are anything but new.
I suspect notifications in Signal are botched because the notifications trip over them even when privacy of content is on.

Guess I can trash my Android 11 (2022) phone because disabling preloading of images is too cumbersome, even if it is better than having your phone rebooted 40 times a week because other people have new devices that can crash me.

## Footnotes about the old bug

Reading material about the old Android 10 JPEG ICC (profile 2.1) bug that likely was never fully fixed in Android 11 for other ICCs (profile 4.3.0):
https://riverloopsecurity.com/blog/2020/07/android-systemui-icc/
https://issues.skia.org/issues/40041653
https://twitter.com/evowizz/status/1267165374262411270
https://twitter.com/evowizz/status/1267165376128958465

An old demonstration of the issue:
https://twitter.com/seb_mc2/status/1266968321733296138
https://video.twimg.com/ext_tw_video/1266967806635126784/pu/vid/720x1280/7XR_OWsbhu_GKCW0.mp4?tag=10

This is **not** a feature request, but this nonsense would not even happen if the ICC profile would be stripped by the app itself. Why can we NOT have an option to have EXIF and ICC data removed upon sending and receiving? In a public group keeping EXIF would also leak GPS metadata.

There are many good arguments to treat images as malicious and sanitize or check them for junk data that can harm the OS:
https://blog.cloudflare.com/uncovering-the-hidden-webp-vulnerability-cve-2023-4863/

**Comment by hondogitsune** [comment]
@greyson-signal
@cody-signal

**Comment by hondogitsune** [comment]
![grafik](https://github.com/signalapp/Signal-Android/assets/75497157/4b824d3e-3672-4d0a-845c-9199199f736d)

Everything I need to know right now. The people working on the android app are heroes, but they could need a little help maybe, dear Signal President M. Whittaker?

**Comment by hondogitsune** [comment]
![grafik](https://github.com/signalapp/Signal-Android/assets/75497157/4d4f4681-d7a5-4f30-bb05-3eb64f25d969)
Everything I need to know right now. The people working on the android app are heroes, but they could need a few more co-workers, dear President @Meredith-Signal ?

**Comment by greyson-signal** [comment]
Can you tell me more about how viewing these images works on this device? Can you view it in other apps, your phone gallery, etc? I'm personally trying to reproduce this on a stock Android 11 emulator and can't. I'm not sure if this is related to Xioami's specific Android 11 release, but I can try to get the specific model to see.

> Setting system notifications to not contain name or message content has no effect.

This in itself indicates a bug, we shouldn't be generating thumbnails for stuff we won't show. This is being fixed in 6.41.3.

> but this nonsense would not even happen if the ICC profile would be stripped by the app itself. Why can we NOT have an option to have EXIF and ICC data removed upon sending and receiving?

The android app re-encodes all outgoing images so as to strip off EXIF data (I imagine ICC too, but I'd have to do more research on that), so that should be happening -- I'll investigate what desktop is doing. Regardless, the receiving-side needs to be able to handle any data.

> All are equal but some are more. Signal.org needs to give the heroes of the android repo more co-workers to ease the workload.

Heh, don't mistake commit count as a proxy for work being done :) Android favors meatier commits, we're doing fine :p As far as not having a commit for two weeks, that's because of American Thanksgiving, holdups in the Play Store, etc. We publish commits on a per-release basis and have plenty of changes slated for release.

**Comment by hondogitsune** [comment]
Okay I try to reply to everything in your post, if my attention manages:
> Can you tell me more about how viewing these images works on this device?
I don't have to interact with the message or the image to trigger a crash. Did the 2 video I record help a bit? They should show nicely what I experience IRL from my perspective as user.
> Can you view it in other apps, your phone gallery, etc?
Oh yes, the media itself is safe to interact with as much as I want after the crash. The automatic download and notification phase is the spicy part. Which is why I only manually download on phone and limit myself to Signal Desktop now.
Maybe a small recap:
notfications OFF + media download ON = crash
MINIMAL notifications (sender/content omitted) + media download ON = crash
image download is OFF + FULL notifications = NO crash
REMOVED ICC + image download is ON + FULL notifications = NO crash
There is clearly a causal link between the receival, notifications and ICC presence.
Without a debugger or break points, for me this is guesswork and frustrating try&error.
> The android app re-encodes all outgoing images so as to strip off EXIF data 
Indeed there is no EXIF, just ICC of a Pixel 7 with Android 13, for the latter I vouch as the hex editor shows the presence of a profile that is not from my device. My own screenshots&photos on Android 11 have a way older ICC.
Do I blame changes to the app or to Android's 11 notifications backend? The Pixel 7 and Android 13 are not that new, the problems are only since ~1 month at a rough estimate. It has to be a change in the code of *any* involved Signal or Android code.
Blaming the (agreeable lousy) Xiaomi phone is hardly possible, as the device is more or less dead since 1.5 years without stock ROM updates. All is vanilla. We owners are considered EOL.
> Heh, don't mistake commit count as a proxy for work being done :)
No offense intended, hence the nod to the good work. You are still flooded with issues by the sheer amount of Android users.
Based on store reviews the disparity is 2.4 million : 300k for Android vs iOS.
> not having a commit for two weeks, that's because of American Thanksgiving
I feel you, we don't have that and I know how important it is. Especially that you have only a few weeks until Christmas right after. It's just that on mere donations and the smallest staff in big tech it is a miracle you operate a non-profit 501(c)(3) org without becoming incapacitated.

**Comment by hondogitsune** [comment]
@Broswons
Your message is excellent. Receiving confirmation from someone with both a different model and Android version is good confirmation, and you can also help your friend by telling him to disable automatic download of images. It is painful to manually click them, but at least you are not put in something worse than airplane mode.

**Comment by greyson-signal** [comment]
Ok, based on what you're describing, it seems like some recent changes to how we generate notification thumbnails is triggering this system crash (haven't gotten a repro yet on our end). I do want to point out that we simply use system-standard image decoding tools, and nothing an app does should be able to crash the entire phone. This is very much a problem with the OS, but it appears to be a problem we should be able to circumvent if it's true that this issue just started recently.

Looks like both affected phones are older Xiaomi's, I'll see if I can get one and see what's happening.

**Comment by hondogitsune** [comment]
> I do want to point out that we simply use system-standard image decoding tools

Which is why I was worried it could be a similar bug as with the old ICC problems that got fixed, but maybe partially only.
Google, if I look into the news, cannot code. They just outsource via bug bounties.

**Comment by Broswons** [comment]
**@hondogitsune**
Well, I was just trying to be most thorough as possible, and even chronologically most detailed, because I am aware how much that can help in resolving any software bugs, errors, etc., and especially when something is rare & serious like now, that even give as this terrible **Android Recovery mode** screen bug nightmare to all here.  :(

I am also aware that all this great posts here, will quite possible read many IT Tech layman persons Worldwide, which are also in a huge panic by seeing this strange, black **Android Recovery mode** screen and are unable to boot normally their mobile phones..., and that in that same screen they can so seriously and so extremely easy, completely mess up their mobile phones, especially in a light if they really do not know for e.g. what **Factory data reset** operation actually do, so I was also most detailed for all those people...

Now, I am also posting this of my second post here now, because today I found out that now even one of my working colleague on my job has that same **Android Recovery mode** screen bug, and he also has..., well well..., **Xiaomi Mi A2 Lite** mobile phone model, and with **Android 10 OS** on it!  :)  :(

He has this **Android Recovery mode** screen bug for last 7 days on this mobile phone, he says to me today..., but he was initially thinking that this bug might happens to him, because maybe his old mobile phone battery maybe malfunctioning here..., but then maybe because he uses an old version of **NOVA Launcher app.** on this of his mobile phone...

However, he temporary disable **NOVA Launcher**, and among any other 3rd party software which he installs and it's running just after or throughout the Android OS boot process and launching (the **Earthquake Network Pro** app., **Data Monitor** app., & **Transparent clock & weather** app.), well everything except **ESET Mobile Security** app. here which he did not touch, and the **AdGuard VPN** and **AdGuard AdBlocker** for Android apps, that he leaves normally engaged just as they are on his mobile phone.
... And even after all this disablings which are just been mentioned here, the **Android Recovery mode** screen bug still happens to him, and he also have **Signal** app. for Android **v6.40.5** installed on his mobile phone for years by now.

So, I told him today that he is certainly not the only one anymore, that has this **Android Recovery mode** screen bug. :)  :(


And at the very end, I please need your confirmation, if I correctly understand you, that you advice for this temporary bug circumvent action, is to go via **Signal** app. for Android, then via **3 dots** on the upper right screen -> **Settings** -> **Data and storage**:

**a) When using mobile data**:
Just temporary remove check-mark for **Images** option here.

**b) When using Wi-Fi**:
Just temporary remove check-mark for **Images** option here.


Once more thank you for all the help and best regards!

**Comment by hondogitsune** [comment]
@greyson-signal 
Thunderbird just synced this very minute and I saw your message drop! I am extremely excited that you prioritize this issue so much and that it could be proven many different models may be affected. I believe many people may not be able to make the association to Signal when this happens, as the screen instantly flashes.

**Very offtop, but I think even if unrelated people here should know:**
https://www.reuters.com/technology/cybersecurity/governments-spying-apple-google-users-through-push-notifications-us-senator-2023-12-06/
https://www.wyden.senate.gov/imo/media/doc/wyden_smartphone_push_notification_surveillance_letter.pdf
The story is popping up everywhere in the news right now.
