### ISSUE TITLE
Wrong title and description for gift badges

### ISSUE THREAD

**Issue by awaitlink** [signalapp/Signal-Android#13297]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When viewing a gift badge, on Android it shows a description that says *the badge owner* (in this case, me) donated. However, this is not the case, as it's a gift badge. My iOS device shows the correct description.

### Steps to reproduce
- Tap on someone's gift (UFO) badge to view its description.

Actual result: | Expected result:
-|-
It says that *I* donated (also, the "supports" wording sounds like a recurring donation...): | Like on my iOS device, it should say that *a friend donated in my name* instead:
![android](https://github.com/signalapp/Signal-Android/assets/19972511/46fb52f1-72a4-4e22-92c9-57f51037ca18) | ![ios](https://github.com/signalapp/Signal-Android/assets/19972511/42d1def2-a7b2-4186-857e-851204b54795)

I believe this is reproducible both on the latest beta (6.41.2) and a recent stable version, too. If needed I can get more precise info.

**Comment by u32i64** [comment]
I've noticed the  @VaishnaviSrivastavaCodes' changes GitHub shows, and it looks like the original version of the code has the badge name and description as string resources in the app.

This is unexpected to me, because iOS fetches these from the service instead (and formats them with the appropriate user name). See e.g. [BadgeStore.swift#L15](https://github.com/signalapp/Signal-iOS/blob/8658c039068993ef9cc4d0d9bed8807d67988f44/SignalServiceKit/src/Util/Profiles/BadgeStore.swift#L15).
