### ISSUE TITLE
Signal (PNP)

### ISSUE THREAD

**Issue by g1zza** [signalapp/Signal-Android#13329]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0
![Screenshot_2023-12-23-11-41-27-75_74c8a8852300b790bef7a2026c132d36](https://github.com/signalapp/Signal-Android/assets/105108932/be39965a-8681-4860-97b0-898949befecf)

Hi,i dont know if here is the  right place ,i have  SIGNAL (PNP)  installed  i cant find any  my contract iv i know 80% have signal app .

**Comment by Sgn-32** [comment]
_"To do so, we’d first like to invite you to test in Staging. Think of The Staging Environment as a parallel Signal universe: you’ll need to install and run a new build (links below), and register for a new account with a phone number (you can use the same one you’re using in Production). **Anybody you wish to talk with in Staging needs to be registered in Staging as well** (please coordinate with your Signal testing pals in group chats rather than posting your phone numbers and usernames to the forums). We have no uptime guarantees in Staging, and it’s likely that push notifications won’t work as well, or potentially at all, during your testing."_

https://community.signalusers.org/t/public-username-testing-staging-environment/
