### ISSUE TITLE
Signal automatic chat backup creates two backup files instead of only one

### ISSUE THREAD

**Issue by HigH-HawK** [signalapp/Signal-Android#13439]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The automatic chat backup of Signal creates two backup files of the same size with just 5 seconds difference.

### Steps to reproduce
- Enable automatic chat backup and set the path, and time of the backups
- Wait for the automatic backup to run 
- See the two backup files in your file browser

**Actual result:** Two backup files of the same size are created with a difference of 5 seconds.
**Expected result:** Only one backup file should be created as it used to be in the past.

### Screenshots
**Signal settings:**
![Screenshot_20240221_112633_Signal](https://github.com/signalapp/Signal-Android/assets/33863449/b71acab8-9489-493c-ac16-e7677b61cf98)

**File browser:**
![Screenshot_20240221_112654_Solid Explorer](https://github.com/signalapp/Signal-Android/assets/33863449/137339bf-3c6b-4119-839c-c0a83b83553f)

### Device info

**Device:** Samsung Galaxy S22 Ultra (SM-S908B)
**Android version:** 14
**Signal version:** 7.0.0 (1394, 139402)

### Link to debug log
https://debuglogs.org/android/7.0.0/df1246da738a38228d4b0bde053a5d1a7f907850b4747409a51afa68d454643d

**Comment by fodinabor** [comment]
Hi,
Sorry to bring this up again, but I am having the issue that it creates two backups each day (see the date on the picture!). Since I automatically upload these to my nextcloud, the device is busy all morning uploading the backup files as it now has to upload 12 instead of 6 GB/day:
![Screenshot_20240614-073856_Files](https://github.com/signalapp/Signal-Android/assets/5982050/8e75a74f-59e4-4382-95b6-f6270c410446)

(Dont mind the temporary, I changed the time of the backup being created.. Which apparently triggered a new backup)

For some background: I restored a backup on this phone a few months ago (since which I believe this is happening). So maybe there's two triggers registered per night for some reason?
I tried disabling the backup and reenabling it once "to clear the triggers" but that didn't change anything..
