### ISSUE TITLE
Signal keeps asking for money and is unable to take no for an answer.

### ISSUE THREAD

**Issue by jvoisin** [signalapp/Signal-Android#13465]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal is repeatedly asking for donations, and one can only answer "yes" or "maybe later", but not "no." I would expect signal to [understand user consent](https://soatok.blog/2024/02/27/the-tech-industry-doesnt-understand-consent/) and accept "no" as an answer.

To make it extra-annoying, I made a [one-time $5000 donation to Signal in 2021](https://dustri.org/b/2021-in-retrospect.html), so it feels a bit rude to be asked to donate $5 on a regular basis.

### Steps to reproduce
- Use Signal
- Get the donation popup
- Notice that one can't say "no", only "yes" or "maybe later."

**Actual result:** 

Get the donation popup on a regular basis without any way to make it go away.

**Expected result:** 

Have Signal behave at least as decently as a random person hitting on my on a bar and be able to take "no" for an answer.

I do understand that Signal needs to make money, bury the option somewhere if you want, but please making it possible to tell it to stop showing the popup. 

### Device info
**Device:** Pixel 8
**Android version:** [GrapheneOS 2024030300](https://grapheneos.org/releases#2024030300)
**Signal version:** 7.0.2

**Comment by jvoisin** [comment]
You closed the issue as "completed", but it looks like it's more of a "wontfix", or did I miss a commit?

**Comment by stefarnold** [comment]
Reviving narcotic thread here because I have noticed the same behavior AND Signal seems to have degraded performance every time I sign up for monthly donations. I am not happy with their response to your bug report. I suspect they are adding people who donate to beta programs without their knowledge.

**Comment by greyson-signal** [comment]
Hi there, looking at this revived thread, we should have provided more context when the issue was closed.

Signal asks for donations quarterly, so 4 times a year. I don't think this is terribly often. There are no plans to allow users to disable these prompts. Signal is a non-profit and therefore sustains itself on donations. I know some people may find it annoying, but I personally do not believe that having to dismiss a popup 4 times per year is too much of a burden.

@jvoisin 
> To make it extra-annoying, I made a [one-time $5000 donation to Signal in 2021](https://dustri.org/b/2021-in-retrospect.html), so it feels a bit rude to be asked to donate $5 on a regular basis.

First off, thank you very much for your incredibly generous donation! We truly appreciate it. My assumption as to why you're being prompted, despite donating, is that there is no association between your donation in 2021 and your Signal account. It's just two different systems. If someone actively has a badge or a subscription that was initiated in the app, we  know that you've already donated, and will therefore not prompt you. But I understand why this would make the donation prompts extra annoying for you.

@stefarnold 
> I suspect they are adding people who donate to beta programs without their knowledge.

We absolutely do not do this. Joining the beta is an explicit action (instructions [here](https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta)) taken by the user.

**Comment by DarkArc** [comment]
@greyson-signal I have an employer match set up so I stopped donating directly through the app. 

I'm now seeing prompts on all ~5 devices I have linked. It would be one thing if my iPad, my desktops, and my phone all understood that I said no (in part because _I already am_ donating -- at $200/mo after match mind you) for this quarter and synced that bit ... but yeah 20x a year is a bit much.

Beyond that I'm subscribed to the backups feature which I assume on average makes _a little_ bit of money.

Donations only work if people like you and this multi-device nagging certainly isn't a point in the "I love Signal" bucket.

----

Upon reflection, I've decided this bugs me enough I'm just going to reduce my amount to $190/mo through the employer system and donate $5/mo non-matched to disable the nags.

If you reopen and fix this so that it's actually 4 nags a year (or give people that have been more than generous some way to just turn off the nags all together), I'll give you back the extra $5, which seems more than fair.
