### ISSUE TITLE
Muted contacts' calls are still visualized

### ISSUE THREAD

**Issue by fkroener** [signalapp/Signal-Android#13558]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Muted contacts' calls are still visualized.

### Steps to reproduce
- Mute a conversation (I think I tested 'for seven days', likely applies to all)
- Verify you get no notification from chat messages as you normally do
- Have that contact call you

**Actual result:** Call gets visualized with options to Accept / Decline
**Expected result:** Nothing should happen.

### Device info
**Device:** Asus Zenfone6
**Android version:** 11
**Signal version:** 7.6.2

**Comment by nicholas-signal** [comment]
Hello,

Please submit a debug log, thanks!

**Comment by githubuser6000** [comment]
Hi I have the same issue. Why won't this be fixed?

**Comment by githubuser6000** [comment]
Hi, wanted to check the status of this?

**Comment by githubuser6000** [comment]
@nicholas-signal @alex-signal Hey guys what's the status of this issue?

**Comment by greyson-signal** [comment]
The feature is currently working as intended. Muting a chat does not mute call notifications. The reasoning is that calls are usually a lower-frequency higher-importance event, and so they break through the mute status. We are, however, looking into updating the UI to allow for muting calls as well down the line.

**Comment by githubuser6000** [comment]
So there is no way to mute a contact's calls as of now? This is so unintuitive. Why does signal _consistently_ find the need to stand apart from other messaging apps in such weird ways? If signal wants to separate out call notifications, please do that as an opt-in or out later. Notification profiles should perhaps cover more fine-grained controls like this. 

There are notification profiles (which has allow-list, no disallow-list, for example), then mute, each with overlapping options, and now a new one? Not to mention signal does not follow system-wide call settings, which, again, all other apps seems to happily honor. I feel like this whole thing has to be redesigned. 

I am sorry, but IMHO, this is horrible user experience, amongst many other things that have been plaguing signal for quite years, with very real consequences. 

---

Just as an addendum, in hopes that someone from signal sees this ... Contacts can tolerate this for only so long before they just give up and migrate away. And it's has happened far too often that it feels like I (and perhaps many more) will have no longer have any contacts to securely connect to. I know this isn't your problem to deal with, but I am just sharing my concerns. Sorry I just wanted someone from Signal to see this because the signal community is overrun with too many people who vehemently, to this day, do not want an opt-in way to sync past history. Conversations have derailed and it seems like no progress will be made in many other issues. I would love to be proven otherwise.

**Comment by greyson-signal** [comment]
We definitely do have a few ways to manage notifications. They're all sort of tailored to different use cases and what level of effort someone wants to put in. Have that one annoying group chat that's bothering you during work? Long-press and mute for 8 hours. Don't want to be bothered during vacation? Create a notification profile that only allows certain chats to reach out (I agree having a disallow-list here would be super-useful, it's been talked about). 

Us not working well with system DND settings and whatnot is a bug that we're still working on, apologies.

> So there is no way to mute a contact's calls as of now? This is so unintuitive. Why does signal consistently find the need to stand apart from other messaging apps in such weird ways? 

Please correct me if I'm wrong, because I don't use other messaging apps very regularly, but my understanding is that muting a chat in WhatsApp or Telegram does _not_ mute calls. Do I have that wrong?

**Comment by githubuser6000** [comment]
I definitely appreciate fine-grained notification control and was glad to see notification profiles. But i haven't re-configured them because I thought they interfered with DnD, so not sure about that. 

I am almost certain whatsapp mutes calls too if you mute a person's chat. If not, then you're right I stand corrected. I unfortunately can't test it since I don't use it anymore
