### ISSUE TITLE
Calls Don't Use Microphone (silent)

### ISSUE THREAD

**Issue by lukeganzevoort** [signalapp/Signal-Android#13576]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When calling someone or answering a call (voice only call, not necessarily video), Signal doesn't use my microphone. I can hear the people on the other end, but they can't hear me. If I change to a bluetooth microphone or switch to speakerphone, they can hear me. However, the speakerphone gives them a lot of feedback, and we usually have to hang up and talk over cellular if I don't have my bluetooth headphones with me.

Important notes:
- I am using CalyxOS on a Pixel 3. I know someone else who is also using CalyxOS on a Pixel 3 and has the same issue.
- Voice memos work fine.
- The green microphone icon in the system tray bar at the top of my phone screen shows up, meaning the microphone is being accessed.
- This started happening a few months ago. I think sometime in 2024.

### Steps to reproduce
- Go to a chat with a friend and hit the phone icon to start a call
- When they pick-up, start talking. They won't be able to hear you. 
or
- Have someone call you on Signal
- Answer the call and start talking. They won't be able to hear you.

**Actual result:** My voice isn't picked up and transmitted to the other person on the call.
**Expected result:** My voice would be able to be heard by the other person on the call.

### Device info
**Device:** Google Pixel 3
**Android version:** 14
**CalyxOS version:** 5.7.0
**Signal version:** 7.6.2 (But this started happening a few months ago. I think sometime in 2024.)

### Link to debug log
[Debug Log](https://debuglogs.org/android/7.6.2/6ea7b98e4e5df62c9752e0696ead7a05a89376847cee3059fde8c68e768399de)

**Comment by sourcrowd450** [comment]
Same issue for me, on the latest version of LineageOS for the Pixel 3 both with Signal release version 7.6.2 and beta version 7.8.1

For regular calls and Signal voice messages the microphone works, for Signal calls it doesn't.

**Comment by starbrights** [comment]
I am suffered too (LOS21). 
Sometime it is working, but mostly not. Sometimes it seems to work to enable permission for micro on a "ask before" base. But that's not reliable too.

**Comment by lukeganzevoort** [comment]
After further research, I believe the bug I'm seeing is OS related. Something to do with Android 14 port to pixel 3 (from CalyxOS or LineageOS). I have the same issue on Slack, where when I join a huddle from my phone, the microphone works fine until I hold the phone up to my ear (which switches from speaker mode to phone mode) then the microphone stops working.

**Comment by starbrights** [comment]
The issue was gone for some time, now it is back. I switched to LOS22 some time ago, but that doesn't seem to trigger this issue. 
To bad, I am not sure what triggered this behavior. 
I am just wondering, why other apps (WA, phone, Fritzbox, Satellite) using calls are not suffered. What is special with Signal here?
Delete and re-install Signal doesn't help.

**Comment by attila-lendvai** [comment]
> The issue was gone for some time, now it is back. I switched to LOS22 some time ago, but that doesn't seem to trigger this issue. To bad, I am not sure what triggered this behavior. I am just wondering, why other apps (WA, phone, Fritzbox, Satellite) using calls are not suffered. What is special with Signal here? Delete and re-install Signal doesn't help.
> 
> For me it is not depending on "holding phone to ear" as [@lukeganzevoort](https://github.com/lukeganzevoort) mentioned. Same no mic with Video-calls or with BT-headset.
> 
> My hardware is beyond1lte (Samsung S10).

similar situation here.

i'm on LOS 18 since it was new. LOS 18 stopped getting updates years ago.

it's a xiaomi poco x3 pro.

i used to have a problem with the mic years ago, and then it got fixed by a signal update.

currently, for about 3-4 months now, again i can only talk to people when i put them on the speaker. otherwise my signal transmits silence.

**Comment by jim-signal** [comment]
Hello @starbrights and @attila-lendvai, can you please provide logs, preferably after a failed call? We can check.

**Comment by starbrights** [comment]
@jim-signal : Sorry for late reply.
How to do so? Do you mean Signals internal Diagnoese? Which section is of interest? The last lines directly after a call?

**Comment by jim-signal** [comment]
@starbrights The instructions for gathering and sending logs is [described here](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports). We would look at the time before and during a call, and the device information in the first section of the log. Logs mainly help us rule out issues, so it is hard to predict what exactly we'll see there. You could send the file or link to [support@signal.org](mailto:support@signal.org) and reference this issue if you can't share here.

**Comment by starbrights** [comment]
Send the log, hope you can figure out something.

**Comment by jim-signal** [comment]
@starbrights Yes, I was able to see your log file, thanks.

I can see that the microphone isn't working for you since no audio data is being sent out. I tested a call on my S10 (exynos) and it worked, but I am on aosp, not lineageos. My logs show that my device is using input "deviceId: 11" whilst your logs show "deviceId: 10", that is the only discrepancy that I see. We don't set these, they are the default from the operating system. The only thing I can try is to set this device to use a different audio interface, which is now active. Please let me know if anything changes for you.

**Comment by starbrights** [comment]
Thanks for evaluating this. Interesting - we have same device. Maybe a phone today has more than one mic. 
How you can set this different interface? Let me know how I can test this - do I need new signal version? Is this a problem hardware layer (maintainer of device) or the LOS itself?
You know, one blames the other - either user, app, os or device specific layer.
Do you compile your AOSP yourself or what is your source.
