### ISSUE TITLE
Add option to add prefix to SMS when requesting a delivery report

### ISSUE THREAD

**Issue by miketrim** [signalapp/Signal-Android#1364]
My service provider (O2 UK) only support SMS delivery reports by adding a *0# prefix to the message text.  Therefore currently when I enable the SMS delivery report option I don't get a delivery report unless I manually type the *0#.

Please add an option to allow a user specified prefix to be added to outgoing SMSes if SMS delivery reports are enabled.   The prefix should be added as the message is transmitted but not displayed/stored in the message log.

**Comment by dhkasdjas** [comment]
O2 UK has made its postion clear that the only way to recieve delivery reports is through adding *0# followed by a space:
http://community.o2.co.uk/t5/Apple-iOS-Devices-iPhone-iPad/SMS-Delivery-reports/td-p/352

Since it is one of the largest UK providers it would be really useful to have this feature.

This feature has now been included in other SMS apps such as 8sms and sliding messaging. It is currently the only feature stopping me from switching completely to textsecure:
![2015-06-28 00 25 40](https://cloud.githubusercontent.com/assets/13081656/8394414/84b68b48-1d2e-11e5-9bcd-fdbff96dce38.png)

Could this be implemented in a similar way to 8sms? i.e. after delivery reports are selected the option is given for O2 network compatibility (where the "*0#[space]" prefix is added to the message but is not displayed in the message log).
