### ISSUE TITLE
Signal crashes few seconds after Launch. Cause corrupted signal-jobmanager.db

### ISSUE THREAD

**Issue by tnixeu** [signalapp/Signal-Android#13762]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

Since a recent Signal update, probably 7.17.4, Signal Crashes a few seconds after launch. Currently the phone runs 7.21.5. I have uploaded a log already in #13697, which shows that the `signal-jobmanager.db` is corrupted. I have uploaded the log again here:
[log.txt](https://github.com/user-attachments/files/17598807/log.txt). I am starting a new issue since is was stated that this is unrelated the bug in that issue.

Signal at first seems to start fine. It loads the full GUI and shows all recently received messages, even those received after Signals started crashing. However,  few seconds later it crashes. New messages are also shown in the notifications bar, however, replying or "Mark as read" do not work. I was able to connect Signal to a PC, by being fast. 

This leads me to believe that the database containing my messages is not affected. In #12435 it was stated, that the `signal-jobmanager.db` is used for pending message, which I now interpret as pending outgoing messages. As root it can be deleted, however, I am not root on this device. 

I am looking for a way to fix the issue by deleting or recreating the affected database.

### Device

Samsung S7

### Android version

8

### Signal version

7.21.5

### Link to debug log

https://github.com/user-attachments/files/17598807/log.txt

**Comment by rishabh-bhatia** [comment]
Hi there, sorry if this sounds obvious but have you tried to clear the cache? The logs seem to indicate that the issue is related to Encryption key/DB corruption. Clearing cache seems to be the only way you can safely force the app to reset tables without losing data. If you're looking to wipe `signal-jobmanager.db` without root access, you should be able to do that by modifying the code and compiling your own version of the app( If no official support is provided).

**Comment by tnixeu** [comment]
I have tried clearing the cache, however, it did not help. I just tired again.

I haven't tired something like this yet, because I think Android protectes against that.

**Comment by rishabh-bhatia** [comment]
Hey @greyson-signal is this a common occurrence? If so it could be affecting the UX on a larger scale. Quoting you from #12435 .

> This is one of those cases where it's probably fine to delete it, but in general not-fine. It stores state about pending messages and such, and it could throw things out of whack.

Implies that in general we don't expect `signal-jobmanager.db` to be corrupted. So in the rare case where it does get corrupted, wouldn't it be a better option to delete it rather than getting the user to clear storage and lose all chats? 

From what I could tell by looking at the code briefly, deleting this DB would not be "ideal"(Especially if it is deleted too often). However, in the rare case it does get corrupted then it needs to be deleted to protect everything else. In case `signal-jobmanager.db` is getting corrupted too often then this could indicate another bug.

**Comment by greyson-signal** [comment]
It's definitely not  _great_ to lose that data, but I think you're right that it might be better here to reset that table. I'll make that change.

**Comment by tnixeu** [comment]
I tried the latest version and Signal seems to be working fine again and I was able to make a backup and move Signal successfully to my new phone. Thank you very much.
