### ISSUE TITLE
Two separate threads for the same contact

### ISSUE THREAD

**Issue by uniquePWD** [signalapp/Signal-Android#1430]
I have an incoming thread for a conversation (447XXXXXXXXX) and an outgoing (07XXXXXXXXX).

If I try and reply to the first one (447...) it fails, I'm assuming because it's not prefixed with a +. And so the work around is to reply to the same number but swapping 447 or 07. This is incredibly broken, is there any way to fix it?

**Comment by dusscloud** [comment]
I have a similar bug.
I received two SMS from the same number. Instead of displaying both messages in one thread, I have two different threads.
(I use Signal for both sms and secure messaging)

### Screenshots
![screenshot_20190125-121952](https://user-images.githubusercontent.com/31505866/51743090-f1c8d000-209b-11e9-9f2b-0f86a692fc54.png)

### Device info
**Device:** Motorola  G4 plus
**Android version:** 7.0
**Signal version:** 4.32.8

### Link to debug log
https://debuglogs.org/19261184976194633e915f6632930fc4416960360e90322af45338c9a9b481a9
