### ISSUE TITLE
Error messages in Argentina

### ISSUE THREAD

**Issue by bleiva** [signalapp/Signal-Android#1511]
For example I live in Buenos Aires and my friend too, so when I need to send a sms to my friend (In Buenos Aires), I have 4 numbers to send it:

11-245678
15-245678
11-15-245678
+54-11-245678

+54: Code for country
11: Code for Buenos Aires (Sometimes is posible using 011)
15: This is a prefix for mobile phones.

When I must register in Texsecure to use push message, I must add a number, the 9. So, if you want to call to me o want to send a message to me, you need add a 9. This is only for people outside Argentina.

Example:

+54-9-11245678 (+54 Argentina Code, get off the code 15, and put the code 11)

Possible problems for this:
1. If I want to register in Textsecure without 9, the message never arrive. Neither the call. Nobody knows in Argentina that is necessary this, so we have problems in this step.
2. If I want to send a push message to my friend, I need add her to my contacts with the number (+54911245678) like she would be in another country.
3. If I send her a push message with the number 11245678 or 15245678 don't work. (message incorrect cipher). The most people don't know when they need to put the numer 9 or the +54, so the message never will arrive between friends.
4. If I 'm online (with internet) and send to my friend a message and she has internet too the message arrive correct both.
5. If I'm offline (without internet) and send to my friend a message and she has internet, doesn't work. (message incorrect cipher). This error is really annoying because If somebody of us doesn't has internet, the message says incorrect cipher. In Argentina is very common that some places don't have 3g signal.

I hope this help you. Thanks for all.

Best regards.

**Comment by drzraf** [comment]
Coming from #5270,
The Android API already provides the country code.
From this, it may be possible to know the area code (depending on the Android API?)
From the above two it should be fairly easy to map phones number from one scheme to another.

Could authors indicate sourcecode files which manage phone number schemes in order to pass it to phone-based contact search?
Is there an "get_i18n_phonenumber()" function somewhere? (Signal or Android API)?

**Comment by tandiljuan** [comment]
Same problem here.
If I register my mobile number like `+5491234567890` (full international number) and my friends doesn't have me in their contact list with my full international number (eg `123 4567890`), they won't find me in the Signal app and also I will not find them.
Also if I have my friends in my contact list with their full international number but they register with a different number (eg `+54 123 4567891`, missing **`9`**) I won't find them in the Signal App and also they won't find me.
My suggestion is that the application must force to use international phone numbers. If the user doesn't have an international phone number, complete the missing numbers.

**Comment by drzraf** [comment]
+1

but a precision about this specific sentence:
> they register with a different number (eg `+54 123 4567891`, missing **`9`**)
they couldn't call either. Argentina international phonenumber notation
MUST contains the "9" whatever the network used at the time they call.

**Comment by tandiljuan** [comment]
That's true. But I have two friends that registered their numbers (in Signal) without the **`9`** and they received the SMS (really weird).

I think the logic to force full international numbers is not complicated:

At register time, you must force to use full international number to send the SMS: `[INTERNATIONAL CODE] + [LOCAL CODE] + [MOBILE NUMBER]`. (In Argentina the international code will be +549, US +1, UK +44, Spain +34, etc).

Taking in mind that all full international numbers for a given country must have same length. I can see two scenarios regarding the numbers in your contact list:

* Contacts from other countries: You must have them saved with their full international number. Otherwise you won't be able to call them. No problem here.
* Contact from your same country:
    1. They are saved with the full international number (no problem)
    2. They are shorter than your full international number but larger than your `[MOBILE NUMBER]`. They are from the same country but from a different city. Just need to add your same `[INTERNATIONAL CODE]` to convert it to full international number.
    3. They have the same length as your `[MOBILE NUMBER]`. They are from your same city. Just need to add your same `[INTERNATIONAL CODE] + [LOCAL CODE]` to convert it to full international number.

In this way you just need to match full international numbers. And, taking in mind that they are unique, I think that it should solve the problem of missing contacts in Signal.

[List of country calling codes](https://en.wikipedia.org/wiki/List_of_country_calling_codes)

**Comment by Pesebrero** [comment]
@tandiljuan Please look at #4378, this issue is about the registration, the other is about other users who cannot see you as a Signal user, which you describe.

Also, in my experience, adding the "9" **does not guarantee proper detection**. In fact, I had **the exact opposite situation** (had to suppress the "9" for the number to work). Right now I have some contacts with the "9" and others without it.

Signal should redundantly search for any possible combinations to properly register a number, i.e. if I register any of these numbers (or have them in the contact list), Signal should search for **all** of them:
15XXXXXXXX
11XXXXXXXX
+5411XXXXXXXX
+54911XXXXXXXX
005411XXXXXXXX
0054911XXXXXXXX

Telegram does not have this issue AFAIK, perhaps it is possible to look at the code to see how it handles numbers from Argentina.

**Comment by drzraf** [comment]
Imagine a contact is saved in the phonebook using this syntax: 15XXXXXXXX

AFAICT Signal has no hint about the country (there are 281)
...  + what happens when traveling abroad?


Even then, the issue lay down to the ambiguous Argentina numbering
scheme which make a number depends upon caller position.


Signal has no hint about the zone (they are ~250 of them!).
= it's like if Argentina was adding 250 country-codes.

The only way to workaround the issue is the make Signal (or related
library) either:

* 1) fetch information from the SIM-card provider in order to 
  determine the prefix code (in the event it's consistently offered but
  Android's API *AND* claro/movistar/personnal implement it)

* 2) fetch the owner's phone number, attempt to extract the zone, assume
  this zone for all un-zoned contact phone number searches.


Again, this may better fit an upstream library like:
https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberAlternateFormats.xml
https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/54.txt
(217 zones according to them)



> Telegram does not have this issue AFAIK

From what I can remember I was having the same issue with Telegram, in
Argentina in 2016: if there was a mismatch in the phonenumber notation,
Telegram wouldn't find the contact (it may have changed since btw)


The only related file found client-side sourcecode in the sourcecode of TG is here:
https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/assets/countries.txt
(but not much interpolation attempt)

**Comment by tandiljuan** [comment]
@Pesebrero You have to remove the *9* because your contacts registered their cellphone number without the *9*. You have them in your contact list as *+5491231234567* but they registered as *+541231234567*.

I can confirm, in the registration process, the international number for Argentina is `+54` (and not `+549`). So, if the user doesn't to enter the *9*, the number nine won't be added automatically by Signal.

@mcginty Is this a Twilio issue? Or is something that you could force in the application side?

@drzraf If Signal properly force the users to register with international numbers (using the *9*), there shouldn't be mayor issues to detect contacts. I've already explained the logic to do it. All countries have an international number, (almost all have?) an area code and then the phone number. Worth to mention that I've worked on a mobile application service, where we fixed this issue with the logic that I've mentioned.

So far, I think the only issue is the *9*. Of course, it's needed to test other combinations.

[US Area Codes By State](http://www.worldatlas.com/na/us/area-codes.html)  
[Spain Area Codes](https://en.wikipedia.org/wiki/Telephone_numbers_in_Spain#Area_codes)

**Comment by drzraf** [comment]
> @Pesebrero You have to remove the *9* because your contacts registered
> their cellphone number without the *9*. You have them in your contact
> list as *+5491231234567* but they registered as *+541231234567*.

thank for clarifying this.

That means that Argentina phone numbers registered in the Signal
server database are *not* reachable (contrary to all other countries' numbers)

Not that it annoy me in any way but it mean it's assumed as raw unique
client ID without a (strong) dialing/reachability semantic.

Should I be able to register using an email address then ;)

**Comment by Pesebrero** [comment]
> Signal has no hint about the zone (they are ~250 of them!).= it's like if Argentina was adding 250 country-codes.
I have no idea how the push messaging system works. But, given the phone "knows" where the owner is located, Signal should use that information, at least for registration. For the contact list, it could make a "safe guess": if both users are from Argentina, then it should limit the search within the registered users in the country.

> From what I can remember I was having the same issue with Telegram, in Argentina in 2016: if there as a mismatch in the phonenumber notation, Telegram wouldn't find the contact (it may have changed since btw)
I have installed it very recently, and it correctly added the contacts I had with the "15XXXXXXXX" format. They were recognized as "+5411XXXXXXXX". Signal should be able to do the same.

> You have to remove the 9 because your contacts registered their cellphone number without the 9. You have them in your contact list as +5491231234567 but they registered as +541231234567.
It seems to be a random issue. I have re-registered the same number twice with and without the "9" (not being able to make it the other way). Also, I have seen a friend "forced" to re-register, first without the "9", then with the "9" again (perhaps because of testing being done on the Signal servers to solve this issue?)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
