### ISSUE TITLE
unable to add / remove person from group post initial group creation.

### ISSUE THREAD

**Issue by zee0** [signalapp/Signal-Android#1591]
i wanted to send a text to a handful of folks instead of copy / pasting to them all. it seems like the only way to do this is by creating a group. i created the group, and then remembered one additional person that i wanted to add, but there seems no way to add someone after the group is created. i was forced to delete the group and start over.

**Comment by gladiac** [comment]
Could this bug be the in the focus of the next version? It is really annoying that groups are really hard to handle. If someone uninstalled TextSecure then whenever you send a message to a group you get an error that the message could not be delivered. The issue is that it couldn't be delivered to one person, but all the others received the message. So people think it isn't working but the message was delivered. In the error message you also can't find out why the delivery failed or to which person it wasn't able to deliver the message.

**Comment by paul-schulze** [comment]
Via the "Update Group" Menu I can add people to the group but there is no way to remove people.

Signal 3.9.1
Android 6.0.1

**Comment by Yky** [comment]
I have the same issue on Signal 3.10.0
Android 6.0.1

**Comment by DreamFlasher** [comment]
Yeah, there is no possibility to remove people from a group. Could you please add that?

**Comment by rpardee** [comment]
I too would like to be able to edit an MMS group.

**Comment by regalstreak** [comment]
Any reason to not having a remove people feature?

**Comment by jedie** [comment]
> Any reason to not having a remove people feature?

Some information about removing group members are here: https://github.com/WhisperSystems/Signal-Android/issues/828

**Comment by dlchen** [comment]
@pauschuu I don't see an option for Update Group for MMS. Is it still possible to add a person to an existing MMS group? Or even create a new MMS group from an existing MMS group with an additional new person(s)? I don't see an easy way to do this. Thanks!
Signal 4.15.5
Android 7.1.1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
