### ISSUE TITLE
Messages lost after App got killed

### ISSUE THREAD

**Issue by fmauch** [signalapp/Signal-Android#1679]
Hej there,

Today I accidentally killed my TextSecure app and after restarting and unlocking it a bunch (a lot of them, actually) of messages were missing.
I think this should be all messages I received after unlocking it for the last time. Do they get written to the database only if the app is shut down correctly? Were are they in the meantime? Is this behaviour intentionally?

Cheers
Felix

**Comment by lpirl** [comment]
> Messages are stored to the database as they come in. However, force closing an app will result in undefined behavior -- sometimes the sqlite database can be corrupted, etc. We have absolutely no control over what happens when you FC TextSecure.

Just out of curiosity, I suspect Signal uses SQLite, doesn't it?
Since [SQLite is transactional/ACID](https://www.sqlite.org/transactional.html) it should never end up in a corrupted state.
When transactions are used correctly, it should additionally never end up in a semantically inconsistent state or do I misunderstand something here?

I came across this issue since my Signal also lost all messages (can't tell if the phone crashed at some point, maybe).

Thanks for your tremendous efforts!
