### ISSUE TITLE
sms delivery report: show received time in message details

### ISSUE THREAD

**Issue by doits** [signalapp/Signal-Android#1692]
when a sms delivery report is received, the time the other user received the message (afaik the `done date`) should be saved and it should be possible to view it in message details. This way one could see **when** the other user received the message (not only that is was received).

edit: if someone can give me a hint where to look/start in the code to implement this, I'd try to make a pull request (but I just glanced through the code and cannot find a starting point ... maybe it's simply too late already ;-))

**Comment by rhodey** [comment]
related #2055

**Comment by m42i** [comment]
Not sure if this is the right issue, because it's about showing a time. The code for showing a double check mark seems to be there. Commenting out three lines shows the icon. (See: SmsSendJob.java:139 )

Though I guess for a proper implementation a preference options should be created. 

Is there a conclusion on the security aspects mentioned in #2055? 
Would it be enough to warn the user of the possibility the SMS delivery report could be forged?

**Comment by GfEW** [comment]
+1 Any news to this? 
Stock messaging app provides confirmation times, but since outgoing messages are not listed there when Signal is the standard messaging app, that doesn't help.

The forgery argument is moot. AFAIK, the entire SMS protocol is forgeable, including authenticity, content, sent time, delivery status, delivery time. If we decide to use it nevertheless (and we might want to warn the user about the risk), there's no reason to conceal SMS delivery times.

Please, provide delivery confirmation times within Signal.

**Comment by moxie0** [comment]
@GfEW Please don't post things like "+1" in issues, it'll only make us less likely to work on it.

**Comment by GfEW** [comment]
Thanks, got it. Main point is about forgery. I'll omit the '+1' primer in the future.

**Comment by grinapo** [comment]
@moxie0 Without the intention of lessening the probability of anyone's working on this issue, would it be possible to actually record and show all the time data Signal was made to be aware of? At least the receive time of a delivery report is pretty obvious, and it's handled by the code putting the second tick on the messages, so it seems to be only a question to store it in the database, and show it when asked. (I don't have the possible content of the delivery report handy so I cannot tell whether it contains the real delivery time, too. If it would do then it should be recorded, too.)

I hope asking about biannually isn't too rapid, considering the complexity of the problem, which is probably close to "trivial", and the age of the issue, which is almost 3 years now. (And I accept the blame for not taking the time to familiarise with java and doing it by myself.)

**Comment by micressor** [comment]
+1

**Comment by AdamGladkowski** [comment]
+1, I'm really surprised that signal is missing sth so simple and yet so useful as plain text message delivery notifications :(
please add it :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
