### ISSUE TITLE
Option to select SMS in sending group message

### ISSUE THREAD

**Issue by grigornobga** [signalapp/Signal-Android#1714]
Your app is really cool, but sending group message is pain as hell. Kindly add an option to select SMS in sending GM, than a default MMS. If I just miss something in config, kindly point it out.. using 4.2.2 Jelly Bean.

**Comment by evertheylen** [comment]
Sorry to hijack this issue, I wanted to comment on the original one but that one is locked.

For the time being, there is a workaround to send SMS to multiple people by misusing the "Invite to Signal" functionality (from the main menu). Just type your SMS instead of the invite, and select to who you'd like to send it.
