### ISSUE TITLE
unable to initiate SMS session

### ISSUE THREAD

**Issue by ctron** [signalapp/Signal-Android#1737]
In the past I was able to start a secure session for sending SMS. This was the main use case for text secure. What happened to this feature?

**Comment by pospi** [comment]
I am utterly appalled that this is even being discussed, and though I may be far too late I am adding my feedback here rather than in the mailing list because this is a more prominent and persistent place for it. End-to-end encrypted SMS is the *only* reason myself, my friends and I would wager a large number of Australian users are using TextSecure at all. Because-



**Problem 1: push messages are broken**

There are a *host* of issues - #1102, #970, #1971, #2238 etc all related to this. It was the reason I disabled the push service in the first place and instructed everyone I know to do the same - because Google's push service is not reliable (at least not in Sydney, Melbourne or Brisbane), and if you opt to use it what you end up with is delayed messages that come in up to a day and a half after they were sent. If SMS gets dropped and there isn't reliable infrastructure in place to service the alternative, then TextSecure becomes completely useless as a realtime communication tool. Really that's the killer, if you can solve the deliverability issues then it's much less of a problem.

Otherwise you will lose users, people's impressions will simply be "this does not work" and they will stop using it. Like they almost did when I went through all of this with non-technical friends in the first place; something I was only able to salvage by working out what the problem was and instructing them how to work around it.



**Problem 2: not everyone has 3G**

Arguing that everyone will have data soon so there's no point in supporting SMS is a poor argument. It's the same as saying "not many blind people will use this app so I shouldn't bother with visual accessibility at all". It may be true that Western perception of the global South's internet situation is off and data is much better than SMS down there. This doesn't change the fact that if you want a service to be usable by the widest range of people possible then you simply have to support the widest range of environments possible.

Relying on data will not work in Australia. We have some of the worst internet in the world, and due to the number of people and our broad geographical distribution that is likely to be the case for many years to come. Several recent administrations have tried to fix or improve upon the problem and every one has made things worse. Given what is happening with metadata down here at the moment I would say that you're looking at one of your primary userbases, and you'll be losing all rural Australians without the ability to send over SMS. And lets not forget people travelling overseas - roaming data is expensive as hell and most people prefer to have it turned off.



----



I don't see how doing an encryption handshake over the data channel and then still allowing sending via SMS using the same encryption keys is a technical challenge; not that I am an expert but surely taking an encrypted message and sending it over a different transport makes no difference at all to its ability to be decoded? It's the handshake that is difficult over sms, once you have that done a message is just a message. Yes SMS will leak the recipient and push messages may not, but I would take encrypted content and reliable delivery over semi-anonymous sending and random message delays any day.

Ok so that's about it, and I am sorry for the tone of this.. obviously it's an issue people are passionate about and it makes me feel as though the utility of TextSecure is being completely undermined. Currently it is the *only* usable end-to-end encryption solution for phones that acts as a seamless replacement for realtime text messaging, and that is what sets it apart. In the absence of SMS it is no more useful currently than something like ChatSecure or Cryptocat. I hope my rather blunt comments add some perspectives and situations not raised before (:
