### ISSUE TITLE
Featue Request: Quick way to wipe message database

### ISSUE THREAD

**Issue by HadManySons** [signalapp/Signal-Android#175]
Say for some reason you're being coerced with force to disclose your password, could you make a quick way (say a button combo + confirm dialogue) to wipe the text message database?

**Comment by nwdev** [comment]
I'd really like to see this feature as well.

**Comment by ail1020** [comment]
I'd also really like to see this feature. I think the most practical way of implementing if for plausible deniability would be to erase any secured communication while leaving the remaining messages. This way there would be no "fake messages" to maintain or import. Besides, if some law enforcement is trying to persuade you into giving a password, odds are they've already got your unsecured messages from your service provider. 

So I think the best way to implement this would be to either remove the secured messages from the database upon entry of the secondary password and continue login as normal (as well as ending any existing secure conversations) and leaving the unsecured messages in the database. Another possibility would be to give an additional option to wipe all the messages instead of just the secured ones.

The thing that worries me about having a set of fake messages is the maintenance. You'd have to maintain it regularly by updating the timestamps and possibly contacts and unless you're purely using the data channel a law enforcement figure would have the meta data about the communications already and probably the unsecure messages making it difficult to say those are the only messages that were kept in your phone when they don't match up with what they got from your service provider.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
