### ISSUE TITLE
Sent silent messages

### ISSUE THREAD

**Issue by cygairko** [signalapp/Signal-Android#1803]
Imagine the following scenario:
It's late at night, but you realized, that you forgot to write/say something to somebody. But it is really important, that the person gets the message by next morning.
- You don't want to wake the other person, but you know his/her phone is aloud.
- You cannot sent the message later
  - because you're asleep then
  - because you will probably forget
  - because you're on the plain
  - or whatever reason

My suggestion:
Make it possible to send silent messages. These silent messages will not ring the phone on the other side. For this silent messages one can set up different notification settings (e.g. just show notification, but no sound).
I think this is really a great feature and will, once established, prevent people to be woken up by messages they also could have read next morning.

**Comment by christophvarga** [comment]
I like the idea. For me its not because of letting people sleep but also to eliminate the need for sending a e-mail. There are messages which are not time critic and therefore i won't hassle the other person. And all of you know how often we have to watch our displays-- to reduce the need for checking our screens would be great!
Maybe it is better to label it as a new kind of message to make the difference very clear and nobody gets confused in the way like: 'did i overhear/overlook that?'
This second category can be set by every user/recipient with separate alarm settings (id they want). To keep a clean and easy UX design this option should not be very obvious in the first place.. like the option to send an 'unsecure SMS', this is done right (for me).

**Comment by apelivan** [comment]
+1
I also came across these situations several times and would have loved sending a "silent Message"

**Comment by jeremymasters** [comment]
Wouldn't it be up to the receiver to decide if they wanted notifications or not?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
