### ISSUE TITLE
Sort by date sent, not date received

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#188]
I have bad signal at work, and receive all my daily texts when I go outside for lunch. I would like a way to sort and display by date sent rather than date received so I don't look at messages out of order, and can ignore older texts.

**Comment by shaaati** [comment]
I'd like to push that issue as well. #1970 states that push messages display the sent date while text messages do not (due to unreliability). Wouldn't it be possible to also sort push messages by sent date then?
I often have a problem to figure out the correct order of group messages when my data connection has been cut for a longer time, e.g., during the night.

**Comment by dkasak** [comment]
This is a pretty big usability issue for me as well, particularly for group conversations. In the past few days, in a group conversation with three people which all had a data connection available at the time (evidenced by the fact that we were all receiving messages from other conversations), we all had our group messages sorted significantly out of order and it was a different order for each one of us. This is a significant issue for common users and I was confused by this myself a few times.

@moxie0 Are there reliability issues for sorting by sent date even for push messages? If yes, what are they? If not, I strongly suggest making sort by sent date a default for push messages.

**Comment by RalfJung** [comment]
Sorting by received date is particularly inconvenient for the case where one was offline for some time, and then receives a batch of messages all that once. It becomes pretty much impossible to reconstruct the conversation that happened in a group chat, because it's all messed up.

What exactly did you mean by sent date being "often unreliable"? I would assume that most phones have their time set to auto-sync, so they get mobile operator and/or NTP time updates and should have reasonably accurate timestamps.

**Comment by jeremymasters** [comment]
This has actually been discussed quite a bit in other issues.  Times supplied by providers can be pretty inaccurate.

**Comment by RalfJung** [comment]
That may be, but the current alternative is also highly suboptimal: When receiving multiple messages in a batch, the date received is much less reliable in practice than the date sent - in my experience at least, and judging from the reports of my friends. Looking at my screen, I can definitely say that sorting by date send would be *much* more useful than the current sorting.

**Comment by jeremymasters** [comment]
If it's discussion we want, this (https://lists.riseup.net/www/arc/whispersystems/) is a better spot.

**Comment by kaueraal** [comment]
This issue gets even more relevant today with multi-device sync. When using the Signal Chrome app with an Android phone your own synchronized messages may be out-of-order as well. That is quite frustrating.

**Comment by x12x** [comment]
Unfortunately the developer assigned to this resigned so we'll have to wait until he is replaced

**Comment by breversa** [comment]
Count me in as well : I switch my phone off (or to airplane mode) during the night and get my new messages when I switch it on again in the morning, and they all show "Received just now" (well duh, I did not notice ! :-P ), while it would be much more useful to have the sent time instead, especially if I received them in a non-chronological order (due to the way SMS work).

I know that SMS sent timestamps can be unreliable sometimes, but (at least for me), it tends to be a thing of the past, and I find the sent timestamp to be much more useful than the received timestamp (which I pretty much never need). It prevents all those awkward "When did you send this message ?" conversations…

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by 2-4601** [comment]
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/message-ordering/2581).
