### ISSUE TITLE
MMS logout

### ISSUE THREAD

**Issue by blocman** [signalapp/Signal-Android#1968]
Textsecure in Android 4.4.4, liteflow

SMS works as expected, I won't be logged out unless the time limit that I establish has been met. However any time I receive a NEW MMS notification and I'm in another app, or not viewing THAT MMS conversation, I'll have to enter my password to view it. 

Thanks

**Comment by rhodey** [comment]
Looking into this I found that  `java.lang.SecurityException: Unable to find app for caller` is most often related to an issue with passing `Intent`'s that have large extras. I imagine that MMS related intents probably have large extras in comparison to SMS intents, so at least that much makes some sense.

this issue seems somewhat related to #1456 which is still open but kinda stale and #461 which is closed with a confirmed fix.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
