### ISSUE TITLE
Merge messages for same contact with multiple #s

### ISSUE THREAD

**Issue by jwalantsoneji** [signalapp/Signal-Android#2242]
Hello,
Sometimes there are multiple source numbers for the same service.. for example, Idea cellular company's advertisements, offers and profile updates come from different "from" address/phone number.
However, all these sender numbers are listed in one contact in my phone's contact book.

It would be nice to have all these text messages shown under one entry on the Text Secure screen rather than 3 different persons with same name.

**Comment by jeremymasters** [comment]
Does this get messy when one contact has both a TextSecure number and a deskphone # for instance?

**Comment by brwolfgang** [comment]
That's something I would really love to see on TS.

**Comment by Mihahn** [comment]
I'd like to see that feature, too, because this would improve the way of changing phone numbers.

For example: (this really happened this evening)
My friend Peter gets a new phone number. He unregisters his old one and registers the new one. He contacts me then and I have the old chat with all the messages (from over one year now) which I'd like to keep and the new chat. 
a) on his phone, he has one chat with me, containing the old messages and the new ones
b) on my phone, I have the old chat with many important messages and the new one we'll use the next few months

So the option to merge the messages from the old chat in the new one would really improve TextSecure and it would be a feature most messaging apps don't support yet (e.g. Whatsapp lacks this functionality).
Of course this should be optional, because some people like to have one number for the work phone and one for the private! But please give us the choice :+1:

**Comment by Lacrymology** [comment]
:+1:

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
