### ISSUE TITLE
Superfluous 'tap for details' in message detail view 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#2618]
Seen with a failed MMS

**Comment by McLoo** [comment]
Below the message bubble 
![screenshot_2015-03-08-09-30-07](https://cloud.githubusercontent.com/assets/5326916/6545104/d01d019a-c575-11e4-93df-2b1f12bf1217.png)

**Comment by nonlinear** [comment]
Yeahhhhh... Even if you folks plan to add more relevant info on this second page, "resend" button is so crucial, it should be "more info" and "resend"

If you're trying to add friction because it's a security breach, consider a warning confirmation popup educating user why it's risky, with "cancel" and "resend anyway", with it appearing just once, or Everytime you click resend, with a "don't show this message again" checkbox.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
