### ISSUE TITLE
Not yet published on F-Droid

### ISSUE THREAD

**Issue by der-stefan** [signalapp/Signal-Android#281]
Dear developers,
as we all care about privacy I would recommend to publish TextSecure on F-Droid (with having updates) as some people don't use Google Market.

edit: The discussion on F-Droid can be read here: https://f-droid.org/forums/topic/textsecure/
edit: I understand the discussion, thanks for your replies.

**Comment by k3a** [comment]
I will stop using textsecure because of that. In my opinion your arguments are wrong. You can track user installs on playstore enough, you don't need to track installs outside it. I don't want my phone to send any unnecrssary statistics stuff. You also don't need crash reports from f-droid as it would crash on playstore too. Automatic updates are not priority - do you have automatic updates on your gnu/linux server too? The biggest fail is that you are making opensource software and don't want anyone to build it and distribute it. That's opensource but not free software. So thanks, will have to find an alternative.

**Comment by JonasT** [comment]
Please everyone! moxie0 clearly stated ( https://github.com/WhisperSystems/TextSecure/issues/282#issuecomment-21763403 ) that he doesn't forbid unofficial builds and that the software is true unrestricted GPL.

He was initially a bit bumped I guess, but why not let him be whatever he wants since he gave a clear statement on the legal standpoint now. You don't need the developer's **love** to make use of the freedom given to you through the GPL, please.
