### ISSUE TITLE
Can't send messages for certain missing country code

### ISSUE THREAD

**Issue by diegode** [signalapp/Signal-Android#3006]
I use Signal and my friend TextSecure.
I had this bug: https://github.com/WhisperSystems/Signal-iOS/issues/766
I fixed it adding the prefix "+549" to my friend's number in my contact list (as I said in the issue).
Then I wrote him and he could read the messages, but he couldn't write me back (it shows an error).
So he added the prefix "+549" to my number on his contact list, and that fixed it.

**Comment by rhodey** [comment]
@diegode so your friend uses TextSecure and couldn't send you messages until adding the country code to your number in their contact book? sound like everything is working now though, right?

I'm unclear what the issue is though, is it that TextSecure for Android should work without country codes in phone numbers?

**Comment by diegode** [comment]
@rhodey I think the issue is related to a bug of libPhoneNumber (referenced here: https://github.com/WhisperSystems/Signal-iOS/issues/766).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
