### ISSUE TITLE
Group messages not restored properly on import

### ISSUE THREAD

**Issue by d3k4r** [signalapp/Signal-Android#3024]
Device info: Nexus 5, 12.1-20150419-NIGHTLY-hammerhead, TextSecure 2.11.1

I exported plaintext backup.
Uninstalled TextSecure.
Updated ROM.
Installed TextSecure.
Imported plaintext backup.

I had a group before the export and after the import the group wasn't there. Messages that I had received from the group show up in the individuals message thread. I can't seem to find messages which I had sent to the group.

Also, noticed that the messages show up as sms messages even though they were previously push data messages. i.e. No distinction between encrypted/unencrypted messages.

**Comment by johanw666** [comment]
That is to be expected: since the plaintext export is in the format of "sms backup and restore", all messages come in as sms or mms and there is no concept of groups. Further, you will see your identity key has changed. The encrypted full backup that once existed has been removed from the app.

Next time, use Titanium Backup. It requires root but if you are in the business of changing ROM's I assume that's no problem.

**Comment by agrajaghh** [comment]
Is it intended that the sent group-messages are not included in the plaintext backup?

**Comment by vanitasvitae** [comment]
I can confirm this. Pretty annoying. Also, is there no other way to get the group conversation back into the chat list, than to wait until another member of the group writes a message?

**Comment by blinry** [comment]
I was tricked by this, too. Ideally, the export functionality should be extended to support groups. For now, the export dialog should warn about this.

**Comment by AlfonsoMuskedunder** [comment]
@agrajaghh 
>Is it intended that the sent group-messages are not included in the plaintext backup? They could be added to each individual conversation I guess...

At the moment they *are* included in the individual conversations, but it makes for a pretty terrible read in my humble opinion. It's probably a matter of taste, but personally I find that the best "second-best" solution for now would be to exclude group messages from plaintext backups altogether.

**Comment by rejhgadellaa** [comment]
I think I agree with @AlfonsoMuskedunder when it comes to handling the current situation:

- Warn the user that group chats can not be properly restored when he tries to do a backup
- By default, do not include group chats in backups since the current implementation can only be described as broken (especially from a user's perspective)
- Maybe give an option to include the group chats anyway
- Maybe remind him about the issue when the user tries to restore the backup

But really, this issue should just get fixed? Anyone who changes ROM's (and/or (re)flashes a factory image?) or buys a new phone will run into this issue and basically lose entire chats. Splitting up a group chat in separate chats renders them almost completely useless and causes a lot of clutter in the conversation list. This whole thing makes for a pretty bad user experience.

**Comment by tecknicaltom** [comment]
I hate to me-to, but this issue just bit me while changing to a new phone. Initially the export-import looked lossless until I noticed the groups were messed up. This means that there's currently no way for a (non-root) user to move to a new phone without losing some of their Signal data. If the problem is the "sms backup and restore" format, then Signal should provide a different export format that losslessly preserves group messages and embedded multimedia. Additionally, warn the users that the other export is lossy. I'm glad I didn't yet wipe my old phone, but who knows how many people have permanently lost data due to this issue.

**Comment by jacksenechal** [comment]
I created a [bounty](https://www.bountysource.com/issues/11679691-group-messages-not-restored-properly-on-import) for this feature.

**Comment by kaihsutai** [comment]
The backup is not writing out sent messages (type="2") in group conversations in my Android client. Received messages (type="1") in groups seem okay.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
