### ISSUE TITLE
all images view for group includes group icon but only for group creator

### ISSUE THREAD

**Issue by rhodey** [signalapp/Signal-Android#3045]
1) create a group with an icon
2) add your friend to the group
3) open the all images view
4) notice that it contains your group icon
5) open the all images view on your friend's device
6) notice that your friend's all images view does not contain the group icon

I feel that all images view should include or not include the group icon for all members, consistency etc.

**Comment by cascheberg** [comment]
I think that the group icon should not be included in the "All images" view, simply because it is currently not possible to delete them (or is it?). Also the image quality is not really that great.

But the problem is that group updates are sent as an `OutgoingMediaMessage` with the avatar as an attachment, which is therefore included in the all images view.

**Sender:**
```
GroupCreateActivity.handleGroupUpdate
GroupManager.updateGroup
GroupManager.sendGroupUpdate
MessageSender.send
MmsDatabase.insertMessageOutbox
MmsDatabase.insertMediaMessage
```

**Receiver:**
```
GroupMessageProcessor.handleGroupUpdate
GroupMessageProcessor.storeMessage
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
