### ISSUE TITLE
Performance issue on emoji keyboard's recent tab

### ISSUE THREAD

**Issue by 5boro** [signalapp/Signal-Android#3242]
I'm getting huge lag on this tab, no apps open other than the screen recorder, and I get the same behavior without it : https://pontet.eu/cloud/index.php/s/LuNviRH6mhuLCWT (Too big for a gif)
The old emoji keyboard was very responsive, even more than swiftkey's. And my phone responds well to other pretty demanding apps.
TS contacts did notice lag but nothing nearly as serious.

Log : https://gist.github.com/anonymous/eb35ed7221ad3754a50d

**Comment by mcginty** [comment]
Wow, yeah there's definitely something wrong there. Unfortunately, none of my devices have that kind of lag (same OS, different manufacturer). Will look into it. If you have Android studio and are feeling adventurous, in the CPU tab there's a "Start Method Tracing" button. If you can get a method trace from that device, that would go a long way in diagnosing.

**Comment by 5boro** [comment]
Sure, I already have the project setup.
One thing i noticed tough is that swiftkey doesn't add the just typed emojis to the recent tab, TS does...
Could it be constantly refreshing?

**Comment by 5boro** [comment]
@mcginty Is there a way to do this without uninstalling the app and changing keys?

**Comment by johanw666** [comment]
If you are rooted, Titanium Backup is your friend. Backup first before testing.

To speed up testing, you can switch between different versions quickly with Appdowngrader (requires root): https://play.google.com/store/apps/details?id=com.pyler.appdowngrader&hl=en

As long as you know what you're doing (don't downgrade to a version wirth a different database structure) this will work well.

**Comment by 5boro** [comment]
Well, there were database changes in the last version : 9c2f14dade14349b31d9c266dc2bba2b574da9b6

**Comment by 5boro** [comment]
Here are the tr

**Comment by mcginty** [comment]
Wow, it looks like Jackson's ObjectMapper and JSON stuff is taking an incredibly long time, which is in turn delaying the FragmentTransaction from happening.

![screen shot 2015-05-23 at 2 57 18 pm](https://cloud.githubusercontent.com/assets/373823/7785875/522fe6e4-015c-11e5-99c4-034fcfaa2b56.png)

**Comment by johanw666** [comment]
"What's the advantage of Titanium Backup over simply exporting messages in TS, does it backup keys?"

Yes, it backups everything. The plaintext export only exports messages as SMS - when you read them in they show up in green instead of blue.

**Comment by moxie0** [comment]
@johanw666 Using titanium backup with TextSecure will seriously fuck up your TS install, break communication with all your contacts, and require you to reinstall TS from scratch.  I don't recommend it.

**Comment by johanw666** [comment]
@moxie01 AFAIKyou should re-initiate secure sessions if you have sent or received encrypted messages since your last backup - since the batch of available session keys has changed by this that is to be expexted. I assume these were the same problems the removed encrypted backup option had, and why it isn't coming back anytime soon.

If you use the setup (mostly) for testing - do your testing, backup, install new version, restore - with no messaging in between - it should work.

BTW, I used TB to get TS working on a tablet: backup old install on phone and store the backup, install on the phone using a temporary simcard, backup, make new backup, transfer new backup to tablet, install TS on tablet (from apk), restore new backup on tablet, restore old backup on phone. All worked perfect, but I did not receive or sent anny messages while I was doing this.

**Comment by 5boro** [comment]
I had to factory reset my device to upgrade to android 5.1 and I can't reproduce this issue now.

**Comment by rhodey** [comment]
thanks for checking back in @5boro. @mcginty this seems like something that won't happen again, I'm thinking close, hbu?

**Comment by mcginty** [comment]
Eh, let's leave open to async-itize the JSON stuff, but keep it low priority unless others report experiencing it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
