### ISSUE TITLE
TextSecure/RedPhone don't support fully the Mexico numbering plan

### ISSUE THREAD

**Issue by ciaby** [signalapp/Signal-Android#3360]
I just stumbled into a peculiar thing of the Mexican phone network.
Internally, most people just use the mobile number without any international prefix to send and receive numbers (for ex. 55 1234 5678).
You can also use the +52 prefix, and normally it works. However, when registering with TextSecure, sometimes +52 is sufficient. Other times you need to put +521 (the additional 1 is used to distinguish between fixed and mobile phones, a purely historical reason).
So, when you send or receive messages, sometimes it's just the number, sometimes it's +52, sometimes it's +521. This seems to confuse a lot the TextSecure/RedPhone server, and in many cases two registered (or re-registered users) can't talk to each other unless they first send a secure SMS, do the key exchange over SMS, and then they can use the push method.
I know, it sounds weird, but that's Mexico ;)
Please have a look at it and see if it's possible to merge the +52 and +521 numbers into a single identity.
Cheers

Ciaby

**Comment by mfb** [comment]
https://en.wikipedia.org/wiki/Telephone_numbers_in_Mexico#Dialing_a_cell_phone_in_Mexico_from_abroad

**Comment by moxie0** [comment]
@mfb Yeah the server should be adding a 1 now.

**Comment by ciaby** [comment]
Thanks a lot! :-***

**Comment by mfb** [comment]
As far as the client side goes, my hypothesis is that if my American phone gets an SMS/MMS from +52 ###, Signal will need to send replies to +52 1 ###

**Comment by mfb** [comment]
another anecdotal data point that leads to problems: at least some folks in Mexico are registered twice with Signal - with and without the "1".  but they can only receive messages for one of these, of course.

**Comment by ciaby** [comment]
Yes, that's one of the issues. Then, depending on the address book of your contacts, you can be contacted on one or the other... Which makes things interesting from a key-exchange perspective :)
Is it possible to merge all these double numbers into a single entity?

**Comment by mfb** [comment]
here's a debug log from someone who's in mexico and is having trouble messaging /some/ of their contacts (they get "error al enviar"): https://gist.github.com/anonymous/78fd7a73354ef13a2b08    I'm not good enough at reading these logs to know what's going on :)  I asked this person to unregister one of their numbers (the one with extra "1") so we'll see if that helps.

**Comment by mfb** [comment]
I'm not on the ground in Mexico so hard for me to have a good grasp of how well things are working, but unregistering the other number seems to improve things.  Mexican users might have to wait until their pre-existing contacts write them again for a secure conversation to be re-established.

**Comment by takahe** [comment]
Hola, the problems still persists between users of +52 and +521. I've changed my number and my contacts to +52 XXXX WITHOUT the 1. That seems to work better. But it fails with the friend I was testing that has my numberas +52 1 ...
So I think we need a clear recommendation OR (maybe better!) the server "knows" the issue (so that I can write to +52 AND +521) like the international calls (tried with sip and skype) where both versions work).
(After the switch to +52, sometimes both sides need to change and delete +521 contact entries and need to "reiniciar sesión segura").
(My signal is 3.9.1, android 4.1.2, provider telcel)

**Comment by takahe** [comment]
Hola, update: 
> But it fails with the friend I was testing that has my numberas +52 1 ...
that was true, because we didn't "reinitialized the session" AND the friend had my number still with the "1" in her contacts.
So again:
- signal should recognize the numbers +52 xxx and +52 1 xxx as the same (as signal contacts).
- signal msgs to a contact with "+52 1 xxx" but registered as "+52 xxx" should find it's way somehow...
(thanks a lot for the great work!!!! I was waiting for Signal for so many years!!!)

**Comment by zurwolf** [comment]
Hello,

I have found a couple of weird side effects because related to this bug. One of them occurs when I create a group chat, were some of the participants have differences in their contacts list (some doesn't have the international prefix, some have the +52 and others have the +521), leading to conversations were some of us can read all of the messages, others can send to all but only read the replies of some, and some that can read the replies from all but cannot send to some.

Also, I've been looking at the way Whatsapp seams to solve this, which is basically normalizing all the numbers at the registration stage and also when retrieving them from the contact list. They normalize them by enforcing the +521 xxx xxx xxxx format. That way the Mexican numbers should match their local and international contact's.

So my proposal is to basically do the same and normalize the Mexican numbers at registration and also when retrieving them from the contact list. What do you think?

**Comment by jeremymasters** [comment]
@zurwolf Is this still an issue?  I have some friends from mexico who might be interested in using signal but wanted to wait until this is resolved.

**Comment by zurwolf** [comment]
@jeremymasters I haven't tried lately. Maybe things have change since last year.

In case you need to know how we solve it back then. We decided to register to Signal and store our mutual numbers with the +521 xxx xxx xxxx format, and haven't seen any issue since them.

Basically you needed to have your friends numbers stored in your contact list with the same format as they register to Signal so they match in Signal's servers. But I'm not sure if that is still needed.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
