### ISSUE TITLE
Notification reappears every time I open the app

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3384]
I tried to search among the existing issues but I couldn't find it.
This issue is best described with this scenario:
1. I receive messages from A and B in two different private chats
2. I open textsecure to read only the messages from A (I want to read those from B later), and I swipe the notification
3. I press the home button
4. Now I want to send a message to C, so I open TextSecure. ---> the notification of the messages from B appears again

This is a little frustrating when you want to temporarily tune out some people -- having a notification being displayed just because you're opening the app doesn't make much sense in my opinion; displaying it one time should be enough
Thanks!

**Comment by rhodey** [comment]
seems that this is still an issue, related #3312 & #2952.

**Comment by moxie0** [comment]
@rhodey I think this is unrelated to those issues. @oaim Is just saying that every time we rebuild the notification it includes all unread messages.

**Comment by oaim** [comment]
@moxie0 I'm not sure exactly what you mean by "when we rebuild the notification", but when in step 4 I open the conversation with C I haven't gotten any new messages -- just the same notification.
Actually, a cleaner way to reproduce the bug is this:
1. get a message from A
2. swipe the notification without reading it
3. open textsecure
4. open a conversation with anyone but A -- now the notification from A should have reappeared

Is it clearer now?

**Comment by rhodey** [comment]
thanks for the clarity @oaim, @moxie0 is correct, I shouldn't have tagged those issues as related.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
