### ISSUE TITLE
Feature request: Auto backup

### ISSUE THREAD

**Issue by rbirtles** [signalapp/Signal-Android#339]
The option to schedule backups to either the SD card or somthing like google drive/dropbox/etc would be great.

I lost all my texts due to a bad pushed rom update. An my TitaniumBackup backup had gone foobar and left me high and dry. I have a real bad need for some of the texts to be used in court so I am now left having to go to my phone provider and ask for a copy of the texts (fingers crossed)

**Comment by aesahaettr** [comment]
Any updates on this? It's been a long time since the last message on this feature request thread.

**Comment by moxie0** [comment]
Hey @aesahaettr welcome to our issue tracker, but keep in mind that this isn't a discussion forum. The mailing list or the support center are the appropriate places for that.  If an issue is open, we're tracking it.  Please only post here when you have new information to add to an issue, rather than things like +1 or asking for updates.

**Comment by aesahaettr** [comment]
Okay, sorry. Thanks!

**Comment by HDCP** [comment]
Automatic/Scheduled backups and the ability to schedule the sending of messages are my two most wanted features for Signal Messenger on Android.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
