### ISSUE TITLE
option to send text with multiple recipients as multiple sms

### ISSUE THREAD

**Issue by jjculber** [signalapp/Signal-Android#341]
Instead of sending an mms, send each individual the same sms.

**Comment by derWalter** [comment]
My GF just lost over 100€ because her SMS invitation to her friends to her birthday party got automatically converted to MMS.
When the phone did not send the MMS she tried it again, resulting a load of MMS. I guess due not being connected to the internet, the phone could not send it. When she finally connected to the net, they flushed out and flooded her friends and now her phone bill.

She has free sms but MMS are horribly expensive.

Maybe you can change that? like giving the users a big phat warning that a tsunami of cost is coming the crush em and giving em the chance to use sms instead of mms!

ps.: conversation feature is mostly not wanted at all, because
most people dont want that all contacts get all the other numbers as well!

**Comment by ajgpitch** [comment]
Doh! Hangouts don't do it no more :(

**Comment by comamondo** [comment]
Me too is missing that option - even receiving MMS is expensive in my country and it's really annoying to copy & paste every text to another contact...

**Comment by ineffyble** [comment]
It's also worth noting that a Group MMS creates a group chat and exposes the numbers of all recipients to each other, right?

**Comment by augustseptember** [comment]
I support this feature request as well. 
Because: 
1. Sending mms is very expensive for me.
2. Not all of my contacts have phones that can receive mms

**Comment by paxperscientiam** [comment]
Would someone explain like I'm five the distinction between conversation mode and broadcast mode? I don't get it.
