### ISSUE TITLE
Support diversity emojis and skin tone modifiers

### ISSUE THREAD

**Issue by wp9015362** [signalapp/Signal-Android#3556]
Hello,

so, apparently you finally made the switch for 2.22.0:

https://github.com/WhisperSystems/TextSecure/commit/9a18be0a6194d4dd8ef420e9b567b1d7ce69c613

And you even seem to use [the updated set](http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x).

But:

Apparently the diversity Emojis are missing.

Could you please add the diversity Emojis and add the skin tone modifier feature to the Emoji drawer?

Like this for example:

http://img.svbtle.com/0v70lxzkamb36w.png ([Source](http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x))

![Image](http://img.svbtle.com/0v70lxzkamb36w.png)

?

Regards

**Comment by wp9015362** [comment]
Apparently WhatsApp for Android has also implemented the skin tone modifier feature for it's built-in Emoji drawer now (and includes the ["Vulcan Salute" Emoji](https://github.com/WhisperSystems/TextSecure/issues/3557)), see the following article and screenshots:

http://www.androidpolice.com/2015/06/30/live-long-and-prosper-whatsapp-adds-skin-tone-emojis-and-spock-vulcan-salute-on-android/

Regards

**Comment by Dyras** [comment]
Has the plans of implementing this been scrapped indefinitely? I really don't care about this being implemented, I'm just curious.

**Comment by heyimgay** [comment]
It's an open issue but no one is currently working on it.

**Comment by xiyote** [comment]
I fully support having diversity emojis, but if we are stuck without, can we at least have a real skin color instead of the cartoonish yellow in the meantime?

**Comment by Dyras** [comment]
@xiyote When Android N comes out we will get even more emojis, presumably Moxie and co is waiting for that.

Personally I don't see the issue with the emojis we have right now, but a female friend of mine keeps complaining over the lack of new emojis so... I guess this is important for some people.

**Comment by jjohns71** [comment]
I found this [github project](https://github.com/iamcal/emoji-data) that has all the new apple emoji's including the various skin tone emoji's as both [64px files](https://github.com/iamcal/emoji-data/tree/master/img-apple-64) and [160px files](https://github.com/iamcal/emoji-data/tree/master/img-apple-160). 

How can I help to get this implemented, does it need to be in the same format as the existing emoji in the [Signal Android assets directory](https://github.com/WhisperSystems/Signal-Android/tree/master/assets)?

**Comment by moxie0** [comment]
Hey @jjohns71, that's exactly right.  We'd need sprites formatted into pages, one page for each emoji section, and the EmojiPages.PAGES array updated with the corresponding EmojiPageModel data.

**Comment by mcginty** [comment]
@jjohns71 https://github.com/mcginty/spritegen/blob/master/spritegen.go was written to make sprite sheets out of the noto emoji, but it could be tweaked to make a new spritesheet for apple emoji. Hope that helps.

As I recall, a lot of the new emoji are formed from two (or more? but I think two) emoji codepoints. Right now, `EmojiProvider.emojify()` and all the drawable code runs using individual codepoints, so I'm guessing that will also need to be refactored before the newest set of diversity emoji will work.

Also, the PAGES *array* might need to turn more into a PAGES *tree* (or you will otherwise need a way to know which emoji the skin tone modifiers can be applied to) to accommodate the UI where the simpsons-style "parent" emoji can be expanded into its skin-toned children selector.

Good luck!

**Comment by tannenzaepfle** [comment]
Hi, is this still being worked on? I'd also like to see this added.

**Comment by srfinkel** [comment]
I'd love to see this added. And if there's anyway to help? I'm sad that there's no taco emoji. #tacosforlife.

**Comment by gkubed** [comment]
Also in favor of having this added. Everyone seems to be bothered that I don't see exactly what they're trying to convey, which I guess bothers me too.

**Comment by devurandom** [comment]
I somehow expected that `Settings > Chats and media > Use system emoji` would allow me to use different coloured emojis, since I expected this to be a feature of the Android keyboard. Is this assumption wrong? I'm confused, since I have the issue in multiple apps and I don't know how emojis are supposed to work in Android.

**Comment by DarthSpock** [comment]
I would like to see this feature implemented as well.

**Comment by haffenloher** [comment]
@DarthSpock please [don't bump issues](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues). You can use GitHub reactions instead if you want to show support for a feature request.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
