### ISSUE TITLE
quick reply draft != regular draft

### ISSUE THREAD

**Issue by turtlekiosk** [signalapp/Signal-Android#3865]
The draft saved for a quick reply is different than the one I wrote in the app normally. If you type a message in quick reply and don't send it, and open the same conversation in the app, this draft will not appear.

**Comment by junitas** [comment]
Do you have any more information on the behavior of this bug (observed vs expected) or how to reproduce?

**Comment by 2-4601** [comment]
Related #3494?

**Comment by FeuRenard** [comment]
### Bug description
A draft saved when leaving the quick reply window with the back button overwrites a draft saved in the regular conversation.

### Steps to reproduce
- open a conversation
- enter something in the input field
- leave the conversation, so that a draft is saved
- close Signal
- receive a message in the conversation where you have a draft saved
- hit "answer" in the notification to enter the quick reply panel
- type something
- leave the quick reply panel with the back button
- open Signal
- open the conversation you used above
- notice that the draft from the quick reply panel is shown and the "regular draft" is gone (forever)

**Actual result:** Quick reply draft overwrites regular draft.
**Expected result:** Not sure, which would be best. Maybe by closing the quick reply panel no draft should be saved at all? Or show the regular draft in the quick reply panel?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
