### ISSUE TITLE
Install TextSecure on external SD card?

### ISSUE THREAD

**Issue by apmon** [signalapp/Signal-Android#4065]
There are some devices with very limited resources, particularly with limited internal storage where even the comparatively modest storage requirements of TextSecure can be an issue.  Would it be possible for TextSecure to be installed on external SD card for those that have one? It looks like all that is necessary to allow this is to add a line in the AndroidManifest.xml [1].

[1] http://developer.android.com/guide/topics/manifest/manifest-element.html#install

**Comment by poacher2k** [comment]
This would be much appreciated.

**Comment by poacher2k** [comment]
@moxie0 or @mcginty: is this something you could look at? My SO and myself practically can't use Signal - although we really, really want to - because it fills up our internal storage, which in turn makes other functions stop working entirely. 

Changing one line of code would enable users to move the app to the SD card. Is this something you could consider?

**Comment by moxie0** [comment]
Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
