### ISSUE TITLE
Can't send multiple sms

### ISSUE THREAD

**Issue by psohm** [signalapp/Signal-Android#413]
Hello
I have a nexus 4.
I can't send the same SMS to multiple persons. I only tryied unencrypted SMS for this case.
The diffent SMS are noted as "Sending" and it is never sent.
(If I send one SMS, it is working)

regards

**Comment by kwantenmechaniker** [comment]
another +1 for @SanderGit, this is a crucial feature imho.

i have been missing this functionality ever since i switched to ts and worked around it by manually forwarding sms to multiple people, which is annoying to say the least.

it's very clear that this can't work in the same way as ts group chat, and (as far as i'm concerned) it's not intended as such. i'd want this to be a broadcast-only feature, working with both secure and unsecure contacts in the way the standard messaging app does.

please, please add this.

**Comment by bisam** [comment]
+1 for @generalmanager 

I got most of my family to use it because of the "you can use it instead of your SMS app"-argument.

**Comment by tknapstad** [comment]
+1

The only feature which prevents TS from being an acceptable replacement app.

**Comment by gyger** [comment]
I'm not sure if SMS is a common communication tool in the states, but it is in several countries in Europe and also in the mountains where datachannels are often not usable. Push Messages are then delivered late or even deactivated to safe battery as it is in the new Battery Saving Options from Android. SMS is in a clear advantage here.

Is there a reason why this feature is not implemented? Or is there an interest in implementing this feature from the developers view?

**Comment by mcginty** [comment]
Please hold back from the "+1" comments; they make notifications more meaningless for the developers. We know people want multiple SMS. We accept pull requests, but no, additional work on legacy protocols is not in the short-term roadmap.

**Comment by oursgris** [comment]
I agree with you mcginty, people shouldn't +1 but I disagree with your legacy protocols ..
OMHO SMS are not dead and I think a lot of people use TextSecure only for SMS. It is my case and I stopped to use TextSecure because of that feature
MMS are slow, now reliable, and not readable for everyone.
If I send a grouped SMS for my friend which will be transformed to MMS, I'll have some friends who will answer me that they can't read my MMS. I can't ask everyone to have MMS well configured. I know also people who have a simple phone. They doesn't care about MMS.

**Comment by st7** [comment]
SMS is not a legacy protocol. Yes, it is old. Not legacy. SMS are reliable. That's why this old protocol is still in use very much. Since Android 4.4 there is no proper SMS-App on Android anymore. There is just hangouts, that many people may not want to use. They could switch to TextSecure, but there is this particular missing feature. It a pain. The ability to send SMS is the only reason for me to use TextSecure. As later Android-Version push to the marked this is your chance to close the gap for those who care about privacy.

Anyways, thank you very much for this nearly perfect app.

**Comment by VorpalBlade** [comment]
The other issue that means SMS should not be considered a legacy problem is that MMS is prohibitively expensive in at least some parts of Europe (such as Sweden). If you want to send messages to multiple persons (some of who might not be using TextSecure), SMS is the only viable option.

**Comment by Polynomdivison** [comment]
I don't know if it references to this topic:

When I'm in an Groupchat I can select send "unsafe sms". But when I'm sending this message it's a textsecure message...

![Picture](http://i.imgur.com/UcHNr6w.png)

**Comment by daryltucker** [comment]
https://github.com/WhisperSystems/TextSecure/issues/1762

**Comment by Thunderpig72** [comment]
I don't get why this hasn't been added yet. Can we get an update on this topic? Is it on the roadmap at all?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
