### ISSUE TITLE
Incoming Audio & Video thumbnails looking faded in light theme

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4159]
The alpha level let's to much background shining through.
That makes the thumbnails look dirty.
The thumbnails in dark theme are always plain white...

(Also the video thumbnail should have white bars at the top all the time IMO)

**Comment by McLoo** [comment]
![_20151001_141957](https://cloud.githubusercontent.com/assets/5326916/10220482/26d0c6aa-6848-11e5-86b9-9a5683d9df51.JPG)

![_20151001_141933](https://cloud.githubusercontent.com/assets/5326916/10220484/2f257292-6848-11e5-9f43-e6ecce34cd54.JPG)

![_20151001_142218](https://cloud.githubusercontent.com/assets/5326916/10220474/1ee196d6-6848-11e5-9a89-2cba3ad8697e.JPG)

**Comment by Dyras** [comment]
Personally I think the video picture should be replaced entirely. It doesn't really scream "video" if you ask me.

**Comment by jeremymasters** [comment]
I agree that the icons are too much.  Maybe I'm just being fussy, but they seem too large and don't really "feel" as nice as the rest of the app.  I was thinking that @mcginty was working on a video preview showing up instead of that video icon; maybe I'm mistaken though.

**Comment by mcginty** [comment]
@jeremymasters that's the goal, yep. libtextsecure just added support for including thumbnails with outgoing media messages so this will be a fallback only in the future.

**Comment by jeremymasters** [comment]
What about just making both the bubble and the icon smaller since they both play outside of ~~TS~~ Signal?  Maybe have the icon inside of a box or something.  Sorry, I'm sucky at art otherwise I'd mock it up more.  Since you'l be doing a preview, this shouldn't be made to be too much work.  I'd say the smaller bubble (2/3 current height/width) + smaller icon (75% the new size of the bubble) would work in the interim.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
