### ISSUE TITLE
Allow removing attachments

### ISSUE THREAD

**Issue by johannesjh** [signalapp/Signal-Android#4242]
Please add the possibility of deleting attachments from received and sent messages.

This functionality would benefit usage on devices with limited storage capacity. E.g., my personal situation is that the many pictures and videos I receive are filling up my precious storage space. I would like to delete the pictures but keep the message texts. (Also compare #4065 for a related request to allow storing messages on the external SD card).

**Comment by jeremymasters** [comment]
I just long press the message with the attachment and then delete it.

**Comment by merkste** [comment]
I think the request was to remove the attachment only while preserving the text.

**Comment by johannesjh** [comment]
yes, exactly. to remove the attachment only while preserving the text.

**Comment by langboost** [comment]
Other similar but slightly different use cases would call for the ability to not download the image by default. This is particularly nice when you have a group of people who feel the need to send an inspiring picture of a sunrise every morning with some sort of inspiring quote embedded into the image. Every day. Sometimes multiple times per day. :) I suppose I could always find new friends...

**Comment by mcginty** [comment]
@langboost You can already do that. Settings -> Chats and Media -> Media auto-download.

**Comment by jeremymasters** [comment]
I think he might be talking about a per-user basis.  Maybe that could work like the ringtones.  All users follow the default settings unless you change that particular user's settings.  Like "Never allow auto-downloads of anything from a specified set of users.  I guess that would be more like "blocked users" but "blocked auto-download users".

**Comment by 2-4601** [comment]
![could not resist](https://cloud.githubusercontent.com/assets/174176/10469533/a87cd4bc-720e-11e5-922a-aa8b12ae7252.jpg)

**Comment by johannesjh** [comment]
To bring the conversation back to a serious level: This is what the functionality for removing attachments could look like in the UI.

![mockup](https://cloud.githubusercontent.com/assets/581188/10476262/5b94f114-724c-11e5-80c3-af8046d56833.png)

**Comment by bhabba** [comment]
1. I think it would be very handy to also add a global option for auto-deletion of attachments after exceeding a certain size limit: Under _Settings_ -> _Chats and media_ -> _Message trimming_ there should be an option for <ins>_Delete old media_</ins> where you can set a maximum storage space limit in MiB. Ideally the current free storage space of the partition where Signal's attachments are stored should be shown besides as a helpful orientation.

  When exceeding the set limit the oldest media attachments should get deleted until the total media size has fallen below the limit again.

  Of course this option should be disabled by default.

  This feature would be most useful in combination with the implementation of https://github.com/WhisperSystems/Signal-Android/issues/283 so that you are able to prevent your most precious attachments from automatically disappearing into nirvana without having to manually export and save them outside of Signal.

2. Additionally it would be awesome to have a per conversation option as well for this (which again of course would be disabled by default). So under _Conversation settings_ of each conversation you would find an option for <ins>_Delete old media_</ins> but this time in number of attachments ("keep last x media attachments"). If a global "media storage limit" was set before, an extra notice should point out that attachments might be deleted before reaching the maximum number entered here due to insufficient storage space left.

  This would be very helpful for the scenario @langboost conceives or for group chats where people randomly post attachments (mostly images) which you essentially want to open one time at most and then forget (i.e. delete). That way the tedious manual deletion of such "disk space munchers" wouldn't be necessary.

**Comment by Calefornia** [comment]
Is there a way to quickly export all photos and videos from every chat? Preferably something that doesn't involve digging through the file system and copying folders to a desktop. Can we save to our device's photo album?

**Comment by patzi** [comment]
I think the "delete all attachments" part would be a nice addition to the already included #3975. So I think this function should be at the same place as the "save all images" action and not as an extra option in the conversation menu like @johannesjh proposed in the second row of his mock-up. So this two functions on all images would be at the same spot.
Over all the longer signal installs exists the more pressing this gets :)

BTW: @Calefornia I think the quick export of all images what you are looking for is what was introduced with #3975

**Comment by floriangosse** [comment]
I think #5515 is a related issue.

**Comment by notspecified** [comment]
I would also welcome a useful and working solution for the problem with decreasing storage over time through sent and received media!
I would love a solution like on the attached screenshots. Is it possible to implement this?

![screenshot_2017-05-05-10-17-47](https://cloud.githubusercontent.com/assets/5119558/25755975/54cb1ab8-31c5-11e7-8579-428b2168e86d.png)
![screenshot_2017-05-05-09-13-01](https://cloud.githubusercontent.com/assets/5119558/25755989/5e694d4c-31c5-11e7-8143-f9038326c1f0.png)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
