### ISSUE TITLE
readd Signal contacts

### ISSUE THREAD

**Issue by obifur** [signalapp/Signal-Android#4338]
Actually this is a feature request because of a bug..

The problem started months ago with several duplicate contacts (shown as duplicates in DavDroid- and TS phonebook).
After deleting the duplcates I realize they are now missing as "Signal contacts" when starting a new conversation.

I know that the duplicate contacts issue is already known, but how can I force TS to search and readd all known Signal-contacts without registrating again?

**Comment by johanw666** [comment]
Pull down in the menu, or go to Android settings, accounts, select Signal and resync.

**Comment by obifur** [comment]
I tried, but it doesn't work

**Comment by riyapenn** [comment]
Sounds like more of a support issue, you are welcome to email support@whispersystems.org.  This should resolve after you reboot your phone.

**Comment by obifur** [comment]
A reboot does not help

**Comment by x12x** [comment]
Yes, I can confirm this is a bug. Please reopen, it's driving me crazy.
Recently I had to delete all my contacts from my phone, and then when I added them back none of them appears to be using Signal -- they're all in the "all contacts" section. I'm running 3.9.1. How could this even happen?

**Comment by sashw** [comment]
I can confirm this bug as well. I had for some reason multiple local phone contacts. To get rid of them, I deleted all my contacts from my phone and resynced them with DavDroid from my server. Since then Signal hasn't changed any of my contacts to add them as a Signal user. I'm running Signal 3.9.1 on Android 5.1.1 (CM 12.1) on a rooted device. It seems that Signal doesn't check the contacts anymore for already known numbers. Maybe this could be related to issues #4819 #4803 #4447.

Things I tried: Sync Signal via Settings -> Accounts; refresh contacts in Signal itself. When I display only Signal contacts, none of the former Signal contacts are shown. In fact only my own contact shows up. 

I can also confirm that this happened on a non-rooted Samsung Galaxy S4 mini running Android 4.4 and Signal 3.9.1. There the contacts had been deleted and resynced with Google. The only "solution" which helped to add Signal users in contacts again was to reinstall the app.

**Comment by swunderlich** [comment]
I can confirm the bug on 3.10.0. Galaxy S5 Mini 5.1.1

**Comment by donnm** [comment]
I have this problem with 3.11.1 on a Nexus 5 running CM13. Set up DAVDroid contacts sync and deleted local contacts, now none show up in Signal. They do show up in SMSSecure 0.13.2, however (is it not a fork of an earlier version of Signal?)

**Comment by maius** [comment]
Confirming this bug on a Samsung Galaxy S5 mini with CM 12.1.

- Accidentally deleted a bunch of contacts in my local adressbook --> Contacts disappeared in Signal
- Restored the contacts from my backup  --> Re-syncing Signal does not bring contacts back into Sigal contact list.

I tried the following without success:
- Restarting Signal
- Rebooting the phone
- Yelling at my phone....

A quick fix would be highly appreciated.

**Comment by riyapenn** [comment]
@maius Go to Android Settings > Accounts > Signal > Menu > Remove Account > then Resync.  Contact support@whispersystems.org for further troubleshooting.

**Comment by maius** [comment]
@riyapenn Thanks a lot for the prompt answer. 
Removing the account will result in the loss of all message threads and group conversations. I will wait for that until Signal can provide a full backup (see other issues, i.e. #4577).

Motivated by your comment I tried to switch off and on: Signal Settings -> Advanced Settings > Signal Messages and Calls 
That helped to bring back the names to the conversation list, however syncing the address book does not bring the lost contacts back. 

Therefore this issue to my understanding is a topic for this thread, rather than a support issue and I hope you can find a solution.
Thanks anyway to the Signal team for your constant and good work.

**Comment by haffenloher** [comment]
> Removing the account will result in the loss of all message threads and group conversations.

No, for that you'd have to uninstall the application. Just remove the account, open Signal, tap the blue :pencil2: button, pull down the contact list to refresh it and see if the contacts are correctly associated again

**Comment by maius** [comment]
> No, for that you'd have to uninstall the application. Just remove the account, open Signal, tap the blue :pencil2: button, pull down the contact list to refresh it and see if the contacts are correctly associated again

@haffenloher Thanks, that was an important info. I was mislead by the warning android sends when removing the account.

Doing so brought all contacts back into the Signal address book.
:arrow_right: I would recommend to add this info into the FAQ.
