### ISSUE TITLE
Limit invite - I'm asked to invite "Google" to Signal

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4436]
Receiving verification codes from number "Google"
I guess am asked for the invite cause I have Google with number "Google" stored in the phonebook (to add a contact photo - and only amazon photos are embed in signal)
Same for various banks or other 2-way authentications with non-replyable numbers.

Though it would be nice to have them use signal, it think the invite should be only available for E164 numbers.

**Comment by mcginty** [comment]
I'm going to make this logic smarter (read: less annoying). Since there are other automated non-shortcode numbers like TextSecure's verification numbers, we might want to have a different heuristic than that.

Perhaps we should only ask for invite if there is at least one incoming message and one outgoing message? That way automated numbers aren't annoying you and it's only (mostly) real people you converse with.

**Comment by Kyushi** [comment]
Totally agree with part 2 of xurizaemon's comment. Especially with the keyboard open my screen real estate is rather small, covering previous messages with the invite reduces this by another quarter or so. When I try to click it away, more often than not the invite message is activated, so that I have to remove it before i write.
I am happy to promote Signal, just let me choose when and to whom.

**Comment by odd-meta** [comment]
I echo the sentiment in making this a feature users can tune. In trying to introduce Signal to some of my less technical family, these notifications have been the deal breaker. Nearly none of their contacts use Signal, and when the choice is X out of the notification for every contact or just go back to their old messaging app that worked fine; it's hard to argue honestly that they shouldn't go back to their old app.

**Comment by dcherian** [comment]
Should also exclude the current phone number. I added my number as a contact so that I could message myself and got this 'invite' notification.

**Comment by treptrek** [comment]
I've just uninstalled myself and my wife's copy of this otherwise excellent app, for exactly this reason.  We upgraded phones, and it became obvious that clicking away a nag screen on each of her contacts was a deal-breaker. She asked if we could 'buy' signal to remove the ad... This issue is about more than E164 numbers; Signal is negating an excellent design with a spam-like, inelegant interface element. I know Signal needs to drive adoption, but the present invasive approach has driven us two to adopt elsewhere. I'll check again in a year and see if matters have improved.

**Comment by treptrek** [comment]
To be constructive:

Our use case might have been better addressed if the export function additionally exported whether the nag bar had been previously clicked away.  That would have left us with the original deal: a a nag-bar per new contact, rather than the prospect of dismissing our way through all our contacts again.  That said, I still would hesitate to give Signal to any less tech-savvy member of my family: too much noise-to-functionality ratio.  I would, however, pay to have Signal without this issue, and thereafter give it to less tech-savvy folk.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
