### ISSUE TITLE
Wrong file suffix on saving videos

### ISSUE THREAD

**Issue by rmueller83** [signalapp/Signal-Android#4536]
I just received a video within a group chat in Signal 3.4.0. When I save that video, it is saved to sdcard\Movies\textsecure-2015-11-14-131819.attach

To make it play in other apps I have to open a file manager and rename the video to textsecure-2015-11-14-131819.mp4

I would expect Signal to directly save the file as textsecure-2015-11-14-131819.mp4

**Comment by RiseT** [comment]
*I would expect Signal to directly save the file as textsecure-2015-11-14-131819.mp4*

Even better would be "**signal**-2015-11-14-131819.mp4"... :smile:

**Comment by rmueller83** [comment]
...or the original file name of the senders file ;)

**Comment by heyimgay** [comment]
This happens only when the file does not report a mimetype, so the video file didnt state it was an mp4 thus signal chose the default .attach as the extension.

**Comment by rmueller83** [comment]
That's not true:
```
$ file --mime-type -b textsecure-2015-11-14-131819.attach
video/mp4
```

**Comment by heyimgay** [comment]
Hey @mcginty i would like to give this a shot ive looked over the code and there is a check to see if the mimetype ==null and then it sets that attachment but that is not where it goes awry. I would love some tips on where to look

**Comment by agrajaghh** [comment]
@rmueller83 could you upload the video file somewhere? this would make it easier to debug...

**Comment by RiseT** [comment]
@rmueller83 Using the original file name could be a privacy issue, though. Same holds true for some embedded Exif metadata like GPS coordinates. Is this stuff stripped off before sending? No idea.

**Comment by rmueller83** [comment]
The sender just sent me the mp4 sample video (3rd download) from this page: https://support.apple.com/en-us/HT201549
And I also received it with .attach suffix.
He is using Signal 3.3.3 on Android 5.0.1, but I could not reproduce this in the emulator using the same versions. :-1:

**Comment by agrajaghh** [comment]
I cant reproduce it :smirk:  

Maybe its his device? What device is he using?

**Comment by rmueller83** [comment]
He is using a Moto G 2nd Gen with Android 5.0.1, I have a Moto G 1st Gen with Android 5.1.
Perhaps @bartz1 (from #4560) could also try the video and post his specs?

**Comment by JavaJens** [comment]
Regarding the information of the mime type, I think it is important to look at the results from the Android framework. See the referenced issue above.

**Comment by rmueller83** [comment]
This is an interesting finding, but it seems that the mentioned method is only called on the receiver side when the attachment is saved. So the saving of a certain mime type would always or never work, which is not the case. I think the misbehavior is due to the value of the contentType argument whose value seems to come from the sender.

**Comment by JavaJens** [comment]
@rmueller83 Yes, this is called on the receiver. But as mentioned there, some manufactures modify this map, so maybe this adds to the difficulty of reproducing: depends on sender/receiver pair.

By skimming the code, it seems that the value of the contentType could possibly come from this mapping as well.

**Comment by unrulygnu** [comment]
@rmueller83 , any chance you can attach a debugger, set a breakpoint on the following line, and try saving the problem video to see the value of `contentType`?

**`SaveAttachmentTask.java`**

        if (extension == null)

**Comment by rmueller83** [comment]
I just tried this via USB, but Android Studio only shows "No Debuggable Applications". :-(

**Comment by rmueller83** [comment]
Good news: I managed to let him send the sample video to my Signal instance running in the emulator. I cannot see the contentType and extension variables in the variables window (do I need to use a different way of building?) but if I step one line further, the debugger goes into line 125 (extension = "attach";) instead of skipping it.
![extension](https://cloud.githubusercontent.com/assets/2698076/11279804/f87a4386-8ef2-11e5-8e71-1f03397e6a4a.png)

**Comment by unrulygnu** [comment]
Ah, you can temporarily add `-dontobfuscate` to `proguard.cfg` and rebuild.  That will let you inspect local variables.  Someone else will probably chime in with a better way, though. :grin: 

Thanks for the followup!

**Comment by rmueller83** [comment]
Thanks, that works. Now I can see that `contentType = "video/*"` which leads to `extension = null`. It should be `contentType = "video/mp4"`.

**Comment by bartz1** [comment]
whoever takes care of this issue, please make sure you fix the problem with audio files too

**Comment by rmueller83** [comment]
@bartz1 which device does the sender of your audio file have?

**Comment by unrulygnu** [comment]
Awesome, thanks!  I'll hack on it later this weekend.

**Comment by rmueller83** [comment]
I just found another person with a Moto G 2nd Gen with Android 5.0.2 who sent me the test video. This time everything is fine, so the issue does not seem to be device-dependent.

**Comment by JavaJens** [comment]
@rmueller83 The question is: are they running the same (stock) Android 5.0.2?

**Comment by rmueller83** [comment]
Yes, they are both stock.

**Comment by unrulygnu** [comment]
Were the problem media files sent via a share intent from another app (rather than attaching from inside Signal)?  I found some creatures lurking there.

**Comment by rmueller83** [comment]
**YOU GOT IT!** If I share the video on my Moto G 1st Gen from within the gallery app, the suffix is broken in my receiving emulator instance too.

**Comment by rmueller83** [comment]
I just installed the new 3.5.0 beta and tried out the new voice message function. If I as the sender save my own voice message, it also gets an .attach suffix. :-(

**Comment by unrulygnu** [comment]
Teamwork! :smile:  I'm working on a fix.

**Comment by unrulygnu** [comment]
59f2446 temporarily stores encrypted file copies ("persistent blobs") of incoming media (via `ACTION_SEND` share), prior to their being processed and saved as actual attachments.  This works around URI permissions issues (losing them on app restart, etc).  The original media's MIME types, however, are not stored, and cannot be derived since the original filename and extension are also not stored. 

Draft media messages store the `AttachmentManager.MediaType`, which is used when processing a persistent blob into an attachment. Each `MediaType` has its own default MIME type, provided by its respective `Slide` subclass, in case `MediaUtil.getMimeType` returns `null`.  Attachments with the type-less persistent blobs described above end up with these default MIME types:

* `GIF` has a specific default of `image/gif`, so it is unaffected by this issue.
* `IMAGE` also has a specific default, `image/jpeg` (due to conversion/scaling process). This type is also unaffected by this issue.
* `AUDIO` and `VIDEO` have unspecified defaults of `audio/*` and `video/*`, respectively.  Passing these types to `MimeTypeMap#getFileExtensionFromUrl`, unfortunately, returns null.  This is why saving attachments of these types results in files with the fallback `.attach` extension.

There are several approaches to store the MIME types of these persistent blobs in a way that survives app restarts and device reboots.  Note that given the current architecture, the MIME types must be retrievable by URI (rather than `long id` as the blob streams are).  Here are a few options:

1. `SharedPreferences`: easy, but unencrypted. If MIME type/URI mapping is a security concern, this is a no-go.
2. Encrypted text files: a little less easy, but more secure if needed.
3. Database: harder, probably overkill.

I'm submitting a PR with an implementation using `SharedPreferences`.  It has tested well so far, and should be fairly easy to swap out with other storage methods.

@mcginty and others, please let me know what you think.  Thanks!

**Comment by x12x** [comment]
You're lucky if you can rename the file, I can't even remove the ".attach" and replace it with ".mp4" (for some reason I don't know)

**Comment by riyapenn** [comment]
Resurfacing for a user: https://gist.github.com/392cfe2fd28771090a0b1aca6113c6d1

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
