### ISSUE TITLE
Notification for new contacts

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#4572]
Signal gives you a notification, when it finds someone from your contacts on the service. It is basically a useful feature. But it needs some user control, I think.

For example I prefer that those notifications are silent and without vibration.

**Comment by generalmanager** [comment]
I like the idea! It helps keeping users updated on which of their contacts can be reached by the app and makes sure the user knows that Signal just became more useful/valuable to him/her because of the network effect.
Those not-very-invasive notifications on the top, which also appear when writing to a non-signal user for the first time, seem like the right way to do something like this.

**Comment by agrajaghh** [comment]
@moxie0 @mcginty are you okay with making these notifications silent? I could do a PR...

**Comment by moxie0** [comment]
I like that they alert. Maybe we should have them silent from 11pm to 9am, and add an option to disable them in the notification preferences as well.

**Comment by agrajaghh** [comment]
okay, sounds good. just to clarify, disable them completely or just mute them?

**Comment by cascheberg** [comment]
I support the idea of always silencing these since they usually do not require immediate attention/action, and they appear at a "random" time anyway.
Silencing them at certain times of the day is not quite user-friendly. Some people prefer to go to sleep at 10pm, some sleep during the day to work at night and so on. But I also wouldn't want to disable them completely since it's a useful feature.
(Apart from that, I usually have my phone in silent mode when I don't want to be disturbed...)

**Comment by tehabe** [comment]
When I hear a notification from my phone I expect a message but *XY is using Signal now.* isn't one. So I really prefer not hear or feel it.

**Comment by moxie0** [comment]
@agrajaghh The preference would be for disabling them completely.

**Comment by heyimgay** [comment]
What about a notify/silent/off preference

**Comment by haffenloher** [comment]
An alternative to hard-coded silent times may be to delay the notifications until the screen is turned on / the phone is in use - if that's feasible and not overly complex?

**Comment by jeremymasters** [comment]
Thinking about this, it seems like a notification that doesn't need to ring and could just be a visual notification that is there when you open signal the next time.

**Comment by mcginty** [comment]
You don't get the notification the instant someone registers (unless they have fantastic timing), so treating the notification as worthy of interrupting their life seems excessive. We don't want that boy who cried wolf situation with alerting notifications.

**Comment by agrajaghh** [comment]
> You don't get the notification the instant someone registers (unless they have fantastic timing), so treating the notification as worthy of interrupting their life seems excessive

I agree, but moxie likes it. What should I do now? :wink: 

OT but it recently happend twice to me that I added a new contact to my adress book, and got this notification, just to find out that the contact uninstalled Signal/Textsure a long time ago. This is really frustrating. for reference: https://lists.riseup.net/www/arc/whispersystems/2015-10/msg00032.html

**Comment by tehabe** [comment]
@agrajaghh @moxie0 I just want it to be quiet. Noises are for messages, I don't consider this a message.

For your OT thing: it should be discussed in a separate issue, but I know the feeling, it is not only important who is coming new to the service but also who stayed.

**Comment by moxie0** [comment]
@agrajaghh Let's start with what I said.  =)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
