### ISSUE TITLE
Play position of a deleted voice message is carried over to a newly recorded voice message

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#4655]
1. Record a voice message
2. Start playing the message and pause at 50% position
3. Delete the message
4. Record a new message
5. The playback position of the new message is at 50%

![george costanza answering machine 2](https://cloud.githubusercontent.com/assets/174176/11320250/29a20ea4-909b-11e5-9845-256acd844155.gif)

Signal 3.5.0
- Nexus 4, stock 5.1.1.
- Huawei U8800, ICS 4.0.4

Edit:
Log from Nexus 4 that goes through the steps:
https://gist.github.com/anonymous/8ab05021c0cbe6a2ab65

**Comment by FeuRenard** [comment]
This is caused by the behaviour of the RecyclerView. You can see that by trying the following steps:

1. Record a voice message (A).
2. Record another voice message (B).
3. Write/Receive some messages so that the two voice notes are not displayed anymore and are only reachable by scrolling up.
4. Record a voice message (B*).
5. Record a voice message (A*).
6. Now change the seekbar position of A* and B* as you like.
7. Scroll up to the other voice messages.

You will see that voice message B has the same seekbar position as B* and A has the same position as A*.
This position is only stored in the view. When the view disappears from the screen (deletion or scrolling) the view will be reused when scrolling up or recording a new voice note.
