### ISSUE TITLE
Draft in input-box is deleted - and reappears later

### ISSUE THREAD

**Issue by char32** [signalapp/Signal-Android#4729]
Problem:
A typed message dissapears as draf but reappears suddenly later on.

Hardware:
HTC One M8 - Android 5.0.1
Signal 3.5.2
Password set for Signal, but in unlocked state

Steps to reproduce:
- write a message (lines or so)
- i am not sure if I left Signal by the back key or not
- lock the screen with the power button (password as screen protection is set)
- wait a couple of minutes
- unlock the screen
- go to Signal
  ---> the text input box is empty. The draft vanished
- write a message and sent it
- leave Signal
- later on open Signal
  --> the draf of the old message (which vanished) is there again!

I could not reproduce this yet again. But I am trying.

**Comment by haffenloher** [comment]
I think this happens if your draft was composed using the quick reply view.

**Comment by 2-4601** [comment]
I might have also experienced this (without using the quick reply). But I have not been able to reproduce. Adding attachments could have had something to do with it.

In any case the quick reply draft bug is very reproducible: #3494

**Comment by McLoo** [comment]
Probably sth #4708 takes care of

**Comment by char32** [comment]
It happed with the normal Input box, not the quick answer one.

But yes it could be the same root cause like the linked ticket. Saving on onPause().

**Comment by FeuRenard** [comment]
I can reproduce the described problem by the following steps:
1. write a message
2. leave the conversation with a back-button (so that a draft is saved)
3. leave Signal
4. receive a message from the person you wrote in 1)
5. Tap the notification to get to the conversation. Then the draft is gone.
6. Go to the conversation list. The draft is still gone (no preview).
7. Enter the conversation again. The draft reappears.

**Comment by FeuRenard** [comment]
I can reproduce the described problem by another set of steps. Differences to my other list are printed bold.

1. write a message
2. leave the conversation with a back-button (so that a draft is saved)
3. leave Signal
4. **open your system's contact app**
5. **choose the person you wrote to in 1)**
6. **choose "Send Signal-Message to (...)".** The draft will be gone.
7. Go to the conversation list. The draft is still gone (no preview).
8. Enter the conversation again. The draft reappears.

I will try to work on this issue.

**Comment by FeuRenard** [comment]
I noticed some things working on this issue and want to write them down here:

- A disappearing draft when entering the conversation from outside Signal could be **more a feature than a bug**. Tapping on the notification of a new message maybe means, I want to answer it. But then the **draft would interfere with writing my answer**. But after sending my reply, it is not indicated, that a draft is still saved. It can be accidentally overwritten by a new draft or it will reappear in the future by entering the conversation from the conversation list. Note, that even the conversation list won't indicate a draft until the conversation with the draft in its input field is closed again.
- When you **share some text from a second app** and choose to share it via Signal, the draft clearly has to disappear. But after sending the to be shared content the draft is still saved but no indication is visible as described in the bullet point above.
- From your system's contact app, there are two ways of entering a conversation. You can use Signal's own "Message [phone number]" button or the default send SMS button. Using the latter option a saved draft will be shown in the input panel of the conversation. Using Signal's own button will let the draft disappear for this "session". This should be handled more consistently, I think. But **we have to make a decision, whether the draft should be shown when entering the conversation from the contacts app**. As far as I understand it, this can be solved in `SmsSendtoActivity.java`. There in the method `getNextIntent` the two contact app buttons are handled differently. The SMS button will use a path with the method `getDestinationForSendTo` and the Signal button uses `getDestinationForView`.

I suspect that the initially described issue in this thread was caused by entering a conversation from outside Signal. But before this can be solved, design decision have to be made like in which situations we want a draft to disappear (which introduces UX problems).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
