### ISSUE TITLE
[UI] Scroll bar changes its size in conversation view

### ISSUE THREAD

**Issue by art1fa** [signalapp/Signal-Android#4778]
When scrolling through a conversation, the scroll bar changes continuously its size.
Expected behavior: Constant size of scroll bar, just like in the message view

GIF:

![animated](https://cloud.githubusercontent.com/assets/11131859/11514149/495adbac-9877-11e5-8e7f-2a372f468cff.gif)

Device info: Nexus 5, OmniROM 5.1, TextSecure 3.6.0

**Comment by heyimgay** [comment]
I can confirm this. It is also not the case that old messages get unloaded and thus the scrollbar becomes larger. This becomes obvious if you look at the scrollbar of a longer conversation.

**Comment by cascheberg** [comment]
It seems that the length of the scrollbar increases with the number of message items that are currently visible on the screen. So it is shorter if you are seeing images or multi-line messages.

**Comment by unrulygnu** [comment]
https://www.quora.com/Why-hasnt-Google-fixed-the-scrollbar-length-problem-in-Android

**Comment by iambmelt** [comment]
Did a quick peek to investigate this.

Relevant class / layout
[`ConversationFragment.java`](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/ConversationFragment.java) | [`conversation_fragment.xml`](https://github.com/WhisperSystems/Signal-Android/blob/master/res/layout/conversation_fragment.xml)

At a glance, it doesn't look like [AbsListView#setSmoothScrollbarEnabled(boolean)](http://developer.android.com/reference/android/widget/AbsListView.html#setSmoothScrollbarEnabled(boolean)) will work because this layout is using [RecyclerView](https://github.com/WhisperSystems/Signal-Android/blob/master/res/layout/conversation_fragment.xml#L8).

Looks like this may have to wait until RecyclerView is enhanced per [this issue](https://code.google.com/p/android/issues/detail?id=78513) to include `setSmoothScrollbarEnabled` or some equivalent.

**Comment by unrulygnu** [comment]
`setSmoothScrollbarEnabled(false)` makes the scrollbar movement twitchy and distracting, probably not the desired user experience.

And if you look at [the source for `LinearLayoutManager#computeScrollExtent`](https://android.googlesource.com/platform/frameworks/support/+/master/v7/recyclerview/src/android/support/v7/widget/LinearLayoutManager.java), you'll see that the scrollbar thumb height still varies, despite what the docs say.  

I tested this a couple of weeks ago in `ConversationFragment#onCreateView`, right after `layoutManager` is declared and initialized.  There was much sadness.

To do this right, I believe we would need to compute the total height of the rendered list: an expensive proposition.  Any estimating or other workarounds will probably just result in other misbehavior, especially noticeable at the top or bottom of the list.

**Comment by McLoo** [comment]
maybe this can be fixed 
by adding fast scroll to #4696 

Can't remember that I've seen that the fast scroll bar changes size

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
