### ISSUE TITLE
Please add a share button for sharing media files in conversations to other apps

### ISSUE THREAD

**Issue by Dollarmannen** [signalapp/Signal-Android#4906]
As I have alot of friends using other messaging apps I would like to have the possibility of sharing media files from the conversations in Signal to other messaging apps.

**Comment by Kamul-PL** [comment]
My voice goes fit that too. For me this feature is crucial to switch from Google Messenger to Signal.

**Comment by FeuRenard** [comment]
Here is my attempt to solve this issue:
https://github.com/FeuRenard/Signal-Android/tree/mpa-share
Sharing to the stock [E-Mail app](https://android.googlesource.com/platform/packages/apps/Email/) of android and Allo for example works fine.

Unfortunately there is a problem with the [Android default MMS app](https://android.googlesource.com/platform/packages/apps/Mms/) (tested it for Android 4.4.4 & 5.1, probably occurs for many more apps). It crashes when it is chosen to share an image. The root cause of this problem is in the initial lines of [this method](https://android.googlesource.com/platform/packages/apps/Mms/+/master/src/com/android/mms/ui/UriImage.java#123) of the MMS app.
To fetch the shared file it attempts to use the `query()` [method](https://github.com/WhisperSystems/Signal-Android/blob/ec63f7014e5e67993ac0793cc94de092d2b7eca6/src/org/thoughtcrime/securesms/providers/PartProvider.java#L132) of our PartProvider. As of now this method is implemented to always return `null`. This causes the crash.

I am not familiar with the concept of a cursor and cannot estimate the security implications of returning a result for `query()`. I would be very happy if someone can provide some thoughts/help :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
