### ISSUE TITLE
Signal seems to "forget" a number is attached to a contact

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#4943]
I didn't take a picture of this, but it's really quite simple. I was chatting with a girl when, at seemingly random, her picture vanished and instead of seeing her name I saw only her phone number. I'll try to figure out a way to reproduce it, but until then please have two error logs:

https://gist.github.com/anonymous/9bfec6ce5c529c32bb89

https://gist.github.com/anonymous/54670ecb4e553926adcd

Something maybe worth mentioning is that this also happens for the girl I talked to, although not at the same time. We are both on Lollipop.

**Comment by 2-4601** [comment]
Possibly related #2612, #3387, #3432

**Comment by att1x** [comment]
It happens to me, too. Kinda randomly. But there is one thing noticeable : my contact app stores the mobile numbers in blocks. "National prefix" "area code" "subscriber number", eg. "+49 171 1234567".
When the issue is fired inside signal and only numbers are shown, there is no block presentation. The number would become "+491711234567" and hence the related contact is not shown. And in addition when I click on "new message", the contact's name is related to the number in non-block-format and only the contact picture is missing (changed into "#").

**Comment by KommX** [comment]
Today, this happend to me too.
I updated my phone to Android 6 and after that **some** of my contacts are now only displayed by their phone number.
In contrast to @att1x statement, for me they are still displayed in blocks.

**Comment by losingkeys** [comment]
This happens to me too. It has only happened to contacts who also use signal. Their name and stuff is fine for awhile, but eventually it will only show their number.

**Comment by rajeevn1** [comment]
This happens when the base contact is deleted/ recreated and the link between contacts is lost.

Merging/ Linking contacts in the contacts application resolves the issue.

**Comment by losingkeys** [comment]
I've had this happen shortly after a contact starts using signal (previousely just using SMS).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
