### ISSUE TITLE
old device has confusing UX after registering on a new device with same number

### ISSUE THREAD

**Issue by eppfel** [signalapp/Signal-Android#5057]
So, I installed the iOS version on an iPad with the same phone number as I used for Android. Full description here: WhisperSystems/Signal-iOS#1041
This made the keys on Android invalid, but the only notice I received was that there is no connection. After removing my registration on Android and re-registering everything works like a charm again. No messages are lost. And of course the iPad does not work anymore.

**Comment by johanw666** [comment]
This happens with most messengers that use a phone number for registration, WhatsApp behaves the same. Viber has an option for installing a "slave" on a tablet coupled to a phone but I don't believe that would work on 2 phones.

**Comment by RichJeanes** [comment]
They do actually have warnings posted that they don't support using tablets, presumably for that reason. That's also why their desktop client just went into closed beta.

**Comment by dharma-guardian** [comment]
Even if we argue with "the user should not do this", the app did give me no hint at all what to do. It just said "no connection". I believe there is more info in the data than that?
At least there should be an article in the help, about the possibility that a connection issue might be resolved by unregistering and registering again.

**Comment by RichJeanes** [comment]
The app description says "Signal is not currently compatible with tablets". That was the instruction, you ignored it. Could the devs do more to prevent this? Sure. They could tell the app stores to not serve the app to tablet devices, but that restricts power users who know what they are getting themselves into.
The app on your phone just knew that it couldn't retrieve messages. There is no more info in the data. That could be caused by a million and one things. And if the server is refusing to allow a client to sync, the server offering more information is actually data leakage and a security vulnerability.
Un/reregistering could be complete overkill for the issue. Is your wifi/mobile data turned off? Is your ISP/carrier experiencing issues? Both scenarios could cause the client to report no connection and registration has nothing to do with it.

**Comment by dharma-guardian** [comment]
> There is no more info in the data. 

Are you sure about that? No HTTP status codes?

> the server offering more information is actually data leakage and a security vulnerability.

Again, http status codes?

Please let us not spam this issue, with arguing about what could have been done. I merely seek to improve Signal, because it is awesome. And from an user experience point of view the app could tell a little more.
Especially because:
> Un/reregistering could be complete overkill for the issue. Is your wifi/mobile data turned off? Is your ISP/carrier experiencing issues? Both scenarios could cause the client to report no connection and registration has nothing to do with it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
