### ISSUE TITLE
music mutes when receiving message and signal is in focus

### ISSUE THREAD

**Issue by unknowndevice** [signalapp/Signal-Android#5109]
this only happens when signal is in focus. I have muted notifications.

**Comment by cascheberg** [comment]
I cannot reproduce this. Can you be more specific?
* Which device, Android version and music player are you using?
* Is the music muting temporarily or does it fully stop?
* Does it only happen if you are in the related conversation, or any Signal screen?
* How did you mute conversations? I assume you set notification sound to silent/none?
* What happens if you do not mute conversations?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
