### ISSUE TITLE
Conveniently raise-to-speak and raise-to-listen Voice messages

### ISSUE THREAD

**Issue by rleonhardt** [signalapp/Signal-Android#5238]
[Telegram 3.5](https://telegram.org/blog/voice-2-secret-3) added the very convenient raise-to-speak and raise-to-listen feature for voice messages:

> When a chat is open, bring your phone to your ear (as if taking a phone call) to listen to new voice messages or record a new one after the signal.

Voice messaging is one of the most popular features of Wazzapp, raise-to-speak  and raise-to-listen would make it much easier to use, even better than the competition!

**Comment by Dyras** [comment]
I think this sounds great, but at the moment they seem to be waiting for https://github.com/WhisperSystems/Signal-iOS/issues/230 to be resolved.

**Comment by rleonhardt** [comment]
Yes, probably. I'm already wondering what is going on, iOS development seems stalled according to the GitHub repo, for a few months now no new release after the big refactoring, some contacts are experiencing problems already... :(

**Comment by freelibertas** [comment]
Currently no one at whispersystems is working on the iOS app simply because they don't have a developer to do that. But they're hiring: https://whispersystems.org/workworkwork/

As for the feature request, I don't fancy having it, I think it would be rather annoying to have my phone do that every time I raise it. Also never compare Telegram to Signal, remember that they have a lot more developers at work, and since every feature brings new bugs (and Signal has quite a few already), the developers want to focus on fixing stuff rather than adding new problems.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
