### ISSUE TITLE
Bad encrypted messages on phone but successfully decrypted in signal-desktop

### ISSUE THREAD

**Issue by kramimus** [signalapp/Signal-Android#5316]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

I was in the middle of a conversation with a signal iOS user and then suddenly I got seven bad encrypted messages from them on my phone. Later, I looked at my signal-desktop window and 5 out of those same 7 messages were decrypted just fine, the other 2 did not show up at all in the signal-desktop window.
### Device info

 **Model:** Moto X 2nd Gen

 **Android version:** 5.1

 **Signal version:** 3.12.0
### Link to debug log

phone debug log:
https://gist.github.com/anonymous/bc65500ae0a211d0903e

signal-desktop log:
https://gist.github.com/anonymous/b08c370b18ae8c07d80e

**Comment by moxie0** [comment]
Have you or the person you were communicating with ever used a backup/restore tool such as Titanium Backup?

**Comment by kramimus** [comment]
No, they are pretty much a stock iOS user, no 3rd party backup applications. I have never heard of Titanium Backup myself.

**Comment by puminya** [comment]
I experienced the same issue. I was using my Android device to chat with an iOS user and apparently we both got bad encrypted messages. The desktop client had no such problems.

### Device info

**Device:** Samsung Galaxy S5 Mini
**Android version:** Android 6.0.1 (unofficial CyanogenMod)
**Signal version:** 3.16.0

### Link to debug log

**Android:**
https://gist.github.com/anonymous/777a04be5466726f9c161f6c165300e6
The first bad encrypted message was received at 06-12 00:31:44.
**Desktop:**
https://gist.github.com/anonymous/a989220df427411dbe69a7922f8b4522

**Comment by Yky** [comment]
@kramimus I used Time Machine to restore a backup and now have problems sending messages to some group members. Everything works fine from the Android phone.

**Comment by Vectornaut** [comment]
I'm having what seems like a similar issue, except my conversation is with another Android user. The trouble started when my phone mysteriously restarted itself in my pocket. After the restart, two media messages I'd received and viewed successfully an hour or so earlier stopped displaying. Intervening text-only messages displayed fine. Every message I sent or received in the conversaion after that, however, showed up on my phone and my contact's phone as _Bad encrypted message_.

On my desktop, I could read the text messages that showed up as _Bad encrypted message_ on my phone. (My desktop installation doesn't receive media messages; is that a known deficiency?) Messages sent from my desktop appeared normally on my phone and my conact's phone.

# Device info

Device: Moto G

**Android version:** 5.1
**Signal version:** 4.8.1

# Links to debug logs

**Android:** https://gist.github.com/anonymous/4d07db05d2ec471d5d9f1bbe2a2c28cf
**Desktop:** https://gist.github.com/eeae7e87185ba4a74de53bb548527281

**Comment by moxie0** [comment]
@Vectornaut It looks as if you suffered some potential data loss during that phone problem. You can select "reset secure session" with this contact from the conversation menu, and that should resolve things.

**Comment by Vectornaut** [comment]
@moxie0 Thanks for your quick diagnosis! I'm very nervous about using the "reset secure session" action, because I have no idea what it does. I can't find a word of documentation for it on the [support site](https://support.signal.org/hc/en-us), and I can't even find explanatory comments in the source code.

The only hints I can find are in [a Reddit thread](https://www.reddit.com/r/signal/comments/6gv7d0/why_does_secure_session_reset_mean_exactly/) and [a Google Play review](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&reviewId=Z3A6QU9xcFRPRU5TOXJCWFlyWE1WelhnYXNqcUpTUFdYQnNuMmlTMkRoNFdYbFJNektqWFdfRHpMRzFMbXVZVXozY25KYS1wUWJqSGctcm5XazRtdElpMXc). The latter, which contains the phrase "wipes your message history," is not reassuring (although it seems to imply that the message-wiping behavior only affects desktop installs, and is not intended).

When I find the time, I'll save my media from the corrupted conversation, try to back up my messages^, hit "reset secure session," and see what happens.

^ The relevant [support page](https://support.signal.org/hc/en-us/articles/212535828) seems conflicted about whether encrypted Signal messages can be backed up. The phrases

> Create a backup of your plain text SMS messages

and

> There is no message recovery or backup through Signal. [...] you can import plaintext messages

seem to imply they can't be.

**Comment by moxie0** [comment]
@Vectornaut It doesn't delete anything, just resets the session state. Shouldn't have any adverse effects.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
