### ISSUE TITLE
Update CONTRIBUTING.md (don't bump issues, etc.)

### ISSUE THREAD

**Issue by p4nci** [signalapp/Signal-Android#5338]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

Actually, this is not a bug!

Now that github added a possibility to add reactions to Pull Requests, Issues, and Comments (see also: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) I think we need some additional info for "Don't bump issues" in CONTRIBUTING.md

**Comment by 2-4601** [comment]
There are also other things that need to be changed and updated in CONTRIBUTING.md. @haffenloher has some changes and I've been collecting changes too for a one time update (because constantly updating the non-wiki docs with small changes is kinda annoying too :)
I'd assign this to @haffenloher but it doesn't seem to be possible, so I'll assign it to myself by which I mean that it's assigned to @haffenloher :)

**Comment by nrizzio** [comment]
This was accomplished a long time ago by 33151867739f050f106474eb909dd7925d77aed9.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
