### ISSUE TITLE
Cannot reply to contact who just joined Signal

### ISSUE THREAD

**Issue by wynkoop** [signalapp/Signal-Android#5480]
See bug 5478 and 5186, then do not be so flip and close the bug report with no investigation.  I have 30 years in the field.  I am sure I know a bug when I see one.  You should have properly posted the response then let me either confirm that my contacts phone numbers were correctly formated or not.

The format of my contacts number is standard north american XXX-YYY-ZZZZ.

Try again.

**Comment by 2-4601** [comment]
In order to fix this please post reproducible steps, device info and a debug log immediately after your issue occurs. All that stuff is laid out in the issue template which you decided to just discard.

**Comment by wynkoop** [comment]
See the referenced bugs where all that is posted and someone closed out 5478 without even checking to see if their suggestion was the issue, which it was not.

If it is too much trouble to see the referenced bug reports I can copy/paste them here.

**Comment by 2-4601** [comment]
#5186 was a permission manager issue (Moboclean) which you said you don't have (in #5478).
Your previous issue #5478 does not contain any kind of device or ROM info, not to mention a debug log. Since you claim to "have 30 years in the field" I'm pretty sure you understand that those are pretty important to get bugs fixed.
Also please go through this support article: http://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way-

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
