### ISSUE TITLE
Information about taken screenshot by receiver

### ISSUE THREAD

**Issue by alvinek** [signalapp/Signal-Android#5483]
Hi Signal Team,

What about information that receiver taken a screenshot of our messages? Wouldn't it be nice to know that this has been done? For example Snapchat informs people that screenshot has been taken in their conservation, or on their snap. I think this would be nice feature that works together with screen security.

**Comment by cascheberg** [comment]
To me this is the same feature category as self-destructing messages, i.e. it will not be implemented.

http://support.whispersystems.org/hc/en-us/articles/213134237-Why-doesn-t-Signal-have-self-destructing-messages-or-remote-deletion-functionality-
> It's trivial for almost anyone to modify their copy of a messaging client [...]
> We take user privacy extremely seriously and will continue to avoid introducing features that do not actually work.

I personally don't even see how this feature would be helpful at all.

**Comment by johanw666** [comment]
Besides, most messages can already be saved by backing them up, why make it difficult with a screenshot? That would, in the current Play Store version without encrypted backup, only be usefull for mms or group messages.

**Comment by NHDaly** [comment]
Those are good points. But I also think that, since the current default behavior in Signal is to prohibit screenshots until you turn off that option, it seems like Signal is sending the message that screenshots are insecure. And it feels weird that you can disable the "prevent screenshots" option, but then it doesn't notify the other person you've done so. So I think people are surprised when they find I've taken a screenshot of their message, since they thought Signal prevented that.


Also, to be fair, a screenshot is a lot more incriminating than a text file claiming you said something in a message. Even though clearly a user could fake a screenshot through photoshop, it adds a semi-non-trivial barrier to many people.

For many people seeing a screenshot that I said XYZ would be a lot more believable than someone just claiming I said it, whether or not that's ridiculous.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
