### ISSUE TITLE
Option to mute notifications for a thread for 12 hours (or a custom period)

### ISSUE THREAD

**Issue by jain-ruchi** [signalapp/Signal-Android#5507]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Feature request

Currently, there are only options to mute notifications for a thread for either 1 hour, 2 hours, 1 day, 7 days, and 1 year. As someone that uses this feature a lot, I would like to see an option to mute notifications for 12 hours, i.e. overnight, or some way to customize the exact time that notifications will be muted for, e.g. with a date picker and time picker.

**Comment by scienmind** [comment]
If anyone is going to take a go for it, I'll recommend also adding a functionality to be able to mute a thread/s without opening it: 
Long pressing a thread in a conversations list, and being able to mute selected thread/s from there.

Use case example - you start receiving a large number of messages (i.e. 20 new messages) to a current group, that you know is not relevant right now, so you could mute it, without clearing the "unread" count for this group, because you prefer to mute it now, but have a thorough read of everything later.

**Comment by grrrrr** [comment]
I was about to open a ticket for this.   Agreed, the defaults are a bit odd.    

Custom time would be great but I think the following would be useful

1 hours = meeting
2 hours = meeting
8 - 10 hours = over night (for me 12 is a little too long)
1 day = leave me alone.

**Comment by jain-ruchi** [comment]
@grrrrr 8 hours is useful for overnight or office hours or school hours

**Comment by Beanow** [comment]
Great idea, how about making it consistent with Android's DND interface giving a +/- that increments by 1 hour. As well as an "until you turn this off" option to replace the 7 days and 1 year choice.

![android dnd](http://www.androidcentral.com/sites/androidcentral.com/files/styles/larger/public/article_images/2015/05/dnd-1.jpg)

**Comment by Forage** [comment]
In addition to a time limit, I think it would be useful to have an option to ignore subsequent notifications of the same conversation. Especially for group messages I'd like to receive only one notification and not hear anything again until I've opened the conversation, since group notifications can become an overload quite quickly.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
