### ISSUE TITLE
Old messages appear AGAIN as bad encrypted messages

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#5525]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

While chatting with a friend I all of a sudden received 8 minute old bad encrypted messages. My friend also has an Android with the latest Signal.

**Actual result:** I get old messages delivered twice, but the second time around they can't be decrypted
**Expected result:** I should either not receive these messages at all, or they should be hidden. It caused crazy confusion. Did I miss messages or something? Nope, just old ones being sent again. The reason I know that they are old messages is because the dates/times matched 100% with previous messages.
### Device info

Device  : motorola MotoG3 (osprey_reteu)
Android : 6.0.1 (33, MPI24.107-55)
Memory  : 35M (0.46% free, 96M max)
Memclass: 96, low-mem device
OS Host : ilclbld28
App     : Signal 3.16.0
### Link to debug log

https://gist.github.com/anonymous/1c08d6f8867a4b3407a65333213a7dcd

This exact same thing happened with Signal-Desktop a couple of months ago.
https://github.com/WhisperSystems/Signal-Desktop/issues/535#issuecomment-201245160

**Comment by CatReady** [comment]
I'm experiencing the same problem. Messages are delivered fine and perfectly readable, but after 8 to 15 minutes into the conversation suddenly a whole load of "bad encrypted message"s is delivered. This load consists of exactly the same amount of messages earlier (properly) received in the conversation.  So for example if the conversation consists of 40 messages, after several minutes suddenly a duplicate string of 40 messages is received in record time (alert sound goes nuts) which all read "bad encrypted message". Pretty annoying since it interrupts/breaks the message list. Dates/times match 100%. None of those duplicate messages were somehow earlier missed or otherwise not properly received. Resetting the secure session (as mentioned in the FAQ) does **not** fix this problem, I tried multiple times with multiple contacts. No luck. Sadly, one of my contacts already ditched Signal because of this..

Are there more users experiencing this problem and is there a solution available?

**INFO**
Device: Sony Xperia M4 Aqua Dual (dual sim version E2333)
OS: Android 5.0 (26.1.B.3.109)
Root: not rooted, no mods
Memory: 16GB (7GB free) + 64GB SD
RAM: 2GB (1GB free)
Signal: 3.25.4
Settings: SMS and MMS disabled (got another app for that)

**Comment by moxie0** [comment]
@CatReady Please post a debug log next time it happens

**Comment by riyapenn** [comment]
Repeat messages from 8:04-8:08 AM according to user's screenshots https://gist.github.com/df71c42814574f0a3d991128ebb6ff05

**Comment by CatReady** [comment]
What I reported 14 days ago just happened again in exactly the same way. Please see the debug log captured right after the incident: https://gist.github.com/3daef8a647a3e88393f7f1c3e8cdafdd

**Comment by CatReady** [comment]
It jut happened again roughly 11 minutes into the conversation. 20 or so messages with bad encryption errors while the original ones were received perfectly fine. Debug log: https://gist.github.com/anonymous/8a1c1f6eef9afd568e950aa29ec95dc3

I'm seeing stuff with "old counter", "duplicate message exception", "no valid session" and so on. I'm not sure what's going wrong here. Is it something we do or something related to a bug causing this?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
