### ISSUE TITLE
Allow formatting of messages (bold, underline, italics)

### ISSUE THREAD

**Issue by nrizzio** [signalapp/Signal-Android#5534]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Feature description

Currently there is no way for a user to italicize, bold, or underline messages. Snapchat's UI is a good example to follow:

![screenshot](https://cloud.githubusercontent.com/assets/13669330/16045911/83d43798-3218-11e6-9102-3aff29964ee4.png)

## If this is a feature you would like to have, please click on the "thumbs-up" button instead of writing a ["me too!" comment](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues). There is also a [forum thread](https://whispersystems.discoursehosting.net/t/font-styling-for-signal-messages/612), and it is preferable to leave comments there. Thanks!

**Comment by rperce** [comment]
Or supporting markdown syntax would be pretty cool

**Comment by hakusdream** [comment]
[Bypass](https://github.com/Uncodin/bypass) is a library which may help with rendering Markdown.

**Comment by Lokesh-Krishna** [comment]
Markdown would be an amazing feature to have.
Really hope some progress can be made on this front.

**Comment by fracture-point** [comment]
I routinely use the Whatsapp style of inline markdown syntax (which I love)...but then I have to explain it to people who don't get it (because Signal doesn't translate it) e.g.

It is _pouring_ outside (pouring is then represented in italics).

WhatsApp converts e.g.
![image](https://cloud.githubusercontent.com/assets/410707/20309311/7c1a94e0-ab15-11e6-80b4-c5b8acf27e44.png)

into 
![image](https://cloud.githubusercontent.com/assets/410707/20309316/80dd3906-ab15-11e6-8f35-76830910d0e6.png)

Once you "close" the markdown tag as you are editing, it updates the text to reflect the format.

I love this for its simplicity - no extra menu options clogging up the screen.  If it's important to you, you'll learn the markdown and use it.  Would similarly love to have this in Signal.

**Comment by Lokesh-Krishna** [comment]
This is exactly the implementation I would love to see though I hope Signal sticks to Markdown and doesn't go its own way like WhatsApp did.

**Comment by moxie0** [comment]
Seems like a good idea. Bypass seems like the kind of thing we want, but I'd prefer something written in Java.

**Comment by Lokesh-Krishna** [comment]
@moxie0 I tried my best and here is what I could find.
[pegdown](https://github.com/sirthias/pegdown) and [txtmark](https://github.com/rjeschke/txtmark), though I am not sure how close they are to being Bypass written in Java.
Will these two do or would we need something else?
Also, could it be possible to proceed with Bypass itself because it does look like the library that most directly addresses our needs and seems to emphasise ease of implementation and speed.
Maybe try it out in a Beta or Development release to see if it is something we can go ahead with? I would love to test it.

**Comment by moxie0** [comment]
@Lokesh-Krishna Both of those product HTML, we need something that produces a Spannable.  Basically, we need something designed for Android.

We also don't need full markdown support, so it's probably straightforward just to write something that implements the few markdown tags we need.  You'd have to submit a PR for that here, on iOS, and on the desktop simultaneously.  Thanks!

**Comment by Stuie** [comment]
I've looked around and I haven't been able to find a plain Java markdown parser that goes straight to Spannables instead of HTML. If anyone knows of one I'm willing to try implementing it.

Libraries I looked at:
1. [Bypass](https://github.com/Uncodin/bypass/tree/master/platform/android) - Non-Java
1. [cwac-anddown](https://github.com/commonsguy/cwac-anddown) - Non-Java, goes through HTML to reach Spannable
1. [MarkdownJ](https://github.com/myabc/markdownj) - Plain Java, but only goes to HTML, implemented as a series of regular expressions, not updated for years

If nobody knows of a suitable library then I propose we come up with a set of requirements and just roll our own.

Would basic inline support suffice to begin with?

**Comment by Lokesh-Krishna** [comment]
We discussed libraries at the [community forum](https://whispersystems.discoursehosting.net/t/font-styling-for-signal-messages/612/24) but didn't fare much better.

As for requirements, I think italics, bold, underline and strikethrough should be all that would be needed for a texting app. 

> Would basic inline support suffice to begin with?  
Does this mean implementing it the way it has been done in WhatsApp instead of the Snapchat implementation suggested in the very first post? If so then inline would definitely be the better option as it wouldn't clutter the action bar up and confuse those who aren't interested in this while letting users who do want to use it do so seamlessly.

**Comment by Lokesh-Krishna** [comment]
If someone can sift through the code and find out what library is being used, there are two open source Android apps with Markdown implemented in them:

- [Simpenote](https://github.com/Automattic/simplenote-android)  
- [QKSMS](https://github.com/moezbhatti/qksms)

Are they of any help?

**Comment by fracture-point** [comment]
Looks like they are both using the TextUtils.java library:

https://github.com/moezbhatti/qksms/blob/835e2659b228e27378d4d8672840653a55052969/QKSMS/src/main/java/com/moez/QKSMS/common/utils/TextUtils.java

**Comment by Lokesh-Krishna** [comment]
Does that library meet our requirements then?
I'm judging from the name that it is written in Java but does it produce a Spannable?

**Comment by TheMcMurder** [comment]
Hey, So based on the discussion here it looks like we haven't found a library that will solve this for us (or have we?). 

Is it time to discuss creating a library that can solve this? I was considering writing a small(ish) parser that we could configure the output.

`StringWithMarkdown -> Lib + config -> Spannables or HTML or whatever iOS needs.`

However... and this is a big however. It's been a long time since I've done anything in Android, so I'm not sure how we'd implement something like that in a cross library way (Java, JS, and Swift or Objective C) Any thoughts?

**Comment by Stuie** [comment]
@moxie0 [prefers something written in Java](https://github.com/WhisperSystems/Signal-Android/issues/5534#issuecomment-262149292), but that limits the cross-platform functionality quite a lot, as far as I understand it.

There's no point writing something cross-platform in C and then having it rejected because it's not written in Java, so I figure we'd want agreement to integrate before spending the time to write a cross-platform parser.

Is it acceptable to have it implemented on one platform and not the others?

**Comment by TheMcMurder** [comment]
Based on the discussion on the [desktop issue for markdown support](https://github.com/WhisperSystems/Signal-Desktop/pull/1084), whisperSystems wants it to release on all three at once.

**Comment by Stuie** [comment]
Requirements for Markdown support in the Signal ecosystem as I understand them:

1. Simultaneous release on all platforms
2. Support for the same subset of Markdown
3. Not native code on Android
4. Not translating through HTML on Android

Given the languages used on the three clients (Javascript, Java, and Objective C), and the requirements suggested in this issue for Android, I don't see a way of writing this once and running it everywhere. That complicates the first two requirements.

Rolling three of our own solutions seems like a terrible idea resulting in bugs and inconsistencies between platforms.

Can someone responsible for each client in WhisperSystems have a conversation and come up with a realistic set of requirements for this feature? It seems like it'll just stagnate if not.

**Comment by TheMcMurder** [comment]
I was hoping we could write it in a single language (regardless of what that single implementation is) and transcompile it. Something like this: https://github.com/google/j2objc but with support for javascript as well.

**Comment by hakusdream** [comment]
Google Web Toolkit can help with that. http://www.gwtproject.org/

**Comment by bmintz** [comment]
@fracture-point, you still don't need to know how Markdown works in order to use it on WhatsApp. If you select text, then press the three dots next to Copy and Paste, you can see there's a "Bold", "Italic", "Underlined", "Strikethrough", and "Monospaced" at the top.

That said, I think the way Snapchat does it is much easier to use because it's more readily accessed and there's no scrolling involved.

Also, I think \`\`\``code blocks`\`\`\` should be supported. WhatsApp uses three backticks but maybe just one should be used instead.

**Comment by rperce** [comment]
@bmintz single backticks are for `inline monospaced` text. Three is for blocks.

**Comment by bmintz** [comment]
Yeah but WhatsApp also doesn't have a separate code block and inline code format, which I think is fine.
Three backticks is also useful for Haskell code, for example, ``even' x = x `mod` 2 == 0``.

**Comment by Stuie** [comment]
Don't decide features because it would be convenient for the 10 people in the world who are sending Haskell code to each other via messenger.

Discussing the finer points of the implementation doesn't matter if nobody is going to implement it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.

**Comment by 2-4601** [comment]
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/issue-allow-formatting-of-messages-bold-underline-italics/2706).
