### ISSUE TITLE
Add longer-term disappearing timeouts

### ISSUE THREAD

**Issue by dingens** [signalapp/Signal-Android#5775]
I have looked at all open and closed issues containing "disappearing" here and in the libsignal-java repo. I hope the bug belongs to this repo, sorry if not!

For my use case, the 30s/.../1 week periods for disappearing messages are not useful. I quite often want to have a look at messages written within the last month. I'd thus not use the feature at all, even though in principle I think it is a good idea.
I'd suggest to add further periods up to at least one year or something. (As I'm thinking of it, maybe it should even be 13 months rather than 12, so you can re-read what you were discussing on your last year's birthday or last christmas or whatever, and it only disappears little after)

(Signal 3.19.1 on Android 6.0.1 / CM 13)

**Comment by skulumani** [comment]
It seems you deleted the issue template :angry: 

https://github.com/WhisperSystems/Signal-Android/blob/master/.github/ISSUE_TEMPLATE.md

This repo is also usually used to track bugs, so someone else with authority may weigh in at some point as well.

Also, since there's currently no way to search messages it seems having a huge time delay (up to a year) would make it difficult to find a specific message from the past.

Increasing the duration only really seems useful if search is first implemented, which is already [tracked](https://github.com/WhisperSystems/Signal-Android/issues/1232)

**Comment by dingens** [comment]
> It seems you deleted the issue template
I did that because it is targeted to bugs, not feature requests, and so the headings there don't really fit... I hope it's still readable like that

I agree reading things from like a year ago is difficult without the search if one writes a lot, but it is easy to read something from like two weeks ago, so we'd still need higher limits for that. Plus there might be low-traffic conversations etc. Plus, I don't see any reason to not allow the user to choose the timeframe they like.

**Comment by cascheberg** [comment]
I also don't see how a one year disappearing timer makes sense. Maybe you want to have a look at #3047 and #5176.

**Comment by dingens** [comment]
Don't concentrate so much on the specific limits I proposed. I personally don't need the one-year thing probably, I'd be happy with 2-3 months.
However as I said I don't see any reason to only offer users the time periods some random people on github (no offense) consider to make sense. Why don't let people decide for themselves?

**Comment by jeremymasters** [comment]
The one that would be cool is a date+time picker...message expires on this particular date and time.

**Comment by ilf** [comment]
Having proposed the [now implemented](https://whispersystems.org/blog/disappearing-messages/) disappearing messages over a year ago in #3047, I am thankful for seeing it implemented, but I would also love an option of one month.

**Comment by merge** [comment]
I might be horribly wrong, but this seems like you are talking about the saved conversations on your own device. You can choose at what amount to trunkate your conversations.
Disappearing messages disappear at the other side too. Anything longer than a week seems confusing, imo

**Comment by dingens** [comment]
I don't know about the others, but I am talking about the disappearing on both sides thing. I don't see any reason why more than a week would be confusing.

My use case is that I want the messages to disappear after a while, so there's no unneccessary data lying around - but I want the interval to be high enough so that I don't really notice it. If it was set to a week, I'd often miss messages. That's why I want something like a few months. That's still way better than no deletion at all (which is what it is set to now, because one week is way too short for us)

**Comment by roadkillazpartybird** [comment]
I would like a 1 month time.

1 week feels a little short for a lot of things. Cheers!

**Comment by LeanderH** [comment]
The issue is not regarding deletion of own messages to clean up the conversion.

I really agree that having options like 1 month, 3 months, 6 months ect. would be awesome for many other reasons; mainly that the point of Signal is to have private messaging. The problem is that if your messages are kept as long as a given device exists, then it doesn't feel very private. This is why we use dissapearing messages in my group of contacts. But the limit of only up to one week, makes it rather un-useful, as one might often need to refer to messages from more than a week or two ago; e.g. "When did we decide to meet?", "He sent his address when we planned it a couple of weeks ago". Etc. 
Mostly not a big deal, but also not a big deal to have more options - or better yet, custom time frame options.

In most cases, we have no use for the messages after a few months, and thus in the name of privacy, it would be nice to know that everything you have said won't be captured for ever and ever, when we already have the feature needed, and can get there with the addition of extra options.

Hope this makes sense.

**Comment by skulumani** [comment]
I think this can already be achieved by trimming messages by length/number
in thread rather than time?

There's a whole lot of discussion Scott something that seems pretty arcane.
There are several time periods that seem fine for a wide variety of
scenarios.

We can spend lots of time getting many more options, but the benefit seems
small to me

**Comment by LeanderH** [comment]
I think it's more natural to think of your messages dissapearing after e.g. three months, rather than after e.g. 500 messages. I know have long three months is, but how much is 500 messages? One months worth? Three years? May vary. Also, that option affect all conversations or none.

The dissapearing messages already achieves exactly this privacy issue - except of the unfortunately short duration. The options of a few minutes is great for highly sensitive content, but one week is two short for most practical conversation, when thinking about Signal as a general conversation platform.

Reading around, it seems that an option of a few months would help a lot. But I can't see why a single option of a custom time setting isn't the most optimal? I would add a great piece of the puzzle of achieving privacy.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
