### ISSUE TITLE
"Select SIM card" Message when I lost my cellular network

### ISSUE THREAD

**Issue by int9h** [signalapp/Signal-Android#5779]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Everytime I lost my cellular network I get a message from Signal "Select SIM card". 
I have only one SIM card. 
### Steps to reproduce

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
### Screenshots

![screenshot_20161014-084812](https://cloud.githubusercontent.com/assets/33732/19379738/d0dbceda-91f3-11e6-9da2-488efdd06dd4.png)
### Device info

**Device:** LGE Nexus 5 (hammerhead)
**Android version:** 6.0.1 
**Signal version:** 3.20.4
**CyanogenMod:** cm-13.0-20160820
### Link to debug log

https://gist.github.com/anonymous/a05bf8585fe2943f2d3d5548b877356e

**Comment by cryptomilk** [comment]
I can confirm this with Samsung Galaxy Alpha (slte).

**Comment by int9h** [comment]
Looks like it's a custom rom issue. Don't get messages like this with latest Marshmallow Stock.

**Comment by cryptomilk** [comment]
I think it doesn't have something to do with Signal.

**Comment by Marsup** [comment]
This might be related to https://forum.cyanogenmod.org/topic/127477-getting-select-sim-card-message-in-hangouts-with-newer-nightlies/, similar problems in hangout it seems.

I have the same popups these days, but I didn't receive any OS update since about 3 months, it seems to match the recent releases of Signal. I'm on a "stock" cyanogenmod on my OnePlus One, and I don't really want to switch to nightly builds. I wouldn't dismiss Signal as the culprit just yet.

**Comment by jonorthwash** [comment]
I'm getting a similar message with a recent CM update.  This device has no sim card...

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
