### ISSUE TITLE
sending messages not possible

### ISSUE THREAD

**Issue by ka223** [signalapp/Signal-Android#5835]
### Bug description
Since the last upgrade, I can not send messages.
Only insecure SMS is available.
Signal. 3.21.3

Deleting previous conversations is not possible.

### Steps to reproduce
- upgrade to 3.21.3
- maybe: (check out the new giphy gifs - they are not loading)

**Actual result:** I can not send messages.
**Expected result:** Sending secure messages should be possible.

### Device info

**Device:** Motorola G2
**Android version:** CM13 stable release
**Signal version:** 3.21.3

### Link to debug log
shows only "Loading Logs ..." for the last 15 minutes

**Comment by 2-4601** [comment]
Does this affect all contacts?

Has there been some issues with your system's contact app?
If so you could try the steps laid out in http://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way-

**Comment by DerGatt** [comment]
Maybe my issue is related. If I want to send a gif and the gifs are not loaded properly. If I select a non loaded gif (there is no preview at all just a solid color) I'm no longer able to send a secure message to that contact.
Only rebooting the phone fixes the issue.
I can't reproduce this error at will, because I can't influence the gifs are loaded, but it happened a couple of times to me.

**Comment by ToppestOfDogs** [comment]
I have the same issue, I can only receive messages and send insecure SMS, even if I disable SMS it'll just tell me to invite my friends to signal and not let me message them. Even if I'm currently receiving secure messages from them it will only let me send an invite.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
