### ISSUE TITLE
Swipe Left/Right to Navigate Between Conversations

### ISSUE THREAD

**Issue by SevenFactors** [signalapp/Signal-Android#584]
[Feature Request]

Being able to navigate between conversations by simply swiping Left or Right would be a killer feature for TextSecure, one that I can't wait to see implemented.

Not having to navigate back to the conversation list to find/choose said conversation would greatly improve the TextSecure messaging experience.

What do you say ^_^

**Comment by d3k4r** [comment]
Instead of swipe left/right to navigate between conversations, I'd simply like to be able to swipe right while in a conversation to get back to the conversation list. As it is now, I have to tap the nav back button or reach all the way to top left and tap the back arrow.

Being able to quickly go in and out of conversations by tapping to get in and swiping right to get out would greatly improve the experience.

**Comment by SevenFactors** [comment]
That is also a good idea.

**Comment by mammuth** [comment]
IMHO it's better to make a swipe to the right to get back to the conversation list, just like Telegram does it.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
