### ISSUE TITLE
Some pictures are not loaded

### ISSUE THREAD

**Issue by JohnnyMT** [signalapp/Signal-Android#6004]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some pictures are not loaded.
When someone tries to sends me a picture, it sometimes does not load.
I only see the message bubble and the "loading circle". That circle keeps turning, but nothing happens.
Since I'm not able to open the picture, I also tried to save it but everytime I try this, it gives me an error message that it is not able to save the attachment to the device.

### Steps to reproduce
Happens randomly, in group chats and in 1on1 conversations, independent from user and connection (wifi or mobile).

### Screenshots
![signal1](https://cloud.githubusercontent.com/assets/24448868/21581546/b0d88db4-d035-11e6-9cf2-23f55d9e3646.jpg)
![signal2](https://cloud.githubusercontent.com/assets/24448868/21581545/b0b500b0-d035-11e6-974a-9a307b6e41d8.jpg)

### Device info

**Device:** Huawei VNS-L31
**Android version:** 6.0
**Signal version:** 3.25.4

### Link to debug log
https://gist.github.com/anonymous/89dded3aef1ee7d7dba505e0f2339154

**Comment by riyapenn** [comment]
If you're interested in troubleshooting, contact support@whispersystems.org.

**Comment by 2-4601** [comment]
Experiencing the same. The animation of the first download spinner seems to be stuck and it's not progressing. The second one just spins forever but nothing happens.
![spinning spinners](https://cloud.githubusercontent.com/assets/174176/21970111/4f3dd6e0-dbac-11e6-8c6e-eb73c030db07.png)

Nvidia Shield K1
Android 6.0.1
Signal 3.27.0

https://gist.github.com/8696c7e1ea723d94b1797def3d7c200c

**Comment by riyapenn** [comment]
Also on Signal 4.3.2 https://gist.github.com/d7fec73f4508be154a1d79c91275ab7a this time with a device that likely received the media file when connected to Android Auto.

**Comment by Dyras** [comment]
This exact same thing happens on my mom's phone really often. If you wanna debug the crap out of her phone, then just say the word.

https://gist.github.com/anonymous/494993a950189778dc6e6d7f469d1e58
https://gist.github.com/anonymous/0c21e2e84df4dcc8a7a3ecb3af8a34b7

**Comment by hlorenz** [comment]
Same problem here.
OnePlus 5, Android 7.1.1, Signal 4.8.1
https://gist.github.com/anonymous/cccdad2c6d5a423095c9149a43c9bf93

**Comment by PiCob** [comment]
I do also experience this every once in a while. Sometimes the spinner keeps spinning forever, sometimes the spinner starts and just stops at a certain point, staying there forever.

Here's another debug log:
https://gist.github.com/anonymous/daab797c034e0a07d6fb2545fb70277b

Moto G4 Plus
Android 7.0
Signal 4.11.5

![screenshot_20171018-203451](https://user-images.githubusercontent.com/23237468/31736470-2b6cd032-b445-11e7-93a7-1a9fb915b94d.png)

Is there something more we can do? Since it's annoying to ask the sender to resend a picture/video, maybe there should be a way to "restart"/reinitialize a media download.

**Comment by Lena-KA** [comment]
Same issue here. I realized that at my device it only happens if something is wrong with the internet connection. 
For example during my holiday with bad mobile internet (and roaming) or if something is wrong with the wifi connection (for example when not logged in, but connected to a WLAN)
It also happened to me that all pictures send in a conversation are not loading anymore because of one picture not loading.
Workaround for bad mobile internet: change in the preferences to only download on request and only download if you are sure internet connection is good.
I tried deleting the cache, restart the app, restart the device - only thing working was deleting the picture and asking the contact to resend the picture.

It would be very helpful to have the possibility to reload or restart the download of the picture. 

Device info
Device: Sony Xperia Z1Compact
Android version: stock Android 5.1.1
Signal version: 4.11.5

**Comment by PiCob** [comment]
It happens again and again -.-

The following log covers the issue at the very beginning:

gist.github.com/anonymous/5bcea352abba717e9cc03d966b6af1ae

Moto G4 Plus
Android 7.0 Stock ROM
Signal 4.13.6

As already pointed out by others and myself: if there is no absolutely no way to get rid of this annoying bug, there must at least be a way to "force restart" the download. Up to now, I can only delete the message and kindly ask the sender to resend - and the sender will pretty much have a "great" impression of Signal and its reliability...

**Comment by Sebl29** [comment]
+1

I know this bug since the I started with my first picture messages. Every time when I open a received message but with bad mobile connection.
In my family group this always ends up in discussions, why we still use Signal,  because everybody once has had this bug and is not able to follow the discussions about a nice picture. 

Please give it prio one!

**Comment by moxie0** [comment]
@Sebl29 Please don't bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

It would be useful if you posted a debug log next time this happened, though.

**Comment by PiCob** [comment]
@moxie0 - didn't expect you still needed more debug logs, since a lot of them have already been posted, but in this case, here's another one: https://gist.github.com/b0a9a8a0f452f27fdb99fef48b72e311

**Comment by PiCob** [comment]
And another log (should be right at the beginning of the log file):
https://gist.github.com/94b154253ddd3b8a7a8e885b35915473

**Comment by PiCob** [comment]
This time representing the case "spinner spinning forever" (the former log dealt with the skimmer stuck somehow) - don't know if there's really a difference between these two symptoms, but anyway:

https://gist.github.com/8cf52a3426a4a172b5fcb740f6af1a33

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
