### ISSUE TITLE
Can't rename MMS group chat

### ISSUE THREAD

**Issue by rhetr** [signalapp/Signal-Android#6123]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I can't rename a group chat

### Steps to reproduce
- open signal
- click a group chat
- click menu
- click conversation settings

**Actual result:** there is no setting to rename group
**Expected result:** there should be a setting to rename group

### Device info

**Device:** LG K7
**Android version:** 5.1.1
**Signal version:** 3.27.1

**Comment by sweeper3000** [comment]
There is an option to rename the chat and add members, it's in the more section in the conversation view and the option is "Update Group"

Having an entry in conversation settings linking to the group update may not be a bad idea

**Comment by rhetr** [comment]
how do I get to conversation view? I don't see it in any menus or if i long press the conversation.

**Comment by 2-4601** [comment]
> how do I get to conversation view? I don't see it in any menus or if i long press the conversation.

- open signal
- click a group chat
- click menu
- click update group

**Comment by rhetr** [comment]
I see, I was trying to rename an MMS group chat, those options are available in a Signal group. Is there a reason why group names are exclusive to Signal groups? It's quite inconvenient to have multiple groups with some of the same people but not be able to differentiate between them at a glance.

**Comment by 2-4601** [comment]
Dunno. I've never used MMS groups. But I just tried to create one and even though I gave it a name it just labeled it as a general "Group chat". No idea if this is a bug or a feature.

**Comment by mvc1095** [comment]
This is also a problem for me. Likely related: I also can't **search** for MMS groups, since they don't have a name of their own, and searching for the name of a member of an MMS group only returns messages sent directly to that contact. This is highly irritating, as it effectively means I need to scroll way back through the list of previous conversations to find the group I want, or go through the procedure of recreating it (at which point it will show up again in my list of conversations together with all previous messages to that group).

I have the impression that support for MMS-only features is lower priority for OWS, which I totally understand, but this breaks basic functionality for me unless and until I can convince every single contact of mine to switch to Signal :sob:

**Comment by lindhe** [comment]
It should display the name that is given to the group. It should also be searchable both on <name>, "group" and each participant.

**Comment by cargohook** [comment]
>  open signal
    click a group chat
    click menu
    click update group

These instructions do NOT work. There is no "update group" option.

**Comment by ringw** [comment]
On Android, the menu only shows "Conversation settings" which only has "Mute conversation", "Notification sound", and "Vibrate". No "Update group".

**Comment by brendonrapp** [comment]
This is still an issue and it's maddening.

**Comment by mvc1095** [comment]
Update: Still a bug, and it's even worse than described above. Signal does not collapse group MMS messages with the same recipients, but rather displays them in a seemingly random order. I thus have multiple message threads visible: one listing the members as A,B,C, another listing the members as A,C,B, etc. To find a previous message I have to scroll back through the list of all message threads (since searching by recipient name doesn't work, and there's no option to set or search by group name) and tap each one in turn.

**Comment by JamesHarrison** [comment]
I'll add to this - when following the below steps, groups show up as "Unnamed group" and cannot be renamed on Android:

- Use Signal on phone A to make a group
- Pair Desktop with phone A
- Buy new phone B
- Set up Signal on phone B, following the instructions on the website for new phones
- Close Desktop
- Open Desktop and re-pair to phone B
- Send message to group on Desktop
- Phone B now shows "Unnamed Group"

This is a bit of a crappy workflow. The instructions on the website for new phones also suggest leaving groups if you have a new number - while this may be good advice, there is no way to leave a group on Android.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
