### ISSUE TITLE
Error downloading MMS message, tap to retry

### ISSUE THREAD

**Issue by jreslock** [signalapp/Signal-Android#6234]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Error downloading MMS message, tap to retry on Signal 3.29.6

### Steps to reproduce
- Receive MMS message from non-signal user.
- Try to click on the message to download the contents.
- Tap to retry when an error is shown.

**Actual result:** I receive the error described in the issue title over and over.

**Expected result:** MMS message is successfully downloaded.

### Screenshots
Omitted

### Device info
**Device:** OnePlus 2
**Android version:** 6.0.1
**Signal version:** 3.29.6

**Comment by jeremymasters** [comment]
My wife's s7 also. Won't grab group mms, which sticks for her big-time! 
https://gist.github.com/9ffc07694cc89fb79efee209d1a93b5a

**Comment by autojim** [comment]
Happening quite a bit on my S5. Highly annoying as it keeps retrying, even if you delete messages or indeed the entire conversation.

But one example: https://gist.github.com/c55f15162cc077efc73e166fc761cb12

**Comment by autojim** [comment]
FOLLOW-UP:

After growing tired of the endless automatic attempts to resend the failed MMS messages to my phone's Signal app, I switched my default messaging app back to the OEM messenger application. This cleared the queue of the residual messages, which were part of a group text a contact of mine initiated. They were not media messages, but apparently group texts are sent as MMS messages, and Signal was unable to process slightly more than half of them, setting up the endless cycle of repeat-send-attempts.

I am a caveman mechanical engineer who can't code his way out of a paper bag regardless of its moisture content, but perhaps a future release of Signal could address this, please?

**Comment by hotpocket** [comment]
Just two of these in a row. I asked the sender and she said she sent the msg days ago... Not sure if that matters

**Comment by autojim** [comment]
Seems to retry on a 12-hour basis.

I've had to switch back to Messenger for primary use, with Signal only for other Signal users.

**Comment by Gingernaut** [comment]
I have this issue constantly. I deleted the app and reinstalled and MMS worked for some time, then the issue came back. I've been forced to use a non-secure app as my default messaging app now. Please address this issue.

**Comment by hotpocket** [comment]
Is there any way to attempt to debug this? I was thinking if there was a dump of the malformed MMS I could get to, I maybe could post that somewhere.

**Comment by jreslock** [comment]
Update on this:

I found that in my case the issue was my carrier (AT&T) mismatching my phone's EIN and not allowing the MMS downloads.

The OnePlus2 has 2 SIM card slots, each with a unique EIN.  I had been traveling abroad and moved my AT&T SIM to the other slot.  This confused the carrier somehow and caused major issues with MMS.  Once I called AT&T to get them to correct the EIN it was fine.

**Comment by hotpocket** [comment]
This can not be the case with me as the issue is intermittent (I actually got one of these errors again yesterday) ... however there was some SNAFU about MMS when initially when I got my phone with tmobile where they had me enter a url to download mms messages from, and then the MMS flowed (before signal) ... as I said before if there is anyway way to attempt to debug this I would be willing to submit dumps or preform diagnostics if desired by the devs.

**Comment by onesweetpea2000** [comment]
I have a Blu Vivo XL and everytime I view MMS photos I have to verify that cellular data is on and WLAN is off.  I reboot it and then everything works great.   The pictures stay when I turn my WiFi back on but I can't receive any new MMS info.  It doesn't take that long but since I kept forgetting what I was doing I actually have a piece of paper reminding me on those two complicated steps stuck on the back of my phone case :)  Hope it's as easy for everyone else as it is for me.

**Comment by hotpocket** [comment]
had this happen again from two different contact that usually text me in a group thread ... i got these errors separately although i suspect they got deinterlaced because i received two separate MMS download requests from two separate contacts that, like I said, usually communicate with me in a group text.  they do not use signal.  captured debug log here.  https://gist.github.com/anonymous/934cc665053bbe90ac05b288e9cae210

**Comment by Rasmis** [comment]
I get this too. I've tried connecting and disconnecting wifi, rebooting the phone, selecting download this and that. Nothing works.

**Comment by onesweetpea2000** [comment]
What I found out is that if I turn off Wifi (WLAN) and leave cellular data on - then reboot it works great, everything downloads great.  It's a pain but at least I get to see the pictures.

Good luck


---- Rasmus Malver <notifications@github.com> wrote: 

=============
I get this too. I've tried connecting and disconnecting wifi, rebooting the phone, selecting download this and that. Nothing works.

**Comment by Rasmis** [comment]
Doesn't work for me. Tried again, no result.

**Comment by onesweetpea2000** [comment]
What a shame.  I'm sorry.  Who makes your phone?  I'm using a Blu product.

---- Rasmus Malver <notifications@github.com> wrote: 

=============
Doesn't work for me. Tried again, no result.

**Comment by Rasmis** [comment]
Samsung Gi9195

**Comment by campbeln** [comment]
This happens with a large percentage of my MMS messages on MotoG3, it makes Signal unusable.

**Comment by sarahgreenlee** [comment]
This happens so consistently for me. So frustrating!

**Comment by erichiggins** [comment]
Experiencing this issue with Signal 4.14.10 on a Pixel 2, running Android 8.1.0

**Comment by zksteel** [comment]
Same on Motorola Moto X Play: Android 6.0.1 and Samsung Galaxy S4: Android 4.4.2, both running Signal 4.14.10 ver. currently. This issue annoying me and my friends for half a year. **Devs, will it be fixed soon?** When? Should we look for other app?

Additional info:
I found that last corrletly downloaded MMS were 8 Apr 2017. It's hard to determine when it started, cuz I delete old messages (limit 200). I always updated Signal app when when a newer version came up.
I think also that telecommunications provider is not a problem. Me and my mate, both we are using "Play" [(wikipedia),](https://en.wikipedia.org/wiki/Play_(telecommunications)) for him everything works great (With newest version of app too). Play uses domestic roaming, so i tried fix MMS issue by allowing for all types of MMS in "media auto-download" option for roaming. It didn't help. And everything works half year ago so... .

**Comment by hotpocket** [comment]
Submit a debug log like I did so the devs have something to go on.   The easier it is for them to figure out the more likely it is to get fixed.

**Comment by zksteel** [comment]
I peek at logs and started digging in code. In my case issue occure because I use application with "Signal messages and calls" disabled (I disable it cuz me and my friends had problem with to long time between sending and receiving an SMS - sometimes few hours). 
When MMS arrive, You guys check:

`      
if (!TextSecurePreferences.isPushRegistered(context)) {
        throw new MmsException("Not registered");
}
`

I don't have to much time to dig deeper, but why you need GCM for just downloading MMS like standard apps do (which not using Google Services).
I think you can just somehow skip it, and download MMS like dozen apps on market do.

With "Signal messages and calls" enabled, MMS are downloaded and displayed correctly.

**Comment by Glassweaver** [comment]
Signal will never fix this. It's been brought up many times over the years. I put in a big request in 2014 as well, if that gives you any idea. As long as most of the product works, they simply don't care about the oddities that affect a minority of users. 

Why am I even here, you ask? I wanted to see if they'd fixed the issue I reported YEARS ago, when Signal was still called TextSecure.

Figured I'd give you the closure that the developers refuse to. MMS magically got better when I ditched signal. I stopped missing texts too.

Signal is an unreliable, buggy program that's been in alpha for half a decade and is unlikely to ever come out of it. 

Find something better. Your time is wasted here.

**Comment by amadib** [comment]
I dont experience the same issue where I have to retry but I have to manually download each image, even if I have it set to automatically download MMS. Is this the same issue or another?

**Comment by JERW86** [comment]
I am having this issue with 4.16.3. 
Android 7.1.2
[Debug Record](https://gist.github.com/e6852ec5887e4e02cd9a2734608d6bd3)

**Comment by douglasg14b** [comment]
same issue...

4.16.9
Android 8.0

https://hastebin.com/miyomubite

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
