### ISSUE TITLE
Signal Messages sent to server, but not delievered. 

### ISSUE THREAD

**Issue by Wwkdiek** [signalapp/Signal-Android#6246]
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I send messages via the Signal-android app and Signal-Desktop app, I often get a single check mark. It will stall (often for hours) until I send a 2nd or 3rd follow up message and then I will get a delivered double check mark. It happens with a handful of contacts, but not with others. I can't seem to trigger the bug and I'm not sure if its client side or server side. I'm fairly certain its not a data issue on my end, nor is it a data issue on the receiving end (this particular contact is always connected to wifi)

### Steps to reproduce
Not sure how to trigger bug.

### Device info
Moto G  3rd Gen
Android 6.0
Signal 3.28.4

Receiving phone is iPhone 6

**Comment by moxie0** [comment]
Hey @Wwkdiek it sounds like everything is working fine on your end, but there is something up on the receiving end.  Since the recipient is an iPhone, either they're not receiving an APN or the client is not handling it correctly. Would you mind opening this in the Signal-iOS repo instead, since if there's a bug it's something they'll have to handle? Thanks!

**Comment by motatuc** [comment]
I experience the same problem lately. First time it happend was around the 10 of February. Message did not arrive for three days. I then sent another one and suddenly both arrived. The other phone was android as well. So it is not an android-iphone-problem only.

Unforunately I do not see any pattern. It seems to happen randomly. But with some contacts it happens quite often, I would say a few times a day.

**Comment by joshuabach** [comment]
I (and friends) also have this problem occasionally. Sometimes the message even seems to be "in transit" indefinetly (at least 12 hours).

Possible Workaround
---------------------------
Sending another message will result in both (the new and the previously undelivered one) to be delivered immediatly, at the same time.

It feels a little like the first message is stuck in a queue somewhere, and sending the second message causes the Signal server (or in whosesoever queue it is stuck) to look at that queue, realise that there is still something in there and deliver both. But thats just a guess.

**Comment by bme13** [comment]
This happens to me occasionally as well for Android to Android messaging. Yesterday I send a message which then had a single check for 23 hours until today I send a message to a group where this contact is also part of. The pending message instantly got 2 checks. This also seems to happen more with specific contacts. Since it's difficult to get a logfile for that, perhaps it's possible to find something that these contact have in common. Mine for example doesn't have a mobile plan so can only be reached while using wifi. Also it turns out he often disables wifi as well, using this as a sort 'do not disturb mode'

**Comment by EvanK** [comment]
I'm experiencing this behavior too, between two Android 7 (LineageOS 14.1) phones -- sending is a Nexus 6 (shamu), receiving is a Nexus 4 (mako).

The noted workaround of sending another message to "unstick" earlier messages does _not_ work in my case. They eventually deliver, but it seems to happen randomly.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
