### ISSUE TITLE
Share content with Anonymous?

### ISSUE THREAD

**Issue by motatuc** [signalapp/Signal-Android#6304]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It's not a bug. But If I choose for example pictures to share with somebody I always have an Anonymous user in the list. Where does it come from? It should not be there - I do not have it in my contacts.

Have a look at the screenshots to understand.

### Steps to reproduce
- choose a picture to share
- press the Signal share button

**Actual result:** Anonymous appears as receiver
**Expected result:** Anonymous should not be there at all

### Screenshots
![shot1](https://cloud.githubusercontent.com/assets/15171154/23338882/e53dbcc4-fc0d-11e6-91a7-4141eaca87b9.png)
![shot2](https://cloud.githubusercontent.com/assets/15171154/23338883/edcf1838-fc0d-11e6-9a26-1bc06cbd7947.png)

### Device info
**Signal version:** 3.30.3

**Comment by skulumani** [comment]
A related issue is that the contacts listed are only those with an active conversation in the inbox. If there's a message thread archived that contact/group will not be visible.

A suggestion would be to ensure all contacts are visible in the share dialog. In addition all groups should also be available, perhaps segmented at the top or bottom somehow? 

The anonymous could be a way to allow the user to type in a new number that isn't already a contact as well?

Thank you for all the great work

**Comment by nrizzio** [comment]
I was about to open an issue for this, but I remembered I've seen this behavior in the past. After the removal of the Canonical Address Database, I now have `-1` as a share option, instead of `Anonymous`. I still don't see why this occurs though.

**Device:** Samsung Galaxy Grand Prime
**Android version:** 5.1.1
**Signal version:** 4.9.7
[Debug log](https://gist.github.com/anonymous/c46ad54bcd7072fb95539d1874242ec8)

![signal-2017-08-10-174013](https://user-images.githubusercontent.com/13669330/29193379-0b33c2cc-7df3-11e7-846d-4dd860d042a3.jpeg)

**Comment by RiseT** [comment]
@nrizzio Same here ("-1").

Nexus 5X, Android 7.1.2, Signal 4.9.8

**Comment by Lesik** [comment]
If you forward a message to this "-1" contact, not only will it fail, you are also going to see _two_ "-1" entries next time you try forwarding a message – once because "-1" is part of your chat list, and once because it always appears at the end of a list.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
