### ISSUE TITLE
Calls do not respect Do Not Disturb mode

### ISSUE THREAD

**Issue by abbradar** [signalapp/Signal-Android#6411]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a phone is in Do Not Disturb mode calls still produce ringing.

### Steps to reproduce
- Enable Do Not Disturb mode;
- Let someone call you.

**Actual result:** Hear the call.
**Expected result:** Phone is silent. Ideally Signal also respects "Repeated Calls" policy when several consecutive calls get through Do Not Disturb.

### Device info
**Device:** Xiaomi Mi 5
**Android version:** 7.0
**Signal version:** 3.31.4

### Link to debug log
https://gist.github.com/024897b2b723fc7a0b3c0aabf2f1709e

**Comment by tsdmgz** [comment]
may be related to #6169 (see last comment)

**Comment by DC7IA** [comment]
Nearly a year passed. I can't see any change. Any news?

This is really annoying: I can't use my phone to listen to music, because people call all the time.

**Comment by moxie0** [comment]
@DC7IA Please read the contributing guidelines before posting here again, thanks!

**Comment by kuro68k** [comment]
I can confirm that this affects my Google Pixel XL as well. Even though the phone is in "do not disturb" priority only mode, it still pings when messages come in.

I had a similar issue with older versions of QQ International. It was because they used the media volume to play notifications, instead of the ringer volume. Media volume isn't muted, I suppose the theory being that if you open up YouTube even during "do not disturb" time you probably do want audio.

So maybe the fix is to use the ringer volume for notification pings.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
