### ISSUE TITLE
Feature request: group admin can delete inappropriate content

### ISSUE THREAD

**Issue by Invictaz** [signalapp/Signal-Android#6451]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
I hope the feature can be added that group admins can delete inappropriate content. In Whatsapp when you delete an image as group admin, it is only deleted for yourself not for all the others. So inappropriate content can be posted. In short: a moderation option to remove this.

**Comment by dcherian** [comment]
There are no group admins in Signal.

**Comment by Dyras** [comment]
If you have someone posting "inappropriate content" in your group, you may want to create another group without him.

**Comment by johanw666** [comment]
And beside all technical issues, censorship doesn't really sound like the Signal philosophy.

**Comment by Invictaz** [comment]
Creating a group "without him" isn't a solution as you can have groups with dozens of users who can all behave on their own. They can litter the group chat with NSFW pictures etc. Censorship isn't maybe the right way but greyout or filter images.

**Comment by Dyras** [comment]
When a user finds another user to be disurbing I would suggest he just blocks them

**Comment by spacekookie** [comment]
I think this issue could be fixed by just allowing users to be kicked from a group which (IIRC) isn't possible right now

**Comment by dcherian** [comment]
What if everyone on the group blocks the person on their phone?

That way signal can figure out that there is consensus against that one person and kick him off the group. Would that be possible?

**Comment by mad-engineer** [comment]
Group-Chat is not useful at all if you can't kick/censor users with administrative privileges for various reasons. Let me summarize what my experience was.

Switched numbers without logout creates Zombies. No, users don't really care what happens to Signal. They just switch. WhatsApp has an number switch option, Telegram too. Signal not. No casual user put's additional effort into maintaining an app.

All users leave the group and create a new one without certain person does not work in real life if the group members are not closely related. You can do it once, but the second time several user just uninstall Singal. This is what actually happened in our friends group. We moved to WhatsApp. Mind it is also not an option for a large group where all others have to do additional work because of one over and over again.

You can't run an open group where anonymous people can enter. They will SPAM and pollute the entire chat.

Again, without administrator privileges the group chat option is useless in 95% of all cases.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
