### ISSUE TITLE
warn about sms being converted to mms!

### ISSUE THREAD

**Issue by derWalter** [signalapp/Signal-Android#6645]
sorry to (re)open this, but I did not find an open ticket where it does actually fit in!

My GF just lost some hundred Euros €€€ because her SMS invitation to her friends to her birthday party got automatically converted to MMS.
When the phone did not send the MMS she tried it again, resulting a big number of MMS. I guess due not being connected to the internet, the phone could not send the MMS. When she finally connected to the net, they flushed out and flooded her friends and now her phone bill, emptying her bank account. :disappointed: 

She has free sms but MMS are horribly expensive.

normal users dont have a clue about anything technical and initially don't react to small tips,
because they have never learned to pay dead serious attention to such.
we live in a world where dangerous things are being marked by terrifying big blinking dangerous looking signs.

**so please, put in a warning, the users have to accept or cancel,
stating that they know about the risk of high cost due to MMS sending.
And even better, giving em the chance to send a SMS to multiple users at once,
instead of converting the msg to MMS**

if signal is not safely usable by average users, it is not usable at all :cry:
now people are uninstalling the dangerous signal app and
dont want to every use it again, as it can break you... darn...
all the talking about security and such, down the :toilet: 

ps.: conversation feature is mostly not wanted at all, because
most people dont want that all contacts get all the other numbers as well.

**Comment by m3dialoud** [comment]
Ok, so if she was sending out a mass text to all her friends with invitations, which I assume was an image of a flyer or something, this would be a mass MMS message because it is an image she's trying to send; hence the meaning 'Multimedia Messaging Service'. If she was sending out a mass text with just "Hey come to my party Friday" it wouldn't ever go through as MMS... This is not a Signal issue... This is a user issue. Please become familiar with the term MMS and SMS and what they mean. Signal was made to allow you to contact another party whom has Signal and lets you have a secure conversation. 

I would say if she wanted to do a mass invitation and is concerned with cost of messages, she should use gmail or something and just add everyone to the email... Or buy an iPhone and use iMessage for invitations.

**Comment by caseorum** [comment]
@m3dialoud I believe he is referring to a group text, which is indeed sent over MMS.

The problem described here is that Signal does not allow one to send the same SMS to multiple people without manually copying and pasting  (#413). If you try to work around this by making a group, it will silently, and to most users inexplicably, send the text as an MMS to anyone that doesn't have Signal. This can be very expensive.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
