### ISSUE TITLE
SettableFuture always throws TimeoutException

### ISSUE THREAD

**Issue by artemalexpetrov** [signalapp/Signal-Android#6903]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
### Bug description
There is an issue in SettableFuture class. Overrided _get_ method with timeout parameters always throws TimeoutException because of wrong comparsion between elapsed time and timeout value.

```
//...
long startTime = System.currentTimeMillis();
while (!completed && System.currentTimeMillis() - startTime > unit.toMillis(timeout)) 
  wait(unit.toMillis(timeout));
}

if (!completed) {
  throw new TimeoutException();
}
//...
```

**Comment by FeuRenard** [comment]
So you are talking about [this method](https://github.com/WhisperSystems/Signal-Android/blob/f3e47f7b608a6beb77b6732d676b47c56184248c/src/org/thoughtcrime/securesms/util/concurrent/SettableFuture.java#L76). And the [flawed line](https://github.com/WhisperSystems/Signal-Android/blob/f3e47f7b608a6beb77b6732d676b47c56184248c/src/org/thoughtcrime/securesms/util/concurrent/SettableFuture.java#L81) should be:

`while (!completed && System.currentTimeMillis() - startTime < unit.toMillis(timeout)) {`

Right? (I reversed the greater-than sign, now a lesser-than sign)

Is this method used anywhere? Do issues occur while running Signal because of this?

**Comment by jeremymasters** [comment]
That statement looks fraught with chance for misinterpretation.  Seems like some extra parentheses would greatly remove occlusion of intended logic.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
