### ISSUE TITLE
Profiles: no way to hide the "share profile with group" message

### ISSUE THREAD

**Issue by vvug** [signalapp/Signal-Android#6927]
As the title says: if I don't want to share my profile with a group, there is no way to just hide the message that suggest doing so. There should be a way to change idea later and share the profile, but that bar is annoying.

An indicator to know if the profile is shared or not is also missing.

Not sure if this also happens in conversations with people not in the contacts list.

**Comment by schmeat** [comment]
You should be able to click the bar and select "no". I believe that's what I did.

**Comment by RichJeanes** [comment]
This bar should mimic the "Invite to Signal" prompt where it has a close button on it, as well as the ability to disable it by default from _Settings -> Chats and media -> Chats_ with a toggle like "Show profile sharing prompts"

**Comment by toddpratt** [comment]
This bug is really bad.  It takes up about 40% of my viewable text area above the keyboard.  20 days is a long time for this bug to sit around.  Everyone I talk to on SIgnal is really displeased.

**Comment by drathier** [comment]
Friendly bump; this is driving me crazy.

**Comment by csapdani** [comment]
Just updated to the latest version and having the same issue. Please fix this bug.

**Comment by nrizzio** [comment]
Please don't bump issues. It generates a lot of unnecessary email notifications. Use the thumbs up button on the issue description instead.

**Comment by moxie0** [comment]
@toddpratt @drathier @csapdani Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

It only makes it less likely to be resolved.

**Comment by interfect** [comment]
This is definitely a [dark pattern](https://darkpatterns.org/hall-of-shame) and I am disappointed to see it used in Signal. The app should not hold users' screen real estate hostage in an attempt to convince them to give up their privacy. There are almost certainly good use cases for being in a group and not sharing profile information, even if you have set up a profile that you are willing to share with your contacts.

In my case, this is doubly annoying, because I have the banner and I haven't even set up (and don't intend to set up) a Signal profile to share. So not only do I have a prompt I can't get rid of, but it's a prompt to share a thing that doesn't exist.

**Comment by moxie0** [comment]
@interfect Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

You just sent an email to hundreds of people without adding any material information to this issue. That takes up everyone's time, and only makes it less likely that I can do the work you're requesting.

**Comment by bodo-riediger** [comment]
Just Updated to Version 4.16.9, the Problem is not fixed.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
