### ISSUE TITLE
Conversation preference should use a shared element transition for the exit as well

### ISSUE THREAD

**Issue by mammuth** [signalapp/Signal-Android#7026]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When opening the conversation preferences there is a shared element transition / animation. When leaving the activity, there is just a fading animation.

### Steps to reproduce
- open conversation settings by tapping on the chat partner's name
- close it by pressing the back button or the arrow in the action bar

**Actual result:** 
The activity exit animation is a fading one

**Expected result:** 
There should be the same shared element transition as when entering the activity

### Device info

**Device:** Galaxy S5
**Android version:** 7.1, LinageOS 14.1
**Signal version:** 4.11.0

### Link to debug log

This is no bug report but a UI suggestion.

**Comment by moxie0** [comment]
I actually don't know how to do this. If you do a standard shared element transition for the avatar icon, it'll look weird because it'll scale down as a square and then suddenly switch to a circle after the transition is complete. I'm not sure how to make it look smooth, let me know if you have any ideas.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
