### ISSUE TITLE
Contacts don't sync to Signal Desktop anymore

### ISSUE THREAD

**Issue by mutantmonkey** [signalapp/Signal-Android#7125]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Contacts don't seem to sync to Signal Desktop anymore. This functionality used to work, but it no longer appears to. From what I can tell in the logs, it seems like Signal Desktop is doing the right thing but Signal Android never sends the contacts properly.

Related Signal Desktop issues: https://github.com/WhisperSystems/Signal-Desktop/issues/1499, https://github.com/WhisperSystems/Signal-Desktop/issues/1575 

### Steps to reproduce
- Start with Signal Android set up with various conversations and contacts in your contact list on Android
- Link Signal Desktop to Signal Android
- Notice that no contacts were imported during the initial linking process, but groups show up fine
- Go to Menu > Settings in Signal Desktop and use the "Import now" button to try to sync contacts

**Actual result:** The "Last import" date is updated on Desktop, but contacts are never imported. Groups show up just fine. On the Android side, nothing happens but there is an error in the logs.
**Expected result:** The "Last import" date is updated on Desktop, contacts are imported, and groups show up fine.

### Device info
**Device:** LG Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.11.5

### Link to debug log
Android (shows an EOFException): https://gist.github.com/anonymous/abe819938bdb4ca4c70fbfbc5f00d7be
Desktop (looks fine): https://gist.github.com/e8f91497c4ad837df05e6207054dd26a

**Comment by joshstoik1** [comment]
I am experiencing a similar inability to import contacts to Signal Desktop on Ubuntu Artful.

The application installation and device-linking worked, and I have been successfully sending and receiving texts. But when attempting to import contacts, I receive the following error:

> Import failed. Make sure your phone and computer are connected to the internet.

Both devices are online, and both otherwise working. I have retried a few times over several days, always with the same result.

The debug log shows a timeout error:
```
INFO  2017-11-03T18:49:42.844Z SyncRequest created. Sending contact sync message...
INFO  2017-11-03T18:49:42.880Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]061
INFO  2017-11-03T18:49:43.540Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]061 200 Success
INFO  2017-11-03T18:49:43.541Z SyncRequest now sending group sync messsage...
INFO  2017-11-03T18:49:43.550Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]061
INFO  2017-11-03T18:49:44.158Z PUT https://textsecure-service.whispersystems.org/v1/messages/+[REDACTED]061 200 Success
INFO  2017-11-03T18:49:52.422Z Sending a keepalive message
INFO  2017-11-03T18:50:42.844Z sync timed out
INFO  2017-11-03T18:50:47.511Z Sending a keepalive message
```

I was previously using the Google Chrome extension on the desktop and had no issues with contacts.

### Devices Info ###
**Device:** Lenovo X1 Carbon (Kabylake)
**OS:** Ubuntu: 17.10 (64-bit)
**Signal Desktop version:** 1.0.35

**Device:** Google Pixel XL (marlin)
**Android version:** Dirty Unicorns (based on 7.1.2)
** Signal version:** 4.11.5

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
