### ISSUE TITLE
New group is empty after I joined, no interaction possible

### ISSUE THREAD

**Issue by FeuRenard** [signalapp/Signal-Android#7134]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It seems like someone added me to a push group. I just got two messages. That's the only interaction I had with this group. I cannot send texts because the input panel is not responsive. I can't even type anything.

### Steps that happened
- I am not part of this group.
- I get two group messages in this group from the same person, presumably the creator

**Actual result:** Member list is empty, name is "Unbenannte Gruppe" (german for unnamed group), nothing happens when tapping on the input panel.
**Expected result:** Member list has entries, I can send texts to the group.

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.11.5

### Link to debug log
I received the two mentioned group messages some minutes before taking this log
https://gist.github.com/4f7a2b47c2a40e771e5cbd4a06f78c58

**Comment by dcherian** [comment]
I had the same issue a while back that I forgot to report.

My friend messaged me on Signal after a long while (some reinstalls might have happened). The conversation is titled "Unnamed group" and the Group Members list is empty.  

I cannot reply on Android but I can do so on Desktop. Messages sent from desktop are visible on Android. Desktop also shows an empty "Group Members" list.

Timestamp says Oct 13, so that should help narrow down which version.

Here's a log captured after I tried to reply on Android: https://gist.github.com/anonymous/6c74e595a942dd69d1bca85114fad0d8

@FeuRenard Can you check whether 
1. that you can reply using Desktop
2. that it is actually a group and not a conversation with a single person.

**Comment by FeuRenard** [comment]
Update:
The issue was fixed by the next message from the group creator. You can see in the screenshot that the group creation info message comes after four messages (three from group creator F, one from me).
![screenshot_20171027-192014](https://user-images.githubusercontent.com/16167751/32116896-aab16ade-bb4c-11e7-82df-3f6aa843dd91.png)
I took this log directly after receiving the "repair" message:
https://gist.github.com/a5a3d6057641b4c5d9601ee2f02b8577

@dcherian 
1. I can write and send a message on Signal Desktop and it is synced to my phone. It seems like the group creator got the message because he answered.
2. I suppose it's a group because of the message content.

**Comment by FeuRenard** [comment]
I just discovered in the single conversation with the group creator that a safety number change was noticed yesterday. The group creation was the first interaction with this contact after a long time. So the creation message might have been the first message with this new safety number.
Maybe this information can help with reproducing this issue.

**Comment by dcherian** [comment]
"The group creation was the first interaction with this contact after a long time. "

Same was true for my contact.

**Comment by xyzzyxw** [comment]
Possible workaround: ask a group member to edit the group details. This will cause an update of the group, which might resolve your issue.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
