### ISSUE TITLE
Bad encrypted message from myself??

### ISSUE THREAD

**Issue by nerdoc** [signalapp/Signal-Android#7154]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
30 minutes ago I got a message from my own phone number with "Fehlerhaft verschlüsselte Nachricht" - German for "Bad encrypted message".
Before you now tell me that there are plenty of closed bugs for that:
#509, #622, #2600, [#4844](https://github.com/WhisperSystems/Signal-Android/issues/4844),etc. But they do not address that problem: I did *not* send a message to myself. I didn't do anything. My phone rang twice within a minute, and there were two messages via Signal, sent from my own phone number.
Sent on "2.Nov.2017.18:49:52 MEZ", received on "2.Nov.2017.18:49:57 MEZ"

### Steps to reproduce
not possible to reproduce.

**Actual result:** Got a badly encrypted message from myself
**Expected result:** I don't expect getting messages from myself if I don't send them.

### Screenshots
Not possible in Android 6.0.1/Signal.

### Device info

**Device:** Using a Fairphone 2,  without Google Apps.
**Android version:** 6.0.1
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/anonymous/5768f7be094d09d423c362c2e86bf54b

(I then sent a message to myself and deleted them afterwords, before creating this bug report.)

**Comment by RiseT** [comment]
I think in order to synchronize, Signal Android/iOS and Signal Desktop communicate with each other via standard Signal messages (although they are not visible to the user). If something goes wrong with such a message, this can lead to the result you've described.

**Comment by nerdoc** [comment]
Yes, this could have been the cause, I was changing from the Signal Chrome App to the standalone Desktop App before. Totally forgot that.

**Comment by RiseT** [comment]
> But shouldn't that be invisible (as you said?).

That's true for the messages themselves. But apparently not for error messages caused by them.

> Could I do anything to reproduce this - is there a need of a fix? I saw a Java Exception in the logs.

My guess is that the issue is on the new Signal Desktop's side. But that's just a guess. I've had a similiar experience when setting it up initially.

**Comment by nerdoc** [comment]
Ok, so I leave it to you (@moxie0?) to close this or proceed here further - If you want me to add some more info by trying to create the Signal Desktop App initialization again etc., please tell me.

**Comment by i7u** [comment]
Exact same thing happened to me right after I removed the Chrome extension and installed the standalone app. Hadn't happened before, hasn't happened since.

**Comment by xyzzyxw** [comment]
I think these are messages you sent to another user. They are supposed to be encrypted with your own keys, so that you can decrypt them yourself, including your other devices. Apparently _something_ goes wrong there, so you get those "badly encrypted messages" at times. In my case it doesn't have to do with switching from Chrome to Electron, since I didn't switch yet. I often have this using the Chrome App and Android. 
Restarting the encryption sometimes helps.

**Comment by nerdoc** [comment]
But i did not send a message to another user.

**Comment by RiseT** [comment]
Just experienced this again.

Here's the log:
https://gist.github.com/anonymous/b0edc4bdb4251c36cd7e2bc63c3c60c9

**Comment by retroformat** [comment]
I'm researching the same problem on my devices (android phone, chromebook, macbook, several iMacs), and thus found this Github issue.  I'm observing a feedback problem which accelerates the generation of the error messages.  e.g. if I have my macbook running, and the Signal extension running, and my android phone awake and Signal running, I can observe these error messages coming in about one every two seconds.  Attempts to delete the "conversation" are only marginally successful.  Sooner or later they start up again.  Resetting sessions slows things down for a while but does not stop the problem.

**Comment by retroformat** [comment]
more detail, testing with android Signal (my "home" for Signal), and a chrome Signal extension on Macbook (OSX 10.6.8):

When I do anything at all on one device (e.g. android), an error message appears on other devices (e.g. macbook).  This error message appears as a message sent from me to myself.  On the macbook, the error is "Error Handling Incoming Message."  (I can open this message, see screen capture).  On the android phone the message is "Bad encrypted message" and I cannot open this message.

The feedback loop happens when I have the "error sessions" open in both devices at the same time.  Then the receipt of the error message in one device generates the transmission of another error message, which is received by the other device, thus generating another error message, etc.  It is impossible to shut down by deleting the sessions, as even this action transmits a (n invisible) message which will generate a (visible) error message, initiating a new "error session."  The feedback can be shut down if only one "error session" is being looked at.

**Comment by euclio** [comment]
I'm seeing this with signal desktop v1.2.0 on Linux. I tried sending a message to a group, and one of the contacts in the group received it, while the other got the bad encrypted message. I also received a bad encrypted message from myself. I'm able to reproduce this consistently by attempting to re-import my groups and contacts.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
