### ISSUE TITLE
Group chat: Can't send message or leave group after being added a second time

### ISSUE THREAD

**Issue by thomasp68** [signalapp/Signal-Android#723]
- Person A creates new group, invites persons B and C and sends message.
- B leaves group after sending a message and deletes group thread.
- A adds B again to group.
- B now gets new group messages, but can't leave again or send any more messages to group.

Happened to me on a Galaxy S4 with Android 4.3. I can delete the group thread, but it will appear again as soon as a new message is posted to the group.

**Comment by Ofenhed** [comment]
This issue still exists. I did exactly as @ghost did, but my friend is unable to add me to the group since I'm still there. 

To add information about the issue, I'm using the Desktop client, and I can communicate with the group perfectly using the Desktop client (and get synced messages to the Android client), but I'm not able to write messages on mobile, and the profile picture and name of the group is unknown to the mobile client. I've tried deleting the group on mobile, but I have no option to leave the group.

**Comment by 2-4601** [comment]
@Ofenhed 
Ask your friend to update the group with the following steps:

1. open the group conversation
1. open the menu
1. tap **Update group** in the menu
1. tap the checkmark (:heavy_check_mark:) in the top right corner

This "empty" update will send your Android client the group metadata.

**Comment by Ofenhed** [comment]
@2-4601 
That helped, thanks. Should the groups after reinstall be a separate ticket?

**Comment by 2-4601** [comment]
There already are #1048, #2581 :)
