### ISSUE TITLE
"draft:" in conversation list even if draft contains only spaces and will be automatically deleted

### ISSUE THREAD

**Issue by freeroot** [signalapp/Signal-Android#7308]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When you write a message only with spaces (for example "    ") to a contact and you don't send it but you come back to conversation list, there is not the last message of the conversation, just below the name, but "draft:" is displayed. When you re-enter to the conversation with this contact, draft is deleted. It's confusing to show "draft:" whereas there is no real/saved/restored draft.

### Steps to reproduce
- write "  " in a conversation
- go back to conversation list
- "draft:" is displayed below the contact name
- re-enter to the contact conversation
- draft were deleted

**Actual result:** Show "draft:" in conversation list even if draft contains only spaces.
**Expected result:** Do not show "draft:" in this case.

**Comment by 2-4601** [comment]
Related or duplicate #4729

**Comment by FeuRenard** [comment]
The root cause for this bug is located in `ConversationActivity`'s [`getDraftsForCurrentState()`](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/ConversationActivity.java#L1416). Inside this method the text input is checked for emptiness with [`Util.isEmpty(EditText)`](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/util/Util.java#L129). The string doesn't get [trimmed](https://docs.oracle.com/javase/8/docs/api/index.html) here. In the case of this bug the white space string is recognized as not empty and will be saved. But before saving the string gets trimmed. So the saved draft doesn't even include the white spaces. In consequence this empty string won't appear later in the text input again.
