### ISSUE TITLE
Enable HDR+ pictures on Signal by targeting API 26 (Pixel Visual Core HAL)

### ISSUE THREAD

**Issue by cegg1** [signalapp/Signal-Android#7398]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In Pixel 2 phones, third party apps get HDR+ pictures from the camera API by default as long as they target API 26 or greater. This is done through a hardware abstraction layer that uses the so-called "Pixel Visual Core" chip. WhatsApp and other apps are already using this in their built-in cameras to seamlessly take HDR+ pictures.

Thus, enabling hardware-accelerated HDR+ pictures on Signal appears to be straightforward. I'm happy to run a test apk if necessary. 

Documentation here:
https://opensource.google.com/projects/pixelvisualcorecamera
https://github.com/google/pixelvisualcorecamera

### Steps to reproduce
- Take a picture from Signal using a Pixel 2 or Pixel 2 XL with the 5-Feb-2018 Android update or above.

**Actual result:** The resulting picture is not HDR+ and the Pixel Visual Core is not used. 
**Expected result:** HDR+ pictures are produced by default on Signal's camera (where supported).

### Screenshots
Not relevant

### Device info
**Device:** Google Pixel 2 and Google Pixel 2 XL
**Android version:** 8.1 OPM1.171019.019 (since 5-Feb-2018 the HDR+ HAL is enabled by default)
**Signal version:** 4.16.5

### Link to debug log
Not relevant

**Comment by thestinger** [comment]
It also has to be done in a compatible way (using ZSL, etc.) so it's likely more involved than just targeting API 26.

**Comment by DarthSpock** [comment]
I second this feature request but it should be available for more than just the Google phones.  For me specifically Samsung Galaxy S phones are what I would like to see included. But as I already said, it should be for as many types of devices as possible, you can always put out a release that supports the major ones such as the type I listed.

**Comment by cegg1** [comment]
@DarthSpock As things stand, getting HDR+ outside the Google camera app requires that a specific piece of hardware is present in the device, known as the "Google Easel" Image Co-processor and marketed as "Pixel Visual Core". It is a chip believed to be related to the Intel "Monette Hill" platform. @thestinger Precisely, the nice thing about it is that it takes the burden of implementing HDR+ away from the the app developer.
https://www.google.co.uk/amp/s/www.androidauthority.com/pixel-visual-core-808182/amp/
Unfortunately, Samsung Galaxy phones are not equipped with the necessary hardware.

**Comment by DarthSpock** [comment]
Do you know if the camera for the S9 could be made to utilize it?

**Comment by thestinger** [comment]
@cegg1 It needs to be used in a very particular way, see https://github.com/google/pixelvisualcorecamera. It's better to use it via the non-deprecated Camera2 API using ZSL. It's very simple when doing it from scratch, since the Camera2 code from there can be used. It's not necessarily easy if there's a complex existing implementation with workarounds for various other devices, unless a separate implementation for this modern approach is added.

@DarthSpock No, it's only on the Pixel 2 and Pixel 2 XL.

**Comment by DarthSpock** [comment]
That's sad to hear but oh well. Good luck getting this implemented.

**Comment by thestinger** [comment]
@DarthSpock A modern Camera2 API compatible with the Pixel Visual Core could be used elsewhere and may provide significantly better image quality though, even without HDR+. Other vendors may be able to take advantage of modern usage of ZSL, etc. too.

**Comment by thestinger** [comment]
The issue is that this would probably end up being an extra implementation. It's really not as simple as just bumping the API level. It's simple if you're starting from scratch because you just copy-paste their sample app code and start from there, and add workarounds for devices to that while making sure HDR+ still works. It can be a lot more complex when you have existing code, especially to use the modern Camera2 API approach.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
