### ISSUE TITLE
Make "just joined Signal" notification optional

### ISSUE THREAD

**Issue by DreamFlasher** [signalapp/Signal-Android#7409]
### Bug description
Upon registration everyone who has my phone number gets a notification "X just joined Signal".

### Steps to reproduce
- Register with a new phone number

**Actual result:** Everyone having my phone number gets the notification
**Expected result:** I should be able to decide if people get this notification or not. 

This has been discussed here and should be a seperate ticket: https://github.com/signalapp/Signal-Android/issues/6750#issuecomment-322371164

**Comment by Dafnik** [comment]
Everyone can disable this notification on his own.

**Comment by FeuRenard** [comment]
This is a duplicate of #6423.

**Comment by rainmaker** [comment]
From #6423
>Changing Signal so that it didn't show you who you could communicate with using Signal until you explicitly tried to initiate a conversation with them using Signal (which may or may not succeed?) would in my opinion make Signal much more difficult to use.

Shouldn't users have the _choice_ of disabling this behavior, and can make the trade-off in ease-of-use if they prefer? Users who don't care can leave the settings as-is, and users who do care will feel secure. Furthermore, turning this off should be the default, and users can opt to broadcast their Signal presence if they prefer to use it as a social network. This could be part of the regular "Invite your friends to Signal!" dialogue.

>However, pretty fundamentally, anyone who knows your number will be able to see that you're a Signal user. 

This is true. A determined person could still "poll" to learn when a certain phone number has joined Signal, by initiating SMS via the app and seeing whether it resulted in a secure conversation. It would help to make their job harder by disabling the "X just joined Signal!" notification, but they could work around it. Many security precautions are incomplete, but that's no reason to throw up our hands and do nothing. Allowing users to make their attackers' lives more difficult is valuable.

This fix would make a difference to people, albeit a smaller minority in the overall user-base, but a group which I'd _hope_ you care about keeping. These people are actually installing Signal to talk about sensitive information, rather than simply to secure their every-day communication. They may already be under suspicion by others, and don't want to worry about this notification being the straw that breaks the camel's back (e.g. their boss calls them in to ask why they joined Signal) For those folks, learning about these notifications would be a nasty surprise. 

I think this is still worth discussing. I'm also happy to take the conversation to the forums if that's preferred.

**Comment by moxie0** [comment]
We've discussed at length why this is not possible, but if you have more thoughts then please visit the forums.  Please try not to open duplicate issues in the future, even if you feel like something is important.

**Comment by mlncn** [comment]
Signal is going around and telling every boss, every abusive partner, every racist uncle, every controlling parent, etc. that a vulnerable person has joined encrypted chat.

Signal need to do two things:

1. Tell people signing up to Signal that _other people can look up if you are on Signal_
2. Stop _broadcasting to everyone who has your contact in their phone that you are on Signal_

The responses by moxie presume that people are asking for some difficult technical thing, rather than changing the default behavior from "hey everyone that person you have stored in your addressbook for some possibly creepy reason is now on Signal! Creep them out!" to that stalker having to [look up on WikiHow](https://www.wikihow.com/Know-if-a-Contact-Is-Using-Signal) a way to spy.

I cannot find a single open one that speaks to this at all, though i do understand that ending the functional directory of Signal users is a goal: https://signal.org/blog/private-contact-discovery/ (though that's so focused on the technical, hiding stuff from your own phone, that i'm still not certain it would give you a way to not be outed to your abusive husband when you join the women's self-liberation group that communicates via Signal and he's already in a Trumper-Prepper group that communicates via Signal).

**Comment by rainmaker** [comment]
@mlncn 100% agree. It would be easy for a vulnerable person to be outed to someone who is dangerous to them, particularly now that Signal is more widely used. Many people have the app installed, so an aggressor wouldn't necessarily need to be fishing for this information to get it 😟

**Comment by leszek-s** [comment]
I think that for an app which markets itself with a sentence "Privacy isn’t an optional mode — it’s just the way that Signal works." the fact that those notifications are turned on by default is not a good decision. If a person who joins the app cannot prevent them then I think that they should be turned off by default and only people who manually turn them on should receive them.

**Comment by ViktorWalter** [comment]
I came here by searching ways to disable the involuntary information sharing.
That I have a software installed does in no way imply that I consented to everyone else with said software knowing I do.
People want private conversations for different reasons, and not everyone in my contacts is so close to me that I want them to know I have such reasons too.
I refuse to ever use the app again unless this is fixed.
The system has potential, but for something that markets itself as privacy-oriented this is past several lines.

**Comment by xe1st** [comment]
Is this still a thing?

**Comment by mlncn** [comment]
The option to not share your phone number at all *might* address this.

Part of this feature, announced here https://signal.org/blog/phone-number-privacy-usernames/ is:

> **Control who can find you on Signal by phone number**
>
> If you don’t want people to be able to find you by searching for your phone number on Signal, you can now enable a new, optional privacy setting. This means that unless people have your exact unique username, they won’t be able to start a conversation, or even know that you have a Signal account – even if they have your phone number.

However, this is an opt-in privacy feature, while the privacy feature of not sharing your phone number in chats will be *on* by default (opt-out), so Signal is still setting up lots of people to unwittingly announce to their abuser / boss / parole officer etc that they have joined Signal.

Indeed, if the announcement is immediate, before people have a chance to change their settings, this problem would not be mitigated much at all.  (It would be mitigated in the case of the person who needs to remain private joining Signal first and finding the option to disable anyone finding them by their phone number, before any potentially dangerous control freaks in their life joins Signal, but other than that, no, the problem described in this 'closed' issue is not fixed— and now that the alleged technical problems are overcome, it should be re-opened.)

**Comment by xe1st** [comment]
Which is a shame because it looks like they have no intention of disabling this notification thing. They can even make it optional when signing, but it looks like they won't.

**Comment by Groxx** [comment]
To attempt to resume this, or hopefully have it closed as "fixed":

Usernames rather clearly prove that Signal believes that broadcasting "X joined [by phone number]" is no longer necessary or always desirable, as you can simply set it private and switch to usernames.

But you still need a phone number to sign up.
Does it still broadcast that your phone joined, or has that giant ball of ick been stopped?

**Comment by quite** [comment]
What mlncn writes in https://github.com/signalapp/Signal-Android/issues/7409#issuecomment-1992092127 i still valid "Signal is still setting up lots of people to unwittingly announce to their abuser / boss / parole officer etc that they have joined Signal."

I am still getting announcements when phone numbers in my contacts are used to register a Signal account (got one less than one week ago). So this is definitely a thing, and it is on by default, happens more or less instantly upon account registration and contact sync is done. User may hurry into the app settings and disable "find me by phone number", but then it is too late for contacts that already have Signal and to which the notification therefor likely already has been sent.
