### ISSUE TITLE
signal support web site does not have a good bug tracking system

### ISSUE THREAD

**Issue by justbabbling** [signalapp/Signal-Android#7433]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I wanted to submit a bug report about a serious security problem to Signal, so I went to the Signal web site, but the problem is that I wasn't able to find any instructions referring me to any bug tracking tool to use to submit a bug report.

### Steps to reproduce
- find a serious security problem in Signal
- go to the official Signal support web site which is www.signal.org (the www is optional) (be sure to put this in the address bar of your web browser although you can also put it in the search bar and it will probably work there too)
- now look around for instructions on how to submit a bug.  I couldn't find any!  
- it looks like the closest you can come to any instructions on how to submit a bug report is this page:
https://support.signal.org/hc/en-us/requests/new   (this is a web form)
- fill out the web form with the information about your bug, and then click "submit"
- For example I filled out that I have found a problem whereby me and my friends keep having our signal messages delivered without encryption.
- wait for someone at signal to e-mail you back
- For example I got an e-mail back from Signal asking for more information
- reply to the e-mail with the requested information
- For example I sent back a reply with more information, steps to reproduce, etc.
- never hear from anyone at Signal about your issue again
- For example no one at Signal ever followed up on my bug report again. 
- And no one at signal told me hey there is a github bug page you can use to report bugs

Actual result: Describe here what happens after you run the steps above (i.e. the buggy behaviour)

ok sorry I already described it see above

Expected result: well like, instead of using a web form and e-mail to process bugs, you should maybe have a support page that actually directs people to your github bug tracking tool, for the love of Jesus Christ!

Screen Shot
![signal bug tracker kinda sucks](https://user-images.githubusercontent.com/36747715/36568643-58ca7c6e-17f0-11e8-8a08-91aad3762fbf.png)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by 2-4601** [comment]
Hi,
thanks for the detailed report and suggestion. In the past the GitHub issue trackers used to get a lot of support requests for the clients. This was making the life of the developers unfeasible because they had to reply to both support questions and to bug reports. The support site was revamped so that it would take the support traffic and GitHub could concentrate on bugs. That could be one reason GitHub is not advertised in the support site. But if you give feedback via the support form and the issue turns out to be a bug, the support staff should either direct you to GitHub or they'll create a bug report themselves. Why this didn't happen in your case, I don't know. Probably because the support is understaffed. But if you have a bug to report, please open a new issue here so we can take a look at it. I'll close this one and wait for your report about the issue you encountered.
