### ISSUE TITLE
Bad old messages after database upgrade

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#7465]
Today I updated Signal to the new 4.16.9 version. After the database migration, Signal started giving notifications. I estimate roughly around 25 notifications. Some related to contacts with whom I have not been in contacts since long. From the notifications that are still visible I see: "Bad encrypted message" (3x), and "Media message" (4x).

I see for example a new "Bad encrypted message" with a sent date of 2 December 2016 and a receive date of 6 March 2018, via Data (signal).

For another contact for whom according to the notification I should have received at least five media messages, I see in his thread twice for today "You safety number with xxx has changed". This contact posted quite a lot of media messages in a Signal group in the past. I did delete a lot of the media to free up space in the past, because Signal was taking nearly all my storage (see issue 4242 and issue #6539).

All the conversations with the new messages appear at the bottom of the contact list (because it are old messages I suppose). The newest "Bad encrypted messages seems to have been sent on 15 July 2017.

Unfortunately, submitting debug logs does still not work for me, see issue #7451.

In total there were at least 70 old messages marked as new. All of them images (that are not correctly displayed, I just see the download arrow, but downloading does not work), and bad encrypted messages and key change notifications.

Sending and receiving of new messages seems to work correctly at the moment. Old messages seem to be still available in their threads.

**Comment by janvlug** [comment]
I see that I also have messages "Message encrypted for non-existing session" for a contact.

**Comment by janvlug** [comment]
This is a debug log:
https://gist.github.com/janvlug/86a157368dad275b0503f89c19445167

**Comment by andres-erbsen** [comment]
I am also getting an ongoing flood of "bad encrypted message" from multiple contacts since I updated to 4.16.9 less than half an hour ago. The current timestamp of bad encrypted messages is 6/16/17, and some of them are from myself (I have used Signal to message myself in the past). I am suspecting I am getting this particularly bad since I have continuously and actively used the same Signal Android installation for a long time (along with Signal Desktop installations that I reset ~monthly to counteract the slowdown).


### Device info
**Device:** OnePlus ONE A2005
**Android version:** 6.0.1 (7, ONE A2005_24_171024) (up-to-date manufacturer rom)
**Signal version:** 4.16.9

### Link to debug log
https://hastebin.com/ihucahexar, a couple of minutes later https://hastebin.com/tinuducojo a couple of minutes later https://hastebin.com/mabagusalu At this rate it seems that the battery

Update: it shows 7/25/17 now, and still going, log: https://hastebin.com/etunatesoz

**Comment by moxie0** [comment]
I'm not sure that I understand the description. Are you saying that you have old messages which should have been marked as read, which are now marked as unread? Or are you saying that new old messages are appearing? Or are you saying that previously received old messages are reappearing?

**Comment by janvlug** [comment]
For me, messages with old time stamps appeared as new. All these messages were error messages or media messages that cannot be displayed/downloaded. I've also been using Signal for a long time. No correct 'normal' previous messages are re-appearing for me.

**Comment by janvlug** [comment]
As far as I can see now, the issue is not particular harmful, nor leading to data loss. I received old messages in  seven conversations (of the ~70 active conversations and 241 archived conversations). The issue seems only annoying so far. The conversation that is most affected show now 36 "Bad encrypted messages" with a sent time from the past that were received today.

**Comment by janvlug** [comment]
Could this be related: https://github.com/signalapp/Signal-Desktop/issues/2090

**Comment by moxie0** [comment]
When a Signal message is received, the first thing we do is write it to a DB queue, and then schedule a job to decrypt and process it asynchronously.

As part of this migration, we can't run those jobs immediately in some cases, so after the migration is complete, we iterate through the entire queue and re-schedule everything there. It seems like these are messages which were inserted into the queue long ago, and for some reason were never processed. Processing them now fails, of course, because they were encrypted for old sessions.

There's nothing I can do about it now, but it would be nice to understand why they were never processed to begin with, since they are essentially "missing messages."

**Comment by janvlug** [comment]
I tried to find some patterns in the messages.
The messages appeared in seven conversations: one with myself, one in a group, and five 'normal' contacts.
Only for one conversation I see "Message enrypted for non-existing session" messages.
The oldest messages is from 2 December 2016. The latest from 15 July 2017.
All but one messages come in pairs of conversation of the same date and time.
* One of the conversations is myself and someone else.
* Another one is a group for which I know that it went corrupt (see https://github.com/signalapp/Signal-Desktop/issues/1115#issuecomment-292172620) and a person who was part of that group. In the group appeared only two indications of Images. The images themselves are not there.
* One is of two contacts who are also both together in several groups.
* One message does not come paired, but this contact is/was also in several groups.
All newly arrived old messages are from contacts who are (or have been) in groups, one is in a group conversation itself. This group had about 50 members and went corrupt.
I am using both Signal Android on my phone and Signal desktop on several computers.
Interestingly enough, it seems that some of the error messages and key change messages that I reported initially in this issue (see the very top) are not in the conversations any more. I see now only two media messages and not a single key change message any more, contrary to what I noticed earlier as described above.

**Comment by andres-erbsen** [comment]
My "bad encrypted message" flood stopped sometime between 30min and 3h after my last post here. I can now see <100 "bad encrypted message" entries in three one-to-one conversations, although I think that I got more notifications than that (approximately 1/second, sustained for at least tens of minutes). Other than that, the mechanism of error proposed by @moxie0 is consistent with my experience. The conversations that have remaining bad encrypted messages are a subset of the contacts who (I chat with enough that) I have experienced the most message loss/garbling with. The latest date I have for a bad message is 7/25/17 as I noted down earlier; I do not see that message anymore, so I don't think I would necessarily see any later bad messages if there had been any.  here does not seem to be anything else wrong, so even though the behavior described here is rather startling, it seems not to have lasting effects.

**Comment by janvlug** [comment]
As this bug happened after the upgrade to 4.16.9, I cannot reproduce this issue any more. For me this issue can be closed, but I leave the final decision about closing this issue up to the devs, in order they want to keep it open for finding the root cause.
