### ISSUE TITLE
[4.17.0] Signal crashes when importing (large) backup

### ISSUE THREAD

**Issue by bungabunga** [signalapp/Signal-Android#7478]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes in the middle of the backup restoring process. Backup file was large, some 6k messages, 183MB.

### Steps to reproduce
- Install Signal
- Open it
- Restore backup

### Device info
**Device:** Sony Xperia Z3c
**Android version:** 6.0.1
**Signal version:** 4.17.0

**Comment by DarthSpock** [comment]
Actually there is a open issue so this is a duplicate. #7430 is what you want.

**Comment by bungabunga** [comment]
i don't know if it's a duplicate; that was a plaintex backup, mine was the new encrypted backup.

**Comment by DarthSpock** [comment]
True, that does make a difference. But if the failure is with backups in general, it won't matter if it's encrypted or plaintext. For now it can be said it's a duplicate because the issue appears to be the fact it's unable to process the .xml file completely. This means it won't matter if it's encrypted. If there's an issue after the plaintext is fixed, then it will be a cipher issue.

**Comment by DarthSpock** [comment]
I just compared our error logs and it's making me want to say it's the same exact issue, line for line. **If** it's not a duplicate then at the very least this issue has a dependency on the other issue.

**Comment by bungabunga** [comment]
@moxie0 i tried to restore the same backup (made with 4.17.0) on 4.17.1 and it crashed again. is this normal and the restore would only work with the backup made with 4.17.1+ or the issue stll isn't resolved and i should post another debug log?

**Comment by moxie0** [comment]
@bungabunga correct the fix only applies to backups created by 4.17.1

**Comment by aresius** [comment]
I think this is not yet fixed, have the same issue with 4.17.5.

**Comment by aresius** [comment]
Here is the error I get, not sure this is actually related to the other restore problems:
`03-28 22:37:44.725: E/AndroidRuntime(8242): FATAL EXCEPTION: AsyncTask #4
03-28 22:37:44.725: E/AndroidRuntime(8242): Process: org.thoughtcrime.securesms, PID: 8242
03-28 22:37:44.725: E/AndroidRuntime(8242): java.lang.RuntimeException: An error occurred while executing doInBackground()
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at java.lang.Thread.run(Thread.java:764)
03-28 22:37:44.725: E/AndroidRuntime(8242): Caused by: java.lang.NegativeArraySizeException: -1457244058
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:238)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:189)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:372)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:364)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-28 22:37:44.725: E/AndroidRuntime(8242): 	... 4 more
`
I'm not so used to Android development, so please let me know if I can provide further helpful information.

**Comment by aresius** [comment]
With 4.18.1, this issue is gone for me, so thanks.

**Comment by suand** [comment]
But the latest version in play store is 4.17.5. When will it be 4.18.1 released? Thanks!

**Comment by DarthSpock** [comment]
@suand I'm on 4.18.2 and it's on the beta channel. If you don't mind some of the bugs that come with beta, you can get more of the fixes too such as this one. It's easy to sign up for. Only have noticed a couple small things that are wrong so far that don't affect the ability to communicate with others. But that's just my experience.

**Comment by haffenloher** [comment]
Please sign up for the beta channel only if you want to help test the beta. Beta releases can introduce serious bugs, leading to crashes or data loss.

**Comment by suand** [comment]
Thanks for your answers! Yeah, I don't think I can help with that at the moment. But is there a plan  when the fix will be released officially?

Am 13. April 2018 01:07:58 MESZ schrieb haffenloher <notifications@github.com>:

**Comment by greenpeacealbert** [comment]
For me, this bug is also persistent with Version 4.19.3. 
 some > 14k messages ( I don´t really know as the process stops at 14000 the last backup created is always: never!

I´m a bit desperate for help.

**Comment by aresius** [comment]
@greenpeacealbert Did you verify in the logs that you hit this issue? Maybe you stepped into #7692 which in the GUI looks pretty the same (no message, backup stops at some point and no backup is created).
