### ISSUE TITLE
[4.16.9] & [4.17.0] Voice message plays, but the slider position stays at the beginning

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#7482]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When playing a voice message, the message plays, but the slider stays at the beginning. If I first try to put the slider in the middle of the duration, this works, but when pressing Play, there is a message "Error playing audio!".

When recording a voice message on my device, it works really well.

### Steps to reproduce
Get a voice message
Play voice message
Discover "frozen" slider

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info
**Device:** Oneplus One
**Android version:** 7.1.2
**Signal version:** 4.17.0 (but discovered it already with 4.16.9)

### Link to debug log
https://debuglogs.org/532966045207bbdf428c601ecdb17f65b15c0d92fb8437b3c357f9f1ce30fbfa

**Comment by junitas** [comment]
The snippet of the debug log below leads me to believe both of the problems you encountered had the same root cause of the Media player not able to get the duration. That could conceivably result in both not being able to seek and calculate the slider position based on file offset.

'08:48:33.540 10357 10357 W MediaPlayer: Stream has no duration and is therefore not seekable. 
03-09 08:48:33.540 10357 10357 E MediaPlayer: error (-2147483648, 0)
03-09 08:48:33.542 10357 10357 E MediaPlayer: start called in state 0, mPlayer(0x586ff600) 
03-09 08:48:33.542 10357 10357 E MediaPlayer: error (-38, 0) 
03-09 08:48:33.543 10357 10357 E MediaPlayer: Error (-2147483648,0) 
03-09 08:48:33.544 10357 10357 W AudioSlidePlayer: MediaPlayer Error: -2147483648 , 0 
03-09 08:48:33.552 10357 10357 E MediaPlayer: Error (-38,0) 
03-09 08:48:33.552 10357 10357 W AudioSlidePlayer: MediaPlayer Error: -38 , 0'

**Comment by p4nci** [comment]
[Manually calculate attachment offsets ](https://github.com/signalapp/Signal-Android/commit/028c6edd8a4a7497490440875abde89c4c0d036b) can be the culprit (since Signal v4.16.7)

**Comment by 2-4601** [comment]
Maybe related #4655

**Comment by greyson-signal** [comment]
There's been changes to audio playback that have hopefully fixed this.
