### ISSUE TITLE
4.16.9 keeps crashing when trying to open the app

### ISSUE THREAD

**Issue by bytemybits** [signalapp/Signal-Android#7554]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Whenever I try to open the app, it crashes.

### Steps to reproduce
- Open the app

**Actual result:** The app crashes
**Expected result:** The app opens normally

### Screenshots
![signal-crashing](https://user-images.githubusercontent.com/8046519/37768189-9dfa2f2a-2dc4-11e8-9a65-0b4c7cdd2fd2.png)

### Device info

**Device:** OnePlus One (bacon)
**Android version:** 7.1.2 (LineageOS 14.1-20180321-NIGHTLY-bacon)
**Signal version:** 4.16.9

### Link to debug log
Because I can't open the app, here's the adb locat.
[signal adb logcat.txt](https://github.com/signalapp/Signal-Android/files/1837284/signal.adb.logcat.txt)

**Comment by haffenloher** [comment]
Dupe of #7534, #7532, and #7453.

**Comment by bytemybits** [comment]
Sorry for creating a duplicate, I only found unrelated LineageOS bugs when searching, but I'll close it now.

@haffenloher quick question: I don't actually have a passphrase set up, any chance for a database backup or it just wouldn't work? Trying to figure out if I'm going to loose all data since last backup or not.

**Comment by haffenloher** [comment]
@bytemybits as far as I know, the whole Signal database is encrypted with a key stored in Android's keystore since Signal 4.16 (whether you set a passphrase or not). If the key is indeed gone due to that LineageOS bug, there's nothing you can do. Someone reported success with a ROM downgrade though: https://github.com/signalapp/Signal-Android/issues/7534#issuecomment-374542948 - so maybe that's worth a try? Good luck!

If you want to continue the discussion, let's do so in the [forums](https://whispersystems.discoursehosting.net) instead to avoid cluttering up the issue tracker and generating more email notifications.

**Comment by Diapolo** [comment]
https://review.lineageos.org/#/c/LineageOS/android_system_security/+/210422/ and https://review.lineageos.org/#/c/LineageOS/android_system_security/+/210421/ have been merged in the LineageOS repo. Is anyone able to do a LOS build and see if Signal does recover with these applied?

**Comment by caugner** [comment]
> Is anyone able to do a LOS build and see if Signal does recover with these applied?

@Diapolo I just upgraded to a LOS build that includes the fixes; unfortunately it doesn't recover Signal.
