### ISSUE TITLE
Switch Silence to Signal

### ISSUE THREAD

**Issue by atao** [signalapp/Signal-Android#7575]
How import Silence backup to Signal app?

Don't work for me.

Thanks

**Comment by piratenpanda** [comment]
This is not a forum. Try the community forum linked here

**Comment by johanw666** [comment]
Which backup? The encrypted backup will not work because there are differences between the Silence database structure and Signal's. The plaintext backup should work (as long as that feature is not removed from Signal but with the export gone I expect the import will be removed some time in the future as well).

**Comment by atao** [comment]
I export in plaintext from Silence but the import in Signal not work...

**Comment by leonardoporpora** [comment]
@atao ask in the forum https://whispersystems.discoursehosting.net
