### ISSUE TITLE
Legacy plaintext export unavailable on v4.17.5 Android. 

### ISSUE THREAD

**Issue by samschr** [signalapp/Signal-Android#7597]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can no longer export plaintext backups after updating to 4.17.5 on Android. 

### Steps to reproduce
- Export menu option is removed
- Navigate to chats & media
- Create new-style backup

**Actual result:** Signal creates a backup of all text and media in conversations. Backup size is 500MB
**Expected result:** Backup size should be comparable to legacy size Legacy plaintext XML backup (2MB). Alternatively, new backup method should have option to only back up text.

### Device info
**Device:** LG G5
**Android version:** 7.0
**Signal version:** 4.17.5

**Comment by johanw666** [comment]
Unfortunately that's supposed to be that way.

**Comment by igor2x** [comment]
This bug report is feature request and/or discussion about export. According to the [recent bug tracking cleanup rules](https://github.com/signalapp/Signal-Android/issues/7598) gets into the category: _If you disagree with the way that a feature is working (but it's working!) that's not a bug._

@samschr, please join the discussion in forum about backup and why is plan text export removal a bad thing in topic: [Lets talk about backups!](https://community.signalusers.org/t/lets-talk-about-backups/2237). Welcome.

In my humble opinion, this issue should be closed down, because it is not a bug report.
