### ISSUE TITLE
support key rollover

### ISSUE THREAD

**Issue by graingert** [signalapp/Signal-Android#7599]
I've moved to a new phone! :D

But in doing so I exported my private key to Google Drive (and also the NSA) and copied it to my new phone.

It would be great if I could send a message to all my contacts that trust me with a key rollover message.

**Comment by jlund-signal** [comment]
Hey, @graingert. Thanks for reaching out, but this doesn't follow the new issue template. We're only using GitHub to track bugs in existing functionality moving forward.

Signal introduced support for [advisory safety number changes](https://signal.org/blog/verified-safety-number-updates/) last year. This feature automatically shows your contacts when your safety number has changed. Many other new features have been added to Signal since November 2013 that make the process of moving to a new a phone much easier too.
