### ISSUE TITLE
Location Link Broken

### ISSUE THREAD

**Issue by mikecardwell** [signalapp/Signal-Android#7604]
I did you a favor by opening https://github.com/signalapp/Signal-Android/issues/6786 and you've just gone and auto-closed it. It contains all the information required to investigate the bug already. Consider this my re-submission. Feel free to close it and retain the bug in your software.

**Comment by moxie0** [comment]
Thank you for the submission, but the attitude is not helpful. Please try considering, if only for a moment, that you may know what the best thing is for development on a project that you have zero involvement developing. Fixed in 4.19.0

**Comment by mikehardenize** [comment]
Consider what sort of attitude is required to dismiss work provided by others without even looking at it. If you close peoples bug reports without looking at them, they will rightly be annoyed.

**Comment by mikecardwell** [comment]
Consider what sort of attitude is required to dismiss work provided by others without even looking at it. If you close peoples bug reports without looking at them, they will rightly be annoyed.

**Comment by sampablokuper** [comment]
@moxie0 if #6786 was fixed in 4.19.0, then why did the dev who committed or merged the relevant commits not also use them to close #6786?

That is the dev's oversight, not @mikecardwell's.

Also, to tell someone who has taken the time to file a bug report, with screenshots, that they have had "zero involvement in developing" the app is deeply condescending and ungracious.

For both these reasons, it is completely inappropriate to criticise Mike's attitude here.

Yes, you have built an impressive piece of software. But that does not justify abusing people who are trying to help.
