### ISSUE TITLE
Registration Lock Pin Dialog Will Not Submit (go away)

### ISSUE THREAD

**Issue by GuardianMajor** [signalapp/Signal-Android#7623]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Other than the fact that we get the PIN verification way too often and unnecessarily interrupting; now on the latest beta it pops up, you put in the pin and press enter and the keyboard goes away but the dialog remains and there is no way past it - effectively blocking access which is horrible (although sometimes pressing somewhere else in the Signal screen will make it go away, which defeats the purpose it was trying to achieve - possibly it IS submitting the code, just not dismissing the dialog - clean up issue/gui glitch?)

### Steps to reproduce
- Open the app
- Put in the passphrase
- Registration Pin lock pops up
- Enter the pin
- Press enter

**Actual result:**
- keyboard goes away
- dialog continues to remain with no way to submit/dismiss it
- (sometimes) pressing anywhere else in the window will make it go away and show the messages

**Expected result:** Once you put in the pin it should submit and go away like before, but it doesn't.

### Device info

**Device:** Motorola Nexus 6 (shamu)
**Android version:** 7.1.1 (N6F27M)
**Signal version:** 4.18.0 (beta)

**Comment by FeuRenard** [comment]
A debug log would be very helpful in this case:
https://support.signal.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-from-Signal-Android-

**Comment by GuardianMajor** [comment]
@FeuRenard No need to link it, I am a professional, if I had it, I would have included it. I will do my best the next time I face the situation. The fact is that it happened and needs to be addressed.

It seems that the information is submitted, but it won't dismiss the prompt, which means someone just needs to look at where that clean up comes after validation and make sure it is happening. If I had time, I would look at the code and submit the pull myself.

**Comment by FeuRenard** [comment]
I do not observe this behavior in 4.18.0 (Android 6.0). As expected the dialog disappears immediately after entering the last digit of the registration lock PIN.

**Comment by moxie0** [comment]
As soon as you type in the correct PIN, the dialog will disappear. There's no need to press "enter." If you're typing in a PIN and the dialog is not disappearing, most likely you're typing in the incorrect PIN.

The more often you type in the correct PIN, the less often you'll see the dialog. The more often you type in the incorrect PIN, the more often you'll see the dialog. You can always dismiss the dialog by hitting "back" or tapping elsewhere, but that will make the dialog appear more often.

I would recommend unsetting and resetting your PIN so that you don't get locked out of your account.

**Comment by moxie0** [comment]
@GuardianMajor The dialog is simply a tool to help users remember their PIN. It's important that people do, because there is no equivalent of a "password reset." If you forget, you're locked out.

The dialog is not "authorizing" access to anything. It is a cancelable dialog. You can dismiss it by hitting back, or by tapping anywhere else on the screen. Just like any other cancelable dialog. It will dismiss itself once you've entered the correct PIN. If it's not dismissing, *you have not entered the same PIN that you originally set*. Again, I would advise you to set your PIN correctly so that you don't find yourself locked out of your account (as you will be locked out if you try reinstalling right now).

**Comment by GuardianMajor** [comment]
@moxie0 Oh I know why and it is fine. While a bit too often prompted, it has been less recently and that's fine, I have no problem with the principle behind it at all, kudos on that.

I was simply reporting the "visual cleanup" issue that seems to have crept into it and wanted to let you guys know so maybe a code check would reveal why it is not removing it off the screen after it is done doing what it is doing, that's all. I can only test it again when it pops up the next time, so I am waiting to see if I can repeat the problem, but I wanted to be proactive in case it can be resolved and pushed into the next update.

I see, good to know it is not authoritative and can be dismissed but still should be responding correctly and going away when pin is properly inputted and not have to be cancelled to go away 😃 

You are saying I am not entering it correctly but it has been the same since I chose it, it has always been put in the same, it has always been correct and it has always dismissed before, just not now (since the last update or so, and since we have no clear changelogs provided for each update, we have to guess when/if it got changes unless we crawl the commits). So how would it phantom change all of a sudden or be wrong without reason? Unless it got corrupted with some back-end update or whatnot? So, you see where I am coming from? Saying emphatically that it is wrong isn't supported by the facts on my end. By your logic, even if I tried to change it now, it would fail as well - correct? Make sure I understand it.
