### ISSUE TITLE
 Signal thinks my name is too long

### ISSUE THREAD

**Issue by espindola** [signalapp/Signal-Android#7648]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
My name is "Rafael Ávila de Espíndola". When I try to register signal complains that the name is too long.

### Steps to reproduce
- Enter Rafael Ávila de Espíndola when asked for the profile info.

**Signal version:** 4.17.5

**Comment by moxie0** [comment]
Thanks for the report, but unfortunately this is the intended functionality. Because of the way we're doing the encryption, all profile names are padded to the exact same length, so that the server learns nothing about the value. That means it can't be arbitrarily long, and it also means that we can't make the maximum huge, since everything will get padded to the maximum. Sorry that it means your full name doesn't fit =(
