### ISSUE TITLE
[4.17.5] Signal doesn't show any contacts on LineageOS

### ISSUE THREAD

**Issue by infosec-handbook** [signalapp/Signal-Android#7681]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There aren't any contacts when I open Signal and press on the 🖋 icon (bottom right). The list is empty. Additionally, all of my contacts (after exchanging several messages) are shown as phone numbers only. There is no contact info added based on my Android contacts. Signal only shows additional info if a contact added name and picture directly in their Signal app.

- "Refresh" (by pressing either refresh or gesture) has no effect (rotating arrow is shown for about two seconds)
- Deleting Signal from Accounts in Android preferences has no effect (it is removed, can't be readded)
- Reinstalling Signal has no effect (there are still no contacts)
- Deleting all of my contacts on the device and readding them has no effect (Signal still doesn't recognize them)
- Restarting the device and/or Signal or deleting Signal's app data/cache has also no effect
- Deleting storage and cache of Android's contact storage (com.android.providers.contacts) has no effect (after synchronizing contacts in Android again, I open Signal and it still does not recognize my contacts)
- Creating several contacts only on the device (without synchronization) has also no effect since Signal doesn't show these contacts, too
- In chats, I can select "Add to contacts" (although this contact is already stored on the device). After that I can add the contact to my Android contacts and it shows that the contact information has been added. When I return to Signal, "Add to contacts" is still shown and I can repeat this process forever.

It seems that Signal can't access my contacts, however, Signal Desktop which is synchronized using this device recognizes my contact list and shows the expected names and photos of my contacts (only in Signal Desktop). Signal Desktop also immediately updates my contacts when I refresh them on my device.

Signal (on Android) does show all of my contacts when I set Signal as my default SMS app. Then Signal shows names and phone numbers, but after selecting an entry the name disappears and only the phone number is shown.

Originally, I encountered this bug in Signal 4.17.5, however, it is still present in 4.18.3.

### Steps to reproduce
- Install Signal on the device with contacts already on the device
- Open Signal and activate it
- Press 🖋 (bottom right) and there "Refresh"

**Actual result:** Signal doesn't show any contacts
**Expected result:** Signal shows a subset of contacts on my device who are also Signal users

### Possible bug fix
I fixed this issue by completing [the steps mentioned below](https://github.com/signalapp/Signal-Android/issues/7681#issuecomment-383920754).

### Screenshots

![screenshot_20180415-123904](https://user-images.githubusercontent.com/35793040/38777690-33100d60-40ac-11e8-9543-638830308bff.png)

### Device info

**Device:** Motorola Moto G4
**Android version:** 7.1.2
**Signal version:** 4.18.3

### Link to debug log

https://debuglogs.org/6ceb1bc491226c888c1f2890c3b8cd428dafc247025bdf388cc7e9ff31d5d6a7

_Edit:_ Added further information.
_Edit 2:_ Bug is still present in Signal 4.18.3.
_Edit 3:_ Possible fix found.

**Comment by JoeAlreadyTaken** [comment]
I am having the same issue with a Samsung S5, a lineage os and the new signal version. Signal does show all contacts, when i allow it to be the standard sms app, but then it won't import all my sms conversations. There is no error displaying, it says it is importing them but they don't show afterwards.

I do not want to use signal for sms, because I am using another app that encrypts sms and i use it to chat with people that are not using signal. And additionally, there is this import-problem.

**Comment by Konsumopfer** [comment]
I have the same problem, exactly like it is described on Samsung Galaxy S4 mini with lineage and microG. If I want to add a signal account in the android account settings, nothing happens but instead the screen is frozen.

**Comment by transmutated** [comment]
I'm also impacted, word for word, by this issue. I'm also running lineageOS. My contacts are being synced to my Motorola X Pure (2015) with a radicale server using DAVdroid.

**Comment by SwartzCr** [comment]
I'm having a similar problem on a new Pixel 2. I installed signal, told it to import my contacts and linked a computer.
Contacts appear when searching by name, but none of my conversation threads have contact names listed, they are all bare phone numbers. Obviously users who have made signal profiles show their profile name, but others are just numbers.
Probably more like #7394 or #4803
I've tried refreshing the account, asking signal to resync contact list, and re-installing. None of these have fixed the issue. I have a debug log taken right after install and sync if that'd be useful.

**Comment by jtracey** [comment]
>DirectoryHelper: Failed to create account! 

I recognize this. In my case I assumed it was bad writes to storage, but maybe there's a bug in Signal. I had similar symptoms on my old phone, and investigated a bit. Like @Konsumopfer reports, what I saw was when I tried to do anything with a Signal account in android settings->accounts, it would hang. I think the bug results from a desync between the `/data/system_ce/0/accounts_ce.db` and `/data/system_de/0/accounts_de.db` databases. I noticed that I had a Signal account in the former (ce), but not the latter (de). My guess was that Signal was trying to use the account, but the de db was returning that it didn't exist, so then it would try to create it, but fail because the account already exists in the ce db.

The way I worked around it was deleting the Signal entry from `/data/system_ce/0/accounts_ce.db` every time I restarted my phone (again, I just assumed the storage was bad X] ), which would let the account creation succeed. This workaround requires root and a shell though. If you have those and know a bit of sql, just load up the databases in sqlite3 and remove the Signal account from the one that has it (I don't remember the layout off the top of my head, if you need help with the sql query I can look it up and write it for you).

If this really is a bug in Signal though, it should be fixed. I don't use that phone any more, but if the devs want me to I could probably figure out a way to install Signal on it again and investigate more.

**Comment by infosec-handbook** [comment]
Hey @jtracey, thanks for the tip.

I **fixed** the issue on LOS 14.1 (nightly from Apr 18, 2018) by completing the following steps:

1. Go to phone settings, activate developer mode, enable USB debugging, enable root via adb
2. Connect your phone with your PC
3. On your PC type: `$ adb root`, then `$ adb shell`. The terminal switches to your phone's shell.
4. Type `# sqlite3 /data/system_ce/0/accounts_ce.db`. The next line begins with `sqlite>`.
5. Type `DELETE FROM accounts WHERE name = "Signal";`
6. Disconnect from your phone, disable developer mode, open Signal, press the :fountain_pen: (bottom right) and refresh.
7. All Signal contacts are back.

If you don't know the structure of the table, you can use `PRAGMA table_info(accounts);` and `SELECT * FROM accounts;` to see if there is an entry for Signal.

Actually, there was a similar issue in Nextcloud (nextcloud/android#1531). However, some people reported that this only **temporarily** fixed this issue in Nextcloud. So, I don't know if refreshing contacts in Signal will work in the future.

**Comment by Konsumopfer** [comment]
Great, that works! Fine! Thank you so much! Hope that will be fixed in further Signal-versions.

**Comment by moxie0** [comment]
Looks like this is another bug in LineageOS, and I don't see any action we can take. I'd recommend filing a bug with the LineageOS folks.

**Comment by infosec-handbook** [comment]
@Konsumopfer 
https://wiki.lineageos.org/bugreport-howto.html

**Comment by nightbluepn** [comment]
Apparently this is due to the app living in external storage.
Solution is to first make sure no orphaned account entry exists in accounts_ce.db and to then move the app to internal storage.

**Comment by theBoatman** [comment]
> Looks like this is another bug in LineageOS, and I don't see any action we can take. 

Well at least it would be possible to inform the user that there was a problem, especially if the contact sync was triggered manually. I know you don't like LineageOS, but I am sure there are other problems that could happen during contact sync, too.

**Comment by santa-klaus** [comment]
For the record, [here](https://jira.lineageos.org/browse/BUGBASH-1611) is the bug in the LineageOS bugtracker. You might consider voting on it if you also experience it.
(Their bugtracker for this issues is only open from friday to monday)

**Comment by ForrestLineager** [comment]
Hey,
first of all: thank you guys for all the information provided above.
I am experiencing the very same bug with Signal 4.34.8 on LineageOS 14.1.
Could one of you tell me, if a factory reset via TWRP and only using the internal storage afterwards (excluding sd card) would possibly suffise to fix the bug? Or won't I be able to fix it without ROOT (and knowledge about sql & shells) anyway?

By the way: Is it my fault that I don't find the bug in the LOS bugtracker / on their gitlab site? Should it actually already be fixed?
