### ISSUE TITLE
Signal kept crashing on start after update from 4.17.5 to 4.18.3 and crashes on importing backup from 4.17.5

### ISSUE THREAD

**Issue by lahmann** [signalapp/Signal-Android#7694]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In order to move my Signal conversations from my old Samsung S4 Galaxy (Android 5.0.1) to my new Sony XZ1 Compact I created a backup with Signal 4.17.5 on the S4. Importing this backup on the XZ1c repeatedly failed with Signal crashing. I found a workaround by applying with the S4 for the beta-programm, installing Signal 4.18.2 and creating a backup, which was successfully imported on the XZ1c with Signal 4.17.5. Signal worked fine the previous four days.

However after the update to Signal 4.18.3 last night, Signal won't start anymore and kept crashing on starting the app with the following exception (obained via adb logcat):

```
04-17 12:20:05.681 12153 12178 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
04-17 12:20:05.681 12153 12178 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12153
04-17 12:20:05.681 12153 12178 E AndroidRuntime: net.sqlcipher.database.SQLiteException: Can't upgrade read-only database from version 4 to 6: /data/user/0/org.thoughtcrime.securesms/databases/signal.db
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:252)
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:181)
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:668)
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-17 12:20:05.681 12153 12178 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

So I tried to recover the previous days' backups made by Signal 4.17.5 on the XZ1c, which kept failing as well (after processing about 12000 messages which is the exact same crash behaviour as seen four days ago when importing my 4.17.5 backup from the S4 on the XZ1c) with exception:

```
04-17 20:50:59.884 30956 31431 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
04-17 20:50:59.884 30956 31431 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 30956
04-17 20:50:59.884 30956 31431 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1174457208 byte allocation with 2899518 free bytes and 509MB until OOM, max allowed footprint 5799038, growth limit 536870912
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:238)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:189)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:372)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:364)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-17 20:50:59.884 30956 31431 E AndroidRuntime: 	... 4 more
```
Luckily I still had the above mentioned workaround-backup (created with Signal 4.18.2 on the S4) which I was able to successfully import. In the end I only lost the past four days messages. The backups are each 623MB in size.

### Steps to reproduce
- create backup with 4.17.5
- update Signal to 4.18.3
- reset settings
- import backup from 4.17.5
- for obvious reasons I cannot provide you my backup-file for testing... any suggestions how I might assist?

**Actual result:** As described above, every backup created with 4.17.5 fails to import to 4.18.3 with the above mentioned OutOfMemoryError-Exception 
**Expected result:** Import should work.

### Device info

**Device:** Sony XZ1 Compact
**Android version:** 8.0.0
**Signal version:** 4.17.5/4.18.3

### Link to debug log
see above

Edit: corrected affected Signal versions.

**Comment by tbsn** [comment]
I've got a similiar problem. Due to the backup on removable storage issue I went back from 4.19.1 to 4.18.3 (Backup and import worked fine).

Now updating from 4.18.3 to 4.19.3 crashes Signal with:
`04-30 12:22:08.746 W/SQLCipherOpenHelper(4644): Upgrading database: 6, 7
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): Couldn't open signal.db for writing (will try read-only):
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): net.sqlcipher.database.SQLiteException: duplicate column name: quote_id: ALTER TABLE mms ADD COLUMN quote_id INTEGER DEFAULT 0
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.onUpgrade(SQLCipherOpenHelper.java:172)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:173)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:227)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:191)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:668)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-30 12:22:08.760 E/SQLiteOpenHelper(4644): 	at java.lang.Thread.run(Thread.java:761)
04-30 12:22:08.796 E/AndroidRuntime(4644): FATAL EXCEPTION: pool-3-thread-1
04-30 12:22:08.796 E/AndroidRuntime(4644): Process: org.thoughtcrime.securesms, PID: 4644
04-30 12:22:08.796 E/AndroidRuntime(4644): net.sqlcipher.database.SQLiteException: Can't upgrade read-only database from version 6 to 7: /data/user/0/org.thoughtcrime.securesms/databases/signal.db
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:252)
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:191)
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:668)
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-30 12:22:08.796 E/AndroidRuntime(4644): 	at java.lang.Thread.run(Thread.java:761)`

Importing a backup from 4.18.3 in a fresh 4.19.3 install crashes at the end of the process:
`04-30 12:29:21.947 E/AndroidRuntime(7269): FATAL EXCEPTION: AsyncTask #1
04-30 12:29:21.947 E/AndroidRuntime(7269): Process: org.thoughtcrime.securesms, PID: 7269
04-30 12:29:21.947 E/AndroidRuntime(7269): java.lang.RuntimeException: An error occurred while executing doInBackground()
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at java.lang.Thread.run(Thread.java:761)
04-30 12:29:21.947 E/AndroidRuntime(7269): Caused by: net.sqlcipher.database.SQLiteException: duplicate column name: quote_id: ALTER TABLE mms ADD COLUMN quote_id INTEGER DEFAULT 0
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.onUpgrade(SQLCipherOpenHelper.java:172)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at org.thoughtcrime.securesms.database.DatabaseFactory.upgradeRestored(DatabaseFactory.java:138)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:364)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-30 12:29:21.947 E/AndroidRuntime(7269): 	... 4 more`

It would be great to be able to update to the newest version keeping my history. Thanks!

**Comment by moxie0** [comment]
As you've discovered, creating a backup and restoring it on an older version will not work. Or at least, it will work until you try to update the older version. I'll look into adding some logic that prevents restoring a backup onto an older version.

**Comment by tbsn** [comment]
That could help getting tricked in such a situation.

Is there any way or do you have an idea how I can keep my 10000+ messages and not stuck to an old version? That would be greatly appreciated.

**Comment by sarevok-anchev** [comment]
I'm experiencing something similar myself.

Running on LineageOS 14.1, using **Noise** from the copperhead repo.

Was happily running either 4.15-0 or 4.15.5-0 (this was a week ago already), and upgraded to 4.18.3-0.

To my sad surprise, all the messages/conversations instantly disappeared.

I had/have a backup made with *oandbackup* prior to the upgrade, both apk and data.

Forcibly downgrading with pm install -d -r base.apk (downgrading from oandbackup directly doesn't seem to work, although it doesn't report any error, and indeed, claims success) and - everything is there again.

I have many dozens of conversations that are worth keeping and any help in performing a smooth upgrade would be greatly appreciated. If I keep a backup of the apk+data and just start over from 4.18.3-0, then chances are I'll never go back and look at the old messages .. especially without the search function.

An upgrade was attempted a few more times, right now it is at a point where starting the latest version just crashes the app.

I reverted to 4.15.5-0 (both data and apk) and everything is there, just unusable since "the version has expired".

@moxie0: "I'll look into adding some logic that prevents restoring a backup onto an older version."

How about refusing to do so only if there are incompatible changes and restoring it on an older version would mean certain trouble?

I followed your comments on a couple of other issues about this and I understand your stance about it "not being supported", but fact of the matter is that had it not been for such workarounds, my signal (noise) data would have not survived 3 phones, since to the best of my knowledge the backup function up to at least 4.15 did not include multimedia messages, rendering it rather useless in my case.

Oh, speaking of backup function - I also did try to use the backup function inside noise (4.15) and import it with 4.18, but alas, it crashes while importing - perhaps worth mentioning, even though it would have not solved the problem anyway (no multimedia messages).


I can't claim to fully understand why several people are running into this bug, but one thing seems clear: if the data is there with 4.15.5-0, it ought to be possible to make 4.18.3-0 recognize and correctly import it ..

Would a logcat be welcomed?

**Comment by Voltaine** [comment]
hey @tbsn 
had more or less the same problem as you did, restored an old TB backup and then signal crash when upgrading to version 4.19.3 
I "solved" the issue as follows:

1. Save all the relevant media (pictures, videos) to my internal storage using the signal gallery (using this method you wont have any media left in signal, only messages)
2. Use this program https://github.com/xeals/signal-back to decrypt a current backup file to get all the messages into an XML file
3. Edit the XML file with windows editor and delete the password: phrase right at the beginning of the file (the file should start with something like <xml... )
4. Rename the backup file to SignalPlaintextBackup.xml
5. Copy the file to the root of your phones storage
6. Download Signal 4.16.9 apk file from apkmirror
7. Uninstall your current signal installation (keep track of all the different passwords for the different backups you might end up having)
8. Install 4.16.9 from the apk file you downloaded before 
9. this version still has the import plaintext backup function --> use it to import all of the messages you earlier saved to the XML file
10. upgrade to the most up to date version via play store 
11. create a backup in 4.19.3 (different password for the new backup)
12. if you want you can try to uninstall and reinstall 4.19.3, to see if the new backup is working correctly 

That's it!
It bugs me a bit that all my media is gone from my chats, but i saved the most important things to the gallery, so I can get over that, glad I still have all my messages
If you have questions, feel free to ask :)

**Comment by tbsn** [comment]
Thanks for sharing your idea, I have thought of that way myself (to my knowledge recent versions still do contain plaintext import / 3dots / Import, at least 4.18.3 does).

However, I still have a little hope for something like a database upgrade or any other way of keeping media inline.

**Comment by tbsn** [comment]
I had no luck getting help on the forums, so I'm trying it here again before I'll give up.

The problem is described in detail above: https://github.com/signalapp/Signal-Android/issues/7694#issuecomment-385372506
I suspect the introduction of quoted replies in 4.19.x changed the database in a way that 4.18.x isn’t supposed to upgrade from.
Since this is a very specific problem it probably won’t get fixed or repaired by a dedicated cleaner.apk.

My phone is rooted so I can pull the signal.db and the USRSKEY_SignalSecret.
I tried opening signal.db with DB Browser for SQlite but don’t know how to get the required passphrase from the USRSKEY_SignalSecret.

Is there a way to open and edit the database into a 4.18.x state, from where I would be able to update to newer versions again, keeping groups and media?

Thank you very much.

**Comment by MaxKoll** [comment]
I have the same problem as tbsn. I downgraded to 4.18.3, because 4.19.x did not create backup files. Since then I am not able to upgrade Signal to any version above 4.18.3 anymore; it will crash on opening (same after deleting app data and importing my encrypted 4.18.3 backup).

In the log I also find this line:
`06-21 13:13:09.716 19921 19946 E SQLiteOpenHelper: net.sqlcipher.database.SQLiteException: duplicate column name: quote_id: ALTER TABLE mms ADD COLUMN quote_id INTEGER DEFAULT 0`

As tbsn I would be grateful for help on how to repair the database. My phone is also rooted.

**Comment by moxie0** [comment]
@tbsn @MaxKoll Any time you go "backwards" with a Signal install, you will almost certainly cause irreparable damage to your install. It's not supported by stock Android for many reasons. Doing it in a rooted environment might work temporarily, but it will eventually break the app. It's not a behavior we can support.

In your cases it looks like you already have a DB column that is trying to be recreated. Unfortunately sqlite doesn't support dropping a DB column, so you would need to rename the entire table, create a new table without that column, then copy the contents of the renamed table into the new table.

It's a sqlcipher database, so you can't use DB Browser. Alternately, you can modify Signal to not run that specific migration. In either case, it's something you'll have to explore on your own, although you're welcome to discuss on the forums.

**Comment by Trolldemorted** [comment]
DB Browser appears to have [dedicated sqlcipher releases](https://nightlies.sqlitebrowser.org/latest/), shouldn't they work with signal if you know the key?

**Comment by moxie0** [comment]
@Trolldemorted I'm not sure, please discuss on the forums rather than here. Thanks!

**Comment by tbsn** [comment]
Thanks for the explanation.

[Here's the discussion topic](https://community.signalusers.org/t/update-chrashes-how-to-edit-signal-db/3256).
DB Browser asks for the SQLCipher-Passphrase, but how is it obtained from the USRSKEY_SignalSecret?

**Comment by tbsn** [comment]
The particular problem mentioned in https://github.com/signalapp/Signal-Android/issues/7694#issuecomment-385372506 is resolved [here](https://community.signalusers.org/t/update-chrashes-how-to-edit-signal-db/3256/2?u=tbsn0).

**Comment by greyson-signal** [comment]
We've blocked the ability to restore newer backups on older versions, which should prevent problems like this in the future.
