### ISSUE TITLE
Replies: Contact name & cancel button in quoted message too dark when using dark theme

### ISSUE THREAD

**Issue by RiseT** [signalapp/Signal-Android#7705]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The contact name contained in quoted messages is too dark (no sufficient contrast) and thus hard to read when using the dark theme. **Note that viewing the screenshots on a monitor looks better than in real life on an actual phone.**

### Steps to reproduce
- Use the Reply feature on a message

**Actual result:** Contact name is hard to read
**Expected result:** Contact name is not hard to read

### Screenshots

![screenshot_20180419-183034](https://user-images.githubusercontent.com/12624674/39006198-ab6aa640-4402-11e8-8b00-9d9034101453.png)

### Device info

**Device:** Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.19.1

### Link to debug log

n/a

**Comment by halb9** [comment]
I would like to add that this goes for the cancel X button on a quoted reply as well. When using dark theme this is almost impossible to see. It is better when quoting a picture since then an X with a transparent grey background is used. 
Have a look
![signal-2018-04-20-091604](https://user-images.githubusercontent.com/18451020/39038368-e26365fe-4472-11e8-93ad-4d63835151c9.jpeg)
![signal-2018-04-20-091617](https://user-images.githubusercontent.com/18451020/39038379-e81e3d70-4472-11e8-829b-6877e3b73996.jpeg)

**Comment by greyson-signal** [comment]
I switched up the quote background color in dark mode, and made the little circle around the X default in dark mode as well. Hopefully it's a bit easier to read now!

![reply-to-dark-mode-improvments](https://user-images.githubusercontent.com/37311915/39078691-d54bb91c-44c1-11e8-8d55-4108f947f57f.png)

**Comment by RiseT** [comment]
@greyson-signal Unfortunately, this is still hard to read on Android 7.1.2. Which begs the question why it looks different on Android 7.1.2 than on Android 8.1:

Android 8.1 (note the green reply bubble background, the decent contrast of contact name and the hard to see cancel button):

![screenshot_20180425-132656](https://user-images.githubusercontent.com/12624674/39243273-3c071cae-488d-11e8-9c43-aa2305e94f52.png)

Android 7.1.2 (note the gray reply bubble background, the rather hard to read contact name - at least on an actual phone display - and the somewhat better to see cancel button):

![screenshot_20180425-132559](https://user-images.githubusercontent.com/12624674/39243367-752c506c-488d-11e8-865a-144406297205.png)

I like the look of the Android 8.1 version much better (apart from that nearly invisible cancel button).

**Comment by greyson-signal** [comment]
@RiseT The colors should not differ by Android version. I believe you've implied you have two different versions of Signal installed, which I'm assuming is the culprit. Let me know if that's not the case, though.

And yeah, to be honest, this dark theme situation is tricky :) Different phones have different color profiles, and while this combination looks good on my device, it's clearly not looking great on yours. I might take another look and see if we can tweak some values. We had decided to make the background of the quote bubble grey in the dark theme because it appeared to solve most of the readability problems, but looks like at least one combination still needs tweaking :)

**Comment by da-anda** [comment]
is there a chance to adjust the dark theme in general? I love the dark theme of Threema, but the one of Signal is IMO not at all friendly to the eye. Instead of a deep black background, a dark grey (with maybe a slight noise/pattern) on it should be more appealing in general. Is there a UI dev group or alike to get in touch with or some docs to read about the design decisions? Don't mean to offend anyone, but IMO there is room for improvement. I can provide screenshots of the Threema theme if anybody is interested.

**Comment by 2-4601** [comment]
@da-anda Open a thread here: https://community.signalusers.org/
