### ISSUE TITLE
Domain Fronting

### ISSUE THREAD

**Issue by WinstonPrivacy** [signalapp/Signal-Android#7751]
Hi @moxie0 and the Signal gang,

We can potentially help you with the domain fronting issue. Best way to contact you?

**Comment by s1awa** [comment]
Signal could use [DGA](https://en.wikipedia.org/wiki/Domain_generation_algorithm)!? Some VPNs use it successfully to avoid domain blocks.

**Comment by vmichalak** [comment]
@s1awa How signal can make an efficient DGA if his source code is fully open source ?

**Comment by s1awa** [comment]
@vmichalak 
DGA algorithm can always be reverse engineered even in closed source. But it still works. Because the effort to block it is too high and needs to be done continuously.

Depending on how you set it up, the countries would need to block millions of possible domains every month/week to keep the block effective.

You can always register dirt cheap domains from the pool, if previous one has been blocked.

This method is used effectively by some VPNs that still work in China. Even though they try hard to stop it.

Use it to access an API that provides server IPs which process signal traffic.

**Comment by moxie0** [comment]
Please do not delete the issue template or use GH issues for discussion. If you'd like to start a discussion, please use the forums. Thanks!
