### ISSUE TITLE
Duplicate of #5293. Re-open it please.

### ISSUE THREAD

**Issue by getbacktoworkmatt** [signalapp/Signal-Android#7796]
I can no longer in good faith recommend Signal to friends and family if you don't take issues like  #5293 seriously. My mother stopped using Signal since it doesn't work on her device. Signal on my phone still sends Signal messages to her unless I toggle insecure SMS using the hidden "hold this button to toggle" option. 

Understandably in a crisis situation one forgets how to operate unintuitive and nonsense software. That's what happened today and suffice to say I'll no longer use this project. Good UI/UX can actually save lives in some situations.

**Comment by cainlevy** [comment]
Signal is losing the mass audience with this issue. It's the opposite of a network effect because the lost users frustrate current users and create more lost users.

I understand the reason for not allowing users to set an insecure preference for certain contacts is that it might result in messages being accidentally sent insecurely.

This is a UX issue that can be resolved. An insecure-by-default conversation should appear in a way that does not easily allow confusion.

**Comment by 2-4601** [comment]
Unfortunately re-opening the old issue or creating a new one and discussing it here is not going to help getting the situation solved any faster. I'm sure one can argue that this issue is a bug (and a frustrating one) but in terms of the recent cleanup guidelines this is a feature request and should be discussed in the forums. Here's [a thread](https://community.signalusers.org/t/remember-the-current-message-mode-sms-or-mms-for-each-contact/2382/) where you can propose how to best handle the switching between Signal and SMS transport.
