### ISSUE TITLE
Encrypted backups not working

### ISSUE THREAD

**Issue by eb053049** [signalapp/Signal-Android#7813]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am unable to create a backup ever since plaintext backups were removed. I have searched for other issues and found them related to external storage, however my phone has no removable storage. Tapping "Create backup" causes my conversation history in all conversations to disappear and my phone cannot send or receive any messages until Signal is killed or my phone is restarted.

I'm not really a technical user at all and didn't understand if this is the same as #7802. If so, feel free to close this issue.

### Steps to reproduce
- Open Signal and navigate to Settings -> Chats and media
- Tap "Create backup"

**Actual result:** 
- A progress bar will appear with the text "0 messages so far". Tap back button to return to conversation list.
- Tap into any conversation listed. It will be empty.
- Going back into Chats and media settings will show "Last backup: never" and the progress bar will be gone.

**Expected result:** 
Backup would work and not freeze Signal

### Device info
**Device:** Google Nexus 5x
**Android version:** 8.1 (LineageOS 15.1)
**Signal version:** 4.19.3

**Comment by haffenloher** [comment]
> I'm not really a technical user at all and didn't understand if this is the same as #7802.

It probably is, but we can't tell without a debug log. Could you capture one and post a link?

**Comment by eb053049** [comment]
Sure, but first I wasn't able to find if this log would contain any personally identifiable information on this page https://support.signal.org/hc/en-us/articles/115005925767-How-do-I-send-you-a-debug-log-

**Comment by nrizzio** [comment]
> I wasn't able to find if this log would contain any personally identifiable information

[Debug logs are stripped of personal information.](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#debug-log-privacy)

> When I go to submit a bug report after tapping "Create backup", it only shows "Loading logs..." but never actually loads the log.

Do you know how to use the `logcat` command?

**Comment by eb053049** [comment]
Hi. Here's a log I was able to capture immediately after pressing "Create backup". If I had waited another 30 seconds or so, the logs would not be accessible, so hopefully it was not taken too early to capture what is going on.

https://debuglogs.org/76984822f8a24bc7332d582d4edf49915680ed4ece4ecf5193ff99cdb065ded3

**Comment by madfusker** [comment]
Confirmed issue here as well.  I'm trying to change phones and seems impossible until this is fixed.  I was able to find a singal.blah.backup file, but no matter where i put that file it is not picked up by the app.

**Comment by velosol** [comment]
@madfusker Signal looks for the encrypted backup file in your external SD card (/storage/NNNN-NNNN typically where N is a number) under: Android/data/org.thoughtcrime.securesms/files/Signal/Backups/signal-YYYY-MM-DD-hh-mm-ss.backup .  Signal only picks it up (per another comment under one of the backup threads) when it is freshly installed and has not otherwise been setup.  In that case it will prompt for your passphrase (the 6 sets of 5 digits given when you enable backups).

Not that I've been able to get a working backup file, but I'm trying! 😄

**Comment by madfusker** [comment]
That worked and I was able to restore, thanks!

What I noticed in settings now is that I have a "last backup" data and time from my original backup file, however hitting backup again doesn't change it.

Here is what I think might be happening: Signal is looking in this specific location for the backup file to read time and date, however the backup file creation is failing without error.  If the file is never created, the last backup is still "never" after it appears to create the backup.

**Comment by velosol** [comment]
@madfusker That looks like you might have the problem in #7692 .  You should be able to check the debug log after attempting to create an updated backup to confirm that.  Basically the file is not being created properly.  Signal can successfully read the SD card for import but creating a new backup doesn't work.  If you need to create a new backup ejecting and then physically removing the SD card seems to do the trick by causing the backup to be created on the internal partition (/storage/self and then Signal/Backups or similar) per steps at the bottom of the 7692 comment chain.

**Comment by georgedorn** [comment]
I have this same error.  Here's the output from logcat:

```05-22 10:53:14.415 10562 10848 W JobConsumer:
05-22 10:53:14.415 10562 10848 W JobConsumer: java.io.IOException: Renaming temporary backup file failed!
05-22 10:53:14.415 10562 10848 W JobConsumer:   at org.thoughtcrime.securesms.jobs.LocalBackupJob.onRun(LocalBackupJob.java:78)
05-22 10:53:14.415 10562 10848 W JobConsumer:   at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
05-22 10:53:14.415 10562 10848 W JobConsumer:   at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

**Comment by eb053049** [comment]
My phone does not have any external sd card. This is a nexus 5x experiencing this issue.

**Comment by velosol** [comment]
Sorry myself and the other 2 more recent posters were ultimately off-topic to your issue.

I haven't looked at a lot of the Signal code, but based on your debug log I was wondering if you were running any greenify, memory manager, task killer, etc type programs?  If so, could you pause them or exclude Signal from them and retry the backup?

When you press' Create Backup' if you just hang out on that screen for 2-3 minutes, ideally without screen timeout, do you ever see more than '0 messages so far'? Just trying to figure out if Signal is even starting on the backup.  If it doesn't even get to this point it may be that using logcat as @nrizzio alluded to will be necessary.

How long have you waited for Signal to create the backup?  It can take tens of minutes or more depending on the size of your messages.  If you go to your phone's Settings -> Apps -> Signal, how much space is listed under 'Storage'?  I have ~1GB worth of messages and it took 10 minutes or so to create a backup on a phone from a similar era as your 5X.

**Comment by velosol** [comment]
For logcat I assume you're already familiar with Android Debug Bridge (ADB) as you're running Lineage OS.  If not you might want to Google for instructions for your computer setup and for the ADB drivers for your phone.  The CliffsNotes are: download it from https://developer.android.com/studio/command-line/adb, enable Developer Options in your phone (tapping the software build number under System Info 7 times) then enabling USB Debugging under Developer Options.  I'm not suggesting the following steps are the most efficient as I haven't done Android dev in a long time but they do work.

* Connect the phone to your computer.
* Open a command prompt (navigating to where adb is installed) and run `adb devices`
* Accept the debugging prompt on the phone screen
* Run `adb shell` then `ps | grep thoughtcrime` then `exit`
* Look at the output of that command, something like `u0_n534  12345 2047   1284524 ...` we want the second entry, in this example `12345`
* Enter `adb logcat --pid=12345 > signal.log`
* Follow your steps to reproduce from the initial submission, when you're done you can interrupt the logging (Ctrl+C)

Now you'll have a file named `signal.log` in the directory you're in.  The problem is this won't be scrubbed of personal data.  The minimum I would search for is phone numbers in the form of: +<countrycode><number> and then replace with +*****NN where NN are the original final 2 numbers of the phone number (e.g. for North America: +11234567890 to +*********90) to have the log match the in-app version somewhat.  Then you could post the log on pastebin.com or similar.

I hope someone else will chime in if there are better ways to approach getting a logcat when the built-in one doesn't work.

**Comment by eb053049** [comment]
Thanks for the instructions velosol.

I finally got the 4.20.18 update and everything is working perfectly with backups. The release notes said it included a fix for backups on devices with external storage, but it also fixed my backup issues as well even though I don't have external storage. Thanks everyone.
