### ISSUE TITLE
Retry sending messages until delivered

### ISSUE THREAD

**Issue by DreamFlasher** [signalapp/Signal-Android#7888]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When having an unreliable data connection regularly messages are trying to be sent and then changes status to `not delivered`/`failed to send`. 

### Steps to reproduce
- be in a phone network with flaky connection
- send a couple of messages

**Actual result:** Some messages get a red exclamation mark next to the message, it says 'Not delivered' and 'Tap for details'. Tapping yields 'Some issues need your attention' and 'Failed to send' with the option to 'resend'.
**Expected result:** This should never appear. Apparently the client is able to realize that the message was not delivered, so it should try to resend the message until the message is sent. 

### More Details
This is a well-known issue for a long time: https://github.com/signalapp/Signal-Android/issues/2384

### Device info

**Device:** Blackberry Priv
**Android version:** 6.0.1
**Signal version:** 4.19.3

**Comment by greyson-signal** [comment]
Not sure if this qualifies as a "bug" - more of a request to change app behavior. Nonetheless, I'll keep this ticket open because I do want to improve the retry flow. That being said - it's unlikely the error message and manual retry button will go away completely.

In situations with poor network, you can't just retry constantly -- you'll kill the user's battery by keeping the radio on. Instead, you usually do something like [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff), which while more efficient, will also lead to larger gaps between retries as time goes on. That means it can still be helpful to show a manual retry option once the gaps between automatic retries gets large enough.

Anyway, yes, we're going to look into improving this :)

**Comment by DreamFlasher** [comment]
Ah that's unfortunate that the error message and retry button will not go completely. Cause in Whatsapp and Telegram they don't exist (actually I don't know any messenger which has this behaviour). That's also why this looks like a bug to me: From an end-user perspective there seems no need for this, because enough other apps can do without. 

I don't understand the battery argument: If the connection is flaky the phone tries to connect all the time anyways (so the radio is on all the time anyways?), and being in a poor network clearly drains the battery. Is there a possibility to check if the phone has a working internet connection and then try it again?

**Comment by ChrisG683** [comment]
I get "message failed to deliver" notifications in Facebook messenger and Hangouts every now and then with a manual retry option, so I wouldn't say it's totally unusual.

Can't say I've run into that issue on WhatsApp yet, although I have seen messages sit waiting to deliver for minutes sometimes, it eventually goes through though.

**Comment by greyson-signal** [comment]
Fixed in #7914
