### ISSUE TITLE
Took update from Play Store yesterday; Signal Force Closes now

### ISSUE THREAD

**Issue by ultrajae** [signalapp/Signal-Android#7945]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android 5.01

Saw the notification for the update yesterday. Let it update, then an hour later, attempted to click on the icon on my home screen to start it and it just Force Closes.

Rebooting the phone didn't help

Additionally, upon reboot, the Signal icon on the home screen became the generic Android icon and it still wont start. Starting from the app drawer is no different (the icon is correct in there).

I had never made any backup of my conversations withing the app; I'm hoping I don't lose my conversations.

I have a connected instance of  Linux desktop Signal still running OK.

### Steps to reproduce
- Accept the Play Store update to the current version from the previous (current) version.

**Actual result:** After successful update, app force closes immediately. No conversations/contact list, no menus, just a blank "opening" screen for a second then back to the home screen.
**Expected result:** Proper launching of the app.

### Device info

**Device:** LG G3
**Android version:** 5.0.1
**Signal version:** 4.21.6, current in Play Store

### Link to debug log

Using adb, and grepping through the log for "signal", only one line is seen:

E/AndroidRuntime(29831): net.sqlcipher.database.SQLiteException: Can't upgrade read-only database from version 7 to 10: /data/data/org.thoughtcrime.securesms/databases/signal.db

I've grepped for securesms and got more. The logfile is attached.
[Signallog.txt](https://github.com/signalapp/Signal-Android/files/2140118/Signallog.txt)

More complete log attached to my comment here:
https://github.com/signalapp/Signal-Android/issues/7945#issuecomment-401578055

**Comment by xeals** [comment]
Search the log for "thoughtcrime" or "securesms" as well, since that's what the app is named as a package.

Getting the same issue on a fresh restore of the database as well.

The initial and subsequent crashes give [these logs](https://gist.github.com/xeals/53bef1d8275f81048ef83b3810f72f54) (restore.txt and after.txt respectively).

**Comment by ultrajae** [comment]
I wonder if I clear the app cache, OR if I install the 4.21.6 directly downloaded from signal.org DIRECTLY over the 4.21.6 from the Play Store, 

If either of those "methods" could get Signal working on my phone without the loss of my long message history..

**Comment by johanw666** [comment]
Clearing the cache does not harm the messages, it contains mostly images in the attachment viewer who are recreated when you open that. And the play store and website versions can be installed over each other as well - they only differ in update mechanism.

**Comment by ultrajae** [comment]
welp, clearing cache didn't do anything.

I'm dying here. I do NOT want to lose TWO years worth of messges/history/images by uninstalling/reinstalling

I cannot believe that there's no hope.

I suppose I'll try to install from the web version and pray that it magically works.

:shudders:

**Comment by xeals** [comment]
What worked for me (I sort of alluded to it earlier, but didn't actually say) was using an old release from APK Mirror that used the same version of database as mine. I haven't upgraded it again yet, but a working outdated app is better than no working app.

**Comment by ultrajae** [comment]
Thanks.

I may try that route.

BUT- Unlike you, I have no backup, and since I (allegedly) successfully installed the upgrade, but could never run it, does that mean (hopefully not) that the new version of Signal already did something to change the database.... and I understand that one cannot go "backwards" to older versions and "restore" the database..


hmm

**Comment by tbsn** [comment]
@xeals your log mentions database version 6 and `net.sqlcipher.database.SQLiteException: duplicate column name: quote_id: ALTER TABLE mms ADD COLUMN quote_id INTEGER DEFAULT 0`

If you possibly have "downgraded" your app or backup at some point you might want to have a look [here](https://community.signalusers.org/t/update-chrashes-how-to-edit-signal-db/).

**Comment by greyson-signal** [comment]
@ultrajae Can you post a more liberal logcat output? There's some other logs that get printed during the upgrade process that I'm not seeing here that could help us debug. You could try including the tag "SQLCipherOpenHelper" in your filter. Thanks!

**Comment by ultrajae** [comment]
@greyson-signal I'm not too familiar w the adb syntax to make it more verbose.

I've simply done
_$ adb logcat > signal.txt_

and then
_$ grep -i securesms signal.txt_
to get that log above.

If you can give me a command line example that is better, I'll be happy to try it and run Signal again to capture a better log.

**Comment by greyson-signal** [comment]
@ultrajae So filtering by application is actually a super annoying problem to solve. The easiest way to do it is to install pidcat from [here](https://github.com/JakeWharton/pidcat). Then you can just run `pidcat org.thoughtcrime.securesms` and get all of Signal's logs.

You can also just provide your raw, unfiltered `adb logcat` output if you're comfortable with that.

**Comment by ultrajae** [comment]
I'll give pidcat a whirl if it doesn't take me too much time. Soon after that, I'll have to install the prior version of Signal over this current one as I've now been w/o a messaging app for too many days and I need to get back up.

**Comment by ultrajae** [comment]
I've updated the OP with the pidcat log (Signallog2.txt) from when I try to launch the current (4.21.6) Signal, and it FC after flashing the white screen...

**Comment by greyson-signal** [comment]
@ultrajae Thank you! I can see now that the reason your upgrade is failing is because of:

```java
net.sqlcipher.database.SQLiteException: duplicate column name: shared_contacts: ALTER TABLE mms ADD COLUMN shared_contacts TEXT
```

So somehow you have a database that already has the `shared_contacts` column (which was added in DB version 8) even though the logs say you're upgrading from DB version 7. 

In fact, I even see this log:

```java
DatabaseUpgradeActivity W LastSeenVersion: 368
```

That means you were upgrading from build with version code 368, which was the 4.20.9 release. The DB version for that release was 9. So this all looks very strange to me.

Did you ever install a self-compiled build, install an older version after having a newer version, use a rooted backup solution, or restore from a backup made by Signal? I can't see how this would happen during a normal upgrade path, so I'm just wondering if you've gone through any interesting version histories or backup/restore paths.

Thanks!

**Comment by ultrajae** [comment]
None of the above.

The only oddity I can recall (and this is not Signal specific per se) is that My Contacts have always been a little "screwy", in that, I (still to this day), have "copies" of certain contacts, that are only assigned to the Whatsapp account.. I recall at one point trying to either "join" or delete certain dupes but wasn't able to.. I just forgot about it tbh.. That was 1-2 yrs ago IIRC.

SO-

Is there a way out of this situation for me?

**Comment by greyson-signal** [comment]
So, off the top of my head, the only path forward I can see where you keep your messages is to:

1. Backup your `Android/data/org.throughtcrime.securesms` directory (which you should be able to do on a rooted phone). Note that while you can see the folder without root access, there's lot of files in there (notably, the database) that you will only see with root privileges. 
2. Uninstall Signal.
3. Compile a custom build that removes offending migrations and install that.
4. Replace `Android/data/org.thoughtcrime.securesms` with your backed up version.

At that point, after you're up and running, you'd have the option to complete steps (1) and (2) again, and then go back to the Play Store version of Signal and do step (4).

This is just an idea, however, and I can't guarantee that it'll work. 

I'm interested in how your app could possibly get in this state. When you upgraded Signal, had you not used it in a while? I'm trying to imagine how your app could be at version 4.20.9, and at least at DB version 8 (almost certainly 9) since you already performed that migration, but the database still thinks it's version 7. Could be some screwy bug with your rooted ROM? Honestly have no idea.

**Comment by ultrajae** [comment]
Jesus man. That's a freaking haul to salvage this...

Would not installing the prior version over this version work like it did for @xeals?

As far as how it got like this- My OS is stock 5.01 from LF,  nothing special, just rooted. I use Signal every day, I saw the Play notification for updates avail, this was there and in took it, like always..

Could it be because of WhatsApp? Perhaps that upgrade did something? I recall also taking a WhatsApp upgrade a day or so before this signal one...

**Comment by greyson-signal** [comment]
@ultrajae Yeah, I'm sorry, this is just a really bizarre problem. It's making me think that there's some bug in the database implementation, or some weird disk write error.

You can go the route of downgrading your app to get back on DB version 7. In that case, you'd want to go back to 4.19.x. However, just know that if you do that, you still won't be able to upgrade to new versions. On top of that, Signal builds expire in 90 days, at which point we don't allow the builds to send messages. In the case of 4.19.x, that means you'd be able to use that version for ~10 days before you'd be unable to send messages.

I know this all really stinks, and I apologize for it. I'm talking with some different people to see what could cause something like this to happen.

**Comment by greyson-signal** [comment]
> n.b. I currently still have a Linux desktop client version running (for several weeks now) with my current conversations going fine.....

That's to be expected. Desktop instances are separate clients that can act independently of the phone.

**Comment by ultrajae** [comment]
But at least if I downgrade, I can make a backup of my messages within signal, and then I could conceivably remove signal, install the current, and import my backup, NO?

**Comment by greyson-signal** [comment]
@ultrajae You could make a backup, but if you import that backup into a newer version, you're going to run into the same issue :/

**Comment by ultrajae** [comment]
jfc. so the ONLY chance I have is to actually compile my own version..

Well I'm gonna need help with that so I'll lean on you.

sheesh. this is terrible. You should really have a way to import backups from older versions. I can imagine a number of scenarios where this could be necessary

**Comment by johanw666** [comment]
I have no problem build a custom version for you.

@greyson-signal which build number would be the most usefull? And which conversions would need to be removed? I assume something from DatabaseUpgradeTask about the SQLCipher updates?

**Comment by ultrajae** [comment]
@johanw666 That would be MOST welcome. I really don't have the environment or the space to create one in order to do a build.

Please do let me know when you can effect this. I'd greatly appreciate it.

**Comment by greyson-signal** [comment]
@ultrajae 
> sheesh. this is terrible. You should really have a way to import backups from older versions. I can imagine a number of scenarios where this could be necessary

We totally support restoring backups from older versions. The problem is that your database is reporting it's at version 7 even though it has features of version 9. It ruins the migration process, and there's no good way to guard against it.

> WOULDN'T that "revert" the database version to an older version? Thereby "putting me back on track" and able to successfully take the install to the current version? Wouldn't it "fix" what is wrong here?

Nope. Your database says it's version 7, even though it's actually version 9. So when you downgrade nothing will happen. You'll still have a database that says it's 7, but has version 9 features. And then you'll still have the same migration problems when you try to install a newer version.

Again, I know this is frustrating. I still have no idea how something like this could happen. It appears to be a failure of the system, and not a failure of our application. 

@johanw666 That's very kind of you. If you want to make a build for them, you'd want to build 707ca53a23683369e33f929e4b23ff81b942fe5e, but comment out the migrations for versions 8 and 9, namely the block from [here](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java#L189) to [here](https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java#L213).

**Comment by johanw666** [comment]
I built an apk as described here and published it on https://github.com/johanw666/Signal-Android/releases/tag/4.22.4-update_for_DB_9_reporting_to_be_7 .

**Comment by johanw666** [comment]
Yes, that's about it. As long as you keep a secure copy of the backup file you can always re-try when something fails.

**Comment by ultrajae** [comment]
I will work on this in a few hours and report back my results!

Fingers crossed!

**Comment by greyson-signal** [comment]
@ultrajae Just to reiterate, you're going to want to ensure you're copying the entire Signal private directory. Here's a [stack overflow answer](https://stackoverflow.com/questions/13006315/how-to-access-data-data-folder-in-android-device) that provides some guidance. You'll need to get all of `/data/data/org.thoughtcrime.securesms`. Crucially, you'll want to make sure you have `/data/data/org.thoughtcrime.securesms/databases/signal.db`.

Best of luck!

**Comment by ultrajae** [comment]
@greyson-signal 
That stack overflow link deals with methods for a phone that's not rooted. Since I am rooted, I am simply going to use Solid Explorer to make a copy of the entire _/data/data/org.thoughtcrime.securesms_  folder tree to another folder in the phone.

**Comment by uspoma** [comment]
@ultrajae did you check the access rights to the folders? Might be wrong but to me it seems Signal is not allowed to access/write to it...

**Comment by ultrajae** [comment]
@greyson-signal 
Yeah, apparently it copied "as root" with root's umask.. so everything in the copy is ownership "root:sdcard", with files having 660 permissions, folders having 770 perms.

I could chmod everything to the same ownership as the "new app" but I'm not sure on the permissions. Can I leave them as is? 660?

**Comment by greyson-signal** [comment]
@ultrajae I would look at other app data folders on your phone and follow that pattern.

**Comment by ultrajae** [comment]
@greyson-signal @johanw666 
YES!
IT'S WORKING!!

I chowned the folders/files, left the perms.

Now slowly pulling in the last 10 days of messages!

After it's done, I'll continue on the process to try to get back to the Play Store version.

Be back w updates.

**Comment by ultrajae** [comment]
Well, 

I finished the "upgrade" to the current Play Store version as @greyson-signal outlined earlier in the thread with NO issues.
(*Well I did have to re-link my current desktop session to get it to completely communicate properly w/the Android session-- it wasn't relaying my own texts in convos, but other ppls texts were being shown in both spaces. Weird.)

Super thanks and kudos to @johanw666 for the custom build which made this "SAVE" possible and for all you guys for helping me thru the speed bumps to get back up and running WITHOUT any data LOSS at all!

As an aside, I learned a bit more about important stuff like adb, capturing logs and manual backing up Signal!

Thanks again all!

**Comment by greyson-signal** [comment]
@ultrajae Glad everything worked out! Apologies for the hassle, and thanks again to @johanw666 for taking the time to help here.

**Comment by xeals** [comment]
Also followed a similar path, only removing the version 7 update check. Good news is that I can now restore backups and have migrated to the Play Store version successfully. Bad news is that the "old backup remover" removed the newest backups and I lost a month's worth of communication. Partially on me for not copying backups, but also might have been worth attaching a warning that that wasn't fixed in the suggested commit to modify.
