### ISSUE TITLE
Error downloading MMS: RetrieveConf was null

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#7950]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Error downloading MMS message, tap to retry, still does not download.

### Steps to reproduce
- Received mms message over MMSC (while on Wi-Fi)

**Actual result:** Received notification of message and new thread, but no content. "Error downloading MMS message, tap to retry". Retry does nothing. In debug log: `MmsDownloadJob: org.thoughtcrime.securesms.mms.MmsException: RetrieveConf was null`.
Retrying download over LTE did not work

This line might have the issue: https://github.com/signalapp/Signal-Android/blob/381547d6687d07f307113c332d27d0727dc7712d/src/org/thoughtcrime/securesms/jobs/MmsDownloadJob.java#L118

**Expected result:** Message is downloaded automatically, or after tapping to retry

### Screenshots

![mms_error_signal](https://user-images.githubusercontent.com/5124946/42120872-e76b64ba-7bf0-11e8-9326-9c066ca38896.png)

### Device info

**Device:** Samsung Galaxy
**Android version:** 6.0.1
**Signal version:** 4.21.6

### Link to debug log

https://debuglogs.org/739f42a284b0dca41b8b36e9d713fbc388b55701629c3b46efe26d1f46ac078c

**Comment by richards1052** [comment]
I have the same error. Cannot display images sent to me. My phone is Samsung Note 8. Carrier is Sprint.

**Comment by wesinator** [comment]
Just happened again for me, only one message of multiple messages received in an existing MMS thread had the error. Messages were sent while phone was inactive and received when network was reconnected (LTE).

Not even sure if this is a bug in Signal or a network/carrier issue (on T-Mobile).


@richards1052 you thumbs downed this issue

**Comment by richards1052** [comment]
One thing I discovered in going through the documentation is that Signal will not accept files larger than 300 kb.  So it will not download jpgs larger than that.  This imo is a major deficiency. But explains why my mms files aren't downloadable.

**Comment by wesinator** [comment]
@richards1052 this issue has nothing to do with image attachments. I confirmed the error happened for me on an MMS message that did not have any image.

**Comment by richards1052** [comment]
Update to my last message. I now understand that Signal limits OUTGOING MMS files sizes of 300 KB.  Incoming are limited only to the carriers size limits.  So that means you and I are still in the same boat regarding MMS download failures.  Though I believe my problems are restricted to image attachments, unlike your issue.

**Comment by dvogel** [comment]
I am experiencing this issue too. Truth be told, I've been experiencing this every few days for well over a year. I'm only commenting now because the title of the issue matches an exception I've noticed in my debug logas. This has occurred on multiple phones (Nexus 4, Moto g3, Moto g4, and Moto e4). It happens when on wifi as well as when not on wifi. I use T-Mobile for a cellular carrier. On the e4, which supports wifi calling, it does not seem to matter whether that feature is enabled or whether the corresponding Signal compatibility option is enabled.

Here is my latest debug log. I received a few MMS messages from someone, then one failed, then the next one succeeded. I didn't send any messages in that time.

https://debuglogs.org/0b529c8ff6bbd236e9d31bc181153c270f46f23d6b328bc21551c8344f5b0749

**Comment by MaxXor** [comment]
Same issue here on Android 8.1.
