### ISSUE TITLE
app crash every time I try to compose a message

### ISSUE THREAD

**Issue by kern5** [signalapp/Signal-Android#7971]
- [ x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I Signal app crash if I try to compose a message
This problem persist only on a nexus 6p with android 8.1.0
I have a nexus 5 with android 6, signal app works perfectly

### Steps to reproduce
- click on icon to compose a message

**Actual result:** 
Signal app crash

**Expected result:** open an area to compose a message

### Screenshots

android popup that says Signal app stopped working

### Device info
**Device:** nexus 6p
**Android version:**  Oreo 8.1.0
**Signal version:** 4.22.4 and all older versions

### Link to debug log

https://debuglogs.org/be8fc58038c943353f6b86b3e727f4154eb2ca92297516df58415aa2155f8213

**Comment by lokesh-krishna** [comment]
I have the same bug but in addition to this, the app also crashes when opening any existing conversation. This happens when I open a conversation from the list of conversations in the main screen or from a notification. The app crashes if I try to reply from the notification. Should I open a separate issue for this?

### Device Info
**Device:** Xiaomi Redmi Note 4
**Android Version:** Android 8.1.0
**Signal Version:** 4.23.3

### Link to Debug Log
[Signal Crash Report](https://gist.github.com/lokesh-krishna/a16f1343b7802382d73b6eae186d1aff)

**Comment by kern5** [comment]
Fix suggested by lokesh-krisna works: for another reason I wiped cache partition and I had to reset to the factory settings(I did not checked Signal between these two operations)
