### ISSUE TITLE
Can't restore encrypted backup

### ISSUE THREAD

**Issue by rljes** [signalapp/Signal-Android#7975]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When restoring from a backup it loads 69501 messages quickly, then slows down and crashes around 70501.

### Steps to reproduce
- make a signal backup on Motorola Droid Turbo, Signal version 4.23.3, and transfer file to Samsung Galaxy s9, Signal version 4.23.3.
- Try to restore the backup

**Actual result:** 
Signal loads around 70000 messages and then crashes
**Expected result:** 
Backup is successfully restored

### Screenshots
Video: https://drive.google.com/file/d/1b-Lv8tLx7aPpzj3kcckfDg4B24vYo9lS/view?usp=drivesdk

### Device info
**Device:** Samsung Galaxy S9
**Android version:** 8.0.0
**Signal version:** 4.23.3 (issue has existed since 4.20 I believe)

### Link to debug log
N/A can't access advanced settings

**Comment by firestorm99** [comment]
My comment in the other thread fits better in here(logcat included for older version) and still applies for 4.22.4: https://github.com/signalapp/Signal-Android/issues/7901#issuecomment-401161094

**Comment by greyson-signal** [comment]
@rljes I know you can't get to the settings, but is it possible for you to provide logcat output? Crashes are super hard to diagnose without any sort of log.

**Comment by rljes** [comment]
```
07-09 19:41:02.436 12884 12969 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
07-09 19:41:02.436 12884 12969 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12884
07-09 19:41:02.436 12884 12969 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:353)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
07-09 19:41:02.436 12884 12969 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.lang.System.arraycopy(System.java:521)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:307)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:245)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-09 19:41:02.436 12884 12969 E AndroidRuntime:        ... 4 more
07-09 19:41:02.469  1439  2029 D Debug   : !@DumpState : SHIP
07-09 19:41:02.469  1439  2029 D Debug   : !@DumpState : debug level:0x4f4c
07-09 19:41:02.469  1439  2029 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
07-09 19:41:02.469  1439  2029 W ActivityManager: crash : org.thoughtcrime.securesms,0
07-09 19:41:02.487  1439  2029 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RegistrationActivity
```

**Comment by greyson-signal** [comment]
So we're somehow reading in bad length values from the stream. It's unclear if there's some sort of file corruption, or if there's a corner case where we write bad values or mess up the read sequence.

I'll note that in this case we read a length of 0, causing the crash to occur a little later, but there's other issues (like #7987) where we read some large negative number as the length, implying that we're reading a bad block.

**Comment by johanw666** [comment]
Integer overflow?

**Comment by firestorm99** [comment]
As the backup did not work I created a new backup (disabling backup, deleting backup file, receiving at least 1 one message then reactivated backup) with a new passphrase and tried to restore it again with the same behaviour (did not check logcat then). So I think the backup file was OK. 

Maybe the bug is in the backup creation routine and not the import routine?

**Comment by shymu** [comment]
Having what seems to be this exact same issues restoring a backup from a Samsung Galaxy Alpha to a Samsung Galaxy S9 running Signal 4.23.4. Signal crashes upon restoring backups after reading approx 65k messages.

Here's what I _think_ is the relevant section of logcat. Happy to do any other digging as necessary.

`--------- beginning of crash
07-17 11:05:17.175 12069 14808 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #10
07-17 11:05:17.175 12069 14808 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12069
07-17 11:05:17.175 12069 14808 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: Caused by: java.lang.NegativeArraySizeException: -796152760
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:303)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:245)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-17 11:05:17.175 12069 14808 E AndroidRuntime: 	... 4 more
07-17 11:07:02.653 15216 15322 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
07-17 11:07:02.653 15216 15322 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 15216
07-17 11:07:02.653 15216 15322 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: Caused by: java.lang.NegativeArraySizeException: -796152760
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:303)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:245)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-17 11:07:02.653 15216 15322 E AndroidRuntime: 	... 4 more
07-17 11:11:52.001 17890 18761 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #6
07-17 11:11:52.001 17890 18761 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 17890
07-17 11:11:52.001 17890 18761 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: Caused by: java.lang.NegativeArraySizeException: -796152760
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:303)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:245)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-17 11:11:52.001 17890 18761 E AndroidRuntime: 	... 4 more`

**Comment by rljes** [comment]
With version 4.24.5 on both devices, created a new backup and restored it successfully. The restore again slowed down toward the end but this time did not crash.

The debug log (https://debuglogs.org/cdf801d4608f3e130002e291393a2d1a4e0fa1f1f4cfb2df144a33c61a2aa8e6) includes the fatal exceptions from previous efforts to restore, if that is of any help.

**Comment by firestorm99** [comment]
I retried the procedure with the latest versions: 
Tried to restore a backup created in Signal 4.24.8 on an other phone with Signal 4.24.8. After entering the code it starts restoring(counter goes up), but at some point it just closes.

Backup size: 195.07MB
Backup created on: Xiaomi Mi 5C, Android 7.1.2, Stable 9.5.2
Tried to restore on: Samsung SM-A300FU, Lineage OS Build @ Android 8.1.0
Logcat:

```
08-15 22:23:53.653 10619 12131 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
08-15 22:23:53.653 10619 12131 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10619
08-15 22:23:53.653 10619 12131 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: Caused by: java.lang.NegativeArraySizeException: -461571146
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:303)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:245)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-15 22:23:53.653 10619 12131 E AndroidRuntime: 	... 4 more
08-15 22:23:53.658   658  7601 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RegistrationActivity
```

**Comment by greyson-signal** [comment]
Hey, so I just ran into this myself personally when switching phones with my large (4.3 GB) backup. In my case, I had a file copy error. Re-copying the file to my new device fixed the problem. Which makes sense. These types of errors very much look like the underlying data is malformed.

Given that everyone in this ticket was moving a file in between phones, I'm going to assume you all experienced some form of the same problem. Let me know if you can reproduce it in such a way that proves otherwise.

Thanks!
