### ISSUE TITLE
Messages in Conversation Marked as "encrypted for non-existing session"

### ISSUE THREAD

**Issue by GuardianMajor** [signalapp/Signal-Android#7982]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I carried a conversation with someone using the desktop app and while all those messages are visible and went through just fine, on the mobile app side, it is showing all of them as `Message encrypted for non-existing session` which makes no sense as we are both on Signal (unlike previous issues that I found, has nothing to do with SMS) and nothing has changed on either of our ends. During the conversation, they would appear both on desktop and mobile just fine but this morning, I went to send her a message, and saw that all of the conversation from last night is marked this way while still showing my messages in between (see screenshot for clarity) and yet they appear on the desktop side just fine (now I know that's probably because it is cached on the db there) but what I don't get is WHY.

### Steps to reproduce
Unfortunately nothing I can lay down as steps other than what I did which you can't replicate, so it is moot.
- have conversation on signal desktop (windows)
- messages show up and get delivered just fine (both android and windows)
- try to send message this morning
- all messages from last night are marked non-existing
- they still exist on desktop (Windows)
- they still exist on android (my messages)
- they exist on the other person's phone (iOS)
- they exist on the other person's desktop (Mac)

**Actual result:** the messages are marked as `encrypted for non-existing session`
**Expected result:** like always all messages are visible and readable and available as they should be

### Screenshots

![android](https://user-images.githubusercontent.com/5274181/42665138-1974deee-85f3-11e8-8862-2b8a8f8200e2.jpg)
![windows](https://user-images.githubusercontent.com/5274181/42665144-1db1380e-85f3-11e8-9c00-b1e8756ef1eb.png)

### Device info

**Device:** Google Nexus 6 (Motorola shamu)
**Android version:** 7.1.1 (N8I11f)
**Signal version:** 4.23.4 (beta)

### Link to debug log

None as it didn't happen until many hours later.

**Comment by johanw666** [comment]
I would start with resetting the secure session.

**Comment by GuardianMajor** [comment]
@johanw666 I appreciate that but it is not fix as the messages there BEFORE this series of messages is fine and still showing, the ones sent AFTER (as in yesterday and today) show up just fine. Her side ALL the messages show up fine, on both iPhone and Mac desktop and mine shows up just fine on the Windows desktop but this slice of messages is showing like this in the middle of before/after which are showing up just fine, makes zero sense.

Here is her phone showing the exact same messages just fine on her phone both sides of the conversation showing fine:
![image](https://user-images.githubusercontent.com/5274181/42715739-1c5e270e-86ad-11e8-8d8b-8f523f1cd678.png)

This seems to indicate that somehow it messed up the encryption and my only thought is that it has to do with the iOS/Mac and Windows/Android crossover somehow, don't know which side or what for, but it has never happened with other users who are on Windows/Android, so my guess is that somehow how the "apple" side of the app is handling or android side is "de-"handling it is messed up.

**Comment by yaomtc** [comment]
I had this happen just now, a couple messages came in with that error. Resetting the session worked. Is there an error log I could share that would help?

**Comment by GuardianMajor** [comment]
@yaomtc When you did that, what happened to all the existing past messages? What happens to them? Logic would dictate doing that will nullify and make all previous messages void and unreadable, is this correct?

**Comment by yaomtc** [comment]
Nothing else changed. All past messages remain on the device, and the two problem messages are still "encrypted for non-existing session".

**Comment by GuardianMajor** [comment]
Got it, thank you.

**Comment by Kylotan** [comment]
I just saw something very similar, but slightly different. Noting here in case it helps:

1. I loaded up the Signal desktop app on Windows, and it updated to v1.14.4.
2. I sent a message to an existing contact.
3. The message didn't arrive 'properly' on the recipient's iOS Signal app (not sure of exactly what she saw)
4. The message arrived fine on recipient's desktop app (Windows).
5. Instead of appearing in our existing conversation on my Android Signal app, the message appeared as if it had come from my phone number, and said "Message encrypted for non-existing session".

**Comment by Kylotan** [comment]
I got this again 3 times today. I'm looking through the debug log to try and work out what has gone wrong but the logs are _very_ chatty and don't make it easy.

I did manage to see that there was a ProtocolNoSessionException raised for that phone number, with a `:2` suffix (not sure what that means), possibly inside 'PushDecryptJob'.

A bit further down I also saw SignalServiceMessageSender raise an IOException saying "Non-successful response: 409" during the SendReceiptJob.

And below that, there's a MismatchedDevicesException, perhaps raised from PushServiceSocket.java:796. Perhaps this is because the most recent messages came from the desktop app, whereas that same sender communicated with me via their phone a few hours earlier.

**Comment by josebrwn** [comment]
Clicking the button to "reset the secure connection" does nothing except populate all your conversations on every device with "encrypted for non-existing session". 

I accidentally pressed it because Signal was in a disconnected state even though my wifi was working. All it did was populate all ensuing messages in the conversation with "encrypted for non-existing session". 

I can't see the point of this feature. Maybe the button should be relabeled "do not press this button".

**Comment by tyleroconnell** [comment]
I just started experiencing this yesterday with one specific contact.

**Device info**
**Device:** Pixel 2 XL
**Android version:** 9 
**Signal version:** 4.36.2

**Comment by gmargari** [comment]
Same here, happened just now.

If this is related, I had an old I conversation with a person. She send me a message on mobile a few days ago. Desktop was closed, so I didn't receive this message on Desktop.
Today I send her a message from Desktop (without seeing her recent messages), and on my mobile app the messages I just sent:
 - are shown as "Note to self"
 - are shown as: encrypted for non-existing session"

Device: Huawei Y560
Android: 5.1.1
Signal: v4.35.1
Singal Desktop: v1.23.2

**Comment by zamboni33** [comment]
A similar situation just happened for me. I had not logged into my desktop app for quite a while. On opening the desktop app in Ubuntu Linux messages began syncing down. At this point several contacts of mine reported many messages were hitting their devices saying "encrypted for non-existing session" and "No available session for contact".

Device: Nexus 5.
Android: 6.0.1.
Signal: v4.40.4.
Signal Desktop: 1.24.1.

**Comment by depassp** [comment]
This seems related to [Signal-Desktop issue 2806](https://github.com/signalapp/Signal-Desktop/issues/2806)

**Comment by greyson-signal** [comment]
Yeah, closing this is a desktop issue.
