### ISSUE TITLE
SMS Notifications should use End to End Encryption

### ISSUE THREAD

**Issue by cluelessperson** [signalapp/Signal-Android#7999]
User's personal content, that's supposed to be encrypted, is allowed raw to pushbullet's servers.

Case and point: My MMS picture is on their server via HTTPS.  No End-To-End encryption required.

**Comment by scienmind** [comment]
@cluelessperson : Please don't delete the issue template.

Feature requests, questions, discussions and **anything else that doesn't fit the issue submission template should be directed to the forum**.

---

Regarding your complaint:

SMS and MMS are not encrypted at all by design, even if used via Signal. If you want encryption - use Signal data-channel messages (and don't install spyware your your device).

Now, Signal's end-to-end encryption is what it is - encrypting message on one device, send it encrypted, and then decrypt it on the recipient's device.

If you install some other app with permissions to access things on your device, like notifications, it will do so, as that's the apps whole intention. Signal (just as any other app) can't do anything about it. And if you're concerned with things ending up on push-bullet servers - don't use it in the first place.

For further discussion you can open a thread on the [forum](https://community.signalusers.org/).

**Comment by FeuRenard** [comment]
As @moxie0 said in #4709:

> if you install spyware onto your device, you get spyware on your device
