### ISSUE TITLE
Export to stock SMS database.

### ISSUE THREAD

**Issue by shadowofdarkness** [signalapp/Signal-Android#8]
I think people should be able to export SMS back to the stock database in-case they decide to remove this app and don't want to lose all their SMS history.

I don't want to start using the app just so I don't have to worry about being locked in, in the future if something better comes along.

**Comment by greyson-signal** [comment]
@RealOrangeOne We support encrypted backup, so we have removed the plaintext backup option.

**Comment by RealOrangeOne** [comment]
I see. But that doesn't allow export into the stock SMS database, as it's a proprietary format. Looks like https://github.com/xeals/signal-back/ solves the problem anyway!

**Comment by GuardianMajor** [comment]
I believe that you should provide both encrypted and also the traditional plain text. Encrypted locks you into Signal, but the plaintext version allows for portability and say populating another message app, and so long as the persons knows what that means (meaning the insecure nature of it) then that should be their call.

Plus this would not be difficult to implement as it already exists and just needs to be put back in the codebase. The current encrypted backup is very poorly done as it keeps creating huge backups instead of using incremental backups into a single file, it does it whenever it feels like it and without any rhyme or reason and that can interfere with your usability. There should really be some kind of a scheduling ability built into it.

**Comment by greyson-signal** [comment]
Github is for bug reports. Please move any other discussion to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
