### ISSUE TITLE
Delivery reports dis- and re-appear with 4.24.2

### ISSUE THREAD

**Issue by uspoma** [signalapp/Signal-Android#8020]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
With version 4.24.2 delivery reports are missing for some messages right after they were sent. Also, after scrolling the screen a few times delivery reports that have been displayed are gone. Leaving and re-opening signal brings them back though.

### Steps to reproduce
- Send some messages
a) Some delivery reports are missing

- Send some messages
- Scroll in the conversation window
b) Delivery reports that have been visible before are gone now

**Actual result:** a) delivery reports are not displayed for some messages; b) delivery reports go missing after scrolling
**Expected result:** Delivery reports should work like they used to

### Screenshots
I have a screen cast if this is necessary...

### Device info
**Android version:** 7.1.2
**Signal version:** 4.24.2

### Link to debug log
If needed tell me.

**Comment by Rolf558** [comment]
Same for me on a Samsung Galaxy Note 3 running Android 5.0.

The checkmark is only displayed once at the last message for a group of consecutive messages.

It looks like a buggy function has been implemented to group all consecutive message into a common graphical bubble. But at least with Android 5.0 separate bubbles are drawn.

**Comment by greyson-signal** [comment]
So we're trying to limit the number of message footers we show to save vertical space and make the overall message list a little cleaner. The behavior here is a little tricky, so let me outline what's _supposed_ to happen, and you can tell me if this is actually happening. Note that we're just looking at outgoing messages in this scenario.

- In general, we want to "collapse" footers of messages that would say the same timestamp (e.g. "NOW", "5 MIN", "12:02 PM", etc). In this case, only the most recently-sent message would have that footer.
- We _always_ show footers for messages that are currently sending.
- We _always_ show footers for messages that failed to send.

Because we may collapse footers after messages are sent or when their timestamp updates, you may notice footers "disappearing" as you scroll around.

Now, if this is not what's happening, please let me know. However,  if you simply don't like this new behavior, please make a forum post or chime in on [the post we made to collect feedback](https://community.signalusers.org/t/feedback-on-the-new-visual-changes-in-android-4-24-ios-2-28-and-desktop-1-15/3532/43).

Thank you!

**Comment by uspoma** [comment]
@greyson-signal 

Thank you for this detailed explanation. What you describe is exactly the behavior I experienced. So this seems to be the default design now.

Indeed, I am not sure yet if I like it but this is a discussion for a different channel. 

Thanks for your good work by the way!
