### ISSUE TITLE
Image message status indicator does not show correct status

### ISSUE THREAD

**Issue by lazlolazlolazlo** [signalapp/Signal-Android#8028]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Image send to group chat is read by everyone in the group but message status indicator displays delivered.

### Steps to reproduce
- send image to group chat
- wait until image is read by receivers
- image message status does not change to read, stays at delivered

**Actual result:** Message status delivered
**Expected result:** Message status read

### Screenshots

![signal-2018-07-23-090504](https://user-images.githubusercontent.com/601905/43062326-bcfa7b2e-8e58-11e8-8d5d-1eb3081682f1.jpg)
![signal-2018-07-23-090548](https://user-images.githubusercontent.com/601905/43062331-bf46a0f6-8e58-11e8-86bf-2769ccb4ea10.jpg)

### Device info

**Device:** Motorola E
**Android version:** 7.0.0
**Signal version:** 4.24.2

**Comment by jdepypere** [comment]
That _is_ the status read indicator. The delivered indicator is [outlined](https://github.com/signalapp/Signal-Android/blob/master/res/drawable-xxxhdpi/ic_delivery_status_delivered.png), the read indicator is [filled](https://github.com/signalapp/Signal-Android/blob/master/res/drawable-xxxhdpi/ic_delivery_status_read.png). The confusion is because in your messages the read-indicator is grey, whilst in the image it is in a dark overlay and thus the icon is shown in white.
