### ISSUE TITLE
[Assistance] MMS messages compressed

### ISSUE THREAD

**Issue by Woodzrul** [signalapp/Signal-Android#8029]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Firstly I apologise and understand that this issue has been raised in the past, but thought I'd ask the question to see if I can do anything myself to resolve. You can merge with issue #672.

Sending of MMS images are compressed and therefore the resolution is rather low.

### Steps to reproduce
1. Create new conversation
2. Send MMS

**Actual result:** MMS (picture) is sent successfully but compressed to a really low resolution, therefore making the image not very pleasant to view.
**Expected result:** MMS (picture) should be sent so it can been seen clearly.

### Device info
**Device:** OnePlus 2
**Android version:** 7.1.2
**Signal version:** 4.24.2

### Other information
I see that the following files have been amended in the past to assist those who also raised this issue.
src/org/thoughtcrime/securesms/util/BitmapUtil.java
src/org/thoughtcrime/securesms/mms/PushMediaConstraints.java

Also read that this issue is potentially due to the amount of RAM on the device. Not sure if I've misunderstood that.

### Question
Is there anything I can do (in terms of amending the above code in those files) so that when I send a picture message the resolution is higher? My carrier supports MMS up to 2mb (tested with another Messaging app).

**Comment by greyson-signal** [comment]
First of all, I want to note that our [bug reporting guidelines](https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports) state that Github is only for reporting bugs -- please direct all other queries to [the forum](https://community.signalusers.org/).

However, since this is a simple question, I'll answer it here: you can edit the two lines here to change the max dimensions and file size of MMS image attachments:

https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/mms/MmsMediaConstraints.java#L11

Thanks!

**Comment by Woodzrul** [comment]
@greyson-signal I apologise now for logging this query in the wrong place. The above suggestion did not work so I will therefore sign up to the forum.
