### ISSUE TITLE
Selected messages in a conversation not vertically centered

### ISSUE THREAD

**Issue by art1fa** [signalapp/Signal-Android#8035]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
- When selecting one or multiple messages in a conversation, the message bubbles are not vertically centered in its list rows, since the padding is only applied to the bottom of the message bubble
- This leads (sometimes) to accidentally selecting the wrong message, especially when long-tapping on the top of a message
- Plus, since the background of a selected message turns blue, it doesn't feel visually right with the current paddings: the message bubble somehow "hangs" in its list row

### Steps to reproduce
- Select messages in a conversation
 
**Actual result:** Padding only on bottom of message bubble
**Expected result:** Padding on both top and bottom of message bubble, resulting in the message being better centered in its list row.

### Screenshots

![conv_item_paddings resized](https://user-images.githubusercontent.com/11131859/43201432-c74b622a-9018-11e8-8dc1-3ebf46b36b70.jpg)

### Device info

**Device:** Samsung Galaxy S8 / Google Pixel 2
**Android version:** 8.0.0
**Signal version:** 4.24.3

### Link to debug log
- not required

**Comment by greyson-signal** [comment]
Yeah, this one is tricky. So there's spacing in-between the messages, and that spacing isn't always even anymore. That's why you're seeing different amounts above and below. The annoying part is that while I could make the highlight only go around the message, the side effect will be that selecting _multiple_ messages will then have white spaces in between. So I kinda had to choose between making single-selects look good and having multi-selects look good.

I suppose there are alternatives where I try to make split the margins across the top and the bottom, but that's going to be quite tricky and bug prone, and I already hate having to do the margin manipulation that's already there.

Does that make sense?

**Comment by art1fa** [comment]
Yeah makes sense! I think the solution to split the paddings is totally sufficient. I'm testing #8036 for more than a week on my production device, I didn't notice any bugs for all message types. Basically it just uses the same methods as for applying the message bubble corner radiuses.
