### ISSUE TITLE
Backup loaction changed

### ISSUE THREAD

**Issue by MarcSN311** [signalapp/Signal-Android#8069]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When encrypted backups were (re-)introduced the backups were saved in `[Internal SD]/Signal/Backups`. This was bad behaviour because large daily writes can kill flash memory quite easily (and obviously internal memorycant be replaced) and also because internal memory is can not be extended and should IMO be reserved to System+apps.
In Signal 4.20.9 the Backup Location changed to `[External SD]/Android/data/org.thoughtcrime.securesms/files/Signal/Backups` . 
In Signal 4.23.4 the backup location switched back to  `[Internal SD]/Signal/Backups`.

### Steps to reproduce
- Enable backups

**Actual result:** Backups are created in `[Internal SD]/Signal/Backups`
**Expected result:** Backups should be created in `[External SD]/Android/data/org.thoughtcrime.securesms/files/Signal/Backups`

### Device info
**Device:** Sony E5823 (suzuran)
**Android version:** 7.1.2 (a28b9b6c88, lineage_suzuran-userdebug 7.1.2 NJH47F a28b9b6c88)
**Signal version:** 4.23.4

**Comment by MarcSN311** [comment]
this seems to be intended behaviour: https://github.com/signalapp/Signal-Android/commit/18756aedf6c5bec1e8abd3789710cc5d59d7e090

But the critique remains: 
- Filling up peoples internal memory is nasty
- Killing peoples internal memory by writing huge amounts of data every day is even nastier

**Comment by PiCob** [comment]
Yep, unfortunately this is actually intended.
For reference (and some background as well as solution proposals:

https://community.signalusers.org/t/v4-23-warning-backups-on-phones-with-sd-card-wont-work-anymore/3437

https://community.signalusers.org/t/support-external-sd-card-storage-for-local-message-store/3216/14

https://community.signalusers.org/t/v4-23-warning-backups-on-phones-with-sd-card-wont-work-anymore/3437/4

**Comment by 2-4601** [comment]
Also this comment sheds light on why the decision was made: https://github.com/signalapp/Signal-Android/issues/7845#issuecomment-401479547

**Comment by norpol** [comment]
@2-4601  How are you supposed to make a backup right now, especially if your internal phone memory is full because of Signal and your only possible way to get it's data out is via. a backup?

My parents are having non-rooted Android phones and I don't know how I'm supposed to help them, their phones are unusable right now.

I would have tried to make a backup, copy it somewhere, set conversation max length to 1 and then clear old conversation => then remove the clearing of old conversations again.

**Comment by PiCob** [comment]
I absolutely see your point (since I'm facing the same problem) and in my opinion the simplest way to solve this is to let the user choose a destination where to store the backups (if this is technically possible in terms of permissions). However, the way it is implemented now is the intended behavior. So let's move the discussion to the forums, you'll find links to this topic above. You can use your GitHub account for the login there.

**Comment by norpol** [comment]
@PiCob Thank you for your response, I've just commented in this [thread](https://community.signalusers.org/t/support-external-sd-card-storage-for-local-message-store/3216/20). I'd love to make code contributions to Signal, but I'm not sure if and how that would be appreciated.

**Comment by LeeBinder** [comment]
Simply let users choose. Add an option in Settings where to save. Really simple as that.......

**Comment by norpol** [comment]
Fully agree, there were so many options introduced in the Signal preferences since 2018. So not offering this one looks like a bad excuse.
