### ISSUE TITLE
Date and message status missing from messages

### ISSUE THREAD

**Issue by andrejsky** [signalapp/Signal-Android#8071]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If there are more outgoing messages sent without being interrupted by incoming message or incoming messages interrupted by outgoing, only the last message shows date and delivery status. This is confusing behaviour especially as individual messages can be sent on different times. Also messages can fail or have different delivery status which is now not apparent in this view.
If you insist on this behaviour, at least provide option to revert to the original.
Note that the desktop version kept the original functionality. 

### Steps to reproduce
- install the latest release
- open message view

**Actual result:** 
Only last message provides info about time and delivery status regardless on whether they were sent on different times

**Expected result:** 
Each message provides info about time and delivery status

### Device info

**Device:** Nokia 3
**Android version:** 8.0.0
**Signal version:** 4.24.7

**Comment by PiCob** [comment]
"This is confusing behaviour especially as individual messages can be sent on different times. Also messages can fail or have different delivery status which is now not apparent in this view.":
In those cases, messages won't collapse, see:
https://github.com/signalapp/Signal-Android/issues/8020#issuecomment-407094504

Apart from that, this collapsing behavior is actually intended.

**Comment by andrejsky** [comment]
While the collapsing may be intended and preferred by some, it is still buggy:
- it groups messages sent several minutes apart and relying on text representation rather than exact difference of timestamps
- in different states (eg: previous message read, last message only received by the device | not received by the device) 

It would be possibly OK for messages sent in the same minute to be grouped, but grouping messages sent minutes apart is not OK.
Preferably also provide option to turn this off. Thank you.

**Comment by PiCob** [comment]
Ah, okay - it's about relying on text representation. Well, I don't think there's a way to collapse other than using the actual representation - which ever that might be (apart from "Now" it's always a minute-based representation, so I don't get what's the problem here). In all other cases (different timestamp), collapsing should'nt happen (AFAIK). If it does: would you be so kind and provide a screenshot, so that the devs have the chance to analyze?

As to the different states: I don't know if collapsing is supposed to happen in this case, maybe someone else is able to tell?

However, if it's **not** a bug, I'm quite sure we won't get an option to control the collapsing behavior (since one of moxie's rules is "the answer is never more options").

**Comment by andrejsky** [comment]
The following example illustrates part of the problem. 
In the first picture, messages were sent each minute at around 30s mark. Picture is taken soon after the messages are sent, everything seems OK, however at some point soon after sending the last message, the previous one had its info hidden for a while as well.
![signal_test1](https://user-images.githubusercontent.com/24830424/43678283-fc662fd0-9810-11e8-9843-c94d55866609.jpg)


Now some time after this, everything looks different and it is impossible to tell the time when each message was sent, neither to differentiate between last unread and undelivered message and previously read messages.

![signal_test2](https://user-images.githubusercontent.com/24830424/43678285-040a6ecc-9811-11e8-8fb7-22450fbf4e45.jpg)

In other conversations looking days back into history, some messages seem to be grouped correctly even when just minutes apart, but sometimes minutes to hours go between messages and theyre still grouped.

If the intention was to bring simplicity, this confusing and inconsistent behaviour introduces more problems than it solves.

If someone doesn't care about timestamps, by all means, allow them to use the functionality, however in my experience date and time can be critical to understanding the context of the conversation.

**Comment by minnmann** [comment]
Actually, the screenshots suggest that there is some buggy behaviour. Given what @greyson-signal explained in #8020, the footer should only collapse, if the displayed timestamp are the same.
Since the timestamp should not be "SAT 15:05" for all messages - maybe some had something like "2H" and these should be collapsed - but not every single message.

So this seems to me to be unintended behaviour (at least if I understood correctly).
Maybe you want to capture a debug log to allow for some investigation of the developers?

That said, I like the collapsing for same-timestamp messages - in any case it would only display e.g. "2H", so it would just be redundant info. If I really need the accurate time, I will just go to the message info (long press + info button).
But in general (e.g. if you like relative timestamps at all), this is a discussion that should happen at the [community forum](https://community.signalusers.org/)

**Comment by greyson-signal** [comment]
This does look like a bug, thank you. I used the wrong date formatter to compare whether the footers would render the same text. So things group correctly for recent messages, but not older messages. I'll address this.
