### ISSUE TITLE
Can't call or recieve call, always gets a misscall

### ISSUE THREAD

**Issue by b2cbd** [signalapp/Signal-Android#8079]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was trying to make a call from my Signal(android) to my friend(IOS). He tried back also. We only get misscall notifications. No ringing in another side! No VPN, standard wifi connection. Text messages work fine. All permission allowed from my app permission.

### Steps to reproduce
- Open Signal
- Make a Call
- Ringing - Showing Dialing
- My friend gets a miss call notification 
- Send a text message to friend and ask him to call back
- He calls back, I also get miscall notifications.

### Device info

**Device:** Manufacturer Huwei Mate 8
**Android version:** 7.0
**Signal version:** 4.23.4

### Link to debug log
My Debug Log: https://debuglogs.org/c253e4dcb8d369c6f5263edeffc2b84152a2eb89f153c9d77546574aa14917ae

My Friend's Log(Person I was trying to call, He also tried): https://debuglogs.org/75ef098773a837ff565e50c19de416b0bb687ef3772ef1dd1c60c1ecddc60160.zip

**Comment by mattimac** [comment]
@b2cbd please try potential solution mentioned here https://github.com/signalapp/Signal-Android/issues/7733#issuecomment-406591981

**Comment by michaelkirk-signal** [comment]
Sorry you're having trouble @b2cbd. Could you have your iOS friend update to the latest release (2.28.1) and see if the issue resolves? 

If not, could you have them submit another debug log?

**Comment by b2cbd** [comment]
@mattimac  It's an IOS device. Tried from both WiFi and Mobile Data. Android device works under the same network.

**Comment by michaelkirk-signal** [comment]
@b2cbd - thanks for the followup log. 

In the first log, there was an error with the iOS client, which I believe was fixed with the 2.28.1 release.

In the new log, from the iOS 2.28.1 client, the story is different - I read from that log that there were two calls initiated from iOS, but that the Android device never responded.

Do you have the android logs corresponding with this second iOS log? I think we'll need to dig in from there.

If you don't, could you please repeat the experiment and submit a fresh debug log from both sides afterwards?

Thanks for helping us get to the bottom of this.

debug notes for posterity:

call 1 here:
```
2018/08/10 10:32:48:027  [CallKitCallUIAdaptee] startOutgoingCall(handle:)
```

call 2 here:
```
2018/08/10 14:13:39:144  [CallKitCallUIAdaptee] startOutgoingCall(handle:)
```

The caller stayed on the line for about 40s the first time, and over a minute the second time, which should be more than sufficient.

From the iOS log, I see the caller's client sent the CallOffer and a flurry of ICE updates. Everything looks normal from the caller end.

In fact, the caller even received delivery receipts from the recipients primary device, indicating that recipient device downloaded the messages. But for some reason, the recipient device did not respond. 

There is no indication of having received any call messages from the recipient device during the attempt to connect the call, nor after.

**Comment by b2cbd** [comment]
@michaelkirk-signal  Okay tried once again.

Steps
----------------
i. I(Android) sent him(IOS) a message, received
ii. He called me, DIALING... nothing received here.
iii. He sent a text, received here
iv. I called him, DIALING...  He received a missed call alert.

My Log(Android) : https://debuglogs.org/59ba7cc3035ff6a49ca39d91e51aca31babfa36477e9dd11155643b60fc91507

His Log(IOS) : https://debuglogs.org/19e38e11a8611e15fadf2117a86988a122228046a24d9290c4a1c0e3c1ff7b66.zip

**Comment by frh** [comment]
Any new information about this issue? I haven't been able to make or receive Android -> iOS calls for three weeks now. Seems to be the same issue as https://community.signalusers.org/t/calls-now-not-working-dialling-only-never-rings/3687

**Comment by gpeddev** [comment]
It seems similar to my problem
https://github.com/signalapp/Signal-Android/issues/8072

**Comment by gpeddev** [comment]
3 weeks without signal and other people i talked yesterday have the same/similar problem with it.

**Comment by frh** [comment]
https://github.com/signalapp/Signal-Android/issues/8131#issuecomment-415155397 indicated that this might be solved by a version update on the iOS app. I just tried calling from Android to someone on 2.29.0.17 on iOS, and the same thing happened.

**Comment by greyson-signal** [comment]
@gpeddev Logs are super helpful here. If possible, could you help the other people you talked to submit debug logs (or post them here on their behalf)?

**Comment by gpeddev** [comment]
@greyson-signal Hi! I posted both debug logs (mine and the other) to the issue i opened

`Link to debug log

This is the debug log that receive the call
https://debuglogs.org/e12f1cf21218eb59eeeaf657712feb9da3a57786e7888f372e11cd62882ac40b
This is the debug log of the caller
https://debuglogs.org/4ce610732adaa8c68ca8c7e30b393df0329237a6f9345b7d6de5b5f8132f65cc`

**Comment by MatejKovacic** [comment]
I have a similar problem with one contact only. I am on iPhone, my contact has Android (non-rooted) and we cannot call each other. However, messages are going through just fine.

Any estimate when this bug is going to be resolved? Because a few weeks (months?) ago it worked just fine. But it seems one of the upgrades brought this error.

P. S. My contact tried to reinstall the app, but it is still the same.

**Comment by Xashyar** [comment]
@michaelkirk-signal @greyson-signal 
Same issue Here.
Tested two devices on the same WiFi Network (Consecutive Dialing on Both Devices):

**iPad:**
https://debuglogs.org/f7534c9ee9e1363237f41b6a3a6b598b4db21c9cad9a0ff75b8f40544ce0dfee.zip

**Huawei (Android 5.0.1):**
https://debuglogs.org/89586dbb727e7e5a557c7c8f3a5e9382f07a9a4ca8ed713d39b5faa7fe784e9c

**Comment by michaelkirk-signal** [comment]
@Xashyar - would you be willing to run a diagnostic build on your iPad? If so, could you email me at michael@signal.org?

**Comment by Xashyar** [comment]
@michaelkirk-signal
Thanks for the Hardwork!
Can we track the corresponding commits?

**Comment by gpeddev** [comment]
@michaelkirk-signal Thats not the case with me. Both phones run android.

The problem still isnt solved.

**Comment by greyson-signal** [comment]
This ticket is about the Android-iOS calling issue, which has been resolved.
