### ISSUE TITLE
Signal crashes when inserting an emoji at the end of a 2000 characters message

### ISSUE THREAD

**Issue by samouy** [signalapp/Signal-Android#8087]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal is crashing when a 2000 character's limit message is reached. Adding an emoji at the end of the message crash the application.

### Steps to reproduce

- Go to https://randomwordgenerator.com/ and generate 500 words to reach the 2000 characters limit
- Copy/Paste the generated words with "Brut text pasting"
- When Signal is displaying the limit "1/2000" or "0/2000", add an emoji to crash the app

**Actual result:** App crash when adding emoji at the end of a 2000+ character message.
**Expected result:** A toast notification that warn the user that limit is reached.

### Device info

**Device:** OnePlus3 - A3003
**Android version:** 8.1.0
**Signal version:** 4.24.8

### Link to debug log
https://debuglogs.org/085e28c4a0d254156db3ec877a0f3dcaddbe62e4524a5e39e07134d3e0661b50 

Thanks !

**Comment by mario123456789o** [comment]
Hi,
I had a look into this. For me its reproducible. The problem is that this code segment is not checking the maximum message size: 
[EmojiEditText](https://github.com/signalapp/Signal-Android/blob/28dc477b54dac1e86d52214db459bf3f99b761b3/src/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java)
```
  public void insertEmoji(String emoji) {
    final int          start = getSelectionStart();
    final int          end   = getSelectionEnd();

    getText().replace(Math.min(start, end), Math.max(start, end), emoji);
    setSelection(start + emoji.length());
}
```
I tried fixing this, but I had no success so far because I didn't see a way how to get the maximum message size in that class. If a developer could give me a hint I would implement that and make a PR.

Mario

**Comment by Sgn-32** [comment]
The limit was increased to a size of 65536. ccfcfa7

There will probably continue to be a crash when this new limit is reached. Didn't test it, but 65536 characters will probably never be used.
