### ISSUE TITLE
Signal voice calls not working !!!

### ISSUE THREAD

**Issue by juliancardoso** [signalapp/Signal-Android#8131]
After installing Signal on Android 4.4.2 and other on iOS 11.4.1 (15G77).

We realized **everything is working besides the voice calls** and there are a lot of complaints from others.

The most strange stuff is without ringing if someone try to call the reply is "busy".

I was expecting more from Signal recommended by Edward Snowden

**Comment by ranomier** [comment]
I'm pretty sure Snowden wouldn't recommend using it with Android 4.*

:wink:

**Comment by minnmann** [comment]
I think it would be very helpful, if you could post debug logs from both devices (Settings > Advanced > Submit debug log) right after you tried to call the other device. 
Otherwise, I assume it is very hard for the developers to analyze and solve the problem.

The [support page](https://support.signal.org/hc/en-us/articles/360008216551-Installing-Signal) at least states that Android 4.0 is still supported.

**Comment by jeremymasters** [comment]
You're supposed to fill out the template, not delete it.  This issue tracker emails tons of people, so if you stick to the template it's easier to suss out what's going on and get the logs...which you did not attach.  If you have complaints to make or questions, those are better suited for the [community](https://community.signalusers.org/).

**Comment by jlund-signal** [comment]
We won't be able to do any kind of troubleshooting without a debug log and more information.

The next iOS release does address a few connection edge cases with voice and video calls that were affecting a small number of users. That release will be available soon, but your friend can also [join the iOS beta](https://support.signal.org/hc/en-us/articles/360007318471-How-do-I-join-Signal-s-beta-) if they would be willing to help with testing.
