### ISSUE TITLE
Not counting whitespaces at the end or beginning of the message for the remaining characters

### ISSUE THREAD

**Issue by supermar1010** [signalapp/Signal-Android#8189]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The maximum message message doesn't count whitespaces at the beginning or end of a message. So there it shows one character left, but you can't type another one, because the whitespace is ignored, and so actually there are already 2000 characters.

### Steps to reproduce
- Open any chat
- Add a message containing 1999 character
- Add a whitespace at the end, notice how the available characters display doesn't change
- Try typing a normal character, doesn't work

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- Signal doesn't count the whitespace at the end of the message
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- Signal shouldn't ignore the whitespace at the end of the message

### Screenshots
Hard to show

### Device info

**Device:** Oneplus 3T
**Android version:** 8.0
**Signal version:** 4.25.10

**Comment by mario123456789o** [comment]
I took a look in the code and I think I found the problem:
[ConversationActivity](https://github.com/signalapp/Signal-Android/blob/5d91a94252f861f25b854a86b03444ba64366617/src/org/thoughtcrime/securesms/ConversationActivity.java)
```
private void calculateCharactersRemaining() {
    String          messageBody     = composeText.getTextTrimmed();
    TransportOption transportOption = sendButton.getSelectedTransport();
    CharacterState  characterState  = transportOption.calculateCharacters(messageBody);

    if (characterState.charactersRemaining <= 15 || characterState.messagesSpent > 1) {
      charactersLeft.setText(String.format(dynamicLanguage.getCurrentLocale(),
                                           "%d/%d (%d)",
                                           characterState.charactersRemaining,
                                           characterState.maxMessageSize,
                                           characterState.messagesSpent));
      charactersLeft.setVisibility(View.VISIBLE);
    } else {
      charactersLeft.setVisibility(View.GONE);
    }
  }
```
This method calls the calculation of the characters remaining, it removes the whitespaces before and after the text, which leads to the wrong result. 
I think we should stop calling the trim method and just count it as it is, because there is no reason to exclude the whitespaces, even if they're removed while transport, if the user can't type longer messages. 
Maybe we should disallow messages starting with a whitespace or a return? And stop using trim to remove the one at the end

Mario

**Comment by johanw666** [comment]
Isn't whitespace stripped from the end of a message when it is sent? I remember some bug in Silence where this behaviour sometimes interfered with sms messages to shortcodes.

**Comment by mario123456789o** [comment]
Yeah the whitespace is stripped from the end and the beginning when the message is sent.
The reason why I made this PR is that Signal shows 1999/2000 (1), but if you try to type another one it won't let you. Because it didn't count the whitespace in calculating the remaining chars. But the edittext counted the whitespace so it won't let you type anymore. 
So I think that it is less confusing if we count whitespace so the number of remaining chars is the real amount of chars you can type as a user.
Am 08.09.18, 19:17, johanw666 <notifications@github.com> schrieb:
Isn't whitespace stripped from the end of a message when it is sent? I remember some bug in Silence where this behaviour sometimes interfered with sms messages to shortcodes.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/signalapp/Signal-Android","title":"signalapp/Signal-Android","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/signalapp/Signal-Android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@johanw666 in #8189: Isn't whitespace stripped from the end of a message when it is sent? I remember some bug in Silence where this behaviour sometimes interfered with sms messages to shortcodes."}],"action":{"name":"View Issue","url":"https://github.com/signalapp/Signal-Android/issues/8189#issuecomment-419658865"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/signalapp/Signal-Android/issues/8189#issuecomment-419658865",
"url": "https://github.com/signalapp/Signal-Android/issues/8189#issuecomment-419658865",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [signalapp/Signal-Android] Not counting whitespaces at the end or beginning of the message for the remaining characters (#8189)",
"sections": [
{
"text": "",
"activityTitle": "**johanw666**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@johanw666",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"signalapp/Signal-Android\",\n\"issueId\": 8189,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"signalapp/Signal-Android\",\n\"issueId\": 8189\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/signalapp/Signal-Android/issues/8189#issuecomment-419658865"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 377444613\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Sgn-32** [comment]
The limit was increased to a size of 65536. https://github.com/signalapp/Signal-Android/commit/ccfcfa71df28c4da2bef0277eb255c739024aed0

How likely is it that someone will reach this limit and be annoyed by an uncounted whitespace?

**Comment by supermar1010** [comment]
Not really :D the only reason I found that bug, because I was fixing something with a crash when adding an emoji, so I was like, let's fix this too, but can be closed from my side if you think it's too much review work.
