### ISSUE TITLE
Long Term Financing

### ISSUE THREAD

**Issue by phime42** [signalapp/Signal-Android#819]
With increasing popularity of the TextSecure-app, questions about financing the server costs arise. While developing is funded via BitHub, I would be interested in getting to know the long term financing concept.

Thank you very much!

**Comment by manuelfink** [comment]
@moxie0 wanna recap here. I join @jedie. For me its really intransparent how Signal and Whispersystems is being financed. Especially the powered by twilio on the app startup screen makes me a little bit suspect, since they provide commercial communication solutions and advertising integration services for phone-call tracking. Servers must be paid, not only developers. I like the ideas above. Also a sponsor is nothing bad, but I appreciate more transparency.
