### ISSUE TITLE
Signal has stopped working. Error when restoring from encrypted backup.

### ISSUE THREAD

**Issue by reactionstudio** [signalapp/Signal-Android#8222]
I created a backup on my Nexus 5 and copied the backup files to my Moto G5S which had a fresh install of signal on it (hadn't been run yet).

I launch Signal for the first time, it finds the backup and prompts me to enter the passphrase. Once entered Signal crashes and i get the error "Signal has stopped working". Opening Signal again just repeats the process.

**Comment by greyson-signal** [comment]
Can you send a debug log? It's almost impossible to debug a crash like this without one. If you're running 4.26.x (currently rolled out to all of beta a 50% of production), you can tap the little circular badge on the main registration screen 8 times to submit a crash report. Otherwise, if you're familiar with ADB, then you could post logcat output. If you're not, you can wait another day or so for 4.26.x to be rolled out 100%.

Thanks!

**Comment by reactionstudio** [comment]
So i got it working in the end. I couldn't copy the .backup file via USB off my old phone as it wouldn't show up in the file manager. Android also wouldn't bluetooth a .backup file either, so i used an android file manager to zip it up which did show up via usb and copied it to the new phone that way then extracted the file.

I left the .zip file on the new phone i believe (cant remember exactly and don't know if signals .backup files are unpacked into zip files) but i ended up removing both of those files from my new phone, making a new backup on my old phone, renaming the extension to .jpg so it would bluetooth across then renamed it back to .backup on my new phone before running signal again and that time it worked fine with no errors.

I did look through the debug log when i was looking for the problem and didn't see any errors towards the end of the log unfortunately.

**Comment by greyson-signal** [comment]
Hmm, well I'm glad you got it working! Feel free to open a ticket with a debug log if it ever happens again. Thanks!

**Comment by leafcutterant** [comment]
Um... so what was it that made it work?
