### ISSUE TITLE
Debug log uploader introduced in 4.25.x makes it difficult to remove irrelevant lines

### ISSUE THREAD

**Issue by pshephard** [signalapp/Signal-Android#8280]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In previous versions of Signal (< 4.25.0), when uploading a debug log via the app it was possible to remove several lines of irrelevant lines at a time by selecting and then deleting them. With the current version, introduced in 4.25, it is now only possible for a user to select a single line at a time, which makes it near impossible to redact large portions of irrelevant debug log.

A privacy-conscious user might want to do this to prevent their being fingerprinting, as the debug logs are public and contain several items that could potentially identify them, including:
* Millisecond-precision log entries (which network-observers could use to de-anonymize by correlation)
* MAC codes (which could be compared to real packets)

Once a user was identified, further information (especially metadata, using the final 2 digits of interacting phone numbers) could potentially be used. An adversary that had network-level traces and some sophistication could create an automated system to monitor debug logs/reports for information matching a set of users that were of interest, and then harvest this data when it became available.

### Steps to reproduce
- Select the triple-dot menu in the top right corner.
- Go to Settings
- Go to Advanced
- Click "Submit debug log"
- Select a word by pressing for a long time, then try to expand the selection to cover multiple lines.

**Actual result:**  You can't :(
**Expected result:**  You could select and delete irrelevant lines. Modifying the times to either have noise added or be less than millisecond precision could also help preserve anonymity. Perhaps having a "share lots of info" vs. a "share minimal info" could be another method.

### Device info

**Device:** Motorola XT1528
**Android version:** 5.1
**Signal version:** 4.29.2

### Link to debug log
That's what this issue is about :)

**Comment by greyson-signal** [comment]
This is a bit tricky. Previously, the log was rendered in one giant TextView. However, when our log size increased, some phones would just crash upon viewing the log because their system couldn't support setting that much text in a TextView. 

To fix it, each line is rendered in it's own view, which fixed the size limit problem and made scrolling much faster overall. It also means you can do multi-line select.

I imagine one way to lessen the problem would be something like batching _n_ lines together in a view, instead of one-line-per-view. That could let you select more at once. The "real" solution would unfortunately be something like importing/creating some custom TextView optimized for rendering large bodies of text, or making some other similarly-large change.

**Comment by pshephard** [comment]
Would giving the user an option to select the time period to include help in reducing the EditText buffers?

That would at least work for issues like #8090, where the problem can be reproduced at will and so the window of interest can safely be narrowed down to the past minute or two.

Making the timestamps relative (like `dmesg` does by default on Linux) might also help improve privacy (unless absolute ones are needed to debug server-side issues).

**Comment by greyson-signal** [comment]
There's no way to retrieve the amount of text that the system can handle displaying in an EditText. It'll just crash or it won't. So giving more options to the user doesn't really help if they just select "all", unfortunately.

**Comment by pshephard** [comment]
How much buffer is typically required to debug stuff?

If a smaller default (like 10 min) could work, the buffer could substantially be reduced. My phone shows about 2 days worth right now.

**Comment by greyson-signal** [comment]
When it comes to logs, more is almost always better. The original problem was that we only ever had 5-10min of logs, and there's many classes of problems that people don't notice within 10 minutes of the incident. Things like delayed messages, attachments failing to download, missed calls, you name it. That's why I had to write an encrypted PersistentLogger. I won't be reducing the size of the debug log anytime soon :)

**Comment by greyson-signal** [comment]
(Also worth noting that logs are limited by size, not time. 2 days for you might be 2 hours of heavy usage by me).
