### ISSUE TITLE
MMS not showing all images in conversation thred

### ISSUE THREAD

**Issue by brianpgrissom** [signalapp/Signal-Android#8297]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Beta on a Pixel 2 XL.
3 images sent across 2 separate messages sent via MMS to me.
All three images are available (via swiping in image view, image to image)...but only the first and last images show in the feed - so there's no indication of the 2nd image.

### Steps to reproduce
- have SENDER send 2 images in one attempt from their chosen MMS app, followed by a single image in a separate MMS

**Actual result:**RECEIVER will receive all three images, but only 2 images will be shown in the Signal conversation.
**Expected result:** RECEIVER should see all three images in conversation

### Device info
**Device:** Pixel 2 XL
**Android version:** 9
**Signal version:** 4.29.4

### Link to debug log
https://debuglogs.org/2e587a4589f7172aca5b59068df39edae2223de0bbd6798ccc7d8066e5943dc4

**Comment by greyson-signal** [comment]
Can you please include a debug log? Can't do much without one :)

**Comment by greyson-signal** [comment]
Oh man, ok, I misunderstood your initial bug report and now realize what's happening. 

Someone sent you two images in a single message, yes? Unfortunately, Signal doesn't yet support showing multiple attachments for a single message. We'll save them, which is why they're visible in the media gallery and stuff, but they don't show in the actual conversation. Apologies. Multiple attachments is something we're still thinking about. Thanks!
