### ISSUE TITLE
Unmonitored apps for Samsung devices

### ISSUE THREAD

**Issue by gelbertgel** [signalapp/Signal-Android#8309]
I have samsung device and signal has not unmonitored apps for samsung devices. So that when app is background or killed , push notification is not coming from devices. Please correct this error

**Comment by siptrunk** [comment]
This error is tricky because it requires constant process / battery use.  Lots of apps snitch on other apps for using services, features or hardware in the background.   My phone however does have a lapse of notifying me sometimes of things that have taken place.   I think it may be when i kill all the apps but I'll look more into it.

**Comment by greyson-signal** [comment]
There's no API for us to automatically add ourselves to some 'unmonitored' whitelist that doesn't require some new permission that we shouldn't have -- like administrative access. I think that's just something you have to whitelist yourself in the settings.

Also, regarding the app being killed, there's multiple interpretations there. If you 'swipe away' an app in the app switcher, you should be fine. Push notifications shouldn't be delayed. However, if you go in to the app info page for Signal and "force stop" it, then that means you're telling the system to stop our app completely, and notifications will be delayed. There's not much we can do here.

Also, in general, please fill out the template. It's difficult to answer these questions without knowing the specific device model, Android version, Signal version, etc.

I'm closing this because I don't think there's actions we can take -- if the system is delaying the push notifications themselves, we can't do anything. However, if there's some misunderstanding here, then please re-open the ticket with a filled-out template.

**Comment by gelbertgel** [comment]
I want to reopen this issue and updated my issue

**Comment by gelbertgel** [comment]
How can whatsapp do it?

**Comment by gelbertgel** [comment]
Yes please look this and reopen my issue. Thank you
