### ISSUE TITLE
[4.30.1] Incorrect link for Sealed Sender "Learn more"

### ISSUE THREAD

**Issue by minnmann** [signalapp/Signal-Android#8324]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The link to "Learn more" in sealed sender settings points to https://signal.org/blog/secret-sender - probably instead of https://signal.org/blog/sealed-sender/.

### Steps to reproduce
- Open settings -> privacy
- Tap "Learn more" in "Sealed Sender"

**Actual result:** 404 error in browser
**Expected result:** Show blog post https://signal.org/blog/sealed-sender/ - or whatever is intended.

### Device info
**Device:** Motorola Moto G5
**Android version:** 8.1.0
**Signal version:** 4.30.1

### Link to debug log
(shouldn't be necessary)

**Comment by greyson-signal** [comment]
:man_facepalming:

**Comment by five-c-d** [comment]
Minor non-user-visible leftover variable name within signal4android == https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/database/helpers/SQLCipherOpenHelper.java#L288 

signal4android strings.xml uses 'sealed sender' correctly (but signal4ios uses 'secret sender') 

At least one icon in signal4desktop has metadata using 'secret sender' , https://github.com/signalapp/Signal-Desktop/search?q=%22secret+sender%22&type=Code , but otherwise no big problems (does not seem to link to blogpost url like the other clients).
