### ISSUE TITLE
Automatic cancellation of an incoming call when the time is different

### ISSUE THREAD

**Issue by dmirgaleev** [signalapp/Signal-Android#8330]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When the time on the device making the call is more than 3 minutes behind the receiver, call automatic makes missed.

### Steps to reproduce
- Set time to device#1: 07:00
- Set time to device#2: 07:05
- Make call from device#1 to device#2.
- Check conversation activity.

**Actual result:** You can see missed call
**Expected result:** Call intent

### Device info

**Device:** Any android device. I checked on Xiaomi and ASUS
**Android version:** Any
**Signal version:** 4.29.7

### Link to debug log
Caller:
https://debuglogs.org/1544210817a7100374f6805650c2da35b64b54b1ebfe705ab939040165765ce3
Receiver:
https://debuglogs.org/bf0f53a5bb53352a6523a6311b9c5d7fe2b9c9d18fa2e8a77e1b1db0bed93034

**Comment by ozgurakyazi** [comment]
I was searching for missed call issue and this came up. I have this issue constantly for months, which is so disturbing. In my case, caller and receiver has only 1 minute( and 3 hours, because of different countries) difference. Nevertheless, "Missed Call" problem happens even when I am waiting on the conversation page with the caller(I am the receiver in this case, i.e). To make a call, they call me 3 or more times, then somehow my phone starts ringing. 
I would be so happy if this is fixed.
