### ISSUE TITLE
Website APK requires logging in and updating Google Play Services

### ISSUE THREAD

**Issue by leedoyle** [signalapp/Signal-Android#8336]
Samsung galaxy note 3, original ROM, Google Play Services installed but not used. 
Trying to install Signal off of the website, after installing the apk and entering the number it demands that I update Google Play Services, where I don't even have an account (and don't want to).

**Comment by johanw666** [comment]
The only difference between the website and the Play version of the apk is the update mechanism. Both versions will detect if Google Play Services are installed and try to use them if they are. Unfortunately both will not fallback to websockets is the Play Services are too old.

**Comment by johanw666** [comment]
Well, it allows to use it without a Google Play account on your phone. You can update Google Play Services without a Play account , from a site like apkmirror.com (although you need to study which taste to install first, there are quite a lot of them but they offer a manual).

**Comment by greyson-signal** [comment]
We only fallback to the websocket if Google Play Services isn't present at all. The target for this was people running Google-free ROMs. If Google Play Services is present, then we're going to try to use it. I consider going beyond this behavior to be a feature request (since it goes outside of the intended scope of the original support), so we should move this to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!
