### ISSUE TITLE
WhatsApp-like Image Cropping

### ISSUE THREAD

**Issue by bisherbas** [signalapp/Signal-Android#8337]
Would be nice to have ability to instantly crop images within the Signal app.

**Comment by five-c-d** [comment]
There are some existing forum-thread on this feature-request, including by Greyson who is a signal4android developer at OpenWhisper.  https://community.signalusers.org/t/new-photo-capture-flow/4155/6 , and also https://community.signalusers.org/t/ability-to-edit-images-before-sharing-crop-rotate-flip-rebalance-draw-on/2446

It is probably okay to leave this issue open for tracking-purposes, since OWS has expressed the desire to someday implement this, but please comment *in the forum* if you have design-suggestions.  Github is mostly (99.99% nowadays) used for tracking bugs, not for feature-request design discussion, which will get this issue closed-and-locked.   :-)  

You can login to the forum-threads using your github username&credentials, if you like

**Comment by bisherbas** [comment]
@five-c-d Thanks a lot! Will do.

**Comment by greyson-signal** [comment]
Yep, gonna close this, for the reasons @five-c-d mentioned :)
