### ISSUE TITLE
Group messages arrive one at a time

### ISSUE THREAD

**Issue by CalumMcCall** [signalapp/Signal-Android#8506]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a group conversation with 2 other participants. Occasionally, when I open Signal, I then start receiving a flood of past messages from both other participants. However, rather than simply updating the conversation with the new messages, they arrive one at a time, with roughly 1/2 second delay between them. This continues until all messages are processed, during this time if I open the conversation and start reading, the messages jump upwards as they are added at the bottom. This makes it impossible to read the messages until they are all processed. This has only started happening after I created this group a couple months ago. In the past, I've never seen this behaviour with groups, although I haven't used groups in a long time before this one.

### Steps to reproduce
I can't reproduce it reliably, but it happens about 50% of the time.

### Device info

**Device:** Oneplus 3T
**Android version:** 8.0.0
**Signal version:** 4.31.6

### Link to debug log
https://debuglogs.org/d6656fa60f4129d4cd44aef7544d9979b7c02e32e181143a05c89893ee930eb9

**Comment by greyson-signal** [comment]
Sounds like you're having issue receiving notifications, possibly because of battery optimizations enabled on your device. We have a [support article](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications) that talks more about how to disable them for signal.

But because you're not receiving those notifications, we don't know you have messages until you open the app, at which point we have to pull all of the messages down and process them in order. We already have an open issue about ongoing notification problems.

Thanks!
