### ISSUE TITLE
Registration on microG requires enabling Google Cloud Messaging

### ISSUE THREAD

**Issue by kenogo** [signalapp/Signal-Android#8513]
# Quick bug overview / Steps to reproduce

- Use microG and disable google cloud messaging
- install Signal and attempt registration
- Signal crashes during the registration process

# Detailed description and possible solution

MicroG is an unofficial and minimal alternative to Google Play Services. Its purpose is to increase privacy while still providing all of the features you would want on your phone (like GPS, push up notifications, …)

Now, Signal is able to run without Google services. During the registration, it performs a check on whether Google Play services are installed. If they aren't, it runs code that doesn't depend on them. If they are, it runs code that depends on Google cloud messaging. Now, microG has cloud messaging disabled by default, because it requires registering your device to Google with a unique identifier, which many microG users might not want. However, Signal recognizes microG as Google Play services, so it crashes when cloud messaging is disabled during registration.

I think it would be good to add an extra check whether cloud messaging is installed, and if it isn't, either prompt the user to activate it or give the option to continue without Google play services. I'd be willing to work on this if this is something with the potential to be merged. Otherwise, I'll just use a dirty hack instead.

**Comment by kenogo** [comment]
@haffenloher Wouldn't it be possible to at least catch the exception that makes Signal crash and handle it in the way described above? And sorry about not using the template, I didn't see it in the phone app I'm using.

**Comment by greyson-signal** [comment]
There's too many permutations of people's rooted devices to actively support them all, especially when you're spoofing key Android components like Google Play Services. We support non-GooglePlayServices devices, but I don't anticipate us supporting "partial-GooglePlayServices" devices.

I suggest following @haffenloher advice and disabling everything during registration, and then turning your microG stuff back on. Thanks!

**Comment by lo9-u** [comment]
@greyson-signal 
I have the same problem as this user on reddit.
https://www.reddit.com/r/signal/comments/gq5u9l/signal_just_wont_work_without_google_play_services/

1. I have downloaded and installed the current signal 4.69.6 from the website.
https://signal.org/android/apk/
2. my Android smartphone is not rooted, but all Google Play services are blocked via Adguard Android
https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.4-release
3. I open Signal for the first time and want to enter my phone number for registration, but I don't get an SMS because the Google Play services are required.


Question:
Can you add a manual function where users can manually switch to Websocket. Then the problem is solved everywhere. Is that possible?
