### ISSUE TITLE
Notifications settings crash accessing Priority if there exist conversations with custom notifications

### ISSUE THREAD

**Issue by wesinator** [signalapp/Signal-Android#8546]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Seems that the presence of muted conversations and/or convos with custom notifications settings breaks the app notification settings, causing Settings to crash when notifications priority are accessed.
See also #8477

### Steps to reproduce
 - Muted conversations, conversations with custom notifications
 - Settings - Notifications - Priority

**Actual result:** "Settings has stopped"
**Expected result:** Access notification app settings.

### Device info

**Device:** Nokia TA-1044
**Android version:** 8.1.0
**Signal version:** 4.32.7

### Link to debug log

https://debuglogs.org/9b9f3e490e892065a32c8c9ccc33b63a4ab5b7264d0dff38c2364df7e30c5f59

**Comment by greyson-signal** [comment]
Can't reproduce this and don't have any logs with relevant details. Feel free to re-open if you can still reproduce this and provide a fresh log. Thanks!

**Comment by wesinator** [comment]
> Can't reproduce this and don't have any logs with relevant details. Feel free to re-open if you can still reproduce this and provide a fresh log. Thanks!

multiple issues noted in https://github.com/signalapp/Signal-Android/issues/8546#issuecomment-456551077

**Comment by greyson-signal** [comment]
Yep, saw all of those. They've all either been fixed or aren't unexpected (i.e. errors that we log that aren't fatal). None of them are related to this notification crash.

**Comment by five-c-d** [comment]
> multiple issues noted

@wesinator I was the one who noted those issues  :-)   but Greyson is specifically asking 

1.  can you reproduce the appcrash problem still, in July 2019 ?  he is unable to do so, running signal4android 4.44.x presumably.  I tried myself, running old-stable signal4android 4.42.3 and was also unable to cause the crash:  I muted one chat for an hour, changed to a custom dingtone on another change, and then flipped the priority-setting from high to default ot max to high, and was unable to cause appcrash.  

2.  if you CAN still reproduce, can you detail the exact steps you needed, to cause the appcrash, and submit a new debuglog, with a more-recent version of signalapp?  The debuglog above is from 4.32 and is pretty "old" in some ways, lots of fixes since then. 

Upload a new debuglog please, and somebody will take a look at it.  The issue can be re-opened, if it is still happening, but if this *specific* issue is not happening, we can close this 8546 as presumably-working-unless-somebody-knows-different, right?
