### ISSUE TITLE
Unable to build when NDK r18b is installed

### ISSUE THREAD

**Issue by bluemarvin** [signalapp/Signal-Android#8564]
### Bug description
Unable to build when android NDK r18b is installed. Google remove mips support from recent NDK releases. Unfortunately older version of gradle still look for the mips tool chain, even if it isn't used to build the project.

### Steps to reproduce
- Install NDK r18b

**Actual result:** Gradle configure fails with the message:
`No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android`
**Expected result:** Gradle should be able to configure the project when opened in AndroidSutdio.

**Comment by bluemarvin** [comment]
NDK r17b also failed during build process. Was able to successfully build with NDK r15c.

**Comment by greyson-signal** [comment]
You can see our section on [reproducible builds](https://github.com/signalapp/Signal-Android/wiki/Reproducible-Builds) if you're having build issues. The most important thing is that Signal-Android builds with that docker image. If it does, but you're still having build issues in your local environment, then the problem is with your local environment and shouldn't result in creating a ticket. You can always go to [the forum](https://community.signalusers.org/) with build issues in the future. Thanks!
