### ISSUE TITLE
"Signal Message" button is dead in textview after I took a picture with build in camera

### ISSUE THREAD

**Issue by halb9** [signalapp/Signal-Android#8575]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"Signal Message" button is dead when trying to send a message

### Steps to reproduce
- Use landscape mode
- open any conversation (1:1 or 1:n does not matter)
- take picture with build in camera function
- add text to picture so message compose view is in fullscreen

**Actual result:** "Signal Message" button is dead and does not send my message. If I go back one step, button works. 
**Expected result:** Button works all the time

### Device info

**Device:** OnePlus 6
**Android version:** 9
**Signal version:** 4.32.8

### Link to debug log

https://debuglogs.org/5cfe8f82cc7d4ca73c1ea92a2f49027e6bff17c4d51fa3943760363ef8e74774

**Comment by jakubgregorek** [comment]
I managed to simulate the same behavior on Motorola G6 Play running Android 8. The issue seems to be here: https://github.com/signalapp/Signal-Android/blob/5cc3ac00c7fc1d87d57537042de7323bf2fca264/src/org/thoughtcrime/securesms/scribbles/ScribbleHud.java#L406-L417 If _TextSecurePreferences.isEnterSendsEnabled(getContext())_ returns false then the send message button does not work. If _Settings -> Chats and media -> Chats -> Enter key sends_ is enabled then the button seems to be working.
