### ISSUE TITLE
No notifications on lockscreen after recent signal updates.

### ISSUE THREAD

**Issue by Shir01** [signalapp/Signal-Android#8597]
### Bug description
Hello.
After recent updates of Signal app(I don't remember the exact version when this started happening) Signal doesn't show any notifications on the lock screen, also notifications on the Signal icon are showing inconsistently(It seems that it depends on whether Signal is locked or not).  I don't know if this information is of any use to you, but I am using several other messengers(Viber, Threema) and an SMS replacement app called Textra, all of them display notifications on the lock screen without any issues. System setting are the same for Signal and other messengers.

### Steps to reproduce
Use latest version of Signal from GP on MIUI 9.6.4 device.

**Actual result:** After receiving messages from my contacts there is no notifications on the lock screen. 
**Expected result:** A proper notification is displayed on the lock screen when Signal receives new message.

### Device info
Xiaomi Redmi Note 5(MIUI 9.6.4 Global Stable)
Android 8.1
Signal 4.32.8

### Link to debug log
https://debuglogs.org/88f884ba7f113cbda9d4914fe69a37563aee99d961a169b92b25273f5b2828d9

**Comment by jkelol111** [comment]
Can confirm this happens on Nokia 2 (Android 7.1.2, Signal 4.32.8). Might be due to the lack of RAM or the aggressive killing of background apps though.

**Comment by Shir01** [comment]
> Might be due to the lack of RAM or the aggressive killing of background apps though.
Prior to reporting this issue I've already tried running Signal as the only app on my phone(other applications were killed) and tweaking memory management without any success. It seems that something was changed in the way Signal interacts with notification system.

**Comment by greyson-signal** [comment]
Just dug through my commits back to November, and 4.32.8 wouldn't have any changes in how we interact with notifications. I also just enabled the Signal screen lock and confirmed notifications work when the screen lock is active and the phone itself is locked (i.e. screen off).

1. If Signal is in the foreground, and you're looking at the conversation list, do you see notifications when new messages come in? i.e. do you get a system notification that goes into your notification tray?
2. If the Signal lock screen is disabled, do you get notifications when the app is backgrounded?
3. Have you gone through our [support page on notifications](https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications)? There's Xiaomi-specific instructions there. Xiaomi can be pretty aggressive with its battery optimizations.
4. Check your notification channel settings in the system settings. On most Android versions, you go to Signal's system 'App info' page, then notifications. Make sure they're all enabled, and then tap into each channel to make sure the settings allow notifications to be posted, make noise, etc.

**Comment by Shir01** [comment]
1. I guess the way I described this problem was a little bit misleading, it's not like I am not getting notifications at all, a small icon appears in the status bar and a proper notification appears in the notification drawer when a new message is received. This happens regardless of Signal running in the background or in the foreground. The problem is that notifications are not displayed on the lock screen. I've already tried everything: did a clean install of Signal, checked it's permissions, checked memory settings, disabled power management for Signal, checked notification setting in Signal and nothing seemed to help. This information might be important for you, when I first encountered this issue no system settings were changed and no system updates were installed(actually I blocked OTA more than half a year ago), everything was fine, no system updates were applied, no system settings were changed and then one day Signal started to behave this way.  Btw today a proper notification appeared on the lock screen but this happened only once without any kind of interference from my side(no settings were changed). 
3. Yes, I've already looked though your support page.
4. I have already checked it several times and even turned them off and on just in case.

P.S. I greatly appreciate you taking the time to look into this matter if you need any additional information just let me know.

**Comment by greyson-signal** [comment]
Huh, that's really strange. Honestly we haven't changed any details of our notification settings themselves in quite a long time, and I haven't heard any other reports of this. That all leads me to believe it's something with your specific device configuration. Maybe you could get more suggestions from other Xiaomi users if you posted in [the forum](https://community.signalusers.org/)?

**Comment by jellevictoor** [comment]
I found this thread while googling why signal does not work nice with my pocophone. I installed all the latest updates, but it seems signal is working next to the whole MIUI OS.
Notification are handled differently, also the sound settings are not synced with the sound profiles on the phone.

**Comment by Shir01** [comment]
> Huh, that's really strange. Honestly we haven't changed any details of our notification settings themselves in quite a long time, and I haven't heard any other reports of this. That all leads me to believe it's something with your specific device configuration. Maybe you could get more suggestions from other Xiaomi users if you posted in [the forum](https://community.signalusers.org/)?

At first I thought that there was indeed something wrong with my device configuration, but that doesn't explain why lock screen notifications are properly displayed by every other application(Viber, Whatsapp, Textra, Threema) except Signal. As well as that doesn't explain why the system(MIUI) started behaving this way, because I definitely haven't touched any of its setting for months.

**Comment by Esokrates** [comment]
@Shir01  Maybe you are describing the problem I having in #8604
It could be that you see the Signal icon in the status bar because of the "Fetching message" notification, but you are not notified since no message is yet downloaded?

**Comment by Meteor0id** [comment]
I am on a Moto G7 Plus:
On one of my group chats, when someone placed a message, my phone would vibrate and my screen turned on, but the signal icon did not show.
On the status bar there was no notification.
When I was in the app and messages were being posted the counter did not show to indicate the number of unread messages.
The text on that conversation did not get bold to indicate unread messages.
The phone only vibrated for every new message.

We tried to reproduce this by making new groups, but we couldn't. After a while we discovered the bug was also gone on the initial group. I have a log, but I have no idea how to reproduce it.

Is this the same issue?
(Will post log later)

**Comment by NicoleRauch** [comment]
I'm also not seeing notifications on lockscreen on an iPhone (with iOS 12.2). This problem persists for me since a very long time. Some weeks ago, I changed some settings on my iPhone (allowing all notification types and keeping banners permanently) and subsequently got a few notifications, but now not any more (although I did not change the settings back). I only use Signal for very low-volume communication (say, one or two messages per week on average) so it is really hard for me to figure out. I think it depends on a combination of those factors:

* whether Signal is open on my phone
* whether Signal Desktop is open on my Mac
* whether Signal Desktop is in the foreground or background
* maybe whether the user I'm receiving messages from is the one whose chat is currently being displayed (even if the app - mobile or desktop - is in the background)

Maybe that gives you more ideas on what to look into, as it is not possible for me to systematically sort this out given my low message frequency. Thanks!

**Comment by nikdale** [comment]
Hello,

Six persons reported to me that they do not receive notifications. One of them never receives any, and 5 of them don't receive only on locked screen.
Those 5 people if they don't use Signal Android app for a period of time (Let's say 5 hours), they don't receive notifications even if the screen is unlocked. 
Phones people use: Sony Experia E5, Samsung Galaxy A50, Huawei P10 Lite, Huawei Y6 (2018), etc. 

Thank you!
Please fix this ASAP, it's hard for me to make people

**Comment by merkste** [comment]
I had the same problem(s) yesterday on a friends Remi Not 7. Apparently there is a dedicated option in the app info menu to allow notifications on the lock screen. Oddly, sometimes it is reset if I change other settings, such as ring tones. And indeed, ring tones are not consistent and their settings hidden in different places. Btw, Signal is also subject to their battery saving - something that might cause troubles as well.

**Comment by sirius-c** [comment]
@greyson-signal  Is this issue still being worked on?

On Android 9 and different phones, myself and several friends often miss calls because Signal is not reliably ringing. It gets to the point that some will eventually drop usage of Signal, which would be a shame.

A short investigation showed that it is not simply the phone being locked, and/or Signal being open or closed. There seems to be some time factor, how long Signal and/or the phone has not been used.

For a phone/video call application, reliable ringing should be a top priority.

**Comment by blu-IT** [comment]
Some clients reported that issue to me on serveral iPhones. No signal notifications in gerneral. 
Seems to occur when a notification/message was was recieved via WhatsApp on the the device
