### ISSUE TITLE
Screen Lock Not Working on Android 4

### ISSUE THREAD

**Issue by hgl2000** [signalapp/Signal-Android#8603]
- [x] I have searched open and closed issues for duplicates
- [ x I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After Signal's inactivity timeout, Signal does not invoke Android's screen lock.
Also when locking Signal in the message center pull down, it remains unlocked.
This is the same issue reported at https://github.com/signalapp/Signal-Android/issues/7962 for Android 4.3, and it also occurs on my Samsung GT-I9105P running Android 4.1.2

### Steps to reproduce
- Set Android screen lock to PIN + to automatically lock immediately after sleep (2 min)
- Set Signal to screen lock + inactivity timeout to 1 minute
- Open Signal after more than 1 minute
- Or open Signal after locking it in the message center

**Actual result:** Signal opens without invoking the PIN lock screen
**Expected result:** PIN lock screen prevents direct access to Signal

### Device info

**Device:** Sony D6503
**Android version:** 4.4.2
**Signal version:** 4.33.5

### Link to debug log

https://debuglogs.org/a21104cfefffd3f8a73b79ad157334e0fac3f2c71051b217d6057427d44e403d

**Comment by johanw666** [comment]
It also does not work on 4.4.4, I saw this on a Sony Z1 Compact and an Acer Z205. It never works, no need to wait for a timeout. After a reinstall, a fresh app start or a manual lock through the notification it also does not work.

At first I thought it was an issue of my own fork but I tested it with the official apk too. My first guess is that https://github.com/signalapp/Signal-Android/commit/45e0bb281faeb1fcd73b741a81aad08d5805baa0#diff-8bb82a4ca18f65394e2c25bf1a9f53aa introduced some code in KeyCachingService that does not work in 4.4 but I have no time to test it now.

**Comment by johanw666** [comment]
The problem lies in PassphrasePromptActivity.java line 275: there, the Android unlock mechanism is called only when SDK >= 21 (Android 5), so it will never work on Android 4.

This is strange because the function it calls, keyguardManager.createConfirmDeviceCredentialIntent(), is added in API 21 according to https://developer.android.com/reference/android/app/KeyguardManager.html#createConfirmDeviceCredentialIntent%28java.lang.CharSequence,%20java.lang.CharSequence%29 (it is somewhat hidden in the documentation, search for "21" on that page).

It seems not possible without root according to https://stackoverflow.com/questions/35072876/how-to-confirm-device-credential-before-android-5-0-api-21 .

All the more reason to merge https://github.com/signalapp/Signal-Android/pull/8175 because the passphrase lock does work on 4.4.
