### ISSUE TITLE
4.33.5 chewing through lots of battery 

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#8605]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
4.33.5 is chewing through battery like mad. Seems to be consistent through restarts. 

### Steps to reproduce
- use 4.33.5
- watch your battery get eaten alive 

**Actual result:** battery is using 10x what it did in 4.33.2
**Expected result:** battery use remains the same as older versions 

### Screenshots
N/A

### Device info
**Device:** Samsung S9
**Android version:** 9.0
**Signal version:** 4.33.5

### Link to debug log
https://debuglogs.org/76ddb198b787ffeeb231ba9bbacd15ce120f9ef72fa1a4e6f58b4072c45763c8

**Comment by jeremymasters** [comment]
Has used 16% in 6h 51m

**Comment by greyson-signal** [comment]
There were no code changes between 4.33.2 and 4.33.5 that could affect battery.

Nothing in the logs looks concerning. As in, I don't see anything going crazy, or getting stuck. However, it's worth noting that your Signal usage seems to be pretty heavy and consistent over the last 4 hours or so. Higher app usage means higher battery usage. You also made a call, which can use a lot of battery.

4.33.x does include a new version of WebRTC (although it was present in 4.33.2) -- do you see higher battery usage during calls at all? Could be something with the new version.

Other than that, my debugging capabilities are sort of at an end. Haven't seen this reported in any of the other support channels, nor have I seen any issues on my personal device. 

In order to learn anymore, I'd need an Android Bug report (Developer Options > Take bug report > Full report) which contains a lot of battery statistics. However, it also contains detailed metrics on how all apps on your phone are used, so I'd recommend you don't post it anywhere publicly. If you're interested in sharing this report with me (no worries if you don't want to), you can DM me on the forum or send it via Signal to one of my test numbers: +1 610-839-7235.

**Comment by jeremymasters** [comment]
Ok, where do I find the file?

**Comment by greyson-signal** [comment]
After you click the button, it kicks of an async process where it's doing stuff invisibly in the background. It'll post a notification when it's done (can take multiple minutes). Click the notification, then share it any number of ways. I think Signal doesn't actually show up as a handler because of our share filter or something, but you can put it any number of places, then send it to me however you like.

**Comment by greyson-signal** [comment]
Ok, so I looked through the battery report, and there appears to be some discrepancies between your experience and what the report says. Here's the summary:

- Report covers the last 6 hours
- Over that period, you went from 100% to ~60% battery (not fantastic, but not terrible either)
- The report says Signal accounts for ~4% of the battery usage
- Your screen was on for ~1:18, so a non-trivial amount of time
- Your mobile radio was active for ~2:32, also non-trivial
- Signal was used pretty heavily

Here's an interesting thing: Signal is listed as being a 'foreground process' for almost the entire 6 hours. However, I looked at your logs, and I can see you use the screen lock. So that makes sense -- we keep a foreground notification to show when Signal is unlocked. 

This _could_ result in your device mis-attributing battery usage to Signal, even though the battery report shows Signal didn't consume much energy at all. That's my best guess. I don't see anything crazy in the report.

If this happens again, you're more than welcome to send me another report, and I'll take a look.

**Comment by greyson-signal** [comment]
If you ever want to look at the report yourself in the future, install [Docker](https://docs.docker.com/install/) on your system and run:

```
docker run -p 9999:9999 gcr.io/android-battery-historian/stable:3.0 --port 9999
```

Then go to `localhost:9999` in your browser, and you'll be greeted with a Web UI that let's you select your bugreport.

(That's assuming Mac or LInux -- Windows instructions are slightly different and can be read about [here](https://github.com/google/battery-historian)).

Hope that helps!
