### ISSUE TITLE
Again Problems with the Backup feature

### ISSUE THREAD

**Issue by dorakas** [signalapp/Signal-Android#8613]
Device  : Google Pixel 3 (blueline)
Android : 9 (5163636, PQ2A.190205.001)
Memory  : 11M (39.79% free, 512M max)
App     : Signal 4.33.5

I use this phone with two profiles. On the second profile I registered signal with an sms receiving free online number service through Tor and locked the number with pin. Messaged everybody with the new number and did make a Backup. Now I transferred this backup to the first profile over signal. Deleted the app after that on the first profile and download it again. Copied the backup file in the signal.backup folder and allowed all permissions. Otherwise the Backup don't get recognised. Enter the password and it starts and takes me back to phone number registration. This is really odd, since I have several phones where not working backups are the case and all of them are in the issue section here with log files. Please OWS finish  a feature before releasing it as public code. 

This problems are present on some other friends phones too.

Please don't estimated on the number of support request and GitHub issues to get a realistic number of how many people are failing in using this backup feature and some other features too.

I would say that, you get maybe 5% of the actual number being effected by an issue. Maybe even much less. Because for some it works. And other don't take time to register or even bother to help with reports.

Respect the community that helps with ideas and bug reports. Don't waste time to work on new features before established ones are not working 100%.

This is the log from the second profile where the backup was made.

https://debuglogs.org/d34d8146c23cbfea1010d4b6d2daa73df239a09ded1e51c5fb20bf2793dcc7c0

This one is the log from the first profile:

https://debuglogs.org/f669e4cd5acd9092dd03ca2893f1a869bae283fb72652ff7a081eebe4380c2ea

**Comment by greyson-signal** [comment]
For whatever reason, your logs are relatively brief and neither include mention of a backup being imported or exported.

Just want to clarify something though:

> Enter the password and it starts and takes me back to phone number registration.

After you restore a backup with Signal, you still need to verify your number again. So after a successful restore,  you're taken to the number registration screen. After you go through the registration, you'll see all of your restored messages.

Just want to be sure that you actually experienced an error here.

**Comment by dorakas** [comment]
No it seems that there is no error. Like I said. I just checked the support pages. Why is it necessary to verify the phone number again? Was this the whole time this way? I think not. This issue can be closed

**Comment by greyson-signal** [comment]
It's always been that way. Just having the backup file doesn't mean you own the phone number associated with it, and you may also want to change your phone number.

**Comment by dorakas** [comment]
Ok. Sorry for the issue. Could have looked better. I'm really surprised to that. For my defense, I never had a working signal backup on my phone. This was one of the main reasons I did want to be able to backup. I tough I could take my anonymous phone number. That I really hustled for. With me. Sad.

**Comment by greyson-signal** [comment]
You _can_ take it with you. You just have to be able to re-verify it to prove that it's yours.

**Comment by five-c-d** [comment]
Forum discussion about the same basic idea == https://community.signalusers.org/t/dont-demand-registering-the-phone-number-again-after-restoring-a-backup/6366

Suggest updating the language when Registration-Lock-PIN feature is turned on, so that endusers are **crystal clear** this is not a way for them to be able to stop paying for the telco-num subscriber-service.  They have to retain control of the ability to receive unencrypted-SMS, if they want to use that phone-num as their signal-identifier long term.  

Reg-lock-PIN is not a substitute for control of the underlying phone-num... you don't want to remain in your groupchats, if you (more than temporarily) lose control of the underlying phone-num.  Reg-lock-PIN helps prevent loss of control over your signal-identifier during a temporary situation where Eve hijacks your phone-num at the SS7 level or via cracking into your carrier-web-settings-page or something... it does not let you *surrender* control of your telco phone-num indefinitely, though.
