### ISSUE TITLE
Contacts and conversations vanished

### ISSUE THREAD

**Issue by RESTORESIGNAL** [signalapp/Signal-Android#8644]
- [x] I have searched open and closed issues for duplicates. There is somewhat similar case with v4.24.8 https://github.com/signalapp/Signal-Android/issues/8102
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
No contacts, no conversations, no files, nothing...everything is gone...

### Steps to reproduce
- Open signal (not the first time after the latest update by the way, so I have no idea what caused it to happen).
- Signal asks to add some contacts. No contacts, no conversations, no files present.

**Actual result:** No contacts, no conversations, no files present.
**Expected result:** See my contacts, my conversations and my files. Be able to keep chatting with my contacts.

### Screenshots
Make a clean install and there is your screenshot.

### Device info
**Device:** Samsung Galaxy s5
**Android version:** rooted 4.4.2
**Signal version:** 4.34.8 (downloaded from Google Play Store)

Apps on my phone are extremely restricted and so is Signal. I will omit any privacy/security holy wars, so just deal with the fact. Signal has no access to contacts/calls/sms/and many more, as I never needed that functionality and it worked like that just fine for years, I'm on signal from the days when it was 2 different apps (almost from the very beginning of its existence).

There seems to be a few gigs worth of data related to Signal. Killed signal, to make sure that it won't kill more than it possibly did already and currently in the process of duping all of it. I'll try to scrape everything possible out of it, since my last Signal backup was performed a while ago.
Probably I'm done with signal. If things can disappear just like that then it's way too extreme and risky.

I'm only interested in messages text and received files. If you have some tips on recovering those from duped data I'd appreciate those. Also after I'm done with duping 100% of everything remained, hopefully it's not too scattered all over the place, I will be able to test your alpha/beta/gamma/whatever versions, to check if they can return everything back, but that's where my help ends, not going to submit my files or anything like that.

P.S. By the way - all settings remained, just in case my comment on screenshot was somewhat misleading for you.

**Comment by greyson-signal** [comment]
Without any logs, it's hard to say what happened. But if everything is completely reset (but your preferences remained intact -- which your 'PS' seems to indicate), it sounds like a database issue. There is no function in the codebase that resets the database or anything, so if something like this happens it's likely due to some sort of corruption/file permissions thing. 

In particular, on rooted devices, I've seen people install mods and/or play around with the file system in such a way where we lose read permissions to our own database, causing us to fail to open it and/or trigger a DB recreation. Maybe you can check that out and see if that's an issue. `/data/data/org.thoughtcrime.securesms` is Signal's internal directory (that can only be accessed on rooted devices). Maybe investigate to see if anything in there looks out of the ordinary. For instance, you could check the permissions in the `databases` folder, and ensure that `databases/signal.db` has the right permissions and whatnot.

**Comment by RESTORESIGNAL** [comment]
Haven't changed anything device-wise in a year or so, neither hardware, nor settings-wise, nor any new software that could potentially has any influence on Signal.

DB has both read and write permissions. I have also logged in Signal to check whether receiving new messages will restore conversation and nope, it wiped out DB and stuff and started new conversation. Now contacts do show up and so do conversations but history is gone, messages came in with "Message encrypted for non-existing session". Basically it was a wise decision of going instantly offline and killing Signal to dupe data, maybe not so wise to start it again before deep-diving into source code.

**Comment by greyson-signal** [comment]
Yeah, I guess the DB was already recreated, so the old one is probably gone. Because you're pre-marshmallow, you could theoretically get your attachment key from sharedprefs and keep your attachments though. 

Your debug logs could still be useful if you haven't cleared your storage yet (Settings > Advanced > Submit debug log). Could help figure out what happened.
