### ISSUE TITLE
Signal restore password after oanbackup backup

### ISSUE THREAD

**Issue by koraa** [signalapp/Signal-Android#8695]
Thanks for working on signal, my main messenger :)

Now to the issue: Currently backing up signal is a bit of a pain; I cannot update it along with my other android applications using oandbackup; initially it seems to work but, when I try to restore signal on the same phone, I just get error messages.

This is a major pain, mostly because it comes so unexpected; there is no warning during backup, it just fails on restore.

The current solution is to use the signal backup feature; unfortunately this still falls short, for to reasons: (1) it is a bit of a pain to have to backup signal separately (2) the actual encryption/authentification keys are not backed up.

The latter is an issue, because at least my contacts have by now been trained to simply disregard notifications of my security number changing, because I had two phones breaking this year.

In order to remedy this situation, I suggest introducing a restore key/password; this key could be user chosen or could be issued on the first install. I could safely store it in my gpg encrypted password manager on my laptop and just use that to unlock my signal instance after any backup.

**Comment by minnmann** [comment]
> (2) the actual encryption/authentification keys are not backed up

They do get backed up actually, if you use the built-in backup-restore function of Signal.

I used the feature several times myself (as have some of my contacts), and there hasn't been any change of safety number whatsoever, no notification, nothing - even the verification state is still the same. Some got a new device and I wouldn't have known, if they hadn't told me.
You just have to re-verify your own phone number (by receiving the SMS code) in order to prove that you still own that number. But AFAIK you could as well register a different phone number with the same backup, as the keys are not tied to the number but the installation.

> initially it seems to work but, when I try to restore signal on the same phone, I just get error messages.

Other apps can't easily do backups, since the key to access (and also backup) the Signal database is stored in the Android Keystore, which only Signal can read/modify. So oanbackup can't read it and therefore you get the error messages. 
There are, however, some workarounds using root access (discussed here and in the community forum).

> (1) it is a bit of a pain to have to backup signal separately

I simply use the built-in backup scheduler that generates a backup every 24h in background. Of course, copying it to a separate device (or uploading it to cloud storage) still requires some manual work.

**Comment by greyson-signal** [comment]
Thanks @minnmann for providing helpful background information!

As far as official support goes though, Signal just doesn't support third-party backup solutions. It's a "use at your own risk" kind of thing. If you encounter specific bugs with our built-in backup solution, please open a separate issue. Thanks!
