### ISSUE TITLE
Registration Lock PIN is not working

### ISSUE THREAD

**Issue by trmendes** [signalapp/Signal-Android#8699]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Once in a while Signal Messenger asks for my Registration Lock Pin and instead of typing it I click outside of the PIN box and then the message goes away and I'm back to Signal without typing my Lock Pin

### Steps to reproduce
- Wait Signal to ask you your Registration Pin Lock
- Don't type it and click anyway out of the dialog box

**Actual result:** Signal unblock even if I don't type my Registration Pin lock
**Expected result:** It should keep the dialog until I type my Registration Pin lock

### Screenshots
No screenshots

### Device info
**Device:** Motorola Z Force
**Android version:** 9
**Signal version:** 4.35.3

### Link to debug log

No Debug log

**Comment by greyson-signal** [comment]
The "registration lock" pin is separate from the "lock screen" in. The registration lock doesn't block your day-to-day usage of Signal -- it's only meant to be required during registration to prevent someone else registering your same number. The pop-ups are simply reminders to help you remember you PIN.

The "lock screen" can be enabled independently in Settings > Privacy, and that will have the behavior I think you're looking for.

**Comment by RickyBC** [comment]
Hi,

On this page - https://support.signal.org/hc/en-us/articles/360007059792-Registration-Lock -  there is the following text about the registration lock:

> How does Signal help me remember my Registration Lock PIN?
> 
> Signal includes a built-in reminder feature that uses spaced repetition. To help you memorize your Registration Lock PIN, Signal will periodically ask you to confirm it. These reminders occur at the following intervals after the feature is first enabled:
> 
>     6 Hours
>     12 Hours
>     1 Day
>     3 Days
>     7 Days
> 
> You will see the reminders less frequently if you consistently enter your Registration Lock PIN correctly. The reminders will become more frequent if multiple attempts are necessary.
> 
> Can I turn off these reminders?
> It is important to memorize your Registration Lock PIN, and the reminders cannot be disabled. However, you will only see the reminder once a week after you have correctly entered your Registration Lock PIN multiple times.

This makes it sound like you need to enter the pin for the reminder to go away. The bug is about the fact that you can just tap outside the reminder box and the box asking for your registration lock pin will disappear.

A resolution, if this is not a bug after all and is actually intended behaviour, would be instead to change that page and other references to the registration lock pin, to point out that the reminders are completely optional and can be ignored/hidden by tapping outside the box to hide the modal/pop-up.
