### ISSUE TITLE
Conversation Settings missing since Note-to-Self

### ISSUE THREAD

**Issue by d-t-o** [signalapp/Signal-Android#8708]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Before the note-to-self feature, the contact behind your own number was a regular contact that had a full conversation settings menu. Which e.g. allowed you to change the notification sound. this has now changed, the conversation settings of the note-to-self contact now miss most of the settings a regular contact has.

background for me using this setting: i had set a non-default notification sound for my own messages in the past, but after reinstalling signal i can't set it any longer. those self-messages are happening when a linked device, in this case my linux box running the signal command line client, sends me a message. as that's usually an important notification (e.g. failed harddrive), i'd like to have a different notification sound for my own messages. might sound weird, but worked well in the past :)

i see that this setting would not be needed if no linked devices would exist since then the note you just wrote would instantly and automatically be marked as read and no notification would be played anyway. but since linked devices are a thing in the signal universe, you can get a message from an external device and a notification sound will be played then. therefore it would be nice if the option to configure it could be reinstated. 

since there is sill an empty, scrollable box where the missing settings once were, i assume their absence is actually a bug introduced with the recent note-to-self feature and not a design decision though.

### Steps to reproduce
- select any contact conversation
- open conversation settings -> chat settings
- see that there is an option 'notification sound'
- open the note-to-self conversation
- open conversation settings -> chat settings
- see that there is no option 'notification sound'

**Actual result:** note to self has a mostly empty layout where the settings should be
**Expected result:** the full set of options is also offered for this contact

### Device info
**Device:** Xiaomi Redmi4X
**Android version:** 9
**Signal version:** 4.35.3

**Comment by minnmann** [comment]
> you can get a message from an external device and a notification sound will be played then

I just tried that (sent a message from a linked device to my phone) and my phone does not play any notification when sending a note-to-self.
This seems to me the expected behavior as Signal does also not display any notification at all for a note-to-self. (Technically, AFAIK, these are not handled as regular messages, but as device-sync messages, similar to what happens, when you message someone else on the desktop: Your phone gets the same message via a sync and does not notify you.)

In general (apart from your specific use case), I don't think a notification for a message sent from yourself would make much sense (you anyway know that you sent it).

If your phone does, however, play a notification in that case, this sounds like a bug to me, for which you probably should add a debug log for the developers to be able to dig into.

In any case, if you would like to discuss features for the Note-to-self conversation (e.g. things that you would like to have for your use case), I think the best place is the [community forum](https://community.signalusers.org/). Btw, there is already a thread discussing such use cases: https://community.signalusers.org/t/use-cases-for-note-to-self-feature/6490

**Comment by d-t-o** [comment]
i assume your linked device automatically marks it as read before the notification is being played on the main device. you'll hear the sound if you send the message via a command line client, since it doesn't also auto-receive but just sends.

since i was able to set the notification sound in an older version of signal, this not being possible anymore sounds like a bug, not a feature to me. thanks for the link though, if the devs say it's not a bug and close this issue, i'll gladly add it to the feature request list. as long as this is open, i'd rather not discuss this in two places at once.

**Comment by minnmann** [comment]
> since i was able to set the notification sound in an older version of signal, this not being possible anymore sounds like a bug, not a feature to me.

Well, on the contrary, I would argue that the (unofficial) command line client is not implementing the "correct" behavior (of the official clients), as it probably does not send a device-sync message, but a regular Signal message.

To confirm this, I had a look at the signal-cli codebase and interestingly enough, they changed the behavior just 16hrs ago:
https://github.com/AsamK/signal-cli/commit/24714454dd43fe2df8981d37c98bd5c4c1a69a45

> if the devs say it's not a bug and close this issue, i'll gladly add it to the feature request list. as long as this is open, i'd rather not discuss this in two places at once.

Sure - let's wait and see what the devs think about this!

**Comment by greyson-signal** [comment]
> since there is sill an empty, scrollable box where the missing settings once were, i assume their absence is actually a bug introduced with the recent note-to-self feature and not a design decision though

Quite the opposite -- it was very much an intentional design decision :) 

> Well, on the contrary, I would argue that the (unofficial) command line client is not implementing the "correct" behavior (of the official clients)

That's correct, it's an unofficial client that was doing things the wrong way. 

> To confirm this, I had a look at the signal-cli codebase and interestingly enough, they changed the behavior just 16hrs ago:

But it looks like they catch up pretty quickly :)

Anyway, the thinking goes like this -- messages to yourself should not trigger notifications, and therefore most conversation settings become irrelevant. That's why we hide them. The fact that you got notifications for messages to yourself before was a side effect of a poorly-behaving client. If you have a CLI setup that you'd like to keep, you can always register it with a $1/mo twilio number or something so that it comes from a different number.

**Comment by isopterix** [comment]
This is really stupid! Please consider adding back an option to at least let the user decide whether he or she wants to get notified on a "Note to Self" message or not.

Now I need to hunt for an extra phone number which otherwise I would not need :/

**Comment by alan-signal** [comment]
@isopterix please use the community forum for feature requests/discussions https://community.signalusers.org/
