### ISSUE TITLE
Backup renders phone nearly unusable at inopportune times

### ISSUE THREAD

**Issue by RobotCaleb** [signalapp/Signal-Android#8717]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While a backup is active the phone is unresponsive. This is a problem as the backup seems to occur at ~noon every day. Would love the backup to be less system intensive or allowed to be scheduled by me. (I'm assuming it's at noon because that's when I initiated the action to create backups. Which would imply a possible workaround is to wake up at 0300 and tell Signal that I want backups to be created?)

### Steps to reproduce
- let automatic backup occur

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
- if backup occurs while one wants to use phone, slowdown is disruptive

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
- backup occurs when phone isn't wanting to be used/on a user-define schedule

### Device info

**Device:** Pixel 2
**Android version:** 9
**Signal version:** 4.36.2

### Link to debug log
https://debuglogs.org/590f825465d9bcabfa9ba69b211386d13cf5688077a87253c88755455a2d7ba9

**Comment by aibaraiduas** [comment]
While I don't experience any lag when Signal is creating a backup, it can be a pretty slow process on an older phone (a Pixel 2 is pretty new though, so that seems odd to me).

As a workaround, you can change the time Signal makes a back up, as [described here](https://community.signalusers.org/t/time-of-day-for-the-creation-of-encrypted-backups/4116/27). The process does require root though.

1. Kill Signal.
2. edit /data/data/org.thoughtcrime.securesms/shared_prefs/org.thoughtcrime.securesms_preferences.xml
3. modify the property pref_backup_next_time to the desired value (Unix time in milliseconds)
4. Restart Signal again.

It'd be nice if there was an easy way for the user to set the backup time within the app.

**Comment by PaymonJ** [comment]
Being able to schedule backups (without root) is something that really is needed. Right now, my phone becomes *really* slow to the point where it is unusable when a backup is being created.

**Comment by dcormier** [comment]
This has been a problem for me, as well. For me, it would be ideal to:

1. Have backups occur at a time when the phone is plugged in
2. At some scheduled window (in my case, late at night/early window
3. Be cancelable; if somehow I'm still using the phone at that point, I just want it to stop

**Comment by vertigo220** [comment]
I agree with this. I didn't even realize Signal was scheduling backups, since there's absolutely no indication of this when performing a backup. I was going to come here to search, and create an issue if necessary, for the ability to schedule backups, since that's such a basic and important function I was surprised it wasn't already there. Then I found out when examining my storage due to running a bit low that it appears to be doing it daily and, as mentioned, it seems to be every 24 hours from when it was done manually.

So it really needs to make this clear when performing one, and it should also allow the backup location to be configured (so I can have it done to external storage, i.e. SD card, which is another problem since it currently says "Backup chats to external storage" which clearly isn't accurate, since it's backing up to internal storage). And it should allow the choice of a one-time backup or doing so on a configurable schedule, not only the time but how often (daily, weekly, etc). Or perhaps better yet, just add an external intent for it, so users can set up an automation app to trigger it whenever they want (of course, it would be ideal to do both, so more basic users could do it easier and more advanced users could customize it more).

**Comment by MarekPikula** [comment]
I also experience slowdown on moderately new HTC One 11, but I have a lot of messages, so I guess it's normal (backup is ~4GB).
Another nice feature would be to run backup only when the phone is plugged, as it drains battery a lot in my case.

**Comment by diogodh** [comment]
Same problem here on OnePlus 6 with 8gb ram and 5gn backup. 
It backups and the app signal becomes unstable.
Would be great to choose the time of the backup since mine doesn't change even after I manually backup on a different time

**Comment by LiKenun** [comment]
To add to the above: when my phone runs out of space at these inopportune backup times, my other apps crash or stop doing their work (such as when I audio record meetings). I’d like to have more space on my phone, but it’s unfortunate that even 64GB is not quite enough for an Android phone with a lot of apps installed.

**Comment by vertigo220** [comment]
I only have 32GB, so at most I can store two backups (and I don't do much texting) before running out of space. Because of how this "feature" is set up, it's completely unusable to me and so I've disabled it. Between that and the new PIN "feature" that only serves to annoy me with an alert covering the bottom quarter of the screen every time I open the app bugging me to enter the PIN, as well as a bunch of other issues, I'm looking at alternatives to Signal.

**Comment by RobotCaleb** [comment]
This has rotated around the clock a fair bit for me and it's now back in the middle of "I want to use my device" time, rendering text entry and app opening slow and annoying. I've even taken the measure of limiting all conversations to 500 messages length in hopes that this would decrease the impact of the backup duration, but to no avail.

**Comment by greyson-signal** [comment]
I'm going to try to do some work to make sure that we only do backups when your device is plugged in and ideally inactive. Should at least be able to do this on Android 8+ :+1:

**Comment by vertigo220** [comment]
Or, here's a thought, just allow the user to set the time. The best option, though, would be to use external calls (intent), so users can set up their own schedules using Auomagic/Tasker/etc.

**Comment by sixcircuit** [comment]
Leaving this for people that might have this issue in the future. As per comment in the [community thread](https://community.signalusers.org/t/time-of-day-for-the-creation-of-encrypted-backups/4116/27) referenced above. Now the solution is:

Turn off backups for more than 24 hours, and then turn them back on at the time you would like them to happen.

**Comment by sixcircuit** [comment]
It would be awesome if you could make this feature work. Could it be as simple as resetting the counter if you manually hit the backup button? Not super elegant, but it means if I hit the back up button at midnight, it'll back up at midnight every day.

**Comment by Duetting** [comment]
Deactivating the backup for more than 24 hours and reactivating it at the desired time still seems to be the only option. I would really love to have some configurable options.
E. g. weekly backups would be sufficient for me.

**Comment by abrasive** [comment]
I see this has been improved along the lines @greyson-signal mentioned!

Unfortunately now the backup runs as soon as I plug my phone in in the evening (eg. 20:30) -- which is often when I need to charge for a few minutes to get through the night. Now instead of charging for minutes I end up tethered to the wall, oops!

Please can we have a simple setting to set a time window for backups? Pretty please? With a cherry on top?

I appreciate the desire to minimise the configuration surface and have something that "just works", but for something that burns so many joules and can't be paused or interrupted, I think it might be necessary.

**Comment by lp35** [comment]
Hi, could you reopen this ticket? Having the possibility to set the frequency of backups OR disable automatic backup will prevent my storage be pumped while we are sleeping :)

Cheers!

**Comment by fischer-felix** [comment]
I would also appreciate more control about when backups are made, since it renders my phone (LG V30) basically completely useless. Most evenings I plug my phone in for charging at night, however I still want to use it for a couple of minutes, which makes this all the more frustrating.

**Comment by cody-signal** [comment]
Hi there @fischer-felix depending on your android version, you can schedule backups now. However, it sounds like yours is old enough that it's still just the charging constraint. We are hoping to expand backup scheduling to all devices soon (no technical restriction really, just need to do it)

**Comment by fischer-felix** [comment]
Thanks for the quick response, but I'm stuck on Android 9, so can't schedule backups. Looking forward to also get this feature.
