### ISSUE TITLE
Button bar on Galaxy S8 remains light in dark mode

### ISSUE THREAD

**Issue by jxcl** [signalapp/Signal-Android#8758]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The software button bar on the Galaxy S8 changes color depending on the theme of the app that is open. Signal in Dark Mode appears to not correctly set the color of the bottom bar.

### Steps to reproduce
- Set app to dark mode
- See that the bar does not change to be dark
- Open samsung keyboard in dark mode
- See that the bar changes to dark

### Screenshots
![Screenshot_20190411-193538_Signal](https://user-images.githubusercontent.com/108500/56006419-f744b800-5c91-11e9-8d60-3034f29afdea.jpg)
![Screenshot_20190411-193743_Signal](https://user-images.githubusercontent.com/108500/56006420-f744b800-5c91-11e9-9279-8a80553b3537.jpg)

### Device info
**Device:** Samsung Galaxy S8+
**Android version:** 9
**One UI version:** 1.0
**Signal version:** 4.37.2

**Comment by mikeymop** [comment]
Does it switch in other apps?

My dad has a Note 8 and his navbar *only* changes based on the theme he set in the Samsung Theme editor.

Also apparently some Samsung apps can trigger it so I think Samsung fragmented their Android Distro *even further* and is using a different intent/api/etc to trigger it than what Android has by default.

**Comment by jxcl** [comment]
@mikeymop When I toggle Dark Theme in Youtube, the bottom bar switches as well. Let me know if you would like screenshots of that.

**Comment by athanasio** [comment]
I'm not a developer, but comparing Conversations IM (where enabling dark mode switches the color of the navbar) and Signal, I see that Conversations follows the theme of the system:
`https://github.com/siacs/Conversations/blob/master/src/main/res/values/themes.xml:
        <item name="android:actionModeBackground">?colorPrimary</item>`
while Signal sets a custom gray color:
`https://github.com/signalapp/Signal-Android/blob/master/res/values/themes.xml:
  <style name="TextSecure.DarkTheme" parent="@style/Theme.AppCompat">
        <item name="theme_type">dark</item>
...
        <item name="actionModeBackground">@color/gray50</item>
`
I can't test it because I don't have a development machine at the moment, however as @mikeymop mentioned, it works on most other apps - and it works in Conversations in particular.
