### ISSUE TITLE
problem with photos 

### ISSUE THREAD

**Issue by leonardoporp** [signalapp/Signal-Android#8825]
### Bug description
Hi Greyson I have problem sometimes when I have to send videos or photos
These problems seems to be present only when the connection is slow, I mean the photo seems to be uploaded at 80% than it restarts and the outgoing traffic seems to be higher than the photos length

### Steps to reproduce
Idk

**Actual result:** image doesn't get sent till I get into a fast wifi
**Expected result:** even if slower it should be sent

### Device info

**Device:** pixel 2 XL
**Android version:** 9
**Signal version:** latest

### Link to debug log

Sent you through Signal

**Comment by greyson-signal** [comment]
Haven't looked at the log, but I'm assuming that if you're on a flaky connection, then occasionally the image upload may fail and be subsequently retried.

**Comment by attila-lendvai** [comment]
just another data point:

i'm seeing this also. even on my wifi, where my upstream is 1 MB/sec, and with photos of around 2-3 MB.

this may or may not be related, but recently i also noticed that calls have more problem getting through when i'm on my wifi, and when i switch to mobile data, it gets through much faster and more reliably. this *should* not be due to my wifi, but i don't have QoS monitoring on it.

i'm in Hungary, and i don't know about any attempts at blocking/interfering with Signal.
