### ISSUE TITLE
Multi-part SMS >160 characters fail to send on US Cellular (CDMA)

### ISSUE THREAD

**Issue by pcttech** [signalapp/Signal-Android#8882]
I'm creating this as a new issue because although there have been issues opened for it before, they've been closed and abandoned, yet this problem has persisted for several years. See #191, #387, #402, and perhaps others.

Basically, long text messages that are supposed to be broken up into multiple messages instead fail to send. This is an issue that affects adoption of Signal for users of the US Cellular network.

I believe the crux of the issue is that US Cellular does not support concatenated SMS, as hinted at by [this Twilio post](https://support.twilio.com/hc/en-us/articles/223181508-Does-Twilio-support-concatenated-SMS-messages-or-messages-over-160-characters-). 

For the record, _all apps_ I've tried that attempt to send multi-part messages / concatenated SMS experience this failure on US Cellular. The only apps that succeed are ones that convert to MMS, like Android Messages or the stock Messaging apps, but from the user's perspective, this is a problem with the affected app (Signal).

Although I do not believe this bug to be necessarily Signal's "fault," it would be beneficial for users if a workaround were implemented to allow the sending of long messages as MMS for those who use the US Cellular network.

Here's one of the relevant debug lines:
`D RilRequest: [5621]< RIL_REQUEST_CDMA_SEND_SMS error: com.android.internal.telephony.CommandException: SMS_FAIL_RETRY ret={ mMessageRef = 108, mErrorCode = 100, mAckPdu = null}`

And here's a log:
[Signal SMS Send Failed Relevant Logs 20190618.log](https://github.com/signalapp/Signal-Android/files/3303239/Signal.SMS.Send.Failed.Relevant.Logs.20190618.log)

This issue is highly reproducible. Let me know if I can help.
![Screenshot_2019-06-18-12-15-56 (2)](https://user-images.githubusercontent.com/51971784/59717022-fcf7d600-91cb-11e9-915c-76c56ab22c7c.png)

**Comment by aastimson** [comment]
Seconding the importance of this issue. It's a deal breaker on using this as my primary messing app, which I had just started to do.

**Comment by pcttech** [comment]
For what it's worth, with a different model of phone, purchased retail rather than through US Cellular, this problem has not occurred. I can't say either way, but this might be something related to US Cellular's customized firmware.

Affected models were: LG K8, LG K8+(2018) - US Cellular models
Unaffected model: Motorola Moto G7 Play US Retail (PAE80008US)

**Comment by matt6575** [comment]
This is a big problem for me as well. Have people that try signal then as soon as this issue crops up they stop using it. 

I also have a few less tech savvy people trying to use it as well and I set their signal to not handle sms but they keep re-enabling it because they have previous texts in signal from contacts without signal and while in signal they will without thinking click the old conversation with that non-signal user. Then because signal displays a "Use signal for sms" at the bottom of a non-signal contact conversation (if signal isn't set to handle sms) they end up clicking that which sets signal as default for sms again. They then have the problem with long messages not working again.

Also MMS doesn't appear to work at all with signal on US Cellular.

I'm fine with using two messaging apps myself, one for signal users and a different one for non-signal users. For most people I know though it's a deal breaker.

**Comment by TannerR1776** [comment]
For what its worth, I am also experiencing this issue. Its very frustrating, and makes the app nearly unusable, as special characters and emoji's reduce the character count down even further.

I can provide debugging / testing information if needed.

**Comment by lewi3069** [comment]
I also have someone on US Cellular having the same issue. Is there any update?

**Comment by lewi3069** [comment]
Any update for this issue?

**Comment by pcttech** [comment]
Unfortunately, there has been no change that I know of. My company ended up switching service providers (for many reasons, including this one), and we are no longer experience the issue. Good luck to those who are.

**Comment by Jonimoose** [comment]
This appears to still be an issue but I have noticed it seems to work if I send one multipart sms with the default messages app first then switch to Signal. It breaks again after restarting the phoneand I'm not sure how to check what this changed. It also wasn't an issue on my previous phone which was a USCC Galaxy S5. The new phone with the issue is an unlocked Pixel 4a 5G.

**Comment by jduiella** [comment]
FWIW:

![image](https://github.com/signalapp/Signal-Android/assets/50113101/806181de-4c65-4cde-b6a7-931aab95a0de)

https://support.twilio.com/hc/en-us/articles/223181508-Does-Twilio-support-concatenated-SMS-messages-or-messages-over-160-characters-
