### ISSUE TITLE
Recording of voice messages fails

### ISSUE THREAD

**Issue by ProactiveServices** [signalapp/Signal-Android#8898]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I pressed and held the microphone icon to record a voice message. The icon showed that it was recording. After recording for approx. five seconds I released the icon and nothing appeared to happen.

I tried again, this time by swiping to lock the microphone. The recording timer started to count and I spoke the voice message. After clicking the send icon, again nothing happened.

Signal actually created three voice messages. One is marked as "failed to send" and two were successfully sent, but are of zero length.

Once I closed the app and re-opened it, voice message recording works correctly.

### Device info
**Device:** Huawei P20 Lite ANE-LX1
**Android version:** 8.0.0
**Signal version:** 4.42.3 (4982)

https://debuglogs.org/b10222c58684fb57004b37d8f9fa3f7524162ffc9a2faf854f4fcafec3dcbedf

Zipped copy of one of the sent voice messages; saved from Signal Desktop.
[signal-attachment-2019-06-29-121721.zip](https://github.com/signalapp/Signal-Android/files/3341828/signal-attachment-2019-06-29-121721.zip)

**Comment by five-c-d** [comment]
> three voice messages.  One is marked as "failed to send" 
> and two were successfully sent, but are of zero length

There are a large number of network-errors (which might not *actually* be problems with the network but that is what signal4android believes is the problem at least).  In particular 

* 2019-06-29 12:09:25.104 BST 
* I BaseJob: org.thoughtcrime.securesms.transport.
* RetryLaterException: 
* java.net.UnknownHostException: 
* Unable to resolve host "uptime.signal.org": 
* No address associated with hostname

But it looks like pretty much all the problems during the 2019-06-29 12:03 (or 12:04) timespan through the end of the debuglog at 12:14 were network-complaints.  

* RetrieveProfileJob started at 12:04:51 which failed 
* PushTextSendJob started at 12:05:23 which failed 7 times in a row 
* ServiceOutageDetectionJob started at 12:08:57 which failed 3 times in a row 
* 26 ioException 
* 56 timeoutExceptions (various types) 
* 36 UnknownHostException

By contrast, earlier the same day in the 8:30-to-9:40 timeframe it looks like everything was fine.  Can you give some idea what the internet-connectivity was like at the two different times?  Whether you were on wifi or on dataplan, and whether you were experiencing other troubles, and if you were at the same physical location during both timeframes.  

To be clear, the root cause of the problem might well NOT be actual network-issues, it could be your internet connectivity was fine ... but certainly, the manifestation of whatever the real problem turns out to be, was a lot of network-related-error-messages, so we start with the assumption the network has SOMETHING to do with it :-)  and go from there

**Comment by ProactiveServices** [comment]
Thank you for such a prompt and detailed reply. My network comings and goings, again in BST:
00:00 to approx. 11:30 the phone was on my home WiFi. According to my ISP and router my connection was up and stable for the duration. I used my connection only briefly but noticed no problem.

Around 11:30 I switched to cellular data and cycled into West Sussex where my signal strength will have steadily dropped. _(A Hampshire resident would say that about West Sussex...)_

I arrived at my destination just after 12:00 whereby I had almost no cellular signal at all, and switched to the WiFi on a reliable Internet service, which I used on both phone and other systems. I can't exactly recall when I switched to WiFi but if the logs suggest network instability until 12:14 then this would suggest I was still on poor cellular then.

**Comment by ProactiveServices** [comment]
I had a similar problem later today, except that a voice message never sent; neither my Desktop clients nor my recipients saw it and Signal is not displaying it on the phone. Again, the UI showed it was recording (locked mic in this case) and I definitely pressed the Send button when finished. No error or anything else appeared.

On this occasion I was on cellular data with a very strong 4G signal but the service was hopeless: I couldn't even connect to my email provider sometimes. I think this was because so many people were out enjoying the sunshine!

The message was attempted just before 18:01 BST.

https://debuglogs.org/0705248ea4e2afa4b864a1cad499329af311871e3e654b45ff20ccd1ab3087a6

**Comment by five-c-d** [comment]
Putting the conclusions at the start... 

1.  why did two of the messages around 12:10 timeframe, send zero-byte screwups, instead of either sending the full correct message, or saying Send Failed?  (bad network-connectivity should not result in "partly successful" send-payloads)

2.  unrelated methinks:  why did the voiceNote attempt at 18:00:07 of around 40 seconds duration, fail to persist?  and did not throw any errors, that I perceived, either? 

3.  what about the 16:43 voiceNote of around 7 seconds duration, did it work/persist?  

As the astute reader will note, these "conclusions" are all questions :-)  so we shall have to await somebody more savvy than myself, to figure out what is going awry.  I can say pretty definitively that your 12:05+ networking difficult and your 18:00 voiceNote don't seem related to each other, in terms of the root cause.  

<details><summary>timeline analysis of debuglog2 and DuplicateMessageException</summary><p> 

> 00:00 to approx. 11:30 the phone was on my home WiFi

Looks like things were mostly fine, at those times, as far as signalapp was concerned

> Around 11:30 I switched to cellular data

Things were still fine for a bit... 

> I arrived at my destination just after 12:00 
>  I had almost no cellular signal at all
>  and switched to the WiFi

Not sure if you were on the wifi or the cellular at 12:04 thru 12:14 when the first debuglog ends, but whichever one it was, did NOT have strong/actual internet connectivity.  Your second debuglog starts at 12:17 a few minutes later, and immediately has a bunch of exceptions which seem pertinent to the bad behavior:  

```
$ cat proactiveSvc_quickMic_later.txt | grep -i -e " E " -e "exception" -e "error" -e "warn" -e "fail" -e "opening url: http" -e "sent message" -e "call_"

12:17:22.387 W PushDecryptJob: org.signal.libsignal.metadata.ProtocolDuplicateMessageException: org.whispersystems.libsignal.DuplicateMessageException: Received message with old counter: 1 , 0
12:17:22.970 W PushDecryptJob: org.signal.libsignal.metadata.ProtocolDuplicateMessageException: org.whispersystems.libsignal.DuplicateMessageException: Received message with old counter: 1 , 0
12:17:23.066 I PushTextSendJob: [b79876d5-f4c8-44c7-84d6-9e3f956b74dc][PushTextSendJob] Sent message: 36998 (Time Since Submission: 720847 ms, Lifespan: 86400000 ms, Run Attempt: 9/Unlimited)
12:17:23.519 W PushDecryptJob: org.signal.libsignal.metadata.ProtocolDuplicateMessageException: org.whispersystems.libsignal.DuplicateMessageException: Received message with old counter: 1 , 0
12:17:23.947 W AttachmentUploadJob: java.io.IOException: Assertion failed, outgoing attachment has no data!
12:17:23.950 W BaseJob: [f402fdfd-1f9e-4ae1-ad71-38394a74eb58][AttachmentUploadJob] Encountered a failing exception. (Time Since Submission: 1854 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
12:17:23.950 W BaseJob: java.lang.NullPointerException: Attempt to invoke virtual method 'org.whispersystems.signalservice.api.messages.SignalServiceAttachmentStream org.whispersystems.signalservice.api.messages.SignalServiceAttachment.asStream()' on a null object reference
12:17:23.957 W JobRunner: [f402fdfd-1f9e-4ae1-ad71-38394a74eb58][AttachmentUploadJob][1] Job failed. (Time Since Submission: 1861 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
12:17:24.181 W PushDecryptJob: org.signal.libsignal.metadata.ProtocolDuplicateMessageException: org.whispersystems.libsignal.DuplicateMessageException: Received message with old counter: 1 , 0
```  

Things look fine again right after that, successful send at 12:17:31.027 and then a slew of successes at 12:34:40 and beyond.  So my guess is that you were on weak-to-nada cellular data from 12:04 thru 12:16 and then switched to wifi afterwards.  Lost the socket around 13:37 when your phone went into doze.  

</p></details> 

Some profile-retrieval exceptions 14:54 thru 15:06 culminating in UnknownHostException again (similar but not identical to what you had in the worst section from 12:04 thru 12:14), and looked fine again around 15:15 or so.  Couple hours later: 

<details><summary>three batches of AttachmentServer SocketTimeoutException: Poll timed out</summary><p>

```
17:05:42.605 W SignalServiceMessageSender: java.io.IOException: No connection!
17:05:42.610 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+**********60
17:05:49.697 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
17:05:55.787 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
17:06:00.750 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
  (fifteen more like... that every ~5 seconds) 
17:07:15.510 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
17:08:33.071 W WebSocketConnection: onFailure()
17:08:33.073 W WebSocketConnection: java.io.EOFException

//later 
17:43:38.182 W SignalServiceMessageSender: java.io.IOException: No connection!
17:43:38.185 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+*********77
17:43:44.684 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
  (twelve more like it) 
17:44:46.949 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out

//later
17:48:42.205 W SignalServiceMessageSender: java.io.IOException: No connection!
17:48:42.207 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+*********77
17:48:48.219 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
17:48:49.605 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
  (fourteen more like it) 
17:50:02.296 W AttachmentServer: java.net.SocketTimeoutException: Poll timed out
```

</p></details>

I'm not sure if the 18:01 message-attempt threw any exceptions?  It looks like it was 40 seconds long (after a couple of sub-second false starts), but then, nothing happened, like you say.  What about your 7 second audioRecorder at 16:43, was that successful?  

p.s.  There is a bug in the new sticker-pack feature with not properly cleaning up the SQLCipher handles, I will note in passing:  

<details><summary> SQLiteCompiledSql DatabaseObjectNotClosedException: App did not close the cursor</summary><p>

```
18:06:55.133 29682 29690 W SQLiteCompiledSql: net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
18:06:55.134 29682 29690 E Cursor  : Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/org.thoughtcrime.securesms/databases/signal.db, table = sticker, query = SELECT * FROM sticker WHERE emoji LIKE ? AND cover = ?
18:06:55.134 29682 29690 E Cursor  : net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
18:06:55.134 29682 29690 E Cursor  : 	at net.sqlcipher.database.SQLiteCursor.<init>(SQLiteCursor.java:237)
18:06:55.134 29682 29690 E Cursor  : 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:71)
18:06:55.134 29682 29690 E Cursor  : 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
18:06:55.134 29682 29690 E Cursor  : 	at net.sqlcipher.database.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1740)
18:06:55.134 29682 29690 E Cursor  : 	at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1692)
18:06:55.134 29682 29690 E Cursor  : 	at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1781)
18:06:55.134 29682 29690 E Cursor  : 	at org.thoughtcrime.securesms.database.StickerDatabase.getStickersByEmoji(StickerDatabase.java:143)
18:06:55.134 29682 29690 E Cursor  : 	at org.thoughtcrime.securesms.stickers.StickerSearchRepository.lambda$searchByEmoji$0(StickerSearchRepository.java:27)
18:06:55.134 29682 29690 E Cursor  : 	at org.thoughtcrime.securesms.stickers.-$$Lambda$StickerSearchRepository$LPCFa1tFsEpt1tQmOW482ZJfENo.run(Unknown Source:6)
18:06:55.134 29682 29690 E Cursor  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
18:06:55.134 29682 29690 E Cursor  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
18:06:55.134 29682 29690 E Cursor  : 	at java.lang.Thread.run(Thread.java:784)
```

</p></details>

Also several of these, which I've seen before ==      06-29 18:06:35.756 29682 29682 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
