### ISSUE TITLE
Signal users on certain Android devices experiencing crashes when downloading profile information

### ISSUE THREAD

**Issue by 3WfMeCuUqzgXBh** [signalapp/Signal-Android#8903]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is an issue being observed by multiple users in the UAE on Android.

1: Signal is crashing when opening particular chats. At first we noticed this issue in a group chat, it occurred for two of the users on Android after one of the users on iOS updated the profile picture for the group. Immediately after the profile picture was updated signal crashes every time the user opens the chat. One of the users has even replaced his phone since and even with a fresh install on a new phone the same group chat crashes the app.

A little while later this started happening in a one on one chat between an Android user and iOS user, everytime the android user opened the chat Signal crashes. Remembering the issue from the group chat the iOS user removed the profile picture and they can now chat without any issues.

### Steps to reproduce
- as mentioned above in one case removing the profile picture fixed the problem for issue 1
- I can not recreate issue 1 on a oneplus 5T with the website build of Signal (no google play)

### Device info
**Device:** Various
**Android version:** Various
**Signal version: 4.42.3

### Link to debug log
This log seems to point to RetrieveProfileAvatarJob possibly having an issue?
https://pastebin.com/raw/9MtvYaZW

More debugging info to come.

**Comment by sekritskwurl** [comment]
Just wanted to second this issue. This has been happening for me for a couple months. 

I have the same issue with my android phone. Apparently when someone adds a profile picture to and existing chat signal crashes. 

I built a websiteDebug version of the app and deployed it to my handset. Everything was fine until my buddy added his profile picture. This was the error that I received.

``I/ConversationActivity: updateDefaultSubscriptionId(null)
D/JobSchedulerScheduler: onStartJob()
D/WakeLockUtil: Released wakelock with tag: signal:167499b3-7790-4dc4-9d4f-bb73fdcbe027
I/JobRunner: [167499b3-7790-4dc4-9d4f-bb73fdcbe027][SendReadReceiptJob][2] Job finished with result: SUCCESS (Time Since Submission: 957 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
D/WakeLockUtil: Released wakelock with tag: signal:1c7d5136-e1fb-4b68-b677-4fda573fb6b7
E/AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-4
    Process: org.thoughtcrime.securesms, PID: 21080
    java.lang.AssertionError: Need: 12272 but only have: 8192
        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
E/UncaughtExceptionLogger: java.lang.AssertionError: Need: 12272 but only have: 8192
        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:71)
        at org.whispersystems.signalservice.api.crypto.ProfileCipherInputStream.read(ProfileCipherInputStream.java:51)
        at org.thoughtcrime.securesms.util.Util.copy(Util.java:271)
        at org.thoughtcrime.securesms.jobs.RetrieveProfileAvatarJob.onRun(RetrieveProfileAvatarJob.java:105)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
I/PassphraseRequiredActionBarActivity: onPause()
I/Process: Sending signal. PID: 21080 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'``

 I looked up what the ProfileCipherInputStream.java was and I couldn't find it in the code, so I checked the libsignal-service-java repo and found it there.  But. I don't know if this is the source of the issue. 

If I knew how to get more verbose output I would.

**Comment by Payam121** [comment]
It's seems issue number 2 is very bad problem, users encountered similar issue in VPN Mode in Iran.
Please see the following issue:
https://github.com/signalapp/Signal-Android/issues/8865

**Comment by sekritskwurl** [comment]
> It's seems issue number 2 is very bad problem, users encountered similar issue in VPN Mode in Iran.
> For better understanding, many Iranian users must use VPN because of heavy censorship mechanism in Iran.
> Please see the following issue:
> #8865

I disagree that these issues are related. If you are connecting and reconnecting to different networks delays and dropped traffic will happen.

**Comment by 3WfMeCuUqzgXBh** [comment]
Updated to reflect single issue, will do more investigation on the 2nd issue and open a separate issue if required

**Comment by Phase121** [comment]
> 
> 
> > It's seems issue number 2 is very bad problem, users encountered similar issue in VPN Mode in Iran.
> > For better understanding, many Iranian users must use VPN because of heavy censorship mechanism in Iran.
> > Please see the following issue:
> > #8865
> 
> I disagree that these issues are related. If you are connecting and reconnecting to different networks delays and dropped traffic will happen.

It's not related about delay in traffic connection. if you want to understand the problem correctly just do Steps to reproduce procedure to understand exactly what am i saying.

**Comment by sekritskwurl** [comment]
Just to add @3WfMeCuUqzgXBh It appears similar to https://github.com/signalapp/Signal-Android/issues/8791 it's a closed issue, but it may help.

**Comment by greyson-signal** [comment]
ed5f5adc9b64c12305efb0e3866a3f03855a27bc should hopefully alleviate this problem, but users affected by this bug will still be unable to pull down some profile images.

If you could give me the details of the devices that are affected by this (Model + OS version), that would be helpful.

**Comment by 3WfMeCuUqzgXBh** [comment]
One of the users that has the issue:

Samsung Galaxy S10+
Android 9 / OneUI 1.1
Signal 4.42.3 (4982)

**Comment by greyson-signal** [comment]
I think this has largely been resolved.
