### ISSUE TITLE
Sometimes networkConstraintObserver is not working when Signal is killed in 8.0 or 9.0 sdks

### ISSUE THREAD

**Issue by gelbertgel** [signalapp/Signal-Android#8906]
### Bug description
It hasn't trigger NetworkConstraintObserver when app is killed

### Steps to reproduce
- Huawei P20 Pro's phone has 8.0 sdk
- Huawei P20 Pro's phone close the Wifi connection
- Huawei P20 Pro's phone is writing multi messages.
- Huawei P20 Pro's phone is killed app
- Huawei P20 Pro's phone open the Wifi connection 
- It isn't triggering NetworkConstraintObserver and Signal can't send pending messages.

**Actual result:** It hasn't trigger NetworkConstraintObserver when app is killed
**Expected result:** It must trigger NetworkConstraintObserver always time
**Frequency of recurrence:** Sometimes

### Device info
**Device:** Huawei P20 Pro
**Android version:** 8.0
**Signal version:**  4.43.7

**Comment by greyson-signal** [comment]
So the `NetworkConstraintObserver` is only designed to be observing network changes while the Application is alive. If it's killed in Android 8.0 and above, it just won't be running. That's expected. 

Instead, on those OS versions, we instead schedule JobScheduler jobs with network requirements to ensure that the work gets scheduled when network is available. 

Now, what happens when the app gets killed depends on what you mean by "killed". Force stopping an app will clear any scheduled jobs, and they won't get re-enqueued until you reopen the app. Force stopping is a very destructive operation. 

However, if you're swiping to dismiss the app, that should be fine, and eventually the jobs with network requirements should be run by the system. However, that is of course up to the system. Some manufacturers have bad implementations of JobScheduler that are overly-battery-conserving and therefore delay job execution. But there isn't much we can do about that.

If you're able to consistently reproduce a situation where a network-constrained task (like a message send) isn't being sent, and you *haven't* force-stopped the app, then please provide the repro steps and debug log. Then I'll re-open the issue.

Thanks!
