### ISSUE TITLE
Signal Application Swallowing SMS

### ISSUE THREAD

**Issue by metaluks** [signalapp/Signal-Android#8922]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal application did not notify me of new incoming SMS. They did not show up in Signal after manually opening the app either. It looks as if no SMS were received at all.

This is especially annoying because you never know, whether this Bug is actually happening. In my case it could have been already hundreds of messages I did not receive and I only found out now. I only noticed this because my TAN-Messages from my banking account did not arrive at my phone. Now I am thinking about disabling Signal as default for SMS because I need to receive SMS regularly for my work.

### Steps to reproduce
I have not found a way to reproduce this issue

Here is how I temporarily solved it, though:
- Deactivated Signal as default application for SMS/MMS
- Incoming SMS started to show up in the native SMS-App again (only new ones, though).
- Reactivated Signal as default app for SMS, now it works again as intended, but how long will this last?

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
SMS would not be received and displayed inside the signal application. No sign for any incoming messages even though I sent plenty of messages from another phone to test.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
SMS should be displayed inside the signal application and there should also be a notification for incoming SMS

### Screenshots
-

### Device info

**Device:** xiaomi mi 8, model M1803E1A
**Android version:** 9 PKQ1 180729.001
**Signal version:** 4.43.8

### Link to debug log
This is the debug log after I fixed the issue with disabling and re-enabling signal as default for SMS/MMS.

https://debuglogs.org/70467c473cb5899b52162257acd59bc0909984fc0617b3857d059c3363d7a6d5

**Comment by labanskoller** [comment]
My husband had a very similar problem on a Samsung device a few days ago. I discovered that Signal was the default SMS app but it didn't have the SMS permission (he must have revoked it by mistake). That resulted in SMS messages not being displayed at all (not in the native message app either). After granting Signal the SMS permission it still didn't work. I had to switch default SMS app to the native one to be able to receive text messages again. After switching back the default app to Signal once again Signal started receiving incoming text messages.

I could reproduce the same behavior once more (granting the SMS permission after revoking it did not help). I planned reporting the bug so I made some preparations like switching system language from Swedish to English and taking some screenshots, but then I got another behavior. Signal started to receive text messages directly when granting the SMS permission. Very strange. I thought it had something to do with me changing the system language so I changed back to Swedish but it still worked.

I "closed" the Signal app between every step if I had started it but maybe it somehow continued to run in the background anyway some of the times so that could be the explanation of the different outcomes?

**Comment by gimpf** [comment]
I've the same problem, started sometime four to eight weeks ago (worked perfectly before), without any preference change since then. I'm using Signal on Android 9 on a RAM-poor Nokia 3.1+.

My workaround is: Start the Signal App (takes several seconds), only then choose to receive a TAN SMS (don't ask, banks...), then the message shows up. If the signal app is not active, the message will seemingly not be received (no notification, even after opening Signal no message).

This practically eliminates using Signal as an SMS app. :-(

**Comment by Aveheuzed** [comment]
I am encountering the same problem ; however, it seems that I receive SMS properly if (and only if) my phone is unlocked and turned on at the time I receive the SMS. If not, I don't receive the message at all, even if my friend sending the message gets an acknowledgment of receipt.

I'm on an Asus phone, however.

**Comment by HugzFluentMiny** [comment]
Same is happening here on my wife's phone.
For some reason she receives my sms' but with several other people she does not receive them when Signal is installed.

My wife uses a samsung galaxy S7 Edge.

On my phone i am unaware if i'm having this issue or not. As indicated by another user this hard to detect ...

**Comment by Aveheuzed** [comment]
I've just fixed the problem on my phone, thanks to [phone-specific troubleshooting](https://support.signal.org/hc/en-us/articles/360028198711). The trick was to allow Signal to start automatically.

Hope it does help you solve it as well; otherwise, I've found this too : [OS-specific troubleshooting](https://support.signal.org/hc/en-us/articles/360027919052)

**Comment by fummymint** [comment]
> I've just fixed the problem on my phone, thanks to [phone-specific troubleshooting](https://support.signal.org/hc/en-us/articles/360028198711). The trick was to allow Signal to start automatically.
> 
> Hope it does help you solve it as well; otherwise, I've found this too : [OS-specific troubleshooting](https://support.signal.org/hc/en-us/articles/360027919052)

Are you using an older version of Android? Apparently the feature to start an app automatically is gone on newer versions of Android.

**Comment by HugzFluentMiny** [comment]
I don't if this is related to something like that. 

Yesterday I noticed that a bunch of text messages I wrote all ended up in a pending status. 
After restarting my phone they got sent. 

I would assume that opening signal would start the service.

I should add that this concerns sending messages. I also have the same issue with receiving but maybe they are related?

**Comment by Aveheuzed** [comment]
@fummymint I'm on Adroid 6.0.1, customized by Asus (ZenPhone).

**Comment by fummymint** [comment]
@Aveheuzed 
Sadly that setting "Auto-start manager" is not in LOS 16. Do you know any alternative way to get auto start manager? Really need to fix this problem badly. I am missing a lot of SMS because of this

**Comment by nils-van-zuijlen** [comment]
This seems to be linked with #5253 which was "Spring-cleaned" in 2018.

I'm also experiencing the same issue on Wiko Y60, Android 9, Android GO, kernel 4.4.146+
