### ISSUE TITLE
Messages are not received by some contacts

### ISSUE THREAD

**Issue by Yky** [signalapp/Signal-Android#8934]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages are not received by some contacts. Only one check mark is shown after sending the message. The recipient has internet connection. 

### Steps to reproduce
- Open Signal
- Send message to single user

**Actual result:** Only one check mark appears. Recipient does not receive the message. 

**Expected result:** Messages are received if the recipient has an internet connection. 

### Device info
Sending device:
**Device:** Pixel 2
**Android version:** 9
**Signal version:** 4.43.8

**Comment by greyson-signal** [comment]
I can't do much with this report, unfortunately. It could be any number of things, and without having logs from the sender and receiver, I can't debug further. However, it's probably safe to assume that this is probably a case of delayed FCM messages, which is a known problem we're working on. Thanks!

**Comment by Yky** [comment]
@greyson-signal 
The sender runs without FCM, the receivers are Huawei phones with FCM. 

I can only provider sender logs at the moment.

**Comment by Yky** [comment]
Update: The messages are received when the receiver opens the Signal app.

**Comment by greyson-signal** [comment]
Yep, that sounds like a known issue. You can have your chat partner go to this page, which describes various phone-specific ways to omit us from battery optimizations and whatnot (which could prevent us receiving notifications). 

https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications

However, even after following those steps, there are still situations where notifications could be delayed, and I'm actively thinking about solutions.

**Comment by alcoolfire** [comment]
@greyson-signal: Would you kindly provide a link to that known issue you're referring to? All I can find is you closing issues #8934, #8841, and #8579 without solutions. If there is no open bug report, then please reopen this one or create a new one so that affected users can follow along. This problem is very badly damaging the usability of Signal.

I am aware of 3 different phones that have used Signal successfully for a long time that now fail to get notifications once they've been sleeping for a while. Although one is a Samsung Galaxy, the others are a Nexus 5 and a Moto G3, so I think its safe to say this is not a Samsung problem. No configuration changes have been made to any of these phones in the transition from functional notifications to unreliable notifications.

As an anecdote for the Nexus 5, I do not have a data plan for it, so Signal only works with Wi-Fi. For years I've been accustomed to hearing notification chimes as a I drove into my driveway and Wi-Fi came into range. Now I get nothing until I manually wake the phone (usually plugging it into the charger).

**Comment by Yky** [comment]
> Yep, that sounds like a known issue. You can have your chat partner go to this page, which describes various phone-specific ways to omit us from battery optimizations and whatnot (which could prevent us receiving notifications).
> 
> https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications
> 
> However, even after following those steps, there are still situations where notifications could be delayed, and I'm actively thinking about solutions.

I think a lot of users will not be able to locate that article page, as the app does not give any hint on what to do if messages are not being delivered. I hope this is only temporary solution.

**Comment by nicobatty** [comment]
Hi, I'm having the exact same problem on my Galaxy S10e, sometimes I only receive messages when I actively open the app.

Here is my log: https://debuglogs.org/353a3874578cf2c86525bb3ee927a57d18906bb83d8baa845ce337fabeef5c1f

I received 5 messages between 18:20 and 18:27. I opened the app at 18:42 with the 5 notifications.

Happened again a few minutes later, received first message 18:45, second message at 18:58 and opened the app at 19:07 with the 2 notifications.

There seems to be this `java.io.EOFException` before I received both the 18:20 and 18:45 first messages. Maybe that can be the cause of the issue? There is basically 0 log between 18:20-18:42 and 18:58-19:07 even though there were 7 messages I should have received on these ranges.
