### ISSUE TITLE
Signal website version no longer receives updates

### ISSUE THREAD

**Issue by Yky** [signalapp/Signal-Android#8936]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal 4.41.6 direct download version does not receive update notification for new versions. 

### Steps to reproduce
- Installed 4.41.6 via direct download from signal.org (not Play Store version)
- Several new versions are released in the meantime
- Signal does not offer any option of updating itself through the app. 

**Actual result:** User is stuck on 4.41.6 and needs to manually download new versions from the website. 

**Expected result:** There should be an option to update through the app, be it through a notification or through a button in the app to check for updates. 

### Device info

**Device:** Pixel 2
**Android version:** 9
**Signal version:** 4.41.6

**Comment by alan-signal** [comment]
Do you use a wifi connection?

**Comment by Yky** [comment]
> Do you use a wifi connection?

Yes.

**Comment by micressor** [comment]
I have exactly the same situation here.
I never saw this log message `Checking for APK update...` in the last days.
I don't use Wifi every day, but I use it regularly.
Signal v4.41.5 is dated June 7th, I haven't received an update notification since.

## Device info
Device: Fairphone FP2
Android version: 8.1.0
Signal version: 4.41.5

**Comment by hontogit** [comment]
Same issue for me.
Got stuck on 4.41.5, installed 4.43.8 manually over it some weeks ago. Now https://updates.signal.org/android/latest.json says 4.44.7 is available. But again no update is initiated by the app.

Device: HTC One M7
Android version: 7
Signal version: 4.43.8

**Comment by jtracey** [comment]
The problem is this method:
https://github.com/signalapp/Signal-Android/blob/e603162ee767d56fa16f56701cd29010f22ed22d/src/org/thoughtcrime/securesms/jobs/UpdateApkJob.java#L109
combining with this commit: https://github.com/signalapp/Signal-Android/commit/5ad02f724cbeb86fd3bb52a8687e7f20278097a8

I.e., when multi-arch APKs were added with independent versioning, the version code was multiplied by 10, plus some epsilon depending on the arch. Everywhere else in the code got a new method to check the version code, `Util.getCanonicalVersionCode()`, but that wasn't used in the APK update job. So that now, my Signal is reporting its version as 4935 (i.e., 493*10+5), but the update json is reporting `"versionCode" : 515`. If this had been found before the first update with this commit, it would have been a one-line fix to the android code, but we can't fix the android code because, well, that requires an update. :laughing:

I believe the best fix at this point is to multiply the version code in the json by 10 from now on (which should be sufficient, since after downloading your version will be greater than or equal to that number, but less than the next version, regardless of which version you're using -- similarly, there's no reason to refrain from bumping it immediately to 5150, since anyone who has 515 is already checking for some number greater than that). Until then, nobody with the website version will be receiving automatic updates.

**Comment by jtracey** [comment]
Also worth noting, that release was first made 85 days ago, which means that [in 5 days, Signal will stop working for those users](https://github.com/signalapp/Signal-Android/blob/ead6e6b2f3d053670c5d4c0992a1a0895a143465/src/org/thoughtcrime/securesms/util/Util.java#L413) :3

**Comment by nutts0** [comment]
https://debuglogs.org/c85924f2ee06c64280e77fd76ec42bd0074dac486ef990c7733be4a96856b5f4

**Comment by jtn20** [comment]
I think I've just run into this.

I originally installed the Signal APK from the website. I last updated it from 4.39.4 to 4.41.5 on 10 June, when prompted to do so. I've received no prompts since, but I see https://signal.org/android/apk/ is now advertising 4.44.7.
I've just today started getting a prompt:
"Your version of Signal is outdated
"Your version of Signal will expire in 9 days. Tap to update to the most recent version."
If I tap on that message, I get a toast "No such app found." and no update occurs.

I'm using a Fairphone 2 running Android 7.1.2.

Since it looks superficially like jtracey understands the problem, and I don't want it to stop working, I'm going to go ahead and update Signal manually.

**Comment by JanZerebecki** [comment]
I have 4.41.6 and just received the "Your version of Signal will expire in 9 days" message. No prompt to download a new apk, yet.

**Comment by greyson-signal** [comment]
@JanZerebecki Please manually close and re-open the app, and then take a debug log and post it here.

**Comment by jtracey** [comment]
The current value at https://updates.signal.org/android/latest.json is still 518 (I.e. it's still on 4.45.2). Is there something that needs to be done to update it to the latest version?

**Comment by greyson-signal** [comment]
Man, I could have sworn I updated the json before uploading, but I guess not. Just fixed it. (4.46+ will all output json with the proper version automatically -- the older one had to be updated by hand).
