### ISSUE TITLE
Recording a voice message stopped after 7 min without interaction

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-Android#8938]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was recording a voice massage in signal with locked microphone icon and it stopped after 7 min.

**Expected result:** wait till I finished my message and don't stop it.

#

### Device info

**Device:** Pixel 3
**Android version:** 9
**Signal version:** 4.43.8

### Link to debug log
https://debuglogs.org/012ba4342e90b4efeefa476f8f68d534a3b4c185f4c100421977dee57097548c

**Comment by nutts0** [comment]
This message stopped recording after 20 sec or so

https://debuglogs.org/141be04206e4dbb4589c5bba507104dbf02db3ba876c21623825ee2bfc59ed8e

**Comment by greyson-signal** [comment]
Looked at your log and saw:

```java
08-20 19:56:39.753 17477 17477 I PassphraseRequiredActionBarActivity: onPause()
08-20 19:56:39.755 17477 17477 I AudioRecorder: stopRecording()
```

We stop the recording if the activity is no longer foregrounded, and it looks like it hit the `onPause()` lifecycle event. Unfortunately we don't log `onStop()`, so that may or may not have been hit. Some common ways this might have happened are:

- You went into "app switcher" mode
- The screen locked due to a timeout (shouldn't happen when recording, but we've gotten bug reports of it happening on certain devices)
- You backgrounded the app
- A dialog box popped up (could be from us, or the system, or some other app)

Did any of these things happen, or did anything else change visually when the recording stopped?
