### ISSUE TITLE
Verification code not accepted

### ISSUE THREAD

**Issue by JuhaFin69** [signalapp/Signal-Android#8941]
### Bug description
I was registering Signal to my Android phone first time. The Signal code(textmessage) was not accepted by verification process(several trials). I got another reg. code that was not accepted either. Somehow the app passed this phase anyway and seemed to be correctly verified. Anyway when I tried to send a message to my phone(from another device) it claims that "Untrusted Identity for "*******9069": Untrusted"

### Device info

**Device:** Xiaomi Mi Max 3
**Android version:** 9
**Signal version:** 4.43.8

### Link to debug log
https://debuglogs.org/833e511e0dc63b761617b36cf39a80cffaa5aeeddbfa22faf67cf0468e5efdb7

**Comment by signaltester** [comment]
I would just like to add that the whole SMS requirement is scary. I understand that the Signal organization needs to prevent robotic signups, but there are plenty of proof-of-work solutions to that, without requiring any sort of phone system access. We should be able to run over wifi from the moment we sign up (ideally via onion routing with blacklisted IPs). Come to think of it, most of us privacy hawks would be willing to hand you some cryto coin for the privilege of avoiding SMS. It's a practical problem also, not just a security problem. What happens when for whatever reason you need to reinstall Signal outside of your wireless provider's region? Or if you lose your phone including your SIM while outside that region? It's hell. Much better to require proof-of-work to sign up, then from then on just require a password. No stupid 2FA that just creates complicated security models, unless someone opts in because they don't know how to create strong passwords. And definitely no SMS activity. I know, I know, I'm dreaming! But it would be so much better.
