### ISSUE TITLE
Verified checkmark animation makes animation look choppy

### ISSUE THREAD

**Issue by piratenpanda** [signalapp/Signal-Android#8952]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When having verified contacts the contact conversion slides in and after that the top bar gets redrawn for the verified check mark making the whole animation look choppy.

### Steps to reproduce
- Open a conversation with a verified contact

**Actual result:** 
Animation looks choppy

**Expected result:** 
Check mark is drawn before animation begins and slides with the rest

### Device info
**Device:** Pixel 2XL
**Android version:** 9.0.0
**Signal version:** 4.43.8

**Comment by alan-signal** [comment]
> Signal version: 4.34.8

Your Signal version is very out of date, dating back to February, the latest is 4.44. Please update.

Where did you install from? Play store/our website or somewhere else?

**Comment by piratenpanda** [comment]
Should be 4.43.8 of course. 4.44 has not been offered to me yet

**Comment by alan-signal** [comment]
Can you explain "Verified checkmark animation..." from the title?

The checkmark is not animated in anyway.

**Comment by mueller-ma** [comment]
The checkmark and the text "verified" don't show up instantly after opening a conversation. Since this view is `GONE`, the contact name is moved up a bit. I guess this is what @piratenpanda means with animation.
This wasn't an issue in older versions of Signal, since the phone number was always displayed. Maybe you can look into how to make the verified text appear faster or you set its view to `INVISIBLE`, so it takes space even if not shown. Then the contact name won't jump during loading.

This issue happens for me in every verified chat with Signal 4.43.8 and Android 7.

**Comment by piratenpanda** [comment]
It appears to be animated as the conversation moves in, the name is displayed right away and then after a while it gets moved upwards to make room for the verified line. Depending on the cpu load this gets rendered at very different times which doesn't look "smooth" at all.

**Comment by greyson-signal** [comment]
I think this was fixed when toolbar stuff was changed in 4.49.x.
