### ISSUE TITLE
Sealed sender problem

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-Android#8956]
Device : Google Pixel 3 (blueline) 
Android : 9 (5600800, PQ3A.190705.003) ABIs : arm64-v8a, armeabi-v7a, armeabi Memory : 31M (26.38% free, 512M max) Memclass: 192 
OS Host : abfarm865 
App : Signal 4.44.5 (5132) 

Seems my friends in the group chat can't send me sealed sender messages. Meteroid drew my attention to it. I have a linked desktop which is up to date. 

This also doesn't work on normal 1:1 conversations. 

https://debuglogs.org/9ba172230e1cbee9a75207833071c9c8bec5f88e2883598df0f192b4213a9935

**Comment by Junkii7** [comment]
This issue has happened in the past, we were unable to pin the bug down but it was discussed on the forum
https://community.signalusers.org/t/sealed-sender-may-not-be-working-on-all-platforms/5210/8

**Comment by Meteor0id** [comment]
I checked our one on one history which was just one or two messages. Turns out sealed sender has worked for Nutso in the past.
![Screenshot_20190729-143124](https://user-images.githubusercontent.com/34976212/62048840-26b20d00-b20e-11e9-86a3-9934a391dc40.png)

Nutso might be able to narrow down the moment by checking more of his messages.

**Comment by Junkii7** [comment]
A group message sent to Nuttso at 19 July 2019, 8:12:57 pm GMT+10:00 shows that sealed sender was not working at that time.

**Comment by Meteor0id** [comment]
Nutso has tried to narrow it down by going through his conversations. We figure his sealed sender stopped working between march 21st and June 1st.

From my conversation with him I do not see any safety number change since at least March 21st when we started our conversation up until today.

**Comment by greyson-signal** [comment]
Here's a relevant bit from your log:

```java
2019-07-26 15:14:04.698 GMT+02:00 I Job: [78e7f0d6-f6a4-42d0-acc2-31bfc63c564d][RefreshUnidentifiedDeliveryAbilityJob] onSubmit() (Time Since Submission: 373 ms, Lifespan: Immortal, Run Attempt: 1/10)
2019-07-26 15:14:04.698 GMT+02:00 D JobSchedulerScheduler: onStartJob()
2019-07-26 15:14:04.698 GMT+02:00 I JobRunner: [78e7f0d6-f6a4-42d0-acc2-31bfc63c564d][RefreshUnidentifiedDeliveryAbilityJob][1] Running job. (Time Since Submission: 385 ms, Lifespan: Immortal, Run Attempt: 1/10)
2019-07-26 15:14:04.698 GMT+02:00 D WakeLockUtil: Acquired wakelock with tag: signal:78e7f0d6-f6a4-42d0-acc2-31bfc63c564d
2019-07-26 15:14:04.699 GMT+02:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-07-26 15:14:04.699 GMT+02:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/profile/+*********64
...
2019-07-26 15:14:05.014 GMT+02:00 I RefreshUnidentifiedDeliveryAbilityJob: Set UD status to: false
```

If we're setting UD to false, that means that there's no unidentifiedAccess set on your profile, or there was some other parsing exception. We'd log something if there was an exception, so that means we're getting back no unidentifiedAccess for your profile. I'm investigating as to why that would be.

To start though, can you let me know what version of desktop you're using?

**Comment by greyson-signal** [comment]
Did some debugging, and we were able to discover that there was a bug in desktop where it didn't properly declare support for Sealed Sender when you re-link a device. We can't send Sealed Sender messages unless all linked desktops support it, and even though yours does, there was a bug in it reporting it. That's getting fixed and will go out in the next desktop release.

In the meantime, if you want to get Sealed Sender up and running faster, you can unlink your desktop instance(s). If you want to use desktop, you'll have to do a fresh install of the desktop client. Or wait for the desktop update, which should fix all of this invisibly without any action required from  you :)

Thank you for all of the detailed information! It makes the debugging process much easier.

**Comment by Meteor0id** [comment]
Thank you for looking into this matter within such short notice, and thank you for writing back to us explaining what was going on. It feels flvery satisfying to discover a bug, narrow it down and hear that it has been found and solved. 
Thank you.

**Comment by Junkii7** [comment]
Thank- you Greyson and team, this bug has haunted me since december 2018 when I first had a glimpse of it.

**Comment by nutts0** [comment]
I have this problem with an other signal pixel 3 phone where I can't get sealed sender working with one of the contacts in the group chat. This signal instance was never connected to a desktop client and we are both running the latest version. 

The strange thing is it seems he is sending sealed to me.

https://i.imgur.com/DNRiJSi.png

https://i.imgur.com/SEL4mWP.png

My debug log:

https://debuglogs.org/fa5055c79877f1c45c471a5452786daa9129f9c20b5f2bf3ebbbd116e8fb8413

**Comment by greyson-signal** [comment]
Looking at your log, I can see a situation where you're sending to a group of two: you have an accessKey for one, but not the other. I'm going to assume that this is the group you're having trouble with.

```java
2019-08-07 21:04:28.025 GMT+02:00 I PushGroupSendJob: [e83d772d-422f-4293-a8ac-6326336520fb][PushGroupSendJob] Sending message: 2376 (Time Since Submission: 39 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
2019-08-07 21:04:28.025 GMT+02:00 D PushSendJob: Certificate is valid.
2019-08-07 21:04:28.026 GMT+02:00 I UnidentifiedAccessUtil: Their access key present? true | Our access key present? true | Our certificate present? true
2019-08-07 21:04:28.026 GMT+02:00 I UnidentifiedAccessUtil: Their access key present? false | Our access key present? true | Our certificate present? true
```
I can also see where you fetched someone's profile, and determined you couldn't send a sealed sender message to them. I'm going to assume this is the affected individual.

```java
2019-08-07 21:04:07.215 GMT+02:00 I RetrieveProfileJob: Marking recipient UD status as disabled.
```

We print that log if they don't have an accessVerifier or if you don't have their profileKey. I'm assuming that because they can send sealed sender messages, they have an accessVerifier. Instead, it must be the case that you don't have their profile key.

What's likely happened is that this user didn't share their profile with the group, but you did, meaning that they can send you sealed sender messages but you can't send them back.

The user probably has a banner at the top of their group asking them to share their profile. Have them click that or have them add you to their contacts. The next message they send to you will have their profile key in it, which will let you start sending sealed sender messages to them.

If that doesn't help, please get me a debuglog from their device. Thanks!

**Comment by Meteor0id** [comment]
@nutts0 before you have your contact share his profile with you in any way, you might also ask him to accept sealed sender from unknown contacts (there is an option for that in the menu). That should also solve the issue. You might want to test that first because it can be disabled again, a shared profile can not be unshared.
