### ISSUE TITLE
Outgoing call sound doesn't differentiate between dialing and ringing 

### ISSUE THREAD

**Issue by osmaa** [signalapp/Signal-Android#8981]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When making an outgoing Signal call, the status screen will say DIALING while sound output is an outgoing ringing audio. This starts immediately, even before the recipient device has been contacted. This is misleading, because the ringing tone indicates the recipient's phone is also ringing - even if it is not. 

### Steps to reproduce
- put phone A in airplane mode or otherwise disconnect from network
- call phone A from phone B
- observe phone B using audio ques indicating phone A should be ringing 

**Actual result:** outgoing phone B audio ques lead caller to believe recipient does not respond to call, despite call never even reaching recipient's phone A
**Expected result:** phone B fails from "dialing" state to "recipient unreachable" in both visual and audio response

### Device info

**Device:** oneplus 6T
**Android version:** 9
**Signal version:** 4.44.7

**Comment by u32i64** [comment]
This is not a bug report, but a feature request/discussion topic, since the separate `connecting` sound has been intentionally removed. See the already existing [Submarine sound gone… ring sound before connection made](https://community.signalusers.org/t/submarine-sound-gone-ring-sound-before-connection-made/6314?u=u32i64) topic on the forum.

Quoting [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md):

> ### The issue tracker is for bugs, not feature requests
>
> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. Bug reports should only be submitted for existing functionality that does not work as intended. Comments that are relevant and concise will help the developers solve issues more quickly.

**Comment by greyson-signal** [comment]
This is currently the intended behavior.

**Comment by attila-lendvai** [comment]
it just doesn't make any sense. even the GSM system is quiet until the callee's phone actually begins ringing.

signal's behavior is super confusing for the users, and there's not enough time in the entire universe to teach all my peers to keep staring at the phone and wait until it prints "Ringing..." and ignore the ringing sound in the speaker **BECAUSE MY PHONE IS NOT RINGING PRIOR TO THAT**.
