### ISSUE TITLE
sending SMS from qr code fails

### ISSUE THREAD

**Issue by wolfgangrupprecht** [signalapp/Signal-Android#9026]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the camera and pointing it at a QR code for sending a message contained in the QR code to the telephone number in the QR code Signal ignores both the provided phone number and the provided text to send.   The normal Android messenger will correctly populate the phone number and message fields.

### Steps to reproduce

**Actual result:**  Signal pops up but the provided phone number and text are ignored
**Expected result:** Signal pops up with phone number and text fields populated according to the QR code.

- navigate a desktop browser to http://goqr.me/qr-codes/type-qr-sms.html
- run the default android camera app
- point the camera at the first QR code
- note that the camera app will pop up a small clickable line at the bottom with the telephone number from the QR code.
- click the telephone number line
- when signal is the default SMS app clicking the link will open up signal but will not 
populate either the telephone number or the text message contained in the QR code.
- when the default android messenger is the default SMS app the fields are populated 
and all the use has to do to send the message is click on the ">" symbol to the right of the text message.

### Screenshots

This is what the messenger app does with the above qr code example.
![image](https://user-images.githubusercontent.com/25571200/64650410-fa280e00-d3d3-11e9-9815-9016bb0b95fe.png)

### Device info

**Device:** Google Pixel 3xl
**Android version:**  version 10  patch level Sept 5, 2019
**Signal version:** 4.47.4

**Comment by cpmcgrath** [comment]
I have just noticed this too. While I'm normally on the side of not thinking Signal needs to support anything but the basics of SMS, I do think this should be considered a critical feature because it's becoming used quite a bit for COVID contract tracing. Basically, yesterday I went to a restaurant and they ask you to sign in by scanning a QR code - basically the QR code tells it to open the SMS app with the string:

```
+61412345678?body=Name: 
E-mail Address:  
```

Signal basically took the entire string and put it in the to field, which results in not only not having the template, but having the to address incorrect, so you can't even write it yourself.

It's annoying because to be honest, this is one of the best & simplest digital solutions I've seen for COVID tracing. I know that support for SMS & non-encrypted channels is a touchy subject in the community - but it's the feature that made me be comfortable installing it on my parents phones, and I can see this being a huge pain point for them.
