### ISSUE TITLE
Getting "message encrypted for non-existing session" and "bad encrypted message" messages

### ISSUE THREAD

**Issue by Maximus778** [signalapp/Signal-Android#9031]
- [x ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------
I keep getting error messages which say  "message encrypted for non-existing session" and "bad encrypted message" in the Android app

- I saw some people said this happens when using the desktop app but I have only used Signal on this phone (Android) and have never used the desktop or any other devices
- I checked linked sessions and don't have any other
- When I send text messages to other users, I don't even see the second check mark which shows the message is delivered even when I know it has been delivered
- I have also tried hitting reset secure session several times and it still keeps happening
- This is NOT happening with just one contact but with all my messages

Is this a bug or do I have malware on my phone? Is there any way to check if it's malware?

Thanks
### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Pixel
**Android version:** 9
**Signal version:** 4.43.8

**Comment by securitybryan** [comment]
I am seeing the same thing on Android and my conversation partners are being bombed with the same messages from me.  I typically receive 20-30 messages in one go.

**Comment by bme13** [comment]
This morning I got a Bad encrypted message in a 1 on 1 conversation. This was due to a message she posted in a group. I did not receive that message in the group however it was received on my wife's phone (she is also part of that group) On my wife's phone there were also 2 'bad encrypted messages' of that same person in the 1 on 1 conversation with that person. 
I've asked that person to create a debug log and after some time I've received a bad encrypted message again. Assuming she did send it I did a 'Reset secure session' at that point I did receive the group message and a new message. 

debug log of my phone (no group message, one bad encrypted message in 1on1 conversation):
https://debuglogs.org/4a05b9dfe2da3d7734dd3a79987fef8f3eb8602f53b53a0a61504985489caa52
debug log of wife's phone (group message received, two bad encrypted messages in 1on1 conversation):
https://debuglogs.org/db03a4fe16db82526ef5313edec9c88daab18da6cd01a7343dd9dfa7029605f4
debug log of sender:
https://debuglogs.org/4421c5ffe05e0444abd079b159d02d08a32f9094799bcba7521c58c40b7385a1
debug log of my phone after restore secured session:
https://debuglogs.org/ca67c51ffe73a5928253f017abe4a6c637c38d23c32d74cb29236a05c1543a4e

Currently I'm not sure if it is completely fixed since the last couple of messages only have one tick again. In the debug log of the sender I've noticed quite a few blocked threads. Seems some kind of deadlock. Would it help if she restarts her phone?

**Comment by bme13** [comment]
Resetting the secure session didn't work. Also restarting the phone didn't solve the issue. Currently I only receive a Bad encrypted message if she sends something and if I send something I only see one checkmark. We also tested both on wifi and by data. That also didn't work. Messaging through Whatsapp works so there seems to be a data connection. Is there anything else to try?
