### ISSUE TITLE
Messages appear in wrong order

### ISSUE THREAD

**Issue by amichair** [signalapp/Signal-Android#9088]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Messages on an android device appear out of order. The chat was performed on the synced desktop, in which the order is ok, but on the android phone they came up in mixed order.

Looking at the message info on the android device for the message and its surrounding ones:

The message before (sent by me) - Sent Oct 10, 2019, 11:55:32 AM GMT +03:00

The problematic message (received) - Sent Oct 10, 2019, 1:23:37 PM GMT +03:00, Received Oct 10, 2019, 1:24:55 PM GMT +03:00

The next message (received) - Sent Oct 10, 2019, 11:55:35 AM GMT +03:00, Received Oct 10, 2019, 1:37:52 PM GMT +03:00

The next message (received) - Sent Oct 10, 2019, 11:55:41 AM GMT +03:00, Received Oct 10, 2019, 1:37:54 PM GMT +03:00

The next message (sent by me) - Sent Oct 10, 2019, 11:56:23 AM GMT +03:00

I don't know why the long delay before receiving the messages on the phone, but in any case they seem to have been received on it out of order and displayed correspondingly, which is wrong.

I don't know enough about the signal protocol to tell if the problem is in the sender, the server, or the recipient, but it seems in this case if the messages were ordered according to their sent timestamp, it would be correct. Or using an increasing sequence number generated for each message in a conversation, so clock changes/differences won't matter either. Or however it is other chat programs have been doing this for years... haven't seen this kind of out-of-order problem in any chat program before.

### Steps to reproduce
It doesn't happen all the time, though this is not the first time I've noticed a message in the wrong order. I don't know what causes it on some messages but not on most.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Messages appear in wrong order.
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Messages should appear in the correct natural order, which should be the same on all devices.

### Device info
Android 9 phone, Signal 4.47.7
Desktop running Kubuntu 18.04, Signal 1.27.3

**Comment by Viperized** [comment]
It just happened to me, I don't know if it's related or do I need to open a new ticket.

Phone was set to airplane mode during several hours. During this, a contact sent me 6 messages. When I took phone out of airplane mode, I received them all at once.

One of them seemed out of context, but by analyzing the timestamps I could immediately see why.

Messages were like this with timestamps:
Message A
3:45
Message B
3:45
Message C
3:46
Message D
3:56
Message E
3:46
Message F
3:57

Message E is clearly the one out of order. Upon inspection, these were the times they were sent, alongside the time received:

Message A
3:45 (6:30:11)
Message B
3:45 (6:30:11)
Message C
3:46 (6:30:11)
Message D
3:56 (6:30:12)
Message E
3:46 (6:30:12)
Message F
3:57 (6:30:12)

Messages are all marked with using sealed sender.

Here's the debug log:
https://debuglogs.org/3d5298fc8237a29fe36f1f73c9293b293b4db54b0d13c8aad5e116d0ab39ad38

**Comment by Jawshy** [comment]
I've also experienced the occasional discrepancy between the order of messages on Android and Debian-based Linux desktop. The messages from both parties in the screenshots were sent using our Android devices. I've noticed that the issue typically occurs when both parties send a message within a very short amount of time of each other. 

### Screenshots
![Signal-Android-messages-2020-02-21](https://user-images.githubusercontent.com/10876578/75036250-5629af00-54a9-11ea-889c-23f8a54b40b5.png)
![Signal-desktop-messages-2020-02-21](https://user-images.githubusercontent.com/10876578/75036257-5a55cc80-54a9-11ea-9786-3ceb8b44db1a.png)

### Device info
Device: Google Pixel 3a XL (aosp_bonito)
Android version: 10 (2020.02.07.19, QQ1A.200205.002.2020.02.07.19)
Signal version: 4.55.8 (Android)
App state: Signal messages and calls registered, linked device
Link to debug log: I did not capture a debug log immediately after the bug occurred. 

Device: Ubuntu 19.10
Signal version: v1.30.1 (Desktop)
App state: Contacts imported
Link to debug log: I did not capture a debug log immediately after the bug occurred.

**Comment by itkfm** [comment]
Happening on a daily basis here.
It's awefully confusing.

Occurs when freshly connecting to the internet – which can happen when one has poor signal or when one has been offline for a while and re-enables mobile data or WiFi.

Device: moto g(7) power
OS: Android 9
Kernel: 4.9.112-perf+

Have a look at the timestamps ;)
![signal-attachment-2020-03-11-133551_001](https://user-images.githubusercontent.com/53079668/76417639-82946500-639d-11ea-99fc-88fa37c30e57.png)
![signal-attachment-2020-03-11-133551_002](https://user-images.githubusercontent.com/53079668/76417642-832cfb80-639d-11ea-8386-6570aeba8774.png)

**Comment by Ke1i** [comment]
Same here.
When I go online (it's not practical for me to be online 24/7) I receive Signal messages which are out of order based on the time they were sent.
This can be confusing for a conversation thread. The screenshot below is an example. 

Device: Samsung Galaxy J7 Core
Android version: 9
Signal version: 4.57.2

![20200331_140223](https://user-images.githubusercontent.com/20503185/78021901-b3443a80-735c-11ea-8a0b-e69865a3b2d2.jpg)

**Comment by TheBrick** [comment]
It happens to me too all the time, even in one-on-one conversations that I'm actively engaged with. I can understand the current design (sorting by received timestamp) is preferred in some extreme cases, but I feel mostly everyone would agree that a different ordering is preferred in a trivial case such as this one:

![](https://i.imgur.com/Q09IrII.png)

**Comment by vertigo220** [comment]
This has happened to me as well when texting with another Signal user, Android to Android. There was confusion, and when I had them send a screenshot of the conversation, it was jumbled.

**Comment by greyson-signal** [comment]
There was recently work done on the server around fixing issues where, when the device is coming back from being offline and processing a lot of messages, it was possible for some messages to be received out of order. @vertigo220 how recently did you see this problem, and can you provide logs?

I've mentioned this in other threads, but I'll reiterate that the reason we render messages in received order is because new messages should always appear at the bottom of a conversation. We can't create situations where messages are randomly inserted somewhere back in time, because they simply won't be seen. And of course it opens up avenues for other, more malicious, scenarios.

**Comment by itkfm** [comment]
> We can't create situations where messages are randomly inserted somewhere back in time

The current batch of messages that is about to be appended could be sorted, though.

**Comment by vertigo220** [comment]
I don't remember, probably a couple months ago, give or take, and so definitely no logs.

As or using received timestamp vs sent, I understand the reasoning, and can't fault it, but why not do something like this:

Messages sent:

A
B
C
D
E
F

Order messages received:

A
B
E
F
D
C

Order messages displayed:

A
B
C*
D*
E
F
D**
C**

*Colored or otherwise marked to indicate they were inserted AFTER following messages
**Colored or otherwise marked to indicate they were received out of order, to both ensure they're seen and to indicate to the user that they are placed in proper order above. They could also be made to take the user to their in-order instance when tapped. Of course, the best way to do this would have to be determined, such as tapping either would go to the first one, or would ask whether to go to the tapped one or the earliest one, etc.

Another option would be:

A
B
C
D
E
F
***Message to notify that new messages have been received at this time that were sent earlier in the conversation, which when tapped would bring the user back to them. Essentially, same thing as above but instead of showing the messages twice, which could be even more confusing, especially if they're out of order with each other (D then C instead of C then D), it just shows a simple warning to alert the user and take them to the changes.

I recently tried out the delete for all users feature for the first time the other day, which says it alerts them that you deleted the message. I'm not sure what this looks like on their end, but I would assume the functionality of that alert would be similar to how this would be implemented. And, as a side note, I was using it to try and clean up the chat of a bunch of no longer needed messages from a lot of back-and-forth with somebody doing some testing of other stuff, to declutter the conversation, figuring I'd clean up both at the same time, but when I found it didn't actually delete the messages, on either end, I realized it would just be more work, because we'd both still have to go through and delete all the messages alerting that messages had been deleted. It'd be a lot easier if there was a way to just delete all those messages automatically (well, semi-automatically, since obviously it can't be fully automatic since the other user needs to be aware of it).

**Comment by greyson-signal** [comment]
The solution is to ensure messages are sent and received in the correct order, not to change the rendering. 

> I don't remember, probably a couple months ago, give or take, and so definitely no logs.

This likely happened before the server fixes. Let me know if it happens again, thanks!

**Comment by greyson-signal** [comment]
In fact, given that the server changes hopefully solved most of these cases, I'm going to close this issue. If a new instance comes up, feel free to comment/reopen.

**Comment by Jawshy** [comment]
I recently had one instance of messages appearing out of order on mobile, but on desktop they were in order. I didn't see the message from the group member in brown until sometime after I had sent my message. 

### Screenshots
![signal-mobile-messages-out-of-order](https://user-images.githubusercontent.com/10876578/102563508-2a0ca800-4125-11eb-8f9e-ab20f1b9d9f4.png)

### Device info
Device: Google Pixel 3a XL (aosp_bonito)
Android version: 11 (RQ1A.201205.003.2020.12.12.03)
Signal version: 4.? (Android)
App state: Signal messages and calls registered, linked devices
Link to debug log: https://debuglogs.org/5d785931b0a38ca681afc1075cdba94db378a06e8c0db99d38f257454cda7578

Device: Ubuntu 20.04.1 LTS
Signal version: v1.39.4 (Desktop)
App state: Contacts imported
Link to debug log: https://debuglogs.org/969bdcffe7092f72f606c743075273659f64d77cf95bb03b1a3a50445b287e32

**Comment by vertigo220** [comment]
Not sure if it's related, but another issue I've had occasionally, including a couple times in the past four or five days, is that I'll send messages and for hours they won't show as delivered, but the last time it happened I had the other person send a screenshot and it showed that it received them at the time I sent them. I'm not sure if it actually did and mine was just not reflecting that fact, or if the messages were actually delayed but then showed the sent time instead of the received time. I was going to wait until it happened again to try and get more info on it then report it as a separate issue, but I figure it might be worth mentioning here.

**Comment by greyson-signal** [comment]
@Jawshy That appears to be less of an issue of inbound messages appearing out of order, and instead an issue where inbound messages were taking a long time to process (even though they were in order). We have work planned this quarter to track down those issues.

**Comment by NilsIrl** [comment]
This issue is still happening. Somewhat sent me a picture followed by some text and both on desktop and android I received the messages in the incorrect order (text message and then image)

**Comment by samuel-lucas6** [comment]
@greyson-signal This still regularly happens for me, so I would argue this needs to be reopened. It's the worst bug I've experienced with Signal by far because it makes some conversations near unreadable on mobile and screws up the backup.

**Comment by gediminasel** [comment]
Same issue here. I was chatting with my friend using Windows app. When I opened Signal app on Android, it downloaded all friend's messages first, and then all mine. All replies display Original message not found error. https://debuglogs.org/0c1ea1a2a266885b2c904efac78d6d43ce5dbfba5932125bc6971741a7180487

**Comment by greyson-signal** [comment]
@gediminasel @samuel-lucas6 I think I actually addressed this problem in 5.28.8, which is currently in beta. Can you let me know if that fixes the issue for you?

**Comment by samuel-lucas6** [comment]
@greyson-signal That's great to hear. Interestingly, I'm currently on v5.26.1 on desktop and v5.28.5 on Android, and I haven't had a problem recently. I think my issue may have been cleared up by a CalyxOS update that fixed some notification bugs. That problem was likely blocking Signal from syncing properly before. I'll let you know if I encounter it again.

**Comment by artheus** [comment]
I am still experiencing this issue. The messages are not sorted by the sent/received dates. But rather the time they actually appear in the app. Which for some reason is often very much delayed.
In my case I use Signal only for regular texting (SMS), as I do not have any contacts willing to use Signal.

**Comment by Komma-5** [comment]
My friend on android still has this or a similiar issue. Received and sent new messages are slipping up/backwards in the chat
