### ISSUE TITLE
Archiving an unread conversation on recipient side is marking it as read on the sender side

### ISSUE THREAD

**Issue by itmaciek** [signalapp/Signal-Android#9147]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
If both contacts have read receipts enabled and one party is archiving messages without reading them, the other side sees it as read.

### Steps to reproduce
Phone1: enable read receipts
Phone2: enable read receipts
Phone1: send a message to Phone2
Phone2: archive a conversation without reading it
Phone1: message is visible for sender as read by the recipient (read receipts check marks)
Phone2: undo archive
Phone1: message is visible for sender as read by the recipient
Phone2: message is visible as unread

**Actual result:** message that was never read is visible for sender as read by the recipient
**Expected result:** unread archived messages should not be visible as read for the sender

### Device info
**Device:** Pixel 3 XL
**Android version:** 9.0
**Signal version:** 4.49.13

**Comment by vahnrr** [comment]
Can't reproduce on Android 9.0 and Signal 4.19.18

**Comment by greyson-signal** [comment]
This behavior is intentional and consistent across platforms.

**Comment by christhomas** [comment]
Why is it intentional and why it is logical that unread messages are marked as read? There is no logical connection between archiving a conversation and marking unread messages as read

**Comment by okdistribute** [comment]
This is an attack vector as I recently had a stalker text me a bunch and I archived the conversation because I didn't want to see it, but I didn't want him to know I had read the conversation... so then he thought I had read it and it increased his intensity in sending messages.

**Comment by jerkey** [comment]
This is an unreasonable conclusion to this issue and needs to be re-addressed.  I think that's obvious.  Just because a behavior is "consistent across platforms" doesn't mean it's correct.  If there is another forum where this issue is being discussed or needs to be brought up, I would love a link.  Otherwise I think this issue should be re-opened and addressed as soon as possible.

**Comment by christhomas** [comment]
Consistency across platforms is LITERALLY the least worthy attribute you should have when considering whether this functionality is good or bad. 

This functionality is bad, it's broken, it's outright wrong. There is no debate to be had about that aspect, archiving a conversation should never conflate whether that conversation is read or not. Those are two separate issues. The fact that they are conflated together is itself a mistake.

So the fact that other platforms do this, just means that this mistake has been made on other platforms too. That isn't a reason to compound this mistake by doing it on every platform. If this mistake was done on 3 platforms out of 5, then implementing this on the remaining 2 platforms isn't the solution. the solution is to fix the problem on the 3 platforms which are broken.

I'm a software engineer, the fact that this decision was made by another software engineer, is incredibly disappointing.

**Comment by bknie1** [comment]
This is toxic and an invasion of privacy. Has this been addressed?

**Comment by kiplingw** [comment]
I agree with the above comments. The whole reason why you archive a message you didn't read is because you don't intend to. It makes no sense to notify the sender that it was read when it wasn't.

**Comment by youngestdj** [comment]
This needs to be addressed imho. Unread messages should never be marked as read no matter what.

**Comment by christhomas** [comment]
It’s effectively leaking unwanted status information. That’s a security hole to glean information about the recipient.

**Comment by dustball** [comment]
SERIOUSLY.  If a woman was in charge of this issue, the bug would not be closed "as designed".

**Comment by trysten** [comment]
@greyson-signal this issue needs to be re-opened. unread messages shouldn't be marked as read.

**Comment by greyson-signal** [comment]
Hey folks, I was prompted to revisit this thread. I looked into it more, and it _was_ intentional to mark things as read when you archive them. However, Signal is a very old app, and archiving threads actually predates "read receipts", where read status is shared with your chat partner. That means that while it was intentional, that decision was made back when the concept of "unread messages" was completely isolated to your device.

With the read status of messages being shared with your chat partner by default, I agree with everyone else in this thread that we should not be marking messages as read when archiving them. I've made the change in 7.24.1. Thank you very much for all of your feedback, and I apologize for any inconvenience in the meantime!

**Comment by vyeol** [comment]
This is amazing news, and thank you for the explanation!

Will the iOS version be fixed in this regard, too?
https://github.com/signalapp/Signal-iOS/issues/5702

**Comment by theschweitz** [comment]
@greyson-signal please acknowledge. this issue needs to be fixed in the iOS version ASAP.

**Comment by vyeol** [comment]
Resolved in iOS, too:

https://github.com/signalapp/Signal-iOS/issues/5702#issuecomment-2984725669
