### ISSUE TITLE
After update not able to send/recieve messages (Rate limit exceeded / Unable to parse entity)

### ISSUE THREAD

**Issue by swevic** [signalapp/Signal-Android#9165]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

### Bug description
After update it is not possible to send or receieve messages. First I thought it was that the sending mechanism maybe was updated because the firewall (AFWall+) was blocking packets to Signal (aws) servers from "Linux kernel", but the problem continued after disabling the firewall. (Also not able to send/receive calls, but a "missing called" notice is received by the other part.)

### Steps to reproduce
- Update Signal 4.47.7->4.49.15
- Start Signal again (and wait for "Signal update", I guess some database update)
- (Potentially block Signal ("Linux kernel" process) from accessing servers for a while when trying to send some secure messages,and then unblock everything)
- A: Send a secure message to someone
- B: Secure calling someone (not relayed call)

**Actual result:**
A: Message not delivered. Only a rotating dotted ball next to the messages (tried several contacts).
B: Just Dialling / Establishing Signal call - but a Missed call notice is received by the other part.

(Because of the "Rate limit exceeded" in the log I also tried turning off all internet connection for half an hour and tested again, if the servers thought it was spam, but no difference.)

**Expected result:**
A: Message delivered to Signal server at least.
B: Call gets connected.

### Device info
**Device:** Oneplus 6
**Android version:** 8.1.0 (rooted)
**Signal version:** 4.49.15

### Link to debug log
https://debuglogs.org/4c898a9faf0b3196f2ec48489e9ae3a06bdbfaa1093ada73560ea73f578c1b75
(The debug log is from the device newly restarted with first scenario A and then B)

After the update it is no longer possible to backup in Chats & Media (tried resetting the backup keys also), and nothing is shown about that in logcat (should make another bug report about it maybe). Therefore I would not want to reinstall, got about 100k messages in ~300 secure conversations.

**Comment by greyson-signal** [comment]
We have a system for "application-level migrations" in the app. These are jobs that have to be completed before any other jobs in the app can be run (jobs like message sending). One of those migrations involved refreshing which of your contacts are on Signal.

However, you have been rate-limited and are thus unable to do a contact sync. I don't know how you got into that state originally (maybe we were making partially-failed requests before because of your firewall?), but that's the state you're in now. You need to be able to get out of the rate-limited state before you can do the sync and get back into a good state. That just takes time.

If you need a quicker solution, I might be able to get you a build to get out of this state. Email me at greyson@signal.org.

**Comment by swevic** [comment]
Ahhh ok! Thank you. Yes, suddently it started working a few minutes ago. About 8h after the update. So problem solved for me :) Was it because I have a lot of contacts? (close to 10k) I'm used that it takes some time.

(A bug/wierd thing related to this maybe: New people on Signal can send me encrypted messages and I can see the safety number and so on, but I cannot reply yet, only "Invite to Signal" until the contact sync is done which usually happens after a few hours.)
