### ISSUE TITLE
"Unlock Signal" PIN screen is white in dark theme

### ISSUE THREAD

**Issue by jpds** [signalapp/Signal-Android#9179]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description

The "Unlock Signal" screen for a PIN with the Dark theme is white.

### Steps to reproduce

- Delete fingerprints
- Have PIN to unlock phone set
- Have screen lock in Signal settings set
- Lock Signal
- Try to unlock Signal
- See bright white screen

**Actual result:** Can't take screenshot as Android blocks this.

### Device info

**Phone:** Nokia 7.2
**Android version:** 9
**Signal version:** 4.49.18

**Comment by mueller-ma** [comment]
> Can't take screenshot as Android blocks this.

Go to Signal settings => Privacy => Disable "Screen security".

**Comment by jpds** [comment]
@mueller-ma I know about that setting, Android still blocks the screenshot of the PIN entry setting (for good reason).

**Comment by alan-signal** [comment]
![image](https://user-images.githubusercontent.com/48254818/68767719-2daf3080-05ef-11ea-8a43-dad19f643eab.png)

> Android still blocks the screenshot of the PIN entry setting (for good reason).

The reason Android blocks this screen even when the setting is off and also the reason it is white is that this screen comes from Android.

We delegate pin entry to an Android service `KeyguardManager` this is because this is your devices pin, and we can't let you enter it into our app, and we couldn't verify it even if we did collect it ourselves.

In addition, I can't see any way of telling it to be dark at the time we request it I'm afraid.
