### ISSUE TITLE
Video autoplay on forwarding

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#9204]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Video starts playing (with sound) on forwarding to an other contact.

### Steps to reproduce
- receive a video
- forward it (right-arrow on the top)
- choose an contact

**Actual result:** Video plays (with sound) and has to be stopped manually by the pause button.
**Expected result:** Preview screen of video and text compose should be shown with video on pause.

### Device info

**Device:** Sony XZ2c
**Android version:** 9
**Signal version:** 4.49.18

### Link to debug log

Propably not needed but can be attached if requested.

**Comment by greyson-signal** [comment]
So we did start doing this intentionally when we added in-app video recording, so you could take a video and see it play back immediately. However, I understand why this isn't desirable in all circumstances where you're sending a video. I'll think on this some more :)

**Comment by WailB** [comment]
Is there any update on this issue? I am a new user and I find this issue annoying and I am sure others cause other new users to leave the app. There is also stuttering at the beginning and sometimes it will continue playing even after hitting the send button.

**Comment by grandchild** [comment]
Maybe preview-play, but always without sound first? Family members have mentioned this to me several times, as a potentially embarrassing feature -- think on-public-transport.

**Comment by Alexees** [comment]
I was looking for a solution to this for the same reason. Annoyance. It's something I wouldn't expect. By the time I share a video I already know what it's content is, otherwise I would not have chosen it.
Auto playing it is of no help in terms of picking a different one either. I have to go back and choose again, meaning I have to know again what I want to share.
The only reason I could think of previewing it during the sharing process is when I want to edit it, crop it or something.
In addition, I cannot share something silently cause every time I do my phone starts playing sound on full volume, unintentionally, attrackting my kids who would not have noticed if it would have been a picture.
Please give us the possibility to disable that.
