### ISSUE TITLE
Random issue to send SMS

### ISSUE THREAD

**Issue by tonio4open** [signalapp/Signal-Android#9268]
Dear team,

I use Signal since years, but only for secure messages. After a factory reset of my smartphone on Monday, I decided to use Signal for both secure messages and regular SMS.
But I have a random issue with the SMS sending.

### Bug description
Sometimes, after the boot of my smartphone, it's not possible to send SMS. The little dotted wheel rotates rotates rotates...

### Steps to reproduce
Maybe to have my smartphone ;-)

### Workaround
Reboot once or twice the smartphone.

### Device info
Device: Samsung Galaxy S4 mini GT-i9195i
Android version: 7.1.1
Signal version: 4.50.6

### Link to debug log
https://debuglogs.org/a8f422d1e1b1176e73e344b54224b2af9d4d68c6177f28783c97b2e29a462805

Thanks for your help.

Antoine

**Comment by svrouwenvelder** [comment]
@tonio4open 
Change the beginning of your post to shows that you have passed all 4 steps for bug reporting ;) 

----
This is not a random issue, I experience the same.  I can only send a SMS when I'm connected to the WiFi.

**Bug description**
When sending a SMS trough signal the little dotted wheel rotates rotates rotates... Once I am connected to the WiFi the SMS will be send (note I am 100% sure it is an SMS, because the end user does not have signal). Note: I have no cellular data.

**Steps to reproduce**
Do NOT have any GAPPS installed on your system. Use signal (4.50.5 or higher) and try to send an SMS while you are not connected to the WiFi or cellular data. 

**Workaround**
N/A. Reboots did nothing for me.

Device info

Device: OnePlus 3 (A3003)
Android version: 9 (NLOS: Lineage OS derivative)
Signal version: 4.51.6

**Comment by tonio4open** [comment]
In fact, link with #9030

**Comment by tonio4open** [comment]
Hello svrouwenvelder,

Please report your bug in #9030 (in fact, the same issue).

Thanks.

Antoine

Le 11/12/2019 à 22:34, svrouwenvelder a écrit :
