### ISSUE TITLE
Setting Note to Self color as gray makes user icon brown

### ISSUE THREAD

**Issue by CaviaPorcellus** [signalapp/Signal-Android#9280]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Changing the "Note to Self" color changes the user icon's color at the top left of the conversations screen. This works for all the colors save one: if gray is selected as the color, the icon instead turns brown.

### Steps to reproduce
- Open Note to Self.
- Tap Note to Self icon at top left.
- Change color to gray.

**Actual result:** 
Color of user icon turns brown.

**Expected result:**
Color of user icon turns gray.

### Screenshots

Inconsistent Note to Self and user icon colors (gray and brown):
![signal-attachment-2019-12-13-121348_002](https://user-images.githubusercontent.com/5825551/70882472-e7f2d880-1f9d-11ea-8ccf-7e477217bd99.png)
Correct and consistent Note to Self and user icon colors (green):
![signal-attachment-2019-12-13-121348_004](https://user-images.githubusercontent.com/5825551/70882473-e7f2d880-1f9d-11ea-8dc5-c0ebd6e54100.png)
Correct and consistent Note to Self and user icon colors (brown):
![signal-attachment-2019-12-13-121348_005](https://user-images.githubusercontent.com/5825551/70882474-e7f2d880-1f9d-11ea-84c9-1e3dfd109940.png)

### Device info

**Device:** Google Pixel 3
**Android version:** 10
**Signal version:** 4.51.6

### Link to debug log
https://debuglogs.org/b7cb42217a6a84fac77d4b3a855a9567c3059e530b70b0f5353cf4a3d021d252

**Comment by Sgn-32** [comment]
in the following case the color is red:

![IMG_20191223_111014](https://user-images.githubusercontent.com/49990901/71352406-8a025a00-2576-11ea-89d1-e25638cdf164.jpg)
![IMG_20191223_111044](https://user-images.githubusercontent.com/49990901/71352405-8a025a00-2576-11ea-81df-dd9922b725fe.jpg)

this is probably due to the following code in AvatarUtil.java (lines 31 to 33)

```
    if (fallbackColor == ContactColors.UNKNOWN_COLOR && !TextUtils.isEmpty(name)) {
      fallbackColor = ContactColors.generateFor(name);
    }
```

grey (MaterialColor.STEEL) also defines the ContactColors.UNKNOWN_COLOR.
by setting the color grey (STEEL) the if-condition generates a color.
