### ISSUE TITLE
selected message bubble should still be swipable to reply

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9289]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Not entirely sure if this was existing functionality before. When one or multiple messages are selected, there is no need to block those message bubbles from being swipeable for quick reply.

### Expected behavior
Be lenient with users who selected something but still decide to use quick reply.

### Device info

**Android version:** 9.0
**Signal version:** 4.52.1

**Comment by greyson-signal** [comment]
All touch interaction on views is disabled in multiselect, and this is intentional. You don't want people accidentally clicking on links, playing voice notes, or (in this case) swiping to reply on messages when they've gone into a mode specifically to select a batch of messages to delete (or whatever action they were looking to perform). Given that this behavior is intentional, I'll close this as a feature request :+1:

**Comment by Meteor0id** [comment]
Feature request exists here:
https://community.signalusers.org/t/enhancement-swipe-to-reply-even-when-one-or-more-messages-have-been-selected/10300

Note that swipe to reply is not more likely to get triggered on accident when selecting messages, so unlike accidental link clicks or playing voice notes on accident, swipe to reply doesn't need to be disabled.
