### ISSUE TITLE
How do Chinese users receive push notifications?

### ISSUE THREAD

**Issue by qiruiluhu** [signalapp/Signal-Android#9318]
My phone is pre-installed with Google Services Framework and I cannot uninstall it. Our country has blocked any services provided by Google, including GCM, so gcm on my phone cannot connect to the Internet normally. But the signal judges that my mobile phone has the Google service framework installed by default using gcm push, and I can't change the push method, what's all this?

**Comment by qiruiluhu** [comment]
Why doesn't Signal provide an option for users to choose the push method freely?

**Comment by Genis-Sage** [comment]
hey @qiruiluhu 

1) for solving your problem, you should search how to deactivate / deinstall the Google Services Components via ADB (signal detects during registration, if GCM is available. If yes, it's used, if not, websockets are used)

2) for feature discussion, like addionla option, and asking design questions, you should go to [Signal Community Forum](https://community.signalusers.org/), since Github is reserved for bug tracking
