### ISSUE TITLE
Signal (without Play Services) persistent connection (Websockets) is enabled when notifications are disabled

### ISSUE THREAD

**Issue by hsanjuan** [signalapp/Signal-Android#9357]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I install Signal from the apk on the website.

I go through the set up. Everything goes well. Eventually there is a banner asking me to disable battery optimizations and what not. I click on the X. For a few hours Signal works perfectly, without battery drain. Notifications are sometimes delayed but that's ok.

Then, after checking Signal some random time, it decides to start a notification with "Background connection enabled" and a huge battery drain (reported dozens of times in the last years) starts.

There is no way to disable background connection. Turning all notifications off does not disable it either (why?).

When trying to enable battery optimizations, it says `Battery optimization not available`.

### Steps to reproduce
- Setup signal
- Use it normally for a while
- At some point it decides it should use persistent connection

**Actual result:** Persistent connection is enabled without asking, cannot be disabled, battery optimizations cannot be enabled.

**Expected result:** Persistent connection should not be enabled unless the user opts-in. Persistent connection should be disabled when notifications are turned off. Battery optimizations should be available to be enabled so that the app can be put to sleep by the OS.

### Device info

**Device:** Google Pixel 3
**Android version:** 10
**Signal version:** 4.53.6

### Link to debug log

There is nothing special in the debug log. The `WebSocketConnection: Message` entries come regularly in bunches separated by a 55 second interval (as intended).

**Comment by greyson-signal** [comment]
Because we don't have the ability to receive FCM messages, we must keep a websocket open to receive realtime messages. You are correct that this will cause additional battery drain. But there's not much else we can do to ensure that you get messages when they're sent to you.

**Comment by figbux** [comment]
Hello  @greyson-signal,

Actually there is something to do. Threema handles no-fcm case with "polling" rather than a always open websocket. Users can select the interval of polling for the new messages (5-15-30 mins). Of course it is user's own decision to use polling instead of FCM; and user accepts the possibility of missing instant notifications (even for calls). But this trade-off is acceptable for someone trying to hide from big brother.

BTW, I didn't know it's possible to install signal w/o google play services. I even couldn't proceed the setup because signal said google services have to be present.
