### ISSUE TITLE
Signal makes encrypted phone calls even if unencrypted mode is selected

### ISSUE THREAD

**Issue by lapp0** [signalapp/Signal-Android#9361]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal makes encrypted phone calls even if unencrypted mode is selected

### Steps to reproduce
- disable encrypted messaging by disabling the option in the bottom right of any contacts text message screen
- call the contact from the same screen

**Actual result:** texts are unencrypted as expected, however calling the contact is still encrypted
**Expected result:** the call shouldn't be encrypted, and should either be handled as such internally by signal, or passed to the phones default call handler

**Comment by bme13** [comment]
Hi lapp0. I understand this might be confusing but it is currently the expected behaviour. See e.g. https://github.com/signalapp/Signal-Android/issues/8965 and [here's](https://community.signalusers.org/t/choice-between-signal-and-non-signal-out-going-calls/8889) some related discussion on the community forum.
