### ISSUE TITLE
Photo preview looks different from fullscreen view (PNG)

### ISSUE THREAD

**Issue by vandenheuvel** [signalapp/Signal-Android#9371]
The fullscreen view of [this png](https://user-images.githubusercontent.com/20440137/73350857-1c8ccc00-428e-11ea-892c-e2d95941793a.png) is missing parts. This is what it looks like in the conversation:
![This](https://user-images.githubusercontent.com/20440137/73351030-7a211880-428e-11ea-954f-47453b001913.jpeg)
While this is what it looks like when I view the picture full screen:
![fullscreen_view](https://user-images.githubusercontent.com/20440137/73351115-9f158b80-428e-11ea-87a7-998e97120c93.png)

Can be reproduced by sending the linked png file to myself from signal desktop and viewing it on my phone (probably also works repeatedly by sending it to a real conversation partner, as was done for the screenshots, but I didn't try to reproduce that way).

I would expect the preview of the image (which is correct) to be equal to the full screen view of the image (which is incorrect).

**Device:** Xiaomi Mi 9T Pro
**Android version:** LineageOS 17.1, [this build](https://forum.xda-developers.com/k20-pro/development/rom-lineageos-17-0-t3976469) from 191205.
**Signal version:** 4.53.7
**Log:** [link](https://debuglogs.org/23230b9743f3a33e369b24e1fcc01538ee07efd0e94f678140c5a12e156beb6b).

**Comment by greyson-signal** [comment]
It's not that it's missing parts, it's that your PNG is transparent on the outside. In the conversation bubble, it defaults to a white background so that your black text on the edges is still visible. But fullscreen, we use a black background, so you can't really see the text on the edges (which is also black). I don't know what the real solution is here. Some PNGs are just going to be hard to view on standard backgrounds.
