### ISSUE TITLE
Signal Enforces Google Play Services to get SMS Permission First to Use the App!

### ISSUE THREAD

**Issue by desmonk** [signalapp/Signal-Android#9376]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal gets Google Play Services opened when setting up for the first time to allow the Play Services access to SMS. Can't use Signal if I deny this permission.

### Steps to reproduce
- Install latest Signal app
- App will open Play Services to grant it access to SMS
- Can't use app without this permission.

**Actual result:** Signal gets Google Play Services opened when setting up for the first time to allow the Play Services access to SMS. Can't use Signal if I deny this permission.

**Expected result:** Signal should not enforce such permission.

### Screenshots
![SMS Permission](https://user-images.githubusercontent.com/55331939/73608417-8a9d0000-45ba-11ea-92e0-2bdb386f234f.jpg)

### Device info

**Device:** OnePlus
**Android version:** 9
**Signal version:** 4.54.3

**Comment by strugee** [comment]
Did you manually deny Google Play Services this permission?

**Comment by Cerberus0** [comment]
Some comments by the developers, which are not directly related to this specific issue but can give context:

>We only fallback to the websocket if Google Play Services isn't present at all. The target for this was people running Google-free ROMs. If Google Play Services is present, then we're going to try to use it. I consider going beyond this behavior to be a feature request (since it goes outside of the intended scope of the original support), so we should move this to [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!

https://github.com/signalapp/Signal-Android/issues/8336#issuecomment-436344478

>There's too many permutations of people's rooted devices to actively support them all, especially when you're spoofing key Android components like Google Play Services. We support non-GooglePlayServices devices, but I don't anticipate us supporting "partial-GooglePlayServices" devices.

https://github.com/signalapp/Signal-Android/issues/8513#issuecomment-452428433

**Comment by desmonk** [comment]
Google Play Services is denied most of the permission except Storage. With that being said, issue here is the way Signal starts the whole registration process. The user gets asked to allow Play Services to access SMS permission to get going.

In the absence of Play Services, this prompt does not take place and works with background sync automatically enabled by Signal.

On most devices, as Play Services usually have most permissions, developers might have thought of above process. Which in turn is a privacy issue if a user chooses to disable SMS permission to Play Services.

Thing is Signal just won't even skip this part unless a user agrees to allow this permission! This is concerning.

**Comment by Tursko** [comment]
A post or issue like this comes up all the time. Google Play Services needs to be turned off completely. It will then skip that message.

**Comment by desmonk** [comment]
Please take a look at the post above yours where I have already mentioned bypassing of Google Play Services in order to get going. Unfortunately, this can not be done on most stock ROM.

**Comment by Tursko** [comment]
There are plenty of discussions about this on the forums. This isn't a bug. 

https://community.signalusers.org/

**Comment by desmonk** [comment]
A bug can be anything that produces unexpected result such as described here. Signal app should be able to tackle this issue without asking a user to allow Play Services access to SMS. As evident from the result above, Signal gets stuck otherwise even when it can easily evade such roadblocks on its own.

Hope this helps.

**Comment by strugee** [comment]
@desmonk @Tursko's point is that the result isn't unexpected. You

**Comment by desmonk** [comment]
Agreed. 

Issue takes an aim to a wide range of audience. As most users have default permissions for Play Services, above concern won't come into play as permission to read SMS is already granted. As noted before, such permission should not become a hindrance.

Unfortunately, Signal simply won't allow the registration process to continue which in turn is the whole reason why this is being labeled as a bug as the app produces such unexpected result knowing what the resolution is.

Whether I like it or not is besides the point of argument. Matters is how privacy gets invaded unknowingly of so many users with no way of escaping the whole process of registration.

**Comment by lo9-u** [comment]
@greyson-signal 
I have the same problem as this user on reddit.
https://www.reddit.com/r/signal/comments/gq5u9l/signal_just_wont_work_without_google_play_services/

1. I have downloaded and installed the current signal 4.69.6 from the website.
https://signal.org/android/apk/
2. my Android smartphone is not rooted, but all Google Play services are blocked via Adguard Android
https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.4-release
3. I open Signal for the first time and want to enter my phone number for registration, but I don't get an SMS because the Google Play services are required.


Question:
Can you add a manual function where users can manually switch to Websocket. Then the problem is solved everywhere. Is that possible?

**Comment by thenhustey** [comment]
**This is simply BAD.**

Please describe, why is not possible to deliver verification code when there is no access to SMS granted? It's still same SMS as when you have phone fully without Google Play Services!

If is this permission for Google Play Services needed I thought that there is a topic in FAQ with looooong list of advantages due this.

But when you grant Google Play Services access to SMS only for time of verification and then deny it again, everything works normally. So it looks 

**This is very suspicious from privacy messenger to require granting access to very private data to proprietary framework (used for ~~spying~~ collecting telemetry)**

**Comment by JakeQZ** [comment]
It's using Google Play Services to access the SMS with the registration code, to auto-fill it.  It should allow manually entering the code from the SMS received.  But if the permission is not granted the installation process will not proceed to allow manual entering.

Anyone security conscious will have revoked permissions from Google Play Services, as these provide a back door for apps to access data without explicitly asking permission.  This is a security issue with Android itself, but exploiting it compounds the problem.

I content that this is a bug, because the installation should not require enabling privileges for Google Play Services, even if briefly.  Manually entering the code must be an option.

**Comment by JakeQZ** [comment]
To clarify, the automatic filling of the code should be considered as a feature (right?), and the ability to manually enter the code as basic required functionality, because the installation cannot proceed without the code being entered (i.e. remove the feature and manually entering the code is required, must therefore work, and anything which prevents it doing so is a bug).  The implementation of the feature breaks the basic functionality.  Therefore it is a bug in the implementation of the feature.

**Comment by My1** [comment]
I fully agree, honestly at the start I was kinda wtf'd when I saw signal autofilling despite iirc not needing SMS permissions, guess that goes over google now. and I fully agree you should just be able to skip to manual entry just like for example when the phone number used is not on the same device you are using signal with.

**Comment by JakeQZ** [comment]
Telegram asks for permission to automatically enter the SMS code, and allows manual entry if not granted.

It does not appear to use Google Play Services as a bypass.

This is how it should work.

Current Signal implementation is unacceptable.

**Comment by My1** [comment]
personally tho I kinda prefer the google services way as a way to not ask for permission since the app can only get SMS intended for itself, however the problem I see is that there's no way to just skip and enter manually

**Comment by JakeQZ** [comment]
> the app can only get SMS intended for itself

Really?  What evidence do you have for that assertion?

How on earth could Google Play Services apply such a restriction?

**Comment by My1** [comment]
The sms contains a hash of stuff including the signing cert of the app so the sms looks like this


SIGNAL: Your code is: 123-456

doDiFGKPO1r

**Comment by JakeQZ** [comment]
> 
> 
> The sms contains a hash of stuff including the signing cert of the app so the sms looks like this
> 
> SIGNAL: Your code is: 123-456
> 
> doDiFGKPO1r

And Google Play Services only allows the app to read SMSs with this specific format?  We trust Google to make this assertion with a closed-source system?  And Google's software never ever has security vulnerabilities?

**Comment by My1** [comment]
Well it's for starters not exactly that the play services just throw you a list of sms with the code but you basically create an event listener for that sms. So it should only work for one incoming sms anyway. (also there's a timer on it as well), so it's a ton better than a blanket perm for anything sms, past, present and future.

Putting that aside I am in full support of this issue and if you ax that you should just be able to enter it manually.

**Comment by JakeQZ** [comment]
> ...you basically create an event listener for that sms...

Good explanation - seems then it's not quite as insecure as it appears on the surface.

This probably also explains why the SMS with the code is never even sent if Play Services is disallowed access (the listener would logically be created first, and if that fails it progresses no further).

That all said, this is a dubious and unnecessary 'convenience' feature of Android that has little justification but plenty of potential security flaws, and thus should not be used.

**Comment by My1** [comment]
I think the point was just that apps stop asking for SMS permissions tbh.

but sure these things should be optional and for example in case the phone number is on a different device that listener goes to the trash anyway.

**Comment by greyson-signal** [comment]
There's been a lot of discussion, so I'll summarize: If you have Google Play Services on your device, we will use them. One of the Play Services API's we use is one that let's us automatically grab the SMS verification code, without *our app* needing the SMS permission. I'm guessing that's why Play Services was specifically whining about needing SMS permissions.

In the end though, Play Services is very black-box-y. We don't request these permission prompts, the API's just kind of do it. Our stance with Play Services has always been that if your phone doesn't have them, we won't use them. But if your phone *does* have them, we expect that they work, they're real (aka not MicroG or what have you), and aren't hindered in any way.

**Comment by ph00lt0** [comment]
@greyson-signal I still think you do not understand the problem many people are facing. If your devices has Google Play Services installed, but disabled by for the user, signal still attempts to use this. This results in a user not being able to sign up using your app. This is a really big problem. 
Furthermore if a user decides to block Google Play Services in the network (either on system or network level, think of blokada, netguard or pihole, adguard) it will result in the app not receiving any notifications! Signal should really have an option to fallback on it's own network, but preferable have this as a setting. 
I am very disappointed that you are not listening to many of us raising this concern / bug.

**Comment by greyson-signal** [comment]
If you have Play Services installed but disabled in a way that can be changed in the UI (i.e. through the normal system settings), Play Services will let you know and tell you how to fix it during registration. 

If you have Play Services installed but disabled in some superuser way (i.e. messing around with adb, or installing some fake Play Services like MicroG), you're on your own. There is no world in which we can reasonably stay up to date on the various methods people are using to alter core system components. A common workaround I've seen for people with MicroG-type-things is to disable it during registration, then turn it on afterwards. That way you'll be put in no-Play-Services mode.

**Comment by ph00lt0** [comment]
@greyson-signal to disable Play Services you do not need superuser. This is a misconception. You can disable play services by either getting it stuck in update via adb, or on most phones execute:
`adb shell pm disable-user --user 0 com.google.android.gms`

This is not something you can do through android settings. Nor will anything tell you how to fix it. The only fix is to use it. That is not a viable solution in my eyes.

**Comment by JakeQZ** [comment]
> if your phone _does_ have them, we expect that they work

But if they don't work (e.g. because the SMS permission has been revoked via settings), surely an error status is returned that can be checked for?  Not checking return values (or suchlike) for errors is surely a bug?

> If you have Play Services installed but disabled in a way that can be changed in the UI (i.e. through the normal system settings), Play Services will let you know and tell you how to fix it during registration.

It won't if you've told it not to show you any more of those kind of notifications.  Also, when you enable the privilege for Play Services, the install still does not proceed, you have to go back and enter your phone number again.  (Weird thing, testing again, after enabling the privilege and re-entering phone number, I got the SMS, but it did not auto-fill - had to manually enter the code.)

Anyway, there are presumably a number of developers reading this with relevant experience who could submit a PR to fix this, and if meeting the required coding standard, it would be accepted?

**Comment by JakeQZ** [comment]
> @greyson-signal closed this 13 days ago

Good luck getting more users with that attitude.

**Comment by greyson-signal** [comment]
> to disable Play Services you do not need superuser.

Apologies, poor choice of word on my end. By 'superuser' I just meant 'advanced user', not a root user. And if you're running adb commands on your phone to disable core functionality not exposed in the UI, you indeed are an advanced user :)

> Anyway, there are presumably a number of developers reading this with relevant experience who could submit a PR to fix this, and if meeting the required coding standard, it would be accepted?

Sure, happy to review a PR that addressed this in a way that doesn't disrupt the rest of the code.

**Comment by desmonk** [comment]
@greyson-signal 
On what grounds you closed this? Reliance on Google at all not a welcoming move by Signal. I am disappointed to see such arrogance presence here whereby a single vote is enough to veto the greater good that's voted in favor by many. Not to mention Signal's usage of System WebView instead of allowing a user to choose a default browser app to fill in the reCAPTCAH, again a service of our beloved Google.

How many red flags can you see? Let me answer. None.

@moxie-signal Is this what you want? What has happened to you guys? Did being popular mean compromising on the user privacy? Signal has stood for freedom and this is like telling users to back off cause Google is more important.

Don't be evil. Do you remember who said that? Yes, Google.
A company that does exactly this with enormous data on each user being used according to their terms and service cause average is user not tech savvy.

Why are you sleeping with Google?

**Comment by SkewedZeppelin** [comment]
I think there is a bug here:
https://github.com/signalapp/Signal-Android/blob/5537039e464d0ae1be6340be29f46fc07c92bd4b/app/src/main/java/org/thoughtcrime/securesms/util/PlayServicesUtil.java#L39-L50

If Play Services is installed but disabled by user, Signal tries to ignore the result from the Play Services Library, but that check broken after targetSdk was set to 30 due to https://developer.android.com/training/package-visibility

```
<queries>
	<package android:name="com.google.android.gms" />
</queries>
```
should be added to https://github.com/signalapp/Signal-Android/blob/main/app/src/main/AndroidManifest.xml
