### ISSUE TITLE
RegistrationActivity_backup_timestamp_s should always show a full non-shorted datetime

### ISSUE THREAD

**Issue by Meteor0id** [signalapp/Signal-Android#9403]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Can't really call this a feature request because it is such a minor tweak.
When recovering a backup, the datetime is sometimes shorted to for example "Mon 00:24". This can however lead to the question "Was this last Monday or just a Monday?" This matters when making a choice whether you want to restore the backup or not. The solution is very simple: always show a full datetime with day, month year and time, even if the backup was made this week. This removes any ambiguity.

Edit: and let me also mention that the datetime currently isn't being localized, and shows in English despite another language being configured.
### Device info
**Signal version:** 4.56.1

**Comment by leethater** [comment]
Hey, I saw your mention at  #9584 and I took a look at your issue. 
The problem is, I cannot reproduce your bug. 
The backup will have "weekday hh:mm" format only if the last back up was made less than a week ago, so referring to your post it could only be "last Monday".

![2020-05-06-144219_369x190_scrot](https://user-images.githubusercontent.com/35769770/81178878-27e84580-8fa9-11ea-91ce-042e97d81a06.png)

As soon as  a backup is older than one week, the timestamp shows full date.(ex : Jul 16h at 5:30) 

![2020-05-06-144255_358x172_scrot](https://user-images.githubusercontent.com/35769770/81178889-2ae33600-8fa9-11ea-87da-74625cec469b.png)

That being said, I agree that it would leave less ambiguity if it was showing full date.

**Comment by Meteor0id** [comment]
@leethater 

Users might not know that the weekday will only be shown if the backup was made less than a week ago. In English that might be a fair assumption, but in some locales that isn't a customary way to refer to a time earlier the same week.

A second issue can arrise from datetimes which don't meantion a year. A full datetime is one that also includes a year. If I disabled backups years ago and need an important message from the past recovered, it really matters to me what year this old backup was generated.

The solution can be to at the word "last"  thys making it "last monday" (most recent monday). And on datetimes include the year to turn it into a full datetime.

**Comment by leethater** [comment]
@Meteor0id 

I agree with you. However I don't know if Signal maintainers do too, otherwise I have no problem with adding this modification to my  PR. (or creating a new one)

**Comment by Meteor0id** [comment]
@leethater 
The way to find out if they agree is to propose it. It would fit just fine to add the word "last" or a translation of that word. And 4 digits to indicare a year fit  just fine to.

It might be nessesary for some languages that the word last can come after the name of the day. That could be solved by creating a string with a variable for the name of the day. We can look at other date strings to find out.

**Comment by alan-signal** [comment]
If you're happy to make the PR, then go ahead. Make it separate one, one fix per PR in general.
