### ISSUE TITLE
Screenshots on Samsung S6 Edge don't send properly

### ISSUE THREAD

**Issue by Kylenol** [signalapp/Signal-Android#9404]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Using the latest Android beta 4.56.1, sending a screenshot taken on the device appears fine on the device itself but appears as a grey .wai file for other recipients (including the Desktop app).

### Steps to reproduce
- Take a screenshot on the phone
- Share the screenshot to Signal*
- Select a group chat^
- Submit with or without a caption
* The same happens if you manually save the screenshot to the device and select the image within Signal
^ The same happens if you send to yourself (Note to Self)

**Actual result:** All recipients (including your own account via the Desktop app) see the image as a grey generic file with a reported file size. Friends on iPhone inform me it comes across as a .wai file. If you rename the .wai file to .jpg, the file opens fine. If you use the image editor within Signal to mark up the file and send it, the file appears fine within chat.
**Expected result:** As before the update, the screenshot should simply appear inline within the chat as an image.

### Screenshots

![image](https://user-images.githubusercontent.com/61174737/74702862-6277e880-51d9-11ea-9d2b-edc8ffa952b2.png)

### Device info

**Device:** Samsung SM-G925W8
**Android version:** 7.0 (G925W8VLU6DRF1, NDRD90M)
**Signal version:** 4.56.1

### Link to debug log

https://debuglogs.org/a555c73224161ce1f355059e58fcaa0b8215e2de2d9cae5eb3d1908df88a6832

**Comment by peterpanondrugs** [comment]
The title should be updated, because its not only for screenshots. 

So when i send picture from the gallery, the preview thumbnail is shown as wide. (Even when i click on it) its not in the right format.

https://debuglogs.org/83a7162c6fc0a3c70df4cfe5e699136f62d735b4f28907afa4f050568692c99e

![safsdf](https://user-images.githubusercontent.com/8776733/74719809-0773df00-5235-11ea-9486-f7fbcd7334e5.jpg)
![gfzhfgh](https://user-images.githubusercontent.com/8776733/74719815-080c7580-5235-11ea-9b02-6481d5a227b0.jpg)

**Comment by greyson-signal** [comment]
This will be fixed in an upcoming 4.56.x release.
