### ISSUE TITLE
Deleted messages for the assigned expiration time can be viewed after they have been "deleted."

### ISSUE THREAD

**Issue by iangelromeroc** [signalapp/Signal-Android#9408]
Messages that have been 'deleted' by the expiration time assigned in the Android application can be viewed in the Signal for Windows application while messages are loaded in the background. You can see them for a few seconds while the application gradually loads the messages and then deletes them.

I have the android application synchronized with the Signal application for Windows.

Is Signal saving messages on its servers? Are the messages not totally deleted?

This is very serious!

**Comment by greyson-signal** [comment]
Messages are deleted on the local device at the appropriate time (i.e. based on the conversation timer settings and when you read the message).

When you send a message to a client and that client isn't online (like a closed/offline desktop instance), that message sits in a queue on the server until that client comes back online. While sitting in the queue, messages are encrypted. For that reason, the server can't delete them based off of timer criteria, because the server knows nothing about the messages. It's the client's responsibility to delete them when they are pulled down.

Of course when a client goes to pull the messages down, it receives the message -- but it doesn't know yet whether or not the message has been read (because it hasn't gotten the "read" message from your android device yet, since that's later in the queue). When it does, that's when the message gets deleted. That's why you see them for a brief moment. In real time, you're seeing the desktop client receive the message, then the read receipt that prompts the deletion.

There might be UI things the desktop could do to hide this, but this is the Android repository. Feel free to discuss it on the desktop repository or the forums.
