### ISSUE TITLE
Call notification missing

### ISSUE THREAD

**Issue by d43m0nhLInt3r** [signalapp/Signal-Android#9414]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

The Call Notification dont appear in the Notification center.

### Steps to reproduce
- call someone
- no notification about the call in the notification center

**Actual result:** No Notification
**Expected result:** The notification i got before the newest Beta release

### Device info

**Device:** Moto G4
**Android version:** 7.1.2
**Signal version:** 4.56.1

**Comment by ozgurakyazi** [comment]
I started having this issue just after upgrading to 4.57.2 (Samsung SM-G900F) .  But this issue was already present for 2 Xiaomi phones, Redmi Note 7 and Redmi 5 Plus for months.

Issue I face is, whenever I receive a call, the call sounds starts but the screen does not change when I am in my phones home screen. I have to click on Signal and then I click a person and  click to call button to see the screen to accept or reject the call. Even if I am in the Signal main screen, I still need to go to a conversation and tap on call button there.

During the calls, when I tap my home button, the call notification is not placed on the top bar (it used be there, with a button to hang up the call without having to go the call screen).

**Comment by Mat3oo** [comment]
I have similar issues on Xiaomi Redmi Note 4, Android 7.0, MIUI 11.0.2 .

> During the calls, when I tap my home button, the call notification is not placed on the top bar

The call notification is not present at all. On the other device notification is persistant during the whole call, even if the call screen is on first plan.

So after exit _"call screen"_ or _"screen with accept/decline the call"_ you need to:
>  I have to click on Signal and then I click a person and click to call button to see the screen to accept or reject the call. Even if I am in the Signal main screen, I still need to go to a conversation and tap on call button there.

This is really annoying, because call sound is still playing until you manualy enter into app and click person, enter call function, accept/decline. You don't even know who's calling from the main application view.
Here is a proposal to display which contact has an active voice/video connection in the main application screen.

**Comment by ozgurakyazi** [comment]
@Mat3oo  Exactly the experience in all Xiaomi s I have setup signal. But instead the normal notification should be the proposal I think. And I can provide a lot of debug logs from all the phones I mention, if they could help.
