### ISSUE TITLE
Four safety numbers changed in an instant on Group Chat, All +44

### ISSUE THREAD

**Issue by hopeseekr** [signalapp/Signal-Android#9447]
I'm in a group I started that is reporting about the Coronavirus. 

A person I don't know that well added 3 +44 UK numbers I don't know.

I bluffed and said I added an "arbiter bot" to verify safety numbers, and within 2 minutes of saying that message, all four of these UK numbers had their safety numbers change, according to numerous people in the group chat, and my own account.

What could cause this? Is it a Signal bug? All of the numbers began with 7.
![security incident redacted](https://user-images.githubusercontent.com/1125541/75989960-beb95880-5eb9-11ea-8b8f-53e403ae230d.jpg)

**Comment by guimspace** [comment]
A safety number is generated (from the Signal protocol magic - after key exchange) when you start a chat with a new number. The safety number is also re-generated if the number changes the device or reinstalls Signal*.  

I suppose you never chatted with the other 3 numbers, so your chat (and the key exchanges) started when you sent that message about the bot. It took a few minutes because the numbers first need to receive your requirement to exchange keys, and then receive your message.  

\* - The safety number is not regenerated if the person uses a backup to recover messages when signing in back in Signal.
