### ISSUE TITLE
Stop showing "add profile name" spam

### ISSUE THREAD

**Issue by RalfJung** [signalapp/Signal-Android#9479]
### Bug description
Since a recent upgrade, Signal has increased the amount of nagging it does to make me set a profile name. It then presents a "choice" between setting my name now and nagging me every 2 days -- which is no worth calling a choice, really.

This is a bug because it reflects the app not respecting user choice: I choose not to set my profile name.

### Steps to reproduce
- do not set a profile name
- keep using the app

**Actual result:** Messages appear to make me set the profile name. I already patched out the permanent banner in group chats, now there's a new banner at on the main screen as well.
**Expected result:** The app should respect my choice not to set a profile name.

**Comment by RalfJung** [comment]
I have updated my patch at https://github.com/RalfJung/Signal-Android to hopefully also get rid of this latest popup.

**Comment by u32i64** [comment]
> This is a bug because it reflects the app not respecting user choice: I choose not to set my profile name.

From [`CONTRIBUTING.md`](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#the-issue-tracker-is-for-bugs-not-feature-requests):

> The GitHub issue tracker is not used for feature requests, but new ideas can be submitted and discussed on the [community forum](https://community.signalusers.org/c/feature-requests). The purpose of this issue tracker is to track bugs in the Android client. **Bug reports should only be submitted for existing functionality that does not work as intended.** Comments that are relevant and concise will help the developers solve issues more quickly.

<sup>(emphasis mine)</sup>

This popup does indeed behave as intended: the app insists on you setting the profile name, because it is becoming mandatory.

There already is a [feature request](https://community.signalusers.org/t/do-not-require-a-profile-name-to-be-set-allow-users-to-delete-their-profile-name-or-explain-why-first-name-is-required/11515?u=u32i64) to not require a profile name on the community forum.

**Comment by RalfJung** [comment]
> This popup does indeed behave as intended: the app insists on you setting the profile name, because it is becoming mandatory.

Assuming that is accurate, that is still no justification to use dark design patterns to impose this "choice" on people. Just make it mandatory, and explain why you think that is "for the greater good". But don't pretend like there is a choice, and then keep nagging people that make the "wrong choice".

**Comment by Legogris** [comment]
+1 on labeling this as a bug.
Will a PR allowing users to permanently silence the megaphone be considered? Relevant commit: https://github.com/signalapp/Signal-Android/commit/3ea1492d672409d6018568b2f8b81d886ced1448

**Comment by alan-signal** [comment]
We value your feedback, but we don't put a higher value on that feedback just because something is labeled a bug on github.

This has already been discussed in the proper place: https://community.signalusers.org/t/enter-profile-name-add-remind-me-never/12459

**Comment by alan-signal** [comment]
> Will a PR allowing users to permanently silence the megaphone be considered?

No. We haven't implemented such an option not because we don't have dev capacity but because we don't want it to work like that. Megaphones function the way we intended but of course we listen to feedback on the forum, and we really do change direction from that feedback.

**Comment by dnut** [comment]
This is a bug because it contradicts your [documentation](https://support.signal.org/hc/en-us/articles/360007459591), which states that it is optional. So either the documentation or the app needs to change.

Personally I think it's a bad idea to make profiles mandatory, but I agree, that discussion is more of a feature request.
