### ISSUE TITLE
Slow sending of messages 

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#9493]
I started facing an issue with the Signal Android application. Messages are slowly sent without apparent reason (network quality is good and other applications works just fine).

Logs: https://debuglogs.org/0f96e29f1d754a15df7e1923817fa25bf977f45c2f603cb837d48153f8e97465

I don't know if it's some Signal's server outage or it's and issue in my side.

Phone: Samsung Galaxy A70 - SM-A705MN
Android: 9 Pie.
Signal version: 4.57.1

**Comment by johnlane** [comment]
I've noticied this too. Unreliable sending of messages whilst receipt and audio/video call/answer works fine. Messages can sit with the spinning disc for hours. 

I'm currently setting up for some new users who I would prefer not jumping to whatsapp etc. So I'd really like to understand whether this is a service problem, a bug with the app, or something I need to do.

I'm setting up an old Samsung phone. Initially I had the play store version but replaced it with the sideload in an attempt to fix it.

I gave up last night, to find that it's working ok today. Messages get through, sometimes slow but minutes rather than hours.

Phone Samsung Galaxy S3,
Android 7.1.2, Lineage 14.1.20190223-unofficial-i9300
Signal 4.57.3 (sideload)

Phone Redmi Note 8T
Android 10, Havoc 3.3
Signal 4.56.4 (play store)

**Comment by Edu4rdSHL** [comment]
Seems that it's happening in different Signal versions, I assume it's an issue with Signal servers.

**Comment by Edu4rdSHL** [comment]
Another debug log from today:

https://debuglogs.org/81aa5eb720e21818773f405c765373e57a623d4b2d164f7c7e01c7e5b115bc06

**Comment by greyson-signal** [comment]
There was some server slowdowns.

**Comment by Edu4rdSHL** [comment]
It's still happening to me. It's what I mean: https://linksharing.samsungcloud.com/1585096394478C3OGPNd

**Comment by johnlane** [comment]
@greyson-signal thanks for the update. I have encountered no issues since Monday. A service status page would help with issues like this.

**Comment by ristein** [comment]
still happening here. sending pics takes about 3mins
v 4.59.11
A10
Oneplus 7pro

**Comment by iaxat** [comment]
Yes, it happens sometimes, the calls are very slow to connect and stay in calling for quite a long time also messages take forever to show tick.

**Comment by wwebers** [comment]
Still having issues with sending messages. Doesn't matter what OS or Signal client. So, why is this issue closed?

**Comment by Jatoxo** [comment]
This issue is still happening to me since about a month. Network is completely fine. Both on the desktop client and on my phone it often takes a dozen seconds for a message to be delivered. The same happens on my recipients side. Sometimes a single message arrives hours late even with chatting in between

**Comment by cody-signal** [comment]
@Jatoxo please open a new issue and include debuglogs for both the android client and desktop client. Thanks!
