### ISSUE TITLE
Video (+maybe audio?) calls drop randomly within minutes

### ISSUE THREAD

**Issue by malnoxon** [signalapp/Signal-Android#9521]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
During video chats, the call (audio+video) drops randomly. This has happened on multiple calls with different people (Both of them were using iphones). Usually the call drops pretty quickly (within a couple minutes) but the time doesn't seem consistent. This problem arose months ago, I'm not sure how many. I used to be able to video call the same people without any issues, for conversations well over half an hour with zero drops.

Audio only calls may have this issue as well. I've had at least one audio only call drop before but it has taken much longer for it to happen (20 mins - couple hours and most calls it never happens) and it's only happened 1-2 times so I'm unsure if it's a consistent thing or related to the consistent video issue.

### Steps to reproduce
- Start a video call in signal
- Wait for a few minutes for the call to drop

**Actual result:** Call drops with no message or error.
**Expected result:** Call continues.

### Device info

**Device:** Nokia 6.1 (TA-1045)
**Android version:** 10
**Signal version:** 4.58.4

### Link to debug log
https://debuglogs.org/897cb3ad1efa6e919b7fdbf5cc38c645d81f01d1e7aa4ba990dc74cfb0cd4e30

**Comment by guimspace** [comment]
Reading your debug log, I think we experience the same issue:
```
SignalServiceMessageSender: java.io.IOException: No connection!
```
Per the exception, I guess Signal ends the call instead of trying to reconnect - like WhatsApp. So, if your internet connection fails for a moment, the call drops - I'm not sure if it is also the case if the connection is re-routed.

You can test the frequency of call drops in this two cases: with a strong and stable internet connection/signal, with a weak and unstable connection.

**Comment by jfsgnl** [comment]
I am seeing the same problem as @malnoxon on the same model phone with the same problem history (over the long run it has been working fine, there was a bad period a few months ago, sorry version unknown, it recovered after signal version update for a little while, and has returned).  Currently using a slightly newer Signal version than @malnoxon: 4.58.5 (6192).

The length of time before crash seems somewhat random, but is rarely long.

@guimspace  while there are connection issues in my logs as well, the video call failures correspond to the SIGABRTs, not the connection alerts.  Example timestamp of problem "04-04 22:16" 
https://debuglogs.org/6d868ac3b624af5637fb85c0b5040283a5402764a8b7b014c45bd180abd99b11

**Comment by gitmiluser27** [comment]
I have the same problem as @malnoxon but with completely different conditions:
* Android 6
* Samsung Galaxy J5
 * Signal 4.58.5

A video call is interrupted irregularly after 20-70 seconds.
With audio calls it usually breaks off after 2-4 minutes.
During video calls I have noticed that the picture usually jerks briefly before the connection is terminated and then freezes. Afterwards the connection breaks off. In rare cases the connection runs on for a while without freezing the picture (sound would continue to run distorted).


The reason for this is easy to explain: 
At my location there is a bad connection for mobile data (transmitter mast 1km away, concrete walls and houses in between).
Accordingly, there is no continuous mobile data stream available, because unfortunately you move the mobile phone a bit during the conversation.


My WLAN connection is super good and always available. But Signal unfortunately never uses the good and stable wifi connection: SIgnal always establishes a mobile data connection for the call in addition to the WLAN connection, although this would not be necessary with an existing wifi connection! 

For a stable conversation, the wifi connection is preferable.
A selection option under settings: whether a wifi connection may be used for calls would be the secure variant. then you can decide for yourself whether you trust and use wifi.

**Comment by SilentJeune** [comment]
I have a similar issue with similar entries in the debug log.  The issue started a few months ago after updating the app.  Every time my screen goes off or I switch to a different app while on a call (audio-only or video) the call drops anywhere between a few seconds to a few minutes later.  The only time this doesn't happen is when I have the battery save feature turned off and the phone is plugged in.  The other party sees "Reconnecting" on their call screen when this happens.  I thought it was an issue on the other person's side and only recently realized it's my phone causing the issue.

Troubleshooting I've tried in progressive order and in combination:
- Use WiFi instead of tower for data connection --> problem persists
- Plug the phone in --> problem persists
- Add Signal to the list of unmonitored power usage apps so (this worked to prevent GPS apps from losing their GPS signal) --> problem persists
- Turn battery save mode off --> problem persists

Specific debug log entries are identical except for the timestamp for when the call drops:
```
2020-04-30 10:32:40.631 EDT W SignalServiceMessageSender: Transmitting over unidentified pipe...
2020-04-30 10:32:40.633 EDT W SignalServiceMessageSender: java.io.IOException: No connection!
 at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:168)
 at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:154)
 at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1145)
 at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendCallMessage(SignalServiceMessageSender.java:212)
 at org.thoughtcrime.securesms.service.WebRtcCallService$3.call(WebRtcCallService.java:1221) 
 at org.thoughtcrime.securesms.service.WebRtcCallService$3.call(WebRtcCallService.java:1217)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:762)
 
2020-04-30 10:32:40.634 EDT W SignalServiceMessageSender: Falling back to new connection...
2020-04-30 10:32:40.635 EDT W SignalServiceMessageSender: Not transmitting over pipe...
```

**Comment by bhlevca** [comment]
This issue should be reopened. I have experienced the same or similar problems with audio or video calls. The issue is not related to bad connection as most of the time both ends had perfect wi-fi connection. It does not seem to matter the OS.
SIGNAL disconnects often and tries reconnecting 

It is gotten worse in the past 2 months

**Comment by cody-signal** [comment]
Hi @bhlevca could you provide update debuglogs after experiencing the issue?

**Comment by bhlevca** [comment]
I was referring to performance not to call drops. The connection freezes for a couple of seconds and the app prints "reconnecting"  after which it is either fast forwarding or completely missing som parts. I did not experience drops, it is about freezes, studdering etc

**Comment by bhlevca** [comment]
This should be reopened as it is not fixed. I understand that's easier to close though

**Comment by cody-signal** [comment]
@bhlevca It sounds like you are experiencing a different problem than the original poster that mentions drops in the title of the issue. If you aren't having drops, but instead quality issues. Please make a new ticket and be sure to include logs **after** you experience the issue again.
