### ISSUE TITLE
Call ended abruptly

### ISSUE THREAD

**Issue by EmilVogt** [signalapp/Signal-Android#9552]
**Bug description**
I wasn't sure if I should open this issue, but since it said "crash" in the logs...
Received a phone call (with video) and answered it. After a while the whole app closed, shutting of the video and ending the call. It might have been the internet connection, but I had good reception. If I remember correctly, usually there's this "hanging up" sound when the call is ended. But it wasn't there this time. So, maybe it was the internet connection or it crashed. 

Thank you for your time :)

**Steps to reproduce**
I can't reliably reproduce this, but it happened more than once in a (I think) stable wifi.
1. Receive a call
2. Call ends suddenly

**System:**
Phone: Nokia 6.1 (2018)
Android: 10
Signal: 4.58.5

**Debug log**
[https://debuglogs.org/c604f998dfd7ca9f12253bace1d956024a58a8669b44a30644435ed005731c77](https://debuglogs.org/c604f998dfd7ca9f12253bace1d956024a58a8669b44a30644435ed005731c77)

**Comment by sirius-c** [comment]
Happens frequently with audio calls now - the call stops as if hung up after around ten minutes.

**Comment by alan-signal** [comment]
Please supply logs @sirius-c you may have a different cause

**Comment by sirius-c** [comment]
@alan-signal It is well possible that it has a different cause. I noticed this problem only since a couple of weeks, and, after a test today, it seems to occur only when I do not use the loudspeaker during a call, but hold the phone like a telephone receiver.

My suspicion is that the call cutting is related to the re-arrangement of the calling buttons with a Signal update a few weeks back.

The proximity sensor on the phone switches the screen off when close to the ear, with the intention of preventing accidental reactions when touching the screen. I possibly remove the sensor part too far, and then accidentally touch the 'hang up' button with the chin. I think the buttons were arranged differently before, and at least for accepting a call some kind of swipe action was required.

This would not really be a bug, but maybe, barring the term operator failure, a user interface issue. - I try to observe the behaviour it in the future.

**Comment by sirius-c** [comment]
The suspicion is not corroborated. I observed today sudden call ends (with hang up sound) when the phone was not touched. The other side told me they suddenly did not hear any sound from me, but they heard no hang up sound. I try to supply logs from the other side next time it happens (always/mostly so far in the 7 to 15 minute range after call start).
