### ISSUE TITLE
Delivery reports for PUSHed messages?

### ISSUE THREAD

**Issue by peti** [signalapp/Signal-Android#957]
SMS messages support the notion of a delivery report that allows me to see when a message was actually delivered to the recipient. I miss that feature for PUSHed messages, though. It seems there is no way to request a delivery report?

**Comment by LoveKC94** [comment]
So where are we on read receipts? The fact that they are not even optional default-off is kind of completely unacceptable in 2016

**Comment by agrajaghh** [comment]
@LoveKC94 please use the mailing list for discussions not the github issues. Thanks! (btw, you'll already find lot of messages about it in the archive)

**Comment by LoveKC94** [comment]
@agrajaghh my apologies, countless searching brought me only to this thread and other closed ones because it was already discussed here. None of these threads have really given a concrete answer or good reason on it. Could you tell me how to get to this mailing list? (BTW, don't know if it matters but I do consider this an issue with the app. Lacking common and useful functionality is definitely an issue)

**Comment by agrajaghh** [comment]
It's linked in the Readme: https://github.com/WhisperSystems/Signal-Android/blob/master/README.md#contributing-ideas

**Comment by LoveKC94** [comment]
Thank you for being polite about my idiocy haha. Can't believe I did not check there.
