### ISSUE TITLE
Profile creation cannot be bypassed

### ISSUE THREAD

**Issue by half-duplex** [signalapp/Signal-Android#9615]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app can no longer used at all without acquiescing to its demands that I create a profile. This is either an application issue or a doc issue, as your [documentation](https://support.signal.org/hc/en-us/articles/360007459591) says we still have a choice.
The previous obscure ways I knew to bypass this, quitting the app or using a back button, no longer work - they all exit the app, and the impassible profile demand is shown again on the next app launch.

### Steps to reproduce
- Open app

Tested methods:
- App drawer icon
- Notification
- A variety of Signal app activities, via Nova Launcher shortcuts

**Actual result:** The profile creation view appears. Clearing the First Name field disables the Next button. The Android back button and Signal back button both exit the application, and re-launching it returns to profile creation. There is no "Skip" button.
**Expected result:** The chat list appears, since this isn't the first launch. At minimum, profile creation can be bypassed. An intuitive way would be ideal, but the previous back button or quit methods are tolerable.

### Screenshots
I'm unable to take a screenshot because of my application configuration.
I'm unable to modify my application configuration because it's demanding I create a profile first.
Ignoring my desire to never do that, creating a profile would make it difficult to reproduce the bug. Is there a way to delete a profile after it's created?

### Device info
**Device:** Google Pixel 3a
**Android version:** 10, 5 Apr patch (QQ2A.200405.005) and 5 May patch (QQ2A.200501.001.B2)
**Signal version:** 4.59.8 and 4.59.9

### App state
- Signal had previously been registered and used successfully
- Registration lock enabled
- Default SMS app, which makes this particularly annoying
- Fingerprint auth required
- Clear cache -> no change
- Force quit / reboot -> no change

### Link to debug log
I'm unable to capture an application debug log because I'm unable to access Signal settings.
Attempting to capture a debug log from the fingerprint prompt results in the fingerprint icon shaking angrily and no information being provided.
Logcat: https://sec.gd/files/f/signal.log

**Comment by greyson-signal** [comment]
When registering with Signal, setting a profile name is now mandatory. I'll request that the first sentence in the documentation be tweaked to be more clear that it isn't optional.

Profiles are encrypted and only readable by those with your profile key (which only includes people you message). However, if you're still concerned, keep in mind it doesn't have to be your actual name. You could write "a", "anonymous", "none", etc. It's basically just the name people will see when you message them and you're not in their contacts.

**Comment by half-duplex** [comment]
The app was already registered when this started, so I guess you mean when using the app at all.
It's very unclear what advantages there are to having a "none" profile over no profile, but thank you for your response.

**Comment by 12people** [comment]
Was just forced to create a profile. Let me just say that, for me, Signal forcing me to do this was both frustrating and made me feel a lot worse about Signal overall. I realize it might be seen as a non-issue from Signal devs' point of view, but it definitely colored my opinion of Signal for the worse.

I use Signal because I like my privacy. One thing that greatly annoys me about apps and websites alike are intro screens that ask me to give them more of my private information. What annoys me even more is when they can't be skipped without providing that data (that's the point when I usually leave or uninstall). Never thought I'd find Signal to be in that category — I wouldn't be using Signal as my only SMS app if I knew it would be holding my data hostage this way.

I understand that I don't have to provide my real name. That said, my options are kind of limited by the fact that I also want a socially acceptable profile. The friends that I convince to use Signal with me would likely be weirded out by me appearing as "None" in their contacts. I also understand that the profile is encrypted, but unfortunately in a way that I have to be careful what message I click on, because otherwise I share my profile without express consent.

So when first seeing this screen, these thoughts are going through my head when I just want to write an SMS. The last thing I want to be doing is figuring out how the encryption works, whether I'm comfortable sharing my profile to strangers that I happen to click on a message from, or how to find a socially acceptable compromise for my profile name.

I would really like this to be reopened, because if there are others like me, this "feature" is likely upsetting a number of users out there.

**Comment by greyson-signal** [comment]
@12people We're slowly moving toward a world where phone numbers will only be used for registration. That means you need some way to identify yourself in a conversation that *isn't* a phone number. That's your profile name. You can identify yourself however you feel comfortable. But when a friend adds you to a group, for instance, we have to show *something* as your name. Hopefully that requirement makes sense. And I know you know this but I'll emphasize it again -- this profile data is encrypted and not readable by the Signal service.

Also, FWIW your profile name has no impact on unencrypted SMS -- just encrypted Signal messages. If someone messages you who isn't in your contacts, we let you decide if you want to share your profile with them. If you start a conversation yourself, you share your profile when you send your first message. Basically, if you're having a back-and-forth conversation with another Signal user, they can see your name and photo. Hopefully that clears up that aspect of it.

**Comment by half-duplex** [comment]
My biggest issue with profiles is that I use different handles with different groups - For example, my legal name with family, and a nickname with internet folks. Right now this is (poorly) solved by just letting them put me into their contacts with whatever name is appropriate.

I've considered creating a second signal account with my voip number for better anonymity, but that would be extremely tedious to use, having to switch Android user accounts to check for messages.

The best solution for me would be one of:
- Allow one signal account to have multiple profiles and choose which to use when creating a conversation. Potentially weird/deanonymizing behavior if a friend is in both the picnic planning group where you're Marcus and your protest group where you're w1n5t0n.
- Allow one signal app installation to manage multiple signal accounts and switch between them easily. Ideally just set which one your phone number should direct users to and allow more non-phone registrations, instead of requiring a bunch of voip numbers for power users.

**Comment by 12people** [comment]
@greyson-signal I understand. I posted here not because I want to argue about the feature, but because I see this as a serious UX issue that might alienate a number of Signal users.

Signal could have easily prevented this, by e.g. making the display name field optional and displaying "Signal User" for profiles without names. It could even ask "Are you sure you don't want to specify a name? Without it, you'll appear as 'Signal User' to your contacts." in a dialog when leaving the field blank. And/or show an infobar inside the app telling the user they haven't set their display name yet.

If this was rolled out to everyone already, then it's too late for this, but I hope at least the Signal team can learn from this and next time, instead of holding a user's data hostage, they can offer an easy out for user scenarios like mine.
