### ISSUE TITLE
localization issue untranslated string "phone number" (label of a text field) in registration screen

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#9626]
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

in the screen for phone number registration is the non-localized string "phone number"
    (there is also a translated string inside the text box, therefore actually redundant)

### Steps to reproduce
- make a reinstallation of Signal with backup restore

**Actual result:** string is non-localized
**Expected result:** string is localized

### Screenshots

![Screenshot_20200515-104044](https://user-images.githubusercontent.com/49990901/82034688-d1f95900-969e-11ea-8523-cf7cf4f5b4b4.png)

### Device info
**Signal version:** 4.59.10

**Comment by Sgn-32** [comment]
@leethater 
i found another similar case like #8842, #8986

line 129 of https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/registration/fragments/RestoreBackupFragment.java

`restoreBackupTime.setText(getString(R.string.RegistrationActivity_backup_timestamp_s, DateUtils.getExtendedRelativeTimeSpanString(requireContext(), Locale.US, backup.getTimestamp())));`

should be:

`restoreBackupTime.setText(getString(R.string.RegistrationActivity_backup_timestamp_s, DateUtils.getExtendedRelativeTimeSpanString(requireContext(), Locale.getDefault(), backup.getTimestamp())));`

**Comment by fumiakiy** [comment]
Hi @Sgn-32 , would you mind if I ask you to file two separate issues for each? I could do too but I don't want to steal your authorship of the issue.

The first one (case b) should be a no brainer, that I could make a pull request fairly easily.

The second one (`app:labeledEditText_label="Phone Number"`) seems a bit tricky because like you said the solution could just be to remove the label. I also found `Phone number` in the translation files, which could be reused here for the label, but it does change the appearance. There is also a discussion around the string in #9403 .

Those are the reasons I would want these two issues filed separately.

**Comment by Sgn-32** [comment]
@fumiakiy i will separate this in two issues.
The related #9403 is not the "Phone Number" label, is the backup timestamp on restoring if new installation.

The string "Phone number" (also the translation) should be the one in the text field, not the label. In the screenshot you see in the text field "Rufnummer" (german translation for Phone Number)

**Comment by fumiakiy** [comment]
Thanks @Sgn-32 . And sorry for my confusion about which one is talking about the issue related to the other issue. I submitted a PR for each issue.
