### ISSUE TITLE
Signal crash, than black screen forewer

### ISSUE THREAD

**Issue by ikino** [signalapp/Signal-Android#9627]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal updated 6 hours ago (now is 15:23 15.5.2020). I want share image to Signal, it crash and now it's black screen when I open Signal. Killing application not help.

### Steps to reproduce
I can test it again, Signal is black screen.

### Screenshots
No screenshot, only black screen.

### Device info

**Device:** Xiaomi 4X
**Android version:** 7.1.2
**Signal version:** 4.60.0

### Link to debug log
I can't get debug log.

**Comment by n0sign4l-official** [comment]
I have a quite similar issue, one of my friends that is using Xiaomi has updated to beta 4.60.0 sent me a messasage (I have 4.58.5 from website installed on my phone) and now I cannot access to Signal anymore... The app keeps stopping, it crashes and so I cannot access, receive any message/call. Lemme know what info you need please fix it ASAP and push an update also on the website, so that I can download the apk. Thanks

**Comment by ikino** [comment]
My black Signal still receive messages and popup notifications, but app is black.

**Comment by greyson-signal** [comment]
If you could get android logcat logs, that would be most helpful. I'm not seeing any crashes in the Play Console that imply any sort of crash loops or crashes at launch in general.

Can get adb here:
https://developer.android.com/studio/command-line/adb

And then:
1. `adb logcat > mylog.txt` 
1. Perform the repro steps
1. Ctrl+C to stop log capture
1. Send `mylog.txt` to greyson@signal.org (or post it here, but *only after looking through it and trimming it* -- raw logs could contain personal information)

**Comment by n0sign4l-official** [comment]
Yes you are not seeying anything cause I haven't got play services in my phone. I get connection refused while connecting to the device (and yes I'm in developer mode)

**Comment by guimspace** [comment]
I've just had a few crashes at launch after update to 4.60.1 (v4.60.0 didn't crash anytime), and sent logs via Google Play Services.

**Comment by ikino** [comment]
No change after update to 4.60.1. Black screen.

**Comment by hupsing** [comment]
Same here on Samsung A3 2017 (SM-A320FL). Android 8.0.0 
Signal 4.60.0 was OK, but 4.60.1 is not starting anymore. Just getting a white screen. 

Update: Just received a signal message from a friend. It popped up in start screen and when tapping on it it switched into signal app. But then switching to chat history just brings a black screen

**Comment by hradcanska** [comment]
Same problem as of yesterday evening, Huawei P9. Opening app just results in black screen (I use dark mode), conversations never load. Restarting phone makes no difference. It doesn't seem to be a crash, it just never opens in the first place and is stuck on the initial blank loading screen. Connected desktop app seems to be working ok at the moment.

**Comment by dmnk** [comment]
Sent a pic via Desktop, Since that a Mix of blank black or white Screens. Share via signal / pick a contact in the Initial share via screen does bring up the contacts communication view.
I Managed to get a ANR Report to be Sent.
Android 8 on a Sony Xperia XZ.

**Comment by zeitwidrig** [comment]
I've had the same issue. I tried installing the [Website distribution build](https://signal.org/android/apk/) but to no avail. So I re-installed Signal via the Play Store but lost all messages in the process since I can't use backups anymore because they're taking up all my internal space which is very limited.
I feel Signal has made some very bad decisions in the recent past:

1. This issue here feels pretty critical. Yet no emergency fix or rollback. Why's that?
2. First you keep nagging us about adding a PIN and finally you force us to create one (as discussed in #9632) - absolute UX disaster.
3. You removed support to save backups on the external SD card (18756aedf6c5bec1e8abd3789710cc5d59d7e090) but didn't reevaluate the issue (#8271). As I mentioned my internal space is already very limited and I can't have Signal clogging it any further with backups. (before the reset it was 600MB - for each backup)

As it was said in multiple other threads (or Play Store reviews): it's hard enough to convince friends to use Signal. You're making it even harder with these terrible UX decisions.

**Comment by guimspace** [comment]
So... My app is working normally again. I think forcing to stop and clearing the cache solved the problem? Or maybe it was the PIN reminder. Anyway, here it is the debug log: https://debuglogs.org/7c5b54fcfe1b56dcd5379743ef7c19152ca4c144e8f018a097ddb43868cb617d

**Comment by ikino** [comment]
> I've had the same issue. I tried installing the [Website distribution build](https://signal.org/android/apk/) but to no avail. So I re-installed Signal via the Play Store but lost all messages in the process since I can't use backups anymore because they're taking up all my internal space which is very limited.
> I feel Signal has made some very poor decisions in the recent past:
>     3. You removed support to save backups on the external SD card ([18756ae](https://github.com/signalapp/Signal-Android/commit/18756aedf6c5bec1e8abd3789710cc5d59d7e090)) but didn't reevaluate the issue (#8271). As I mentioned my internal space is already very limited and I can't have Signal clogging it any further with backups. (before the reset it was 600MB - for each backup)

You are true. My Signal DB is about 8 giga, I don't have storage for 3 backups (2 old + 1 currently created). For me, backpu is impossible. (Samsung S7 witch 32GB storage space).

**Comment by Sgn-32** [comment]
@guimspace 
If you can get running Signal again with cache clearing or otherwise. Then set the language setting to system default.
There are problems with "DynamicLanguageActivity" if the language is set to another language.

For details:
https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-4-60-release

**Comment by hupsing** [comment]
Thanks Sgn-32 👍
My Signal works again. Clearing the app cache and changing the language setting to 'system standard in Signal did the trick 😊

**Comment by dmnk** [comment]
Clearing app Cache and using landscape instand of Portrait made my ui re-appear.

**Comment by ikino** [comment]
Clearing app cache make app work. Xiaomi X4

**Comment by hradcanska** [comment]
Just installed 4.60.3, app is working again. Huawei P9.

**Comment by ikino** [comment]
yes, i generate black screen again (with share image via signal), than install 4.60.3 a it's working :)
