### ISSUE TITLE
"Introducing PINs" screen is not dismissable

### ISSUE THREAD

**Issue by ludocode** [signalapp/Signal-Android#9632]
There is a critical bug in the latest version of Signal. It is not allowing me to view my messages.

### Steps to Reproduce

1. Launch Signal
2. Observe full-screen "Introducing PINs" dialog preventing viewing of messages

### Expected Behaviour

Launching Signal should show me my messages.

### Actual Behaviour

There is no obvious way to view my messages.

----

Last week there was a "Create a PIN" overlay over the bottom third of the screen that couldn't be dismissed. Thankfully it could at least be ignored. As of today this seems to no longer be the case. I now cannot access the message list without creating a PIN. Since I also use the Signal app for my non-Signal text messaging, I cannot send or receive ordinary text messages either.

I don't want to create a PIN. I don't care that you want to store my messages and restore them when I switch phones or whatever. I don't want you to. I would be much happier if I could trust that my messages are just gone after I delete the app rather than have them stored forever in the cloud. PINs do not increase my security and do not at all increase my trust of Signal.

It seems every couple of months there is some change, some new annoyance in Signal that forces me to change my behaviour. I hate this. I just want it to work like a normal messaging app.

This is a serious problem for me because the few people I have convinced to use Signal are now contacting me (over non-Signal messaging) to ask me what PINs are, why Signal is so complicated and doesn't "just work" compared to other messaging apps, and why I won't just talk to them over Facebook Messenger like everyone else. I am running out of answers for them. Either I will lose friends or I will lose Signal.

**Comment by danastasio** [comment]
I created a PIN to get rid of the message and now it asks me for the PIN every few days, "JUST to make sure you didn't forget lol". This needs to go.

**Comment by greyson-signal** [comment]
Hi there, feel free to discuss this on the forum. [There's already a post there](https://community.signalusers.org/t/mandatory-pin-without-clear-explanation-within-the-app-might-cause-significant-number-of-users-to-quit-using-signal/11597/243). Thanks!

@danastasio The reminders back off over time. There will be a reminder in 1 day, 5 days, 7 days, and then afterwards every 2 weeks. We try to make them unobtrusive. It's bit tricky, because we have no way for people to reset their PIN if they forget it when re-registering, so we have these reminders.

**Comment by ludocode** [comment]
The PIN reminders are a whole other problem that honestly should be filed as another bug report. I don't want PIN reminders because I don't want to remember my PIN. That's what my password manager is for! Do you think spaced repetition helps my password manager remember my passwords? Why on earth are you trying to force people to remember passwords when the entire worldwide security community recommends storing randomly generated passwords inside password managers?

I am dreading having to explain this shit to my parents. I already feel bad enough making them use Signal just to get pictures of their granddaughter. I am sure they hate it. This just makes it so much worse.

I guarantee you, the vast majority of Signal users are only using it because they have some weird privacy-obsessed friend (i.e. us) that has roped them into using it. They don't care enough about Signal to memorize a PIN and get constantly tested on whether they remember it. They want it to just work.

It is incredibly disappointing that you are closing these bug reports without discussion. Pointing people to your forums is useless because you aren't providing any real feedback. There are hundreds of forum posts, hundreds of tweets, hundreds of Reddit posts complaining about this issue. This is a disaster and you are ignoring all feedback about it. You are just doing what you want instead of what your users want.

**Comment by greyson-signal** [comment]
It's a tricky thing. There are certain expectations of messengers that we want to be able to fulfill in a secure way, and the most user-friendly approach we've been able to come up with is this [pretty cool system](https://signal.org/blog/secure-value-recovery/) that lets people get a lot of security out of a short PIN. People now almost-universally have a 4-digit PIN for their phone already, so we figured it wouldn't be too burdensome. I know you said you're dreading to explain this to your parents, but I imagine it'd be a bit worse if you told them they had to store a 32-digit randomly-generated password somewhere :)

We point people to the forum because Github isn't great for discussions. Forums are. I've written plenty of replies there, I assure you. Largely in the beta feedback threads, so probably not so many in the one post I linked to. Regardless, I'd appreciate it if the discussion was moved there. Thanks!

**Comment by kototama** [comment]
"Here is a dagger in your throat. But please be nice and express your emotions somewhere else where nobody will listen to you."

**Comment by kototama** [comment]
Also the original problem of this issue was not adressed before closing this ticket.

"Introducing PINs" screen is not dismissable ". The original issue is not about mandatory PIN in general but about the terrible UX for using them.

**Comment by delxg** [comment]
Agreed. One of my relatives was fairly upset with the introduction of PINs. She called me to ask what to do because Signal had locked up all of her messages and she couldn't access them.

I feel bad for convincing her and others to use Signal for SMS.

I think it's a quite rude for Signal to block access to somebody's SMS messages because they won't create a Signal PIN.

**Comment by greyson-signal** [comment]
PINs are mandatory, and will have to be set at some point. We show a non-blocking prompt at the bottom of your conversation list for 8 days before showing the blocking screen. You can also still enter conversations through tapping the notification -- we only show the blocking screen on the conversation list.
