### ISSUE TITLE
Keep successive messages from the same contact in the same window

### ISSUE THREAD

**Issue by jocelynthode** [signalapp/Signal-Android#964]
When someone is posting 3-4 messages back to back, the username shouldn't be displayed each time with a new box for the new message. It adds to the confusion, especially in a group and isn't good looking imho.

**Comment by mcginty** [comment]
We've toyed with it, but it'd require some database changes for it to be efficient enough to push to prod. Not going to happen in the immediate future.

**Comment by Lokesh-Krishna** [comment]
Even if the clumping can't be implemented, can't we make a few minor design changes such as displaying the contact picture of the contact only on the first message in a series of messages and the small triangle that points towards the contact being visible only on the first message in a series? Just looks very redundant, especially the deluge of contact pics.

I was actually [discussing](https://whispersystems.discoursehosting.net/t/redesigning-signals-chat-bubbles/632) updating the message bubbles to keep up with current trends, giving it rounded corners and doing away with the small triangle entirely. Is anybody interested in that? We might also have to give the message input field rounded edges to stay consistent. This would also make it more consistent with the gorgeous iOS version if that counts for anything.

There is an open source app called QKSMS that has great chat bubbles and we could use it for [reference](https://github.com/moezbhatti/qksms).

I have no idea how much time this might take though. Is this too going to be too much effort?

**Comment by Lokesh-Krishna** [comment]
I discovered an [open source collective](https://github.com/opensourcedesign/jobs) that focuses on design today.
If this is a direction that Signal would be okay with taking then can I post a request there?

**Comment by Lokesh-Krishna** [comment]
I just realised that the way the Signal desktop client handles messages is what I've been asking for all this time.
The contact pic is displayed as part of the action bar while individual messages aren't encumbered with contact pics or those tiny arrows pointing towards the screen edge when the nice chat bubble colors already making distinguishing messages a breeze.
Could @liliakai please tell us if this same style can be brought to the Android client too, especially since this is the case with what's called the Android theme to begin with.
