### ISSUE TITLE
Create PIN Message Doesn't Disappear

### ISSUE THREAD

**Issue by 58AF943B9943C4ADDE944** [signalapp/Signal-Android#9647]
On the main screen of the app I see the message "Create a PIN".

I don't want to do this and tabbed somewhere else on the screen. However this message does not go away from the main view. I've forced the app to stop and restarted it, yet it is still showing the message.

I expect that this message can be removed without being forced to create a PIN as the new PIN feature is optional anyway.

This is on Anrdoid 10 on a Pixel 3a with the latest update installed.

**Comment by WSLUser** [comment]
I have same issue on Samsung Galaxy S10

**Comment by alan-signal** [comment]
Moving forward, everyone will have a PIN. That's why you're getting prompted to create one with no way to dismiss.

You can find more detail on this feature on our blog post https://signal.org/blog/signal-pins/

You can also discuss pins on our [forum](https://community.signalusers.org/) if you wish, but I'm closing this issue as we reserve github for bug reports.
