### ISSUE TITLE
Sharing contact adds the wrong country code

### ISSUE THREAD

**Issue by k3anton** [signalapp/Signal-Android#9677]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When sharing a contact using "Share" in Android Contacts, the contacts phone number gets altered and adds +1 in front of their phone number by Signal. This seems to happen if the contact does not have a country code added to their phone number.

### Steps to reproduce
- Go to your Android Contacts
- Pick a contact without a country code in their phone number
- Go to the More Options Menu (three dots)
- Tap 'Share' and select a Signal Contact
- Notice that the number has now changed format and a +1 has been added to the number.

Please note: This has been tested on Samsung S9 and a Nokia 7 as well, both up to date running the 

Additionally, this bug may relate to #9439? 

**Actual result:** The contacts number has been modified with a +1 in front. Causing the contact information to be invalid. 
**Expected result:** The contact information should remain it's integrity when shared with Signal.

### Screenshots
![signal-attachment-2020-06-01-092314_002](https://user-images.githubusercontent.com/10774165/83385591-0ed08a00-a3d9-11ea-8dce-466aa2c79dcc.png)
![signal-attachment-2020-06-01-092314_001](https://user-images.githubusercontent.com/10774165/83385595-109a4d80-a3d9-11ea-9ebe-97b644d1b081.png)

### Device info
**Device:** Pixel 3A
**Android version:** 10
**Signal version:** 4.59.9

### Link to debug log
N/A

**Comment by alan-signal** [comment]
What is the correct country code for this number?

**Comment by k3anton** [comment]
> What is the correct country code for this number?

The number in the screenshots are fake. It it just to prove the bug exists. Feel free to reproduce the bug by following my instructions.

**Comment by alan-signal** [comment]
Please answer: is your own country code not +1?

**Comment by k3anton** [comment]
> Please answer: is your own country code not +1?

My country code is not +1.

**Comment by alan-signal** [comment]
Is your device language set to "English (United States)"?

I'm not saying that changing that is the solution (although it should), just trying to find the source of your issue.

That is where it is getting the +1.

**Comment by k3anton** [comment]
> Is your device language set to "English (United States)"?
Yes, my system language is set to English.

> I'm not saying that changing that is the solution (although it should stop this happening), just trying to find the source of your issue.
> 
> That is where it is getting the +1.

**Comment by alan-signal** [comment]
Sorry, the question wasn't so much about English as which country you have set.

The country dictates the country code. Do you have it set to "English (United States)"?:

![image](https://user-images.githubusercontent.com/48254818/85725795-d700ed80-b6cb-11ea-99e4-5fb380ccbb9d.png)

**Comment by k3anton** [comment]
Right, I do have English (United States) set in my phone. 
I still strongly suggest that this automated country code editing is removed or at least not done without user being prompted about it. The way it works today is sneaky and not very clear to the user.

**Comment by IronJunkie** [comment]
I just had the same issue. However it changed the international dialling code to +44 (UK) one of the other languages I have listed lower down in Android, this despite when I sent it my Signal was showing +1 (had English US as first language).

Update: her Samsung Android phone has language set as English UK, so that is why Signal added the +44 dialling code. However we are both in Australia!

Changing defalt language to Australian on both phones fixed issue. Though guess just changing her phone to Australian would have given her correct international dialling code, ie Australian.

When sharing with Whatsapp the correct Australian code was set as +61, this was before we made any changes to default language (perhaps you can use their method)

Can't Signal deduce country from the country code that it already has from user registration? I can see this becoming a larger issue given recent user base growth, user who are probably less technically savvy than most older Signal users.

(I have another app which only works with language set to English US 😕)

**Comment by ristein** [comment]
this is still an issue.
if I share a contact without a leading country code Signal will add that oft the country I have currently set in settings -> language

**Comment by d2weber** [comment]
In https://github.com/signalapp/Signal-Android/pull/13004 I try to circumvent the issue by using `NATIONAL`  formatting, when the `defaultRegion` has been used while parsing. It could be argued that providing a `defaultRegion` doesn't make sense in the first place.
Unfortunately I currently don't have a local toolchain available to build and test the changes. Maybe a contributor can tell if this solution might be a viable option and if it makes sense to take this further.

**Comment by ristein** [comment]
another thing:
I just mentioned I can not share a contact including birth date. This could be fixed when looking into here anyway...

**Comment by Jasper-Ben** [comment]
> Sorry, the question wasn't so much about English as which country you have set.
> 
> The country dictates the country code. Do you have it set to "English (United States)"?:
> 
> ![image](https://user-images.githubusercontent.com/48254818/85725795-d700ed80-b6cb-11ea-99e4-5fb380ccbb9d.png)

Can confirm that this is due to the language settings. Sharing a contact without an explicit country code with my wife will show up as +44 on my end (language set to english uk) and +1 on her end (language set to english us). We live in Germany (+49). When saving the contact it will be saved without the country code.

Sharing a contact that has a country code included shows up correctly.

I don't think it is a good idea to tie the country code to the phone language settings. This is just bound to cause confusion. The chance of someone having their phone language not set to their country of residency is quite high.

**Comment by 4SH-gaupee** [comment]
Just to bump this up, it is still an issue, I got a french contact shared to my phone where the language is English UK, got a +44 as country code instead of +33.

**Comment by dub4u** [comment]
Bumping too. I'm in the Philippines, there is no language setting "English (Philippines)" and so all PH contacts without country code are being shared with +44 prefix, the language I have set. Sharing the same contact through WhatsApp correctly sets the country code to +63
