### ISSUE TITLE
A link (with a apostrof ) i pasted in a signal message did not work

### ISSUE THREAD

**Issue by Gerard64** [signalapp/Signal-Android#9707]
In Android Signal app i sended a link with a apostrof in a post.
`https://nl.m.wikipedia.org/wiki/Singin'_in_the_Rain`
Wen my mother after clicked the link she is send to https://nl.m.wikipedia.org/wiki/Sh%C3%ABngjin

**Comment by Melud** [comment]
Still reproducible in 2026. Same issue with a different URL:
https://www.who.int/news/item/07-02-2000-world-health-organization-assesses-the-world's-health-systems
The link gets cut right before the apostrophe, so only the truncated portion is treated as a clickable link:
https://www.who.int/news/item/07-02-2000-world-health-organization-assesses-the-world
Everything after the apostrophe (`'s-health-systems`) is left as plain text and the link opens a broken/incomplete URL. Seems related to #14084, #9449, and #6224 — the link parser appears to mishandle several punctuation characters in a URL.
From what was mentioned earlier in this thread, this apparently comes from a bug on Google's side (Linkify.WEB_URLS), with no planned workaround on Signal's end since it would need to be fixed upstream. Just adding this as another confirmed real-world occurrence in case it's useful for tracking impact / prioritization.
