### ISSUE TITLE
Profile name showing instead of contact name

### ISSUE THREAD

**Issue by SinTan1729** [signalapp/Signal-Android#9739]
I finally convinced my girlfriend to start using Signal. Now she's saying that she can't see my contact name (a nickname that she uses) and instead, there's my first name (as given in my profile).
How can this be fixed?

**Comment by Sgn-32** [comment]
Has your girlfriend saved your number on the mobile device?
Your profile is shown if somebody hasn't you in your contact list.

Read more:
https://support.signal.org/hc/en-us/articles/360007459591-Signal-Profiles-and-Message-Requests

**Comment by SinTan1729** [comment]
> Has your girlfriend saved your number on the mobile device?
> Your profile is shown if somebody hasn't you in your contact list.
> 
> Read more:
> https://support.signal.org/hc/en-us/articles/360007459591-Signal-Profiles-and-Message-Requests

Yes, of course she has it saved (shouldn't even be a question lol).

**Comment by UserX404** [comment]
She has to grant contacts permission an sync them. This could be done within signals contacts list with a swipe-down.

**Comment by SinTan1729** [comment]
> She has to grant contacts permission an sync them. This could be done within signals contacts list with a swipe-down.

I did ask her to double check if she had granted contacts access and she said that she has. I'll ask her to do the swipe-down and tell you if it worked.

**Comment by SinTan1729** [comment]
It didn't work, unfortunately. Still the same condition.

**Comment by greyson-signal** [comment]
So we definitely prefer using contact names if one is available. So somehow we're either not able to link your account to your contact, or we aren't able to get the correct name from your contact.

To check if your contact is linked, have your girlfriend go to your contact in her system contacts app, and see if there's a shortcut to send you a Signal message from that screen. If so, that contact has been found by Signal.

If it's been found, have her verify that the nickname she uses is set as your actual name, and not in some secondary nickname field. Also, if she clicks the shortcut, see if that takes her to the correct conversation.

If it hasn't been found, it could be because of a phone number formatting issue, possibly due to country codes. Try making sure to put the full number (with country code and area code).

That's my first collection of suggestions :)

**Comment by SinTan1729** [comment]
@greyson-signal Alright. I'll try out all of those.
