### ISSUE TITLE
Font contrast issue in light theme

### ISSUE THREAD

**Issue by Akash0123G** [signalapp/Signal-Android#9743]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Font contrast in the ellipsis menu on the main screen and contacts screen is very low, words are barely visible.

### Steps to reproduce
- set system theme to dark and signal app theme to light

### Screenshots
![signal-2020-06-17-173055](https://user-images.githubusercontent.com/67055157/84897567-6d795180-b0c3-11ea-82aa-eb84cdbde5e3.jpg)
![signal-2020-06-17-172952](https://user-images.githubusercontent.com/67055157/84897570-6eaa7e80-b0c3-11ea-8fee-15f60bda43f1.jpg)

### Device info

**Device:** Nokia 4.2
**Android version:** 10
**Signal version:** 4.64.0

**Comment by u32i64** [comment]
Noticed this on Pixel 3 XL, Android 11 beta 1, Signal 4.64.0 as well.

I think https://github.com/signalapp/Signal-Android/commit/a9ea1d760650b8ce93bc1143735c23c7393de875 caused this. It appears to make sure that the background (when the app is launching) matches the theme. However it uses the system theme for this decision, not Signal's, and because of this it affects some labels as well.

**Comment by Akash0123G** [comment]
This issue is fixed in Signal version 4.64.5
