### ISSUE TITLE
Newly Downloaded Video From Silde For Reddit Not Showing Up In Signal Gallery

### ISSUE THREAD

**Issue by chantisnake** [signalapp/Signal-Android#9782]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Newly downloaded videos (mp4) from [slide for Reddit](https://f-droid.org/en/packages/me.ccrama.redditslide/) is not found in signal.

On the other hand, I have tried downloading a video using my browser, signal finds the video with no problem, and I have moved video downloaded to video storage folder of Slide for Reddit, signal seems also able to find the video.

And my gallery app ([Simple Gallery](https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/)) can find newly downloaded video without a problem.

And this bug only exists for newly downloaded videos. After several days the video will show up in signal gallery just fine.

### Steps to reproduce
- download a video from Slide for Reddit
- go to a conversation in signal
- click on the `+` button on the lower right
- click `Gallery`

**Actual result:**
The video will not show up on all the following
- the preview from clicking the `+` button
- when click `Gallery` and navigate to `all photo`
- when click `Gallery` and navigate to the correct folder that contains the video

**Expected result:** 
Should show up on all three places mentioned above

### Device info

**Device:** OnePlus 6 With Lineage OS
**Android version:** 10
**Signal version:** 4.64.5.6622

### Link to debug log

https://debuglogs.org/d5cac0b1daa6c04968bd7d8996f75c3ce64463c8de93bf5096a6bc988186bd4f

**Comment by greyson-signal** [comment]
When it comes to rendering media that's already on your device, we defer entirely to the system. We basically just ask your phone to tell us what media you have. If something isn't in the list, then the problem lies with your OS, or perhaps with how the app in question is saving media. The fact that it shows up  sometime later makes me think that the app is putting media in a place that is only re-indexed periodically by your system.

To see more about how we find media, you can see the code here:
https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/mediasend/MediaRepository.java#L189
