### ISSUE TITLE
Voice Message Freezes Signal

### ISSUE THREAD

**Issue by Dwyte** [signalapp/Signal-Android#9786]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Everytime there's a voice message the app starts freezes then goes back to conversations list or crashes.

### Steps to reproduce
- Go to any convo that has voice message
- Scroll up until see a voice message
- Or just send a voice message

**Actual result:** Once a voice message is shown into the list it'll start the freezing then goes back to conversations list, If the voice message is one of the latest messages on the convo meaning can be seen without scrolling, the convo wont even finish opening it'll start freezing then crash exits.
**Expected result:** It shouldn't freeze and crashes.

### Screenshots

![gifout](https://user-images.githubusercontent.com/30210654/85736536-26c5d000-b731-11ea-92f3-b5a6b4357ceb.gif)

### Device info

**Device:** OPPO A71
**Android version:** 7.1.1
**Signal version:** 4.64.7.6642

### Link to debug log
https://debuglogs.org/b5a42bb838700889730544f2cda5eaa0d35b565ca6d7bb9149bf645e508835a1

**Comment by Dwyte** [comment]
This was all good before I updated, the version I used before still had the old call design, I updated to the latest version cause it alerted me that my signal is expiring in 9 days, that was June 23 4pm UTC. Not sure if this info helps hehe.

**Comment by danielboegner** [comment]
I have the same issue. On 2020-06-12 I sent a report including debug log to support@signal.org. I used the settings -> help -> "Contact us" function of the android app to do that. Since then there were at least two signal updates.

I only received one single voice message recently from which I was talking about in the support email. So I cannot tell if this issue is related to this specific contact or message. There is no frequency curve displayed at this new message. Maybe there is something wrong with it. The app should not crash even if it is so. 

**It is important to say that I was not able to send messages to this contact until I found the workaround (see below).** That makes this issue a little more important I think. Not everyone will come up with this workaround (even if it is easy). In my case I couldn't write to one of my most important contacts. Calling was not always appropriate which got me into a scrape a couple of times.

I went back to another conversation with older voice messages. These messages are working fine. I can see the frequency curve an it does play fine. 

@Dwyte Do you have the same issue with multiple voice messages? From different contacts? How about older voice messages?

I can confirm that when the message is one of the least received an will be displayed without scrolling the app goes back to the conversations list or crashes. If the voice message moves up out of the view port than the app behaves normal until you scroll up to the voice message. Than it goes back again to the conversation list or crashes.

I can confirm that when the message is one of the least received an will be displayed without scrolling the app goes back to the conversations list or crashes. If the voice message moves up out of the view port than the app behaves normal until you scroll up to the voice message. Than it goes back again to the conversation list or crashes.

The problematic voice message is not even displayed in Signal Desktop (Linux).

**Workaround:** 
It is still possible to call a contact by touching the avatar image in the conversation list. You can ask you contact to send you some messages so that the voice message moves out of the initial view port. Maybe if you call the contact a couple of times yourself it might have the same effect, but I do not know that for sure.

I thought of deleting the conversation or the app or something like this, but I would like to loose no data. The problematic voice message is probably not really important. 

**Device info**

**Device:** Meizu MX6 (M685H)
**Android version:** Flyme 5.24.0G based on android 6.0
**Signal version:** 4.64.7 (now) When I received the message it must have been at least two updates before.

**Comment by Dwyte** [comment]
I too has submitted debug logs from the android app the first time I was experiencing the bug. Yes the age of the voice message doesn't seem to matter even very old ones causes it to crash. I can confirm the problem doesn't occur on the linux desktop version. I hope this gets resolve soon.

**Comment by danielboegner** [comment]
I'm sorry but I have to revoke the workaround at least partially. The bug occurred and I was trying get it working without success. I wasn't able to send text messages to this specific contact. I gave up and the contact and I just called each other via signal instead of writing. After a couple of days I tried it again and I was surprised to see, that I was able to write text messages again until I do not scroll up to the buggy voice message. In the conversation I saw the entries of the calls which has moved up the voice message entry. That is why I thought that we could workaround the bug by sending text messages to move voice message entries out of the view port, but actually I didn't try it this way. I apologize for that.

As my last report here was based on only one buggy message and having a workaround at hand I thought I could try to find out more. I asked my contact to send me another voice message. This voice message triggers the bug like the first one. I tried to use the workaround to get the conversation to a usable state. Unfortunately the workaround didn't work. I asked my contact to send me longer text messaged and pictures, to call me and I called the contact, too. When enter the conversation the voice message is still in the view port together with parts of the next text message beneath. If I react quick I can start scrolling down but the app still goes back to the conversation list or crashes. I terminated the app which did not help.

I will edit my last report to notify other users.

I couldn't see the first buggy voice message in Signal Desktop. Maybe it was not connected to the server or some time so that the message was deleted on the server meanwhile and Signal Desktop could not fetch it. The new voice message I received today is displayed in Signal Desktop but does not play!

My contact's system is this:
Hardware: OnePlus 6T (A6013)
Android: 9
today Signal version: 4.64.7 (6642)

If the workaround would work reliably I would ask another contact to send me a voice message but I won't block the ability to send them texts. Some of them don't want to be called.

@Dwyte: That's not what I wrote. I wrote: "I went back to another conversation with older voice messages. These messages are working fine. I can see the frequency curve an it does play fine." So in my case the age of a voice message does seem to matter. But I can not exclude other factors. I.E. The contact may matter. Anyway it is suspicious that you see older messages to trigger the bug too while I do not.

**Comment by danielboegner** [comment]
I get careful now with propagating workarounds but maybe signal Desktop might help. I wrote a text message from Signal Desktop now. This not only worked. After that I the conversation on Signal android has scrolled down so that the buggy voice message is out of the view port. I am able the send text messages from android again! I think it was similar the first time.

Can somebody confirm this?

**Comment by alan-signal** [comment]
If anyone who has this problem is on the Beta 4.65.1, can you tell me if the conversations can now open?

**Comment by Dwyte** [comment]
@alan-signal sorry for the late reply, I use aurora store, is it possible for me to test it via apk installation?

**Comment by u32i64** [comment]
@Dwyte version 4.65.2 is already released to production so you should be able to download it the same way you usually do.

**Comment by Dwyte** [comment]
The bug still appears, but now behaves differently, I will write more in detail later.

**Comment by Dwyte** [comment]
The bug occurs now only on the first load of a voice message. Like when you scroll to a vm it'll crash first, then when you try scroll to that vm again it'll be ok, no crash and playable.

**Observe**
![signal-2020-07-04-224051](https://user-images.githubusercontent.com/30210654/86514859-80bc4900-be47-11ea-9ac3-3476b51cd5bb.gif)

See here it crashed on the first vm, then next try it didn't crashed on the first vm but the 2nd older vm crashed it, on final they're both I think "loaded" so it didn't crashed and both are playable. Loaded might not be the right term, but I can't think of any how to describe it.

Here is a debug log:
https://debuglogs.org/606dc7b4a49c3fd01d4184901fb3be91db44e1d75b733d75085a271209dadbb0

**Comment by danielboegner** [comment]
I can confirm that behavior. I am on version 4.65.2.

**Comment by danielboegner** [comment]
The issue is still alive on 4.68.8. I had cases where the app not goes only back to the list of conversations but crashes again. I wonder if this is a regression bug. It is also possible, that I tests where I confirmed the behavior of going back to conversation list covered not enough cases. Sometimes before the app crashes or goes back to the conversation list the screen gets completely blank or white. I use dark theme.

Fortunately when I go into the conversation again after one or two tries the app works fine so in this state it is usable and not a total blocker. 

I made two new discoveries:

1. I received voice messages from an iPhone without any problems. So maybe this bug is not included in the iPhone version. I think the code bases between Signal android and iPhone are different, but maybe a comparison helps to track the issue down.

2. The issue occurs not only when I receive a voice message and try to open it. It also occurs when I record and send a voice message to someone else. Even if I send it to "note to myself". And even if I send it to an iPhone.

As there are only two people here reporting this issue I think it does affect relatively small part of Signal users. Maybe it is related to specific android versions or devices. What do you think?
