### ISSUE TITLE
APK size is too large

### ISSUE THREAD

**Issue by kousu** [signalapp/Signal-Android#9797]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I cannot install Signal's updates.

Signal was taking 70MB in /data/app/org.thoughtcrime.securesms-1. It downloaded its update apk to /data/media/0/Android/data/org.thoughtcrime.securesms/files which was another 70MB, and those two together, plus the unpacking during the installation process, failed the install. My phone is decent but it's not a flagship device: I have about 250MB free on my phone at all times, which is a fairly generous reserve given the hardware.

For about a year now I've been having to wipe my Signal .mms files and clear out my synced emails and double-check for photos to offload every time a new Signal update comes in because the temporary spike in storage usage that comes during the install would often make it fail with Android's obscure "App Not Installed" error. But this time I additionally *had to move the APK to my external SD card* to make room. When I finally did get update installed the /data/app part is now 100MB -- or fully 5% of my available storage.  I wonder what got added in the last month that took 30MB? Was it the face detector?

If Signal keeps growing in size I am going to have to stop using it, and so will anyone who is running on used/budget phones.

For comparison, Discord is 110MB. WhatsApp is 55MB. Conversations is 30MB, and that's only after a big update that added VoIP (previously it was 12MB).

### Steps to reproduce

- wait for the Signal update notification to come
- click the notification
- sometimes: immediately get "App Not Installed",
- sometimes: the APK is pre-unpacked and I can press "Install", but then I get "Out of space: Manage Space?"

**Actual result:** Signal fails to install.
**Expected result:** Signal should install.

### Screenshots

![signal-2020-06-26-234649](https://user-images.githubusercontent.com/987487/85914053-09b00080-b808-11ea-8fd1-e2127eab0c1b.png)

(I missed getting a screenshot of the update notification or the install failing, but I'm sure I'll get it again in a few days when the next update comes)

### Device info

**Device:** Motorola Moto E (condor)
**Android version:** 7.1.2
**Signal version:** 4.64.7

### Thanks

Also, let me say that I really do appreciate the work you've done to get encryption in the hands of regular folks. It's key to making it a realistic option. Stay safe and stay strong.

**Comment by kousu** [comment]
Let me just add that I know a workaround might be to reformat my external SD card as [adoptable storage](https://source.android.com/devices/storage/adoptable) except

1. adoptable storage was pretty glitchy/poorly supported the last time I tried it with several apps, so I would rather not
2. I don't think Signal allows me to move it to an SD card anyway?

**Comment by vertigo220** [comment]
Unfortunately, this is an Android "issue," since it needs enough space for the update and for processing it, i.e. unpacking and merging with the old apk, which may also require keeping the old one around until it's done. If there's not enough free space, there's nothing that can be done. The only thing Signal can do is shrink the apk, which should of course always be done if possible. I can't imagine you need to post any further info to help, since they can't really do anything to specifically help your situation.

As for adoptable storage, I've only messed with it a little, so I have no idea how well it works, but I *believe* when you set it up that way, apps see the SD as internal storage, so Signal *should* work just fine.

Instead, if possible, I'd recommend putting everything you possibly can on the SD card (files/photos/music/apps) and clear cache of apps that tend to grow large (browsers, image galleries, mail, keyboards, social media, etc) in order to free up enough space to do the update. It's not a solution, and it's a PITA, but it's an unfortunate necessity until manufacturers start putting usable amounts of storage in phones for reasonable prices.

**Comment by greyson-signal** [comment]
I'm going to close this issue, only because I don't believe it has a definitive "fixed" point we can track. I will say that we have multiple work items planned in the coming weeks to reduce our APK size. Hopefully they will help!

**Comment by kousu** [comment]
Thank you @greyson-signal, that's good news! It might still be too late for my device but I appreciate that you're not insensitive to tech accessibility.
