### ISSUE TITLE
Crash on restoring backup from old signal version

### ISSUE THREAD

**Issue by EmilVogt** [signalapp/Signal-Android#9808]
A friend got a new phone and wants to move Signal from his old one to the new one. The old phone had Android 4.2, that's why he was using Signal 4.36.2 until yesterday. He created a backup and copied it to the new phone. He installed Signal (newest version, 4.64.7) and on first start it recognized the backup. He's asked if he wants to restore from backup, he pressed "restore from backup" and entered the passphrase. The counter starts running up to several thousand messages. Then Signal suddenly closes. When reopening Signal, he's asked again, if he wants to restore from backup.

**Steps to reproduce:**
- Create backup in Signal 4.36.2 on old phone
- Move backup to new phone
- Install Signal (4.64.7) on new phone
- Start Signal on new phone for the first time
- Press "restore from backup" and enter passphrase
- The counter counts several thousand messages, but suddenly Signal closes/crashes
- When reopening Signal, you will see the screen again, where you can restore from backup or skip.

**Information on phone:**
Model: Nokia 7.2
Android version: 10
Signal version: 4.64.7

**Debug log:**
[https://debuglogs.org/c888009f1b79b92187a5d22c99ccd7178828f4e4e409f35b19d94e4916c917f7](https://debuglogs.org/c888009f1b79b92187a5d22c99ccd7178828f4e4e409f35b19d94e4916c917f7) (from new phone)

I know that the version of Signal, which can create backups, is very old. Can you please let me know if it's possible to successfully restore these backups? Then he can wait until this is fixed. Otherwise he'd have to create a new account and lose all of his old messages.

**Comment by Sgn-32** [comment]
From the debug log:

`2020-06-30 14:41:22.271 MESZ W FullBackupImporter: Bad MAC for attachment 1546813406619! Can't restore it.`

Maybe this could be a workaround and solve the issue (but no guarantee):

If your friend has access to the old phone with a working Signal, he should search for an attachment from Sun Jan 06 2019 22:23:26 (UTC) and delete it. Then make a new backup and try to restore on the new phone.

**Comment by EmilVogt** [comment]
Thanks, I will try that.

**Comment by EmilVogt** [comment]
Removing the malformed media solved the issue. Creating a new backup without it and restoring on the new phone worked. Thank you so much!

**Comment by Sgn-32** [comment]
Found also a commit "Skip corrupt attachments during backup restore". Seems like this didn't work in this case.

https://github.com/signalapp/Signal-Android/commit/17b5816d5b66273e699df69eec40ced76def4554

**Comment by TimeScience** [comment]
I'm getting the same problem as described above. I made a backup Aug 1, 2020 and verified the backup. Sent my phone for a repair, now on Aug 11, with the repaired phone (new device but same make/model) , I put in my passcode to restore and it starts to unpack messages and then hangs at message 5201 and says "Bad Passcode". If I put in an actually wrong passcode, it says the code is wrong right away, as expected. Seems that message 5201 has a bad attachment or something as described in #8355 
I used signal for 3 and a half years in a relationship that just ended and this is my only record of our written communications over that entire time. It would be really too bad if I lost all that just because signal can't skip a single bad attachment and out of tens of thousands of messages.

I still have Signal on my PC and I can see all the messages fine there. But there doesn't appear to be a way to save them or relink to my phone from the full messages still on my computer. It is super frustrating to see they all still exist on my PC but there is no way to push them back to my phone.

Any suggestions? 

(Samsung S9, Signal version 4.68.8)
