### ISSUE TITLE
Unable to use Signal, which is hijacked by "Introducing PINs" view

### ISSUE THREAD

**Issue by bz-fsecure** [signalapp/Signal-Android#9812]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
"Introducing PINs" screen is visible at all times after launching Signal. It is not possible to use Signal as intended. It is not possible to create backup, access settings nor do anything at all.

### Steps to reproduce
- Open "Signal"
- The message view is briefly showed and then it is covered by "Introducing PINs" view

**Actual result:**
Signal is no longer a messaging/text app. It is a single "view" app showing only "Introducing PINs" screen.

**Expected result:**
Be able to access messages, settings, backup options as it was without "Introducing PINs" view obstructing access to the app.

### Device info

**Device:** Lenove K5 Vibe
**Android version:** 9
**Signal version:** 4.64.7

### Link to debug log
Capturing the debug log is not possible as the "Introducing PINs" view blocks access to everything.

**Comment by greyson-signal** [comment]
Are you not able to create a PIN?

**Comment by Trombonista** [comment]
Did affect me too. Was able to assign a PIN, but the bug part was: it just came while trying to answer an incoming message. The "PIN requested" should come up at application startup (even better: first app startup after update), not midtime within usage IMO.

**Comment by greyson-signal** [comment]
Tapping a notification should still bring you to the conversation. It only comes up when you go to the conversation list directly (by tapping the app icon, for instance). Just personally verified this to be sure.

We're entering the mandatory phase of the PIN rollout. We've been showing a bubble at the bottom of the conversation list asking you to create a PIN for probably over a month now? I feel ok with doing a blocking flow when viewing the conversation list, while keeping the ability to still interact with notifications. FWIW we also don't show the screen if you don't have network access, so we've also taken that precaution.

**Comment by Trombonista** [comment]
The "usability comment" does not perfectly apply IMO because one not always does the technical way. Maybe I did not jump directly from notification to message but I have been in the process of answering a message when I got interrupted.

I do not understand what relates "for a long while PIN should have been entered" with "Signal gets locked suddenly". If it is intended that any time the app might cease its operation well then it ain't a bug. I have a different view and do not understand why I should not report something looking like a bug when enrolled in beta program.

**Comment by bz-fsecure** [comment]
I don't want to create a PIN as I don't want to store my contacts in the Signal cloud. Signal is a messaging app so I don't see a reason to store contacts with it. But that's beyond the scope of the bug. 
I am not able to access settings ie. to remove an account from Signal or to create a backup. So basically Signal keeps my data hostage in order to force me to create a PIN and exfiltrate my contacts.
This is borderline poor UX and ransomware.

**Comment by bz-fsecure** [comment]
>  FWIW we also don't show the screen if you don't have network access, so we've also taken that precaution.

Thanks for this workaround.

**Comment by itkfm** [comment]
How about those who don't want to have a PIN. e.g. because they don't care about those features that would require it? (or hypothetically, how about those who don't want their stuff uploaded at all, not even encrypted?)

**Comment by itkfm** [comment]
> **I feel ok** with doing a blocking flow when viewing the conversation list

I feel patronized and discriminated.

> while keeping the ability to still interact with notifications.

which is just horrible usability. I'd even claim it makes the app mostly unusable.

**Comment by SandyShores** [comment]
Just noticed this too. It's completely freaking horrible. Waiting for an update that undoes this or uninstalling within the week. Otherwise I have to go around and convince every single contact who I had to convince to install Signal just to use it with me in the first place, to remember some stupid pin, which can not be 1111 btw even if you do not give the slightest *** about that so called "feature", to be able to contact me, and if they don't, or can't, well *** them I suppose?! Jesus, who comes up with stuff like this?

HAVE YOU ANY IDEA THE HOURS IT WILL COST TO EXPLAIN THIS TO MY ELDERLY RELATIVES?!?!? AND TO AGAIN AND AGAIN RESTORE/REMIND THEM OF THEIR PINS?!

What do you mean youngin, pin, I know my pin, I've had the same one for 15 years. What do you mean another pin? No youngin, I know my pin, it's.... No no, there is no other pin. I know my pin, I've had the same one for 15 years. What do you mean another pin? No youngin, ... *suicidal thoughts*

You don't simply add new "features" like that...

"I feel ok with doing a blocking flow", well I feel ok uninstalling this (suddenly and without reason) unusable piece of *** instead of spending my summer like this, having to visit everyone in person because phone instructions somehow don't work, always, as anyone who has any elderly relatives and knows anything about computers knows.

And btw, **if you can't turn it off, it's a bug, not a feature.**

Thank you for the otherwise, and until now, great messenger, though... my #1, so far, but that's super, super annoying, and incredibly poorly thought out, no matter how long you've been showing users the "IT PUTS THE LOTION ON ITS SKIN OR ELSE IT GETS THE HOSE AGAIN" screen.

Please do consider your user base wider than just teeny cloudy hipsters who need to sync their messages across 17 devices...

Again, thanks guys, otherwise, great messenger.

**Comment by itkfm** [comment]
I mean. It's not even consistent. I can use **Signal Desktop** just fine and pretend there's never been a PIN or anything.

**Comment by ignus2** [comment]
Workaround: turn off the network before opening Signal (airplane mode), then turn it back on. That way the nag screen won't show. (Until they decide to close this loophole).

**Comment by greyson-signal** [comment]
Feel free to read the blog posts we've written about how PINs and Secure Value Recovery work:

https://signal.org/blog/signal-pins/
https://signal.org/blog/improving-registration-lock/

**Comment by bz-fsecure** [comment]
"My way or the highway" attitude will not improve trust and build community around this project. Seriously, the fact that there is a workaround does not mean that this is not an issue and that it will not affect huge number of users.
Regarding the blog posts, I have read them and they don't answer the most significant issue: why would I want to store my contacts in your cloud? They also does not explain why suddenly the trust is moved from project with source code available on github(not to be confused with open source, which imho Signal no longer is) to the proprietary hardware implementation provided by US company.

**Comment by grandchild** [comment]
I for one think it's a good move in the long run, even though it might seem controversial now. I know quite a few people who are still primarily on Telegram -- _fully aware of the unencrypted nature of it_ -- simply because the "I-lost/changed/bricked-my-device" experience on Signal is currently lacking.

@bz-fsecure, the most likely answer to your question is: "You might not, but the Signal devs seem to feel that _most_ people would prefer having easy recovery of contacts and groups, vs... not." And the crucial point is in the word "_most_", it's a decision they made in order to make Signal (again in their view, which I happen to agree with here) better for _most_ people.

Signal has made strides towards making features that are convenient and commonplace in other messengers available to Signal users by going the extra mile to make it secure, or to make the security & privacy tradeoffs (which are sometimes necessary) bearable. I for one welcome our new insect overlords ;)

I have to agree on one point though, @bz-fsecure, that I'm less than absolutely convinced of SGX, but, honestly, I am willing to make that tradeoff. This is not "my way or the highway" in my opinion, but a choice. It has to go one way and not both. The alternative would be to overload Signal with an unmaintanable amount of options. The fact that the settings menu is as complex as it is now, _with the express design goal_ of "another option is not the answer" is, I think, not a sign of that goal failing but a testament to how ridiculous the options would be if that design goal didn't exist.

**Comment by BryanQuigley** [comment]
"Currently, that also happens to mean that if your hands accidentally lose your phone to the toilet, your information in Signal is lost along with it."

That is why I use Signal. I get that that is a bug for some, but that is a feature for me.

**Comment by sirius-c** [comment]
For me it is a terrible usability mistake to force a PIN and to not to have an option "No, thanks, I do not want a PIN."

It is a mandatory requirement for me to not enter a password more than once when logging into a device. After this, all secrets for all programs should come from a system key ring or other credential storage. It is fine of course to optionally allow an extra security check if the users opts to do so, but it must not be mandatory.

One can set a PIN (1111 does not work, but 1122 works does) and forget about it - but this is extra dubious, why set it at all, then? 

No reason to  dump Signal right away, it still has some singular features - maybe a reason why the devs think they can enforce this PIN -, but it makes recommending Signal to others impossible for me now.

It should be up to the user if he wants the toilet protection or not. I do not need it, I can make a new Signal account if flushed down.

Forcing to remember another secret (PIN or password) is extremely inconvenient and the extra security that it provides exceeds for many people their needs - extra effort for no benefit. Now all these people could drop or not start to use Signal, arguably, but, devs, is that desirable?

**Comment by bz-fsecure** [comment]
> "You might not, but the Signal devs seem to feel that _most_ people would prefer having easy recovery of contacts and groups, vs... not." And the crucial point is in the word "_most_"

@grandchild Unfortunately it's not. The crucial point is "_feel that_". No one has actually asked majority nor anyone for that matter. I do understand that some people might want such feature. Though there is definitely a lot of people being unhappy about it.

While I myself find the PINs unnecessary to say the least, this issue is about certain behavior of the app, which was not fixed. Developers response here(ie. closing issue almost instantly) shows that they don't care about community opinions nor user issues. 

In addition the devs are outright hostile towards the forks (see: https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165) and specifically towards the forks using their servers and messaging with **their** users. While I do appreciate the tremendous work of developing the application, I don't believe that it's user-base is build solely on the app greatness rather then on the grass-roots of more privacy/security-minded users recommending it to their peers. Those users trust has been betrayed. Instead of inviting their peers into privacy and security oriented messenger, they invited them into a trap governed by superiority assuming development team with no regard for community. I for one don't welcome that.

At this point it would not surprise if a future release of the app would ask for your credit card with "all covering" banner. Just to ensure that it's stored safely.

**Comment by cpmcgrath** [comment]
I think signal should strongly consider reversing this choice at least for the moment, I think the feedback has been pretty overwhelming. I think the problem with this isn't with the concept behind it, but the UX and marketing

When it first showed up for me I had no idea the PIN was for - I'm a developer so imagine the confusion for those less technical. Calling something a PIN means people make assumptions about it - mainly that it's a lock, and that it can lock you out of the app. Consider calling it something like "Backup PIN" - it gives a context on what the PIN is used for.

Next, the first sentence in all marketing and documentation about this should have been - YOUR MESSAGES STAY ON YOUR PHONE ONLY,  THEY DO NOT GET BACKED UP TO THE SERVER - So many people missed this point and were concerned. Yes it's mentioned, but not clearly enough

Then there's the timeframe, you say a month is enough. I'm sorry, it's not. Especially during a pandemic. 6 months minimum probably more like a year.  It could get more aggressive with the requests in that time. As some people have noted, some of us more technical people have installed signal for others, thus we need time to be able to go through this process with them - never underestimate the benefit of having an actual person hand hold people through the process.

Finally, you've communicated the benefits this, but not why it should be **mandatory**. 
* Your contacts can sync if you get a new phone? Well, that's a subset of my full contact list, so that already happens.
* You can restore the groups you had? Yeah, but can't I just get someone in the group to send a message to the group and it appears? Also many/most people just don't have enough contacts on signal yet to use groups
* Your profile? My name and photo? Probably time I update the photo!
* Future support for contacts without phone numbers? That sounds cool, but I doubt I'd actually use it.
So why do I need this feature?

With all that in mind, why not focus the UX on the backup functionality, let people choose what to backup - not only does that give the user more control, but it explains the feature. It explains that messages don't get backed up, it explains what the PIN is actually for and gives context, and if people choose not to back anything up, then no need for them to enter a PIN. A simple UX doesn't mean a barebones UX.

**Comment by brianlheim** [comment]
I agree with the above commenters. I think this should be made 100% optional and the ramifications more clearly explained. Up until this point I have trusted Signal to be straightforward and honest about what the app does, perhaps naively. After this change I have permanently lost that trust.

> why would I want to store my contacts in your cloud? They also does not explain why suddenly the trust is moved from project with source code available on github(not to be confused with open source, which imho Signal no longer is) to the proprietary hardware implementation provided by US company.

This is the fundamental question. And the reason it is not answered in the article is that there _is no_ justification for why you would want to do that, and so it should not be forced on people.

**Comment by greyson-signal** [comment]
Hey folks, sorry, but this has gotten off-topic. The claim in the original report was addressed. As is mentioned in our issue template, we use github for bugs, not discussion topics. You're more than welcome to discuss this on the [forum](https://community.signalusers.org/). Thanks!
