### ISSUE TITLE
Missing option to cancel an upload

### ISSUE THREAD

**Issue by sirius-c** [signalapp/Signal-Android#9824]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is no way to cancel an upload.

If (for example by accident) one chooses a large file over a slow internet connection, no way to stop the upload other then by force removing and reinstalling Signal, which a contact of mine felt compelled to do twice already (losing all message history etc).

It seems that #9585 is fixed, at least this time messaging was still possible while uploading, but cancelling a long duration operation is a standard feature of any application. Not having it is a bad design bug (judging in particular by the unfortunate consequence I had to witnessed)

### Steps to reproduce
Upload a big file and try to cancel the upload.

**Actual result:** No way to stop the upload, not even by deleting the file and restarting the phone.
**Expected result:** There should be a button 'Cancel'.

**Comment by navid-zamani** [comment]
You can just long press on the message, and tap on the trash can, to delete it. If that doesn't stop the transfer itself, which it doesn't on my device, and which does feel like a bug to me, then force-close Signal, and turn your mobile connection off, wait a few seconds, and on again. That definitely does the job for me.

So this is not a bug, except in the general design of think-they-are-smart-and-you-are-dumb-phones (”smartphones"), Apple-style, imitated by Android, where the mindset is that if you hide important functionality in a way that nobody can find it unless he gets lucky by accident, making the whole UI limiting and cumbersome, then that counts as ”simple“ and ”user-friendly“.

**Comment by sirius-c** [comment]
Thanks for the work around suggestion, but my contact could not even stop the upload by restarting the device. Upload continued as soon as Signal was launched.

In any case, needing to turn off network or restarting the phone (if that would have worked) to stop an hour-long upload is definitely a fundamental bug for me and should be addressed.

**Comment by navid-zamani** [comment]
> my contact could not even stop the upload by restarting the device. Upload continued as soon as Signal was launched.

Then the definitely skipped the first "delete the message" step. Signal cannot start sending something after reboot, that does not exist in storagr anymore, can it?
If he wants to not lose it, he can send it to "Note to me", and forward that later.

**Comment by robo2bobo** [comment]
I am having the same problem.

I tried to send 19 images of about 3MB each (nearly 60MB in total) over a slow wifi connection. Signal tries to upload the images, goes up to around 40% and the upload procedure stops. 

Unfortunately, I am stuck there.

- I tried to force-stop the app and restart it, but it just keeps trying to upload the images all over again
- I tried to stop the upload procedure by long pressing, but there is no trash can/dumpster/bin icon, all I get is a bunch of smiley faces

It seems my only option is to completely uninstall and reinstall the app.

**Comment by alex-signal** [comment]
Deleting the message should cancel the upload. Is that not working properly?

**Comment by fabiomus** [comment]
@alex-signal Hi Alex, actually it works. The fact that the upload doesn't stop (the progress bar in the notifications keep showing that the upload is still progressing even after deleting the message) made me think that it wasn't working. It seems like the file is still completely uploaded but then it doesn't reach the recipient's phone. If this is the case, it's a bug since the upload should be stopped entirely.

Although deleting the message works (in the Android version, in the desktop version it doesn't work), that's not really that clear for the user and it also takes a little too much time. Let's pretend you press on the wrong file and it's fairly small (e.g. a photo), it takes a few seconds for it to be uploaded and it's likely it arrives to the recipient's phone before you manage to delete it, the photo can then be seen by the recipient for a few seconds and depending on the photo you've sent by mistake, things could turn ugly.
By making something like the following, it's so much clearer and also you can cancel it straight away.

![upload](https://user-images.githubusercontent.com/31598206/174814717-6eb8a566-c4d3-4797-856b-6ef5c7518bef.jpg)

**Comment by alex-signal** [comment]
I see where you're coming from! This has turned into a feature request, so I'm going to keep this closed, but I will definitely pass this feedback along to design and see what they've got to say about it :)
