### ISSUE TITLE
Original profile picture is not visible to my cintacts

### ISSUE THREAD

**Issue by AnukritiSinghh** [signalapp/Signal-Android#9833]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Only my Gmail profile picture is visible to all my contacts instead of the original profile picture that I put on Signal. I have tried changing my Signal profile picture several times, but it only shows my Gmail profile picture to everyone I talk to. I do not want it to sync with my Gmail or for everyone to look at my Gmail profile picture, if I am changing my Signal profile picture explicitly and I can see the new one on my device then why it isn't visible to everyone in my contacts?

**Actual result:** only Gmail profile picture is visible as my signal profile picture
**Expected result:** I am explicitly changing my signal profile picture but still it is showing my Gmail profile picture to others.

### Device info

**Device:** Samsung Galaxy J8, Xiomi redmi note 4
**Android version:** 9
**Signal version:** 4.65.2

**Comment by greyson-signal** [comment]
If you have a friend Alice, when showing you her avatar, we will prefer any photo you have set in your system contacts for Alice over her profile photo. This is a way to allow you to (1) change Alice's photo to something specific and (2) ensure that Alice appears the same way she does in other apps that also use the contact photo you have set.

I am assuming that your friends have you in their contacts, and that they have synced your photo from whatever you have in Gmail via Google contact sync.

We recently swapped it so we preferred profile photos instead of contact photos, but we got a ton of negative feedback, so we reverted it and are currently exploring some possibilities around a happy middle ground.

**Comment by Nisc3d** [comment]
I actually like it, when you prefere profile photos. I know there are people who like it the other way, so maybe an option for this would be nice.

**Comment by AnukritiSinghh** [comment]
This is interesting. I like the option where I can use the same picture of
my friend which I have set on contacts, but I know that not everybody will
be comfortable with this. Maybe you can come with ON/OFF option, if I set
it ON my profile picture will sync with the contacts picture and my friends
can then set the display picture as per their choice but if I set it OFF
everyone can see the display picture which I set on my signal account.

**Comment by subhodeeps** [comment]
Using the contact image instead of the profile picture is a terrible idea.

**Comment by Nisc3d** [comment]
@subhodeeps The latest beta includes an option and you can change it how you want.

**Comment by AnukritiSinghh** [comment]
Really?
That will be amazing

**Comment by osmafuda** [comment]
**Why** does my friend who uses iOS can see my picture that I put on the app but I can't see his? 

This idea is very bad, and it shouldn't be forced at all, it is enough for me to leave the application, which I just joined!!!
 I don't understand you 😕
