### ISSUE TITLE
Please Explain The Necessity of using Google's Firebase based "Face Detection" ML Library inside this Secure Messaging App.

### ISSUE THREAD

**Issue by shaswata56** [signalapp/Signal-Android#9888]
In this file -> [FirebaseFaceDetector.java](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/scribbles/FirebaseFaceDetector.java)

Please don't close the issue without a proper explanation.

**Comment by Cerberus0** [comment]
Hi @shaswata56,

This is not the right place for questions, comments, or feature requests, as stated in the project's [CONTRIBUTING.md](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#issues) and the [issue template](https://raw.githubusercontent.com/signalapp/Signal-Android/master/.github/ISSUE_TEMPLATE.md) that you appear to have deleted/missed. I suggest moving this discussion over to the [community forum](https://community.signalusers.org).

**Comment by shaswata56** [comment]
I've posted once in the community forum related to BitmapUtil.java and then the post got removed without any explanation. Since the devs are here, it'll be great to hear from them.
Since @alan-signal and @greyson-signal contributed to that file, I won't be able to hear from them in the community forum.

**Comment by greyson-signal** [comment]
We use it because it's the best offline face detection library available. It just gets a model and the rest is performed on-device. It's not reporting any metrics to Google. We've taken care to remove all the analytics pieces from our Firebase imports. I did a decent amount of research on this specific library before using it -- you're also more than welcome to do your own investigations and report any specific problems you find. Thanks!

**Comment by danvau7** [comment]
Wow this seems suspicious (but could also be nothing at all I want to stress). Since I'm here, would like to know why do sensitive debug logs get uploaded to https://debuglogs.org for download via a ZIP file?
