### ISSUE TITLE
[RTL] Screen Lock Inactivity timeout numbers misalign

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#9892]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Numbers get misaligned to the right:

![image](https://user-images.githubusercontent.com/34171942/77711328-4a706180-6fee-11ea-91bd-3c73fbe2d5ac.png)

### Steps to reproduce
1. Choose an RTL language from Signal settings
2. Settings -> Privacy -> Screen Lock -> Inactivity timeout

**Comment by jaredandrews** [comment]
@alan-signal This is an issue with the [TimeDurationPicker](https://github.com/svenwiegand/time-duration-picker) library which Signal uses. [Someone reported it in their issue tracker](https://github.com/svenwiegand/time-duration-picker/issues/20).

In the issue thread, a fix is shown, which I did apply to Signal with an okay result:
![Screenshot_20200804-010128_Signal](https://user-images.githubusercontent.com/1737565/89742077-b9fa6100-da64-11ea-8b3a-554662a0cdbe.jpg)

You can see that the margin between the numbers isn't right. [This is because there is a left margin applied to the numbers in the views onMeasure method.](https://github.com/svenwiegand/time-duration-picker/blob/master/time-duration-picker/src/main/java/mobi/upod/timedurationpicker/TimeDurationPicker.java#L321) I couldn't figure out a non-crazy way to apply a Signal side fix to this.

I thought about making a Pull Request with this partial fix applied on the Signal side by extending TimeDurationPickerDialog but I'm not sure you want it. This should really be fixed in the library unfortunately, the README states: "Note: I'm no longer supporting this library, as I dropped Android development in general."

I'm not sure how this is handled in the Signal repo. But `TimeDurationPicker` is only 5 files so it could be pulled into the Signal repo. Alternatively, the original repo could be forked.

**Comment by fumiakiy** [comment]
Hi @Xashyar, does this look too weird or maybe offending? Basically the dialog is forced to appear in LTR, except the OK/Cancel buttons at the bottom. In the LTR languages, the buttons are aligned to the right (end in LTR language), so in the RTL language they are mirrored to the left (end, in RTL language).

I know this is not the definitive resource but Samsung says that the time string should not be mirrored here [[1](https://developer.samsung.com/galaxy-watch-design/internationalization.html#:~:text=RTL%20should%20not%20be%20applied%20to%20time)]. So I thought this could be ok?

![Screenshot_1601672658](https://user-images.githubusercontent.com/28482/94970061-d7cacc00-04d1-11eb-89bd-f5a0256d77e4.png)

**Comment by Xashyar** [comment]
Hello @fumiakiy,
Yes, this is perfect (basically in the case of numbers in RTL, everything is the same as LTR), the only, albeit negligible, issue is that the numerals aren't localized.

I'm guessing that localizing numerals requires, some unnecessary logic overhead?

PTAL: https://community.signalusers.org/t/backup-passphrase-misrendered-in-rtl/

**Comment by fumiakiy** [comment]
Thanks! I'll be able to submit a pull request for this soon.

> issue is that the numerals aren't localized.

For this specific case, yes it will be a lot more difficult because the numbers are hard-coded in the file of the third party library.
