### ISSUE TITLE
Unrendered Characters Padding Senders Name in Notification

### ISSUE THREAD

**Issue by msoose** [signalapp/Signal-Android#9907]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Characters padding sender's name aren't rendered correctly on Pebble. 

### Steps to reproduce
- Use mentioned version of app
- Receive message from sender
- View Pebble notification

**Actual result:** Characters padding sender name not rendered correctly
**Expected result:** All characters rendered correctly. Prior to 4.68.2-ish this rendered correctly. I wasn't able to find the commit that made this change.

### Screenshots
![Imagepipe_0](https://user-images.githubusercontent.com/30473690/89430472-03ad1980-d6fc-11ea-9c55-d6b8c25ca52c.jpg)

### Device info
**Device:** Xiaomi Mi Mix 2S 
**Android version:** Android 10.0 / LineageOS 17.1
**Signal version:** 4.68.4

**Comment by greyson-signal** [comment]
Oh, how I miss the Pebble. This is likely due to a change where we put in guards to isolate bi-directional text from the surrounding text. It's unfortunate that the Pebble can't render those characters appropriately (they should be invisible). But I don't think we'll be making any changes to support this specific smartwatch.
