### ISSUE TITLE
Signal 4.36.2 (Android 4.1 - legacy) not receiving pictures

### ISSUE THREAD

**Issue by ka223** [signalapp/Signal-Android#9965]
Since yesterday, signal stopped receiving pictures (or other files) on version 4.36.2, which is the last version working on Android 4.1 devices.
All pictures are stuck in a  progress circle.

Pictures from other devices with 4.36.2 are working

Sending pictures from version:
4.36.2 -> 4.69.6    -    working
4.36.2 -> 4.36.2    -    working
4.69.6 -> 4.36.2    -    not working

**Comment by alan-signal** [comment]
Sorry, this version of Android has not been supported by Signal for about 17 months at this point. You will need to update Android and Signal to continue to receive files.

**Comment by ka223** [comment]
@alan-signal Regarding to the last changes, correct that it shut not work any longer?
This is not a server problem? The previous signal version 4.69.4 can also not send pictures any longer to 4.36.2.

... higher android versions unavailabe

**Comment by alan-signal** [comment]
I have closed the issue, because we will not be addressing this.

V4.36.2 is no longer supported. You should have been seeing a banner explaining that the version is out of date and will not support the latest Signal features.

```
The latest Signal features won\'t work on this version of Android.
Please upgrade this device to receive future Signal updates.
```

The new way files are sent is one of those latest features that the old version can not support.

> Sending from 4.66.8 -> 4.36.2 is still working.

This is because these version does not use the new method of sending files.

> higher android versions unavailabe

You may need to update your device in order to get on a later version of Android.
